### ISSUE TITLE
Bugsnag: Type error crash on table sort in stocktakes

### ISSUE THREAD

**Issue by sussol-invoices** [openmsupply/mobile#1000]
## Error in mSupply Mobile

**TypeError** in **MainActivity**
TypeError: undefined is not an object (evaluating 't[n].localeCompare')

This error is located at:
    in p
    in f
    in p
    in s
    in Connect(s)
    in Unknown
    in v
    in RCTView
    in f
    in RCTView
    in f
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in f
    in b
    in y
    in L
    in RCTView
    in h
    in C
    in k
    in v
    in P
    in Unknown
    in Connect(Component)
    in RCTView
    in n
    in Connect(n)
    in s
    in c
    in v
    in RCTView
    in RCTView
    in c

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5ce6b64381e082001a39f229?event_id=5ce6b643003d8cdbc3c40000&i=gh&m=ci)

## Stacktrace

    src/utilities/sortDataBy.js:26 - 
    src/utilities/sortDataBy.js:26 - sortDataBy
    src/pages/StocktakeEditPage.js:240 - refreshData

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5ce6b64381e082001a39f229?event_id=5ce6b643003d8cdbc3c40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Possibly related to #989, or similar area at least
