### ISSUE TITLE
Bugsnag: Crash viewing supplier requisition

### ISSUE THREAD

**Issue by sussol-invoices** [openmsupply/mobile#1002]
## Error in mSupply Mobile

**TypeError** in **MainActivity**
TypeError: undefined is not a function (evaluating 't.sorted(n,!u)')

This error is located at:
    in p
    in f
    in p
    in s
    in Connect(s)
    in Unknown
    in v
    in RCTView
    in f
    in RCTView
    in f
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in f
    in b
    in y
    in L
    in RCTView
    in h
    in C
    in k
    in v
    in P
    in Unknown
    in Connect(Component)
    in RCTView
    in n
    in Connect(n)
    in s
    in c
    in v
    in RCTView
    in RCTView
    in c

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cebfb4c37ebda0019f89ee9?event_id=5cebfb4c003e68b535d50000&i=gh&m=ci)

## Stacktrace

    src/utilities/sortDataBy.js:36 - sortDataBy
    src/pages/SupplierRequisitionPage.js:319 - refreshData

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cebfb4c37ebda0019f89ee9?event_id=5cebfb4c003e68b535d50000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Looks like the the supplier requisition page is trying to sort a null object (or at least not a realm list/object)
![image](https://user-images.githubusercontent.com/7684221/58442420-32fee880-813f-11e9-80eb-a8eebe222af9.png)

**Comment by andreievg** [comment]
these test should catch it: https://github.com/openmsupply/mobile/issues/1239
