### ISSUE TITLE
Stocktake reason saved on wrong row 

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1011]
Build Number: 2.3.3

Description:

1. Make a new stocktake and go from top to bottom replacing "Not counted" values with counts and adding reasons, all is well.
![Screen Shot 2019-05-28 at 17 13 00](https://user-images.githubusercontent.com/7684221/58452826-e0d4bc00-816c-11e9-82d5-1a1b0e7bd309.png)
![Screen Shot 2019-05-28 at 17 13 42](https://user-images.githubusercontent.com/7684221/58452833-e7fbca00-816c-11e9-8aa5-d65f6fe92d56.png)
2. Edit line 1 to have no diff. Reason will be reset to Not applicable.
![Screen Shot 2019-05-28 at 17 14 05](https://user-images.githubusercontent.com/7684221/58452834-eb8f5100-816c-11e9-885b-7063dd33d79e.png)
3. Edit line 1 again to have a diff, hitting next or selecting the next line manually. Selecting a reason will edit the next line's reason
![Screen Shot 2019-05-28 at 17 17 41](https://user-images.githubusercontent.com/7684221/58452859-082b8900-816d-11e9-92c9-aa3f2b588cd5.png)

Reproducible: Yes

Reproduction Steps: Description

Comments:

**Comment by Chris-Petty** [comment]
fixed in #1013

**Comment by joshxg** [comment]
# Testing
- [x] No matter how hard I try reasons are applied to the correct line or batch
