### ISSUE TITLE
Can dismiss the stocktake batch editor modal and can't get it back

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1012]
Build Number: 2.3.3

Description:
You can dismiss the stocktake edit modal by clicking on the grey background. When you do this it become hidden but you can't bring it back by clicking the buttons in the "BATCHES" column. You must reopen the stocktake.

Reproducible: Yes

Reproduction Steps:
1. Open a stocktake
2. Open batches modal on a line
3. Press on the grey area near the OK button
4. Modal dismissed
5. Cannot not reopen as had been done in step 2

Comments:
I think there is a boolean prop to disable dismissing the modal component by clicking on background. Without it, I think the page state has the modal as still visible, but the modal's own internal state thinks otherwise.

**Comment by joshxg** [comment]
![image](https://user-images.githubusercontent.com/35858975/58589975-32895d80-82b7-11e9-8ff7-f1ae4ca08f8a.png)

For some reason I added all these props... basically `backdropPressToClose={true}` needs to be set to `false`.

**Comment by Chris-Petty** [comment]
@joshxg pretty much exactly that 👍. If false is the default, just remove the line.

**Comment by joshxg** [comment]
Fixed by #1071
