### ISSUE TITLE
Can't cancel the reason selection on stocktake item

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1015]
## Describe the bug
On a stocktake with reasons, if there is already a reason on a line and you press it to view it, you must select a reason again, although the current most common (across the batches) will be highlighted.

Problem is, if the batches have been edited individually this will overwrite all batches to have the same reason and there is no way to get around this currently.

### To reproduce
1. Click on a reason cell in stocktakes that already has a reason
2. Cannot cancel the modal that comes up
3. If you click a row it'll update all the batches regardless of what they were

### Expected behaviour
1. Have a cancel button. Disable it if reasons are compulsory and the item doesn't have any yet
2. Perhaps it should only update batches that don't have a reason yet (and should have one)?

### Version and device info
 - App version: 2.3.3

**Comment by joshxg** [comment]
I think both the expected behaviours are right. I think this should involve bringing the `GenericChoose` component from vaccines into development - might do a new issue for that and do that before this is done

**Comment by joshxg** [comment]
Fixed by #1071
