### ISSUE TITLE
Google play services breaking changes

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1030]
## Describe the bug

Google play services had a release with breaking changes, migrating to androidX:
- https://android-developers.googleblog.com/2018/05/hello-world-androidx.html
- https://developers.google.com/android/guides/releases

I believe RN 0.60 supports androidX, we are not using RN 0.60 (last I checked, RN0.60 is 64bit, realm does not support 64bit (couldv'e changed by now). Some dependency is relying on google play services.
- https://github.com/facebook/react-native/issues/25307

This prevents a merge in the android manifest files.

### To reproduce
1. Clone the repo
2. `yarn build` or `react-native run-android`
3. No work

### Expected behaviour
Work

### Version and device info
 - App version: 2.3.5

### Additional context
We need to downgrade google play services (for now, as an immediate solution, as nothing can be done on mobile with this issue) in order to build the app, I believe. I'm not 100% on all of this, I think a better solution is to find the exact dependency causing problems, upgrade realm and RN again etcetc.

Error when trying to compile
```
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:13:5-35:19 to override.
```

**Comment by andreievg** [comment]
@joshxg, building works now right? if so, can you please move to done

**Comment by andreievg** [comment]
@joshxg, same with, https://github.com/openmsupply/mobile/pull/1045

**Comment by joshxg** [comment]
Building works on my computer, sure. That's not enough for me to be confident - if you've built it since then feel free to tick off the test!
