### ISSUE TITLE
Simplified english localisation

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1033]
## Describe
Require a simplified version of english for localisation, exluding words like `requisition`, replacing it with `order` etc.

### Additional context
This will be for use in Vannutatu

**Comment by katherine-sussol** [comment]
@joshxg Hmm I see this one didn't get merged, is this something still something we're looking to do?

**Comment by joshxg** [comment]
.. 🤷  soz

**Comment by katherine-sussol** [comment]
> .. 🤷 soz

That's what I look like when reading a lot of these issues! 😹
