### ISSUE TITLE
Strange spacing in modalStrings

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1036]
## Describe the bug
In `modalStrings.js`, some of the strings have strange spacing when displayed on mobile (Was on a tablet and didn't take a screenshot, oops). There is sometimes what looks like a tab space between two words.

### To reproduce
1. Go to a customer requisition
2. Click on finalize
3. See error in modal

### Expected behaviour
For there not to be strange spacing

### Version and device info
 - App version: 2.3.4
 - Tablet model: Lenovo Tab4 10

### Additional context
I think it is due to the multiline strings. I don't see the harm, personally in just having these strings exceed the standard limit of 100 characters, personally.

**Comment by joshxg** [comment]
Being fixed with #1043

**Comment by wlthomson** [comment]
This should probably have it's own dedicated PR, if it's not already fixed. Otherwise, we can go ahead and move it to DONE.
