### ISSUE TITLE
Odd modal spacing when opening while keyboard is open

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1037]
## Describe the bug
When opening a modal (i.e. clicking finalize, or any other action which opens a modal whether it is in requisitions or stocktakes), if the keyboard is opening when the modal is mounted, the spacing is odd forcing the vertical height downward

### To reproduce
1. Go to requisition / stocktakes 
2. Click on a cell to open the keyboard
3. Press Finalize

### Expected behaviour
The modal should always be consistent

### Version and device info
 - App version: 2.3.4
 - Tablet model: Lenovo Tab4 10

### Additional context
N/A

**Comment by joshxg** [comment]
This is from the `Modal` component that we use.

We use this package for full screen modals as well as smaller `popover` views. I can't find a suitable replacement for `react-native-modalbox` which includes click through and all of our use cases. We most likely need to build our own to fix this?

**Comment by Rebecca367** [comment]
When cell or keyboard not been activated, modal is in the middle.
![Screen Shot 2020-01-17 at 10 53 45 AM](https://user-images.githubusercontent.com/57238075/72566509-cf693b80-3918-11ea-82ea-fabeea30f2aa.png)
When cell been pressed then modal is in placed in the middle down side.
![Screen Shot 2020-01-17 at 11 03 52 AM](https://user-images.githubusercontent.com/57238075/72566693-31c23c00-3919-11ea-9f36-257bd81f9f10.png)
Maybe it's related either cell or keyboard? 
@joshxg @Chris-Petty @diegoevangelisti do you have any thoughts?

**Comment by joshxg** [comment]
Yeah as per the description, if the keyboard is opening (or open?) the spacing is forced downwards. This could possibly be fixed by using the native modal component rather than the package we are using (maybe, just a guess). Or possibly by manipulating the keyboard in other ways to ensure the keyboard is closed

**Comment by joshxg** [comment]
Fixed a while ago
