### ISSUE TITLE
French localization is incomplete

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1041]
## Describe the bug
As seen here https://github.com/openmsupply/mobile/issues/889#issuecomment-507093202 - french translations are not being used and/or are inconsistent.

### To reproduce
1. Go to Language modal, select french
2. Click on create requisition [With a program defined]
3. See error

### Expected behaviour
To be translated correctly

### Version and device info
 - App version: 2.3.4

### Additional context
Translations are there, localizations have been put in place, but I have done it incorrectly. Should also check the consistency in the translations, i.e. capitalization and fit correctly etc.

**Comment by DhanyaHerath** [comment]
Also the 'Log in' and 'Log out' translation strings still have options ("disconnector o disconnexion")

**Comment by joshxg** [comment]
Closed by #1048
