### ISSUE TITLE
Hide/Show overstock button should default to show overstock when finalised

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1042]
## Describe the bug

UPDATE: This issue should default the show/hide overstock toggle to show overstock when viewing a finalised requisition.

The show/hide overstock button is usable when a requisition is finalized and is a little confusing. This button hides the rows in the requisition which have stock that is over the MOS, defined by the order type chosen for the requisition.

### To reproduce
1. Go to a finalized, program requisition
2. Click on hide/show overstock
3. See error

### Expected behaviour
Shouldn't be usable

### Version and device info
 - App version: 2.3.4
 - Tablet model: All
 - OS version: All

### Additional context

@DhanyaHerath @Chris-Petty @wlthomson @nmadruga

Looking for opinions

Not 100% sure if the expected behaviour should be that this is disabled. I think that it should be disabled, but looking for feedback

**Comment by Chris-Petty** [comment]
I think step 3 isn't actually an error right? It's just a UX problem?

I agree that hiding the buttons on finalised and not filtering the list would be better. That said, I'm no user!

**Comment by DhanyaHerath** [comment]
@joshxg @Chris-Petty yeah, not actually an error - this just came from when I was testing. Finalised a requisition with only over-stocked items (tbf probably shouldn't have been doing that), and got confused for a second when it looked like I'd created an empty requisition.

I think all lines should be showing at the start (so default to show), but having it enabled might be helpful if you wanted to look back at historical data and see that you were ordering all overstocked items?

**Comment by diegoevangelisti** [comment]
> @joshxg @Chris-Petty yeah, not actually an error - this just came from when I was testing. Finalised a requisition with only over-stocked items (tbf probably shouldn't have been doing that), and got confused for a second when it looked like I'd created an empty requisition.
> 
> I think all lines should be showing at the start (so default to show), but having it enabled might be helpful if you wanted to look back at historical data and see that you were ordering all overstocked items?

@DhanyaHerath based on your thoughts and other previous comments, I am going to try to fix this issue setting the show/hide overstock toggle to default show overstock (now it is still hide), unless anyone has a different opinion? @Chris-Petty @joshxg

**Comment by joshxg** [comment]
@diegoevangelisti do it!

**Comment by diegoevangelisti** [comment]
Both toggles are taking the state of showAll (boolean) to hide/show (which it is working when pressing the buttons). 

https://github.com/openmsupply/mobile/blob/4b68400858316c6071754ed68d4e2d11d3c2f7b9/src/pages/SupplierRequisitionPage.js#L189-L203

Apparently, setting the default prop for showAll as true (see line 325) will have to make the expected change, but it is not.

https://github.com/openmsupply/mobile/blob/4b68400858316c6071754ed68d4e2d11d3c2f7b9/src/pages/SupplierRequisitionPage.js#L323-L326

After setting showAll: true, I am getting the same result:

![Screen Shot 2019-12-12 at 12 58 00 PM](https://user-images.githubusercontent.com/32987464/70671131-db415c80-1cdf-11ea-891e-2191b2e4b7f1.png)

@joshxg any thoughts? Maybe create an action that executes onPress: onShowOverStocked when rendering this page?

**Comment by joshxg** [comment]
- The initial state for `SupplierRequisitionPage` (And basically all other pages) come from `getPageInitialiser.js` 
- Setting `showAll: true` won't be quite enough, you will also need to ensure the `data` property has the correct initial data.

**Comment by diegoevangelisti** [comment]
> @diegoevangelisti
> 
> * The initial state for `SupplierRequisitionPage` (And basically all other pages) come from `getPageInitialiser.js`
> * Setting `showAll: true` won't be quite enough, you will also need to ensure the `data` property has the correct initial data.

Thanks, that worked! In fact, changing `showAll` in `SupplierRequisitionPage`was not necessary at all, all changes were made in `getPageInitialiser.js`. Creating the PR now. Cheers

**Comment by joshxg** [comment]
Closed by #1676

**Comment by Rebecca367** [comment]
## Testing
success!
Steps to reproduce or otherwise test the changes of this PR:

- [x] Create a new program requisition (the program should have over stock items, otherwise modify quantities performing a stocktake).
- [x] Finalise the requisition
- [x] Check that the option `Show over stocked items` is set as default and items are visible
- [x] Press `Hide over stocked` and check toggle works.

Attention: Remember to add items that are over stocked, otherwise the toggle will not make any sense (all items will be shown either hide/show is pressed).
