### ISSUE TITLE
Upgrading dependencies part two

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1050]
## Describe
- AsyncStorage within `react` is deprecated, want to replace it with @react-community/async-storage. This will enable upgrading `redux-persist` with no issues once 6.0 is released.
- Want to upgrade realm. 
- Want to remove the following devDependencies (and just start fresh with a new testing framework)
    - `sinon`
    - `react-native-mock`
    - `enzyme`
    - `expect`
    - `expect-jsx`
    - `react-addons-test-utils`
    - `promise-sync-es6`
    - `flow-bin`
- upgrade any remaining devDependencies
### To reproduce
N/A

### Expected behaviour
N/A

### Version and device info
 - App version: 2.3.4
 - Tablet model: All
 - OS version: All

### Additional context
Have already upgraded many dependencies in the develop branch, this will finish off upgrading/removing.

**Comment by joshxg** [comment]
Closed by #1051

**Comment by wlthomson** [comment]
## TESTS

- [x] Can build and run the app
- [x] Runs as per normal
- [x] Specifically, testing realm creating of records
- [x] Runs on both 32 bit and 64 bit architectures (using either x86 or ARM)
