### ISSUE TITLE
Add uninstall script to dev_scripts

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1053]
## Describe 

During development it is often necessary to reinitialise the mobile app. It would be helpful to have a script to reduce overhead involved in repeated manually uninstallation.

# To reproduce

N/A.

# Expected behaviour

N/A.

# Version and device info

- App version: 2.3.4
- Tablet model: All
- OS version: All

# Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #1054

**Comment by Chris-Petty** [comment]
Reviewed the PR and didn't read the issue. If the issue is reinitialising the app then the better script would just wipe the app data, not uninstall it?

**Comment by joshxg** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Uninstall the app using `./dev_scripts/uninstall.sh`
