### ISSUE TITLE
Sync stalls when receiving sync delete records for records that don't exist 

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1072]
## Describe the bug
When mobile is sent a "delete" sync record, but the record to delete doesn't exist in mobile's data, mobile sync stalls.

### To reproduce
Steps to reproduce the behaviour:
1. On primary server send out delete records for something that a mobile sync site doesn't have.
2. Try sync the mobile device
3. Hangs, starts processing only 10 records at a time.

(I'm just inferring the above, I'm told this has been a problem)

### Expected behaviour
Mobile should gracefully ignore them. Bonus would be logging the event, perhaps on bugsnag for the time being.

### Version and device info
 - App version: <= 2.3.4

### Additional context
@adrianwb wrote elsewhere:
>2. deleted the unsent bad sync records from the cloud server before they infected any other sites, and create "delete" sync records for those sites which had already been infected. It appears that mobile doesn't like getting "delete" sync records for a record which doesn't exist - this seems to make it process only 10 sync records at a time, but not actually apply any of them?. Desktop ignores such records, although  it does log them.

**Comment by joshxg** [comment]
@adrianwb 

I haven't been able to recreate this at all, what am I doing wrong?

deleting and creating done through code trying not to mess with sync queues

Have tried, multiple times each:

**1**
- Created 5000 period records on desktop
- synced them to mobile
- deleted them on mobile
- deleted them on desktop
- synced delete records

**2**
- Created a period record on desktop
- Synced it to mobile
- deleted it on mobile
- deleted the same period on desktop
- created 5000 period records on desktop
- synced mobile

**3**
- Created a stock take on mobile
- synced
- deleted it on mobile
- deleted it on desktop
- put every item, transline, transact, requisition, requisition line, stock take, stock take line (basically every table in the sync out queue)
- synced mobile

**4**
- created a stocktake on mobile
- synced to desktop
- delete the stocktake on mobile 
- Added a delete record for a stock take with sync_generate_sync_record
- created 5000 periods
- synced mobile


The code for handling sync records starts here:
https://github.com/openmsupply/mobile/blob/ff2f47a676955afa1753e8564ae90f10dfc85632/src/sync/incomingSyncUtils.js#L722-L746

and ends here for delete records:
https://github.com/openmsupply/mobile/blob/master/src/database/utilities/deleteRecord.js

I can't see anywhere in the code where this could be causing issues, either

**Comment by andreievg** [comment]
Some back ground info (from email)

AB - #5 - fix mobile to allow incoming sync delete records when the record doesn't exist, and ignore/log them rather than barfing

AE - I just looked at some code, mobile should handle records that don’t exist gracefully, from reading the code -> it doesn’t allow is deletion of foreign constrained record. In Mobile trans line has to have item line (even in desktop schema it’s a relation, not sure if it’s enforce though). So I would assume that item lines that were deleted where associated with a trans line ?

AB - Ah, that would explain it, so we'd need to re-link the related trans lines first to point to the right item line, before deleting the dud one. From my testing, it seemed that trying to delete a related item line stopped sync on mobile for that batch of 10, so maybe need to check that?

**Comment by joshxg** [comment]
Ok - irrelevant now, but putting it down for some reason: if all details could be added to issues from emails, trello, google docs, telegram, email and skype it'd be less frustrating.

If there is any more information regarding the deletion? Were delete records for `item_line` records sent, and they were the ones causing issues? What exactly was the issue, there is descriptions of barfing and sync stopping for a batch - did sync stop completely?

What I can understand is that we need to bugsnag a record that comes in through incoming sync which doesn't exist, or that can't be deleted for some reason?

**Comment by adrianwb** [comment]
> 
> 
> Ok - irrelevant now, but putting it down for some reason: if all details could be added to issues from emails, trello, google docs, telegram, email and skype it'd be less frustrating.
> 
> If there is any more information regarding the deletion? Were delete records for `item_line` records sent, and they were the ones causing issues? What exactly was the issue, there is descriptions of barfing and sync stopping for a batch - did sync stop completely?
> 
> What I can understand is that we need to bugsnag a record that comes in through incoming sync which doesn't exist, or that can't be deleted for some reason?

What I observed was that, when I sent a batch of (manually created) sync delete records for item lines which were still related to an existing trans line on mobile, mobile sync would look like it was processing 10 records (the queue would go down by 10) and then sync would stop; if I did another manual sync, it would process the next 10 and then stop. When I looked at stock in mobile again, the item lines that I was trying to delete were still there (which makes sense, given @andreievg's explanation). I didn't leave mobile long enough to see if it would do the same thing if I just let it sync normally, and I didn't try to add some normal sync records in the middle of the dud ones to see if they would be processed ok, or if the whole batch of 10 would be rejected because of one dud. Hope that helps...

**Comment by wlthomson** [comment]
> Ok - irrelevant now, but putting it down for some reason: if all details could be added to issues from emails, trello, google docs, telegram, email and skype it'd be less frustrating.
> 
> If there is any more information regarding the deletion? Were delete records for `item_line` records sent, and they were the ones causing issues? What exactly was the issue, there is descriptions of barfing and sync stopping for a batch - did sync stop completely?
> 
> What I can understand is that we need to bugsnag a record that comes in through incoming sync which doesn't exist, or that can't be deleted for some reason?

Will coming in with a DevOps sadface 😢. Not a moan, understand that without a bit more of a process for design, emails are prob one of the best ways to discuss stuff. Just to remind that our goal is to make GitHub the source of truth for all dev related stuff, so ideally we want to work towards that. Let me know if there are reasons you think we need to use other sources of info (e.g. email) and we can see if we can find a way of incorporating these into our GitHub templates etc.

**Comment by joshxg** [comment]
More investigating:

1.
- Create an `ItemBatch` in mobile, sync to the server
- Create a delete syncout record on the server
- Create 10,000 period records
- Immediately start syncing from mobile (such that all 10,000 records aren't created yet)

2.
- Created 10,000 `Transaction`+`TransactionItem`+`TransactionBatch`+`ItemBatch` records on mobile
- Synced to desktop
- Created delete records on desktop
- Synced to mobile

3.
- Created 10,000 `Transaction`+`TransactionItem`+`TransactionBatch`+`ItemBatch` records on mobile
- Synced to desktop
- Created delete records on desktop
- Created 50,000 period records on desktop
- Synced to mobile


I still cannot recreate this at all and `ItemBatches` are deleted correctly(incorrectly?)

**Comment by andreievg** [comment]
What happens if you try to delete an ItemBatch that is associated with a transaction, and then try to finalise that transaction in mobile ?

**Comment by joshxg** [comment]
You can't open the transaction, do you mean through code?

**Comment by adrianwb** [comment]
@joshxg have you tried simply creating a delete sync out record for an item line (and sending it to the mobile site) which is linked to by a trans line on the mobile store. And yes, sync didn't stall forever, just for that one cycle (presumably10 records at a time).

**Comment by joshxg** [comment]
@adrianwb sorry the first attempt in my second batch wasn't correctly described - I did link the `ItemBatch` to a `TransactionBatch`. Realm has no problem deleting `ItemBatch` records related to `TransactionBatch`'s, so the behaviour doesn't change

**Comment by adrianwb** [comment]
@joshxg thanks for the clarification - I'll give it one last shot here to see if I can recreate somehow! If mobile could process messages, that would be a cleaner way to do stuff like this remotely - @andreievg??

**Comment by joshxg** [comment]
@adrianwb I was just talking about that the other day, but to be fair if sureMDM was working, pushing a patch with migration code is quite easy and also a lot safer?
