### ISSUE TITLE
Handling placeholder batches

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1073]
## Describe the bug
Not 100% on place holder lines yet so can't elaborate too much. I believe placeholder lines aren't supported in mobile (?) so just looking to keep desktop happy:

- Desktop doesn't allow "none" as the batch name and there is logic revolving around using this batch name
- `[trans_line].type` is now used to flag place holder lines

### To reproduce
1. Sync a line with "none" as the batch name

### Expected behaviour

- Don't allow "none" as a batch name

options:
- Modal on naming a batch "none" and set the batch name to `""`
- Outgoing sync changing the batch name to some other arbitrary value (causes inconsistent data)
- When a batch name is set to `"none"`, rename it to `"n0n3"` - best solution

- Sync `[trans_line].type`

Options
- add to incoming/outgoing sync 
### Version and device info
 - App version: all
 - Tablet model:all
 - OS version:all

### Additional context
`"none"` is handled case insensitively

**Comment by Chris-Petty** [comment]
Related to this serverside: https://github.com/sussol/msupply/issues/3789

I originally wrote out the issue here, but after reading Adrian's comments I began to think that the problem is that desktop is filtering/reserving `[trans_line]batch:="none"` when the newer `[trans_line]type:="placeholder"` was meant to have replaced this functionality since mSupply v3.5. @adrianwb @craigdrown yea nah?

I don't think polluting mobile's code base with a superseded means of handling placeholders is a good idea.

**Comment by joshxg** [comment]
Since this had only just been a problem recently I had assumed `[trans_line]type` was added recently. I think you're right, since the current mobile is not backwards compatible anyway it does seem like the wrong choice to add irrelevant backwards compatibility, unless I'm missing something

**Comment by Chris-Petty** [comment]
The part missing is that a new system was put in place, but the code base wasn't actually migrated to use it everywhere. So while that system has been in for yonks, there is still core areas that use the old "none" way for placeholders.

**Comment by craigdrown** [comment]
If there is no batch, writing "none" is superfluous- consider it user training and data entry validation ;-)

**Comment by joshxg** [comment]
As much as I agreed initially, from a UX POV it is actually a bit of a problem IMO. The [Nielson](https://www.nngroup.com/articles/ten-usability-heuristics/) heuristics are a pretty good guideline and I think following from that, enforcing a particular naming convention, if not completely obvious is not a great idea without providing feedback for the error and to why something happened (reverting the name back to an empty string?). Although not horrible to throw a modal up saying "you can't use 'none'", it's still intrusive. Also it's pretty presumptuous to claim using "none" is not useful for anyone, anywhere, anytime.

Last one: The discussion already points to a deeper problem than fixing a small naming thing as I think @Chris-Petty points out. Making changes to fix a problem but not fixing it properly is pretty horrible for everyone. Do we have to stop in-directly encouraging it by sweeping it under the rug, at some point?

**Comment by Chris-Petty** [comment]
The following is really shaving the yak, discussing finer implications of how to handle this when the root problem is server side, and this does very little to resolve that. So **TL;DR:** I still don't think we should do this feature.

@joshxg I really dig that article. Should share it in mSupplyDev chat.

In stocktakes we often pre-populate batch with "stocktake_X" when generating batches. This existing behaviour negates a blank batch number representing "unrecorded" state as much as putting in "none" does. So blocking "none" really doesn't give us much.

> Also it's pretty presumptuous to claim using "none" is not useful for anyone, anywhere, anytime.

I do think the more often case is going to be people entering "none" to represent a blank/unavailable/unreadable batch number is certainly going to be higher than a batch actually having a number "none". Unless they really need to keep track of unrecorded batch numbers separate from unavailable batch numbers. In which case the answer is I agree it's better to do nothing. But for every person entering "none" they just as well might be entering "n/a", "neg", "unreadable" etc.

So it'd be a lot of design and implementation (or not, just throw UX out the door) all for dubiously singling out "none" 'cause server-side has an ancient bug that needs fixing. No bueno.

**Comment by craigdrown** [comment]
@Chris-Petty  @joshxg  searching for "none" in our 4D code returns 321 hits over maybe 60 methods. You 2 decide which of you gets assigned the issue to remove all reference to it. Remember to buy Alain a present for the amount of testing you made him do ;-)

**Comment by andreievg** [comment]
@Chris-Petty @joshxg @craigdrown 

Can we reach a compromise here, on outgoing sync, convert from 'none' to '' (ItemBatch and TransactionBatch) and explaining why in comments there only. This way we don't need to touch UI. If tablet is re-synced the batch name will be none : ).
* But the info won't be consistent between desktop and mobile ! <- this would only be for a minority of cases (very rare), and really, what is the difference between 'none' and '' in terms of batch name ? Once again very rare for someone to filter in reporting by batch name 'none', and when report is printed, 'none' would be equivalent to ''

**Comment by joshxg** [comment]
I'm just throwing in opinions, happy to do whatever is best. I do feel having inconsistent data between the two databases (for the same record) is the worst result. I think interrupting the user with a "Sorry! you can't do that, choose another name" is the best option, it will only really interrupt anyone once

**Comment by craigdrown** [comment]
@Chris-Petty @joshxg @andreievg  - I don't really mind how it's handled, although I am sceptical that rewriting a whole bunch of mSupply code at this time is a good idea (regressions potential), and was just making the point that purity comes with a high cost sometimes ;-)  [For context, I would think that around Edwin's time on conversion to 3.5 someone with clue said "It's naff to handle special cases with a reserved word- we should use a field" (or more likely just made a field), but didn’t / forgot to update the code to use the new field.  (Actually 91 hits for "placeholder" so we did some of the work...)

**Comment by andreievg** [comment]
> I'm just throwing in opinions, happy to do whatever is best. I do feel having inconsistent data between the two databases (for the same record) is the worst result. I think interrupting the user with a "Sorry! you can't do that, choose another name" is the best option, it will only really interrupt anyone once

Sure, but we would need to remember to add this functionality to supplier invoices (if we ever expose batches there) and vaccine module (if we allow batch names to be changed there). Also how to handle existing batches with 'none' set (i.e. if stocktake is done or if they are issued), could do it with migration I guess. Still leaning towards outgoing sync, personally.

**Comment by Chris-Petty** [comment]
> @Chris-Petty @joshxg @andreievg - I don't really mind how it's handled, although I am sceptical that rewriting a whole bunch of mSupply code at this time is a good idea (regressions potential), and was just making the point that purity comes with a high cost sometimes ;-) [For context, I would think that around Edwin's time on conversion to 3.5 someone with clue said "It's naff to handle special cases with a reserved word- we should use a field" (or more likely just made a field), but didn’t / forgot to update the code to use the new field. (Actually 91 hits for "placeholder" so we did some of the work...)

Was that a chapter in The Phoenix project?

> Sure, but we would need to remember to add this functionality to supplier invoices (if we ever expose batches there) and vaccine module (if we allow batch names to be changed there). Also how to handle existing batches with 'none' set (i.e. if stocktake is done or if they are issued), could do it with migration I guess. Still leaning towards outgoing sync, personally.

That's a bit too behind the scenes hacky for me, though it would work. I'd rather a UI feedback saying don't do it as Josh suggests. Keeps user informed and data consistent. One day when server is fixed, it's also in our face on mobile and can be removed.

I'd suggest using a toast that just says "None" is reserved in batches, will have to check stock takes and supplier invoices (and anywhere it is editable in vaccines as Andrei pointed out).

**Comment by adrianwb** [comment]
The more I think about it, the more I lean towards just addressing this problem server side, and leaving mobile as-is:

- the root cause is actually outdated/inconsistent code on the server => there is no longer any actual need to disallow "None" batches in desktop or to treat them as a special case, as we have the "placeholder" line type to do that now (the ledger code uses "placeholder" already but it _still_ also looks for "None" batches)
- telling users that they can't do something that isn't obvious (and that they've already done) is a nasty UI experience

**Comment by joshxg** [comment]
Cool, so no changes? I guess I'll close this

**Comment by Chris-Petty** [comment]
I agree with @adrianwb. @bijaySussol is assigned and already started it'd seem!

Getting into it, bijay spotted desktop falling victim as it is, see here: https://github.com/sussol/msupply/issues/3840

The server side implementation is dodgy as it is and needs to be addressed.

I can see the case for saying that we should filter out and give users feedback if they're doing something silly regardless. That should be given some proper thought on how we want to achieve that because there is definitely more than the string "none". Not to mention localisation.
