### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#1075]
## Description

More French translations supplied by the team in Côte d'Ivoire

In   English | Traduction en Français
 - [ ] Programme   order | Commande par programme
 - [ ] General   order | Commande Générale
 - [ ] Last successful sync | Date de dernière   synchronisation
 - [ ] 15 :36   July 22, 2019 | Le 22 Juillet 2019, 15 :36
 - [ ] Order type | Type de commande
 - [ ] Hide   over stocked | Masquer les produits surstocké
 - [ ] Show   over stocked | Afficher les produits surstocké
 - [ ] Progamme stocktake | Inventaire par   programme
 - [ ] Général   stocktake | Inventaire général

Source documents:
[Traduction mSupply mobile 2407.docx](https://github.com/openmsupply/mobile/files/3434096/Traduction.mSupply.mobile.2407.docx)

[News Translate Tablet 2407.xlsx](https://github.com/openmsupply/mobile/files/3434097/News.Translate.Tablet.2407.xlsx)

**Comment by joshxg** [comment]
Have added these into #1041 - I didn't know what to do with the date one so I just pretended it wasn't there, some were already in

**Comment by mark-prins** [comment]
> some were already in

they are using a slightly older version of mobile - might be why some were already done but they haven't seen the changes yet

**Comment by joshxg** [comment]
Closed by #1048

**Comment by wlthomson** [comment]
## TESTS

- [x] Programme order | Commande par programme. **PASSED (but text looks a bit ugly and is not centred correctly?)**.
- [x] General order | Commande Générale. **PASSED**.
- [x] Last successful sync | Date de dernière synchronisation. **PASSED**.
- [x] 15 :36 July 22, 2019 | Le 22 Juillet 2019, 15 :36. **PASSED**.
- [x] Order type | Type de commande. **PASSED**.
- [x] Hide over stocked | Masquer les produits surstocké. **PASSED**.
- [x] Show over stocked | Afficher les produits surstocké. **PASSED**.
- [ ] Progamme stocktake | Inventaire par programme. **FAILED (reads same as general stocktake)**.
- [x] Général stocktake | Inventaire général. **PASSED**.
