### ISSUE TITLE
CustomerInvoicePage new DataTable

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1090]
## Is your feature request related to a problem? Please describe.

Data table is being rewritten. Context is CustomerInvoicePage is good starting to make sure it's up to par with old.

## Describe the solution you'd like

Rewritten using hooks API rather than class API. Uses new VirtualisedList based data table.
Review GenericPage and usage of GenericTablePage.

## Describe alternatives you've considered

None.

## Additional context

__Add any other context or screenshots about the feature request here.__

**Comment by joshxg** [comment]
I think it's worthwhile, since we're refactoring to:

- Try to consolidate logic in all the 'pages' which are exactly the same, more or less to also give more flexibility for the inevitable customizations. i.e a better way to handle:
    - columns
    - cells
    - modals

Lots of options. E.g. for columns: Each page could be passed their columns through redux/navigator props which are a composition of objects created and determined by the current active modules.

Although I'm not sure how much time we have

**Comment by Chris-Petty** [comment]
> I think it's worthwhile, since we're refactoring to:
> 
> * Try to consolidate logic in all the 'pages' which are exactly the same, more or less to also give more flexibility for the inevitable customizations. i.e a better way to handle:
>   
>   * columns
>   * cells
>   * modals
> 
> Lots of options. E.g. for columns: Each page could be passed their columns through redux/navigator props which are a composition of objects created and determined by the current active modules.
> 
> Although I'm not sure how much time we have

I think we don't have time, but good point. Related to #1092 potentially

**Comment by Chris-Petty** [comment]
More specifically regarding redux/nav props, we should evaluate using redux more extensively and revisit nav -> out of data table scope IMO.

**Comment by joshxg** [comment]
definitely out of scope. I agree using redux more extensively is a good idea though. Primarily for passing data which doesn't change frequently as it can cause quite a lot of performance issues if the data starts to be mutated a lot

**Comment by joshxg** [comment]
Closed by #1108

**Comment by Chris-Petty** [comment]
@joshxg I originally intended to leave this open till customer invoice page is properly done, styles and all. Basically when it's got the final flavour of refactor on it.
