### ISSUE TITLE
Consistent React hooks code

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1092]
@Chris-Petty @sworup @Stanzzer @DhanyaHerath @mark-prins  @andreievg @wlthomson 

## Description
With React hooks being usable now in the code base and with them being awesome and how they are quite a big feature that does change how regular components are written quite a bit, I think it would be good to just have a discussion on a consistent way to use them before we end up with a mess

### Context
Hooks are designed so that code can be more easily shared between components. To share the code a consistent style/way might make this easier.

For example: `useReducer` hook is awesome for managing certain components with complex/multiple state manipulations, but comes with a bit of extras (potentially) i.e. action creations, actions and the reducer itself.

Also `CustomHooks`

Even if the code isn't going to be shared, it's nice to be able to extract out a reducer/actions from a component, but that can be annoying for checking out the code if there are many different styles throughout the code base for action creators etc.

## Design discussion

Questions to start:

- File structure
    - does it need to change overall? i.e. ducks/feature first
    - tactics for handling components written using hooks, where do reducers/actions/creators/selectors/custom hooks go

- Hooks
    - Consistent 'style' for writing hooks - i.e. should you always use action creators for actions (so that switching files becomes less needed when checking out code)

I'm not suggesting strict guidelines, but I think a discussion about how to try to make this somewhat consistent would be helpful, especially for me

**Comment by Chris-Petty** [comment]
@joshxg I think we should go over this a bit when doing broader refactoring for new data table in pages
