### ISSUE TITLE
Foreign Item Lines

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#1102]
## Describe the bug

Before there was a fix for #1062 it was possible to sync foreign item lines to mobile store, this cause a few issue in IC. 
Foot runner code was originally executed that caused deletion of foreign item lines, causing #1088
We don't actually know if some of the sites that have not been synced yet need to be fixed by foot runner code.

### Proposed solution

Do migration code (specific for IC) that looks through all item batches, identifies them as foreign and deletes them. Followed by running this migration code https://github.com/openmsupply/mobile/pull/1094

### Version and device info

- App version: 2.3.0

### Additional context

A special RC version should be made for this migration code (2.3.5-RC1) <- maybe better named

#### How to find foreign item line ?

* First transaction is supplier invoice (finalised on)
* First transaction is inventory adjustment coming from a stock take where snap shot quantity was 0 (can deduce this through code)

**Comment by andreievg** [comment]
I'll branch from #1094

**Comment by GaryWilletts** [comment]
Err, what's the bug? The description doesn't make it very clear (unless I'm being very dense this morning which is a distinct possibility).

**Comment by andreievg** [comment]
There is an email chain about it, it's the IC related data issue that was being fixed with foot runner code, I'll forward email to you if you not on it

**Comment by joshxg** [comment]
Closed by #1104 - into IC special
