### ISSUE TITLE
Develop branch APK Size

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1107]
## Is your feature request related to a problem? Please describe.

Currently in the development branch the APK size has been bumped up to 33Mb. This is probably a little too large.

## Describe the solution you'd like

Reduce the size via not using a universal APK

## Describe alternatives you've considered

Use a universal APK

## Additional context
We could use 2-6 APKs, one for each: 32 & 64 bit and ARM, x86 and ...MIPS

This is the most useful stats on which devices are using what architecture https://web.archive.org/web/20170808222202/http://hwstats.unity3d.com:80/mobile/cpu-android.html

I believe *some* devices might still be using MIPS - no idea what tablets are being using by actual users? Or if we even need to support x86 anymore

**Comment by Chris-Petty** [comment]
Fixed in #1109

**Comment by wlthomson** [comment]
## TESTS

- [x] On this branch, yarn build (using java 11+ and node 10+). Should generate 5 APKs as above.
- [x] Check each APK in android studio->debug APK to view contents
- [ ] Each APK tested on it's respective CPU architecture on a real tablet
  - [x] mSupplyMobile-2_3_6-arm64-v8a-debug.apk
  - [x] mSupplyMobile-2_3_6-arm64-v8a-debug.apk
  - [x] mSupplyMobile-2_3_6-universal-debug.apk
  - [x] mSupplyMobile-2_3_6-universal-release.apk
- [x] Universal APK tested on each CPU architecture on real tablets
  - [x] Lenovo TB-X304L (Snapdragon 425, 4x Cortex A53).
