### ISSUE TITLE
New CustomerInvoicePage filtering feature

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1111]
## Is your feature request related to a problem? Please describe.

The new CustomerInvoicePage needs a filtering feature.

## Describe the solution you'd like

The same as sorting - need an array of realm objects to display data, but also have access to a realm results backing data.

options:
- Filter on the backing data using realm queries, apply sorting, convert to an array. I think clearing sorting and simply filtering and converting is a viable option. Is filtering ever needed on getter fields?

OR

- Filter and return the data array using basic array methods

I'd suspect that realm would be a fair bit quicker for this. Especially if we index common filter fields, which is a valid use case. 

Should filtering be done on potentially many fields?

## Describe alternatives you've considered

As above, couple options.

## Additional context

Might need to check the performance of both options, highly suspect realm queries to be faster. Is clearing the current sort state terrible after a search?

Should also debounce this

**Comment by Chris-Petty** [comment]
@joshxg Could be a rerender penalty on realm filtering if the row object references change, worth testing cause otherwise I'd hope it be faster than JS filtering.

**Comment by Chris-Petty** [comment]
Fixed in #1115
