### ISSUE TITLE
New Data Table components require new props

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1119]
## Is your feature request related to a problem? Please describe.

The new components added for the new `DataTable` - `Row`, `Cell` etc. require new props for styling.

## Describe the solution you'd like

a `prop` added for each styling required i.e. `viewStyle` to style the `View` in a component, or `textStyle` to style the `Text` component.

As it is a very common use case that components in react-native use `flex` to adjust their size, and that this is normally a dynamic property, I think it is a good idea to have components have a `width` optional property, which when used injects the passed style (or default) with a `flex` property with a value of the passed `width prop`.

Another common use case is to use `borderRight` in a row based table for indicating the column seperators. I think it would be beneficial to have a `isLastCell` property, which when true, will inject the style with a `borderRightWidth: 0` property.

## Describe alternatives you've considered

Using `context` and `defaultProps` extensively. I think the above solution of using `props` is cleaner and simpler

Not having the additional `props` and having this logic within a `Page` component which uses the components. I think the use-cases are extremely common and if written in a way which can be ignored is a great feature

## Additional context

N/A

**Comment by Chris-Petty** [comment]
👍 for both `width` and `isLastCell` props. Were in old data table for same reasons.

**Comment by Chris-Petty** [comment]
Fixed in #1120
