### ISSUE TITLE
Navigating unmounts components

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1122]
## Describe the bug

When navigating in the app, each page on the `NavigatigationStack` is `unmounted` every time navigation occurs.  This is a significant preformance degradation, as when a user is navigating to a page 3 deep, there are three large unmounting, then remounting process' occuring, including an initial render. These are extremely slow process' compared to a simple re-render.

### To reproduce
1. Put a log in `componentDidUnmount` of some pages you will navigate to
2. Start navigating

1. Use a function which uses `runWithLoadingIndicator`
2. See pages in the stack (a part from mSupplyAppContainer) unmount

I.e - Add a log in `CustomerInvoices` page and navigate to a `CustomerInvoice`, see `CustomerInvoicesPage` unmount.

### Expected behaviour

Components should not be unmounting.

### Version and device info

- App version: I would say all, but possibly 2.3+
- Tablet model:  All
- OS version:  All

### Additional context

**This is about the unmounting of components in the navigation stack rather than the many re-renders of mSupplyMobileApp**

I believe there are two issues here. The large re-rendering is because of `props` being passed. Simple re-rendering of pages should not cause unmounting of components that are already mounted.

**Comment by Chris-Petty** [comment]
Fixed in #1124

**Comment by wlthomson** [comment]
## TESTS

- [x] Navigating does not throw any errors
- [x] Navigating does not unmount components currently in the navigation stack [ You can test this by making some sort of state change - highlight a row for example. when navigating back to this page, the state should be the same]
