### ISSUE TITLE
Refactor StockPage to use new DataTable

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1128]
## Is your feature request related to a problem? Please describe.
Need to use the new `DataTable` in `StockPage`.

## Describe the solution you'd like

- A more or less complete refactor, using the first refactored page `CustomerInvoicePage` as a guide.
- This will require using hooks and the new DataTable `component`.

## Describe alternatives you've considered

N/A

## Additional context

This is a placeholder issue. Please investigate and compare the page with `CustomerInvoicePage`. Each page being refactored may have their own quirks. The tissue is encouraged to describe any additional problems and differences with the particular page here, to find a solution which encourages further extensibility and code-reuse with other pages, if possible.

**Comment by joshxg** [comment]
Have done some **rough playing** around:

current behaviour:
![oldstockpage](https://user-images.githubusercontent.com/35858975/64299259-93b68080-cfcc-11e9-96a4-44efcd517482.gif)


Not good:

![stockpage](https://user-images.githubusercontent.com/35858975/64299241-813c4700-cfcc-11e9-91bf-4c21d91dac9a.gif)

bit better:

![stockPageAtBottom](https://user-images.githubusercontent.com/35858975/64299264-9c0ebb80-cfcc-11e9-8525-483e0736fc34.gif)

If we go with bit better option 3, I think it would mean essentially a table with some headers and a bit more effort than just using page info to look half decent. I think this is more work than anticipated for an easy replacement (given that this type of replacement for an expansion wouldn't work on other pages that need an expansion)

At this point I think it might be best to just not refactor this page, until we have a better solution.

potential other solution:

Take something similar to this 'modal' - remove the button/textinput and just increase the height and display data - add a close button. Has a pretty awful interaction with the keyboard, though

![stocktakemanagepge](https://user-images.githubusercontent.com/35858975/64299309-e09a5700-cfcc-11e9-9083-5b2c739c4609.gif)

**Comment by Chris-Petty** [comment]
1. Still looks best imo haha
2. Yea ew I regret this suggestion now
3. Slightly better
4. I reckon not consistent with other usage of the bottom modal

... Would it be bad just to do #1 in renderRow and use the new selected row state logic to conditionally show it?

**Comment by joshxg** [comment]
no, I think it's  probably right.  Although the comparison is a little unfair - imagine 12? batches for an item - still not the best solution?

**Comment by Chris-Petty** [comment]
Put the batches in a ScrollView? haha

**Comment by joshxg** [comment]
You can't scroll a `ScrollView` inside another `ScrollView`, from my testing. It's also not very user friendly.

**Comment by joshxg** [comment]
This is the last full page left to refactor - still not 100% sure what I should be doing with it?

**Comment by andreievg** [comment]
As per our convo, i think the fastest way for now is to just take current expansion component and put it in into a view modal (not a full page modal)

**Comment by joshxg** [comment]
Closed by #1257
