### ISSUE TITLE
New DataTable CustomerInvoicePage refactor part two

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1136]
## Is your feature request related to a problem? Please describe.

the new `CustomerInvoicePage` requires further refactoring.

## Describe the solution you'd like

Looking to refactor:

- The 'base object' in state renamed to a common/consistent name - `object`.. `baseObject`, `pageObject`? suggestions welcome! looking at the last one I think.
- `PageInfo` - similar/the same as how columns are currently done. Injecting `infoColumns` into a pages state through `usePageReducer`
- Modal logic in state: Putting opening/closing modal logic in state. I think having a `basicModalOpen` action/reducer case for `customerInvoicePage`, where nothing is required to be set before opening is the way to go. For more complex modal interactions - i.e. opening the `StocktakeBatchModal`, some property needs to be set in state. I think making individual modal opening actions and cases should be the way to go. As long as there is a consistent `isModalOpen` property and `modalKey` in state, the logic can be easily shared.
- Adding items: haven't looked to much at this, but am looking at using a common action/reducer case for all pages to add an item. If the logic between `Transaction`/`Requisition`/`Stocktake` are to different, having individual actions for these is still a solid way to go, I think. They would at least be shared between a couple of pages?
- Adding master list items: Same as above
- Wrapper around `HeaderRow` accepting `columns` and sorting logic will be a simple way of creating headers for each page.
- Searching fully in state
- deleting logic
- `checkForFinaliseError` - not sure what to do with this hehe but seems smelly

Other possibilities
- `renderButtons` - A wrapper around this could also be possible?
- `renderModalContent` - not sure but would be cool!

## Describe alternatives you've considered

Leaving it how it is

## Additional context

@Chris-Petty - seems a bit big for one PR, might be a couple. Anything you think I should just leave along or any additional things you think I should do?

**Comment by joshxg** [comment]
another one is this block

```

**Comment by Chris-Petty** [comment]
> another one is this block
> 
> ```
> for (const row of dataState.values()) {
>     if (row.isSelected) {
>       isSelection = true;
>       break;
>     }
>   }
> ```
> 
> little bit heavy to be running constantly? Trying to think of a way to not have to

Would you have noticed if it was `const isSelection = dataState.some(row => row.isSelected)`?
It's only a `for` loop 'cause dataState is a `Map`, which doesn't have the same methods as array annoyingly.

That said, I agree that it's a bit heavy. `isModalOpen` or whatever could be in reducer state. Then reducer methods to add/remove selection can update it appropriately.

**Comment by joshxg** [comment]
Closed by #1143
