### ISSUE TITLE
Require cycles in settings and other utility methods

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1141]
## Describe the bug

There are many require cycles in settings and other various utility methods i.e. merge records/create records.

I don't know if this is 100% my problem, but it seems so.

Removing: `import { createRecord } from '../database';` from `CustomerInvoicePage` makes the app unusable

![image](https://user-images.githubusercontent.com/35858975/63471716-0ea77380-c4c4-11e9-86f4-b7cf34b94406.png)

### To reproduce

1. `CustomerInvoicePage`
2. Remove the above line
3. Restart the app

### Expected behaviour

No require cycles

### Version and device info

- App version: 2.3.5+
- Tablet model: all
- OS version: all

### Additional context

Have spent a couple hours trying to fix this without being able to. The actual error I am getting is `Module AppRegistry is not a registered callable module (calling runApplication)`. Standard fixes seem to suggest clearing caches etc. However I just backtracked through commits and found the one commit that had the above line in it is where the app stops being runnable. 

Removing and adding this line is all it takes to bypass the error.

Also there are heaps of warnings when loading the app which are annoying

**Comment by Chris-Petty** [comment]
fixed in #1142

**Comment by wlthomson** [comment]
## TESTS

- [x] There are no require cycles when building the app. Can just use react-native run-android - this will have warning messages if there are any require cycles
