### ISSUE TITLE
UIDatabase/Settings should be singletons

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1144]
@Chris-Petty @mark-prins @andreievg @wlthomson 

## Description

In the app we have many interfaces to persistant storage, with two 'main' ones, `UIDatabase` and `MobileAppSettings`. Both of these are classes which are instantiated in `mSupplyMobileAppContainer` and passed around in the app through props through the `ReduxNavigator` component. Specifically using `screenProps`, which is an old/deprecated method that needs to be removed (see #1123), alternatively replaced with using redux to pass the database access object. 

Since these two classes are only ever instantiated once and are passed around to just about every part of the app - to every page/container, a lot of display components and almost every `Realm Class` has at least one method which requires the database to be passed, I think these should be singletons that are required in files that need them.

i.e. in `UIDatabase.js`, export like: `export default new UIDatabase(database)`

I think there's an argument that coding to a concrete class without any dependency injection can cause problems when the implementation changes. I think the likelihood of the implementation changing, while maintaining the same API is extremely unlikely (i.e. if the database changes, the API will not stay the same, anyway, unless we had *another* database access layer on top).

**Comment by mark-prins** [comment]
yes. also agree with the comment about the lack of DI and the use of a concrete class, but don't think that the complexity and overhead of dependency injection is worth it in this case.

**Comment by wlthomson** [comment]
I agree. As far as I can tell, this pattern is still DI, just not via props.

The `Settings` class in particular seems a bit over-engineered, I don't know enough about it but it seems to me something which should probably be a static helper class which takes the database object (which is similar to the existing DI but a bit cleaner from a SOC perspective?). The `UIDatabase` seems like almost a textbook case for a singleton, though.

**Comment by joshxg** [comment]
Yeah, the `Settings` helpers could most definitely just be a part of `UIDatabase` (or actually not used at all, as we also use `redux-persist` and `AsyncStorage` as other sources of persistantstorage. But one thing at a time hehe

**Comment by wlthomson** [comment]
> Yeah, the `Settings` helpers could most definitely just be a part of `UIDatabase` (or actually not used at all, as we also use `redux-persist` and `AsyncStorage` as other sources of persistant storage. But one thing at a time hehe

Yeah, just IMO, database should only be for storing core "mSupply data" (i.e. data that maps to desktop), with something like `AsyncStoarge` being used for "app data". I think that's a pretty standard differentiation, and it seems quite tidy and clean to me.

**Comment by Chris-Petty** [comment]
I agree. I think the original decision was an over committal to EVERYTHING needs to be a prop to get to children. I guess modern react might prescribe using context rather than a singleton, but that doesn't help all the realm class files.

Agree with implementation change comments.

**Comment by andreievg** [comment]
I am not sure what the difference is between:
`export default new UIDatabase(...)` and` export let database = new UIDatabase(...)`,
but https://k94n.com/es6-modules-single-instance-pattern, recommends the let option.

It would be sooo much better to have database available everywhere (especially in realm classes).

**Comment by Chris-Petty** [comment]
> I am not sure what the difference is between:
> `export default new UIDatabase(...)` and` export let database = new UIDatabase(...)`,
> but https://k94n.com/es6-modules-single-instance-pattern, recommends the let option.
> 
> It would be sooo much better to have database available everywhere (especially in realm classes).

I think the only diff is the first is default export, the second is named. Usage:
`import database from './UIDatabase'`
`import { database } from './UIDatabase'`

I'd argue he's wrong to be using `let` rather than `const`, too.

**Comment by wlthomson** [comment]
> > I am not sure what the difference is between:
> > `export default new UIDatabase(...)` and` export let database = new UIDatabase(...)`,
> > but https://k94n.com/es6-modules-single-instance-pattern, recommends the let option.
> > It would be sooo much better to have database available everywhere (especially in realm classes).
> 
> I think the only diff is the first is default export, the second is named. Usage:
> `import database from './UIDatabase'`
> `import { database } from './UIDatabase'`
> 
> I'd argue he's wrong to be using `let` rather than `const`, too.

My intuition would be that binding the export to a declaration with `let` or `const` would make it a true singleton in that only one instance is created. It's possible that without that, each `import` statement might create another instance?

**Comment by joshxg** [comment]
Closed by #1149

**Comment by joshxg** [comment]
>My intuition would be that binding the export to a declaration with let or const would make it a true singleton in that only one instance is created. It's possible that without that, each import statement might create another instance?

The same instance is exported, but it's at least nicer to export a variable - was just an example. See #1149 for how it was implemented, it's been merged but happy to talk about it more
