### ISSUE TITLE
Final new CustomerInvoicePage changes

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1148]
## Is your feature request related to a problem? Please describe.

The final `CustomerInvoicePage` changes to complete the first page with the new `DataTable`

## Describe the solution you'd like

- No editing when finalised
- Remove `checkForFinaliseError` (?)
- Doc strings/comments to clarify anything
- "nice it up" - destructuring where needed, rename any variables  etc

@Chris-Petty anything else you can think of?

## Describe alternatives you've considered

Leaving it as is

## Additional context

Hopefully the last issue to finish off `CustomerInvoicePage`!

**Comment by Chris-Petty** [comment]
> Remove checkForFinaliseError (?)

Why?

**Comment by joshxg** [comment]
Seems to me that it would be more at home in a `canFinalise` member of `Transaction`. If I were to look for that method I don't think I would think of looking in the `CustomerInvoicePage` - all of these `checkFor..` methods seem to have been dumped there? The finalisation logic is elsewhere and it is logically related to a `Transaction` object, nothing to do with the `CustomerInvoicePage` view, in my opinion

**Comment by joshxg** [comment]
Remove all logging also

**Comment by joshxg** [comment]
quite a few inline functions now actually - dunno if they're nicer defined, or not - they're not causing render issues as far as I am aware

**Comment by Chris-Petty** [comment]
>Seems to me that it would be more at home in a canFinalise member of Transaction edit: excluding the strings, just returning true/false. If I were to look for that method I don't think I would think of looking in the CustomerInvoicePage - all of these checkFor.. methods seem to have been dumped there? The finalisation logic is elsewhere and it is logically related to a Transaction object, nothing to do with the CustomerInvoicePage view, in my opinion

Yea fair enough, I'm sold. Side note, what do you think of incoming/outgoing sync mapping functions being in the realm classes?

>Remove all logging also

What logging is there in the CustomerInvoicePage?

> quite a few inline functions now actually - dunno if they're nicer defined, or not - they're not causing render issues as far as I am aware

She'll be riiiight

**Comment by joshxg** [comment]
>Yea fair enough, I'm sold. Side note, what do you think of incoming/outgoing sync mapping functions being in the realm classes?

It can work, I think a significant improvement on what we have which is not very open to change. 

Kind of hard to explain my thoughts but I think the way to go would be to be able to pass a mapping algorithm to whatever was doing the parsing. I.e. when instantiating `Synchroniser`, pass some parsing object (i.e. if we had `ParserForXApi` and `ParserForYApi` which had common api's and handled all mapping) or alternatively, each class could have a method which gets passed the parser also - i.e. `Transaction.parseIncomingRecord(record, parser)` - where the `parser` was the same as above. I think having the objects parse their own incoming records most likely breaks the SRP and makes them too complex though

>Remove all logging also

Just meant in all the components

**Comment by Chris-Petty** [comment]
> > Yea fair enough, I'm sold. Side note, what do you think of incoming/outgoing sync mapping functions being in the realm classes?
> 
> It can work, I think a significant improvement on what we have which is not very open to change.
>
> Kind of hard to explain my thoughts but I think the way to go would be to be able to pass a mapping algorithm to whatever was doing the parsing. I.e. when instantiating `Synchroniser`, pass some parsing object (i.e. if we had `ParserForXApi` and `ParserForYApi` which had common api's and handled all mapping) or alternatively, each class could have a method which gets passed the parser also - i.e. `Transaction.parseIncomingRecord(record, parser)` - where the `parser` was the same as above. I think having the objects parse their own incoming records most likely breaks the SRP and makes them too complex though

I like the direction, keen to look at later 😃 

> > Remove all logging also
> 
> Just meant in all the components

Oh duh.

**Comment by joshxg** [comment]
Closed by #1148
