### ISSUE TITLE
Can't finalize stocktakes

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1151]
## Describe the bug

A little strange - but a regression from when I changed a method in `createRecords`, I removed the return value. So any stock take with inventory adjustments would error on finalizing. *This is only in develop*

### To reproduce

1. Go to `StocktakeEditPage`
2. Create a `Stocktake`
3. Make an inventory adjustment (adjust the quantity such that the actual quantity !== counted quantity)
4. Try to finalise

### Expected behaviour

Finalising should complete

### Version and device info

- App version: 2.3.6(?) or 3.0.0(?) - Development 
- Tablet model: All
- OS version: All

### Additional context
Oopsies

**Comment by Chris-Petty** [comment]
Testing huh?

**Comment by Chris-Petty** [comment]
Fixed in #1152

**Comment by wlthomson** [comment]
## TESTS

- [x] Finalize a stocktake with an inventory adjustment
