### ISSUE TITLE
Rename `sortBy` to `sortKey` throughout codebase

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1166]
## The suggestion
Rename `sortBy` to `sortKey` throughout codebase.

**Why?**
`sortKey` is clearer to what is actually being passed around

## Describe alternatives you've considered

`sortField` makes sense too in realmDB context, but `sortKey` is better for the regular JS arrays of objects that the (new)sortDataBy method takes. 
## Additional context

Should come after data table and vaccine module work so that all instances are done in one swoop.

**Comment by joshxg** [comment]
@diegoevangelisti when you close issues github automation switches the project column - for example when you closed this, github moved it from IN PR to NEEDS TESTING -- you can move it back by the projects widget on the left hand side bar

**Comment by joshxg** [comment]
Closed by #1550

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
