### ISSUE TITLE
DataTable CustomerInvoicesPage fixes

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1167]
## Is your feature request related to a problem? Please describe.

Putting off the title request, as other refactor branches cover the code for handling this well.

## Describe the solution you'd like

Revisit CIs page when date cells are available in base refactor branch

- Needs an EntryDate field added
- Status column needs correct formatting
- New Invoice button doesn't get closed after navigating away
- Navigation done through redux

## Describe alternatives you've considered

Redoing the work. Which is a [waste of my time](https://www.youtube.com/watch?v=WTr1M7DwLkc)

**Comment by joshxg** [comment]
Closed by #1202
