### ISSUE TITLE
Extract keyExtractor and getItemLayout from pages

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1170]
## Is your feature request related to a problem? Please describe.

Each page uses a `keyExtractor` and `getItemLayout` function. They are exact duplicates everywhere. They should be extracted to their own file.

## Describe the solution you'd like

Extract each to their own file. Not sure exactly which file. `DataTableUtilities/utilities`...?

## Describe alternatives you've considered

Not doing this

## Additional context

@Chris-Petty anything else that should be extracted?

**Comment by Chris-Petty** [comment]
Fixed in #1173
