### ISSUE TITLE
App becomes unresponsive and crashes with 1000+ rows in any page

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1179]
## Describe the bug

keyboard-aware-scroll-view causes the entire table (including the header row!) to be inside a ScrollView. Instead of the table limiting the amount of rows rendered, it is given unlimited hight within the ScrollView and attempts to render every row. Sites that have 1000s of rows for any page (e.g. 3000+ transactions) will try render every Row. This hogs the JS thread making the app unresponsive and leads to runtime errors when putting the app in the background.

### To reproduce

1. Install v2.3.5
2. Initialise
3. Ensure the site has 1000+ items visible
4. Go current stock and wait
5. Becomes slow. You can see the burden if you turn on android develop options -> GPU rendering profile -> "On screen as bars"

### Expected behaviour

Data table with 1000 rows doesn't make the app unusable

### Version and device info

- App version: 2.3.5 (at least)
- Tablet model: Samsung Tab A (SM-T585)
- OS version:

### Additional context

The tablet is a good one. Definitely the app.

**Comment by Chris-Petty** [comment]
Need to narrow down the version upgrades this occurs with and if number of records has an affect.

**Comment by joshxg** [comment]
I agree need to determine if 

- Occurs with any data (most likely)
- What version this first starts occuring with

I think the biggest versions I know with big upgrades are

- `2.2`
- `2.3`

Would be good to start with those and go backward from there?

**Comment by joshxg** [comment]
Oh - I also think that the app crashing when putting into the background is not insignificant. Android bundles a bunch of stuff when this occurs and `redux-persist` uses `AsyncStorage` also. 

Have we always used `redux-persist`?

**Comment by Chris-Petty** [comment]
Problem is the change included in this PR: https://github.com/sussol/react-native-generic-table-page/pull/15

`keyboard-aware-scroll-view` causes the entire table (including the header row!) to be inside a ScrollView. Instead of the table limiting the amount of rows rendered, it is given unlimited hight within the ScrollView and attempts to render every row. Sites that have 1000s of rows for any page (e.g. 3000+ transactions) will try render every Row. This hogs the JS thread making the app unresponsive and leads to runtime errors when putting the app in the background.

**Comment by craigdrown** [comment]
@Chris-Petty and @joshxg "doesn't make the app unusable"? ;-)
Can you liase with Lou to make sure sites are updated in Côte d'Ivoire and Solomons and Kiribati and ???
