### ISSUE TITLE
DataTable Refactor Testing

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1231]
## Description

- This is a centralized issue for all testing of the `DataTable` refactor. 

### Context

Every page  in the application has been touched and therefore every page needs to be tested to ensure there has been no regressions.

This refactor was for the purpose of performance increasing. The purpose was NOT for adding new features (although there was a couple!) or altering existing behaviour or logic.

*however some things did sneak in*

- `SearchBar` has a 'clear' button
- Plural pages use the current/past toggle to show unfinalized/finalized records
- Stockpage uses a popup instead of an expansion
- Rows are highlighted when selected

## Plan

- There are 12 issues - one for each page. 
- Each issue has all the tests for a single page.
- Each page should be tested multiple times.
- After testing, any failed tests should be reported IN THE ISSUE for that page.
- A list of up-to-date problems with a page will be kept in each pages issue, so that knew testing which occurs does not need to re-report.
- Once a reported problem has been confirmed, a new issue should be made to fix the problem.
- If test cases are not clear, or you had troubles following, please feel free to update with a clearer discription

### Issues

- [ ] `CustomerInvoicesPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1233
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three: 
- `CustomerInvoicePage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1234
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `SupplierInvoicesPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1237
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `SupplierInvoicePage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1236
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `CustomerRequisitionsPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1243
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `CustomerRequisitionPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1244
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `SupplierRequisitionsPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1238
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `SupplierRequisitionPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1239
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `StocktakesPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1240
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `StocktakeManagePage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1241
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `StocktakeEditPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1242
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:
- `StockPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1245
    - [x] Testing one: 
    - [ ] Testing two:
    - [ ] Testing three:

**Comment by Chris-Petty** [comment]
@wlthomson I'm confused, why did you add a different download link?

**Comment by wlthomson** [comment]
> @wlthomson I'm confused, why did you add a different download link?

That's the latest .apk after recent merges (the other download link is Josh's dropbox).
