### ISSUE TITLE
Consistent filtering between  DataTable pages

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1235]
## Is your feature request related to a problem? Please describe.

At the moment a lot of tables filtering keys are in consistent:

example: `CustomerInvoicePage` [uses `Item.name` and `Item.code`](https://github.com/openmsupply/mobile/blob/55057105f3da721188cc8761a65cf253aa74cca9/src/pages/CustomerInvoicePage.js#L62-L65) where as `SupplierInvoicePage` [uses `Item.name`](https://raw.githubusercontent.com/openmsupply/mobile/master/src/pages/SupplierInvoicePage.js)

## Describe the solution you'd like

Pages should be consistent. Every page should be filtered by `Item.name` and `Item.code` if they list items - if not, it should be filtered by `serialNumber` and the other parties name - possibly by comment also.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by Chris-Petty** [comment]
@Rebecca367 just a note an github assignment: We use it to indicate who is actually doing the coding/work required to resolve the issue. This helps avoid multiple people working on the same issue accidentally. People should assign themselves when they want to commit to an issue (or sometimes more manager-ish people will assign others). So no need to assign anyone here.

**Comment by Chris-Petty** [comment]
@joshxg I agree with filtering by Item+code consistently for all pages with items lists. Just party name column for the rest. Useful for #264

**Comment by Rebecca367** [comment]
@Chris-Petty Yes, sure. I assign myself to it first then will add people if they contribute to it later on.
@joshxg I agree with consistent approach to avoid confusion.

**Comment by Rebecca367** [comment]
@joshxg I think that inconsistent of assigning different value to filterDataKeys cause this. 
So, might be good to change some initializers from  [item.name] to ['item.name', 'item.code'], including filterDataKey value of supplierInvoiceInitialiser  in getPageInitialiser.js?

<img width="611" alt="Screen Shot 2020-01-07 at 4 17 52 PM" src="https://user-images.githubusercontent.com/57238075/71866031-c1bdf400-3169-11ea-9a32-377ebdd637aa.png">

**Comment by wlthomson** [comment]
Duplicated by #2796.
