### ISSUE TITLE
TESTING: Supplier Invoices Page

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1237]
# TESTING

This is an issue for testing `SupplierInvoicesPage`.

Please copy and paste this list of tests and post your results in a comment in this issue.

#### TESTER NOTES:
- Have an EXTERNAL supplier with a very long name [External supplier: A facility, visible to the mobile store, who is a supplier]

### NAVIGATION

- [ ] Can navigate to this page through the Menu Page using the `"Supplier Invoices"` button
- [ ] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [ ] Navigating back to this page from an SI shows the correctly updated details (e.g. finalising a supplier invoices shows that SI as finalised, adding a comment will show the comment)

### SYNC

- [ ] Supplier invoices are synced to desktop
- [ ] Supplier credits are synced to desktop

### TABLE

- [ ] Lists all supplier invoices and supplier credits for this store (should match what is displaying in desktop for this store)
- [ ] Initial sort is by invoice number in descending order

#### Row Press

- [ ] Pressing a row (except for the DELETE column), navigates to `SupplierInvoicePage`
- [ ] The supplier invoice or supplier credit navigated to is the one clicked on
    
#### Filtering

- [ ] Invoices are filtered by supplier name when a search term is entered
- [ ] Invoices are filtered by invoice number when a search term is entered
- [ ] Filtering is cleared when the search term is cleared

#### Columns

- [ ] **INVOICE NUMBER**
    - [ ] Sortable (and sorts correctly)
    - [ ] New invoices correctly increment (numbers are re-used)
    - [ ] Invoice numbers are correct for each invoice or credit
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Cells NOT editable
    - [ ] Invoice numbers are re-used (delete an invoice that isn't the maximum invoice number, create a new one, number deleted should be reused)
    - [ ] Left aligned
- [ ] **SUPPLIER**
    - [ ] Sortable (and sorts correctly).
    - [ ] Supplier names are correctly listed for every invoice or credit
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Cells NOT editable
    - [ ] Text overflow handled (create a supplier name that is very long)
    - [ ] Left aligned
- [ ] **ENTERED DATE**
    - [ ] Sortable (and sorts correctly). NOTE: if data file does not have historical supplier invoices,  clicking the sort button is sufficient
    - [ ] Shows the correct date an invoice or credit was created
    - [ ] Dates are in the form `Weekday Month Year`, e.g. `22 April 2020`
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Left aligned
- [ ] **TYPE**
  - [ ] Sortable (and sorts correctly)
  - [ ] Shows the correct type of the invoice or credit: `"Supplier invoice"` or `"Supplier credit"`
  - [ ] Left aligned
- [ ] **Comment**
    - [ ] Column NOT sortable
    - [ ] Cells NOT editable
    - [ ] Shows the correct comment for the invoice.
    - [ ] Text overflow handled (create a very long comment)
    - [ ] Left aligned
- [ ] **Remove**
    - [ ] Column NOT sortable
    - [ ] Cells NOT editable
    - [ ] Finalised invoices are not selectable
    - [ ] Finalised rows indicate they are not selectable
    - [ ] Rows not finalised are selectable
    - [ ] Multiple rows are selectable
    - [ ] Selecting a row opens a confirmation dialog at the bottom of the page
    - [ ] Unselecting a row closes the confirmation dialog at the bottom of the page
    - [ ] Confirming the confirmation dialog deletes the invoices    
    - [ ] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [ ] Finalised invoices are not selectable   
    - [ ] Finalised credits are not selectable

### Buttons

- [ ] `"New Supplier invoice`"
  - [ ] Button is displayed
  - [ ] On press, opens '"Search for the supplier"' dialog

### Modals

- [ ] **New Invoice Modal**
    - [ ] Title: `"Search for the supplier"`
    - [ ] Options to select are names records that are: VISIBLE, a SUPPLIER, not THIS store and whose type is a FACILITY.
    - [ ] Search Bar is auto focused on opening
    - [ ] Closing the modal, closes the modal
    - [ ] Filtering the list, filters by supplier name.
    - [ ] Clearing the search term clears filtering
    - [ ] Clicking a supplier creates a new supplier invoice and navigates to  `SupplierInvoicePage` with the newly created supplier invoice open

**Comment by wlthomson** [comment]
## Testing

### Navigation to/from. **PASSED**.
- [x] Can navigate to this page through the Menu Page, Supplier Invoices button. **PASSED**.
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page. **PASSED**.
- [x] Navigating to this page, BACK from an SI shows the correctly updated details (i.e. finalising a customer invoices shows that CI as finalised). **PASSED**.

### Sync. **PASSED**.
- [x] Supplier invoices are synced to desktop. **PASSED**.
- [x] Supplier invoices are synced from desktop. **PASSED**.
- [x] Syncing while on this page correctly updates the table. **PASSED**.

### Table. **PASSED**.
- [x] Lists all of this stores Supplier Invoices. **PASSED**.
- [x] Initial sort is by descending Invoice Number column. **PASSED**.

#### Row Press. **PASSED**.
- [x] Pressing a row (except for the DELETE column), navigates to the `CustomerInvoicePage`. **PASSED**.
- [x] CustomerInvoice navigated to is the one clicked on. **PASSED**.
    
#### Filtering. **FAILED**.
- [ ] Invoices are filtered by Customer name when a search term is entered. **FAILED (assuming supplier name: can search by invoice number but not supplier name).
- [x] Filtering is cleared when the search term is cleared. **PASSED**.

- [x] **Invoice Number**. **PASSED**.
    - [x] Sortable (and sorts correctly). **PASSED**.
    - [x] New invoices correctly increment. **PASSED**.
    - [x] Invoice numbers are correct for each invoice. **PASSED**.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting. **PASSED**.
    - [x] NOT editable. **PASSED**.
    - [x] Invoice numbers are re-used (delete an invoice, create a new one, should reuse the number). **PASSED**.
    - [ ] Left aligned. **PASSED**.
- [x] **Supplier**. **PASSED**.
    - [x] Sortable (and sorts correctly). **PASSED**.
    - [x] Supplier names are correctly listed for every invoice. **PASSED**.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting. **PASSED**.
    - [x] NOT editable. **PASSED**.
    - [x] Text overflow handled (Create a Supplier name that is very long). **PASSED**.
    - [x] Left aligned. **PASSED**.
- [x] **Status**. **PASSED**.
    - [x] Sortable (and sorts correctly). **PASSED**.
    - [x] Shows the correct status for an invoice. **PASSED**.
    - [x] Status' should be Confirmed or Finalised. (New CI's are Confirmed by default). **PASSED**.
    - [x] Status' are correctly updated. **PASSED**.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting. **PASSED**.
    - [x] Left aligned. **PASSED**.
- [x] **Entered Date**
    - [x] Sortable (and sorts correctly). **PASSED**.
    - [x] Shows the correct date an invoice was created. **PASSED**.
    - [x] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM MM YYYY ]. **PASSED**.
    - [x] Status' are correctly updated. **PASSED**.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting. **PASSED**.
    - [ ] Left aligned. **PASSED**.
- [x] **Comment**. **PASSED**.
    - [x] NOT sortable. **PASSED**.
    - [x] NOT editable. **PASSED**.
    - [x] Shows the correct comment for the invoice. **PASSED**.
    - [x] Text overflow handled. **PASSED**.
    - [x] Left aligned. **PASSED**.
- [ ] **Delete**. **FAILED** (assuming "REMOVE").
    - [x] NOT sortable. **PASSED**.
    - [x] NOT editable. **PASSED**.
    - [x] Finalised invoices are not selectable. **PASSED**.
    - [x] Finalised rows indicate they are not selectable. **PASSED**.
    - [x] Rows not finalised are selectable. **PASSED**.
    - [x] Multiple rows are selectable. **PASSED**.
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page. **PASSED**.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page. **PASSED**.
    - [x] Confirming the confirmation dialog deletes the invoices. **PASSED**.
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog. **PASSED**.
    - [ ] Finalised invoices are not selectable. **FAILED (can remove finalised invoices, although they do not seem to actually delete) 

### Buttons. **PASSED**.
- [x] Clicking New Supplier invoice opens a 'select a supplier' dialog. **PASSED (assuming "New Invoice").

### Modals. **PASSED**.
- [x] **New Invoice Modal**
    - [x] Title is `Search for the supplier`. . **PASSED**.
    - [x] Options to select are names records that are: VISIBLE, a SUPPLIER, not THIS store and whose type is a FACILITY. **PASSED**.
    - [x] Search Bar is auto focused on opening. **PASSED**.
    - [x] Closing the modal, closes the modal. **PASSED**.
    - [x] Filtering the list, filters by supplier name. . **PASSED**.
    - [x] Clearing the search term clears filtering. **PASSED**.
    - [x] Clicking a supplier creates a new Supplier Invoice and navigates to a SupplierInvoicePage with the newly created supplier invoice open. **PASSED**.

**Comment by joshxg** [comment]
> Invoices are filtered by Customer name when a search term is entered. **FAILED (assuming supplier name: can search by invoice number but not supplier name).

Incorrect test:

https://github.com/openmsupply/mobile/blob/55057105f3da721188cc8761a65cf253aa74cca9/src/pages/SupplierInvoicesPage.js#L116

> Finalised invoices are not selectable. FAILED (can remove finalised invoices, although they do not seem to actually delete).

Same issue as others : #1327 

Closing with issues made - thanks a lot !!

**Comment by joshxg** [comment]
### Navigation to/from
- [x] Can navigate to this page through the Menu Page, Supplier Invoices button.
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [x] Navigating to this page, BACK from an SI shows the correctly updated details (i.e. finalising a customer invoices shows that CI as finalised or adding a comment will show the comment when navigating back)

### Sync
- [x] Supplier invoices are synced to desktop

### Table
- [x] Lists all of this stores Supplier Invoices [should match what is displaying in desktop for this store]
- [x] Initial sort is by descending Invoice Number column.

#### Row Press
- [x] Pressing a row (except for the DELETE column), navigates to the `CustomerInvoicePage`
- [x] `CustomerInvoice` navigated to is the one clicked on
    
#### Filtering
- [x] Invoices are filtered by Customer name OR Invoice number when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

- [x] **Invoice Number**
    - [x] Sortable (and sorts correctly).
    - [x] New invoices correctly increment [numbers are re-used].
    - [x] Invoice numbers are correct for each invoice.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable.
    - [x] Invoice numbers are re-used [delete an invoice that isn't the maximum invoice number, create a new one, number deleted should be reused]
    - [x] Left aligned
- [x] **Supplier**
    - [x] Sortable (and sorts correctly).
    - [x] Supplier names are correctly listed for every invoice.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable
    - [x] Text overflow handled (Create a Supplier name that is very long)
    - [x] Left aligned
- [x] **Status**
    - [x] Sortable (and sorts correctly). [This is redundant as of 18/10/19 and may get removed in the future]
    - [x] Shows the correct status for an invoice
    - [x] Status' should be IN Progress or Finalised [Or the correct language equivalent]
    - [x] Status' are correctly updated.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Entered Date**
    - [x] Sortable (and sorts correctly). [This is difficult if all SI's are from the day of testing. Clicking the sort button *shou;d* be sufficient]
    - [x] Shows the correct date an invoice was created.
    - [x] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM MM YYYY ]
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Comment**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Shows the correct comment for the invoice.
    - [x] Text overflow handled [create a very long comment]
    - [x] Left aligned
- [x] **Delete**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised invoices are not selectable
    - [x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog deletes the invoices    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised invoices are not selectable


### Buttons
- [x] Clicking New Supplier invoice opens a 'Search for the supplier' dialog

### Modals
- [x] **New Invoice Modal**
    - [x] Title is `Search for the supplier`
    - [x] Options to select are names records that are: VISIBLE, a SUPPLIER, not THIS store and whose type is a FACILITY.
    - [x] Search Bar is auto focused on opening
    - [x] Closing the modal, closes the modal
    - [x] Filtering the list, filters by supplier name.
    - [x] Clearing the search term clears filtering
    - [x] Clicking a supplier creates a new Supplier Invoice and navigates to a SupplierInvoicePage with the newly created supplier invoice open.

**Comment by diegoevangelisti** [comment]
### NAVIGATION
- [x] Can navigate to this page through the Menu Page, Supplier Invoices button.
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page

**(Fail)** Navigating to this page, BACK from an SI shows the correctly updated details (i.e. finalising a customer invoices shows that CI as finalised or adding a comment will show the comment when navigating back) **--> After adding a comment and navigation back, it shows the changes when, for example, toggle to Past and Current again.**

### SYNC
- [x] Supplier invoices are synced to desktop

### TABLE
- [x] Lists all of this stores Supplier Invoices [should match what is displaying in desktop for this store]
- [x] Initial sort is by descending Invoice Number column.

#### Row Press
- [x] Pressing a row (except for the DELETE column), navigates to the `CustomerInvoicePage`
- [x] `CustomerInvoice` navigated to is the one clicked on
    
#### Filtering
**(Fail)** Invoices are filtered by Customer name OR Invoice number when a search term is entered. **--> Search filtering just works for Invoice Number**
- [x] Filtering is cleared when the search term is cleared.

- [x] **Invoice Number**
    - [x] Sortable (and sorts correctly).
    - [x] New invoices correctly increment [numbers are re-used].
    - [x] Invoice numbers are correct for each invoice.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable.
    - [x] Invoice numbers are re-used [delete an invoice that isn't the maximum invoice number, create a new one, number deleted should be reused]
    - [x] Left aligned
- [x] **Supplier**
    - [x] Sortable (and sorts correctly).
    - [x] Supplier names are correctly listed for every invoice.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable
    - [x] Text overflow handled (Create a Supplier name that is very long)
    - [x] Left aligned
- [x] **Status**
    - [x] Shows the correct status for an invoice
    - [x] Status' should be IN Progress or Finalised [Or the correct language equivalent]
    - [x] Status' are correctly updated.
    - [x] Left aligned
- [x] **Entered Date**
    - [x] Sortable (and sorts correctly). [This is difficult if all SI's are from the day of testing. Clicking the sort button *shou;d* be sufficient]
    - [x] Shows the correct date an invoice was created.
    - [x] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM DD YYYY ]
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Comment**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Shows the correct comment for the invoice.
    - [x] Text overflow handled [create a very long comment]
    - [x] Left aligned
- [x] **Delete**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised invoices are not selectable
    - [x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog deletes the invoices    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised invoices are not selectable

### Buttons
- [x] Clicking New Supplier invoice opens a 'Search for the supplier' dialog

### Modals
-  [x] **New Invoice Modal**
    - [x] Title is `Search for the supplier`
    - [x] Options to select are names records that are: VISIBLE, a SUPPLIER, not THIS store and whose type is a FACILITY.
    - [x] Search Bar is auto focused on opening
    - [x] Closing the modal, closes the modal
    - [x] Filtering the list, filters by supplier name.
    - [x] Clearing the search term clears filtering
    - [x] Clicking a supplier creates a new Supplier Invoice and navigates to a SupplierInvoicePage with the newly created supplier invoice open.

**Comment by joshxg** [comment]
> (Fail) Navigating to this page, BACK from an SI shows the correctly updated details (i.e. finalising a customer invoices shows that CI as finalised or adding a comment will show the comment when navigating back) --> After adding a comment and navigation back, it shows the changes, for example, when toggle to Past and Current again.

I can't replicate this on develop? I.e. when I change a comment and navigate back, the list is updated. Are you getting something different?

![ciupdating](https://user-images.githubusercontent.com/35858975/69951214-b881ac00-1559-11ea-95aa-3c28d16a7499.gif)


> (Fail) Invoices are filtered by Customer name OR Invoice number when a search term is entered. --> Search filtering just works for Invoice Number

Lets fix this here: https://github.com/openmsupply/mobile/issues/1235 -- not urgent, can do for 3.2

**Comment by diegoevangelisti** [comment]
> > (Fail) Navigating to this page, BACK from an SI shows the correctly updated details (i.e. finalising a customer invoices shows that CI as finalised or adding a comment will show the comment when navigating back) --> After adding a comment and navigation back, it shows the changes, for example, when toggle to Past and Current again.
> 
> I can't replicate this on develop? I.e. when I change a comment and navigate back, the list is updated. Are you getting something different?

My bad @joshxg, I was using an old APK to reproduce the error. I've checked again and it's working fine. Thanks for reviewing it! Cheers

**Comment by Rebecca367** [comment]
There are no records synced to desktop 

### SYNC
- **[x] Supplier invoices are synced to desktop**

### TABLE
- [x] Lists all of this stores Supplier Invoices [should match what is displaying in desktop for this store]
- [x] Initial sort is by descending Invoice Number column.

# TESTING

This is an issue for testing `SupplierInvoicesPage`.

Please copy and paste this list of tests and post your results in a comment in this issue.

## Supplier Invoices Page (SI = Supplier Invoice)

#### TESTER NOTES:
- Have an EXTERNAL supplier with a very long name [External supplier: A facility, visible to the mobile store, who is a supplier]

### NAVIGATION
- [x] Can navigate to this page through the Menu Page, Supplier Invoices button.
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [x] Navigating to this page, BACK from an SI shows the correctly updated details (i.e. finalising a customer invoices shows that CI as finalised or adding a comment will show the comment when navigating back)

### SYNC
- **[x] Supplier invoices are synced to desktop**


### TABLE
- [x] Lists all of this stores Supplier Invoices [should match what is displaying in desktop for this store]
- [x] Initial sort is by descending Invoice Number column.

#### Row Press
- [x] Pressing a row (except for the DELETE column), navigates to the `SupplierInvoicePage`
- [x] `SupplierInvoice` navigated to is the one clicked on
    
#### Filtering
- [x] Invoices are filtered by Customer name OR Invoice number when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

- [x] **Invoice Number**
    - [x] Sortable (and sorts correctly).
    - [x] New invoices correctly increment [numbers are re-used].
    - [x] Invoice numbers are correct for each invoice.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable.
    - [x] Invoice numbers are re-used [delete an invoice that isn't the maximum invoice number, create a new one, number deleted should be reused]
    - [x] Left aligned
- [x] **Supplier**
    - [x] Sortable (and sorts correctly).
    - [x] Supplier names are correctly listed for every invoice.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable
    - [x] Text overflow handled (Create a Supplier name that is very long)
    - [x] Left aligned
- [x] **Status**
    - [x] Unsortable (and sorts correctly).
    - [x] Shows the correct status for an invoice
    - [x] Status' should be IN Progress or Finalised [Or the correct language equivalent]
    - [x] Status' are correctly updated.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Entered Date**
    - [x] Sortable (and sorts correctly). [This is difficult if all SI's are from the day of testing. Clicking the sort button *should* be sufficient]
    - [x] Shows the correct date an invoice was created.
    - [FAILED] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM MM YYYY ]
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Comment**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Shows the correct comment for the invoice.
    - [x] Text overflow handled [create a very long comment]
    - [x] Left aligned
- [x] **Remove**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised invoices are not selectable
    - [x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable 
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog deletes the invoices    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised invoices are not selectable


### Buttons
- [x] Clicking New Supplier invoice opens a 'Search for the supplier' dialog

### Modals
- [x] **New Invoice Modal**
    - [x] Title is `Search for the supplier`
    - [x] Options to select are names records that are: VISIBLE, a SUPPLIER, not THIS store and whose type is a FACILITY.
    - [x] Search Bar is auto focused on opening
    - [x] Closing the modal, closes the modal
    - [x] Filtering the list, filters by supplier name.
    - [x] Clearing the search term clears filtering
    - [x] Clicking a supplier creates a new Supplier Invoice and navigates to a SupplierInvoicePage with the newly created supplier invoice open.

**Comment by wlthomson** [comment]
Updated for `v5.0.0`.

**Comment by DhanyaHerath** [comment]
### Testing v5.0.0RC1

### NAVIGATION

- [ ] Can navigate to this page through the Menu Page using the `"Supplier Invoices"` button
- [ ] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [ ] Navigating back to this page from an SI shows the correctly updated details (e.g. finalising a customer invoices shows that CI as finalised, adding a comment will show the comment)

### SYNC

- [ ] Supplier invoices are synced to desktop
- [ ] Supplier credits are synced to desktop

### TABLE

- [ ] Lists all supplier invoices and supplier credits for this store (should match what is displaying in desktop for this store)
- [ ] Initial sort is by invoice number in descending order

#### Row Press

- [ ] Pressing a row (except for the DELETE column), navigates to `SupplierInvoicePage`
- [ ] The supplier invoice or supplier credit navigated to is the one clicked on
    
#### Filtering

- [ ] Invoices are filtered by supplier name when a search term is entered
- [ ] Invoices are filtered by invoice number when a search term is entered
- [ ] Filtering is cleared when the search term is cleared

#### Columns

- [ ] **INVOICE NUMBER**
    - [ ] Sortable (and sorts correctly)
    - [ ] New invoices correctly increment (numbers are re-used)
    - [ ] Invoice numbers are correct for each invoice or credit
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Cells NOT editable
    - [ ] Invoice numbers are re-used (delete an invoice that isn't the maximum invoice number, create a new one, number deleted should be reused)
    - [ ] Left aligned
- [ ] **SUPPLIER**
    - [ ] Sortable (and sorts correctly).
    - [ ] Supplier names are correctly listed for every invoice or credit
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Cells NOT editable
    - [ ] Text overflow handled (create a supplier name that is very long)
    - [ ] Left aligned
- [ ] **ENTERED DATE**
    - [ ] Sortable (and sorts correctly). NOTE: if data file does not have historical supplier invoices,  clicking the sort button is sufficient
    - [ ] Shows the correct date an invoice or credit was created
    - [ ] Dates are in the form `Weekday Month Year`, e.g. `22 April 2020`
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Left aligned
- [ ] **TYPE**
  - [ ] Sortable (and sorts correctly)
  - [ ] Shows the correct type of the invoice or credit: `"Supplier invoice"` or `"Supplier credit"`
  - [ ] Left aligned
- [ ] **Comment**
    - [ ] Column NOT sortable
    - [ ] Cells NOT editable
    - [ ] Shows the correct comment for the invoice.
    - [ ] Text overflow handled (create a very long comment)
    - [ ] Left aligned
- [ ] **Remove**
    - [ ] Column NOT sortable
    - [ ] Cells NOT editable
    - [ ] Finalised invoices are not selectable
    - [ ] Finalised rows indicate they are not selectable
    - [ ] Rows not finalised are selectable
    - [ ] Multiple rows are selectable
    - [ ] Selecting a row opens a confirmation dialog at the bottom of the page
    - [ ] Unselecting a row closes the confirmation dialog at the bottom of the page
    - [ ] Confirming the confirmation dialog deletes the invoices    
    - [ ] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [ ] Finalised invoices are not selectable   
    - [ ] Finalised credits are not selectable

### Buttons

- [ ] `"New Supplier invoice`"
  - [ ] Button is displayed
  - [ ] On press, opens '"Search for the supplier"' dialog

### Modals

- [ ] **New Invoice Modal**
    - [ ] Title: `"Search for the supplier"`
    - [ ] Options to select are names records that are: VISIBLE, a SUPPLIER, not THIS store and whose type is a FACILITY.
    - [ ] Search Bar is auto focused on opening
    - [ ] Closing the modal, closes the modal
    - [ ] Filtering the list, filters by supplier name.
    - [ ] Clearing the search term clears filtering
    - [ ] Clicking a supplier creates a new supplier invoice and navigates to  `SupplierInvoicePage` with the newly created supplier invoice open

**Comment by wlthomson** [comment]
Thanks @diegoevangelisti :tada:!

**Comment by joshxg** [comment]
# TESTING

This is an issue for testing `SupplierInvoicesPage`.

Please copy and paste this list of tests and post your results in a comment in this issue.

## Supplier Invoices Page (SI = Supplier Invoice)

#### TESTER NOTES:
- Have an EXTERNAL supplier with a very long name [External supplier: A facility, visible to the mobile store, who is a supplier]

### NAVIGATION

- [x] Can navigate to this page through the Menu Page using the `"Supplier Invoices"` button
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [x] Navigating back to this page from an SI shows the correctly updated details (e.g. finalising a supplier invoices shows that SI as finalised, adding a comment will show the comment)

### SYNC

- [x] Supplier invoices are synced to desktop
- [x] Supplier credits are synced to desktop

### TABLE

- [x] Lists all supplier invoices and supplier credits for this store (should match what is displaying in desktop for this store)
- [x] Initial sort is by invoice number in descending order

#### Row Press

- [x] Pressing a row (except for the DELETE column), navigates to `SupplierInvoicePage`
- [x] The supplier invoice or supplier credit navigated to is the one clicked on
    
#### Filtering

- [x] Invoices are filtered by supplier name when a search term is entered
- [x] Invoices are filtered by invoice number when a search term is entered
- [x] Filtering is cleared when the search term is cleared

#### Columns

- [x] **INVOICE NUMBER**
    - [x] Sortable (and sorts correctly)
    - [x] New invoices correctly increment (numbers are re-used)
    - [x] Invoice numbers are correct for each invoice or credit
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [x] Cells NOT editable
    - [x] Invoice numbers are re-used (delete an invoice that isn't the maximum invoice number, create a new one, number deleted should be reused)
    - [x] Left aligned
- [x] **SUPPLIER**
    - [x] Sortable (and sorts correctly).
    - [x] Supplier names are correctly listed for every invoice or credit
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [x] Cells NOT editable
    - [x] Text overflow handled (create a supplier name that is very long)
    - [x] Left aligned
- [x] **ENTERED DATE**
    - [x] Sortable (and sorts correctly). NOTE: if data file does not have historical supplier invoices,  clicking the sort button is sufficient
    - [x] Shows the correct date an invoice or credit was created
    - [x] Dates are in the form `Weekday Month Year`, e.g. `22 April 2020`
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [x] Left aligned
- [x] **TYPE**
  - [x] Sortable (and sorts correctly)
  - [x] Shows the correct type of the invoice or credit: `"Supplier invoice"` or `"Supplier credit"`
  - [x] Left aligned
- [x] **Comment**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Shows the correct comment for the invoice.
    - [x] Text overflow handled (create a very long comment)
    - [x] Left aligned
- [x] **Remove**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised invoices are not selectable
    - [x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page
    - [x] Confirming the confirmation dialog deletes the invoices    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised invoices are not selectable   
    - [x] Finalised credits are not selectable

### Buttons

- [x] `"New Supplier invoice`"
  - [x] Button is displayed
  - [x] On press, opens '"Search for the supplier"' dialog

### Modals

- [x] **New Invoice Modal**
    - [x] Title: `"Search for the supplier"`
    - [x] Options to select are names records that are: VISIBLE, a SUPPLIER, not THIS store and whose type is a FACILITY.
    - [x] Search Bar is auto focused on opening
    - [x] Closing the modal, closes the modal
    - [x] Filtering the list, filters by supplier name.
    - [x] Clearing the search term clears filtering
    - [x] Clicking a supplier creates a new supplier invoice and navigates to  `SupplierInvoicePage` with the newly created supplier invoice open
