### ISSUE TITLE
TESTING: Stocktakes Page

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1240]
# TESTING 

This is an issue for testing `StocktakesPage`.

Please copy and paste this list of tests and post your results in a comment in this issue.

### NAVIGATION

- [ ] Can navigate to this page through the Menu Page, using `"Stock take"` button
- [ ] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [ ] Navigating to this page from a stocktake shows the correctly updated details (i.e. finalising a stocktake shows that stocktake as finalised)

### Sync

- [ ] Stocktakes are synced to desktop (create or edit a stocktakes comment/status, should be reflected in desktop for the mobile store)

### Table

- [ ] Toggled to `"Current"`: list displays all stocktakes for this store which are NOT finalised
- [ ] Toggled to `"Past"`:  list all stocktakes for this store which are finalised
- [ ] Initial sort is by descending created date

#### Row Press

- [ ] Pressing a row (except for the `DELETE` column), navigates to the `StocktakeEditPage`
- [ ] Stocktake navigated to is the one clicked on
    
#### Filtering

- [ ] Stocktake are filtered by stocktake name when a search term is entered
- [ ] Filtering is cleared when the search term is cleared

#### Columns 

- [ ] **NAME**
    - [ ] Sortable (and sorts correctly).
    - [ ] Names are correctly listed for every Stocktake.
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [ ] Cells are NOT editable
    - [ ] Text overflow handled (Create a Customer name that is very long)
    - [ ] Left aligned
- [ ] **PROGRAM** (NOTE: only displays if at least one stocktake is associated with a program)
  - [ ] Does not display if no stocktakes are associated with a program (includes current AND past stocktakes)
  - [ ] Displays if at least one stocktake is associated with a program (includes current AND past stocktakes)
  - [ ] Sortable (and sorts correctly)
  - [ ] Programs are listed correctly for every stocktake (`"N/A"` if stocktake has no program)
  - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
  - [ ] Cells are NOT editable
  - [ ] Text overflow handled (create a program name that is very long)
  - [ ] Left aligned
- [ ] **CREATED DATE**
    - [ ] Sortable (and sorts correctly)
    - [ ] Shows the correct date an invoice was created
    - [ ]  Dates are in the form: `WeekDay Month Year`, e.g. `17 May 2008`
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Left aligned
- [ ] **STATUS**
    - [ ] Shows the correct status for each stocktake
    - [ ] All stocktakes have a status of: `"In Progress "` or `"Finalised"`
    - [ ] Stocktake status is correctly updated
    - [ ] Cells NOT editable
    - [ ] Left aligned
- [ ] **REMOVE**
    - [ ] Column NOT sortable
    - [ ] Cells NOT editable
    - [ ] Finalised stocktakes are not selectable
    - [ ] Finalised rows indicate they are not selectable
    - [ ] Rows not finalised are selectable
    - [ ] Multiple rows are selectable
    - [ ] Selecting a row opens a confirmation dialog at the bottom of the page
    - [ ] Unselecting a row closes the confirmation dialog at the bottom of the page
    - [ ] Confirming the confirmation dialog deletes the stocktakes    
    - [ ] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [ ] Finalised stocktake are not selectable

### Buttons

- [ ] `"New Stocktake"`
  - [ ] Button is displayed
  - [ ] On press, navigates to the manage stocktake page

## WITH PROGRAMS

*Note: Having a program: Having a master list which is a program related to the store with a store tag matching a tag in this stores tag

### Buttons

- [ ] `"New Stocktake"`
  - [ ] Button is displayed
  - [ ] On press, opens `ByProgramModal`

### Modals

- [ ] **ByProgramModal**
  - [ ] Must select steps in order - program, name or name if toggled
  - [ ] Can back pedal steps, where the progress is adjusted correctly
  - [ ] Name used is the name applied to the stock take
  - [ ] The selected programs items are added to the stocktake
  - [ ] Pressing OK will navigate to the `StocktakeEditPage` when a program stocktake
  - [ ] Pressing OK will navigate to the `StocktakeManagePage` when NOT a program stocktake

**Comment by wlthomson** [comment]
### TESTING (WITH PROGRAMS):

#### Buttons

- [x] Clicking New Requisition button opens the ByProgramModal. **PASSED (assuming "New Stocktake" button)**.

#### Modals

- [ ] ByProgramModal modal. **FAILED**,
  - [x] must select steps in order - program, name or name if toggled. **PASSED**,
  - [x] Can back pedal steps, where the progress is adjusted correctly. **PASSED**,
  - [ ] Name used is the name applied to the stock take. **FAILED (stockname is named by on program and time, e.g. `Program - 30/9/2019 17:47`)**.
  - [x] programs items are added to the stocktake.  **PASSED**,

**Comment by wlthomson** [comment]
## TESTING (WITHOUT PROGRAMS)

### Navigation to/from
- [ ] Can navigate to this page through the Menu Page, Stock take button. **SUCCESS**.
- [ ] Pressing either the top left back button, or hardware back button navigates to the Menu Page. **SUCCESS**.
- [ ] Navigating to this page, from a stocktake shows the correctly updated details (i.e. finalising a stocktake shows that stocktake as finalised). **SUCCESS**.

### Sync
- [x] stocktakes are synced to desktop. **SUCCESS**.
- [x] stocktakes are synced from desktop. **SUCCESS**.
- [x] Syncing while on this page correctly updates the table. **SUCCESS**.

### Table. **FAILED**.
- [x] Current toggled: Lists all of this stores stocktakes which aren't finalised. **SUCCESS**.
- [x] Past toggled: Lists all of this stores stocktakes which are finalised. **SUCCESS**.
- [ ] Initial sort is by descending created date. **FAILED (stocktakes are sorted in ascending order by created date (oldest to most recent)**.

#### Row Press
- [ ] Pressing a row (except for the DELETE column), navigates to the `StocktakeEditPage`. **SUCCESS**.
- [ ] Stocktake navigated to is the one clicked on. **SUCCESS**.
    
#### Filtering
- [ ] Stocktake are filtered by Stocktake name when a search term is entered. **SUCCESS**.
- [ ] Filtering is cleared when the search term is cleared. **SUCCESS**.

#### Columns 
- [ ] **Name**
    - [ ] Sortable (and sorts correctly). **SUCCESS**.
    - [ ] Names are correctly listed for every Stocktake. **SUCCESS**.
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting. **SUCCESS**.
    - [ ] NOT editable. **SUCCESS**.
    - [ ] Text overflow handled (Create a Customer name that is very long). **SUCCESS**.
    - [ ] Left aligned. **SUCCESS**.
- [ ] **Created Date**. **SUCCESS**.
    - [ ] Sortable (and sorts correctly). **SUCCESS**.
    - [ ] Shows the correct date an invoice was created. **SUCCESS**.
    - [ ] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM MM YYYY ]. **SUCCESS**.
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting. **SUCCESS**.
    - [ ] Left aligned. **SUCCESS**.
- [ ] **Status**. **SUCCESS**.
    - [ ] Sortable (and sorts correctly). **SUCCESS**.
    - [ ] Shows the correct status for an invoice. **SUCCESS**.
    - [ ] Status' should be In Progress or Finalised. (New CI's are Confirmed by default). **SUCCESS (not sure about part about CIs)**.
    - [ ] Status' are correctly updated. **SUCCESS**.
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting. **SUCCESS**.
    - [ ] Left aligned. **SUCCESS**.
- [ ] **Delete**
    - [ ] NOT sortable. **SUCCESS**.
    - [ ] NOT editable. **SUCCESS**.
    - [ ] Finalised invoices are not selectable. **FAILED (assuming reads "finalised stocktakes", see #1340)**.
    - [ ] Finalised rows indicate they are not selectable
    - [ ] Rows not finalised are selectable
    - [ ] Multiple rows are selectable
    - [ ] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [ ] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [ ] Confirming the confirmation dialog deletes the stocktakes    
    - [ ] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [ ] Finalised stocktake are not selectable


### Buttons
- [ ] Clicking New invoice navigaates to the stocktake manage page

**Comment by joshxg** [comment]
Sorting bug issue here : #1344 

Row selection/deleting finalised issue fixed in #1327

**Comment by joshxg** [comment]
#### TESTER NOTES:
- When creating a new stocktake you'll be navigated to the 'manage' page too add items. Once you add items you go to the 'Edit' page. When you navigate BACK from the edit page, you should not go to the manage page again.

# TESTING

### NAVIGATION
- [x] Can navigate to this page through the Menu Page, Stock take button.
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [x] Navigating to this page, from a stocktake shows the correctly updated details (i.e. finalising a stocktake shows that stocktake as finalised)

### Sync
- [x] stocktakes are synced to desktop [ Create or edit a stocktakes comment/status - should be reflected in desktop for the mobile store]

### Table
- [x] Current toggled: Lists all of this stores stocktakes which aren't finalised
- [x] Past toggled: Lists all of this stores stocktakes which are finalised
- [x] Initial sort is by descending created date.

#### Row Press
- [x] Pressing a row (except for the DELETE column), navigates to the `StocktakeEditPage`
- [x] Stocktake navigated to is the one clicked on
    
#### Filtering
- [x] Stocktake are filtered by Stocktake name when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [x] **Name**
    - [x] Sortable (and sorts correctly).
    - [x] Names are correctly listed for every Stocktake.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells are NOT editable
    - [x] Text overflow handled (Create a Customer name that is very long)
    - [x] Left aligned
- [x] **Created Date**
    - [x] Sortable (and sorts correctly).
    - [x] Shows the correct date an invoice was created.
    - [x] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM MM YYYY ]
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Status**
    - [x] Sortable (and sorts correctly).
    - [x] Shows the correct status for each Stocktake
    - [x] Status' should be In Progress or Finalised
    - [x] Status' are correctly updated.
    - [x] Cells NOT editable
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Delete**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised stocktakes are not selectable
    - [x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog deletes the stocktakes    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised stocktake are not selectable

### Buttons
- [x] Clicking New invoice navigates to the Stocktake manage page

## WITH PROGRAMS

*Having a program means, having a master list which is a program, which has a storeTag matching a tag for this store*

### Buttons
- [x] Clicking New Requisition button opens the ByProgramModal

### Modals
- [x] **ByProgramModal modal**
- [x] must select steps in order - program, name or name if toggled
- [x] Can back pedal steps, where the progress is adjusted correctly
- [x] Name used is the name applied to the stock take
- [x] The selected programs items are added to the stocktake
- [x] Pressing OK will navigate to the StocktakeEditPage when a Program Stocktake
- [x] Pressing OK will navigate to the StocktakeManagePage when NOT a program stocktake

**Comment by diegoevangelisti** [comment]
### NAVIGATION
- [x] Can navigate to this page through the Menu Page, Stock take button.
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [x] Navigating to this page, from a stocktake shows the correctly updated details (i.e. finalising a stocktake shows that stocktake as finalised)

### Sync
- [ ] stocktakes are synced to desktop [ Create or edit a stocktakes comment/status - should be reflected in desktop for the mobile store]

### Table
- [x] Current toggled: Lists all of this stores stocktakes which aren't finalised
- [x] Past toggled: Lists all of this stores stocktakes which are finalised
- [x] Initial sort is by descending created date.

#### Row Press
- [x] Pressing a row (except for the DELETE column), navigates to the `StocktakeEditPage`
- [x] Stocktake navigated to is the one clicked on
    
#### Filtering
- [x] Stocktake are filtered by Stocktake name when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [ ] **Name**
    - [x] Sortable (and sorts correctly).
    - [x] Names are correctly listed for every Stocktake.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells are NOT editable
    - [ ] Text overflow handled (Create a Customer name that is very long)
    - [x] Left aligned
- [ ] **Created Date**
    - [x] Sortable (and sorts correctly).
    - [ ] Shows the correct date an invoice was created.
    - [ ] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM MM YYYY ]
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [ ] Left aligned
- [ ] **Status**
    - **(FAIL) Sortable (and sorts correctly) --> Status is not sortable, it is "Finalised" or "In Progress" depending on the toggle's position**
    - [x] Shows the correct status for each Stocktake
    - [x] Status' should be In Progress or Finalised
    - [x] Status' are correctly updated.
    - [x] Cells NOT editable
    - **(FAIL) Sorting icon updates correctly to indicate ascending/descending and no sorting. --> There's not sorting icon**.
    - [x] Left aligned
- [ ] **Delete**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised stocktakes are not selectable
    - [ x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog deletes the stocktakes    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised stocktake are not selectable

### Buttons
- [x] Clicking New invoice navigates to the Stocktake manage page

## WITH PROGRAMS

*Having a program means, having a master list which is a program, which has a storeTag matching a tag for this store*

### Buttons
- [ ] Clicking New Requisition button opens the ByProgramModal

### Modals
- [ ] **ByProgramModal modal**
- [ ] must select steps in order - program, name or name if toggled
- [ ] Can back pedal steps, where the progress is adjusted correctly
- [ ] Name used is the name applied to the stock take
- [ ] The selected programs items are added to the stocktake
- [ ] Pressing OK will navigate to the StocktakeEditPage when a Program Stocktake
- [ ] Pressing OK will navigate to the StocktakeManagePage when NOT a program stocktake

**Comment by joshxg** [comment]
> (FAIL) Sorting icon updates correctly to indicate ascending/descending and no sorting. --> There's not sorting icon.

This column was changed recently and is no longer sortable - might have to update all the templates

thanks for testing!

**Comment by Rebecca367** [comment]
There is one testing case under Button because I am not sure if click new invoice would navigate to stocktake manage page?
 
**- [ ] Clicking New invoice navigates to the Stocktake manage page
=> I am not sure if this is the right testing case?** 

# TESTING 

This is an issue for testing `StocktakesPage`.

Please copy and paste this list of tests and post your results in a comment in this issue.


## Stocktakes Page
# TESTING

### NAVIGATION
- [x] Can navigate to this page through the Menu Page, Stock take button.
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [x] Navigating to this page, from a stocktake shows the correctly updated details (i.e. finalising a stocktake shows that stocktake as finalised)

### Sync
- [x] stocktakes are synced to desktop [ Create or edit a stocktakes comment/status - should be reflected in desktop for the mobile store]

### Table
- [x] Current toggled: Lists all of this stores stocktakes which aren't finalised
- [x] Past toggled: Lists all of this stores stocktakes which are finalised
- [x] Initial sort is by descending created date.

#### Row Press
- [x] Pressing a row (except for the DELETE column), navigates to the `StocktakeEditPage`
- [x] Stocktake navigated to is the one clicked on
    
#### Filtering
- [x] Stocktake are filtered by Stocktake name when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [x] **Name**
    - [x] Sortable (and sorts correctly).
    - [x] Names are correctly listed for every Stocktake.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells are NOT editable
    - [x] Text overflow handled (Create a Customer name that is very long)
    - [x] Left aligned
- [x] **Created Date**
    - [x] Sortable (and sorts correctly).
    - [x] Shows the correct date an invoice was created.
    **- [FAILED] Dates are in the form [ DayOfWeek Month DateOfMonth Year - DDD MMM MM YYYY ]
// There is no dayOfWeek in the form. Is it default setting?**

    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Left aligned
- [x] **Status**
    - [x] Shows the correct status for each Stocktake
    - [x] Status' should be In Progress or Finalised
    - [x] Status' are correctly updated.
    - [x] Cells NOT editable
    - [x] Left aligned
- [x] **Remove**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised stocktakes are not selectable
    - [x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog deletes the stocktakes    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised stocktake are not selectable

### Buttons
**- [ ] Clicking New invoice navigates to the Stocktake manage page
=> I am not sure if this is the right testing case?** 

## WITH PROGRAMS

*Having a program means, having a master list which is a program, which has a storeTag matching a tag for this store*

### Buttons
- [x] Clicking New Stocktake button opens the ByProgramModal

### Modals
- [x] **ByProgramModal modal**
- [x] must select steps in order - program, name or name if toggled
- [x] Can back pedal steps, where the progress is adjusted correctly
- [x] Name used is the name applied to the stock take
- [x] The selected programs items are added to the stocktake
- [x] Pressing OK will navigate to the StocktakeEditPage when a Program Stocktake
- [x] Pressing OK will navigate to the StocktakeManagePage when NOT a program stocktake

**Comment by joshxg** [comment]
@Rebecca367 

When you have no `Programmes`, you should navigate straight to the `StocktakeManagePage` rather than having the black modal pop up :)

**Comment by Rebecca367** [comment]
@joshxg 
cool, thanks 👍

**Comment by wlthomson** [comment]
Updated for `v5.0.0`.

**Comment by ArpitaSussol** [comment]
Tested with v5.0.0 rc1

# TESTING 

### NAVIGATION

- [x] Can navigate to this page through the Menu Page, using `"Stock take"` button
- [x] Pressing either the top left back button, or hardware back button navigates to the Menu Page
- [x] Navigating to this page from a stocktake shows the correctly updated details (i.e. finalising a stocktake shows that stocktake as finalised)

### Sync

- [x] Stocktakes are synced to desktop (create or edit a stocktakes comment/status, should be reflected in desktop for the mobile store)

### Table

- [x] Toggled to `"Current"`: list displays all stocktakes for this store which are NOT finalised
- [x] Toggled to `"Past"`:  list all stocktakes for this store which are finalised
- [x] Initial sort is by descending created date

#### Row Press

- [x] Pressing a row (except for the `DELETE` column), navigates to the `StocktakeEditPage`
- [x] Stocktake navigated to is the one clicked on
    
#### Filtering

- [x] Stocktake are filtered by stocktake name when a search term is entered
- [x] Filtering is cleared when the search term is cleared

#### Columns 

- [x] **NAME**
    - [x] Sortable (and sorts correctly).
    - [x] Names are correctly listed for every Stocktake.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells are NOT editable
    - [x] Text overflow handled (Create a Customer name that is very long)
    - [x] Left aligned
- [x] **PROGRAM** (NOTE: only displays if at least one stocktake is associated with a program)
  - [x] Does not display if no stocktakes are associated with a program (includes current AND past stocktakes)
  - [x] Displays if at least one stocktake is associated with a program (includes current AND past stocktakes)
  - [ ] Sortable (and sorts correctly)
  - [x] Programs are listed correctly for every stocktake (`"N/A"` if stocktake has no program)
  - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
  - [x] Cells are NOT editable
  - [x] Text overflow handled (create a program name that is very long)
  - [x] Left aligned
- [x] **CREATED DATE**
    - [x] Sortable (and sorts correctly)
    - [x] Shows the correct date an invoice was created
    - [x]  Dates are in the form: `WeekDay Month Year`, e.g. `17 May 2008`
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [x] Left aligned
- [x] **STATUS**
    - [x] Shows the correct status for each stocktake
    - [x] All stocktakes have a status of: `"In Progress "` or `"Finalised"`
    - [x] Stocktake status is correctly updated
    - [x] Cells NOT editable
    - [x] Left aligned
- [x] **REMOVE**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Finalised stocktakes are not selectable
    - [x] Finalised rows indicate they are not selectable
    - [x] Rows not finalised are selectable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page
    - [x] Confirming the confirmation dialog deletes the stocktakes    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Finalised stocktake are not selectable

### Buttons

- [x] `"New Stocktake"`
  - [x] Button is displayed
  - [x] On press, navigates to the manage stocktake page

## WITH PROGRAMS

*Note: Having a program: Having a master list which is a program related to the store with a store tag matching a tag in this stores tag

### Buttons

- [x] `"New Stocktake"`
  - [x] Button is displayed
  - [x] On press, opens `ByProgramModal`

### Modals

- [x] **ByProgramModal**
  - [x] Must select steps in order - program, name or name if toggled
  - [x] Can back pedal steps, where the progress is adjusted correctly
  - [x] Name used is the name applied to the stock take
  - [x] The selected programs items are added to the stocktake
  - [x] Pressing OK will navigate to the `StocktakeEditPage` when a program stocktake
  - [x] Pressing OK will navigate to the `StocktakeManagePage` when NOT a program stocktake

Program Column sorting is missing. Created an issue #2773

**Comment by wlthomson** [comment]
Thanks @arjunSussol :tada:!

**Comment by ArpitaSussol** [comment]
### Testing 7.0.0

**Comment by joshxg** [comment]
Thanks @ArpitaSussol !!
