### ISSUE TITLE
TESTING: Stocktake Manage Page

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1241]
# TESTING 

This is an issue for testing `StocktakeManagePage`.

Please copy and paste this list of tests and post your results in a comment in this issue.

#### TESTER NOTES:
- Navigation Stack will always be `StocktakePage -> StocktakeManagePage` OR `StocktakePage -> StocktakeEditPage -> StocktakeManagePage`

### NAVIGATION

- [ ] Navigating to this page through creating a new stocktake (no items should be selected, no filters on items)
- [ ] Navigating to this page through the `"Manage Stocktake"` button from `StocktakeEditPage` (no filters applied, all items in stocktake should be auto selected)
- [ ] Pressing either the top left back button, or hardware back button navigates to the page prior to navigating to this page i.e. `StocktakeEditPage` for already existing, or `StocktakesPage` for a new stocktake
- [ ] Top left title is `"New Stocktake"` for a new stocktake OR `"Manage Stocktake"` for an existing stocktake

### Table

- [ ] Initial sort is by item name in ascending order
- [ ] If navigated to from `StocktakeEditPage` (all items in that stocktake are pre-selected)
- [ ] If navigated to from `StocktakePages` (no items are selected)

#### Row Press

- [ ] Pressing a row selects that row
    
#### Filtering

- [ ] Items are filtered by item name when a search term is entered
- [ ] Items are filtered by item code when a search term is entered
- [ ] Filtering is cleared when the search term is cleared

#### Columns 

- [ ] **CODE**
    - [ ] Item codes are correct
    - [ ] Cells NOT editable
    - [ ] Sortable (and sorting is correct)
    - [ ] left aligned
    - [ ] Text overflow handled (Create a item code that is very long)
- [ ] **NAME**
    - [ ] Sortable (and sorts correctly)
    - [ ] Names are correctly listed for every stocktake
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] Cells NOT editable
    - [ ] Text overflow handled (create an item name that is very long)
    - [ ] Left aligned
- [ ] **SELECTED**
    - [ ] Column NOT sortable
    - [ ] Cells NOT editable
    - [ ] Multiple rows are selectable
    - [ ] Selecting a row opens a confirmation dialog at the bottom of the page
    - [ ] Unselecting all rows closes the confirmation dialog at the bottom of the page
    - [ ] Confirming the confirmation dialog navigates to the next name
    - [ ] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog

### Toggles

- [ ] **Hide Stockouts*
  - [ ] Button is displayed
  - [ ] On press, switches between hiding/showing all items which have a current stock on hand of `0`
- [ ] **All items Selected**
  - [ ] Button is displayed
  - [ ] On press, switches between selecting/not selecting all items
  - [ ] if all items are selected, de-selecting an item removes this toggle

### Modals (this is the bottom pop up which should always be visible on this page)

*NOTE: as this page is not used for program stocktakes, "using programs" is used below to refer to making a general stocktake via the `ByProgramModal` (i.e. making a general stocktake in a store with programs enabled)

- [ ] **Confirm modal**
    - [ ] If not using programs and navigating from a new stocktake, no name is set
    - [ ] If using programs, name is set to name set in `ByProgramModal`
    - [ ] If no name is set, placeholder is `"Give your stocktake a name"`
    - [ ] Editing the entered name renames/names the stocktake
    - [ ] Not entering a name results in the default name for a stocktake (`"Stocktake - ${date}"`), where `date` is the current date)
    - [ ] Placeholder: `"Enter a stocktake name`"
    - [ ] Button text should be "Confirm" or "Create" dependent on confirming or creating a stocktake
    - [ ] Clicking confirm button navigates to a stocktake, where all items selected are the items of the stocktake

**Comment by wlthomson** [comment]
## TESTING

### Navigation to/from. **FAILED**.
*Note: Navigation Stack will always be StocktakePage -> StocktakeManagePage OR StocktakePage -> StocktakeEditPage -> StocktakeManagePage
- [ ] Navigating to this page through creaating a new stocktake [No items should be selected, no filters on items]. **FAILED (when new stocktake is made, have to navigate via "Manage stocktake" button)**.
- [x] Navigating to this page through Manage stocktaake button from StocktakeEditPage [ No filters applied, all items in stocktake should be selected]. **PASSED**.
- [x] Pressing either the top left back button, or hardware back button navigates to the page prior to navigating to this page [ as above ]. **PASSED**.
- [ ] Top left title is "Manage Stocktake". **FAILED (top-left title is the name of the stocktake)**.

### Sync. **PASSED**.
- [x] Syncing while on this page doesn't update this page. **PASSED**.

### Table. **FAILED**.
- [x] Initial sort is by Ascending item name. **PASSED**.
- [x] If navigated to from StocktakeEditPage - all items in that stocktake are pre-selected. **PASSED**.
- [x] If navigated to from StocktakePages - no items are selected. **PASSED**.

#### Row Press. **FAILED**.
- [ ] Pressing a row selects that row. **FAILED (pressing a row throws an error)**.
    
#### Filtering. **PASSED**.
- [x] Items are filtered by item name and item code when a search term is entered. **PASSED**.
- [x] Filtering is cleared when the search term is cleared. **PASSED**.

#### Columns 
- [x] **Code**. **PASSED**.
    - [x] Item codes are correct. **PASSED**.
    - [x] NOT editable. **PASSED**.
    - [x] Sortable (aand sorting is correct). **PASSED**.
    - [x] left aligned. **PASSED**.
    - [x] Text overflow handled (Create a item code that is very long). **PASSED**.
- [x] **Name**. **PASSED**.
    - [x] Sortable (and sorts correctly). **PASSED**.
    - [x] Names are correctly listed for every Stocktake. **PASSED**.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting. **PASSED**.
    - [ ] NOT editable. **PASSED**.
    - [ ] Text overflow handled (Create a Customer name that is very long). **PASSED**.
    - [ ] Left aligned. **PASSED**.
- [ ] **Selected**. **FAILED**.
    - [x] NOT sortable. **PASSED (not sure what this means, assuming "sorting applies to all items, invariant of selected items")**.
    - [x] NOT editable. **PASSED (not sure what this means, assuming "cannot edit cells of selected items")**.
    - [x] Multiple rows are selectable. **PASSED**.
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page. **PASSED**.
    - [x] Unselecting all rows closes the confirmation dialog at the bottom of the page. **PASSED**.
    - [x] Confirming the confirmation dialog navigates to the next name. **PASSED**.
    - [ ] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog. **FAILED (not sure how to test, no cancel button)**.

### Buttons. **PASSED**.
- [x] **HideStockouts**. **PASSED**.
    - [x] Toggle: switches between hiding/showing all items which have a quantity of 0. **PASSED**.
- [x] **All items Selected**. **PASSED**.
    - [x] Toggle: Switches between selecting/not selecting all items. **PASSED**.
    - [x] if all items are selected, de-selecting an item removes this toggle. **PASSED**.

### Modals. **FAILED**.
- [ ] **Confirm modal**. **FAILED**.
    - [x] If navigating from a new stocktake: default name is set. **PASSED**.
    - [ ] Editing the entered name renames/names the stocktake. **FAILED (stocktake name does not update)**.
    - [x] Not entering a name results in the default name for a stocktake [ "Stocktake - date" ]. **PASSED**.
    - [ ] Placeholder is : Enter a stocktake name . **FAILED (placeholder is default name specified above)**.
    - [ ] Button text should be "Confirm" or "Create" dependent on confirming or creating a stocktake. **FAILED (button is always "Confirm")**.
    - [x] Clicking confirm button navigates to a stocktake, where all items selected are the items of the stocktake. **PASSED**.

**Comment by joshxg** [comment]
>Navigating to this page through creaating a new stocktake [No items should be selected, no filters on items]. FAILED (when new stocktake is made, have to navigate via "Manage stocktake" button).

Interesting, I have tested and it navigates to the manage page. When it's navigating to the  stocktake edit page, are there any items in the stocktake?

related: https://github.com/openmsupply/mobile/blob/35b0f195fcd79c26f9d0cd0d20bfaefaecaf8005/src/pages/StocktakesPage.js#L59-L62

> Top left title is "Manage Stocktake". FAILED (top-left title is the name of the stocktake).

Issue here: #1337

> Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog. FAILED (not sure how to test, no cancel button).

>  Placeholder is : Enter a stocktake name . FAILED (placeholder is default name specified above).

This is referring to the placeholder - when the text field is blank

>  Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog. FAILED (not sure how to test, no cancel button).

This  was a mistake I got confused with another one sorry :(

> Pressing a row selects that row. FAILED (pressing a row throws an error).

Issue: #1327 


Issues made - couple confirmations regarding navigation before I make an issue please @wlthomson

**Comment by joshxg** [comment]
### NAVIGATION
- [x] Navigating to this page through creating a new Stocktake [No items should be selected, no filters on items]
- [x] Navigating to this page through Manage stocktake button from StocktakeEditPage [ No filters applied, all items in stocktake should be auto selected]
- [x] Pressing either the top left back button, or hardware back button navigates to the page prior to navigating to this page i.e. StocktakeEditPage for already existing, or StocktakesPage for a new stocktake
- [x] Top left title is "New Stocktake" for a new stocktake OR "Manage Stocktake" for an existing stocktake

### Table
- [x] Initial sort is by Ascending item name.
- [x] If navigated to from StocktakeEditPage - all items in that stocktake are pre-selected.
- [x] If navigated to from StocktakePages - no items are selected

#### Row Press
- [x] Pressing a row selects that row
    
#### Filtering
- [x] Items are filtered by item name and item code when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [x] **Code**
    - [x] Item codes are correct
    - [x] Cells NOT editable
    - [x] Sortable (and sorting is correct)
    - [x] left aligned
    - [x] Text overflow handled (Create a item code that is very long)
- [x] **Name**
    - [x] Sortable (and sorts correctly).
    - [x] Names are correctly listed for every Stocktake.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable
    - [x] Text overflow handled (Create a Customer name that is very long)
    - [x] Left aligned
- [x] **Selected**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting all rows closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog navigates to the next name
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog

### Buttons
- [x] **HideStockouts**
    - [x] Toggle: switches between hiding/showing all items which have a current stock on hand of 0
- [x] **All items Selected**
    - [x] Toggle: Switches between selecting/not selecting all items
    - [x] if all items are selected, de-selecting an item removes this toggle.

### Modals [ This is the bottom pop up which should always be visible on this page ]
- [x] **Confirm modal**
    - [x] If navigating from a new stocktake: No name is set [Should show the plaaceholder "Give your stocktake a name]
    - [x] Editing the entered name renames/names the stocktake
    - [x] Not entering a name results in the default name for a stocktake [ "Stocktake - date" ]
    - [x] Placeholder is : Enter a stocktake name
    - [x] Button text should be "Confirm" or "Create" dependent on confirming or creating a stocktake
    - [x] Clicking confirm button navigates to a stocktake, where all items selected are the items of the stocktake

**Comment by wlthomson** [comment]
> > Navigating to this page through creaating a new stocktake [No items should be selected, no filters on items]. FAILED (when new stocktake is made, have to navigate via "Manage stocktake" button).
> 
> Interesting, I have tested and it navigates to the manage page. When it's navigating to the stocktake edit page, are there any items in the stocktake?
> 
> related:
> 
> https://github.com/openmsupply/mobile/blob/35b0f195fcd79c26f9d0cd0d20bfaefaecaf8005/src/pages/StocktakesPage.js#L59-L62
> 
> > Top left title is "Manage Stocktake". FAILED (top-left title is the name of the stocktake).
> 
> Issue here: #1337
> 
> > Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog. FAILED (not sure how to test, no cancel button).
> 
> > Placeholder is : Enter a stocktake name . FAILED (placeholder is default name specified above).
> 
> This is referring to the placeholder - when the text field is blank
> 
> > Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog. FAILED (not sure how to test, no cancel button).
> 
> This was a mistake I got confused with another one sorry :(
> 
> > Pressing a row selects that row. FAILED (pressing a row throws an error).
> 
> Issue: #1327
> 
> Issues made - couple confirmations regarding navigation before I make an issue please @wlthomson

As per discussion, looks like this only occurs when programs are enabled. Issue created (#1425).

**Comment by diegoevangelisti** [comment]
### NAVIGATION
- [x] Navigating to this page through creating a new Stocktake [No items should be selected, no filters on items]
- [x] Navigating to this page through Manage stocktake button from StocktakeEditPage [ No filters applied, all items in stocktake should be auto selected]
- [x] Pressing either the top left back button, or hardware back button navigates to the page prior to navigating to this page i.e. StocktakeEditPage for already existing, or StocktakesPage for a new stocktake
- **(FAIL) Top left title is "New Stocktake" for a new stocktake OR "Manage Stocktake" for an existing stocktake --> It says "Manage Stockake"**

### Table
- [x] Initial sort is by Ascending item name.
- [x] If navigated to from StocktakeEditPage - all items in that stocktake are pre-selected.
- [x] If navigated to from StocktakePages - no items are selected

#### Row Press
- [x] Pressing a row selects that row
    
#### Filtering
- [x] Items are filtered by item name and item code when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [ ] **Code**
    - [x] Item codes are correct
    - [x] Cells NOT editable
    - [x] Sortable (and sorting is correct)
    - [x] left aligned
    - [ ] Text overflow handled (Create a item code that is very long)
- [ ] **Name**
    - [x] Sortable (and sorts correctly).
    - [x] Names are correctly listed for every Stocktake.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable
    - [ ] Text overflow handled (Create a Customer name that is very long)
    - [x] Left aligned
- [x] **Selected**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting all rows closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog navigates to the next name
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog

### Buttons
- [x] **HideStockouts**
    - [x] Toggle: switches between hiding/showing all items which have a current stock on hand of 0
- [x] **All items Selected**
    - [x] Toggle: Switches between selecting/not selecting all items
    - [x] if all items are selected, de-selecting an item removes this toggle.

### Modals [ This is the bottom pop up which should always be visible on this page ]
- [ ] **Confirm modal**
    - [x] If navigating from a new stocktake: No name is set [Should show the placeholder "Give your stocktake a name]
    - [x] Editing the entered name renames/names the stocktake
    - [x] Not entering a name results in the default name for a stocktake [ "Stocktake - date" ]
    - **(FAIL) Placeholder is : Enter a stocktake name . --> It says: "Give your stocktake a name"**
    - [x] Button text should be "Confirm" or "Create" dependent on confirming or creating a stocktake
    - [x] Clicking confirm button navigates to a stocktake, where all items selected are the items of the stocktake

**Comment by joshxg** [comment]
@diegoevangelisti 

> (FAIL) Top left title is "New Stocktake" for a new stocktake OR "Manage Stocktake" for an existing stocktake --> Should be "Manage Stocktake" and it's "Manage Stockake"

Issue: #1626 

> (FAIL) Placeholder is : Enter a stocktake name . --> It says: "Give your stocktake a name"

thanks for testing and updating the comment!

**Comment by Rebecca367** [comment]
There is no 
### Buttons
- [ ] **HideStockouts**
    - [ ] Toggle: switches between hiding/showing all items which have a current stock on hand of 0
- [ ] **All items Selected**
    - [ ] Toggle: Switches between selecting/not selecting all items
    - [ ] if all items are selected, de-selecting an item removes this toggle.
 in StocktakeManagePage

# TESTING 

This is an issue for testing `StocktakeManagePage`.

Please copy and paste this list of tests and post your results in a comment in this issue.

#### TESTER NOTES:
- Navigation Stack will always be StocktakePage -> StocktakeManagePage OR StocktakePage -> StocktakeEditPage -> StocktakeManagePage

### NAVIGATION
- [x] Navigating to this page through creating a new Stocktake [No items should be selected, no filters on items]
- [x] Navigating to this page through Manage stocktake button from StocktakeEditPage [ No filters applied, all items in stocktake should be auto selected]
- [x] Pressing either the top left back button, or hardware back button navigates to the page prior to navigating to this page i.e. StocktakeEditPage for already existing, or StocktakesPage for a new stocktake
- [x] Top right title is "New Stocktake" for a new stocktake OR "Manage Stocktake" for an existing stocktake

### Table
- [x] Initial sort is by Ascending item name.
- [x] If navigated to from StocktakeEditPage - all items in that stocktake are pre-selected.
- [x] If navigated to from StocktakePages - no items are selected

#### Row Press
- [x] Pressing a row selects that row
    
#### Filtering
- [x] Items are filtered by item name and item code when a search term is entered.
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [x] **Code**
    - [x] Item codes are correct
    - [x] Cells NOT editable
    - [x] Sortable (and sorting is correct)
    - [x] left aligned
    - [x] Text overflow handled (Create a item code that is very long)
- [x] **Name**
    - [x] Sortable (and sorts correctly).
    - [x] Names are correctly listed for every Stocktake.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] Cells NOT editable
    - [x] Text overflow handled (Create a Customer name that is very long)
    - [x] Left aligned
- [x] **REMOVE**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Multiple rows are selectable
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting all rows closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog navigates to the next name
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog

### Buttons
- [ ] **HideStockouts**
    - [ ] Toggle: switches between hiding/showing all items which have a current stock on hand of 0
- [ ] **All items Selected**
    - [ ] Toggle: Switches between selecting/not selecting all items
    - [ ] if all items are selected, de-selecting an item removes this toggle.

### Modals [ This is the bottom pop up which should always be visible on this page ]
- [x] **Confirm modal**
    - [x] If navigating from a new stocktake: No name is set [Should show the placeholder "Give your stocktake a name]
    - [x] Editing the entered name renames/names the stocktake
    - [x] Not entering a name results in the default name for a stocktake [ "Stocktake - date" ]
    - [x] Placeholder is : Enter a stocktake name
    - [x] Button text should be "Confirm" or "Create" dependent on confirming or creating a stocktake
    - [x] Clicking OK button navigates to a stocktake, where all items selected are the items of the stocktake

**Comment by joshxg** [comment]
@Rebecca367 

I have the toggle here on the top right hand side - you dont have this?

<img width="931" alt="image" src="https://user-images.githubusercontent.com/35858975/74400678-8c50a880-4e83-11ea-90d2-55c9e3d7dcd1.png">

**Comment by Rebecca367** [comment]
@joshxg 
No, would you like to take a look at it? I can show you when you have a MOMENT.

**Comment by Rebecca367** [comment]
@joshxg 
Some testing cases have been altered.

**Comment by wlthomson** [comment]
Updated for `v5.0.0`.

**Comment by diegoevangelisti** [comment]
### Testing 

### NAVIGATION

- [x] Navigating to this page through creating a new stocktake (no items should be selected, no filters on items)
- [x] Navigating to this page through the `"Manage Stocktake"` button from `StocktakeEditPage` (no filters applied, all items in stocktake should be auto selected)
- [x] Pressing either the top left back button, or hardware back button navigates to the page prior to navigating to this page i.e. `StocktakeEditPage` for already existing, or `StocktakesPage` for a new stocktake
- [x] Top left title is `"New Stocktake"` for a new stocktake OR `"Manage Stocktake"` for an existing stocktake 

### Table

- [x] Initial sort is by item name in ascending order
- [x] If navigated to from `StocktakeEditPage` (all items in that stocktake are pre-selected)
- [x] If navigated to from `StocktakePages` (no items are selected)

#### Row Press

- [x] Pressing a row selects that row
    
#### Filtering

- [x] Items are filtered by item name when a search term is entered
- [x] Items are filtered by item code when a search term is entered
- [x] Filtering is cleared when the search term is cleared

#### Columns 

- [x] **CODE**
    - [x] Item codes are correct
    - [x] Cells NOT editable
    - [x] Sortable (and sorting is correct)
    - [x] left aligned
    - [x] Text overflow handled (Create a item code that is very long)
- [x] **NAME**
    - [x] Sortable (and sorts correctly)
    - [x] Names are correctly listed for every stocktake
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [x] Cells NOT editable
    - [x] Text overflow handled (create an item name that is very long)
    - [x] Left aligned
- [ ] **SELECTED**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Multiple rows are selectable
    - [ ] Selecting a row opens a confirmation dialog at the bottom of the page -**FAILED**- 
    - [ ] Unselecting all rows closes the confirmation dialog at the bottom of the page  -**FAILED**- 
    - [x] Confirming the confirmation dialog navigates to the next name
    - [ ] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog  -**FAILED**- 

**NOTE**: The confirmation dialog pops up when I open the page, even before selecting any row. And also is still open when unselecting all items. Issue: #2768

### Toggles

- [x] **Hide Stockouts*
  - [x] Button is displayed
  - [x] On press, switches between hiding/showing all items which have a current stock on hand of `0`
- [x] **All items Selected**
  - [x] Button is displayed
  - [x] On press, switches between selecting/not selecting all items
  - [x] if all items are selected, de-selecting an item removes this toggle

### Modals (this is the bottom pop up which should always be visible on this page)

*NOTE: as this page is not used for program stocktakes, "using programs" is used below to refer to making a general stocktake via the `ByProgramModal` (i.e. making a general stocktake in a store with programs enabled)

- [x] **Confirm modal**
    - [x] If not using programs and navigating from a new stocktake, no name is set
    - [x] If using programs, name is set to name set in `ByProgramModal`
    - [x] If no name is set, placeholder is `"Give your stocktake a name"`
    - [x] Editing the entered name renames/names the stocktake
    - [x] Not entering a name results in the default name for a stocktake (`"Stocktake - ${date}"`), where `date` is the current date)
    - [x] Placeholder: `"Give your stocktake a name`"
    - [x] Button text should be "Confirm" or "Create" dependent on confirming or creating a stocktake
    - [x] Clicking confirm button navigates to a stocktake, where all items selected are the items of the stocktake

**Comment by wlthomson** [comment]
Thanks @diegoevangelisti :tada:!

**Comment by ArpitaSussol** [comment]
Testing V.7.0.0

**Comment by joshxg** [comment]
Thanks @ArpitaSussol !!
