### ISSUE TITLE
TESTING: Stock Page

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1245]
This is an issue for testing `StockPage`.

Please copy and paste this list of tests and post your results in a comment in this issue.

# TESTING

### USER GUIDE
https://docs.msupply.foundation/en:mobile:user_guide:current_stock

### NAVIGATION

- [ ] Can navigate to this page through the Menu Page using `"Current Stock"` button.

### TABLE

- [ ] Lists all items visible to this store

#### Row Press

- [ ] Pressing on a row opens a small popup at the bottom of the screen
- [ ] Pop up closes when focusing the search bar when it is open
- [ ] Pop up is scrollable when a large number of batches
- [ ] Pop up displays correct category name for the item
- [ ] Pop up displays correct department name for the item
- [ ] Pop up displays correct number of batches for the item
- [ ] Pop up displays correct batch names for the item
- [ ] Pop up displays correct category name for the item
- [ ] Pop up batches all have the correct quantity for the item
- [ ] Pop up batches all have the correct expiry date for the item
    
#### Filtering

- [ ] Items are filtered by name
- [ ] Items are filtered by code
- [ ] Filtering is cleared when the search term is cleared

#### Columns 

- [ ] **CODE**
    - [ ] Sortable (and sorts correctly)
    - [ ] Items have the correct code
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] NOT editable
    - [ ] Left aligned
- [ ] **NAME**
    - [ ] Sortable (and sorts correctly)
    - [ ] Items have the correct name
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [ ] NOT editable
    - [ ] Text overflow handled (create an item name that is very long)
    - [ ] Left aligned
- [ ] **QUANTITY**
    - [ ] Sortable (and sorts correctly)
    - [ ] NOT Editable
    - [ ] Items have the correct current stock 
    - [ ] Right aligned
- [ ] **RETURN**
    - [ ] Displays an arrow icon
    - [ ] NOT editable
    - [ ] Centre aligned
    - [ ] On press, opens supplier credit modal (see supplier credit tests)

**Comment by wlthomson** [comment]
## TESTS

### Navigation to/from
- [x] Can navigate to this page through the Menu Page - Current Stock button. **PASSED**.

### Sync
- [x] Sync occuring while on this page does update this page. **PASSED**.

### Table
- [x] Lists all items visible to this store. **PASSED**.

#### Row Press
- [x] Pressing on a row opens a small popup at the bottom of the screen. **PASSED**.
- [x] Pop up scrollable when a large number of batches. . **PASSED**. 
- [x] pop up clsoes when focusing the search bar when it is open. **FAILED (search bar does not close)**.
- [x] Pop up. **PASSED**.
    - [x] displays correct category name for the item. **PASSED**.
    - [x] displays correct department name for the item. **PASSED**.
    - [x] displays correct number of batches for the item. **PASSED**.
    - [x] displays correct batch names for the item. **PASSED**.
    - [x] Each batch has the correct quantity for the item. **PASSED**.
    - [x] Each batch has the correct expiry date for the item. **PASSED**.
    - [x] displays correct category name for the item. **PASSED**.
    
#### Filtering
- [x] items are filtered by Item Name or Item Code. **PASSED**.
- [x] Filtering is cleared when the search term is cleared. **PASSED**.

#### Columns 
- [x] **Item code**. **PASSED**.
    - [x] Sortable (and sorts correctly). **PASSED**.
    - [x] Items have the correct Item Code. **PASSED**.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting. **PASSED**.
    - [x] NOT editable. **PASSED**.
    - [x] Left aligned. **PASSED**.
- [ ] **Item Name**
    - [x] Sortable (and sorts correctly).
    - [x] Item Names are correct for an item in the Supplier Requisition.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] NOT editable. **PASSED**.
    - [x] Text overflow handled (Create an item name that is very long). **PASSED**.
    - [x] Left aligned. **PASSED**.
- [x] **Total quantity** (**quantity**?)
    - [x] Sortable (and sorts correctly). **PASSED**.
    - [x] NOT Editable. **PASSED**.
    - [x] Right aligned. **PASSED**.
    - [x] Displays the current stock for that item. **PASSED**.
    - [x] Is updated when adjustments are made and requisition is revistited. **PASSED**.

**Comment by joshxg** [comment]
> pop up closes when focusing the search bar when it is open.

Issue: #1324 

Issues made - thanks for testing!

**Comment by joshxg** [comment]
# TESTING

### NAVIGATION
- [x] Can navigate to this page through the Menu Page - Current Stock button.


### TABLE
- [x] Lists all items visible to this store.

#### Row Press
- [x] Pressing on a row opens a small popup at the bottom of the screen
- [x] Pop up scrollable when a large number of batches
- [x] pop up clsoes when focusing the search bar when it is open.
- [x] Pop up
    - [x] displays correct category name for the item
    - [x] displays correct department name for the item
    - [x] displays correct number of batches for the item
    - [x] displays correct batch names for the item
    - [x] Each batch has the correct quantity for the item
    - [x] Each batch has the correct expiry date for the item
    - [x] displays correct category name for the item
    
#### Filtering
- [x] items are filtered by Item Name or Item Code
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [x] **Item code**
    - [x] Sortable (and sorts correctly).
    - [x] Items have the correct Item Code.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] NOT editable.
    - [x] Left aligned
- [x] **Item Name**
    - [x] Sortable (and sorts correctly).
    - [x] Item Names are correct for an item in the Supplier Requisition.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] NOT editable
    - [x] Text overflow handled (Create an item name that is very long)
    - [x] Left aligned
- [x] **Total quantity**
    - [x] Sortable (and sorts correctly).
    - [x] NOT Editable
    - [x] Right aligned
    - [x] Displays the current stock for that item
    - [x] Is updated when adjustments are made and requisition is revistited

**Comment by Rebecca367** [comment]
Tests for below items couldn't get elaborated 

- Pop up scrollable when a large number of batches
=> there is no scrollable bar when a large of batches were created

- pop up clsoes when focusing the search bar when it is open.
=> there is no pop up when search bar was opened

- Text overflow handled (Create an item name that is very long)
=> couldn't see how it gets handled

-   Is updated when adjustments are made and requisition is revistited
=> couldn't see quantities under stocktake name when revisit requisition

**Comment by Rebecca367** [comment]
done and move to done list

**Comment by CarlosNZ** [comment]
> [ ] Text overflow handled (Create an item name that is very long)

The 'new item' interface in mSupply tops out at 80 chars for the name, which is more than long enough for the mobile NAME display. (So can't see what happens with text overflow.)

**Comment by Rebecca367** [comment]
**- [FAILED ] Pop up scrollable when a large number of batches
 // when click on return column will go to "Available Credits for the item",  but click on sorting batch name msupply closes itself.**

# TESTING

### USER GUIDE
https://docs.msupply.foundation/en:mobile:user_guide:current_stock

### NAVIGATION
- [x] Can navigate to this page through the Menu Page - Current Stock button.


### TABLE
- [x] Lists all items visible to this store.

#### Row Press
- [x] Pressing on a row opens a small popup at the bottom of the screen
**- [FAILED ] Pop up scrollable when a large number of batches
 // when click on return column will go to "Available Credits for the item",  but click on sorting batch name msupply closes itself.**

- [x] pop up closes when focusing the search bar when it is open.
- [x] Pop up
    - [x] displays correct category name for the item
    - [x] displays correct department name for the item
    - [x] displays correct number of batches for the item
    - [x] displays correct batch names for the item
    - [x] Each batch has the correct quantity for the item
    - [x] Each batch has the correct expiry date for the item
    - [x] displays correct category name for the item
    
#### Filtering
- [x] items are filtered by Item Name or Item Code
- [x] Filtering is cleared when the search term is cleared.

#### Columns 
- [x] **Item code**
    - [x] Sortable (and sorts correctly).
    - [x] Items have the correct Item Code.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] NOT editable.
    - [x] Left aligned
- [x] **Item Name**
    - [x] Sortable (and sorts correctly).
    - [x] Item Names are correct for an item in the Stocktakepage.
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] NOT editable
    - [x] Text overflow handled (Create an item name that is very long)
    - [x] Left aligned
- [x] **Total quantity**
    - [x] Sortable (and sorts correctly).
    - [x] NOT Editable
    - [x] Right aligned
    - [x] Displays the current stock for that item

**Comment by wlthomson** [comment]
Updated for `v5.0.0`.

**Comment by DhanyaHerath** [comment]
# TESTING - v5.0.0

### NAVIGATION

- [x] Can navigate to this page through the Menu Page using `"Current Stock"` button.


### TABLE

- [xh] Lists all items visible to this store

#### Row Press

- [x] Pressing on a row opens a small popup at the bottom of the screen
- [ ] Pop up closes when focusing the search bar when it is open Issue: https://github.com/openmsupply/mobile/issues/2760
- [x] Pop up is scrollable when a large number of batches
- [x] Pop up displays correct category name for the item
- [x] Pop up displays correct department name for the item
- [x] Pop up displays correct number of batches for the item
- [x] Pop up displays correct batch names for the item
- [x] Pop up batches all have the correct quantity for the item
- [x] Pop up batches all have the correct expiry date for the item
    
#### Filtering

- [x] Items are filtered by name
- [x] Items are filtered by code
- [x] Filtering is cleared when the search term is cleared

#### Columns 

- [x] **CODE**
    - [x] Sortable (and sorts correctly)
    - [x] Items have the correct code
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [x] NOT editable
    - [x] Left aligned
- [x] **NAME**
    - [x] Sortable (and sorts correctly)
    - [x] Items have the correct name
    - [x] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [x] NOT editable
    - [x] Text overflow handled (create an item name that is very long)
    - [x] Left aligned
- [x] **QUANTITY**
    - [x] Sortable (and sorts correctly)
    - [x] NOT Editable
    - [s] Items have the correct current stock 
    - [s] Right aligned
- [x] **RETURN**
    - [x] Displays an arrow icon
    - [x] NOT editable
    - [x] Centre aligned
    - [x] On press, opens supplier credit modal (see supplier credit tests)

**Comment by wlthomson** [comment]
Nice:tada:! Thanks @DhanyaHerath!

**Comment by ArpitaSussol** [comment]
Tested in 7.0.0.rc10

**Comment by joshxg** [comment]
@ArpitaSussol 🎉 Thanks 🥇
