### ISSUE TITLE
Update lockfile

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1254]
## Describe the bug

The develop branch currently does not build, throwing an error when building `react-native-gesture-handler`. The app builds successfully if the yarn lockfile is reverted to before  commit `f8584eac3b82de835569fb17b7bcc685a951aaad` (most recent lockfile update).

### To reproduce

1. Checkout develop.
3. Run `rm -r ./node_modules && react-native run-android`.
4. See error.

### Expected behaviour

The app should build.

### Version and device info

- App version: 2.3.6.
- Tablet model: N/A.
- OS version: MacOS.

### Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #1255
