### ISSUE TITLE
RealmExplorer page

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1263]
## The suggestion

`RealmExplorer` page is using the old `DataTable` and should be refactored with all the other pages. This is a page which can be accessed in admin mode to browse the currently opened relam.

**Why?**
Consistency in the app, faster and that would mean being able to remove a large number of old dependencies that aren't used anywhere else.

## Describe alternatives you've considered

Not bothering

## Additional context

Not sure if should bother? @mark-prins @Chris-Petty @wlthomson @andreievg

**Comment by wlthomson** [comment]
I'd say go for it. IMO it makes sense to migrate off the old `DataTable` completely (or at least as much as possible).

**Comment by mark-prins** [comment]
>  able to remove a large number of old dependencies that aren't used anywhere else

yep. go for it!

**Comment by joshxg** [comment]
This is a potential blocker for #1165 -- not sure how best to handle this. Has it begun @wlthomson ? To remove old dependencies, the old page needs to be deleted which might cause some merge problems

**Comment by wlthomson** [comment]
> This is a potential blocker for #1165 -- not sure how best to handle this. Has it begun @wlthomson ? To remove old dependencies, the old page needs to be deleted which might cause some merge problems

Currently working on it. If its a major blocker, best approach is probably to delete the old page and merge it back in afterwards?

**Comment by joshxg** [comment]
ok

**Comment by wlthomson** [comment]
Fixed by #1263.

**Comment by joshxg** [comment]
@wlthomson 

## Testing

- [x] All tables display correctly.
- [x] Filter strings work. -- hard to test 🤣 but did a lot, and works well
- [x] Table state is reset when the filter string is cleared.
- [x] No errors thrown when the search string is cleared.


Can clear the Object search while having a filter which is a little weird, but not a biggie.


I think having this editable in dev mode only would be cool, what ya think?

**Comment by wlthomson** [comment]
> @wlthomson
> ## Testing
> 
>     * [x]  All tables display correctly.
> 
>     * [x]  Filter strings work. -- hard to test 🤣 but did a lot, and works well
> 
>     * [x]  Table state is reset when the filter string is cleared.
> 
>     * [x]  No errors thrown when the search string is cleared.
> 
> 
> Can clear the Object search while having a filter which is a little weird, but not a biggie.
> 
> I think having this editable in dev mode only would be cool, what ya think?

Agree. I think that could be really helpful for debugging/testing.
