### ISSUE TITLE
Update RegimenDataModal to use getPageReducer

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1289]
## The suggestion

Currently `RegimenDataModal` defines its own actions and reducer and uses the standard `getReducer` hook. Suggestion is to refactor to use `getPagesReducer` and move initialisation logic to `getPageInitialiser`.

**Why?**

AFAIK, all existing pages/modals with flux-style state management use `getPagesReducer`. Will make maintaining the code a lot easier if there is only one place to manage actions, reducers for pages.

## Describe alternatives you've considered

Leaving as is?

## Additional context

N/A.

**Comment by joshxg** [comment]
I basically hate this modal (and `StocktakeBatchModal`) - any 'modal' that requires state and indepth logic shouldn't be a modal. I hacked these together to be a little consistent and to remove the need for all the extra dependencies, with an eventual goal of finding an alternative solution to having a secondary table in a page.

To conclude: I disagree as it was easy to just write a quick reducer and I hope to remove this as a modal

**Comment by Chris-Petty** [comment]
@wlthomson @joshxg Just regarding milestone, I think we should keep 3.0.0 down to Data table refactor

**Comment by joshxg** [comment]
@Chris-Petty and what is already in develop? what about badges? maybe not the best place for this discussion

**Comment by wlthomson** [comment]
> To conclude: I disagree as it was easy to just write a quick reducer and I hope to remove this as a modal

Sounds good, probably best to address that in a dedicated issue. Closing.
