### ISSUE TITLE
Sorting performance

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1294]
@Chris-Petty @mark-prins @wlthomson 

## Is your feature request related to a problem? Please describe.

Sorting a list of ~3500 takes too long (~3 seconds) : SPECIFICALLY for strings as `localCompare` is used and it's slow

- Currently we use JS sorting to sort the `data` object of the `DataTable`. 
    -  thought it would be fine (still sorta is)
    - avoids a lot of complexities
    
Info:
- `backingData` is the base array of data, as it needs to be filtered etc.
- Realm can't sort based on getters (i.e. `totalQuantity` of an item is the `sum` of all `batch quantities)
- We use a `type` lookup - `totalQuantity: number`, `otherPartyName: string` 

Solutions:

1. Add a `Realm` type and also pass the `backingData` - then, sorting would occur on this. However, this unfilters the data. So, need to figure out the filtering and apply that again when sorting by a `realm` type. **added complexity**
2. Use `current/past` (finalized/not finalized) toggle. **No one needs to see a list of 3,000+ things. Consist UI** (My choice)
3. some combination

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/35858975/65293369-22bbbf00-dbaf-11e9-9f32-f49aac53ed4c.png">

4. Could also just use native `sort()` without passing a parameter for somethings, but I don't know if this is a feasible option (sort() with no function parameter performs almost as well as realm - 0.2 (realm) v 0.5 seconds(native sort) )

5. Implement a more efficient algorithm for our specific use case like a modified merge sort (my real choice 1)

6. figure out what compare object should be used for specific languages that are used https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare (option 1) [*Note: I dunno if this is possible in react-native as it would require the `Intl` window object*]

## Describe the solution you'd like

Option 2 + option 6 ?

## Describe alternatives you've considered

Doing nothing it's not that bad

## Additional context

Possibly can think about eventually having patients and having to sort them. However I really don't think having 1000's of patients in a table is really a great idea, so I don't think it should be considered

**Comment by wlthomson** [comment]
I think the UI approach (limiting the results which are sorted) makes the most sense. I can definitely see a slow-down when a custom comparison method is used (which is probably because the underlying implementation can't make as many assumptions for purposes of optimising). Even if we improve the performance, it'll always be a linear function of the input size (n log n to be more precise). If we are using mobile on bigger data sets, it's going to start slowing down even with the best algorithm in the world.

Re: the best algo in the world, I'd also be surprised if rolling our own custom sort would be any faster unless there is a specific aspect of our data that we can leverage to make some kind of shortcut. I can't find what sorting algo react-native + Android uses, but it's likely to be some kind of hybrid mix of mergesort/quicksort with insertion sort, which is usually pretty speedy.

**Comment by mark-prins** [comment]
agree with limiting the number of results shown in some way
perhaps necessary to have a hard limit on number of items as well as the filter (past/current) as the past could still end up being a big list?

**Comment by joshxg** [comment]
Definitely would still be a large list

Can either:
- if you want to look at ooold transactions, have to look on desktop - and then trim any X+ months old
- Add a secondary filtering option with a date range

I think these are the only options. 

Would it be fair to implement the current/past toggle which has some sort of 'precedence' in the app and will help at least somewhat with the performance and to sort out the length of the 'past' table in a new issue, possibly requiring more feedback? Or should it just be done with this?

**Comment by mark-prins** [comment]
I was also wondering about a date filter of some kind, or a link to 'show more' or lazy loading the list in batched quantities - with a scroll point as the trigger.

> Would it be fair to implement the current/past toggle etc..

yes - I agree. Both to defaulting to current items and keeping the app snappy for most people and usage, and pushing the loading problem onto another issue

**Comment by Chris-Petty** [comment]
Missed the boat but agree with option 2 as a minimum.

**Comment by joshxg** [comment]
Fixed by #1306
