### ISSUE TITLE
Add install script for faster .apk testing

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1319]
## Is your feature request related to a problem? Please describe.

Testing an .apk involves:

- Getting the release key.
- Building the .apk(s).
- Uninstall the latest build on the device.
- Installing the target .apk on the device.

The last two steps can be automated with a few lines of code.

## Describe the solution you'd like

Add an `deploy.sh` script to `dev_scripts`.

## Describe alternatives you've considered

Continue doing it manually.

## Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #1320
