### ISSUE TITLE
Sync wipes out requested quantities for manually created customer requisitions

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1326]
## Describe the bug

When a customer requisition is manually created, the `"Customer requested"` field is wiped out when syncing to mobile (after syncing back from mobile, the field is reset to `0`).

### To reproduce

1. On desktop, go to `Requisitions -> New customer requisition`.
2. Add an item and set a value for `"Customer requested"`.
3. Manually sync the requisition to mobile.
4. Open the requisition in mobile, note that `"Requested quantity"` has not been updated.
5. Edit another field to trigger an update and manually sync back to desktop.
6. Reopen the requisition on desktop, note that the `"Customer requested"` field has been reset to `0`.

### Expected behaviour

The field should be correctly synced to and from desktop and mobile.

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1244#issuecomment-537723537.

**Comment by joshxg** [comment]
sorry, to clarify: 

- `CustomerRequisition` created on DESKTOP
- sync to MOBILE
- lines are ZERO ON MOBILE

OR

- `CustomerRequisition` created on DESKTOP
- sync to MOBILE
- lines editted
- sync to DESKTOP
- lines are ZERO ON DESKTOP

**Comment by joshxg** [comment]
Have tried to replicate using standard workflow - i.e. creating internal order and receiving a customer requisition. I think since this is a real edge case and shouldn't be happening anyway, we can close this?

**Comment by wlthomson** [comment]
> Have tried to replicate using standard workflow - i.e. creating internal order and receiving a customer requisition. I think since this is a real edge case and shouldn't be happening anyway, we can close this?

Yeah, I believe to replicate it you have to "break" mSupplys permission system. Thought it was worth flagging up but I think we can close this.
