### ISSUE TITLE
CustomerRequisitionPage button for requested quantities does not update fields

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1328]
## Describe the bug

When the `"Use Requested Quantities"` button is clicked on a customer requisition, the `"Supply this invoice"` field is not updated (tested with various values).

E.g. of before and after button is clicked (same screenshot):

![#1328-requested-quantities-do-not-updated](https://user-images.githubusercontent.com/43223637/66090310-4f280000-e5df-11e9-91f4-64b25afce309.png)

### To reproduce

1.  On desktop, create and finalise an internal invoice for the mobile store (request at least `1` of some item).
2. The previous step should trigger new records for mobile. Manually sync to update.
3. Open the response customer requisition in mobile, note that the `"Requested quantity"` field contains the value you requested in the internal invoice.
4. Click `"Use Requested Quantities"`. Note that `"Supply this invoice"` does not change.

### Expected behaviour

The values in the `"Suggested quantity"` column should appear in the `"Supply this invoice"` column when `"Use Requested Quantities"` is clicked.

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1244#issuecomment-537723537.

**Comment by joshxg** [comment]
Maybe I can get lucky and you've missed a step or something? I'm not able to replicate, so if you're not it might be more complicated than I hoped 🤣 

![requestedToSuggested](https://user-images.githubusercontent.com/35858975/66274976-a92b0d00-e8e0-11e9-89fd-e000c431e4ea.gif)

**Comment by wlthomson** [comment]
Tests again and can still replicate on latest `#1043-data-table-rewrite`. Could be a data or config issue?
