### ISSUE TITLE
Items with zero quantity are not pruned from automatically created customer invoices

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1329]
## Describe the bug

When a customer requisition is finalised on mobile, a customer invoice is automatically created. This customer invoice should contain the same items are the requisition, with the exception of items with a supplied quantity of `0`. Currently, `0` quantity items are not being pruned and are still appearing in the customer invoice.

Example:

![#1329-ci-no-prune-zero-quantity](https://user-images.githubusercontent.com/43223637/66090557-7501d480-e5e0-11e9-8f41-c466fa8fb7f8.png)

### To reproduce

1. Create a customer requisition containing multiple items, at least one of which has a supplied quantity of `0`.
2. Finalise the customer requisition. This will create a new customer invoice.
3. Open the newly created customer invoice. Note that the item(s) with supplied quantities of `0` have not been pruned.

### Expected behaviour

Items with supplied quantities of `0` should not appear in the customer invoice.

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1244#issuecomment-537723537.

**Comment by joshxg** [comment]
When a customer requisition is finalised, it finalises the linked customer invoice transaction (It already is created, technically, just doesn't show in the list). This invoice isn't finalised. The linked customer invoice also has a default comment of "From customer requisition X" - which this invoice doesn't have.

This is a lot more problematic than first thought. 

Actually, could this be the wrong invoice opened?

**Comment by wlthomson** [comment]
> When a customer requisition is finalised, it finalises the linked customer invoice transaction (It already is created, technically, just doesn't show in the list). This invoice isn't finalised. The linked customer invoice also has a default comment of "From customer requisition X" - which this invoice doesn't have.
> 
> This is a lot more problematic than first thought.
> 
> Actually, could this be the wrong invoice opened?

Looks like I attached the wrong screenshot. Unable to replicate on latest `#1043-data-table-rewrite` so will go ahead and close 👍 .
