### ISSUE TITLE
Customer requisitions not filtering by customer name

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1334]
## Describe the bug

Customer requisitions are filtering correctly by requisition number, but not by customer name. Entering any non-numerical character into the search bar is removing all requisitions from the table.

### To reproduce

1. Go to `"Customer Requisitions"`.
2. Click the search bar to update the focus.
3. Enter some or all of a customer name listed in the `"Customer"` column.
4. See error.

### Expected behaviour

The requisitions should be filtered by customer name.

### Version and device info

- App version: 2.3.6.
- Tablet model: TB-X304L (replicated on emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1243#issuecomment-538796738.

**Comment by joshxg** [comment]
Sorry, this appears to be an incorrect test: 

https://github.com/openmsupply/mobile/blob/55057105f3da721188cc8761a65cf253aa74cca9/src/pages/CustomerRequisitionsPage.js#L58
