### ISSUE TITLE
Manage stocktake page title

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1337]
## Describe the bug

Manage stocktake page is using the name of the stocktake, rather than `manage_stocktake` navstring

### To reproduce

1. Go to `StocktakeEditPage`
2. Click on `Manage Stocktake`

### Expected behaviour

Should be the correct string

### Version and device info

#1043 branch

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1337.
