### ISSUE TITLE
Supplier Requisition months stock

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1338]
## Describe the bug

Months stock in `SupplierRequisition` not updating

### To reproduce

1. Go to `SupplierRequisitionPage`
2. Click on Months supplier
3. Scroll down to Edit, press ok

### Expected behaviour

Should update in the UI

### Version and device info

Data table branch #1043 

### Additional context

I think to do with page info memoizing, maybe not just a guess

**Comment by wlthomson** [comment]
Fixed by #1338.
