### ISSUE TITLE
Stocktake not finalising without focussing on quantity

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1339]
## Describe the bug

When a new stocktake is created via `StocktakeManagePage`, the actual quantities of the chosen items are automatically populated to the snapshot quantities. When attempting to finalise the resulting stocktake, the user is prompted with the following error:

![Screen Shot 2019-10-11 at 10 26 07 AM](https://user-images.githubusercontent.com/43223637/66607842-9df21d00-ec11-11e9-9534-32c82d52166d.png)

### To reproduce

1. Go to "Stocktakes".
2. Click on "New Stocktake".
3. Select some items and create a new stocktake.
4. Attempt to finalise the new stocktake.
5. See error.

### Expected behaviour

Should be able to finalise a stocktake with the default actual quantities?

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

N/A.

**Comment by Chris-Petty** [comment]
Snapshot quantities shouldn't automatically fill counted quantity. If #1343 has done that, then that change needs to be undone.

**Comment by joshxg** [comment]
Closed by #1346
