### ISSUE TITLE
User is not prevented from "removing" finalised transactions 

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1340]
## Describe the bug

Once a transaction is finalised, it should not be able to be deleted. This is indicated on by an appropriate "cross" icon in "Remove" column.

On clicking the icon, the user is presented with the same modal as when deleting a row for an unfinalised requisition/invoice ("are you sure you want to remove these items?"). When the user clicks "Remove", nothing happens.

### To reproduce

1. Go to "Supplier Requisitions".
2. Click on "Past".
3. Click the cross icon in the "Remove" column on a finalised requisition.
4. See error.

### Expected behaviour

Deletion should be disabled for finalised invoices/requisitions.

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1236#issuecomment-540841062, https://github.com/openmsupply/mobile/issues/1238#issuecomment-540826594, https://github.com/openmsupply/mobile/issues/1240#issuecomment-540835164.

**Comment by joshxg** [comment]
this is fixed here https://github.com/openmsupply/mobile/pull/1331
