### ISSUE TITLE
StocktakeEditPage updates

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1343]
## Describe the bug

Few bugs in `StocktakeEditPage` highlighted in testing: https://github.com/openmsupply/mobile/issues/1242#issuecomment-540822222

- name `PageInfo` is disabled
- Items are set to the snapshot quantity automatically
- Placeholder does not show

additional:

- can't remove items  from the stocktake
- Bottom confirm modal goes away when nothing is selected, but should always stay

### To reproduce

1. 
- try to edit a name in a stocktake
- see error

2.
- Add an item to a stocktake
- see error

3. 
- try to remove an item from a stocktake
- see error

### Expected behaviour

The opposite of the bugs

### Version and device info

`DataTable` feature branch in development

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1346.

**Comment by wlthomson** [comment]
## TESTS

- [x] When editing a cell that should be numeric, the numeric keyboard is opened
- [x] When adding an item to a stocktake, initial state is to be NOT COUNTED
- [x] When changing a value in a stocktake row, the state is the value entered
- [x] Can remove items from a Stocktake
- [x] When finalising a Stocktake, Not Counted rows are pruned
