### ISSUE TITLE
StocktakesPage and CustomerRequisitionsPage initial state incorrect

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1344]
## Describe the bug

The `StocktakesPage` initial sort is incorrect, it is in ascending order where it should be descending order

The `CustomerRequisitionsPage` filtered items state is incorrect. It shows both in progress and finalised requisitions initially

### To reproduce

1. Go to `StocktakesPage`

1. Go to `CustomerRequisitionsPage`

### Expected behaviour

Should be the opposite sort order, on the same field.

### Version and device info

DataTable refactor branch in development

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1347.

**Comment by wlthomson** [comment]
## TESTS

- [x] When navigating to CustomerRequisitionsPage with BOTH requisitions created - FINALISED and NOT FINALISED, the toggle is correct
- [x] When navigating to StocktakesPage, using the toggle correctly holds the sorting of the rows
