### ISSUE TITLE
Remove autocorrect when initialising primary server url

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1350]
## Is your feature request related to a problem? Please describe.

When initialising the mobile site, the primary server URL is case-sensitive. This can be frustrating as text entry modal autocorrects the first word capital case, which in this case is the network protocol (e.g. "`Http`").

## Describe the solution you'd like

Prevent autocorrection when entering server URL.

## Describe alternatives you've considered

Alternative is to make the network address ignore case. This seems more hacky and could could user confusion (e.g. user will probably correct the capitalisation as they will likely assume it is case sensitive). 

## Additional context

Only a small concern, as not really user functionality. Each site is only setup once, and probably not by the end user him/herself.

**Comment by joshxg** [comment]
Closed by #1351

**Comment by joshxg** [comment]
# TESTING 

- [x] Primary server URL does not autocorrect (in particularly, does not autocapitalise).
