### ISSUE TITLE
Bug in RequisitionItem supplied quantity setter

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1354]
## Describe the bug

Bug found while replicating #1328. 

Sometimes when updating `"Supply this invoice"` for a requisition line, the value reverts to its previous value (even if the value is valid, i.e. is less than current stock). This seems to be caused by the following lines in `setSuppliedQuantity`:

```
const transactionItem = this.linkedTransactionItem;

if (!transactionItem) return;
```

Logging indicates that `this.linkedTransactionItem` is `undefined` for the problematic requisition lines.

### To reproduce

I can't find a common factor in the problematic requisitions, but it seems to be requisition scoped (i.e. if a requisition line has no linked transaction item, then no requisitions lines associated with its parent do).

### Expected behaviour

All requisition lines should have linked transaction items (not aware of any exceptions to this constraint, but someone with more domain knowledge may know of some).

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

Possibly related to #1328.

**Comment by joshxg** [comment]
only thing I can think of is some combination of syncing a customer requisition and something going wrong the the creation of a customer invoice.

my understanding:

- After sync, the `PostSyncProcessor` runs. This creates a queue of functions to run.
- When a `Requisition` is synced, the `generateFunctionsForRequisition` function runs, which enqueues some functions to run after syncing is complete. 
- This will enqueue a call to `Requisition.createCustomerInvoice` for unfinalised customer requisitions. 
- This creates a CI for a customer requisition and links the two together (supplier requisitions have no linked transaction).

Can ya either give instructions on how you replicated, a data file or a realm file?

Or if you want to look into it: I'd be looking to check all the conditions which would result in the linking. I.e. the status of the Customer Requisition (only links if it is not finalised, which only checks for the status being 'finalised' which only occurs if the type is 'fn' when synced, only if the type is not 'request',  etc

The flow would go from 
- `IncomingSyncUtils` -> `PostSyncProcessor` -> `Requisition` .. and everything inbetween 🤣

**Comment by joshxg** [comment]
This is an existing bug, moving it to 3.1.0
