### ISSUE TITLE
Incorrect French translation for program stocktakes

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1356]
## Describe the bug

When creating a new stocktake, the toggle for program stocktake reads `"Inventaire general"` (general stocktake).

![Screen Shot 2019-10-15 at 2 53 32 PM](https://user-images.githubusercontent.com/43223637/66793930-00258780-ef5c-11e9-822b-c7046ca0a954.png)

### To reproduce

1. Logout and change language to French.
2. Click on `"Releves d'inventaire"`.
3. Click on `Nouvel inventaire"`.

### Expected behaviour

The program stocktake toggle should read `"Inventaire par programme"`.

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1075#issuecomment-542000268.

**Comment by joshxg** [comment]
Closed by #1391
