### ISSUE TITLE
Dependency updating

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1380]
## Is your feature request related to a problem? Please describe.

Need to upgrade dependencies. Security problems and to stay up to date

This should be done once 3.0.0 is released

## Describe the solution you'd like

Upgrade dependencies

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1393.

**Comment by joshxg** [comment]
Cliosed by #1432

**Comment by diegoevangelisti** [comment]
### Testing

 - [x] Can run yarn build and build apk's "as per normal" (@wlthomson)
 - [x] Can run react-native run-android and the app runs "as per normal"

**Success**. All working well. 
Apk's created successfully. Also after executing `react-native run-android` the app is running as expected. (same behaviour for command `yarn start`)
