### ISSUE TITLE
Uncounted stock difference is potentially confusing

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1397]
## Describe the bug

When a new item is added to a stocktake, the actual quantity column contains the placeholder string `"Not Counted"`. The quantity value is set to `0`, and the difference calculated accordingly (e.g. given a newly added item with snapshot quantity `123`, the quantity is `"Not Counted"` and the difference is `-123`). 

IMO, if we are using a placeholder for `"Actual quantity"`, we should probably also use one for `"Difference"`? The logic here is that the placeholder value `"Not counted"` indicates that the stock has not yet been calculated, so `"Difference"` doesn't really make sense in this context and is potentially confusing?

![#1397-uncounted-stock-difference](https://user-images.githubusercontent.com/43223637/67055669-7f59cc00-f1a5-11e9-8ce6-bb32a903b8bb.png)

### To reproduce

1. Create a new stocktake.
2. Add an item with a snapshot quantity `x >= 1`.
3. Note that the `"Actual quantity"` is `"Not counted"` and that the `"Difference"` is `-x` (indicating `x` missing stock).

### Expected behaviour

Open to suggestions (including whether this is a problem or not). My suggestion would be to use a placeholder string. Simplest solution would be to replicate the logic for `"Actual quantity"` and set `"Difference"` to `"Not Counted"` or `"Unknown"` until the quantity is set.

### Version and device info

-  App version: 2.3.6.
- Tablet model: TB-X304L (replicated on emulator).
- OS version: 8.1.0.

### Additional context

Follow up from #1343.

**Comment by joshxg** [comment]
@wlthomson 

This is a regression *I think* from my change here: https://github.com/openmsupply/mobile/pull/1394/files#diff-21f2298b3aeda82d16e3056070783d8e

My recommended if the above is the problem:

```
get difference(){
 if (this.hasBeenCounted) return this.countedTotalQuantity - this.snapshotTotalQuantity;
 return 0; 
}
```

**Comment by wlthomson** [comment]
> @wlthomson
> 
> This is a regression _I think_ from my change here: https://github.com/openmsupply/mobile/pull/1394/files#diff-21f2298b3aeda82d16e3056070783d8e
> 
> My recommended if the above is the problem:
> 
> ```
> get difference(){
>  if (this.hasBeenCounted) return this.countedTotalQuantity - this.snapshotTotalQuantity;
>  return 0; 
> }
> ```

Sweet, got it.

**Comment by joshxg** [comment]
> Sweet, got it.

Nice thats good that you got it

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
