### ISSUE TITLE
Status column is sortable but shouldn't be

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1399]
## Describe the bug

Since we're using a PAST/CURRENT toggle for all "plural" pages, the status column [in progress/finalised] isn't needed.

### To reproduce

1. Go to any plural page

### Expected behaviour

Should have it not sortable as it's redundant and stupid

### Version and device info

2.3.6 development

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1399.

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
