### ISSUE TITLE
Column headers not great when not english

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1400]
## Describe the bug

Column headers aren't looking great when not in english

### To reproduce

1. Go to supplier/customer requisitions or stocktake edit page in french/laos/kiribati

### Expected behaviour

Should look good

### Version and device info

2.3.6 development

### Additional context

![image](https://user-images.githubusercontent.com/35858975/67079846-64f91000-f1f0-11e9-9b7e-78f52262c692.png)

![image](https://user-images.githubusercontent.com/35858975/67079855-69bdc400-f1f0-11e9-9dc8-545b12b85553.png)

![image](https://user-images.githubusercontent.com/35858975/67079888-7a6e3a00-f1f0-11e9-86b0-141672bffd19.png)

Tetum/English are fine

**Comment by wlthomson** [comment]
Fixed by #1412.
