### ISSUE TITLE
Filtering should be trimmed

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1402]
## Describe the bug

Filtering should be trimmed of trailing whitespace

### To reproduce

1. Go to a filterable page, 
2. filter and add trailing white space

### Expected behaviour

Trailing whitespace shouldn't effect the filtering string

### Version and device info

2.3.6 development

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1413.

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
