### ISSUE TITLE
Months Stock modal has no title

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1403]
## Describe the bug

The modal opened when selecting months of stock in `SupplierRequisitionPage` has no title

### To reproduce

1. Go to `SupplierRequisitionPage`, create a requisition
2. Click on Months Stock to change the months of stock

### Expected behaviour

Should have a title. Specifically: `modalStrings.select_the_number_of_months_stock_required`

### Version and device info

2.3.6 development

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1414.

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
