### ISSUE TITLE
Cell component should be multi line by default

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1405]
## Describe the bug

`Cell` is a single line. This cna be a bit problematic when item names are long. Especially given that their units and sizes need to be in the name.

### To reproduce

1. On desktop edit an item name to be super long
2. Add this item to any page - SI/CI/Stocktake etc
4. See error [It's ellipsized up and cut off even though theres room for a couple lines at least]

### Expected behaviour

Should use two lines

### Version and device info

All, forever I think

### Additional context

- Would need to update PR here: https://github.com/sussol/react-native-data-table/pull/57
- Maaybe need to adjust row height maybe, but worth it most likely

**Comment by wlthomson** [comment]
Fixed by #1417.

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
