### ISSUE TITLE
ByProgramModal not handling very long text gracefully

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1406]
## Describe the bug

A very long supplier name, for example, doesn't look nice in the `ByProgramModal`

### To reproduce

1. Create a very long program or supplier name
2. Create a program supplier requisition

### Expected behaviour

Should handle long strings gracefully, with elipsis or multi lines

### Version and device info

2.3.6 development

### Additional context

![image](https://user-images.githubusercontent.com/35858975/67131851-ca85e480-f262-11e9-8be7-7d6070deda91.png)

**Comment by wlthomson** [comment]
Fixed by #1406.

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
