### ISSUE TITLE
Shouldn't be able to remove items from a program requisition

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1408]
## Describe the bug

The remove column is present in a program requisition. Having the option to remove an item, may cause user errors since you can't add items, accidently removing an item would be extremely frustrating.

It is also not possible on desktop

### To reproduce

1. Go to Supplier requisitions page, create a program requisition

### Expected behaviour

Supplier requisition should not have the remove column when it is a program requisition

### Version and device info

2.3+

### Additional context

N/A

**Comment by joshxg** [comment]
Fixed by #1418

**Comment by diegoevangelisti** [comment]
## Testing

- [x] `SupplierProgramRequisition` page has no `remove` column when a program requisition

**Success**
