### ISSUE TITLE
Can't scroll ItemDetails on StockPage

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1410]
## Describe the bug

`StockPage` uses `DataTablePageView` which captures gestures that aren't handled by a child. Scrolling isn't technically handled by the child, so this gesture is captured and ignored rather than scrolling the view.

### To reproduce
Have 5+ batches of an item
1. Go to StockPage
2. Click on an item with the batches
3. Scroll the popup

### Expected behaviour

Should be able to scroll the `ItemDetails` component

### Version and device info

2.3.6 development

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #1419.

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
