### ISSUE TITLE
User is not navigated to StocktakeManagePage when creating a new stocktake

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1425]
## Describe the bug

Expected behaviour should be as described by the following workflow:

Go to stocktakes -> Click button to create a new stocktake -> Enter stocktake parameters -> Enter stocktake items.

After entering the stocktake parameters via `ByProgramModal`, the user should be presented with the `StocktakeManagePage` to specify items. This works as expected when programs are not enabled, but does not when programs are enabled. 

### To reproduce

1. Disable programs if they are enabled.
2. Create a new stocktake.
3. Note that you are navigated from `ByProgramModal` to `StocktakeEditPage` (instead of to `StocktakeManagePage`).

### Expected behaviour

User should be navigated to `StocktakeManagePage` after creating a new stocktake (invariant of programs enabled or not).

### Version and device info

- App version: 2.3.6.
- Tablet model: Pixel C (emulated).
- OS version: Android API 28

### Additional context

See https://github.com/openmsupply/mobile/issues/1241#issuecomment-544342739.

**Comment by joshxg** [comment]
Closed by #1428

**Comment by joshxg** [comment]
This will be tested with templates - moving to done
