### ISSUE TITLE
Remove remaining UIDatabase props

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1441]
## Describe the bug

`UIDatabase` is now exported as a singleton, which allows it to be injected directly into components without passing it down the prop tree. Some pages are still passing the `UIDatabase` around as a prop, which is potentially causing unnecessary re-renders and slowing down performance.

### Expected behaviour

Components should directly import `UIDatabase` via the exposed singleton.

### Version and device info

Bug is present in `develop` and `master` branches.

### Additional context

N/A.

**Comment by joshxg** [comment]
Believe this is done
