### ISSUE TITLE
Interrupting sync breaks site registration /hardware ID

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1449]
## Describe the bug

When trying to initialise with poor connectivity, sometime it hangs. If you press the back key (or by some means the details get cleared, Surelock is being pretty wild) then re-enter the sync details to resume, it'll say "Site registration doesn't match /n Tap to retry".

### To reproduce

1. Start syncing of site initialisation
2. hit back button
3. Reopen mobile (Should have lost sync details I think)
4. Re-enter same details and hit sync
5. Observe brief showing of trying to resume sync with prior progress numbers, before getting shown: "Site registration doesn't match /n Tap to retry"

### Expected behaviour

It continues initialisation sync from where it was interrupted

### Version and device info

- App version: 3.0.0
- Tablet model: Samsung TabA SM-T515
- OS version: Android recent edition

### Additional context

Related to #1290
Also have a user unable to login after initialisation, again due to site registration not matching.

**Comment by joshxg** [comment]
fixed by #1453

**Comment by joshxg** [comment]
Pretty internal change - not sure if the 'fix' actually did anything. Moving to done 🤷‍♂
