### ISSUE TITLE
The french translation for Login or the alert for a wrong password are not right 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#1450]
## Describe the bug

The french translation for Login is displayed as "Se connecter or Ouverture de session". It should be either "Se connecter" OR "Ouverture de session" but not both. You can choose either !!!

Also when you don't have the right password, the alert that is displayed has not been translated

### To reproduce

1. Open msupply mobile
2. Change language to french
3. See error
4. Put a wrong password
5. See Error

### ScreenShot

![image](https://user-images.githubusercontent.com/11624516/67802338-4ea94a80-fa61-11e9-9899-978d323d9cec.png)

![image](https://user-images.githubusercontent.com/11624516/67802505-a6e04c80-fa61-11e9-9611-7e903cbb060e.png)

### Expected behaviour

Translation should be either "Se connecter" OR "Ouverture de session" but not both

For the alert Translation should be "Utilisateur ou mot de passe incorrect"

### Version and device info

- App version: 3.0.0
- Tablet model: Galaxy Tab A
- OS version: Android 9.0

### Additional context

I remember having put both as translation to choose one or the other but I was probably unclear or even forgot to say that a choice needed to be made...

**Comment by alainsussol** [comment]
@joshxg @wlthomson 

Do someone needs permissions to add an issue to a project or add milestone or labels to an issue? I can't seem to be able to do either...

**Comment by joshxg** [comment]
🤣 

Another since we're here:
- `user_name: "Identifiiant or Nom d'utilisateur",` 

Also note for implementation: the error `Invalid username or password` is the error message which is sent from the server - we will need to capture this message and use a localized string, rather than the error message

---

Also @alainsussol yeah I think so - I can't seem to add, might need @andreievg or @Chris-Petty to add

**Comment by alainsussol** [comment]
> user_name: "Identifiiant or Nom d'utilisateur"

I would use "Identifiant" since it is kind of the facility name rather than a user name. The alert would then need to be "Identifiant ou mot de passe incorrect"

**Comment by alainsussol** [comment]
@joshxg 

> Also note for implementation: the error Invalid username or password is the error message which is sent from the server - we will need to capture this message and use a localized string, rather than the error message

OK. Will take care of this

**Comment by wlthomson** [comment]
> @joshxg @wlthomson
> 
> Do someone needs permissions to add an issue to a project or add milestone or labels to an issue? I can't seem to be able to do either...

Permissions resolved as discussed :).

**Comment by joshxg** [comment]
Fixed by #1525
