### ISSUE TITLE
Add request headers to bugsnag

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1454]
## Is your feature request related to a problem? Please describe.

Related to #1449.

When a sync error occurs, we currently snag the URL, body and response in the report metadata. It would also be useful to snag the headers that were sent, for debugging purposes.

## Describe the solution you'd like

Add headers to the report metadata.

## Describe alternatives you've considered

N/A. 

## Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #1461

**Comment by joshxg** [comment]
Internal development change - moving to done
