### ISSUE TITLE
Adding items to tables causes strange ordering

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1479]
## Describe the bug

Adding items to tables causes strange ordering.

Items are always added to the head:

`data: [record, ...backingData.slice(0,backingData.length-1)]`

The ordering of `backingData` may change. After adding one item it is at the head of the list. Adding the next item may not have the exact same ordering. For example:

List:

- A
- B

Add C:

- C
- A
- B

Add D:

- D
- A
- B
- C

This is because adding an item removes ALL user defined sorting, and what is left is the implicit database sort which is a standard sorting on the primary key. If it gets sorted before/after adding by whatever the current sort is it just starts to add complexity. I think just adding to the bottom and stop trying to be cool is the right solution?

### To reproduce

As Above

### Expected behaviour

As Above

### Version and device info

- App version: 3.0.0+
- Tablet model: All
- OS version: All

### Additional context

N/A

**Comment by joshxg** [comment]
Fixed by #1514

**Comment by diegoevangelisti** [comment]
## Testing

Create a list of a few items in a supplier invoice. Easiest to number the quantities `1,2,3` etc. Add an item. It should be added to the head and the order of the remaining rows should be stable when adding more items - whether there is a filtering term or sorting.

This applies to adding of all rows `supplier invoice`, `customer invoice` and `supplier requisition`. All the logic is shared, so testing one page is sufficient.

Try to break the app, by using some funky ordering or workflow of sorting/filtering/adding/editing/removing etc

- [x] App doesn't break

**Success** Working well after trying to break it from different ways.
