### ISSUE TITLE
Update dev_scripts

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1480]
## Is your feature request related to a problem? Please describe.

Placeholder issue for updating out-of-date scripts and adding scripts for generating signing keys and uploading bugsnag sourcemaps. 

## Describe the solution you'd like

Update scripts:

- `deploy.sh`

Add scripts:

- `clean.sh`
- `keygen.sh`
- `upload.sh`

## Describe alternatives you've considered

N/A. 

## Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #1481

**Comment by joshxg** [comment]
Internal development change - moving to done
