### ISSUE TITLE
Remove badges at the top of pages

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1487]
## Describe the bug

The badges at the top of pages i.e. `SupplierInvoicePage` do not update correctly and are unneccesary.

### To reproduce

1. Go to `SupplierInvoicePage` with unfinalised invoices
2. Go to a in progress invoice, finalise it.
4. See error - not updated badge

### Expected behaviour

The badge shouldn't be there since there is a toggle for in progress/finalised

### Version and device info

- App version: 3.1 development
- Tablet model: All
- OS version:  All

### Additional context

Solution for this issue is to remove this badge

**Comment by joshxg** [comment]
@sworup you want to do this? It's a quick one - with a toggle to show finalised/inprogress records, the badge is really not needed, and it's quite a bit of work to make it update properly. I think for now lets remove it - we can add it back later if users like the badges on the `MenuPage`

**Comment by sworup** [comment]
> @sworup you want to do this? (if you dont have time no problem) It's a quick one - with a toggle to show finalised/inprogress records, the badge is really not needed, and it's quite a bit of work to make it update properly. I think for now lets remove it - we can add it back later if users like the badges on the `MenuPage`

ok will take this.

**Comment by joshxg** [comment]
@sworup I was adjusting the size and just did this commit 1d0c5af7cf1fb6c91df8e94836be322ec4c46803 because it was very easy.. so I think we can just close this it is the PR #1509

**Comment by sworup** [comment]
@joshxg I was occupied with Axios and was about to do this today. 
Anyways great job. Will look into the PR.

**Comment by joshxg** [comment]
sorry @sworup I hope it is not a problem.. was just deleting some lines of code so I thought it was ok..

**Comment by sworup** [comment]
> sorry @sworup I hope it is not a problem.. was just deleting some lines of code so I thought it was ok..

Of course no problem. 👍

**Comment by sworup** [comment]
Closing because @joshxg continued with https://github.com/openmsupply/mobile/issues/1489
