### ISSUE TITLE
Badges are too small

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1489]
## Is your feature request related to a problem? Please describe.

Need to increase the size of the newly introduced badges.

## Describe the solution you'd like

Should probably increase the size by at least double, maybe three times.

I'm not sure about the shape - I personally think a circle is nice, but not required to change!

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by GaryWilletts** [comment]
@joshxg can you include a screenshot of what you're seeing? We've discussed the badges' appearance quite a lot and they have been agreed...

**Comment by joshxg** [comment]
I don't have a tablet on my right now sorry @GaryWilletts ! I will do tomorrow in the office. But basically I can't click on the badges. I admit my fingers are not petite, but they're just a bit small to be able to quickly and easily click on to bring up the popup.

Regarding the shape - I think the oval seems strange, personally, although I don't have any strong feelings against it, just seems odd to me!

Just trying to iterate on the badges as I hope to release a new version soon with a couple more features before we do a lot of dispensing work  :)

**Comment by joshxg** [comment]
Fixed by #1509

**Comment by joshxg** [comment]
Going to consolidate badge testing to #507
