### ISSUE TITLE
Badges should have a time limit

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1490]
## Is your feature request related to a problem? Please describe.

At the moment badges display all unfinalised records. This could be way too many for many existing users.

## Describe the solution you'd like

Should only display the number of unfinalised records in the last.. month? 2 months? Not sure. I think one month to start.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by GaryWilletts** [comment]
We discussed this at length before merging the badges stuff in. We decided that we'd see how it works in practice for users before deciding whether badges should be time limited.

**Comment by joshxg** [comment]
If there's anything else that was discussed it would be great to hear it. I am getting told mixed messages and have no clear understanding of requirements, what was discussed and it seems no one who is actually working on the feature knows what was discussed in the meeting.. :(

**Comment by GaryWilletts** [comment]
Sworup and Andrei were on the last call, can't remember who else. Pity none of it's been documented and passed on, bit of a hole there.

**Comment by joshxg** [comment]
Well I'll close this then! Thanks for checking up on it
