### ISSUE TITLE
Item select should show the Item Code

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1513]
## Is your feature request related to a problem? Please describe.

Selecting an item doesn't show the item code, which can slow users down.

## Describe the solution you'd like

It should show the item code

## Describe alternatives you've considered

N/A

## Additional context

- Someone said this was a regression. I looked at 2.3.6 and it wasn't there. Didn't look back further.

@Chris-Petty @andreievg 
Option: 

![image](https://user-images.githubusercontent.com/35858975/68352886-b56aea00-016c-11ea-83d0-320f2e4a611a.png)

**Comment by joshxg** [comment]
Fixed by #1516

**Comment by emilyporrello** [comment]
Docs updated

Added screenshots showing what happens when you search for an item when creating Customer Invoices and Supplier Requisitions https://docs.msupply.foundation/en:mobile:user_guide:customer_inv
https://docs.msupply.foundation/en:mobile:user_guide:supplier_requisitions
