### ISSUE TITLE
Dependency upgrades November 2019

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1526]
## Is your feature request related to a problem? Please describe.

Monthly dependency upgrade

## Describe the solution you'd like

- Mainly looking to upgrade `react-navigation`. It was left out of last months as there were other major ones and didn't want to do too many at once. All of the navigators have been ripped out of the main package and are their individual packages now - i.e. stack/switch/tabs. Not a biggy as they've made them backwards compatible I believe, but a couple of code changes, I believe
- Haven't seen any other major releases

## Describe alternatives you've considered

Getting behind in upgrades

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #1527

**Comment by diegoevangelisti** [comment]
## Testing

Never know what to put here.. (no worries, me neither @joshxg)

- [ ] Can run `react-native run-android`
- [ ] Can run `yarn build`

**Success** 
Both are working fine to me.
