### ISSUE TITLE
GenericChoiceList should use Hooks API

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1541]
## The suggestion

GenericChoiceList should use Hooks API rather than React Class API

**Why?**
Consistency and https://github.com/openmsupply/mobile/issues/1092

## Describe alternatives you've considered

Doing nothing.

**Comment by joshxg** [comment]
@Rebecca367 do you have time to work on this issue? 

It is a refactoring from a `PureComponent` to a `functional` component.

An example PR of a similar refactor is here: https://github.com/openmsupply/mobile/pull/1704

**Comment by Rebecca367** [comment]
OK, I will move on to it today.Apology for that I only saw the notification now.

**Comment by joshxg** [comment]
Closed by #1776

**Comment by diegoevangelisti** [comment]
## Testing

**This PR is a refactor, so behaviour should mimic the old behaviour. This is a vague test case, so please check the current MASTER branch behaviour, and see that the behaviour is the same on THIS branch**
This component is used:
- [x] `StocktakeEditPage` for reason selection
- [x] `LoginPage` for selecting a language

Both pages tested and working fine. ** Success **
