### ISSUE TITLE
BottomModal should use Hooks API

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1542]
## The suggestion

BottomModal should use Hooks API rather than React Class API

**Why?**
Consistency and https://github.com/openmsupply/mobile/issues/1092

## Describe alternatives you've considered

Doing nothing.

**Comment by joshxg** [comment]
Closed by #1767

**Comment by diegoevangelisti** [comment]
## Testing
**This PR is a refactor, so behaviour should mimic the old behaviour. This is a vague test case, so please check the current MASTER branch behaviour, and see that the behaviour is the same on THIS branch**

i.e.
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/35858975/71332073-a8c61800-2599-11ea-9658-77685a16a21d.png">
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/35858975/71332083-b2e81680-2599-11ea-9e1d-b0b7fdd093a5.png">


This PR refactored the modals which open from the `BottomModal`. This occurs whenever you try to REMOVE a record OR when you NAME a stocktake on `StocktakeManagePage`

- [ ] Removing records opens the modal as per normal - on `CustomerInvoicesPage`
**Doesn't pass, I opened the issue #1882  regarding this**
- [x] Modal displays and acts as per normal on `StocktakeManagePage`
