### ISSUE TITLE
PageContentModal should use Hooks API

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1545]
## The suggestion

PageContentModal should use Hooks API rather than React Class API

**Why?**
Consistency and https://github.com/openmsupply/mobile/issues/1092

## Describe alternatives you've considered

Doing nothing.

**Comment by joshxg** [comment]
This is actually only being used in `ByProgramModal` (ew) and is being slowly replaced with `ModalContainer` which is using the react native modal, but that too could have some hooks added!

**Comment by joshxg** [comment]
Closed by #1766

**Comment by diegoevangelisti** [comment]
## Testing
**This PR is a refactor, so behaviour should mimic the old behaviour. This is a vague test case, so please check the current MASTER branch behaviour, and see that the behaviour is the same on THIS branch**

This PR refactored the modals which open from the `ByProgramModal`. When selecting the details for a [program stocktake](https://docs.msupply.foundation/en:mobile:user_guide:stocktakes_program) or [requisition](https://docs.msupply.foundation/en:mobile:user_guide:supplier_requisitions_program), a modal appears, this modal should function the same as before for :

- [x] Requisition: selecting a program
- [x] Requisition: selecting a supplier
- [x] Requisition: selecting an order type
- [x] Requisition: selecting a period
- [x] stocktake: selecting a program
- [x] stocktake: naming the stocktake

**Success**
