### ISSUE TITLE
Wrong message when ServerURL is not properly lowercase

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1553]
## Description

Related with: [#1440 ](https://github.com/openmsupply/mobile/issues/1440)

In the initialize page, when the server URL is not completely lowercase (e.g. `Http:// ...`), the returned message is `Unable to Connect`, which I found not so explanatory. Maybe it would be better to show a message like `Invalid URL` or something more direct such as `URL should be lowercase`.

Reproduction Steps:

1. Go to initialize page
2. Type a server URL with an uppercase char (e.g. `Http://10.2.0.0:5000`)
3. Check the retrieved message

## Design discussion

Which should be the correct message? Possible solutions: 
- `Invalid URL`
- `URL should be lowercase`

@Chris-Petty, @joshxg any thoughts about it?

**Comment by joshxg** [comment]
having a look - it is pretty deep nesting  of packages and dependencies. Quite a big code smell, that this change would be so difficult:

If you trace the code you see that the call in `FirstUsePage` goes through this:

`FirstUsePage` -> `Synchroniser` -> `SyncAuthenticator`, which calls the method `const responseJson = await authenticateAsync(authURL, username, passwordHash, ...` -- this validates the URL.

This `authenticateAsync` method is in a package `sussol-utilities` (https://github.com/sussol/sussol-utilities/blob/master/src/index.js#L3) , which imports another package `authentication-utilities` (https://github.com/sussol/authentication-utilities/blob/master/src/index.js) which imports another package `valid-url` https://github.com/ogt/valid-url -- valid URL package says the URL with capitals is a valid url, so a error is not thrown. (if you try to enter `zzz://10.0:2048` as the URL, you will see if returns `Invalid URL` 

Maybe @Chris-Petty has different thoughts, but I think we should leave this issue for now, and should consider refactoring this code to remove all the importing of packages in #1539 

Alternatively we could just fix this by changing `authentication-utilities` - a line right here in this repo to check capitilization would fix this https://github.com/sussol/authentication-utilities/blob/ba1678118f3055bb311f4d8979f0d0d33126f55c/src/index.js#L27-L30

enough info? 🤣

**Comment by diegoevangelisti** [comment]
Explanations are never long enough, so you always go ahead. This is great @joshxg, highly appreciated. So, I guess I will wait for @Chris-Petty thoughts before taking any action.

**Comment by wlthomson** [comment]
> having a look - it is pretty deep nesting of packages and dependencies. Quite a big code smell, that this change would be so difficult:
> 
> If you trace the code you see that the call in `FirstUsePage` goes through this:
> 
> `FirstUsePage` -> `Synchroniser` -> `SyncAuthenticator`, which calls the method `const responseJson = await authenticateAsync(authURL, username, passwordHash, ...` -- this validates the URL.
> 
> This `authenticateAsync` method is in a package `sussol-utilities` (https://github.com/sussol/sussol-utilities/blob/master/src/index.js#L3) , which imports another package `authentication-utilities` (https://github.com/sussol/authentication-utilities/blob/master/src/index.js) which imports another package `valid-url` https://github.com/ogt/valid-url -- valid URL package says the URL with capitals is a valid url, so a error is not thrown. (if you try to enter `zzz://10.0:2048` as the URL, you will see if returns `Invalid URL`
> 
> Maybe @Chris-Petty has different thoughts, but I think we should leave this issue for now, and should consider refactoring this code to remove all the importing of packages in #1539
> 
> Alternatively we could just fix this by changing `authentication-utilities` - a line right here in this repo to check capitilization would fix this https://github.com/sussol/authentication-utilities/blob/ba1678118f3055bb311f4d8979f0d0d33126f55c/src/index.js#L27-L30
> 
> enough info? 🤣

My 2c for what it's worth.

I agree with @joshxg. I think the dependencies `sussol-utilities` and `authentication-utilities` probably were a good idea in the beginning, but they are small enough that it makes sense to refactor/rewrite them as helpers in the main code base.

Pros:
  - Authentication logic is abstracted.
  - Same logic is enforced across multiple repos.
Cons:
  - Authentication logic is abstracted :).
  - Mobile behaviour may change unexpectedly without any commits/PR.
  - Codebase is more difficult to parse.

On balance, I think modularising stuff is a good idea if the logic is complex enough and repeated across >3 repos which should all behave the same. On balance, I think it's probably slowing down development a bit more than speeding it up in this case, and reducing external dependencies as much as possible seems like a good idea in general to simplify the codebase 🤷‍♂ .

**Comment by Chris-Petty** [comment]
Yup, fully on the same page. Was a big hassle with react-native-generic-table-page or whatever it was called, especially with that being between mobile and react-native-data-table. Without a consistent effort to maintain the packages it ends up more trouble than it's worth until we have more repositories needing similar functions and react components.

In defence of that, money-mob repo did/does use those packages too, but we don't really actively maintain that either.
