### ISSUE TITLE
Allow unlimited emergency requisitions but only a configurable maximum amount of lines on each

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#1557]
## Is your feature request related to a problem? Please describe.
Client request from Côte d'Ivoire. Raised also in mSupply as https://github.com/sussol/msupply/issues/4557

The requirement as stated: "Maximum of 5 lines of items on emergency requisitions. Allow the possibility to enter many emergency reports each month. Max. no. lines needs to be configurable."

## Describe the solution you'd like

Configuration as part of the program settings perhaps? Defaulting to a value of 5. 
Perhaps also some way of turning the feature off? It isn't ideal for all users.

## Describe alternatives you've considered

Have tried to avoid implementing.

**Comment by joshxg** [comment]
@mark-prins is there a date for this? Is this before dispensing in mobile needs to be delivered?

**Comment by mark-prins** [comment]
The mSupply changes will be delivered before mobile dispensing. I think it unlikely that mobile would be upgraded with an interim version, one that contains this change but not the dispensing.
All the same, I'd put this as a higher priority and ideally get it into a build before dispensing is done if that's possible.

**Comment by joshxg** [comment]
I'd prefer to get it done sooner rather than later also - should be simple, dependent on the desktop implementation 🤣

**Comment by joshxg** [comment]
@mark-prins 

I only just realised/remembered that you can't add items to a program requisition..! It seems desktop is just not allowing finalisation when there are more than 5 edited items..? That's easy to do. Was wondering.. can we just split the requisition into multiple with a max of 5 lines instead 🤣

**Comment by joshxg** [comment]
Closed with #1643

**Comment by emilyporrello** [comment]
Docs updated

Updated screenshot and added definition of 'max lines' in Supplier Requisitions (Programs); also updated desktop user guide for program configuration
https://docs.msupply.foundation/en:mobile:user_guide:supplier_requisitions_program
https://docs.msupply.org.nz/items:programs#creating_a_program
