### ISSUE TITLE
Update react-navigation version

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#1558]
Setting up the dev environment for this project for the first time results in an error:

![Screen Shot 2019-11-14 at 10 31 23 AM](https://user-images.githubusercontent.com/9192912/69278574-7f873480-0c47-11ea-9c50-9b0828b0d87d.png)

## The suggestion

The version specified of `react-navigation` is `^3.11.0` and yarn has helpfully installed v4
This gives the above error. Suggest refactor to enable v4 of react-navigation.

**Why?**
Assist with initial set up of environment.

## Describe alternatives you've considered

A work around to the error would be to fix the version of `react-navigation` to v3
Prefer to upgrade if possible.

**Comment by joshxg** [comment]
Odd.

Develop branch has been upgraded already: https://github.com/openmsupply/mobile/blob/1b2fae2af1106ff9561c68e777e729be826344af/package.json#L75

In this PR: https://github.com/openmsupply/mobile/pull/1527

**Comment by mark-prins** [comment]
I thought I was on develop. closing issue - thanks.
