### ISSUE TITLE
Move README.md to wiki

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1560]
## Is your feature request related to a problem? Please describe.

Placeholder issue for updating `README.md` to get up-to-date with recent wiki changes.

## Describe the solution you'd like

Remove documentation from `README.md` that is duplicated in wiki. 

## Describe alternatives you've considered

N/A.

## Additional context

Part of ongoing process of tidying up mobile documentation and updating based on feedback from new mobile developers. See #1555.

**Comment by joshxg** [comment]
Closed by #1561
