### ISSUE TITLE
ByProgramModal opening when no programs defined

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1573]
## Describe the bug

When no programs are defined, the `ByProgramModal` is still opening

### To reproduce

**Have no programs defined**

1. Go to `StocktakesPage` or `SupplierRequisitionsPage`
2. Click on 'new'

### Expected behaviour

Should only show when programs are defined

### Version and device info

- App version: 3.0.0 + development
- Tablet model: All
- OS version: All

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #1577

**Comment by diegoevangelisti** [comment]
## Testing

With no programs defined:
- [x] Clicking `New Requisition` on `SupplierRequisitionsPage` does not open the `ByProgramModal`
- [x] Clicking `New Stocktake` on `StocktakesPage` does not open the `ByProgramModal`

**Success**.
