### ISSUE TITLE
Toast the user when there are no master lists available

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1575]
## Describe the bug

Clicking `Add from Masterlist` displays "No masterlists" in the modal where none are defined.

### To reproduce

1. Go to `CustomerInvoicePage` [With a `Customer` who has no `MasterList` defined]
2. Click on `Add From MasterList`

### Expected behaviour

Should toast the user, rather than opening the modal

### Version and device info

- App version: 3.0.0 development
- Tablet model: all
- OS version: all

### Additional context

Related PR: #1573

**Comment by joshxg** [comment]
Closed by #1579

**Comment by diegoevangelisti** [comment]
- [x] Go to CustomerInvoicePage [With a Customer who has no MasterList defined]
- [x] Click on Add From MasterList
- [x] No errors found

Test done
