### ISSUE TITLE
Badges crash when navigating quickly

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1580]
## Describe the bug

When opening a popover from a badge and quickly navigating, the app crashes

Throwing: `java.lang.Double.doubleValue()' on a null object reference`

### To reproduce

1. Click on a badge to open the popover
2. Click on a button to navigate before the popover opens

![badgeCrash](https://user-images.githubusercontent.com/35858975/69501245-01d56880-0f68-11ea-9679-02d59450abc9.gif)

### Expected behaviour

The app shouldn't crash

### Version and device info

- App version: 3.1 development
- Tablet model: all
- OS version: all

### Additional context

Not sure of the cause, exactly

**Comment by joshxg** [comment]
Closed by #1581

**Comment by diegoevangelisti** [comment]
- [x] Click on a badge to open the popover
- [x] Click on a button to navigate before the popover opens
- [x] No errors found

Test done
