### ISSUE TITLE
Add script to reset mSupply mobile app data

### ISSUE THREAD

**Issue by raviSussol** [openmsupply/mobile#1589]
## Is your feature request related to a problem? Please describe.
Most of the time the mobile app need to re-setup in the same version (without install/uninstall) for testing purpose. I am used to do this (flushing app data) several time while I am testing either in emulator or in device which I do by uninstall/install or sometimes running long script (which is a bit frustrating :-( )

## Describe the solution you'd like
`adb shell pm clear com.msupplymobile` would work or a script in the package.json file would be helpful (just like any other scripts)

**Comment by joshxg** [comment]
Closed by #1590
