### ISSUE TITLE
Payment utility: cancel()

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1593]
## Is your feature request related to a problem? Please describe.

Need to be able to cancel a script. For some reason a cancellation is different from refund/credit.

## Describe the solution you'd like

- A utility method `cancel(Transaction script)`

- Creates a full inverse of the passed script and each line.
- Creates full inverses of each of the passed scripts related `TransactionBatch` records
- Sets both of the invoices `isCancellation` to true

## Describe alternatives you've considered

- Not really sure why a cancellation is different from a refund/return/credit.
- Possibly extract some logic from #1592 to methods to create inverses is a better solution

## Additional context

N/A

**Comment by joshxg** [comment]
@mark-prins - since cancelling on desktop doesn't give credit (essentially doesn't work correctly) what do you think the correct behaviour should be:

cancelling on desktop isn't giving credit at the moment. It is simply making an inverse CI which puts the stock back:

```
[
  {
    "ID": "AD1C4FB06A854321B04684EA5986428A",
    "invoice_num": 58,
    "amount_outstanding": 0,
    "comment": "",
    "type": "ci",
    "total": 10,
    "linked_transaction_id": "",
    "subtotal": 10,
    "insuranceDiscountAmount": 0,
    "insuranceDiscountRate": 0,
    "transLines": [
      {
        "price_extension": 10,
        "note": " ",
        "quantity": 1,
        "item_name": "Item1",
        "ID": "121F5409D9D1483587481DE67ACD1A4D",
        "type": "stock_out"
      }
    ]
  },
  {
    "ID": "E7D0FA5FECB54E309EA3576216F21F1A",
    "invoice_num": 58,
    "amount_outstanding": 0,
    "comment": "Receipt for invoice(s) 58",
    "type": "rc",
    "total": 10,
    "linked_transaction_id": "",
    "subtotal": 0,
    "insuranceDiscountAmount": 0,
    "insuranceDiscountRate": 0,
    "transLines": [
      {
        "price_extension": 10,
        "note": "",
        "quantity": 0,
        "item_name": "",
        "ID": "713A7244E75341028F2936CDCE97CFC8",
        "type": "cash_in",
        "linkedTransact": { "ID": "AD1C4FB06A854321B04684EA5986428A" }
      }
    ]
  },
  {
    "ID": "CA684EEDBEDA415085A0D6395695B02C",
    "invoice_num": 58,
    "amount_outstanding": -0,
    "comment": "Cancellation of customer invoice 58",
    "type": "ci",
    "total": -10,
    "linked_transaction_id": "",
    "subtotal": -10,
    "insuranceDiscountAmount": 0,
    "insuranceDiscountRate": 0,
    "transLines": [
      {
        "price_extension": -10,
        "note": " ",
        "quantity": -1,
        "item_name": "Item1",
        "ID": "729676FECFE2475D96902A1FEAA9BD3A",
        "type": "stock_out"
      }
    ]
  }
]

```




Patient credits make a `CC` transaction, put the stock back and add credit:

```
[
  {
    "ID": "1EB2FCE4E4BB46C487EC32C91B430198",
    "invoice_num": 71,
    "amount_outstanding": 0,
    "comment": "",
    "type": "ci",
    "total": 10,
    "linked_transaction_id": "",
    "subtotal": 10,
    "is_cancellation": false,
    "insuranceDiscountAmount": 0,
    "insuranceDiscountRate": 0,
    "transLines": [
      {
        "price_extension": 10,
        "note": " ",
        "quantity": 1,
        "item_name": "Item1",
        "ID": "71F185D862234661A9B0E4DC6419B75A",
        "type": "stock_out"
      }
    ]
  },
  {
    "ID": "4A0FC098214044F59570CECA924BBCC7",
    "invoice_num": 71,
    "amount_outstanding": 0,
    "comment": "Receipt for invoice(s) 71",
    "type": "rc",
    "total": 10,
    "linked_transaction_id": "",
    "subtotal": 0,
    "is_cancellation": false,
    "insuranceDiscountAmount": 0,
    "insuranceDiscountRate": 0,
    "transLines": [
      {
        "price_extension": 10,
        "note": "",
        "quantity": 0,
        "item_name": "",
        "ID": "688C73EF84A04AD6A8E8B07256C48D71",
        "type": "cash_in",
        "linkedTransact": { "ID": "1EB2FCE4E4BB46C487EC32C91B430198" }
      }
    ]
  },
  {
    "ID": "7EEC245E18264597BE5C355C89D96CFD",
    "invoice_num": 73,
    "amount_outstanding": -10,
    "comment": "",
    "type": "cc",
    "total": -10,
    "linked_transaction_id": "",
    "subtotal": -10,
    "is_cancellation": false,
    "insuranceDiscountAmount": 0,
    "insuranceDiscountRate": 0,
    "transLines": [
      {
        "price_extension": -10,
        "note": " ",
        "quantity": 1,
        "item_name": "Item1",
        "ID": "55631995FB8E4BA7AAD5C6F36FBA02AC",
        "type": "stock_in"
      }
    ]
  }
]
```



Not sure what the behaviour should be for cancelling while giving credit.

- Just do a patient credit for all items in the script
- Do a cash in transaction for the value of the script
- ???

**Comment by mark-prins** [comment]
I think do it properly:
- make an inverse CI to put the stock back
- do a patient credit 

and create an issue for mSupply to be fixed. I'll take advice, but I'm fairly sure that creating a patient credit is actually what was intended and that mSupply is not working correctly.

**Comment by joshxg** [comment]
@mark-prins 

A patient credit currently makes a `[transact]` with `type="cc"` and `amount_outstanding=[total amount of the items being returned]` - which gives the credit, and also has related `[trans_lines]` with `type="stock_in"` which put the stock back 

So doing an inverse CI and a patient credit would double up. I dunno which is right!

**Comment by mark-prins** [comment]
Oh, yeah. sorry - the patient credit only, that's a good point. I didn't realise the patient credit did the stock return too.
