### ISSUE TITLE
(M)General issue found: Mobile app doesn't like sync out records when you have a sync out type = "M" which is merging

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#160]
@edmofro : Feel free to close this once you have a answer to it.

I found this issue yesterday on demo EC2 server while trying to dump all the records in to the app.
There were some records in the sync out table some of it having a sync out type = M
When app tries to collect that data : Gave me an message saying : Cannot integrate with sync type m .

Taking this : We cannot ignore the fact that we can have some pre existing sync out records with this type - Any thoughts?

# Implementation notes
Handling merge on mobile to avoid server bombing mobile with sync records from a merge.
Server will have to handle the fact that mobile pushes sync changes to server before pulling. This means that mobile may push records referencing records that have been merged and deleted already on the server.
Handling merge on site means handling all these tables (feel free to correct!).
Architecture wise (pending more discussion), perhaps something similar to the delete record code - e.g. find all `Transactions` that have `TransactionBatches` referring to the item to delete in the merge and call `Transaction.mergeItems(itemA, itemB)`. A similar thing is done for all `TransactionBatches`; `TransactionBatch.mergeBatches`...

**All pending researching if realm has effective means of managing merging of records.**
If realm can smartly update all existing references to a item/name to point to another, then easy peasy.
### Names
Tables to update:
- [ ] Name 
- [ ] Transaction
- [ ] Requisition
- [ ] NameStoreJoin
- [ ] MasterListNameJoin
- [ ] Stocktake
### Items
Tables to update:
- [ ] Item 
- [ ] ItemBatch
- [ ] ItemStoreJoin
- [ ] MasterListItem
- [ ] Transaction
- [ ] TransactionItem
- [ ] TransactionBatch
- [ ] Requisition
- [ ] RequisitionItem
- [ ] Stocktake
- [ ] StocktakeItem
- [ ] StocktakeBatch

**Comment by edmofro** [comment]
Wow, Adrian came up with a server based solution at one point!

**Comment by edmofro** [comment]
Some other conversation happened on #392

**Comment by adrianwb** [comment]
I'd forgotten about that server-based solution - let me know if you want me to take it further

**Comment by Chris-Petty** [comment]
@adrianwb if you can spare, bumping option 1. Although I think that mobile should have to deal with it eventually, if this solves problems for mSupply too then that is good. Fairly pressed on getting other features of release 1.2 out so it'd be great if you have time to cover this issue server side!

**Comment by adrianwb** [comment]
Added Mantis issue https://bugs.msupply.org.nz/view.php?id=8314

**Comment by Chris-Petty** [comment]
Bump @adrianwb @edmofro 
So we've been thinking about this. Leaning towards implementing the merge code on mobile - just to avoid server sync bombing mobile sites with patchy connections - sync is already painful in some places, don't need to strain it.

As mobile pushes before pulling from the server, the server will still have to handle mobile pushing records referencing merge-deleted records. This is detectable/handleable; If a record comes in referencing a ID of item/name that no longer has a record, that means that the sync out record of the merge is still on the server sync_out table. This should be enough for the server to correct the incoming record.

**Comment by edmofro** [comment]
Sweet

**Comment by Chris-Petty** [comment]
In regard to the last idea, keeping the arrays/table recording merges would probably still be necessary as old mobile sites will still do nothing with a merge record and acknowledge them. Further research needed.

**Comment by adrianwb** [comment]
Just to clarify - if the server detects a field in an incoming record which needs to be merged, it would only send back that field to the sender in the sync_out (not the whole record, otherwise there is a chance that it could overwrite any other changes to the record which happen on the mobile side before it receives the sync_out from the server)

**Comment by andreievg** [comment]
I've add comment to: https://bugs.msupply.org.nz/view.php?id=8314 re how I see server implementation handling merge.

I don't think we need an updated record sent back from server.. another 'm' record should be sufficient (if the server handles merged id translation as per the mantis comment)

**Comment by andreievg** [comment]
https://github.com/sussol/msupply/pull/1375 + comment in https://bugs.msupply.org.nz/view.php?id=8314 

I've asked a question in (it's relevant to Mobile implementation of merging):

`I have a question: What happens to fields like [trans_line]item_name during merged, does desktop update it to reflect new [item]item_name`

**Comment by andreievg** [comment]
@adrianwb mobile handles merge now : ), it will be in the next mobile release (some final testing to do).

@craigdrown raised an interesting point, how can we get rid of overhead from `merged_ids` table lookup in every sync push ? (even though in my initial benchmark, with thousands of record in merged_ids table, the performance decrease was negligible, still we should think about improvements on that front).

One suggestion is this (only works if both satellite and primary are on this particular version):

* Remove the merge_ids table
* Put the merge records as the first one in the sync_out table (for all sites) (see note below)
* When push from satellite happens (before pull), we check if the first record in sync_out for that site is merge, if it is, then don't process the push but respond with that merge record (see note below)
* Satellite recognises that merge needs to happen, does the merge and tries to push again.

(note below) -> there could be another way to identify that merge needs to happen on a site that is pushing record (site table maybe?)

Of-course, if this change is introduced, satellite/mobile will need to be able to handle it, was wondering if we should add this functionality to mobile/satellite sooner then later. (seems like a small change)

@adrianwb 
Anyways, no urgency, but would be good to hear what you think

**Comment by adrianwb** [comment]
@andreievg What you've suggested sounds plausible, but I'm not convinced that it's worth spending any significant time & effort on trying to reduce this overhead which, as you've found, doesn't seem to have a significant impact anyway. Merges are only supposed to happen infrequently, so if you've got enough records in the merge table to affect performance, then you've got bigger problems! We can always manually purge old merge records if needed, or if we know that all mobile sites have been upgraded to be able to handle merge records. 

BTW, resending a sync merge record should be harmless - if the ID to be merged no longer exists (e.g. if it has already been merged), then there's nothing to do.
