### ISSUE TITLE
Program storeTags should be case insensitive

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1611]
## Describe the bug

Linked issue: https://github.com/sussol/msupply/issues/4664

a mobile stores tags are saved as is, and a programs store tags are saved as is. This can make them mismatch. These should ignore case.

### To reproduce

See linked issue

### Expected behaviour

See linked issue

### Proposed Solution

See linked issue

### Version and device info

- App version: All
- Tablet model: aLL
- OS version: all

### Additional context

See linked issue

**Comment by joshxg** [comment]
Closed by #1614

**Comment by diegoevangelisti** [comment]
## Testing

Set up a program such that the `[store]tags = test1` and a `program.storeTag = TEST1`

- [x] Mobile recognizes the program being for the store with the above setup

**Success**
Tested using test1 (store tag) and TEST1 (program store tag), test1 and Test1, both options worked fine.
