### ISSUE TITLE
Removing a stocktake from the Current list doesn't work properly

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1615]
## Describe the bug

After removing a stocktake from the Current list, it's not deleted until the user goes to Menu Page, comes back to Stocktages page and remove the mentioned stocktake again.

![deleted-stocktake-doesnt-go](https://user-images.githubusercontent.com/32987464/69688896-414cb200-112c-11ea-805b-c2d7bf1c4b20.gif)

### To reproduce

1. Go to Stocktakes page.
2. Remove a stocktake from the Current list.
3. See error

### Expected behaviour

Removing a stocktake from the current list must work on the first attempt.

### Version and device info

- App version: v3.0.4
- Tablet model: Lenovo TB-X304L
- OS version: Android 8.1.0

Also tested on Android Emulator (Name: WXGA API 28, OS version: Android 9.0)

**Comment by joshxg** [comment]
Closed by #1617

**Comment by Rebecca367** [comment]
Tested removing current stocktake from stocktake list on 2 conditions.
1. 
While there were 2 stocktakes - Needed several attempts to remove the first stocktake. Once the first one been removed, the second one was removed easily.
2.
While there was only 1 stocktake- couldn't remove it.

Did the testing on Galaxy Tab A(2016)
Samsung experience version - 9.5
model number - SM-T580
serial number - R52H70KSW5Y
Android version - 8.1.0

**Comment by joshxg** [comment]
@Rebecca367 Was this on the most recent develop branch? This issue was only fixed in the last few days

**Comment by Rebecca367** [comment]
@joshxg I am on the dev. branch but couldn't remove new stocktake just been created. Diego recommended me to renew apk on physical tablet or testing on emulator., What is your opinion?

**Comment by joshxg** [comment]
Was your testing done on a tablet with an APK? If so, you should re-build an APK, otherwise the fix for this issue won't be in your APK - cheers

**Comment by Rebecca367** [comment]
@diegoevangelisti @joshxg thanks for support and reply.
It's all good now by testing it on emulator.
cheers
