### ISSUE TITLE
Can type letters into stocktake batch quantity field and crash app

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1621]
## Describe the bug

When editing stocktake batches, you can type in non-numeric characters. Even with numeric keyboard, any operators visible will crash app if entered.

![Screen Shot 2019-11-21 at 11 43 23](https://user-images.githubusercontent.com/7684221/69833433-b806be00-1298-11ea-9e16-d9cc0cc7d857.png)

![Screen Shot 2019-11-21 at 11 43 14](https://user-images.githubusercontent.com/7684221/69833436-bc32db80-1298-11ea-9708-06c3df0c498d.png)

### To reproduce

Description should be enough.

### Expected behaviour

Sanitises input like all other quantity fields.

### Version and device info

- App version: 3.0.4dev
- Tablet model: emulator
- OS version: android9

**Comment by joshxg** [comment]
Closed by #1644

**Comment by Rebecca367** [comment]
## Testing

- [x] Can edit a `StocktakeBatch` with any positive integer and have make a persistent change.
- [x] Entering invalid values into a `StocktakeBatch` quantity column ("!", "a" etc.) makes no change
