### ISSUE TITLE
Mispelt title ManageStockake

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1626]
## Describe the bug

The localized string `navStrings.manage_stocktake` is incorrect `"Manage Stockake"`

### To reproduce

N/A

### Expected behaviour

Should be spelt correctly

### Proposed Solution

Should be spelt correctly

### Version and device info

- App version: All
- Tablet model: All
- OS version: All

### Additional context

N/A

**Comment by Rebecca367** [comment]
@joshxg 
Have found where to make a change.
![Screen Shot 2019-12-02 at 12 10 57 PM (2)](https://user-images.githubusercontent.com/57238075/69922072-89d5e800-14fd-11ea-8675-4f53a220d724.png)

**Comment by Rebecca367** [comment]
@joshxg 
changes are in github now
Thanks

**Comment by Chris-Petty** [comment]
@Rebecca367 you should make a pull request for your changes. A handy shortcut in Github desktop is `cmd+R` when viewing your desired branch.

https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request

Remember to make sure it's aimed at the right base branch. In this case when the browser PR page comes up, you'll want to change base to `develop` as that is destined to be the 3.1.0 release.

**Comment by joshxg** [comment]
Closed by #1628

**Comment by Rebecca367** [comment]
@joshxg @Chris-Petty @diegoevangelisti 
thanks for helping with this matter in different ways.
