### ISSUE TITLE
Native multi select component

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1631]
## Is your feature request related to a problem? Please describe.

Want a component similar to the multi select native component shown here: https://material-ui.com/components/selects/ and we don't have it

## Describe the solution you'd like

Make a component similar to the multi select native component shown here: https://material-ui.com/components/selects/

## Implementation

Should just be a simple FlatList with no frills

## Describe alternatives you've considered

Not doing this//using a flat list

## Additional context

N/A

**Comment by sworup** [comment]
https://github.com/openmsupply/mobile/blob/develop/src/widgets/MultiSelectList.js
This multi-select list is pretty generic, we can modify it and should make it work for entire mSupply.
 
We just need to add-
1. selected pills with individual remove (X) buttons.
2. Toggle select/deselect all

**Comment by joshxg** [comment]
I was thinking of something more similar to this 

<img width="217" alt="image" src="https://user-images.githubusercontent.com/35858975/70884196-28a02f80-203a-11ea-945a-87cd814e9e60.png">

Rather than a modal. 

This is for dispensing, so want to reduce the number of clicks and time taken

**Comment by sworup** [comment]
@joshxg The most of the code in `MultiSelectList` is very much similar similar to what we would do for drop-down. We would be creating dropdown with list tags. Maybe can create a base generic component that both share.

**Comment by joshxg** [comment]
going to close this as I don't think this is needed anymore!
