### ISSUE TITLE
No select MANY/ALL icons on items select model in supplier requisition page

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#1638]
## Is your feature request related to a problem? Please describe.
There is no icon to select "ALL" items or select "MANY" items at the same time on "new item" model in supplier requisition page.
Model is cleared and go back to requisition page after one item is selected on the model.
User needs to click on "new item" icon to add more items.

 ## Implementation
 not sure.

## Describe the solution you'd like
An icon of "ALL ITEMS" shown on new item model.

## Describe alternatives you've considered
Allow users to select multiple items at the same time in supplier requisition page. 

## Additional context

![Screenshot_1575410886](https://user-images.githubusercontent.com/57238075/70094101-a81b1f80-1686-11ea-9c5b-27fde613100c.png)
![Screenshot_1575410970](https://user-images.githubusercontent.com/57238075/70094134-bd904980-1686-11ea-91ae-520db6b5636b.png)
![Screenshot_1575411359](https://user-images.githubusercontent.com/57238075/70094479-76568880-1687-11ea-9813-b57f813245f7.png)

**Comment by joshxg** [comment]
@Rebecca367 

1. Can we please follow the issue template with the provided headings? Even if you put `N/A` or, `not sure` - that is ok, but if we proceed with this issue, a plan for implementation would be good, which there is a heading for - we can edit this in later. I've also added some labels and a milestone so you can see for your next issues.
2. I agree 100% that this should be a feature we add. It is very cool! I want to just point out this term here: https://searchcio.techtarget.com/definition/feature-creep -- adding features like this, while it may not take too much time, does take away from other features we could be implementing (which we might be getting paid for), or bugs we could be fixing. Again, I love this idea I don't want to discourage you, just something to keep in mind!

**Comment by Rebecca367** [comment]
@joshxg 
1. The template already been modified. FYR. Thanks for helping with labels and milestones. I was going to implement these features on the issue page.
2. It's a good website to reference to. I totally agree with the concept it is trying to convey.
cheers!
