### ISSUE TITLE
Program goes crash once click on " create automatic order" on the top right in supplier requisition page  

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#1640]
## Describe the bug

![Screenshot_1575411919](https://user-images.githubusercontent.com/57238075/70095093-c4b85700-1688-11ea-84bb-f302d7aa1c17.png)
![Screenshot_1575411958](https://user-images.githubusercontent.com/57238075/70095125-da2d8100-1688-11ea-85d8-23c8b44855e4.png)

### To reproduce

1. Go to '...supplier requisition page '
2. Click on '...create automatic order.'

### Expected behaviour
Expected to have a clear page of automatic order
No "create automatic order" button if there is no function or event after it is clicked.

**Comment by joshxg** [comment]
Fixed by #1642

**Comment by diegoevangelisti** [comment]
## Testing

*This PR relates to the `Create Automatic Order` Button on `SupplierRequisitionsPage`*. An automatic order will add all items to the requisition which have a suggested quantity > 0, and will set the `requested quantity` to the `suggested quantity`.

- [x] Clicking `Create Automatic Order` creates an automatic order and does not crash the app!

**Success** 
Looking good now.
