### ISSUE TITLE
Error message occurs while selecting masterlist at CustomerEditingPage to add Master List Items

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#1645]
## Describe the bug

Error message occurs after selecting masterlist at CustomerEditingPage to add Master List Items.

### To reproduce

1. Go to '...customer invoices->new invoice
2. Click on 'search for customer ...add masterlist'-> select master list

### Expected behaviour

Bring items listed up on the master lists that were selected

### Proposed Solution
refer #1212  

### Version and device info

N/A

### Additional context
<img width="1440" alt="Screen Shot 2019-12-05 at 9 46 46 AM" src="https://user-images.githubusercontent.com/57238075/70182303-75d1f680-1748-11ea-8612-5913c1caba7a.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 9 47 05 AM" src="https://user-images.githubusercontent.com/57238075/70182308-79fe1400-1748-11ea-9fc4-4384834c8869.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 9 47 19 AM" src="https://user-images.githubusercontent.com/57238075/70182315-7ec2c800-1748-11ea-9d6b-e469a5b238af.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 9 47 25 AM" src="https://user-images.githubusercontent.com/57238075/70182318-808c8b80-1748-11ea-8cfe-8a6290ea87c6.png">

**Comment by joshxg** [comment]
Closed by #1646

**Comment by Rebecca367** [comment]
## Testing

- [x] Adding items from a master list on `CustomerInvoicePage` adds items from the selected masterlists
- [x] Adding items from a master list on `SupplierRequisitionPage` adds items from the selected masterlists
- [x] Creating a `Program` Requisition works correctly - adds all items to the requisition for that program.
- [x] Using the `Create Automatic Order` button on `SupplierRequisitionPage` correctly creates an auto matic order.
