### ISSUE TITLE
When creating a program requisition, an item is taking the price of a different Item

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1647]
## Describe the bug

Related with #1407 
When having two master lists related with a mobile store, it is taking the highest price as expect. But at the same time it is applying that max price to the rest of the products in the ML.

Like in the following example:
![Screen Shot 2019-12-05 at 9 39 00 AM](https://user-images.githubusercontent.com/32987464/70179852-b2e7ba00-1743-11ea-83e4-000c853e9b25.png)

ITEM CODE 050457, Price: 30 -> Ok. Should be 30 because in the other ML it is 15.
ITEM CODE 047285, Price: 30 -> Wrong. Should be 20. This product only belongs to ML New Program and price is 20.

New Program and Test Program are the only two ML programs related with this mobile store.
![Screen Shot 2019-12-05 at 9 47 33 AM](https://user-images.githubusercontent.com/32987464/70180164-59cc5600-1744-11ea-8c71-a93872ccd419.png)

In New Program, Price of ITEM CODE 047285 is 20.
<img width="688" alt="Screen Shot 2019-12-05 at 9 38 07 AM" src="https://user-images.githubusercontent.com/32987464/70179961-e9253980-1743-11ea-8bc8-2d86358e5263.png">

And ITEM CODE 047285 doesn't belong to Test Program. (so it doesn't have a another price rather than 20)
<img width="661" alt="Screen Shot 2019-12-05 at 9 38 46 AM" src="https://user-images.githubusercontent.com/32987464/70180064-28ec2100-1744-11ea-8bcc-7c0cfe7be230.png">

### To reproduce

- [ ] Create two masters lists for the mobile store. At least one should be a program. Add an item with different prices. Create a program requisition with the item (ITEM 1) and add a different item (ITEM 2).
- [ ] See that ITEM 2 is taking the price of ITEM 1.

### Expected behaviour

ITEM 2 shouldn't take the price of ITEM 1, they are not related.

### Version and device info

- App version: v3.0.4
- OS version: Android 9.0 (AVD)

**Comment by joshxg** [comment]
@diegoevangelisti 

Nice find!!!

**Comment by joshxg** [comment]
Closed by #1658

**Comment by joshxg** [comment]
### To reproduce

Steps to reproduce the behavior:

- [x] Create two masters lists for the mobile store. At least one should be a program. Add an item with different prices. Create a program requisition with the item (ITEM 1) and add a different item (ITEM 2).
- [x] See that ITEM 2 is taking the price of ITEM 1.

beautiful, passed
