### ISSUE TITLE
Bold/ Highlight the current row

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#1657]
**Describe the bug**
Currently when editing a cell in a row, there is not enough visual feedback of what row the the user has focused.

**To reproduce**

Go to a unfinalised customer invoice
Add a few items if there aren't any
Focus textinput of quantity field of an item
WANT: the row that focused cell is in to be highlighted.

**Expected behaviour**
The row currently with focus in it should be highlighted in some manner. Either highlight the row by changing the background colour. BONUS: Get fancy and highlight the row and bold the text in the cell with focus if you like.

**Solution**
This will require some in-depth knowledge of the page and data table state management.

1. Add action constant "focusCell"
Create an action creator function in cellActions.js. Action payload should have rowKey and columnKey
2. Add a reducer function in cellReducers.js that immuntably sets: dataState.row[action.rowKey].focusedColumn = action.columnKey (likely catch, if the focus has moved from one row to another, need to clear the focusedColumn from the previous rowState object)
3. Add a function onFocusCell to getPageDispatchers that dispatches the above action.
TextInputCell.js needs prop for onFocus that passes into the TextInput props. The component should make a method that calls it with rowKey and columnKey.
4. DataTableRow.js needs to check rowState to see if it's "focusedColumn" has a value and highlight the row if so.
Version and device info
App version: all
Tablet model: all
OS version: all
Additional context
Original description:

When editing a stocktake in particular, but also requisitions etc., it can be easy for a user to enter the quantity on the row above or below the one they mean to. The contrasting lines help with that, but apparently not enough. Would be great to highlight or bold the currently edited item to make it clearer!

**Comment by Rebecca367** [comment]
@mark-prins 
Thanks for the response but there is one as below:
https://github.com/openmsupply/mobile/issues/1657 unless it's been closed for some reasons.

**Comment by joshxg** [comment]
Closed
