### ISSUE TITLE
There should be NO Settings button in the bottom right of the menu page.

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#1665]
## Describe the bug

Setting page is in the bottom right of the menu page when user doesn't have view/edit preference permission.

### To reproduce

1. Go to '...log-in menu page'

### Expected behaviour

There is no setting bottom in the bottom right of the menu page when user doesn't have view/edit preference permission.

### Proposed Solution
not sure

### Version and device info

- App version: 3.1.0
- Tablet model:
- OS version: macOS 10.14.6

### Additional context
N/A
There is setting icon with a user WITHOUT `view/edit preferences` permission
<img width="1440" alt="Screen Shot 2019-12-11 at 8 32 51 AM" src="https://user-images.githubusercontent.com/57238075/70563202-b02d0f00-1bf2-11ea-9da0-621cdb8d99c4.png">
<img width="1440" alt="Screen Shot 2019-12-11 at 8 34 14 AM" src="https://user-images.githubusercontent.com/57238075/70563214-b58a5980-1bf2-11ea-98bd-a1d58c4e885f.png">

**Comment by joshxg** [comment]
@Rebecca367 

When I take the permission off a user:

![image](https://user-images.githubusercontent.com/35858975/70569550-0738e100-1bff-11ea-9183-e696e4278664.png)


When I log in again, I do not have the settings button:

![image](https://user-images.githubusercontent.com/35858975/70569570-1029b280-1bff-11ea-9315-e081d33b18f4.png)

Is your mobile store `General Warehouse` because I think that is the permission you removed, although your screen shot is small so it is hard to see exactly.

**Comment by Rebecca367** [comment]
Does that mean store matters?

**Comment by joshxg** [comment]
Yes - as I demonstrated, you would need the permission for the mobile store

**Comment by Rebecca367** [comment]
Setting icon still there even though I selected Hufflepuff health center

<img width="1440" alt="Screen Shot 2019-12-12 at 8 36 41 AM" src="https://user-images.githubusercontent.com/57238075/70654191-ae2e8300-1cba-11ea-9136-2b07a2c8d501.png">

![Screen Shot 2019-12-12 at 8 34 52 AM (2)](https://user-images.githubusercontent.com/57238075/70654209-b5559100-1cba-11ea-92bc-ea2b38ed2b2a.png)

![Screen Shot 2019-12-12 at 8 36 01 AM (2)](https://user-images.githubusercontent.com/57238075/70654180-a969cf00-1cba-11ea-8502-71b8596ab3a6.png)

**Comment by joshxg** [comment]
@Rebecca367 

I can't recreate this problem :( 

After you changed the preference, did you re-login?

**Comment by diegoevangelisti** [comment]
@Rebecca367 When you login in the mobile app, are you doing it as Admin user or Hufflepuff? I reckon that's the mistake. 
If you changed the permissions for Admin user in Hufflepuff Health Centre you should log in with that user.

Change permission for Admin:
<img width="768" alt="Screen Shot 2019-12-12 at 9 35 01 AM" src="https://user-images.githubusercontent.com/32987464/70658502-fe114800-1cc2-11ea-862a-1e6fc814c284.png">

Login as Admin:
![Screen Shot 2019-12-12 at 9 35 50 AM](https://user-images.githubusercontent.com/32987464/70658513-010c3880-1cc3-11ea-86d7-47ea2e66b26b.png)

Settings options hidden now:
![Screen Shot 2019-12-12 at 9 36 01 AM](https://user-images.githubusercontent.com/32987464/70658523-036e9280-1cc3-11ea-85ba-3985c03dd993.png)

Hope this can help, it is working for me.

**Comment by Rebecca367** [comment]
I did both to try on both users . but still the same.
I duplicate the same procedure as it is described.
It's the same that there is setting page on the right hand side of menu page.

**Comment by Rebecca367** [comment]
All done. All good now. Thanks for Diego's help with troubleshooting.

**Comment by joshxg** [comment]
Cool - I will close this issue then
