### ISSUE TITLE
Add section 'Scripts' in mSupply Mobile Developer Portal

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1677]
## Is your feature request related to a problem? Please describe.

I believe a new section should be added in the setup documentation to explain how scripts available in `/dev_scripts` work, what they do, how to run them, etc. I reckon there are some scripts that are really useful and new developers that start working on the repo don't know them or how to use them properly (happened to all of us I guess).

Also, a new doc will have to be added (ready or almost) after #1661 is merged, and this can be a good way to incorporate all together in a proper section.

## Describe the solution you'd like

Add a new section named **Scripts** under section **Development guide** maybe or in the main section to make it more handy and visible.

## Implementation

Add .md files explaining how the scripts work, their main purpose, how to run them, etc.

## Describe alternatives you've considered

Don't add anything ;-)

@wlthomson and any other interested, what do you think about it?

**Comment by joshxg** [comment]
more documentation is always welcomed :)

**Comment by diegoevangelisti** [comment]
Great, thanks @joshxg!I will assign myself to this one later and happy to get feedback from anyone related with these docs.

**Comment by diegoevangelisti** [comment]
I am going to close this one since the section was properly added and now can be edited when necessary.
