### ISSUE TITLE
App crashes when opening an un-finalised supplier requisition

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1681]
## Describe the bug

When opening a current Supplier Requisition, the app shows the following error. 
![maxLineserror](https://user-images.githubusercontent.com/32987464/70769361-102bdd00-1dce-11ea-965f-836e11b52ff7.gif)

### To reproduce

**Important note before testing**: That happened when I had 64 supplier requisitions Un-finalised. After removing many of them (actual number is 31) I couldn't reproduce the error. Need to check what is the number in which this error comes up.

1. Go to Supplier Requisitions Page
2. Open a current (Un-finalised) requisition
3. See error

### Expected behaviour

Should be able to open the requisition that was clicked.

### Version and device info

- App version: v3.1.0
- Tablet model: AVD
- OS version: Android 9.0

**Comment by joshxg** [comment]
@diegoevangelisti I can see the problem - so I will take this real quick so we can get a patch out for it

**Comment by joshxg** [comment]
Closed by #1682

**Comment by Rebecca367** [comment]
## Testing

- [x] Can finalise a non-program supplier requisition without the app crashing
