### ISSUE TITLE
Localization for dispensing

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1693]
## Is your feature request related to a problem? Please describe.

This is an issue for the dispensing feature branch localization, to track all introduced strings. This should be completed toward the end of the feature introduction.

## Describe the solution you'd like

- At minimum, french translations for all strings introduced

### List of issues/cpde where strings are introduced:

- #1694 
- titles in https://github.com/openmsupply/mobile/blob/%23feature-dispensary/src/navigation/actions.js
- #1702 
- #1724 
- #1750 
- #1749 
- #1747 
- #1759
- #1750
- #1734 
- #1810 
- #1784 
- #1785

**Comment by mark-prins** [comment]
[spreadsheet](https://docs.google.com/spreadsheets/d/1r-hdhIHvuZ7XDSiEmL8lLgtLfww5E-XHMrEwoU3BMg0/edit#gid=0) created to track translations

**Comment by joshxg** [comment]
Closed by #2070
