### ISSUE TITLE
Validation strings should use consistent casing and nesting

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1695]
## The suggestion

Most/majority of localized strings are key/value pairs in objects with snake_case. Some/minority are camelCase and an even smaller amount are nested within other objects. I think this should be consistent. One level deep, snake_case OR camelCase, I don't mind but snake_case would be easier.

**Why?**
It's a small amount that is inconsistent (`validationStrings`/`demoUserModalStrings`) and the sooner we can do this, the less work it will be if it is ever done and the more consistent this is the better.

## Describe alternatives you've considered

N/A

## Additional context

@diegoevangelisti might have thoughts!

and I'm sure @Chris-Petty and @wlthomson do also!

**Comment by diegoevangelisti** [comment]
Yes, this is a good point! We have considered this issue with @andreievg and we ended up with the idea of converting the camelCase strings you mentioned (no so many) to snake_case to keep consistency in all files. I have planned to commit those changes soon (today/tomorrow when ready), I am working on that now.

More than welcome to listen if anyone has a different opinion :-)

**Comment by joshxg** [comment]
so this issue is being taken care of by you in a different issue? great! should I close this?

**Comment by diegoevangelisti** [comment]
> so this issue is being taken care of by you in a different issue? great! should I close this?

Yes, it is basically coming with the new scripts to import/export json files and that was done in the first part (converting js files to json). Arriving soon if it is all good

**Comment by joshxg** [comment]
Sweet, i'll close this then :)

**Comment by Chris-Petty** [comment]
Yup a fan of doing these as snake case, consistency of that is goo
