### ISSUE TITLE
Dashboard dependencies

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1706]
## Is your feature request related to a problem? Please describe.

Need to add dependencies used in the `Dashboard` feature.

## Describe the solution you'd like

Add the dependencies 

- `victory`
- `react-native-svg`
- `victory-native`

## Implementation

Follow instructions: https://github.com/FormidableLabs/victory-native

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by diegoevangelisti** [comment]
@joshxg 
Just a comment related with these dependencies, as far as I understood there is no need to install `victory` (which is for React) but yes we have to go ahead with the other two (`victory-native` and `react-native-svg`) and then link them.

**Comment by andreievg** [comment]
yep, i don't see a reason for `victory` to be installed

**Comment by joshxg** [comment]
oopsies
