### ISSUE TITLE
Add Report class to realm schema

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1708]
## Is your feature request related to a problem? Please describe.

Add the `Report` class to the realm schema.

## Describe the solution you'd like

The a report class with the following fields

![image](https://user-images.githubusercontent.com/35858975/70942284-334adb00-20b3-11ea-8430-a59546b4b920.png)

Note that this is slightly different from the previous dashboard PR schema as well as the desktop schema. I don't think the additional fields are needed, but I could be wrong

## Implementation

I think this should be a `Realm` class, as it would be very helpful to have getters and setters later

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
had an idea that in the schema the `data` field could be called `_data` .. then have defined in the class

```
get data(){
     return JSON.parse(this._data)
}
```

and 

```
set data(dataObject){
    this._data = JSON.stringify(dataObject)
}
```

So that when handling the `data` field, you just handle it as if it is an object..

**Comment by diegoevangelisti** [comment]
> had an idea that in the schema the `data` field could be called `_data` .. then have defined in the class
> 
> ```
> get data(){
>      return JSON.parse(this._data)
> }
> ```
> 
> and
> 
> ```
> set data(dataObject){
>     this._data = JSON.stringify(dataObject)
> }
> ```
> 
> So that when handling the `data` field, you just handle it as if it is an object..

I like your idea. I created Report Schema following your suggestion:
```
Report.schema = {
  name: 'Report',
  primaryKey: 'id',
  properties: {
    id: 'string',
    type: 'string',
    title: 'string',
    _data: 'string',
  },
};
```
More fields can be added if necessary, mainly talking about this https://github.com/openmsupply/mobile/issues/441
