### ISSUE TITLE
Add Report class getters and setters

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1709]
## Is your feature request related to a problem? Please describe.

Since the `data` field on the `Report` object will be a stringified JSON object, it would be very helpful to have getters/setters to help save these fields.

## Describe the solution you'd like

I imagine a field `get data()` would be very helpful, which would handle the parsing. The same with a `set data(Object object)` field. Basically getters/setters which make dealing with a JSON Stringified object a lot easier.

## Implementation

Not 100% sure!

## Describe alternatives you've considered

N/A

## Additional context

Maybe this is better done after the `Report` class has been used a bit to understand what would be needed, not sure!

**Comment by diegoevangelisti** [comment]
@joshxg 
We need to add getters for `@property type` and `title` here as well, right?

**Comment by joshxg** [comment]
@diegoevangelisti nope - if you don't provide a getter/setter this will act just the same as a normal object property.
