### ISSUE TITLE
Add Report to incomingSyncUtils

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1710]
## Is your feature request related to a problem? Please describe.

Need to add the new `Report` class to `incomingSyncUtils` to enable sync

## Describe the solution you'd like

Add a `case` for the `Report` class in `incomingSyncUtils`

## Implementation

Dependent on the final schema, need to simply add a case statement which will save a report that has come in hot from the server to the database.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by andreievg** [comment]
https://github.com/sussol/msupply/issues/2179
