### ISSUE TITLE
Dashboard button on MenuPage

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1712]
## Is your feature request related to a problem? Please describe.

Need to add a Dashboard button to the `MenuPage`

## Describe the solution you'd like

When enabling the dashboard, the dashboard button should shown on the main page, similar to how dispensary/vaccines is working. 

Modules introduced in this PR: https://github.com/openmsupply/mobile/pull/1488

Will need to finalise a `[store]customData` field which when synced to desktop, will enable the dashboard module and the button.

## Implementation

- Will need to add a `usingDashboardModule` field to `ModulesReducer`
- Add a `Dashboard` button to the menu page when dashboard module is enabled.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
@diegoevangelisti 

To fully understand this it does get a little complicated but will give a go explaining, although it's a little uneeded:


A store has custom data - a JSON object with random things here in desktop:
![image](https://user-images.githubusercontent.com/35858975/71052293-c49f7780-21af-11ea-85b7-33655aebd3d7.png)

When we sync it comes in from `incomingSyncUtils`: https://github.com/openmsupply/mobile/blob/9067a20101d8ffa835e1ad962699957525406853/src/sync/incomingSyncUtils.js#L591-L603

AFTER sync occurs, the `PostSyncProcessor` runs and manages all the custom data: https://github.com/openmsupply/mobile/blob/9067a20101d8ffa835e1ad962699957525406853/src/sync/PostSyncProcessor.js#L89-L120

Then, in the `ModulesReducer` https://github.com/openmsupply/mobile/blob/master/src/reducers/ModulesReducer.js it's passed to `MenuPage` through props!



--------


All of this is to say, if you  add a custom data field here on desktop for your store:

![image](https://user-images.githubusercontent.com/35858975/71052399-134d1180-21b0-11ea-95ac-52a040301374.png)


I think `usesDashboardModule` will work, we can change if people don't like that!

Then, in `ModulesReducer` add a new `dashboardModule` field.. then that should be passed to `MenuPage` in `mapStateToProps` to pass you a value to know if you're using the dashboard.. then you can use that to show a button! 


I think this probably still isn't 100% clear but I will leave it to you to ask questions that I will answer!

**Comment by diegoevangelisti** [comment]
@joshxg 
Really clear instructions, thank you so much for that 😃
