### ISSUE TITLE
Add docs string for all files added in feature/Dashboard

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1745]
## Is your feature request related to a problem? Please describe.

Many new files are being added while working on the new dashboard for Mobile, and it would be really useful to add all doc string to explain as much as possible: what the component/action/dispatcher/reducer/utility/etc does, how to use it, which are the params, etc.

## Describe the solution you'd like

Add doc string to each file added in the branch feature/dashboard and try to be as much explanatory as possible. So much important when our code is analise by somebody else.

## Implementation

Add docs strings (comments) at top of each file and where needed as well. Follow the pattern used in other files.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #1932
