### ISSUE TITLE
Tidy up styles in new components in feature/dashboard

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1751]
## The suggestion

Work on tidying up styles in added components for the new feature/dashboard. Some similar code can be taken to extra dedicated files and then being imported.
Some issues where can be applicable: #1740, #1741, #1742, #1744 

**Why?**
This will create a more tidy and consistence code. Those mentioned component share some styles and it can be a good chance to organize them properly.

## Describe alternatives you've considered

Leave them like that, but that won't be the best case.

## Additional context

For example:
```
const localStyles = StyleSheet.create({
  ChartContainer: {
    width: '75%',
    minHeight: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
That code is shared by `PieChart`, `BarChart`, `LineChart`, `ReportTable` component.

**Comment by joshxg** [comment]
Closed by #1820
