### ISSUE TITLE
Remove Height and Width calculations  

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1765]
## The suggestion

Need to remove `height` and `width` (dimensions) calculation on `PieChart`, `BarChart` and `LineChart` because it's now being generated in their parent component and values are passed via props.

**Why?**
Those calculations are totally unnecessary extra code  Discussed here: #1760 

## Describe alternatives you've considered

Leave it like that, but not the best case to keep a neat code.

**Comment by joshxg** [comment]
Closed by #1820
