### ISSUE TITLE
Return goods to a supplier by selecting them on the supplier invoice and clicking a button

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#1770]
## Is your feature request related to a problem? Please describe.

An IC requested feature / customisation.
 
Returns   to supplier: link to supplier invoice stock was delivered on, can't return   more than is on invoice for individual items.

This is the mobile implementation of an mSupply change: https://github.com/sussol/msupply/issues/4437

## Describe the solution you'd like

1. A button on supplier invoices to allow you to return lines. Active only if invoice is finalised.
2. A field [trans_line].PacksReturned which is the number of packs already returned
3. Clicking button does checks [that qty returned is <= current stock and is <= (original num of packs - packsReturned), then creates a finalised supplier credit. 

## Alternatives

We recommended (Tony, in email of 24 September 2019) that this requirement be removed, as the requirement is unnecessary when there is only one supplier for a site! No response received from client re this. ([CD]: It is priced to IHSCTA though, so it didn't get removed).

**Comment by craigdrown** [comment]
@mark-prins I think for desktop implementation we don't have [trans_line].PacksReturned - the upper bound of what you can return is what you have in stock of the linked item_line ?

**Comment by joshxg** [comment]
@craigdrown @mark-prins 

I'm not 100% on the solution described:

Is this:
- Click a "Return Items" button which navigates to a page to create a supplier credit
- Click a button on a particular line which .. (not sure) opens a modal to type in amount to return? Does..?

**Comment by joshxg** [comment]
Forgot to comment after speaking with mark/craig

- Returns from the `StockPage`
- Column with a button to open a modal, which lists batches for an `Item`. Can return some amount of a batch and that creates a SC transaction

**Comment by joshxg** [comment]
Closed by #1983
