### ISSUE TITLE
NewConfirmModal to replace ConfirmModal

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1781]
## The suggestion

Currently there are two components `NewConfirmModal` and `ConfirmModal` each doing the same thing. `ConfirmModal` should be finally deleted and replaced completely with `NewConfirmModal`

**Why?**
Having both is not good!

## Describe alternatives you've considered

N/A

## Additional context

`ConfirmModal` is used in `DemoUserModal` and `finaliseModal`

**Comment by joshxg** [comment]
Closd by #2344

**Comment by ArpitaSussol** [comment]
Tested in 4.0.0

### Tests
- [ ] Click on CustomerInvoicePage to see if the page can be finalised and closed properly.- **PASS**
- [ ] Click on StocktakeEditPage to see if the page can be finalised and closed properly. - **PASS**
- [ ] Click on SupplierInvoicePage to see if the page can be finalised and closed properly. - **PASS**
