### ISSUE TITLE
Commit PopoverDropdown to develop

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1834]
## Is your feature request related to a problem? Please describe.

A component `PopoverDropdown` was created in the `feature-dispensary` branch which would be really helpful for the indicators feature branch.

## Describe the solution you'd like

Commit the `PopoverDropdown` component to develop

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by wlthomson** [comment]
Thanks!

Fixed by #1835.
