### ISSUE TITLE
Add logic for displaying indicators values 

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1848]
## Is your feature request related to a problem? Please describe.

Add actions/reducers and `SupplierRequisitionPage` props/logic for rendering indicator values in datatable.

## Describe the solution you'd like

See above.

## Implementation

TODO.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #1685.

**Comment by joshxg** [comment]
Closed by #1851
