### ISSUE TITLE
AutoCompleteSelector is not filtering with new SearchBar

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1866]
## Describe the bug

The AutoCompleteSelector using the new SearchBar it is not working properly while being tested in a Tablet (see details below). 

### To reproduce

- [ ] Download the APK and install it the tablet (or use the AVD)
- [ ] Go to customer invoice
- [ ] Click on "new invoice"
- [ ] Search for customers
- [ ] See error.

### Expected behaviour

The filter should be working properly (e.g. After typing `Baltimor` the rest of the options should hide).

### Proposed Solution

Mentioned by @joshxg 
https://github.com/openmsupply/mobile/blob/1223ef686342e963aadcc51fcb87d8ce3a593c9c/src/widgets/modalChildren/AutocompleteSelector.js#L34 this line is a problem. Should be:

`const inputValue => setQueryText(inputValue)`

### Version and device info

Tablet model Lenovo XB-X304L
Android version 7.1.1
APK: mSupplyMobile-3_2_0-rc1-universal-release.apk

**Comment by joshxg** [comment]
Closed by #1871

**Comment by Rebecca367** [comment]
## Testing on AVD 
Steps to reproduce or otherwise test the changes of this PR:

- [x] Download the APK and install it the tablet (or use an AVD)
- [x] Go to customer invoice
- [x] Click on "new invoice"
- [x] Search for a customer.
- [FAILED] See the filter is working ok.
![#1866 autocomplete search bar filtering test](https://user-images.githubusercontent.com/57238075/72106607-89e6c480-3394-11ea-8274-5fb475aae18e.gif)

**Comment by diegoevangelisti** [comment]
> ## Testing on AVD
> Steps to reproduce or otherwise test the changes of this PR:
> 
> * [x]  Download the APK and install it the tablet (or use an AVD)
> * [x]  Go to customer invoice
> * [x]  Click on "new invoice"
> * [x]  Search for a customer.
> * [FAILED] See the filter is working ok.
>   ![#1866 autocomplete search bar filtering test](https://user-images.githubusercontent.com/57238075/72106607-89e6c480-3394-11ea-8274-5fb475aae18e.gif)

Thanks for testing @Rebecca367 !
This is working for me, I can't reproduce that Failed test case. Just checking, are you working on develop branch?

**Comment by Rebecca367** [comment]
Had a version behind issue been resolved thanks to @diegoevangelisti  
I will move this to Done.

**Comment by diegoevangelisti** [comment]
> Had a version behind issue been resolved thanks to @diegoevangelisti
> I will move this to Done.

Thanks for the testing Rebecca! 😃
