### ISSUE TITLE
Not clear placeholder in SuppliersInvoices

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1873]
## Describe the bug

Related with #264

The placeholder `Search by INVOICE` in SuppliersInvoices is quite hide behind the toggles. See here:
![Screen Shot 2020-01-08 at 5 12 02 PM](https://user-images.githubusercontent.com/32987464/71950126-0bc2da80-323b-11ea-89bb-4f3dba073cb3.png)

### To reproduce

1. Go to SupplierInvoices page.

### Expected behaviour

The placeholder text should be clear, same as the rest.

**Comment by joshxg** [comment]
Closed by #1929

**Comment by Rebecca367** [comment]
success!
## Testing

**Might be different on different size emulators?**
- [x] `SearchBar` placeholder looks good in all the pages!
