### ISSUE TITLE
Dashboard fields are incorrect

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1878]
## Describe the bug

Currently, we have that the "data" object on a `Report` object from mSupply is `data` where in fact it is `json`.

### To reproduce

Development bug

### Expected behaviour

Rename occurences of `"data"` for `Report` to `json`

### Proposed Solution

N/A

### Version and device info

Dashboard development

### Additional context

N/A

**Comment by diegoevangelisti** [comment]
Closed by #1881
