### ISSUE TITLE
Removing records in `CustomerInvoicesPage` doesn't work

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1882]
## Describe the bug

App crushes when trying to remove one or more items in `CustomerInvoicesPage`. See here:
![modalError](https://user-images.githubusercontent.com/32987464/72102325-91ee3680-338b-11ea-9db2-9d4f0c71f18d.gif)

### To reproduce

1. Go to `CustomerInvoicesPage`
2. Select one or more records to remove
3. Click on the Delete option provided by the modal

### Expected behaviour

Items should be removed when the Delete button is pressed. 

### Version and device info

- App version: All
- Tablet model: All
- OS version: All

**Comment by joshxg** [comment]
So this is related to #1883 

Not tooo sure how this is occurring! definitely going to need some investigation

**Comment by Rebecca367** [comment]
@diegoevangelisti @joshxg 
This issue looks good on my side..
![customer invoicesa removal](https://user-images.githubusercontent.com/57238075/72487390-b6a64a80-3872-11ea-9002-21d5c69ca475.gif)

**Comment by diegoevangelisti** [comment]
@Rebecca367 
Yes, it seems to be an issue that is related with my data file (I had duplicate Invoice Numbers in that DF, when that shouldn't occur). Meanwhile, the idea is to keep this one open, in case it happens again in a different circumstance. Thanks for testing!😀

**Comment by Rebecca367** [comment]
So I will close this issue..
