### ISSUE TITLE
Change charts names to snake_case

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1897]
## Describe the bug

We are expecting to get chart types as `bar_chart`, `pie_chart`, `line_chart`, `table`, no those that are camelCase should be change to snake_case

### Proposed Solution

Change expected types in `ReportChart.js` to snake_case. Here:

```
switch (type) {
      case 'BarChart:
        return <BarChart data={data} height={height} width={width} />;
      case 'LineChart':
        return <LineChart data={data} height={height} width={width} />;
      case 'Table':
        return <ReportTable rows={rows} header={header} />;
      case 'PieChart':
        return <PieChart data={data} height={height} width={width} />;
      default:
        return null;
    }
```

### Additional context

These `types` must be similar as the ones generated in server side. If those changed, these ones should be updated as well.

**Comment by diegoevangelisti** [comment]
As discussed with @andreievg, by now the idea is to keep `PieChart`, `BarChart`, `LineChart`, `Table` since this is not a final decision. I am closing this one, but it can be reconsidered in the future if necessary.

**Comment by joshxg** [comment]
@diegoevangelisti I don't know what you guys discussed, but you may need to add these types to sync translations?

**Comment by diegoevangelisti** [comment]
> @diegoevangelisti I don't know what you guys discussed, but you may need to add these types to sync translations?

Basically that there is not a final decision about the types we are going to received (in camelCase, snake_case, etc). So by now those mentioned types are the same we were expecting since the beginning, and I _think_ nothing should be changed. Let me know if I'm wrong 😀

**Comment by joshxg** [comment]
@diegoevangelisti 

The types here: https://github.com/openmsupply/mobile/blob/5a595bfd77b167bc8898903585d12cf6486825c8/src/widgets/ReportChart.js#L30-L40

aren't they different from the types coming from desktop?

**Comment by diegoevangelisti** [comment]
By now, the only type coming is `Table`, the rest haven't been created on desktop side. That said, any time I run a new dashboard report on desktop the default type is Table, and I change it to whatever I need for testing purposes (PieChart, LineChart, BarChart). That's what I'm doing right now. Maybe @andreievg  can clarify a little bit more about it! 🙂

**Comment by diegoevangelisti** [comment]
> By now, the only type coming is `Table`, the rest haven't been created on desktop side. That said, any time I run a new dashboard report on desktop the default type is Table, and I change it to whatever I need for testing purposes (PieChart, LineChart, BarChart). That's what I'm doing right now. Maybe @andreievg can clarify a little bit more about it! 🙂

Btw, even if the data structure matches with the one expected for a pie, line or bar chart, the auto generated type is Table

**Comment by andreievg** [comment]
type is defined in dashboard parameters, 'reportType'.
