### ISSUE TITLE
Add Labels to Charts

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1898]
## Describe the bug

The `json` data arriving from the desktop version includes label information from all charts, so that can be added to explain in a better way the illustrated data.

### To reproduce

See that all rendered charts are not showing any labels.

### Expected behaviour

Show labels on charts 😃

**Comment by diegoevangelisti** [comment]
@joshxg 
Regarding the upcoming data from desktop, there are a couple of texts that should be consider when labeling:
`name`: The actual name of the report
`label`: Explains the data to be rendered

Example:
```
{
   "name":"ExpiringStock",
   "data":[
      {
         "label":"Cumulative",
         "values":[
            {
               "x":"1 month",
               "y":0
            },
            ...
         ]
      },
      {
         "label":"Monthly",
         "values":[
            {
               "x":"1 month",
               "y":0
            },
            ...
         ]
      }
   ]
}
```
Just to confirm, we are going to use `name` on top as the main title and then `label` close to its corresponding graph ?

**Comment by diegoevangelisti** [comment]
> @joshxg
> Regarding the upcoming data from desktop, there are a couple of texts that should be consider when labeling:
> `name`: The actual name of the report
> `label`: Explains the data to be rendered
> 
> Example:
> 
> ```
> {
>    "name":"ExpiringStock",
>    "data":[
>       {
>          "label":"Cumulative",
>          "values":[
>             {
>                "x":"1 month",
>                "y":0
>             },
>             ...
>          ]
>       },
>       {
>          "label":"Monthly",
>          "values":[
>             {
>                "x":"1 month",
>                "y":0
>             },
>             ...
>          ]
>       }
>    ]
> }
> ```
> 
> Just to confirm, we are going to use `name` on top as the main title and then `label` close to its corresponding graph ?

Instead of using name, I believe it's better to use directly the `title` coming from the report, which will reflect it in a perfect way.

**Comment by joshxg** [comment]
@diegoevangelisti 

That sounds good. You could also check in `incomingSyncUtils` for `name` and set that as `Report.title`, but I think leave it for now.

For label - yup that sounds correct
