### ISSUE TITLE
Migrate indicator helpers to datatable utilities

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1901]
## Is your feature request related to a problem? Please describe.

Indicator helpers are all imported via `utilities/getIndicatorTableData`. For consistency with other helpers and for reduced imports/dependency cycles, these should be moved to `dataTableUtilities`.

## Describe the solution you'd like

See above.

## Implementation

Migrate `getIndicatorTableData` methods to `Indicator` object classes.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by joshxg** [comment]
Since `UIDatabase` is imported, I think the way to fix the cycles is unfortunately by passing the database as an arg?

**Comment by wlthomson** [comment]
After investigating a bit more, the problem seems to be mainly caused by importing from `index` files instead of directly from the exporting files. Re. the database cycles, moving the helpers out of utilities and into the data table utilities should fix that. 

Will fix these two things and hopefully that should fix most of the problems.

**Comment by wlthomson** [comment]
Closed #1919,
