### ISSUE TITLE
Merge feature/dashboard into develop branch

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1922]
The feature/dashboard is ready to be merged into develop for further testing when both integrated.
All graphs (`PieChart`, `LineChart`, `BarChart` and `TableReport`) look like working ok, including navigation, messages, localization strings, colours, rendering, etc. based on requirements.

Complete project here:
https://github.com/openmsupply/mobile/projects/8

Thanks @joshxg for all your help, advices, reviews, patient and for being so fast at replying all the time!

**Comment by joshxg** [comment]
Closed by #1924
