### ISSUE TITLE
TESTING: Dashboard

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1927]
## Testing description

The main idea here is to test that all created graphs (Pie chart, Line chart, Bar chart and Table) are working as expected. 
This is just related with front end, so we are guessing that all the reports being under test are coming properly from desktop.

Doc related with dashboard reports (from desktop msupply):
https://docs.msupply.org.nz/playground:2020-01_sworup_dashboard

That being said, desktop need to be set up properly before testing. After that, Menu Page of mobile must show the Dashboard option. It would look like this:

<img width="754" alt="Screen Shot 2020-01-15 at 9 45 17 AM" src="https://user-images.githubusercontent.com/32987464/72381166-c98a2380-377b-11ea-8888-b302faff0bad.png">

#### Test case 1: Dashboard Page

- [ ] Go to DashboardPage (Menu page -> Dashboard)

**Option 1: No Reports to show**

If there is no reports to show (there's a problem with sync or there's no reports generated on desktop) this should be the case:

- [ ] Check that there is no items on the left side of the screen.
- [ ] See the message `No Reports to show` on the right side. It should be vertically and horizontally centered.

**Option 2: Reports available**

There are reports available to show. Then test the following:

- [ ] Check that on the left side of the screen there is a list of options with different reports.
- [ ] Each Report has its corresponding icon (one for Table, one for Bar chart, one for Line chart and other one for Pie chart)
- [ ] When clicking on a specific Report, its title's color changed to SUSSOL_ORANGE and the report it's being rendered on the right side of the screen.
- [ ] All reports are well contained on the right side of the screen.

For both options:
- [ ] Navigating back takes you to Menu Page again.

#### Test case 2: Line Chart

- [ ] Go to DashboardPage (Menu page -> Dashboard)
- [ ] On the left side bar click on a Line chart report (Check the icon to find one).

    - **Line chart with one set of values:**

- [ ] Check that the X and Y axis exists and include values.
- [ ] Verify that the line and dots color is SUSSOL_ORANGE.
- [ ] See that close to the line there's a `label` that represents what information it's been shown. Its colour should be SUSSOL_ORANGE as well.

    - **Line chart with more than one set of values:**

- [ ] Check that the x and y axis exists and include values.
- [ ] Verify that all line colors are different (one should be SUSSOL_ORANGE).
- [ ] See that close to each line there's a `label` that represents what information it's been shown. Its colour should be different but similar than the one used for the line.

#### Test case 3: Pie Chart

- [ ] Go to DashboardPage (Menu page -> Dashboard)
- [ ] On the left side bar click on a Pie chart report (Check the icon to find one).
- [ ] Check that the colours are different for each represented value.
- [ ] Verify that each value has its corresponding label. That will be its value and quantity in GREY colour.
Should look i.e like this: `Customer Invoices : 452`. General rule: `[Value] : [Quantity]`  
- [ ] Check that labels are separated enough space from the Pie chart and are clear to read and understand.

#### Test case 4: Bar Chart

- [ ] Go to DashboardPage (Menu page -> Dashboard)
- [ ] On the left side bar click on a Bar chart report (Check the icon to find one).
- [ ] Check that the X and Y axis exists and both include values.
- [ ] Check that all colours are similar for each bar (SUSSOL_ORANGE).
- [ ] Verify that each X value has its corresponding bar and value on top of it in GREY colour.

#### Test case 5: Table

- [ ] Go to DashboardPage (Menu page -> Dashboard)
- [ ] On the left side bar click on a Table report (Check the icon to find one).
- [ ] Check that there is a header row that includes header values for the corresponding table.
- [ ] Check that there below there are rows that contains values, left aligned and same font for and colour for all of them.
- [ ] Verify that scrolling down/up gives access to see more available rows with values (in case it applies to the selected report).

### Expected behaviour

All test cases should pass, otherwise please comment or point what is not working as expected.

**Comment by Rebecca367** [comment]
Thanks for @diegoevangelisti spending sometime helping with setup. It's successful for testing.
Well done!

### Test cases

#### Test case 1: Dashboard Page

- [x] Go to DashboardPage (Menu page -> Dashboard)

**Option 1: No Reports to show**

If there is no reports to show (there's a problem with sync or there's no reports generated on desktop) this should be the case:

- [x] Check that there is no items on the left side of the screen.
- [x] See the message `No Reports to show` on the right side. It should be vertically and horizontally centered.

**Option 2: Reports available**

There are reports available to show. Then test the following:

- [x] Check that on the left side of the screen there is a list of options with different reports.
- [x] Each Report has its corresponding icon (one for Table, one for Bar chart, one for Line chart and other one for Pie chart)
- [x] When clicking on a specific Report, its title's color changed to SUSSOL_ORANGE and the report it's being rendered on the right side of the screen.
- [x] All reports are well contained on the right side of the screen.

For both options:
- [x] Navigating back takes you to Menu Page again.

#### Test case 2: Line Chart

- [x] Go to DashboardPage (Menu page -> Dashboard)
- [x] On the left side bar click on a Line chart report (Check the icon to find one).

    - **Line chart with one set of values:**

- [x] Check that the X and Y axis exists and include values.
- [x] Verify that the line and dots color is SUSSOL_ORANGE.
- [x] See that close to the line there's a `label` that represents what information it's been shown. Its colour should be SUSSOL_ORANGE as well.

    - **Line chart with more than one set of values:**

- [x] Check that the x and y axis exists and include values.
- [x] Verify that all line colors are different (one should be SUSSOL_ORANGE).
- [x] See that close to each line there's a `label` that represents what information it's been shown. Its colour should be different but similar than the one used for the line.

#### Test case 3: Pie Chart

- [x] Go to DashboardPage (Menu page -> Dashboard)
- [x] On the left side bar click on a Pie chart report (Check the icon to find one).
- [x] Check that the colours are different for each represented value.
- [x] Verify that each value has its corresponding label. That will be its value and quantity in GREY colour.
Should look i.e like this: `Customer Invoices : 452`. General rule: `[Value] : [Quantity]`  
- [x] Check that labels are separated enough space from the Pie chart and are clear to read and understand.

#### Test case 4: Bar Chart

- [x] Go to DashboardPage (Menu page -> Dashboard)
- [x] On the left side bar click on a Bar chart report (Check the icon to find one).
- [x] Check that the X and Y axis exists and both include values.
- [x] Check that all colours are similar for each bar (SUSSOL_ORANGE).
- [x] Verify that each X value has its corresponding bar and value on top of it in GREY colour.

#### Test case 5: Table

- [x] Go to DashboardPage (Menu page -> Dashboard)
- [x] On the left side bar click on a Table report (Check the icon to find one).
- [x] Check that there is a header row that includes header values for the corresponding table.
- [x] Check that there below there are rows that contains values, left aligned and same font for and colour for all of them.
- [x] Verify that scrolling down/up gives access to see more available rows with values (in case it applies to the selected report).

**Comment by diegoevangelisti** [comment]
Thanks @Rebecca367 for your patient and for going through all test cases! 😀

**Comment by wlthomson** [comment]
@diegoevangelisti assuming all these test cases are up to date? If you could update any that need updated would be great (or if already up-to-date, just reopen the issue!).

**Comment by wlthomson** [comment]
On advice of @diegoevangelisti, bumping to `v6.0.0` as has been tested recently and is not worth the  relatively high time cost of getting another tester setup at this stage.

**Comment by diegoevangelisti** [comment]
@wlthomson Thanks! As you mentioned, there is nothing to be updated by now, and I agree with the decision to bump it to `v6.0.0`.
