### ISSUE TITLE
Hotfix indicators incoming sync

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1930]
## Describe the bug

Placeholder for hotfixing bug in indicator incoming sync.

### To reproduce

1. Sync program indicator data.
2. See error.

### Expected behaviour

No error.

### Proposed Solution

Fix `incomingSyncUtils.sanityCheckIncomingRecords` missing field.

### Version and device info

- App version: v3.2.0.
- Tablet model: emulator.

### Additional context

N/A.

**Comment by joshxg** [comment]
Fixed by #1931
