### ISSUE TITLE
syntax error message pops out on preference page in msupply

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#1944]
## Describe the bug

<img width="898" alt="Screen Shot 2020-01-17 at 8 23 26 AM" src="https://user-images.githubusercontent.com/57238075/72559489-c6bd3900-3909-11ea-9599-d356cdfe78b9.png">

### To reproduce

1. Go to 'msupply'
2. Click on 'admin'->'preference'
3. See error

### Expected behaviour

Expect normal behaviour which is no error message occurs when you click on buttons. 

### Version and device info

- App version: v3.2.0-rc3
- Tablet model: emulartor
- OS version: 

### Additional context

Never happen before, so maybe relate to rc upgrading?

**Comment by DhanyaHerath** [comment]
Hi @Rebecca367 this looks like it's happening in desktop, not mobile - so you would want to make an issue in the mSupply desktop repository (https://github.com/sussol/msupply/issues). 

Diego has also made one that is the same (https://github.com/sussol/msupply/issues/5175) so I will close this one - thanks!

**Comment by Rebecca367** [comment]
@DhanyaHerath 
got it!
