### ISSUE TITLE
PropTypes in SupplierRequisitionPage

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1950]
## Describe the bug

- Many prop type warnings in `SupplierRequisitionPage` for non-program requisition

### To reproduce

1. Create a non-program requisition

### Expected behaviour

No prop type warnings

### Proposed Solution

Fix the prop type warnings

### Version and device info

- App version: 3.1.1 development
- Tablet model: N/A
- OS version: N/A

### Additional context
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/35858975/72573250-e8c6b380-3929-11ea-8257-1762a264d6f0.png">

**Comment by diegoevangelisti** [comment]
I will work on this one after issues #1951 is fixed

**Comment by wlthomson** [comment]
Yo @diegoevangelisti! As discussed, I think leave this issue for now as it's likely to be fixed by #1951 😄 .

**Comment by diegoevangelisti** [comment]
- [x] Navigating to a program supplier requisition without indicators does not cause any prop type warnings to be shown.

**Success** No warnings are popping up
