### ISSUE TITLE
App crash on creating a non-program requisition

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1951]
## Describe the bug

App crashes when creating a non-program requisition.

### To reproduce

1. Create a non-program requisition

### Expected behaviour

No crash

### Proposed Solution

Think it's the state init method

### Version and device info

- App version: 3.1.1 development
- Tablet model:
- OS version:

### Additional context

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/35858975/72573200-b87f1500-3929-11ea-80df-6d194305a805.png">

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Can create a non-indicators program supplier requisition without any errors.
- [x] Can create an indicators program supplier requisition without any errors.

**Success**
