### ISSUE TITLE
SearchBar incorrect placeholders

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1952]
## Describe the bug

Incorrect placeholders in the `SearchBar` on pages:

- `CustomerRequisitions`
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/35858975/72571275-f7aa6780-3923-11ea-8536-c713c4833b96.png">

- `SupplierInvoices`
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/35858975/72571321-232d5200-3924-11ea-94e2-42d76c01572b.png">

- `SupplierInvoice`
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/35858975/72571395-58d23b00-3924-11ea-8a59-bdae38c9d019.png">

Also inconsistencies.. specific column names for most i.e.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/35858975/72577302-20882800-3937-11ea-8efb-d588ac0a9aa8.png">

V

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/35858975/72577311-28e06300-3937-11ea-8264-88d3e6977593.png">

### To reproduce

1. Go to the above pages

### Expected behaviour

Consistency and correctness

### Proposed Solution
N/A

### Version and device info

- App version: 3.2 development
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #1955

**Comment by Rebecca367** [comment]
## Testing
It looks like only "S" in search is capital letter, other words are in small cases. 
All pages look pretty consistent.
success!  
- [x] Placeholder correctly states the columns it filters on and looks good on Customer Invoice Page
- [x] Placeholder correctly states the columns it filters on and looks good on Customer Invoices Page
- [x] Placeholder correctly states the columns it filters on and looks good on Supplier Invoice Page
- [x] Placeholder correctly states the columns it filters on and looks good on Supplier Invoices Page
- [x] Placeholder correctly states the columns it filters on and looks good on Customer Requisition Page
- [x] Placeholder correctly states the columns it filters on and looks good on Customer Requisitions Page
- [x] Placeholder correctly states the columns it filters on and looks good on Supplier Requisition Page
- [x] Placeholder correctly states the columns it filters on and looks good on Supplier Requisitions Page
- [x] Placeholder correctly states the columns it filters on and looks good on Stocktakes Page
- [x] Placeholder correctly states the columns it filters on and looks good on Stocktake edit Page
- [x] Placeholder correctly states the columns it filters on and looks good on Stocktake Manage Page
- [x] Placeholder correctly states the columns it filters on and looks good on Stock Page
