### ISSUE TITLE
Not HIV Programs are showing HIV Indicators

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1954]
## Describe the bug

Not completely sure about this one, but when creating a Requisition from a program that is not an `HIV program`, this is showing Indicators data anyway:

Program settings (See `HIV program` it's unticked)

<img width="690" alt="Screen Shot 2020-01-17 at 11 49 02 AM" src="https://user-images.githubusercontent.com/32987464/72569687-dc3d5d80-391f-11ea-9922-001ce48896e9.png">

And the requisition is showing Indicators anyway:

![Screen Shot 2020-01-17 at 11 49 28 AM](https://user-images.githubusercontent.com/32987464/72569637-bf088f00-391f-11ea-9fb3-6c07af72f9ac.png)

### To reproduce

1. Create a Program requisition that is not an `HIV Program`
2. See that show Indicators

### Expected behaviour

It shouldn't show Indicators (?)

### Version and device info

- App version: 3.2.0-rc3
- Tablet model: AVD 
- OS version: Android 9.1

**Comment by wlthomson** [comment]
Thanks! Just to check, was this program previously an HIV program which you unticked?

**Comment by diegoevangelisti** [comment]
No worries! No, the option `HIV program` was never ticked for that program.

**Comment by wlthomson** [comment]
Hmm, I can't seem to replicate this. Let's leave this open for now, and see if we can replicate again after #1959, #1960 have been merged.

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Supplier requisitions for active HIV programs display HIV indicator values.
- [x] Supplier requisitions for inactive HIV programs do not display HIV indicator values (disable `"Is HIV program"` -> resync -> create a new supplier requisition).

**Success** 
As you mentioned before @wlthomson, it for the second test case, it shows only REGIMEN but not HIV values. (Not even the option to select HIV is available, so it's fine).
