### ISSUE TITLE
Can't toggle between HIV and REGIMEN properly

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1973]
## Describe the bug

After creating a new HIV program requisition, after accessing to Indicators -> Regimen, coming back to Indicators -> HIV doesn't work as expected.

HIV selected and its showing REGIMEN options:

![Screen Shot 2020-01-21 at 3 59 01 PM](https://user-images.githubusercontent.com/32987464/72771819-fbf9bc00-3c66-11ea-8216-a10979244242.png)

REGIMEN selected and its showing HIV options:

![Screen Shot 2020-01-21 at 3 58 41 PM](https://user-images.githubusercontent.com/32987464/72771821-fbf9bc00-3c66-11ea-948d-d2049cfa4493.png)

### To reproduce

1. Create a new HIV program requisition.
2. Click on Indicators.
3. Select Regimen or HIV.

### Expected behaviour

The shown values should be the ones selected (Regimen for Regimen and HIV for HIV).

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v3.2.0-rc3
- Tablet model: ADV
- OS version: Android 9.1

**Comment by wlthomson** [comment]
Closed by #1975.
