### ISSUE TITLE
Wrong placeholder for search bar in Indicators

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1974]
## Describe the bug

Incorrect placeholder for Search bar use to filter Indicators (for HIV and REGIMEN in Supplier and Customer requisitions).

See here an example:

![Screen Shot 2020-01-21 at 4 59 07 PM](https://user-images.githubusercontent.com/32987464/72774404-5b5bca00-3c6f-11ea-98b6-4739577a06f6.png)

### To reproduce

1. Go to Customer Requisitions
2. Open or create a new `HIV program` requisition
3. See error in search bar placeholder (as shown in photo above).

### Expected behaviour

It should say `Search by description or code`

### Proposed Solution

Change the search bar placeholder in each corresponding page. Probably need to add new localization strings to `generalStrings` in English and French. (As done in https://github.com/openmsupply/mobile/pull/1955)

### Version and device info

- App version: v3.2.0-rc3
- Tablet model: AVS
- OS version: Android 9.1

**Comment by wlthomson** [comment]
Fixed by #1980.
