### ISSUE TITLE
3.2.1 Patch release discussion

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1979]
## Release Version

v3.2.1 Patch releases

### SUMMARY

This is a forum for discussing related problems with the 3.2.0 release and planning issues for the  3.2.1 patch.

### ISSUES

- #1990 
- #1992 
- #1994

**Comment by joshxg** [comment]
UPDATE:

- There has been an issue pop up for Myanmar in particular, but could technically effect all users. #1990 

Going to release a patch to fix this issue

**Comment by joshxg** [comment]
Also have noticed the issue in #1994 which I think is serious enough to be in the 3.2.1 patch also. 

#1992 also popped up over night. Have not been able to recreate this, however I think making the code a little more defensive would be a good option.

I think these three issues making it into the patch today is a good target and will definitely make the release better!

Feel free to suggest anything else that should be in the patch :)

**Comment by wlthomson** [comment]
Update:

Just following up from our discussion. Have move indicators issues to 3.2.2 patch discussion (https://github.com/openmsupply/mobile/issues/1995).
