### ISSUE TITLE
Errors can occur while plotting a dashboard report with a wrong data structure

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1982]
## Describe the bug

As mentioned in the docs related with `dashboard_report`, https://docs.msupply.org.nz/playground:2020-01_sworup_dashboard, If no `reportType` parameter is provided, table type is set by default.

Since the `json` structure can be one for pie/line/bar and a different one for table (main difference is the header), in case of assigning i.e. a table type (as default) to a bar chart, can occur in errors while trying to plot a graph in the new dashboard feature. It will result in trying to represent a table but received a bar chart `json` structure instead.

## To Reproduce

Steps to reproduce the behaviour:

1. Create a dashboard report without a `reportType`
2. Make sure the json structure is the correct one for a Bar chart.
3. Run the report as usual
4. Sync in mobile
5. Go to `DashboardPage`
6. Try to open the mentioned report
7. See error

### Expected behaviour

The plotted report should have a proper json structure.

### Proposed Solution

Check that the `reportType` and the json structure matches. It can be done verifying if there's a header in the json (means the real type is table) and that the `reportType` is table. If not, show an error message instead of trying to plot.

### Version and device info

- App version: All
- Tablet model: All
- OS version: All

**Comment by joshxg** [comment]
Closed by #1998
