### ISSUE TITLE
Stocktake edit page no refreshing when editing by batch

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1994]
## Is your feature request related to a problem? Please describe.

When editing a stocktake batch and closing the modal, the underlying stocktake item row is not refreshed.

## Describe the solution you'd like

Should refresh

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #1997

**Comment by diegoevangelisti** [comment]
## Testing

- [x] With a line in a stocktake, open the batch editor and edit the quantity in a/some batches. The changes are reflected when the modal is closed, in the underlying line for those batches.
- [x] Enable some "reasons" -- [mSupply Desktop-Preferences-OptionsTab-Enable/create BOTH a POSITIVE and NEGATIVE reason and sync, two of each] -- and now edit the reason to be a different reason. This change should be reflected the same as above.

**Success**
