### ISSUE TITLE
3.2.2 Patch release discussion

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1995]
###  Release version

Patch release for v3.2.2.

### Summary

This is a forum for discussing related problems with the 3.2.0 release and planning issues for the 3.2.1 patch.

### Issues

- Add remaining indicator localisation (#1991).
- Wrong placeholder for search bar in indicators (#1974).
- Enforce indicator types (#1906).
- Create duplicate indicator values on supplier requisition finalisation (#1938).

**Comment by wlthomson** [comment]
Update:

@joshxg I'm happy to release this now as an indicators patch if you don't have anything to add?

**Comment by joshxg** [comment]
@wlthomson Nothing to add that I know of - do it! 🎉
