### ISSUE TITLE
Add cash register interface for creating new cash transaction

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2004]
## Is your feature request related to a problem? Please describe.

An interface for the cash register which provides functionality for entering cash in/out transactions.

## Describe the solution you'd like

Suggest using a simpler implementation of the modal used when initialising a program-based requisition (without "stepping" functionality).

## Implementation

TODO.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #1917.

**Comment by joshxg** [comment]
Closed by #2005
