### ISSUE TITLE
Add new cash transaction functionality

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2006]
## Is your feature request related to a problem? Please describe.

Add functionality for adding new cash transaction.

## Describe the solution you'd like

Add logic to existing cash register modal UI for creating new cash in and cash out records.

## Implementation

- switch on `cashTransaction.type` in `addCashTransaction`.
- use existing `createCashOut`, `createCashIn` helper methods.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #1917.

**Comment by joshxg** [comment]
Closed by #2018
