### ISSUE TITLE
Add cash transaction name searchbar 

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2045]
## Is your feature request related to a problem? Please describe.

Cash transaction names bottom modal requires a searchbar. 

## Describe the solution you'd like

Add a searchbar to the bottom modal.

## Implementation

Wrap `MultiSelectList` in a bottom modal container, e.g. `BottomMultiSelectList`.

## Describe alternatives you've considered

N/A.

## Additional context

Epic #1917.

**Comment by joshxg** [comment]
Closed by #2072
