### ISSUE TITLE
Cash register should only display finalised transactions

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2047]
## Is your feature request related to a problem? Please describe.

See desktop issue https://github.com/sussol/msupply/issues/5092.

## Describe the solution you'd like

Remove finalised column from cash register.

## Implementation

See above.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by DhanyaHerath** [comment]
Nice! As I said, I think all cash receipts and payments are automatically finalised so the column was redundant anyway (my bad) :)

**Comment by wlthomson** [comment]
Fixed by #2074.
