### ISSUE TITLE
Payment and receipt transaction totals do not sync

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2063]
## Is your feature request related to a problem? Please describe.

See #2062.

## Describe the solution you'd like

Update `outgoingSyncUtils` with cases for `Payment` and `Receipt` transaction types.

## Implementation

See above.

## Describe alternatives you've considered

An alternative is to generate placeholder `TransactionItem` and `TransactionBatch` records associated with the payment record, but this is not done in desktop, so consistency seems like the best way to go here.

## Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #2064
