### ISSUE TITLE
Auto-log out after some time frame

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2069]
## Is your feature request related to a problem? Please describe.

From @craigdrown 

IC Requirement: Automatically log a user out after a time frame of X for security reasons. Data should not be lost which was being worked on.

## Describe the solution you'd like

Log the user out after X time

## Implementation

Could use store custom data `logoutTimeoutPeriodInSecondsOrMinutes` to set the period..

- Use [AppState](https://facebook.github.io/react-native/docs/appstate#addeventlistener) to hook into the app going into the background - log the user out if so. Android would go to sleep after X amount of time, putting the app into the background (I THINK, UNTESTED)
- Use a package like https://www.npmjs.com/package/redux-idle-monitor to track activity, have a schedule that is reset each time an event happens.
- Use the above package but combine it with the current user authentication scheduler (tries to re-auth against the server every X minutes, or the local DB if no connection available) - I think not good

## Describe alternatives you've considered

Not having this in the dispensary/IC branch 🤣 

## Additional context

@wlthomson @mark-prins @Chris-Petty thoughts?

**Comment by Chris-Petty** [comment]
- Option 1 with AppState sounds clean, if only bit limited in control. 
- Option 2 without an external package sounds like: root redux state of "lastActionTime". Update value to now in reducer for all actions (can just put it before/after the switch statement?). Have a function at startup that checks it every [interval] forever? That NPM package doesn't look supported/popular so I'm apprehensive given I don't imagine being too hard to do in house.
- Option 3 ends up being what I described above but not in redux?

**Comment by joshxg** [comment]
@Chris-Petty I agree

Only point regarding the redux package which I missed was that the plan would definitely be to make an internal middleware. However with the extremely limited time.. probably easier to just use that for UAT

**Comment by Chris-Petty** [comment]
Yea just do the prompt thing for UAT. Does UAT specify central control? If not just hardcode a `timeoutInterval`?

**Comment by joshxg** [comment]
oh yup nice

**Comment by joshxg** [comment]
Closed by #2079
