### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2071]
## Is your feature request related to a problem? Please describe.

Some strings are not translated into french

## Describe the solution you'd like

All strings being translated into french

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

@alainsussol please help sir

There is a CSV here with all translations which are missing!

We need to import these new translations as a `.tsv` 

Note: the last column needs to be filled for each missing value.
Note: The `{nextLine}` placeholder replaces `\n` 

[fr.csv.zip](https://github.com/openmsupply/mobile/files/4136670/fr.csv.zip)

**Comment by diegoevangelisti** [comment]
@alainsussol 
In case you need more information about the new localization import/export feature: https://github.com/openmsupply/mobile/wiki/Scripts

**Comment by alainsussol** [comment]
@diegoevangelisti Thanks !!!

**Comment by joshxg** [comment]
Closed by #2082
