### ISSUE TITLE
Unable to run develop

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2075]
## Describe the bug

<img width="817" alt="image" src="https://user-images.githubusercontent.com/35858975/73510382-c4e59080-4446-11ea-9be4-55a70876151b.png">

When running in develop - but not master. Think the only PR this couldv'e come from is: https://github.com/openmsupply/mobile/pull/1998 

### To reproduce

Try run develop

### Expected behaviour

N/A

### Proposed Solution

N/A

### Version and device info

N/A

### Additional context

N/A

**Comment by wlthomson** [comment]
See hotfix 6e8136fab35bc8c94b46b56e4b0e1d75db60db5a. Should be fixed by merging `master` back into `develop`.

**Comment by joshxg** [comment]
Closed by #2076
