### ISSUE TITLE
Add sorting functionality to cash register page

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2077]
## Is your feature request related to a problem? Please describe.

The cash register page does not currently sort on click.

## Describe the solution you'd like

Add functionality for sorting by invoice number.

## Implementation

Most of the logic is there, just need to pass through a `onSort` prop for `renderHeader`.

## Describe alternatives you've considered

N/A.

## Additional context

See #2074.

**Comment by joshxg** [comment]
Closed by #2131
