### ISSUE TITLE
Cash register reason column type is incorrect

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2078]
## Is your feature request related to a problem? Please describe.

The cash register reason column displays an icon which suggests the cell is editable on click (it isn't). 

## Describe the solution you'd like

Use a string type column, which makes it clearer that existing rows are not editable.

## Implementation

Just requires adding a new column type to `getColumns`.

## Describe alternatives you've considered

N/A.

## Additional context

See #2074.

**Comment by joshxg** [comment]
Closed by #2130
