### ISSUE TITLE
Add cash register search bar

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2096]
## Is your feature request related to a problem? Please describe.

Add search bar to cash register.

## Describe the solution you'd like

Add a search bar component for filtering transactions by name.

## Implementation

Nothing tricky, just a case of making a few tweaks to an existing page search bar component.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #1917.

**Comment by joshxg** [comment]
Closed by #2159
