### ISSUE TITLE
Build 7: Mobile sync error is not very informative!

### ISSUE THREAD

**Issue by adrianwb** [openmsupply/mobile#210]
All you can tell is that something went wrong in the first batch of 20 sync records in the outgoing queue for the store. I'd suggest one or both of:
- if there's a sync error, reduce the requested number of records to 1 temporarily -> then at least we can pinpoint the offender
- add the ID and/or sequence of the probelm sync record to the Realm window

**Comment by joshxg** [comment]
New issue has been opened, closely related. Will use that and close this one #1027
