### ISSUE TITLE
Update cash register to use new payment types

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2107]
## Is your feature request related to a problem? Please describe.

See desktop issue https://github.com/sussol/msupply/issues/5346.

## Describe the solution you'd like

- Update incoming sync to handle new payment types table.
- Update cash register modal to use payment options. 

## Implementation

Simplest option is to use existing `Options` table and add a `UIDatabase` case. Other option is to adding a new payment types table. @joshxg @Chris-Petty @andreievg @DhanyaHerath @mark-prins @diegoevangelisti Thoughts?

## Describe alternatives you've considered

N/A.

## Additional context

See epic #1917.

**Comment by wlthomson** [comment]
Putting on backlog for now. @DhanyaHerath feel free to update.

**Comment by joshxg** [comment]
Most likely we will be doing this. Waiting for desktop implementation before moving forward though

**Comment by wlthomson** [comment]
Fixed by #2107.
