### ISSUE TITLE
Quick UI review of dispensing: select prescriber

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2124]
## Is your feature request related to a problem? Please describe.

A simple refresh of the select prescriber screen

![Screenshot_1580784532](https://user-images.githubusercontent.com/9192912/73709641-7e55a600-4766-11ea-86b9-f398fbc6ff19.png)

## Describe the solution you'd like

Mainly a little padding. perhaps also a little uniformity of font sizes.

**Comment by joshxg** [comment]
Closed by #2125
