### ISSUE TITLE
Additional sortable cash register columns

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2133]
## Is your feature request related to a problem? Please describe.

Cash register is only sortable by invoice number, should be sortable by a few more columns
Also the type column doesn't seem needed

## Describe the solution you'd like

Sortable by at least confirm date could also add total amount, reason sorting

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #2179.
