### ISSUE TITLE
Dispensary UI tweak - select items

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2135]
## Is your feature request related to a problem? Please describe.

A quick UI refresh of the *Select items* page
![Screenshot_1580862233](https://user-images.githubusercontent.com/9192912/73799444-e6fe5a80-481a-11ea-9ae5-192f22626aa2.png)

## Describe the solution you'd like

Add some padding and tweak styles

**Comment by mark-prins** [comment]
also looking at the prescription confirmation screen:

![Screenshot_1580869977](https://user-images.githubusercontent.com/9192912/73806445-65182c80-482e-11ea-9b87-ecd4ac09247b.png)

**Comment by joshxg** [comment]
Closed by #2137
