### ISSUE TITLE
Prescription: specifying category throw error

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2138]
## Describe the bug

From the PrescriptionConfirmation screen - selecting a category throws an error:

![Screenshot_1580871066](https://user-images.githubusercontent.com/9192912/73807080-1a97af80-4830-11ea-9127-e080fb285859.png)

### To reproduce

Steps to reproduce the behaviour:

1. Create a prescription
2. Enter details, add items and proceed to the confirmation screen
3. Select a category

### Expected behaviour

Should update the transaction category

**Comment by joshxg** [comment]
Closed by #2146
