### ISSUE TITLE
Supplier column on StocktakeBatchModal

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2142]
## Is your feature request related to a problem? Please describe.

When creating a new stocktake batch, you cannot assign a supplier. 

## Describe the solution you'd like

A column to select a supplier

## Implementation

@craigdrown @mark-prins (sorry, thoughts?)

- Not sure if this should be under any sort of customisation. I am thinking it shouldn't
- Maybe default to the mobiles  stores supplying store?
- Should no supplier be allowed? Doesn't seem to make sense
- Should possible suppliers be only the stores supplying store + external suppliers?

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
After thinking some more, I think:

- No customisation
- default to the `inventory_adjustment` name
- no supplier shouldn't be allowed - can choose invad if you don't know
- possibly suppliers should be any supplier + invad 

Additionally will need to remove returning batches to the invad name through supplier credits

**Comment by mark-prins** [comment]
I'm confused - this is when creating a line on a stocktake? which wouldn't normally allow or require a supplier. The need for a supplier is driven by the ability to return stock, is that the issue here?

**Comment by joshxg** [comment]
@mark-prins 

Yeah 

- on desktop you would be able to do a supplier credit for any batch to any name 
- on mobile we are only bringing up a modal which we enter a quantity in, which will return it to that supplier
- So basically require a way of adding a supplier to a batch which was created (through a stocktake)

**Comment by mark-prins** [comment]
that all sounds good then - I agree with the

- No customisation
- default to the `inventory_adjustment` name
- no supplier shouldn't be allowed - can choose invad if you don't know
- possibly suppliers should be any supplier + invad

**Comment by joshxg** [comment]
Closed by #2147
