### ISSUE TITLE
Cash transactions not using the specific transaction cash reasons

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2162]
## Describe the bug

There is a specific type of reason which should be used for cash in reasons

<img width="287" alt="image" src="https://user-images.githubusercontent.com/35858975/73980990-2b623580-4996-11ea-806a-30b5f1fc15ce.png">

### To reproduce

Dispensary development

### Expected behaviour

As above

### Proposed Solution

Create a `UIDatabase` case for this specific type and use that rather than `Options`

### Version and device info

Dispensary development

### Additional context

Dispensary development

**Comment by wlthomson** [comment]
Fixed by #2162.
