### ISSUE TITLE
Cancelling a prescript throws error

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2164]
## Describe the bug

After pressing **Cancel** from the prescription confirmation screen, this shows up:

![Screenshot_1581033347](https://user-images.githubusercontent.com/9192912/73989044-5bff9a80-49a9-11ea-8f15-616bafaf6eb5.png)

### To reproduce

1. Go to *Dispensary*
2. Create a prescription, go all the way to the confirmation
3. Press **Cancel**

**Comment by joshxg** [comment]
Closed by #2168
