### ISSUE TITLE
App crushes when clicking the button 'New Prescriber' on the Dispensary module

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2189]
## Describe the bug

![Screen Shot 2020-02-10 at 3 57 06 PM](https://user-images.githubusercontent.com/16461988/74117896-0e3f9800-4c1e-11ea-814a-8530dd673762.png)

![Screen Shot 2020-02-10 at 3 57 14 PM](https://user-images.githubusercontent.com/16461988/74117895-0b44a780-4c1e-11ea-99c8-797abf0d021d.png)

### To reproduce

1. Go to Dispensary
2. Click on the arrow icon on the 'DISPENSE' column in one of the patients
3. Then click on 'New prescriber'
4. The app crashes

### Expected behaviour

Continue creating the prescriber o/

### Version and device info

- App version: 4.0.0-RC1
- Tablet model: Genymotion
- OS version: Android 4.4.4

### Additional context

The 'New prescriber' button on the 'Prescribers' also crashes the app.
There was no prescribers in the list.

**Comment by wlthomson** [comment]
Tested on latest feature branch and can't replicate.

@joshxg You OK with closing this? Can reopen if required.

**Comment by diegoevangelisti** [comment]
> Tested on latest feature branch and can't replicate. Possible that may be related to Android version as `4.4.4` is right at the bottom of what is usually supported?
> 
> @joshxg You OK with closing this? Can reopen if required.

I can't replicate with AVD Android 9.0 but just tested using an emulator with Android 4.4 and it crushes when trying to add a New Patient and a New Prescriber as well.
Example:
![crushing](https://user-images.githubusercontent.com/32987464/74121650-46020c00-4c2d-11ea-820f-06982056a6b0.gif)

**Comment by joshxg** [comment]
Who knows how many other bugs there are on that android version!

Looks like we should be updating https://msupply.org.nz/mobile which lists the minimum android version as `4.4.4`.

Before doing that I suppose we need to find out if there are any users on `4.4.4`!

**Comment by nmadruga** [comment]
Confirmed the problem was only on Android 4.4.4. Tested on Android 5.1 and there is no problem. So we will be changing the minimum required Android to 5.1 on the website.

We also will have to check current mSupply mobile users on SureMDM to upgrade their Android before we upgrade them to mobile v4.00

**Comment by joshxg** [comment]
turns out this is a react-native bug with `4.4.4`. https://github.com/facebook/react-native/issues/24000

Can't pass a `null` backgroundColor

Reopening

**Comment by joshxg** [comment]
Closed by #2305
