### ISSUE TITLE
Sort by INVOICE NUMBER doesn't work properly on CashRegisterPage

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2191]
## Describe the bug

This is happening on the new `CashRegisterPage`, when adding a new payment (cash in or cash out), the table can't be sorted as expected, but this is working ok when navigation back to menu page and returning to `CashRegisterPage`.

Example:

![Screen Shot 2020-02-10 at 3 05 57 PM](https://user-images.githubusercontent.com/32987464/74116176-3bd51300-4c17-11ea-844e-8fc3f7f0cf7a.png)

### To reproduce

1. Go to `cashRegisterPage`
2. Click on 'New Transaction' and create a Cash Out or Cash In
3. Try to sort by `INVOICE NUMBER`

### Expected behaviour

It should sort right after the new transaction is added to the table.

### Version and device info

- App version: v4.0.0-rc1
- Tablet model: AVD
- OS version: Android 9.0

### Additional context

Happened during testing #2182

**Comment by joshxg** [comment]
Closed by #2192
