### ISSUE TITLE
Fix indicator attribute incoming sync

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2211]
## Is your feature request related to a problem? Please describe.

Indicator attribute incoming sync logic does not exist (most likely a bad merge).

## Describe the solution you'd like

Add indicator attribute incoming sync logic.

## Implementation

See above.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #2212
