### ISSUE TITLE
Incorrect customer requisition indicator behaviour

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2213]
## Describe the bug

Customer requisition indicators are not filtering correctly. This can result in incorrect values being displayed or the app crashing.

### To reproduce

1. Open a customer requisition without indicators.
2. See error.

### Expected behaviour

Correct values, no crashing.

### Version and device info

- App version: `4.0.0-rc2`
- Tablet model: Android emulator.
- OS version: API 28.

### Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #2214
