### ISSUE TITLE
App crash - return to supplier

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2218]
## Describe the bug

On confirmation of a supplier return the app crashes

### To reproduce

Raised during UAT - the tablet demoing is syncing to demoivory.msupply.org using the zambakro store.

1. Go to a finalised supplier invoice
2. Return
3. Enter quantities and click **Confirm**
4. App closes

### Version and device info

- App version: 4.0.0-RC4
- Tablet model: Lenovo Tab 4 10
- OS version: Android

**Comment by mark-prins** [comment]
Tested in emulator and couldn't reproduce.

**Comment by joshxg** [comment]
Have installed on a tab4 10 - can't repoduce! :(

**Comment by joshxg** [comment]
Clsoed by #2235

**Comment by mark-prins** [comment]
Tested on the originating tablet after upgrading and cannot reproduce

**Comment by joshxg** [comment]
![phew](https://user-images.githubusercontent.com/35858975/74321622-72fa1e80-4de7-11ea-8278-10eb32217125.gif)

**Comment by mark-prins** [comment]
Have narrowed down the use case ( it is still an issue as demonstrated in UAT )

Return all stock on all items on supplier invoice and the app crashes.

**Comment by joshxg** [comment]
Closed by #2279
