### ISSUE TITLE
App hangs on confirming a prescription

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2219]
## Describe the bug

Press **Confirm** at the end of the prescription process.
The 'wait' window comes up, and does not go away.
Observed during mobile UAT running on the zambakro store from *demoivory.msupply.org*

Running in an emulator the following error comes up:
<img width="351" alt="Screen Shot 2020-02-11 at 3 51 11 PM" src="https://user-images.githubusercontent.com/9192912/74253321-d5b7c100-4ce6-11ea-9af8-d595fc71947d.png">

### To reproduce

1. Create prescription
2. Add an item which has a price
3. Click **Confirm** from the summary screen

### Version and device info

- App version: 4.0.0-RC4

**Comment by joshxg** [comment]
Clsoed by #2231
