### ISSUE TITLE
Quantity supplied/Quantity received columns for SI

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2222]
## Is your feature request related to a problem? Please describe.

IC Want a quantity supplied and a quantity received column on an SI

## Describe the solution you'd like

As above

## Implementation

Use the `sentQuantity` field on a `[trans_line]`

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
@craigdrown @mark-prins 

CSN

(Craig "The Bossman" Drown said no)

**Comment by craigdrown** [comment]
@mark-prins  @joshxg this (to me) counts as clutter- once we implement the "details panel" for a trans_line it could live there.
The information would be available from a dashboard or from central server as sent = the quantity on the customer invoice in the supplying store (showing in mobile is duplicating this info)
