### ISSUE TITLE
Total price column for SI

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2224]
## Is your feature request related to a problem? Please describe.

SI Total price column

## Describe the solution you'd like

SI Total price column

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
@craigdrown @mark-prins 

Closing this?

**Comment by craigdrown** [comment]
@joshxg  wait for discussion with @mark-prins  thx

**Comment by mark-prins** [comment]
Yes, closing this - as an out of scope item.
