### ISSUE TITLE
Stocktake total price column

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2225]
## Is your feature request related to a problem? Please describe.

IC Want: Add a column for Value / total cost - quantity x cost price

## Describe the solution you'd like

Option 1:

Add it for the `StocktakeItem` Line, for all batches of that item:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/35858975/74276948-8ec7db00-4d7b-11ea-975c-091732b0a737.png">

Option 2:

Add it at the batch level...

<img width="861" alt="image" src="https://user-images.githubusercontent.com/35858975/74276997-a30bd800-4d7b-11ea-9801-f6a37289f6fb.png">

Option 3:

![confused](https://user-images.githubusercontent.com/35858975/74277105-cd5d9580-4d7b-11ea-9d8f-f7d0e957c64f.gif)

## Implementation

- Have this column only show when `usingPaymentsModule`
- Do one of the above two options

## Describe alternatives you've considered

:)

## Additional context

N/A

**Comment by joshxg** [comment]
@craigdrown @mark-prins 

Closing this?

**Comment by craigdrown** [comment]
@joshxg - need to go through with @mark-prins  to make sure (after he's back). I think we have to say "If you want it done, someone has to pay, and it will not be available until we implement the detail line panel where all your interface polluting ideas have to go"

**Comment by joshxg** [comment]
@craigdrown Thanks.

What do we think the chances of the `interface pollution panel` are?

Hopefully release dispensing soon and jump onto vaccines asap so just trying to plan worst-case

**Comment by mark-prins** [comment]
I think close it, as not useful for all mobile users.

**Comment by Rebecca367** [comment]
I think that I just move these closed issues to done.
