### ISSUE TITLE
Cash register balance should only include cash transaction totals

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2232]
## Is your feature request related to a problem? Please describe.

The cash register balance currently does not filter transactions by payment type. This differs from desktop behaviour which only sums transactions with cash payment types.

## Describe the solution you'd like

Filter transactions by payment type before summing totals.

## Implementation

See above.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #2238
