### ISSUE TITLE
Program Requisition use SOH at the end date of the period

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#2233]
## Describe the bug

When creating requisition should use SOH at the end date of chosen period rather then current SOH (IC requirement, but can be used as generic logic for program requisitions)

### To reproduce

Make program requisition for historic period, use IC mobile UIAT data file

### Expected behaviour

described above

### Proposed Solution

Use reverse ledger, can check SOH on date in desktop, item -> ledger -> print -> stock movement

### Version and device info

4.0.0-rc4

### Additional context

Similar was done for AMC

**Comment by joshxg** [comment]
Closed by #2233
