### ISSUE TITLE
Can only enter one value at a time in the 'Requested Quantity' field of a Supplier Requisition

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2234]
## Describe the bug

On a supplier requisition, I can only enter one number into the 'Requested Quantity' field at a time. If I start to type the next number, it goes directly to the Reasons window. 

For example, if I try to type in '12', it will go to this window after I type in '1'

![image](https://user-images.githubusercontent.com/29744386/74291426-b75ecd80-4d99-11ea-9324-402a4b7200fe.png)

and then I have to type in the 2 after. 

![image](https://user-images.githubusercontent.com/29744386/74291492-dd846d80-4d99-11ea-976d-84ec55d46956.png)

### To reproduce

1. Go to Supplier Requisitions and create a new one
2. Enter a value into the 'Requested Quantity' field
3. See error

### Expected behaviour

The reasons window should only come up when you lose focus of the cell ideally

### Version and device info

- App version: 4.0.0 RC4
- Tablet model: 
- OS version:

**Comment by bijaySussol** [comment]
@joshxg : 

I have seen this too - Good catch @DhanyaHerath now I am suffering from this a little though.

**Comment by DhanyaHerath** [comment]
Duplicate of https://github.com/openmsupply/mobile/issues/2940
