### ISSUE TITLE
When you add your first prescriber, it does not appear in the list

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2237]
## Describe the bug

When you add your first prescriber, it does not appear in the list immediately. I had to search for it (it didn't show in the search) and then deleted my search term and it appeared. 

I have no screenshots because I can't delete prescribers and reproduce, sorry! 

It seems to work fine after the first one is added, ie. when adding the 2nd prescriber. 

### To reproduce

1. On a datafile with no prescribers, select a patient and click 'Dispense'
2. On the window with an empty prescriber listbox, click 'New Prescriber'
3. Add a prescriber and return to the listbox window - it will still be empty

### Expected behaviour

I think it should appear in the listbox when added 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:4.0.0 RC4
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
Closed by #2328
