### ISSUE TITLE
Small typo on dashboard report: 'This month transactions'

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2239]
## Describe the bug

'Purchased orders' should be 'Purchase orders', unless that was on purpose?

![Screen Shot 2020-02-12 at 2 32 50 PM](https://user-images.githubusercontent.com/29744386/74295059-bda67700-4da4-11ea-860a-a66aecea004e.png)
### To reproduce

1. Go to Dashboards
2. See error

### Expected behaviour

As above

### Proposed Solution

Change string?

### Version and device info

- App version: 4.0.0 RC4
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
All the data here is from desktop - so this will need to be a desktop issue :)

**Comment by DhanyaHerath** [comment]
@joshxg Ah right! Cool thanks, closing
