### ISSUE TITLE
Update cash register to use page info component

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2244]
## Is your feature request related to a problem? Please describe.

See above.

## Describe the solution you'd like

Display cash register balance with `PageInfo` component .

## Implementation

Add a `selectCashRegisterInfoColumns` selector, pass columns directly as props to `CashRegisterPage`.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.
**Add any other context or screenshots about the feature request here.**

**Comment by joshxg** [comment]
Closed by #2245
