### ISSUE TITLE
The input for 'directions' is not showind on summary for new Prescription

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2246]
## Describe the bug

The directions don't show on the 3rd step of creating a new Prescription
![Screen Shot 2020-02-12 at 3 38 48 PM](https://user-images.githubusercontent.com/16461988/74298253-11698e00-4dae-11ea-973f-0725fdecb7c6.png)
![Screen Shot 2020-02-12 at 3 38 40 PM](https://user-images.githubusercontent.com/16461988/74298261-14fd1500-4dae-11ea-9cf7-8dbe194864a5.png)

### To reproduce

1. Go to Dispensary
2. Click on any Patient, column dispense
3. Click on any Prescriber (or create a New Prescriber and select it)
4. Add 2 items
5. Add quantity
6. Add directions to one
7. Click next and see that it's not showing on the Summary

### Expected behaviour

Show the directions on the summary window,

### Version and device info

- App version: 4.0.0-RC5
- Tablet model: Emulator
- OS version: Android 5.1

**Comment by joshxg** [comment]
Closed by #2263
