### ISSUE TITLE
App closes itself after clicking on sorting batch name column on Available Credits for the item modal on current stockpage  

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2247]
## Describe the bug

Msupply stopped after clicking on batch name arrow on Available Credit for the item on current stockpage. 

### To reproduce

1. Go to 'current stockpage'
2. Click on 'any displayed item'
3. Click on Return column
4. Click on Batch Name column on "Available Credit for the item Modal that you just clicked in 

### Expected behaviour
 App should display batch name as expected without msupply been stopped

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 4.0.0-rc1
- Tablet model: samsung
- OS version: ios

**Comment by joshxg** [comment]
closed by #2254
