### ISSUE TITLE
Search query box in Cash Register is case-sensitive

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/mobile#2250]
## Describe the bug

When typing in the search bar on the Cash Register page, the typed query must match the text case in order to show results. 

### To reproduce

1. Go to "Cash Register"
2. Start typing in the Search bar. Type lower-case.
3. Items that should match, but are in upper-case (lots in Ivory Coast data), won't show up.
4. Now type the same search query in upper case. The matching results remain.

### Expected behaviour

Filtered results should not be dependent on the case of the typed search string.

### Proposed Solution

Other search filters in the mobile app work as expected (eg. Dispensary -> Patients), so do whatever they're doing.

### Version and device info

- App version: 4.0.0 RC5
- Tablet model: Lenovo TB-X304L
- OS version: Android 7.1.1

### Additional context

Noted during testing [here](https://github.com/openmsupply/mobile/issues/2182#issuecomment-584972579).

**Comment by joshxg** [comment]
Closed by #2259
