### ISSUE TITLE
Column sorting in Dispensary defaults to Descending (rather than ascending)

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/mobile#2251]
## Describe the bug

Within the Dispensary module, all column sorting operations (clicking on headers) first sort in _Descending_ order. This makes sense for Dates where you want the most recent to show first, but is looks weird for Names and Numbers.

### To reproduce

1. Go to Dispensary
2. Click on a column header (e.g. Last Name)
3. Note that the column is sorted in descending order (ie. names starting with "Z" are at the top).

### Expected behaviour

Columns with names/numbers/strings (and maybe even DOB) should show in Ascending order first, then switch to Descending if header is clicked again.

### Version and device info

- App version: 4.0.0 RC5
- Tablet model: Lenovo TB-X304L
- OS version: Android 7.1.1

### Additional context

Note that default column sorting behaviour works as expected elsewhere in the app.

Discovered during testing [here](https://github.com/openmsupply/mobile/issues/2106#issuecomment-585002332).

**Comment by joshxg** [comment]
Closed by #2260
