### ISSUE TITLE
New Patient/Prescriber form -> DOB field doesn't alert when adding a future date

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/mobile#2252]
## Describe the bug

There is a warning message "Must be a date before today, in the format DD/MM/YYY" when incorrectly entering a DOB.  However, it only shows up if entering a date via text input -- if you select a future date from the Date Picker, no warning is given.

### To reproduce

1. Go to Dispensary
2. Select "New patient"
3. Select the Date Picker in the Date of Birth field.
4. Select a future date.
5. No Invalid message appears below the date entry.
6. Focus on the date.
7. Re-type the same date using the keyboard.
8. Now the warning appears.

### Expected behaviour

Future dates chosen from the Date Picker should give the same Invalid message as when typed in from the keyboard.

### Version and device info

- App version: 4.0.0 RC5
- Tablet model: Lenovo TB-X304L
- OS version: Android 7.1.1

### Additional context

Picked up during testing [here](https://github.com/openmsupply/mobile/issues/2106#issuecomment-585014049).

**Comment by joshxg** [comment]
Closed by #2327
