### ISSUE TITLE
Insurance discount is applied to prescription payments before it's selected

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2253]
## Describe the bug
When I make a prescription, it looks like the last insurance policy I made is applied to the payment price, before I select a policy. 

This is what it looked like when I had one policy created - note that the prescription value is actually $4 but has been set to $3 because a 25% insurance policy was applied. 

![PrescriptionInsurance](https://user-images.githubusercontent.com/29744386/74301899-72e32a00-4db9-11ea-9afa-6851c3bf7bdf.png)

When I have more than one insurance policy created, it selects the last one made and does show it in the DDL this time: 

![image](https://user-images.githubusercontent.com/29744386/74302034-e5540a00-4db9-11ea-9fa4-09102dafd0bd.png)

### To reproduce

1. Create a prescription for a patient with no insurance policies, add a policy. 
2. Create a new prescription for the same patient, this time make sure that the items you're adding has a value 
3. Check the Payment Amount field and the Subtotal

### Expected behaviour

It shouldn't select an insurance policy for you I think? And if it does, it should at least show in the dropdown list

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:4.0.0 RC5
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
Closed by #2258
