### ISSUE TITLE
Look back denominator for program based AMC to be aligned with desktop

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#2267]
## Describe the bug

Not so much of a bug but alignment issue.

We've used denominator = actual number of days for daily usage calculation, which seems accurate but doesn't quite align with how desktop does it, and would be hard to verify again item ledger. Should just use lookBackMonths * 30 (since daily usage is displayed as AMC in requisition, which also uses 30)

### Other info

Sorry, don't really have time to write out more detailed issue

**Comment by joshxg** [comment]
Closed by #2268
