### ISSUE TITLE
Sync: While syncing from tablet got error

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2273]
## Describe the bug
As per client email in below link, while syncing the stock take got an error.
https://support.msupply.org.nz/cerb6/profiles/ticket/MB-6183-WP/conversation
### To reproduce
For now we are unable to reproduce if we get any clue then we will update.

### Expected behaviour

Must work properly

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:3.2.1
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
Closed by #2321
