### ISSUE TITLE
Unable to see suppliers

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2278]
## Describe the bug

Observed during CI mobile UAT - not by the client though, it's not a blocker to sign-off.

Created some new suppliers on the sync site and synced. They showed up on the tablet fine - but the existing suppliers were no longer available.

### To reproduce

Steps to reproduce the behaviour:

1. Create a new supplier, assign visibility to the mobile store.
2. sync
3. Create a supplier invoice and observe the suppliers available. Only the new supplier shows

### Version and device info

- App version: 4.0.00-RC7

**Comment by joshxg** [comment]
https://github.com/sussol/msupply/issues/5433 possibly related??

**Comment by mark-prins** [comment]
yeah, this one made me think of that one too! It's the reverse scenario - the new supplier shows and the old doesn't. And I wasn't sure if this was mobile or desktop that was at fault. I'm really suspecting desktop though.

**Comment by joshxg** [comment]
Attempt to recreate:

1. Started with no external suppliers.
2. Created an external supplier, added visibility and synced to mobile. All ok
3. Created another, added visibility and synced to mobile. All ok
4. At this point, had two suppliers to choose from.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/35858975/75070797-dce99500-5558-11ea-82e5-2a29602383c0.png">

5. Uninstalled the app.
6. Reinitialized.
7. Added a third external supplier

<img width="704" alt="image" src="https://user-images.githubusercontent.com/35858975/75071181-b8da8380-5559-11ea-8a80-e0d355f13930.png">


Must be something else going on here! :(

**Comment by mark-prins** [comment]
Ok - I'll have another try to recreate using the CI demo server and hopefully can close the issue

**Comment by mark-prins** [comment]
It's still a little broken when using the ZAMBAKRO store on _demoivory.msupply.org_

This is what I get when creating a new supplier invoice:

![Screenshot_2020-02-25-16-03-11-274](https://user-images.githubusercontent.com/9192912/75216735-dfb6e500-57f9-11ea-9acd-dd89b72d280a.jpeg)

and this is the list of suppliers when logged into that store on the server:

![Screen Shot 2020-02-25 at 6 03 26 PM](https://user-images.githubusercontent.com/9192912/75216780-0248fe00-57fa-11ea-941f-f0655b5413d9.png)

The `District Sanitaire de Yamoussoukro` used to show up, before creating the `Banque` and `Transport` suppliers.

**Comment by joshxg** [comment]
We can only make SI's to external suppliers in mobile - no SI's can be created for internal stores directly on mobile - only SI's which are synced are for internal suppliers.

Could we get lucky and it could be a mistake that you were able to create an SI to `district..`? Maybe it was creating an CI and it showed up or something? Cause it is 'desired behaviour' that `district...` isn't showing up for a manually created SI

**Comment by mark-prins** [comment]
ah... light bulb! yes - that'd be it. I thought there was an aspect of the suppliers that was causing it, but forgot about the external thing and was thrown by the District showing up initially. 
Thanks!
