### ISSUE TITLE
Item price missing on the card of the 2nd to create Prescription

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2285]
## Describe the bug
Before adding item quantity: Not showing the price
<img width="757" alt="Screen Shot 2020-02-13 at 10 26 58 AM" src="https://user-images.githubusercontent.com/16461988/74379503-c6528800-4e4c-11ea-8670-1142317dc084.png">

After adding item quantity: Showing the item price
<img width="928" alt="Screen Shot 2020-02-13 at 10 27 19 AM" src="https://user-images.githubusercontent.com/16461988/74379495-c2266a80-4e4c-11ea-9583-7c8f4a01b398.png">

### To reproduce

1. Go to Dispensary
2. Click on any Patient, column dispense
3. Click on any Prescriber (or create a New Prescriber and select it)
4. Add item that has price associated (this needs to be set in mSupply server before injitial sync)
5. Check that the item shows without price
6. Add quantity to the item - now you can see the price!

### Expected behaviour

Show the price on items added to the card

### Version and device info

App version: 4.0.0-RC5
Tablet model: Emulator
OS version: Android 5.1

**Comment by nmadruga** [comment]
Oh! I think this is not a real bug... Just not very clear that the `price` in there is the amount x sell_price. So while there is no quantity selected it shows 0. I don't know. Maybe it would be good to also show unity price here. Or only show unit price and just the total on the summary.

@joshxg @mark-prins @wlthomson @craigdrown What do you think about?

**Comment by joshxg** [comment]
@nmadruga originally I had just the unit price and then was told to change it to sell * quantity ..

🤷‍♂

**Comment by mark-prins** [comment]
I've been caught by this too! so I think it is a valid usability issue.
perhaps if it was just showing unit price it would be clearer 🤷‍♂ (sorry)

Suggestions:

1. show - rather than 0
2. show the unit price as well
3. hide the price row until the quantity is > 0

side note: the term 'price' is, for me, associated with a per unit value - and the price*quantity would be more usefully called cost or total cost

**Comment by joshxg** [comment]
cool!

Will just add both .. kind of think the unit price would be good in the table .. but no room! 

I'll just add both 🤣

**Comment by joshxg** [comment]
oh - I forgot one of the reasons for this!

The 'line' or 'row' could be over multiple batches, each having a different price. So if you are to show a unit price, do you put the maximum price? the first batches price? an average? A range? 🤷‍♂

**Comment by nmadruga** [comment]
I understand that with different prices per batch it would be hard to show a unique price, or even change the price based on the `next batch to use` could be confusing for the users. But showing price == 0 before adding quantities could be also misleading. 
What do you thing about just it to `total price` for now? Maybe in the future if needed - based on usability - we could show different batches details on a collapsable table or something like that.

**Comment by joshxg** [comment]
- so ya think just change the label to be `total price` or `total cost` (I think price is more appropriate in this case, personally)? I think that's a good idea.
- As for choosing batches - at the moment if we 'spill' over onto multiple batches, the last page in the prescription will show each batch and how much each batch cost, but there is no way to choose a batch. From my understanding this is what most people want from mobile - FEFO - but I agree, having an 'advanced' feature is a really good idea!

**Comment by joshxg** [comment]
Closed by #2374
