### ISSUE TITLE
Payment type not correctly sent to mSupply on SYNC

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2288]
## Describe the bug

The Payment type is missing from the Cash payment that was done on a mobile store using `New Prescription` with a payment type selected. The prescription was Finalised and synced. 

## To Reproduce

Steps to reproduce the behaviour:

On mSupply MOBILE:
1. Go to Dispensary
2. Click on any Patient, column dispense
3. Click on any Prescriber (or create a New Prescriber and select it)
4. Add item that has price associated (this needs to be set in mSupply server before injitial sync) and some quantity to it
5. Go to the next step and select a 'Payment type' i.e.: Espèce
6. Click confirm
7. Click on the SYNC enabled
8. Click on Manual SYNC. Wait until is finished

On mSupply DESKTOP:
1. Log to the same store as used in the mSupply mobile
2. Go to Customers > Cash receipts
3. Double-click on the line for the same customer that the Prescription was created for
4. Check that the Payment type is showing: `

## Expected behaviour

Show the same Payment Type that was selected on the Created Prescription on mSupply mobile 

## Screenshots

<img width="768" alt="Screen Shot 2020-02-13 at 10 51 57 AM" src="https://user-images.githubusercontent.com/16461988/74383673-8b545280-4e54-11ea-9088-46605c5c1dad.png">
<img width="768" alt="Screen Shot 2020-02-13 at 10 51 55 AM" src="https://user-images.githubusercontent.com/16461988/74383611-665fdf80-4e54-11ea-9608-b7e696606a6f.png">

## Versions (please complete the following information)
 - mSupply Version v4.09.00-RC7
- mSupply mobile Version: 4.0.0-RC7
 - OS: macOS X
 
## Users affected

Ivory Coast

## Additional context

It was originally created as a mSupply Desktop issue: https://github.com/sussol/msupply/issues/5442

After checking the log we could see that `paymentTypeID` was arriving empty to the server.

**Comment by joshxg** [comment]
hmm it seems that I am getting the same in the receipt form:

![image](https://user-images.githubusercontent.com/35858975/74595250-2e4edb80-50a4-11ea-8a2c-34bb7c6f60bf.png)


But actually the payment type is being set on the record:

![image](https://user-images.githubusercontent.com/35858975/74595256-3eff5180-50a4-11ea-931d-0bf18a20853d.png)

(which is the correct payment type ID)

**Comment by nmadruga** [comment]
I'll check again and let you know.

**Comment by joshxg** [comment]
@nmadruga 

Did you get a chance to check on this again?

**Comment by nmadruga** [comment]
AAAAAHHHHH 🙉

**Comment by nmadruga** [comment]
![Screen Shot 2020-02-28 at 2 52 39 PM](https://user-images.githubusercontent.com/16461988/75503287-26931d80-5a3a-11ea-88dd-4d1dcc3b3d0e.png)

@joshxg I have tried one more time. This time my itens don't have price, but even though I was able to select the payment type on mobile as 'Carte visa'. And the payment type is not being filled on mSupply Desktop. I'll check the sync record in a moment...

**Comment by nmadruga** [comment]
Hi @joshxg I've finally managed to find time to test it and.... The record received the Payment type. See the record browser on mSupply Desktop showing it! So, this seems to be a mSupply bug, I'll reopen the issue there and close it here : ) For now (ping-pong)
<img width="841" alt="Screen Shot 2020-02-28 at 3 42 18 PM" src="https://user-images.githubusercontent.com/16461988/75505810-23e7f680-5a41-11ea-8cd8-5eac67c77b9e.png">

**Comment by joshxg** [comment]
YESSSSSSS I KNEW IT! 🎉

**Comment by joshxg** [comment]
thanks :)
