### ISSUE TITLE
Payment type coming filled on second creation of Prescription

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2290]
## Describe the bug

I have selected the Payment type for one Prescription. Finalised and confirmed.
Then went to create another Prescription. Then on the 3rd step the Payment type was already selected with the same type selected on the last Prescription.

### To reproduce

1. Go to Dispensary
2. Click on any Patient, column dispense
3. Click on any Prescriber (or create a New Prescriber and select it)
4. Add item that has price associated (this needs to be set in mSupply server before initial sync) 5. Add some quantity to the item
6. Go to the next step and select a 'Payment type' i.e.: Cheque
7. Click confirm
7. Now repeat steps above again and check that 'Payment type' already comes filled as 'Cheque'

### Expected behaviour

1. The Payment Type should be showing: "Select a payment type". 
2. And the Confirm button should not be enabled (haven't checked if that was working before I selected the payment type). mSupply mobile should not allow the creation of prescription without the Payment type selected (if it's using Payment module).

### Version and device info

- App version: 4.0.0-RC7
- Tablet model: Emulator
- OS version: Android 5.1

**Comment by joshxg** [comment]
Closed by #2326
