### ISSUE TITLE
Available credit not showing on 3rd step of Creating Prescription

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2291]
## Describe the bug

I've created one Prescription for Patient KOUAKOU that costed $12, but over paid $18. Finalised.
When I went to create a second Prescription for the same patient that costed $6, the `Available credit` was not showing up correctly.

I tried to change the `Payment Amount` to 0, but still not showing. So possibly a bug.

![Screen Shot 2020-02-13 at 12 23 40 PM](https://user-images.githubusercontent.com/16461988/74387144-a2973e00-4e5c-11ea-96d4-8ff4cb5caee2.png)
![Screen Shot 2020-02-13 at 12 22 56 PM](https://user-images.githubusercontent.com/16461988/74387151-a4f99800-4e5c-11ea-9b5c-c7aa848103de.png)

### To reproduce

1. Go to Dispensary
2. Click on any Patient, column dispense
3. Click on any Prescriber (or create a New Prescriber and select it)
4. Add item that has price associated (this needs to be set in mSupply server before initial sync) 5. Add some quantity to the item
6. Go to the next step and add a little bit more to `Payment Amount`.
7. Confirm this prescription. Sync.
8. Repeat the process, creating a another prescription for the same Patient.
9. On the 3rd step under `Payment Amount` the `Available credit` should be showing the amount that was over paid previously on the first prescription created.

### Expected behaviour

The `Available credit` should be showing.
Changing the `Payment Amount` to 0 should use the `Available credit` available.

### Version and device info

- App version: 4.0.0-rc7
- Tablet model: Emulator
- OS version: Android 5.1

**Comment by joshxg** [comment]
You can't gain available credit by overpaying - if you put `$18` for a `$12` prescription the `change required` field should say `$6`
