### ISSUE TITLE
Improvement - Prescription categories order

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2292]
## Describe the bug

The prescription categories order are different from what we see in mSupply desktop. Not a big issue, but why not to use the Alphabetical order here? I think it would be useful.
![Screen Shot 2020-02-13 at 12 39 58 PM](https://user-images.githubusercontent.com/16461988/74387726-33bae480-4e5e-11ea-931e-0a9bc42e2ea7.png)

### To reproduce

1. Go to Dispensary
2. Click on any Patient, column dispense
3. Click on any Prescriber (or create a New Prescriber and select it)
4. Add item that has price associated (this needs to be set in mSupply server before initial sync) 5. Add some quantity to the item
5. Go to the next step
6. Click on 'Select a prescription category'
PS: To see this option those should be inserted previously in mSupply:
Special > Transaction categories > Select Transaction type: Prescriptions 

### Expected behaviour

Show prescription categories in alphabetical order

### Version and device info

- App version: 4.0.0-rc7
- Tablet model: Emulator
- OS version: Android 5.1

**Comment by joshxg** [comment]
Closed by #2325
