### ISSUE TITLE
Patient categories not showing up on 3rd step of Creating Prescription

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2293]
## Describe the bug

`usesPatientType` in here:
![Screen Shot 2020-02-13 at 12 49 05 PM](https://user-images.githubusercontent.com/16461988/74388068-44b82580-4e5f-11ea-95ae-b34b6ba514d9.png)

But no dropdown showing in here:
![Screen Shot 2020-02-13 at 12 49 11 PM](https://user-images.githubusercontent.com/16461988/74388062-4255cb80-4e5f-11ea-9e5a-a929ed401f59.png)

### To reproduce

1. Go to Dispensary
2. Click on any Patient, column dispense
3. Click on any Prescriber (or create a New Prescriber and select it)
4. Add item that has price associated (this needs to be set in mSupply server before initial sync) 5. Add some quantity to the item
6. Go to the next step, which is the 3rd step
7. Where is the dropdown??

### Expected behaviour

Should show the dropdown box to select Patient type on the 3rd step of New Prescription

### Version and device info

- App version: 4.0.0-RC7
- Tablet model: Emulator
- OS version: Android 5.1

**Comment by mark-prins** [comment]
oh yeah. I noticed that today and wondered about it. Thanks for spotting it!

**Comment by mark-prins** [comment]
oh yeah. I noticed that today and wondered about it. Thanks for spotting it!

**Comment by joshxg** [comment]
Closed by #2306
