### ISSUE TITLE
Spinner when creating program requisition

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#2294]
## Is your feature request related to a problem? Please describe.

With newly added logic for program requisition SOH and AMC calculation, need an indicator that requisition is loading (as it takes a bit longer and looks like app frozen)

## Describe the solution you'd like

Have the `runWithLoadingIndicator` spinner display when the requisition is being navigated to.

## Implementation

Wrap the call to navigate in `runWithLoadingIndicator`. To access the function you can use `LoadingIndicatorContext`

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by joshxg** [comment]
We also need this for adding items from master list on customer invoice and creating a program based customer requisition
