### ISSUE TITLE
Mobile App crashes when edit comment button been clicked on StocktakePage, StocktakeEditPage and StocktakeManagePage )

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2297]
## Describe the bug

mSupply Mobile crashes after editing comment button been clicked on StockTakePage 

### To reproduce

1. Go to 'StockTake page'
2. Click on 'one of stocktake name'
3. Click on editing comment'

### Expected behaviour

Edit comment modal should be triggered to ask for editing

### Proposed Solution
let you decide

### Version and device info

- App version: v4.0.0 rc-1
- Tablet model: samsung
- OS version: ios

### Additional context

not really

**Comment by joshxg** [comment]
Closing this one in favour of #2308
