### ISSUE TITLE
"Select a reason" Modal pop-up too quickly( after 1 digit of number been typed in)

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2307]
## Describe the bug
User couldn't type in actual quantity in one go because "select a reason" modal will pop-up after 1 digit has been put in. User has to go back to StocktakeEdit page to re-type the quantity again.

### To reproduce

1. Go to 'StocktakePage'
2. Click on 'one Stocktake'
3. Click on selective item's "ACTUAL QUATITY" cell then type actual quantity in the cell  

### Expected behaviour

User should be able to type in actual quantity in StockEditPage in one go.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v4.0.0. rc-1
- Tablet model: Samsung
- OS version:

**Comment by joshxg** [comment]
Same issue as #2234
