### ISSUE TITLE
Viewing customer requisitions > App crashed

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#2317]
## Describe the bug

When clicked to View the customer response requisition > App crash

### To reproduce

1. Do the requested order to Mobile store
2. Once request order is placed > View the customer requisition 
3. click on that requisition to see

### Expected behaviour

APP should not crash

### Proposed Solution

@joshxg Master Mind needed

### Version and device info

- App version: v4.0.0-rc10
- Tablet model: Samsung 4.4.4
- OS version: ANDRIOD

**Comment by joshxg** [comment]
Closed by #2322
