### ISSUE TITLE
Editing a stocktake batch does not enter the sync queue

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2318]
## Describe the bug

Typo in the code, where after editing the counted quantity of a stocktake batch, the sync queue isn't informed

### To reproduce

1. Create a stocktake - add some batches if none
2. Sync to desktop
3. Edit a stocktake batch
4. Try to sync - no sync records sent

### Expected behaviour

Updating a stocktake batch should enter the sync queue

### Proposed Solution

N/A

### Version and device info

N/A

### Additional context

N/A

**Comment by bijaySussol** [comment]
+1 - I was about to create one.
I have seen this on mobile version: v4.0.0 RC10

**Comment by joshxg** [comment]
Closed by #2320
