### ISSUE TITLE
Creates ledger issues if quantities on stock take lines get set to go infinite and finalise it

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#2338]
## Describe the bug

Mobile allows stock taking.
Doing the stocktake against the associated lines > When setting the quantity to go infinite against that line having stock > It creates the ledger problem on desktop against that item on that store.

### To reproduce

1. Create a stock take line against the current stock for one item
2.View that lines and on quantity field set the quantity until you get to see `infinite`
3. Finalize that stock take

### Expected behaviour

No ledger issues should be created

### Proposed Solution

Am not sure but maybe don't let it go to `infinite`

### Version and device info

- App version: v4.0.0 RC10
- Tablet model: Samsung
- OS version: 4.4.4

### Additional context

Shared this to @joshxg via Telegram
Leaving this to @joshxg to put his thought.

**Comment by joshxg** [comment]
I think having a limit of `999,999` or something for number inputs..? hopefully `999,999` is big enough?

**Comment by joshxg** [comment]
Closed by #2351
