### ISSUE TITLE
Add Prescriber.storeID to schema

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2339]
## Is your feature request related to a problem? Please describe.

Potentially going to be receiving prescribers from other stores in the future.

## Describe the solution you'd like

- Add `storeID` to `Prescriber` to keep it stable between syncing
- I think adding a `fromThisStore` field would also be a good idea

## Implementation

As above

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2352

**Comment by ArpitaSussol** [comment]
Tested in V4.0.0

### Tests

- [ ] In clinician table, storeID is saved for given prescriber. - **PASS**
