### ISSUE TITLE
Change visibility on store in msupply will cause app crash on physical mobile

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2354]
## Describe the bug

Change visibility on store in desktop will cause physical mobile crash( "unfortunately, msupply mobile has stopped")

### To reproduce

Change visibility of stores under zam will cause physical mobile with mobile app logged in as store(zam) crash. 
1. Go to 'customerRequisitionsPage'
2. Click on 'customerRequisitionsPage'

### Expected behaviour

get in to customerRequisitionsPage

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v4.0.0
- Tablet model: Samsung
- OS version:

**Comment by joshxg** [comment]
@Rebecca367 

What RC version are you using?

**Comment by Rebecca367** [comment]
@joshxg 
RC1 Do you think it related? Should I use the latest RC version?

**Comment by joshxg** [comment]
@Rebecca367 

Seems related to me. Should always try to use the latest RC version - it is RC12 now, so a lot of bugs have been fixed since RC1 :)

**Comment by Rebecca367** [comment]
@joshxg OK
