### ISSUE TITLE
Cash register throws error if no payment types defined

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2355]
## Describe the bug

If no payment types are defined, the cash register throws an error. Arguably is a config issue, but could theoretically occur due to an incomplete sync etc. In any case, best to play it safe and add some defensive code. 

### To reproduce

1. Setup a datafile with no payment types defined.
2. Enable mobile cash register (`usesCashRegisterModule`).
3. Open cash register on mobile.

### Expected behaviour

My current thinking is that the cash register is pretty tightly bound to payment types, so probably shouldn't appear as a module unless there is at least one payment type defined?

### Proposed Solution

Small change to `modulesReducer`:

```
const usingPaymentTypes = UIDatabase.objects('PaymentType').length > 0;

const usingCashRegister = checkModule(SETTINGS_KEYS.CASH_REGISTER_MODULE) && usingPaymentTypes;
```

### Version and device info

- App version: v4.0.0
- Tablet model: Emulator
- OS version: API 29.

### Additional context

N/A.

**Comment by joshxg** [comment]
Closed by #2356
