### ISSUE TITLE
v3.2.4 sync error - objectType must be of type 'string', got (undefined)

### ISSUE THREAD

**Issue by LouLomas** [openmsupply/mobile#2360]
## Describe the bug
mSupply Mobile v3.2.4, in use in the field by customer
Automatic sync not happening
When trying to do a manual sync the following error message appears
![image](https://user-images.githubusercontent.com/50306838/74887801-d9cb9900-53e0-11ea-86b0-97dd59c943ed.png)
objectType must be of type 'string', got (undefined)

### To reproduce
1. attempt a manual sync to get this error message.  The two tablets haven't had a successful automatic sync since they were running v3.2.0

### Version and device info
- App version: v3.2.4
- Tablet model: - 
- OS version: - 

For further info our internal mSupply Foundation developers can see https://tinyurl.com/unmskro

**Comment by joshxg** [comment]
@LouLomas 

Thanks! Is there anyone able to use SureMDM and access the realm database file for this? I've had a quick look and this isn't a trivial problem - the more detail I'm able to get the easier it will be! :)

**Comment by andreievg** [comment]
I think josh mean "@LouLomas thanks!"

And request to access sureMDM for realm database is for a developer. @anildahalsussol @sworup @raviSussol maybe one of you can get the realm db for testing ?

**Comment by andreievg** [comment]
Unless you have time and you want to learn how to do it @LouLomas

**Comment by andreievg** [comment]
ohh btw, please don't post the data here

**Comment by raviSussol** [comment]
@joshxg @andreievg Their tablet is on v3.2.4 which means in order to grab a data file the `view/edit preferences` need to be ticked and synced into that tablet. Then only setting button gets visible from where we can tap to pull a backup. At the moment, the error occurs when mobile force sync is tapped and can not sync to the server.

**Comment by raviSussol** [comment]
The other way I can think of  to work around for this is to edit that setting button in the mobile app and make it visible to all and build an apk and auto upgrade it via suremdm job...? That way we can pull a backup of their tablet data file. As soon as we get backup of that data file we again revert back to the previous apk in that tablet.

**Comment by LouLomas** [comment]
FYI @raviSussol is working on this support ticket at the moment

**Comment by raviSussol** [comment]
Ignore above comments. No syncing is required - just need to set that pref on in the server and the rest will be done when user logging in the mobile. I forgot myself this... 😄  . Anyway, pulling their data file now.

**Comment by joshxg** [comment]
Thanks @raviSussol 🎉 

Maybe I can make the docs more clear? If you have any suggestion

**Comment by raviSussol** [comment]
@joshxg Ah yes perhaps Mark Glover would love to put his input on this one. He was wondering if this sort of thing somewhere in the docs.

**Comment by joshxg** [comment]
at the moment just here: https://docs.msupply.foundation/en:mobile:user_guide:mobile_settings

**Comment by joshxg** [comment]
Have found it is because of a "M" sync record from the server which mobile can't handle. Don't know how this has never come up before!

Will release a patch for this early tomorrow.

**Comment by joshxg** [comment]
Closed by #2365
