### ISSUE TITLE
Difference between a patient created on mobile and desktop

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2375]
## Describe the bug

- There is a bit of a diff between a patient created on desktop and on mobile

### To reproduce

1. Create a patient on mobile
2. Create a patient on desktop
3. Compare the records

### Expected behaviour

- Address' of a patient should be mapped to `billing_address1` and `bill_address2`
- Patients created on desktop have on default a `currency_ID`
- Patients created on desktop have a default `barcode` : `"*[name]code*"`
- Patients created on desktop have a default `[name]charge_code === [name]code`
- Patients have a `[name]price_category` on desktop - a selection from `["A","B", ..., "F"]`

### Proposed Solution

Address is easily done. 
Need some help with the `currency_ID`, `barcode`, `charge_code` and `price_category` ... @craigdrown @mark-prins @andreievg @DhanyaHerath ? Some of these fields seem to be assigned simply because they're a `[name]` 

- `currency_ID`: patients get assigned a `currency_ID` by default but this isn't selectable in the UI. Can Probably skip.
- `barcode` : No idea what this is used for. Is auto-assigned - just going to assign
- `charge_code` : Seems to have something to do with some customizations or other names? - just going to assign
- `price_category` : Should there be a choice of a price category for a patient? From A-F? This isn't localized either - where is this used?

### Version and device info

- App version: 4.0.0RC12
- Tablet model: All
- OS version: All

### Additional context

N/A

**Comment by craigdrown** [comment]
Currency_ID- for consistency, good to assign home currency.
barcode: for future use - like to usually be the [name]code - old barcode readers had definable stop characters, hence the "*" - ignore.- suggest leave barcode blank.
[name]charge_code is a way of aggregating names for billing- e.g. you have branches, but their charges should all be billed to HQ  (or potentially a family where they are all paid for by the Mother ;-)  ). Should be filled with name.code by default.
price_category: can leave blank - is used to set different markups- most of these fields are relevant to customers more than patients.

**Comment by joshxg** [comment]
@craigdrown thanks a lot

Just double checking this is correct(currency's not in mobile - so need to add):, currency is system data with a single home/default currency set by `[currency]is_home_currency` for each country

**Comment by craigdrown** [comment]
That's right, but also OK to leave I think. 
The logic is that when making an invoice, by default transact.currency is set to the name.currency. As long as that logic (on desktop) falls back to using the home currency if the name has no currency set, we're safe. (thinking of issuing to a name on desktop that was created on mobile)

**Comment by joshxg** [comment]
Option A) Add currency to mobile and auto assign the default
Option B) Have the server auto add the default currency to a name if it's not set

Leaning toward A because it's easier for me 🤣 

🤷‍♂

**Comment by mark-prins** [comment]
I would have leaned toward B - same reason though. Seemed easier to me 😆 
Option A sounds fine; either option would work and A gives more functionality to mobile?

**Comment by joshxg** [comment]
Hey that's true - it is quite easy to make an issue in the desktop repo and hope that someone does it? 🤣

**Comment by joshxg** [comment]
Closed by #2392

**Comment by DhanyaHerath** [comment]
Build test - passed with issues 

- [ ] When syncing a patient to desktop - the billing address fields are correctly set.
Not set - I might be reading the code wrong but I thought it might be because these lines should be setting `bill_address1`  and `bill_address2` rather than `address1` etc : 
https://github.com/openmsupply/mobile/blob/c61b5e172f2c4e2ea3ffccded0edc8f2baf8380f/src/sync/outgoingSyncUtils.js#L98
Making issue now 

- [x] When syncing a patient to desktop - the charge code field is correctly set.
charge code is set to [name]code - from comments above, I assume this is correct
- [x] When syncing a patient to desktop - the barcode field is correctly set.
Barcode set to `[name]code` with asterixs around it - as above
- [x] When syncing a patient to desktop - the currency_ID is correctly set. - set to the home currency, nice :)
