### ISSUE TITLE
Missing Prescriber details

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2376]
## Is your feature request related to a problem? Please describe.

A few prescriber details are missing 

## Describe the solution you'd like

- Add a registration code
- Add a gender toggle + field
- derive from first and last names to create the `initial` field to sync to desktop

## Implementation

As above

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2394

**Comment by nishaSussol** [comment]
Tested on mobile version 4.0.0

## Tests
- [x] When synced to mobile, prescribers correctly sync their gender **-PASS-**
- [x] When synced to mobile, prescribers correctly sync their code **-PASS-**
- [x] When synced to mobile, prescribers correctly sync their initials (first name + last name, auto set) **-PASS-**
- [x] When creating or editing a prescriber, toggling their gender correctly saves **-PASS-**
