### ISSUE TITLE
Prescription missing fields

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2377]
## Is your feature request related to a problem? Please describe.

A basic prescription has a few missing fields

## Describe the solution you'd like

Add the following fields
- `Date_order_written` : same as `entry_date`
- `entry_time` : the time confirmed.
- `Colour` : no idea what this is!

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2396

**Comment by nishaSussol** [comment]
Tested on mobile version 4.0.0

## Tests
- [x] When syncing a `Transaction` the `entry_time` is correct on the server. **-PASS-**
- [x] When syncing a `Transaction` the `Date_order_written` is correct on the server (and equal to `entry_time`. **-PASS-**
