### ISSUE TITLE
Missing fields on RC Transaction for a prescription

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2378]
## Is your feature request related to a problem? Please describe.

An RC Transaction being created after a prescription payment is missing a few fields

## Describe the solution you'd like

- Comment: Should be `Receipt for invoice(s) X'
- `currency_rate`: For some reason being set (by the server it) to `1`, rather than one on desktop being set with `0`
- `entry_time` : the time of entry
- `foreign_currency_total` : On desktop this is not set
- `subtotal` : on desktop this is not set
- RCLine - `foreign_currency_price`: this is not set on desktop

## Implementation

As above. Need to determine if the following *should* be set on desktop, or not @DhanyaHerath 

The `RC` `transact` for a prescription payment:
- `foreign_currency_total` : On desktop this is not set
- `subtotal` : on desktop this is not set
- RCLine - `foreign_currency_price`: this is not set on desktop

Should they all be set?

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by DhanyaHerath** [comment]
Hm I'm a bit confused 
![image](https://user-images.githubusercontent.com/29744386/75118422-e69d0500-56de-11ea-939a-d34190ab1228.png)

I think they should be set - also for the currency fields, I had been setting them to the default currency (home currency?) for that store: 
![image](https://user-images.githubusercontent.com/29744386/75118444-1cda8480-56df-11ea-9970-3b7c080dcc0b.png)

**Comment by DhanyaHerath** [comment]
Oh hold on sorry - I should read better, that was for a cash transaction not a prescription payment, I will take another look.

**Comment by joshxg** [comment]
@DhanyaHerath 

Have some json files of records if you'd like to see - not sure if theres a problem, just inconsistencies we might need to agree on the right way?

**Comment by DhanyaHerath** [comment]
@joshxg Yeah that would be great! Sorry, got distracted but had been looking at the method `payment_receipt_ok_next`which is what is currently being used to make the prescription payment RCs

**Comment by joshxg** [comment]
[prescription-with-payment.zip](https://github.com/openmsupply/mobile/files/4242402/prescription-with-payment.zip)

**Comment by DhanyaHerath** [comment]
I think that mobile's version is correct - total, subtotal, and foreign currency total should be set as the same in this case. Not sure why destop has the currency rate set to 0 - it looks like this happens if the currency ID is not found (somewhere?). Can make a lower priority issue on desktop

**Comment by joshxg** [comment]
Closed by #2397
