### ISSUE TITLE
Remove the 'Reason' column from the main stocktake screen

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2382]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:

Stocktake:   Remove the Reason column from the main stocktake screen. Reason should only   appear when you click into 'Lot' and specify the reason for each batch   individually.

**Comment by mark-prins** [comment]
Original requirements document: 
**EXF55: Integrate a field to justify discrepancies in the stocktake**

In the pilot proposal spreadsheet, customisations tab (perhaps relates to EXF61 in original reqs):
**EX61: Stocktakes: allow justifications for difference between counted and snapshot for each line (desktop)**

No mention of the requirement being mandatory - though it does ask for a report showing difference and justification for all items that differ from snapshot quantity, which might imply mandating selection of a reason.

**Comment by mark-prins** [comment]
I vote for doing this - which should help resolve #2384 as well

**Comment by joshxg** [comment]
@mark-prins 🎉 🎉 🎉 🎉 🎉

**Comment by joshxg** [comment]
To clarify - this is issue would be 

1) No reason column for stocktake edit page. *There is still a reason column on the batch edit*
2) There is still a reason column for stocktake batch editing 
3) Remove the mandatory part of reasons - i.e. don't force open the reason modal
4) allow opening the modal without a reason currently selected (currently you can't open the modal without one selected)

**Comment by wlthomson** [comment]
Fixed by #2696.
