### ISSUE TITLE
Change the stocktake date format to show DD/MM/YYYY

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2383]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:

Stocktake:   Change the date format to DD/MM/YYYY (currently only month and year displayed)

**Comment by mark-prins** [comment]
Confirming that we'll to this one.

**Comment by joshxg** [comment]
Hmm actually:

![image](https://user-images.githubusercontent.com/35858975/75730784-ae3a9e00-5d52-11ea-9e03-9db6585c236b.png)


I'm confused. I figured this must be the created date. The date for the stocktake doesn't display anywhere else.

Only thing I can think of is the expiry date?

![image](https://user-images.githubusercontent.com/35858975/75730825-cdd1c680-5d52-11ea-88a8-d0452fd6645a.png)

From my understanding, expirys are always the last of the month. Although that has always been quite strange to me - i've just believed it. Maybe it's not? Or maybe the requirement is .. ***?

**Comment by mark-prins** [comment]
perhaps they'd like to have numbers rather than the short month as words?

`2 Mar 2020` => `02/03/2020`

( I think the first is nicer.. less clinical )

**Comment by mark-prins** [comment]
To me, the request isn't clear enough to action. I suggest closing, following up with Emily, and reopening if a formal change request comes through.

**Comment by wlthomson** [comment]
@mark Sounds good to me. Closing.

**Comment by wlthomson** [comment]
@mark-prins @DhanyaHerath @joshxg Do we have a channel for communicating stuff like this with Emily?

**Comment by joshxg** [comment]
nah I think she works for BE now

**Comment by mark-prins** [comment]
previously its been via email
