### ISSUE TITLE
Reasons screen appears too quickly when you are typing in the quantity in a stocktake

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2384]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:

Stocktake: Reasons screen appears too quickly when you are typing in the quantity. 
The screen pops up as soon as you type a single number.

**Comment by mark-prins** [comment]
Related to #2382

**Comment by joshxg** [comment]
Using #2940 consolidated reason
