### ISSUE TITLE
Update the ARV regimens in the dispensation report

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2385]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:

Update   the ARV regimens in the dispensation report - they will send an updated list   to us

***Updated to respond to comments made below***
The *Dispensation report* is the HIV program table i.e. the indicators for the HIV program.

**Comment by DhanyaHerath** [comment]
Nb. I'm not sure what this means either - may be a dashboard issue? either way, shouldn't be worked on until confirmed.

**Comment by mark-prins** [comment]
Need to understand what is meant by the 'dispensation report' - and need to updated list to be provided.

**Comment by joshxg** [comment]
I'm just gonna go and close this 🤷
