### ISSUE TITLE
Set the price format to a whole number

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2387]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:
Set the price format to a whole number

 (no other info available to me yet sorry :( )

**Comment by mark-prins** [comment]
Unsure what to change to meet this request.

**Comment by mark-prins** [comment]
This was a vague request to make all prices whole numbers across the entire platform.
Closing this issue - we can look at it when a formal request comes through.
