### ISSUE TITLE
Should be able to search for a patient by code, surname or name

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2388]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:
Search for a patient by code, surname or name (currently can only search by first name apparently?)

**Comment by mark-prins** [comment]
Can currently search by first name, surname and date of birth. Surely this is sufficient?
To query with CI

**Comment by mark-prins** [comment]
no further details, closing until requested to add code
