### ISSUE TITLE
GTT Translation request - dose

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2389]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:
Change instructions to posologie (dose)

## Describe the solution you'd like

Change the string under `directions` in `dispensingStrings.json` under the french translations

## Implementation

Change `directions` in `dispensingStrings` from `Instructions` to `posologie`

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by mark-prins** [comment]
sure

**Comment by joshxg** [comment]
Closed by #2450

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v5.0.0RC1

### Tests
- [x] Dispense, get to the item selection screen and check the label of the Directions entry
It should be changed from `Instructions` to `posologie` **-PASS-**
