### ISSUE TITLE
GTT Translation request - show all products

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2390]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:
Change afficher les produits surstockés to afficher tous les produits (show all products)

## Describe the solution you'd like

Change the string in `programStrings.json`: `show_over_stocked`

## Implementation

Change `show_over_stocked` in `programStrings.json` in the french translations from `Afficher les\nproduits surstocké` to `afficher tous les produits` - check the button (used in `Supplier Requisitions` for a program requisition that the string looks fine.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by mark-prins** [comment]
Confirming that we'll go ahead with this one

**Comment by joshxg** [comment]
Closed by #2450

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v5.0.0RC1

### Tests
- Create or edit a Factures réquisition and check the text of the toggle to show all items
- [x] The `show_over_stocked` should show as `afficher tous les produits` in French **-PASS-**
