### ISSUE TITLE
Set "usesPaymentModule" to false doesn't hide cost and sell prices in the supplier invoice page

### ISSUE THREAD

**Issue by raviSussol** [openmsupply/mobile#2402]
## Describe the bug
When _usesPaymentModule_ set to `false` or when there is no any this key created in the mobile store's custom data in the desktop app then the `Cost Price` and `Sell Price` columns don't get hidden.

### To reproduce

In the mSupply desktop primary sync server:
1. Go to Show stores... > double click to a dispensary store and goto `Custom` tab and set _usesPaymentModule_ key to `false` (if already exists) or without _usesPaymentModule_ key in the custom tab.
2. In the mobile, login to the home screen and open a supplier invoice
3. The `Cost Price` and `Sell Price` columns still appear in the page

### Expected behaviour
`Cost Price` and `Sell Price` columns should be hidden when _usesPaymentModule_ is set to false or if there is no any key with name _usesPaymentModule_ in the custom tab of the mobile store

### Version and device info

- 4.0.0-rc12
- Tablet model: Any (Lenovo, Samsung, android tablet....)

**Comment by joshxg** [comment]
Closed by #2404

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.0

## Tests 
- [x] Sell/cost price columns show in supplier invoice page with usesPaymentModules enabled. **-PASS-**
- [x] Sell/cost price columns DON'T show in supplier invoice page with usesPaymentModules disabled. **-PASS-**
