### ISSUE TITLE
Undefined data field in pages when sorting

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2406]
## Error in mSupply Mobile

**TypeError** in **MainActivity**
t.sort is not a function. (In 't.sort(function(t,n){var u;return null==(u=n[o])?void 0:u.localeCompare(t[o])})', 't.sort' is undefined)

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e579721173457001950a773?event_id=5e5797210055ede926f40000&i=gh&m=ci)

## Stacktrace

    src/utilities/sortDataBy.js:56 - sortDataBy
    src/pages/dataTableUtilities/reducer/tableReducers.js:24 - sortData
    src/pages/dataTableUtilities/reducer/DataTablePageReducer.js:26 - PageReducerLookup
    src/reducers/PagesReducer.js:38 - PagesReducer
    src/pages/dataTableUtilities/getPageDispatchers.js:45 - onSortColumn
    src/widgets/DataTable/HeaderCell.js:43 - 
    src/utilities/underscoreMethods.js:27 - 

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e579721173457001950a773?event_id=5e5797210055ede926f40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by joshxg** [comment]
Not sure exactly how this is occurring. Have looked through the code and bugsnag - 1) it *must* be occurring when sorting a column 2) all columns are defined correctly 3) this is to do with `data.sort` not being a function [`data` is undefined or null]

Have tested all columns and they are sorting correctly, so there is some step missing for full repro

**Comment by joshxg** [comment]
Have had another bugsnag for this in #2539 

Can't see the code path where this is possible so I am guessing there is some sort of tricky UI interaction. For example spam clicking sort while navigating backwards, or something like that!

**Comment by wlthomson** [comment]
Hm, seems relatively low priority so going to bump again to `v4.0.3`!

**Comment by wlthomson** [comment]
Hm, without being able to replicate this its not gonna be fixable. Going to bump to `v4.0.3` and lower the priority as seems like this is quite a rare bug. If we start seeing a few more snags for it then might need to revisit it as high priority.

**Comment by joshxg** [comment]
Going for a reopen
