### ISSUE TITLE
Comments in translation.js of example to export/import

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2409]
## Is your feature request related to a problem? Please describe.

Problem? I have a bad memory!

## Describe the solution you'd like

An example in `dev_scripts/translation.js` with an example of importing and exporting so I don't have to go to the wiki every time! :trollface: 

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
See docs: https://github.com/openmsupply/mobile/wiki/Scripts

**Comment by diegoevangelisti** [comment]
> Problem? I have a bad memory!

Never change my friend 😆 
(I can work on this one btw)

**Comment by joshxg** [comment]
Closed by #2452
