### ISSUE TITLE
Editing a supplier invoice after syncing does not re-sync

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2414]
## Describe the bug

After syncing a supplier invoice which has been created against an external supplier, if you go back and edit it it does not resync

### To reproduce

1. Go to Supplier invoice
2. Add an item, edit a quantity
3. Sync it
4. Change quantity, finalise and sync
5. See error.

### Expected behaviour

The updates should sync!

### Proposed Solution

Make sure to add it to the sync queue!

### Version and device info

- App version: 3.2+
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2417

**Comment by ArpitaSussol** [comment]
Tested in V4.0.0

### Tests

- [ ]  After editing a TransactionBatch in an SI - the record on the server is updated also- **PASS**
