### ISSUE TITLE
Two decimal places showing 

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2422]
## Describe the bug

When paying for a prescription, two decimal places show instead of one in the payment amount

### To reproduce

1. Go to pay for a prescription

### Expected behaviour

Should only show one

### Proposed Solution

Show one

### Version and device info

N/A

### Additional context

nN/A

**Comment by joshxg** [comment]
Closed by #2423

**Comment by ArpitaSussol** [comment]
Tested in 4.0.0

### Tests

- [ ]  Decimal places in payment for a prescription payment amount looks good

@joshxg payment amount on load shows one decimal place which is fine
![Screenshot_2020-03-03-12-26-27](https://user-images.githubusercontent.com/58979436/75749905-05d50b80-5d4b-11ea-917c-5eaaba16325e.png)

but when filled with number it takes upto two decimal place.
![Screenshot_2020-03-03-12-27-13](https://user-images.githubusercontent.com/58979436/75749922-11283700-5d4b-11ea-8f73-5cf4b9ea5d5c.png)

Is this the required behavior?

**Comment by joshxg** [comment]
@ArpitaSussol 

Yes - thanks. The actual problem was that it used to show TWO `.` instead of one
