### ISSUE TITLE
Disabled buttons too grey

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2424]
## Describe the bug

Buttons which are disabled are too grey, should be lightened

### To reproduce

1. Go to a finalised CI

### Expected behaviour

Not so grey that you cant even see the background text

### Proposed Solution

Change the styles

### Version and device info

N/A

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2425

**Comment by nishaSussol** [comment]
Tested on mobile version 4.0.0

## Tests
- [x] Can read text on buttons which are disabled **-PASS-**
