### ISSUE TITLE
Modal titles should have an elipsis mode

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2428]
## Describe the bug

Titles in modals don't have an elipsis mode, so they look strange if you add a patient name, for example with a very long first/last name

### To reproduce

1. Create a patient with a very long name
2. Try to edit the patient

### Expected behaviour

Should be cut off 

### Proposed Solution

Possibly ellipsis mode or max number of lines

### Version and device info

- App version: 4.0.0RC15
- Tablet model:
- OS version:

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2435

**Comment by ArpitaSussol** [comment]
Tested in V4.0.0

### Tests
@joshxg 
tried with different scenario/length of firstname/lastname. It appears that title and firstname lastname overlap.
![Screenshot_2020-03-04-11-24-08](https://user-images.githubusercontent.com/58979436/75848984-d803cb80-5e0b-11ea-80e8-a1c82c2a03cf.png)
![Screenshot_2020-03-04-11-23-34](https://user-images.githubusercontent.com/58979436/75848993-dc2fe900-5e0b-11ea-9a3d-8bb55b280cf3.png)

**Comment by joshxg** [comment]
@ArpitaSussol 

ahh thats not good!

do you think you can make a new issue for that?

**Comment by ArpitaSussol** [comment]
@joshxg ok sure!!
