### ISSUE TITLE
cant edit patients

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2429]
## Describe the bug

Patients which have been created on the mobile store should be editable

### To reproduc

1. Create a patient
2. Try to edit the patient

### Expected behaviour

N/A

### Proposed Solution

N/A

### Version and device info

- App version: 4.0.0RC15
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2436

**Comment by nishaSussol** [comment]
Tested on mobile version v4.0.0

## Tests
- [x] Can edit patients on the mobile store after creating them **-PASS-**
