### ISSUE TITLE
Total price string incorrect

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2431]
## Describe the bug

Total price string usage is incorrect

<img width="319" alt="image" src="https://user-images.githubusercontent.com/35858975/75637666-cb0c9e00-5c8c-11ea-9b58-06e69e0ea3cf.png">

### To reproduce

1. Go to a prescription, add an item

### Expected behaviour

Correct string should be displayed

### Proposed Solution

N/A

### Version and device info

- App version: 4.0.0RC15

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2437

**Comment by ArpitaSussol** [comment]
Tested in V4.0.0

### Tests

- [ ]  The total price string in the prescription cart is correct - PASS
