### ISSUE TITLE
Slider styles misaligned

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2432]
## Describe the bug

`Slider` styles are misaligned

### To reproduce

1. Go to make an insurance policy

### Proposed Solution

N/A

### Version and device info

- App version: 4.0.0RC15
- Tablet model: N/A 
- OS version: N/A

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2439

**Comment by ArpitaSussol** [comment]
Tested in V4.0.0

### Tests

- [ ]  slider doesn't look all squashed n stuff! 
@joshxg ..slider still look messy. Please refer to below attached image
![Screenshot_2020-03-03-11-55-16](https://user-images.githubusercontent.com/58979436/75748011-86ddd400-5d46-11ea-93a0-f3066bd6130d.png)

**Comment by joshxg** [comment]
@ArpitaSussol 

That's the look I was going for ;-) don't like it? hehe

**Comment by ArpitaSussol** [comment]
@joshxg okay i thought Discount rate slider and Discount rate field should be aligned in same level. right now it isn't.

**Comment by ArpitaSussol** [comment]
Tested in 4.0.3

### Tests

- [ ]  slider doesn't look all squashed n stuff!  - **PASS**
Slider looks like this now
![imageslider](https://user-images.githubusercontent.com/58979436/78323516-cb50cf80-7591-11ea-9d7a-3ff69fcda340.png)
