### ISSUE TITLE
Insurance fields are incorrect

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2433]
## Describe the bug

Insurance policies aren't quite right, after reading the wiki: https://sussol.net/wiki/doku.php/msupply:specifications:customers:insurance

- Can edit policy numbers after having been saved
- Policy numbers need to be unique as a full number per provider. Not just a unique personal number, which validation checks for currently

### To reproduce

1. Go to a prescription
2. Try to make an insurance policy

### Expected behaviour

As above

### Proposed Solution

N/A

### Version and device info

- App version: v4.0.0RC15
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #2499.

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

### Tests
- [x] Create a new insurance policy and save. The policy number is NOT editable. **-PASS-**
- [x] Reopen the previously saved insurance policy. The policy number is NOT editable. **-PASS-**
- [x] Prevent duplicate policy numbers. **-PASS-**
