### ISSUE TITLE
A receipt is created even when payments are off for prescriptions

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2434]
## Describe the bug

Even when payments are off - receipts are still created for prescriptions

### To reproduce

1. Without having `usesPaymentModule` on, create a prescription
2. Finalise it

### Expected behaviour

No RC should be created for a prescription where payments are not enabled.

### Proposed Solution

N/A

### Version and device info

- App version: 4.0.0RC15
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2442

**Comment by nishaSussol** [comment]
Tested on mobile version 4.0.0

## Tests

- [x] When confirming a prescription which costs > 0, with payments enabled - create a receipt. **-PASS-**
- [x] When confirming a prescription which costs <= 0, with payments enabled - do not create a receipt **-PASS-**
- [x] When confirming a prescription which costs > 0 with payments not enabled - do not create a receipt **-PASS-**
- [x] When confirming a prescription which costs <= 0 with payments not enabled - do not create a receipt **-PASS-**
