### ISSUE TITLE
Navigating to the stock page crashes the app

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2440]
## Describe the bug

Navigating to the stock page crashes the app

### To reproduce

1. Go to the stock page

### Expected behaviour

No crashing of the app

### Proposed Solution

N/A

### Version and device info

- App version: 4.0.0-RC15
- Tablet model: N/A 
- OS version: N/A

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2441

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.0

## Tests
- [x] Can navigate to the stock page without the app crashing instantly **-PASS-**
