### ISSUE TITLE
March 2020 Dependency upgrades

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2447]
## Is your feature request related to a problem? Please describe.

Dependencies haven't been upgraded in a few months. Definitely 

## Describe the solution you'd like

Dependency upgrades!

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2453

**Comment by diegoevangelisti** [comment]
## Testing

*Must test in development environment*
- [x] Can run `yarn start` **--PASSES--**
- [x] Can run `yarn build` **--PASSES--**
