### ISSUE TITLE
Mobile should list customer credits with customer invoices

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2451]
## Describe the bug

- If a store creates a supplier credit where the supplier is a store on a mobile site, the customer credit will get lost!

### To reproduce

1. Create an internal requisition to a mobile store.
2. Finalise the Customer Requisition [This will create a CI]
3. Sync [This will create an SI on the desktop site]
4. Return goods from the SI [So, returning goods to the mobile store].
5. Sync. [This will create a CC for the mobile site]
6. See error [Mobile won't list the CC - so it can never be finalised!]

### Expected behaviour

Should list customer credits in customer invoices and allow them to be finalised. This is similar to supplier credits, which are listed with supplier invoices. Although I disagree with this approach as it's also mixing incoming v outgoing stock @craigdrown insists that a supplier credit is a type of supplier invoice and the same for customer credit and he is the boss

### Proposed Solution

Display customer invoices AND customer credits in the customer invoices page. When navigating to a customer credit, navigate to a customer invoice page [When navigating to a supplier credit page, different page info is used, so a different config has been set up. Although the columns are the same and it is always finalised, so you can't edit] - this may require different columns and/or different page info, not sure

### Version and device info

- App version: Forever
- Tablet model: N/A
- OS version: N/A

### Additional context

Technically could have done this forever(?) but the problem is worse now that you can create supplier credits on mobile - so potentially more supplier credits from being supplied from mobile stores.

**Comment by wlthomson** [comment]
Fixed by #2703.

**Comment by DhanyaHerath** [comment]
### Testing 
- [x] Customer credits appear in the customer invoices page.
- [x] Selecting a customer credit navigates to the customer invoice page.
- [ ] Customer credits cannot be edited.

^ These were editable, I could change the quantity, add and remove items etc
![image](https://user-images.githubusercontent.com/29744386/80178623-cb089900-8652-11ea-9d55-e6ce2e1c65ca.png)

Saying that, I did check on desktop and that is the same behaviour seen for the supplier credit -> customer credit on a desktop site, and the `[trans_line]sentQuantity` was stored accurately.
@wlthomson so maybe that's accurate?


- [x] Customer credits can be finalised.
- [x] Finalising a customer credit adds the correct items + quantity to stock

**Comment by wlthomson** [comment]
@DhanyaHerath Thanks! Patient credits are auto-finalised on incoming sync as of #2772, so I think that takes care of it anyway!
