### ISSUE TITLE
Upgrade react-navigation

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2454]
## The suggestion

Upgrade `react-navigation` and related dependencies to v5

**Why?**

- It's good
- Don't want to get too far behind

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2469

**Comment by wlthomson** [comment]
App navigates nicely and `v5` is a lot nicer to work with!
