### ISSUE TITLE
Disable editing insurance provider for saved policies

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2456]
## Is your feature request related to a problem? Please describe.

Related to #2433. Insurance providers should not be editable after a policy is saved.

## Describe the solution you'd like

See above.

## Implementation

Add to changes in #2455.

## Describe alternatives you've considered

N/A.

## Additional context

See #2433.

**Comment by joshxg** [comment]
Closed by #2457

**Comment by Rebecca367** [comment]
@wlthomson 
Maybe you guys are working on doc. regarding to insurance policy, but here is the link
https://docs.msupply.foundation/en:mobile:setup:server_side:config?s[]=insurance&s[]=provider regarding to insurance policy in wiki 
but just let you know that there haven't got any info. about it and hard for testers to do proper testing.

**Comment by wlthomson** [comment]
@Rebecca367 try this: https://docs.msupply.foundation/en:mobile:user_guide:dispensing?s[]=insurance

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

## Tests
- [x] Create a new insurance policy. The insurance provider can be changed. **-PASS-**
- [x] Reopen the saved insurance policy. The insurance provider cannot be changed. **-PASS-**
