### ISSUE TITLE
Disable editing policy type for saved policies

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2458]
## Is your feature request related to a problem? Please describe.

Related to #2433. Insurance policy type should not be editable after a policy is saved.

## Describe the solution you'd like

See above.

## Implementation

Add to changes in #2455.

## Describe alternatives you've considered

N/A.

## Additional context

See #2433.

**Comment by joshxg** [comment]
Closed by #2459

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

## Tests
- [x] Create a new insurance policy. The policy type can be toggled. **-PASS-**
- [x] Reopen the saved insurance policy. The policy type cannot be toggled. **-PASS-**
