### ISSUE TITLE
Unneeded file 'validationStrings.js' in localization folder

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2465]
## Describe the bug

The file `validationStrings.js` was replaced by `validationStrings.json` when all localization strings were migrated from `.js` to `.json` files, so there is no need to keep this one here.

### To reproduce

1. Navigate to `./src/localization`.
2. See file `validationStrings.js` is there.

### Expected behaviour

The file should have been deleted when the JSON one was created.

### Proposed Solution

Remove the file.

### Version and device info

- App version: All
- Tablet model: All
- OS version: All

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2482
