### ISSUE TITLE
Supplier requisition: 3 requisition are auto created after initialisation

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2468]
## Describe the bug

Once we sync the tablet from server while starting tablet....3 supplier requisitions are auto created without any details.

### To reproduce

1. Install apk (tested in 4.00)
2. Setup the sync details and username in server.
3. Sync records to tablet.
4. After login check the supplier requisition.

### Expected behaviour

Should not create requisition without any details.

### Version and device info

- App version: 4.00
- Tablet model: samsung version 4

### Additional context
![photo_2020-03-04 15 49 46](https://user-images.githubusercontent.com/18479204/75868200-cd5b2d80-5e2f-11ea-93e4-92a9f05ba8d5.jpeg)

**Comment by joshxg** [comment]
@anildahalsussol -- in your data file -when you synced, there was only 1 requisition for the store?

**Comment by anildahalsussol** [comment]
@joshxg : there are more than 10 requisition.

**Comment by joshxg** [comment]
Thanks @anildahalsussol -- since this seems like it's just a few extra records (although really bad), might target this for 4.1

**Comment by joshxg** [comment]
Can't recreate this - if you can, can you send me a data file anil on telegram?
