### ISSUE TITLE
Some fields in new patient form don't get saved

### ISSUE THREAD

**Issue by raviSussol** [openmsupply/mobile#2470]
## Describe the bug
When adding new patient fields like `Address 1`, `Address 2`, `Country` don't get saved after clicking `Save` button

### To reproduce

1. Go to Dispensary > New patient
2. Fill up a form with some values
3. Tab `Save` button to save
4. Tap a edit button to re-open that form and see those 3 fields now have an empty values

### Expected behaviour
Entered values should get saved after tapping `Save` button

### Screenshot
![](http://g.recordit.co/cgIlDukvDt.gif)

### Version and device info

- App version: 4.0.0

**Comment by raviSussol** [comment]
@joshxg Same issue with while adding `Address 1` & `Address 2` fields in the prescriber form

**Comment by joshxg** [comment]
@raviSussol Sweet - just been a bit busy but hopefully will get this done tomorrow!!

**Comment by joshxg** [comment]
Closed by #2488

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

## Tests
- [x] Edit a patient "Address 1". Close and reopen. The patient "Address 1" is updated. **-PASS-**
- [x] Edit a patient "Address 2". Close and reopen. The patient "Address 2" is updated. **-PASS-**
- [x] Edit a patient "Country". Close and reopen. The patient "Country" is updated. **-PASS-**
