### ISSUE TITLE
Dispensary: Not displaying insurance for patients

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2471]
## Describe the bug

While creating a prescriptions, if we add new insurance its not displaying in desktop, but if we choose from existing from dropdown list it display.
### To reproduce

1. Click dispensary
2. Choose any patient.
3. Select item with price and click next
4. Create new insurance for that patient and confirm by selecting that insurance
5. Sync and check payment for that patient in desktop.

### Expected behaviour

Must show insurance.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 4.00
- Tablet model: samsung version 4

**Comment by wlthomson** [comment]
Fixed by #2484.

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

### Setup
- Create a new prescription.
- Create a new insurance policy.
- Save the prescription without updating insurance policy dropdown.
- Sync to desktop.
- Open the synced prescription transaction in desktop. 
- Navigate to the `"Payment"` tab.

### Test cases
- [x] The insurance policy is correctly listed in the dropdown (bottom right of form, above `"Invoice Total"`). **-PASS-**
