### ISSUE TITLE
Changes in Patient details(name) is not seen in Patient history

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#2473]
## Describe the bug
Changes in patient details(name) is not seen everywhere. The patient history stills shows the old name. And, prescriptions created for the patient also shows old names.
![ss123](https://user-images.githubusercontent.com/59193490/75877139-21214300-5e3f-11ea-9c38-694e138472a8.png)

![ss1232](https://user-images.githubusercontent.com/59193490/75876613-1ca85a80-5e3e-11ea-8a99-ec89fd49f7d4.png)

## To reproduce
1. Edit a patient's name in mobile.
2. On server-client setup in desktop, open the Patients List.
3. Open the edited patient details
4. Click the History tab, and see the old name set for the patient there.
5. Also, check out the Prescriptions List created for that patient and see the old name there as well.

## Expected behaviour
After the patient name has been changed, the new changed name must be displayed everywhere, not the old one.

## Version and device info
-  App version: 4-09-00
- Tablet model: 4.0.0

**Comment by wlthomson** [comment]
Fixed by #2485.

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

### Setup
 - [x] Edit a patient name on mobile and sync to desktop.

### Test cases
- [x] When opening the patient in desktop, the patient name is correct for the `"Prescriptions"` tab. **-PASS-**
- [x] When opening the patient in desktop, the patient name is correct for the `"History"` tab. **-PASS-**
