### ISSUE TITLE
Modal titles are not centered

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2476]
## Describe the bug
current select master list is not in the middle of row.
It's better to be in the middle of row.

![Screen Shot 2020-03-05 at 2 46 43 PM](https://user-images.githubusercontent.com/57238075/75939866-5b96e880-5ef0-11ea-85cb-fd5428e4514b.png)

A clear and concise description of what the bug is. Use screenshots!

### To reproduce

1. Go to 'customer invoice'
2. Click on 'new invoice'
3. Click on add master list items

### Expected behaviour
Header should be in the middle of row and supposedly with bigger font

### Proposed Solution
Get into Modal String to change font and distance from left and right?!

### Version and device info

- App version: 4.0.0 rc10
- Tablet model: emulator
- OS version:

**Comment by joshxg** [comment]
Closed by #2535
