### ISSUE TITLE
Edit sync url warning showing on single line

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2478]
## Is your feature request related to a problem? Please describe.

The modal title is now showing only on a single line.

## Describe the solution you'd like

This used to split across multiple lines. For most modals this is fine - but the sync url warning will need to spread across lines. 

It now looks like this:

![Screen Shot 2020-03-05 at 3 25 42 PM](https://user-images.githubusercontent.com/9192912/75941896-c860b180-5ef5-11ea-950d-3cf2c0924df7.png)

But used to look like this:

![image](https://user-images.githubusercontent.com/9192912/75941907-d1518300-5ef5-11ea-8731-19b5b43124bc.png)

**Comment by joshxg** [comment]
The english version was just using a `\n` in the actual string

**Comment by mark-prins** [comment]
The english version has the same problem! (both languages have `\n` but the change to add `...` to the modal title has caused a small issue here.

**Comment by joshxg** [comment]
oh whoops! heh

**Comment by joshxg** [comment]
Closed by #2489

**Comment by nishaSussol** [comment]
## TESTING
Tested on mobile v5.0.0RC1

### Tests
-[x] Check the warning message shown when editing the sync url: should show multiline **-PASS-**
-[x] Check other modal titles - long ones should be single line with ellipses **-PASS-**
