### ISSUE TITLE
Reason window pop-up twice when reason column has been selected in "enter new requisition" in internal order

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2492]
## Describe the bug
When open "enter new requisition" . A reason window will pop-up asking for reasons if you enter user requested quantity. Once click on one reason then the same window pop-ups again.

![Screen Shot 2020-03-06 at 2 44 03 PM](https://user-images.githubusercontent.com/57238075/76042234-12f73200-5fb9-11ea-941a-664f6e7e9fe7.png)
![Screen Shot 2020-03-06 at 2 43 52 PM](https://user-images.githubusercontent.com/57238075/76042237-14285f00-5fb9-11ea-9206-f534181b3842.png)
![Screen Shot 2020-03-06 at 2 44 15 PM](https://user-images.githubusercontent.com/57238075/76042233-112d6e80-5fb9-11ea-8495-0249ce900994.png)

### To reproduce

1. Go to 'internal order list' then 'edit new requisition'
2. Click on 'reason'
3. See error

### Expected behaviour
reason pop-up window should only pop-up once

### Version and device info

- App version: v410
- Tablet model: all
- OS version: all

**Comment by joshxg** [comment]
Is this in the wrong repo @Rebecca367 ?

**Comment by Rebecca367** [comment]
@joshxg 
crap..yes
