### ISSUE TITLE
Confirmed prescriptions without payments are synced to server (should they be?) 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2494]
## Describe the bug

My knowledge is still patchy around mobile & sync, so I may be getting some things wrong, and am mainly opening this issue as a question. 

Currently, if you have payments enabled on mobile and create a prescription without paying for it on mobile, it is synced to desktop as a confirmed invoice. Once you click around in desktop (open prescriptions?) it is deleted. 

Between the prescription being synced to desktop and it being deleted, you can create a new prescription for the same patient on mobile and view their history, which will (incorrectly?) show them as having been prescribed the items from that initial confirmed prescription (which will soon be deleted). 

### To reproduce
With the `usesPaymentModule` and `usesDispensaryModule` turned on: 

1. Create a prescription on mobile
2. Add items that have a cost, but don't make a payment for them
3. Click ok.
4. Sync to desktop
5. Make a new prescription for the same patient
6. Click history - the goods from the prescription in Step 1 will show 
6. Search for prescriptions on desktop - the confirmed invoice will show up initially

### Expected behaviour

Not sure 

### Version and device info

- App version:v4.0.0
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
I think it's probably best to just only have finalised prescriptions sync out - limits sync records and other potential problems syncing out to other sites, showing in hisotry, more delete records etc etc

**Comment by wlthomson** [comment]
Fixed by #2702.

**Comment by DhanyaHerath** [comment]
### Testing - Passed 
- Can't complete Step 6 anymore ("Click OK") because you can't save a prescription without paying ===> test passed. 
![image](https://user-images.githubusercontent.com/29744386/79944519-d7a8b800-84bf-11ea-80fb-7631b71d5184.png)
