### ISSUE TITLE
foreign_currency_total differs from [transact]total in prescriptions synced to server 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2495]
## Describe the bug
Not sure whether this is a bug or I am missing something: 
The `[transact]foreign_currency_total` for a prescription that was made on mobile and then synced to desktop is different from the `[transact]total` value. 

If you have prescription payments turned on, this means that the cash receipt that is created from the payment shows the value of the prescription differently from the value shown on the prescription itself. 

Prescription: 
In this example, the prescription cost 20. THe insurance discount was 5, leading to the total being 15. The foreign currency total was set to 30. 

![Screen Shot 2020-03-06 at 4 38 09 PM](https://user-images.githubusercontent.com/29744386/76047877-fa8f1380-5fc8-11ea-9018-07e5051317f6.png)

Cash receipt for prescription: 
![Screen Shot 2020-03-06 at 4 40 39 PM](https://user-images.githubusercontent.com/29744386/76047992-4f328e80-5fc9-11ea-9dd7-0a6d18fd43b4.png)

### To reproduce

Not sure if this is on every datafile and instance - let me know if you want the datafile and I can send it to you, or if you can access NUC 2, it is the I`vory Coast mSupply master - switch` datafile on that NUC. 

1. Create a prescription on mobile that requires payment. 
2. Assign an insurance discount value (I don't think this is needed necessarily) 
3. Sync to desktop - open prescription and cash receipt on desktop
4. Check total shown on the cash receipt 

### Expected behaviour

I'm not sure, maybe this is a cash conversion thing?

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:4.0.0
- Tablet model:
- OS version:

### Additional context

I checked the currency_ID of the [transact], and it was set to the home currency, which had a ratio of 1.

**Comment by joshxg** [comment]
Very strange. 

In the outgoing sync we're sending

```
total: String(record.total),
foreign_currency_total: String(record.total),
```

So seems like it must be something to do with how it is calculated on the server - currency or trans lines

**Comment by DhanyaHerath** [comment]
@joshxg Hm ok, will move over to desktop repo for checking
