### ISSUE TITLE
Wrong patient credit calculation when pay off by credit

### ISSUE THREAD

**Issue by raviSussol** [openmsupply/mobile#2496]
## Describe the bug
If a patient has some available credit and when a prescription is paid by credit then the next available credit is increased by the total credit used in that prescription for that patient.

### To reproduce

1. Create a cash in transaction with $10 for a patient
2. Now create a prescription for that patient with $5
3. Pay off by credit ($5) and tap to confirm button
4. Again select that patient and create a new prescription
5. Now check available credit of that patient = $15 which is wrong. 

### Expected behaviour
The paid amount should have been deducted from its available credit. (i.e. $5)

### Version and device info

- App version: 4.0.0

**Comment by joshxg** [comment]
Closed by #2497

**Comment by Rebecca367** [comment]
## Testing

- [x] When using a patients credit, it correctly reduces the amount, rather than adding

**Comment by ArpitaSussol** [comment]
Tested in 4.0.3

### Tests

- [ ] When using a patients credit, it correctly reduces the amount, rather than adding - **PASS**
