### ISSUE TITLE
Enter qty of stocktake is not shown in the mSupply desktop app

### ISSUE THREAD

**Issue by raviSussol** [openmsupply/mobile#2501]
## Describe the bug
Creating stocktake in the mobile with quantity different than its snapshot quantity just shows blank in the desktop app.

### To reproduce

1. Create a new stocktake in the mobile.
2. Put a quantity different than its snapshot quantity. Then force sync to the mSupply desktop app.
3. Open a stocktake in the desktop app.
4. See the enter quantity shows now blank.

### Expected behaviour
Quantity should show up if counted no. of packs are different than its snapshot quantity.

### Proposed Solution
Had a quick check in the desktop app and found that `stockt_ake_line.is_edited` field didn't populated while assigning quantity in the mobile. The field should get True when actual quantity is different than its snapshot quantity in the mobile.

### Version and device info

- App version: 4.0.0

**Comment by joshxg** [comment]
so if I this correctly:

- `snapshot_qty` and `stock_take_qty` are syncing correctly, but the `is_edited` is not being sent.
- When you open a stocktake on the server, it is not showing values if under the ivory coast customisation code

My question is why does desktop not just show the `stock_take_qty` in a finalised stocktake? 

Anyway, can just sync `is_edited` if in mobile `countedNumberOfPacks` is defined

**Comment by wlthomson** [comment]
Sounds about right. Already exists a getter `StocktakeBatch.hasBeenCounted`, so should only involve a one-liner change to outgoing sync.

**Comment by joshxg** [comment]
Closed by #2503

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

## Setup
-   Using mobile, create a new stocktake.
-   Enter a quantity different than its snapshot quantity.
-   Sync to desktop.
-   Open the stocktake in desktop.

## Test cases
- [x] The entered quantity is shown correctly (i.e. the same as entered on mobile). **-PASS-**
