### ISSUE TITLE
Sync logic incorrect for new navigation bar

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2502]
## Is your feature request related to a problem? Please describe.

The sync logic is incorrect for the new navigation bar.

## Describe the solution you'd like

There is currently a sync reducer which could be used over the current convoluted logic which isn't working with the current navigation model

## Implementation

Not sure just yet!

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2510

**Comment by wlthomson** [comment]
No general problems with sync as of  `v5.0.0-rc3` (using latest navigation).
