### ISSUE TITLE
Add a units column to inventory

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2508]
## Is your feature request related to a problem? Please describe.

Raised in UAT review with Côte d'Ivoire October 2019.

*14. Ajouter une colonne de l'unité dans l'inventaire sur mobile*

## Describe the solution you'd like

Add a column to the stocktake edit page

**Comment by joshxg** [comment]
The number of columns is getting pretty limited!

**Comment by wlthomson** [comment]
Fixed by #2513.

**Comment by ArpitaSussol** [comment]
Tested in V5.0.0 rc3.

### Tests

- [ ]  Stocktake batch "Unit" column is displayed - **PASS**
