### ISSUE TITLE
Supplier requisition isVisible is undefined

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2515]
## Describe the bug

When creating a new program or general supplier requisition, the `isVisible` prop is `undefined`.

### To reproduce

1. Go to `Supplier Requisitions` -> `New Requisition` -> `General order`.
2. Click on `"Select a supplier"`.
3. See error.

### Expected behaviour

`isVisible` should be correctly defined.

### Proposed Solution

Define `isVisible` prop.

### Version and device info

- App version: v4.0.1.
- Tablet model: Android emulator.
- OS version: API 28.

### Additional context

N/A.

**Comment by joshxg** [comment]
Supplier requisitions should only be created for internal suppliers whereas supplier invoices should only be created for external suppliers (You can still receive supplier invoices for internal suppliers, but not create them arbitrarily). 

With those in mind, I don't understand the problem here exactly

**Comment by wlthomson** [comment]
@joshxg Oops, a case of mistaken identity due to the prop name being the same as the `Name` property. Still an undefined prop here though, so issue remains. 

As an aside, could you explain or point me to the documentation on why the above logic is enforced (i.e. why requisitions only for internal, and invoices only for external)?

**Comment by joshxg** [comment]
I don't know of any docs - just that requisitions are only internal because it doesn't make too much sense to make an order in a system to a supplier who isn't in the system - for SI's, i'm not sure - ironically maybe to make things simpler - like how you cant make customer requisitions at all

**Comment by joshxg** [comment]
But the user guide is here ;-) https://docs.msupply.foundation/en:mobile:user_guide

**Comment by wlthomson** [comment]
Hm, yeah the requisition makes sense, but maybe a bit restrictive to prevent requisitions for internal suppliers. Thanks!

![noice](https://user-images.githubusercontent.com/43223637/76265721-36c4bb80-62ca-11ea-8eb2-9a56690e638b.gif)

**Comment by joshxg** [comment]
> Update: maybe missing something but user docs don't seem to specify internal v external:

ah oops! Would be great if you could update them with the confusion then! :) Thanks!

**Comment by wlthomson** [comment]
> > Update: maybe missing something but user docs don't seem to specify internal v external:
> 
> ah oops! Would be great if you could update them with the confusion then! :) Thanks!

Hm, I think prob best you do it as you seem to know more! Let me know and I can proof read it though!

**Comment by joshxg** [comment]
> Maybe I'm missing something, but I got it now, thanks!

Oh, was there something else you needed to know?

anyway, no worries they're collaborative :)

**Comment by wlthomson** [comment]
> Oh, was there something else you needed to know?

No worries, I got it now! If you end up doing the docs feel free to update here with a link :).

**Comment by wlthomson** [comment]
Fixed by #2517.

**Comment by ArpitaSussol** [comment]
Tested in 4.03 apk.

### Tests

- [ ] Go to Supplier Requisitions -> New Requisition -> General order. - **PASS**

- [ ] Click on "Select a supplier". - **PASS**

- [ ]  No warning isVisible prop is undefined when selecting a supplier for a new supplier requisition. - **PASS**
