### ISSUE TITLE
Use Prefs instead of custom data for preferences

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2516]
## Is your feature request related to a problem? Please describe.

Desktop is changing here: https://github.com/sussol/msupply/issues/5762

- Deprecating custom data usage for preferences
- using the pref table to store preferences for mobile stores as well as desktop stores

## Describe the solution you'd like

- Currently after sync, there is code in `PostSyncProcessor` which evaluates the mobile stores `custom_data` stringified object.
- This stores each key in `Settings`. For example: `USES_VACCINE_MODULE: true` is placed in settings after having received `usesVaccineModule: true` in the store custom data.
- The solution required is to determine preferences from a `pref` record, rather than custom data. We can then either continue to store the key:value pairs in `Settings` or store them in a new `Preference` table.

## Implementation

Rather than using `PostSyncProcessor`, a potential solution would be to just read the `Pref` records as they are synced, and store them in the database. Not sure if we want to be selective on the prefs we store? i.e. only store the ones we have decided to accept or not

## Describe alternatives you've considered

N/A

## Additional context

So my questions on the implementation:

- Use `Settings` or `Preference` table? `Settings` is easier but I feel like it's piggy backing on something that it wasn't really designed for. I think there are differences between Sett
- Just save all `pref` records or be selective?

**Comment by joshxg** [comment]
waiting for confirmation that the desktop side will be implemented in the newest desktop version before committing to a milestone

**Comment by wlthomson** [comment]
Just updating here that going to go ahead with #2509  `custom_data`  implementation as unlikely to get store prefs any time (and only a small change which can be easily refactored anyway).

**Comment by joshxg** [comment]
@wlthomson yeah defo

**Comment by andreievg** [comment]
I guess there is a difference between Settings and preferences, settings sound like it's `site` wide and preferences are for the `store`.

Anyway new table for prefs sounds good to me. Would you have a trigger on that table that will throw an action for say navigator changes (when new module is added, show it straight away) ?

**Comment by joshxg** [comment]
- I'm ok if I am being crazy with the settings v preference thing... I dunno why heh
- At the moment we are just listening to the existing sync action `SYNC_COMPLETE` .. then we can see if there are any pref changes, and that will update the redux state which will just automatically show any changes into the UI
- Maybe if we get a lot more there could be a better way, so you just calculate each one individually rather than all of them, but it's small enough at the moment to not bother

**Comment by wlthomson** [comment]
I agree with @joshxg that cleanest solution ATM is to piggyback onto the existing logic for "flattening" `custom_data` into the redux store. 

- Is the idea to add `preferences` to state, or something similar, or to treat prefs similar to `custom_data` and store as a "flat" structure?
- Do we want to add a new "table"? If not, any thoughts re. how to temporarily store the pref data before the post sync action? 
- Related to previous question is question of how much we want to do desktop side v. mobile side (i.e. do we want to send the prefs as is, or do we plan to do some "preprocessing" on desktop before syncing to mobile)?

**Comment by joshxg** [comment]
> Is the idea to add preferences to state, or something similar, or to treat prefs similar to custom_data and store as a "flat" structure?

Initially I think just the same as we have it with the `ModulesReducer`

> Do we want to add a new "table"? If not, any thoughts re. how to temporarily store the pref data before the post sync action?

I like the idea of `Preferences` - not 100% sure it is the correct idea. Otherwise `Settings`. I see just a new `case 'Pref':` in `incomingSyncUtils` to store it there. `ModulesReducer` is really just for ease of use and to easily reflect changes in data to the UI (which realm has trouble with)

> Related to previous question is question of how much we want to do desktop side v. mobile side (i.e. do we want to send the prefs as is, or do we plan to do some "preprocessing" on desktop before syncing to mobile)?

mSupply doesn't transform any data for anything else(?), so I don't think desktop will send anything other than what it has internally.


--------


So the solution I have in my mind:
- Add a `case 'Pref':` to incoming `syncUtils`
- Change `ModulesReducer` to read the new `Prefs`

Questions:
- Use `Settings` or a new `Preference` table?
- Save all preferences synced, or just a subset of selected ones?

**Comment by wlthomson** [comment]
> Add a case 'Pref': to incoming syncUtils
>  Change ModulesReducer to read the new Prefs

I agree, just thinking how to temporarily store the prefs before the post sync action is dispatched? Or, alternatively, do we want to dispatch an action directly from the incoming sync case?

**Comment by joshxg** [comment]
@wlthomson If there is a "Pref" case, then we are storing it in either the `Settings` table or a new `Preference` table - so either one of those? Maybe I am not understanding you?

**Comment by wlthomson** [comment]
@joshxg My thinking was that you don't necessarily need a table to have an incoming sync case. I.e. instead of using a table, just store the pref directly in the redux store (i.e. redux-persist)?

**Comment by joshxg** [comment]
I personally would prefer to remove redux-persist rather than add more to it - we have enough persistent data stores :(

**Comment by wlthomson** [comment]
Hm fair enough, just an option! Moving forward with a table sounds good to me.

**Comment by wlthomson** [comment]
So to summarise:

- Add a `Preferences` table. 
- Update the modules reducer to read `Pref` instead of `custom_data` keys (I think for now, include a fall back onto `custom_data`, but prefer `Pref` if they differ).

I think that's it?

**Comment by joshxg** [comment]
I think that's good (also of course the incoming sync for the preferences table).

I would argue that we can deprecate custom data completely and not have to have a fall back for it (We're bumping to 5.0, which will require a 4.10 desktop, anyway?)

**Comment by andreievg** [comment]
https://github.com/sussol/msupply/issues/5762#issuecomment-596835681
I agree

**Comment by wlthomson** [comment]
Fixed by #2516.

**Comment by diegoevangelisti** [comment]
**Testing in progress**

### Test cases 

- [ ] Enable preference `Uses Vaccine Module` and sync with mobile. 
  - [ ] The `Pref` `usesVaccineModule` is set to `true`.
- [ ] Disable preference `Uses Vaccine Module` and sync with mobile.
   - [ ] The `Pref` `usesVaccineModule` is set to `false`.
- [ ] Enable preference `Uses Dispensary Module` and sync with mobile. 
  - [ ] The `Pref` `usesDispensaryModule` is set to `true`.
  - [ ] The `"Dispensary"` tab is visible in the bottom-right of the menu page.
- [ ] Disable preference `Uses Dispensary Module` and sync with mobile. 
  - [ ] The `Pref` `usesDispensaryModule` is set to `false`.
  - [ ] The `"Dispensary"` tab is not visible in the bottom-right of the menu page.
- [ ] Enable preference `Uses Dashboard Module` and sync with mobile. 
  - [ ] The `Pref` `usesDashboardModule` is set to `true`.
  - [ ] The "`Dashboard`" tab is visible in the bottom-right of the menu page.
- [ ] Disable preference `Uses Dashboard Module`and sync with mobile. 
  - [ ] The `Pref` `usesDashboardModule` is set to `false`.
  - [ ] The "`Dashboard`" tab is not visible in the bottom-right of the menu page.
- [ ] Enable preference `Uses Cash Register Module` and sync with mobile. 
  - [ ] The `Pref`  `usesCashRegisterModule` is set to `true`.
  - [ ] The `"Cash Register"` tab is visible in the bottom-right of the menu oage.
- [ ] Disable preference `Uses Cash Register Module` and sync with mobile. 
  - [ ] The `Pref` `usesCashRegisterModule` is set to `false`.
  - [ ] The `"Cash Register"` tab is not visible in the bottom-right of the menu page.
- [ ] Enable preference `Uses Payment Module` and sync with mobile.
  - [ ] The `Pref`  `usesPaymentModule` is set to `true`.
  - [ ] Payments/prices are enabled for supplier invoices, stocktakes and prescriptions.
- [ ] Disable preference `Uses Payment Module` and sync with mobile. 
  - [ ] The `Pref` `usesPaymentModule` is set to `false`.
  - [ ] Payments/prices are disabled for supplier invoices, stocktakes and prescriptions.
- [ ] Enable preference `Uses Patient Types` and sync with mobile.
  - [ ] The `Pref`  `usesPatientTypes` is set to `true`.
  - [ ] The patient type dropdown is displayed in the prescription wizard.
- [ ] Disable preference `Uses Patient Types` and sync with mobile.
  - [ ] The `Pref` `usesPatientTypes` is set to `false`.
  - [ ] The patient type dropdown is not displayed in the prescription wizard.
- [ ] Enable preference `Uses Hide Snapshot Column` and sync with mobile. 
  - [ ] The `Pref`  `usesHideSnapshotColumn` is set to `true`.
  - [ ] The snapshot quantity column is NOT displayed for stocktakes.
- [ ] Disable preference `Uses Hide Snapshot Column` and sync with mobile.
  - [ ] The `Pref` `usesHideSnapshotColumn` is set to `false`.
  - [ ] The snapshot quantity column is displayed for stocktakes.
- [ ] Set preference `"Monthy consumption lookback period"` to a non-negative numerical value.
  - [ ] The `Pref` `monthlyConsumptionLookBackPeriod` is set to the given value.
  - [ ] The lookback period is calculated as expected for requisitions (@andreievg, @joshxg, @mark-prins).
- [ ] Enable preference `Enforce look back period` and sync with mobile.
  - [ ] The `Pref` `monthlyConsumptionEnforceLookBackPeriod` is set to `true`.
  - [ ] The lookback period is calculated as expected for requisitions (@andreievg, @joshxg, @mark-prins).
- [ ] Disable preference `Enforce look back period` and sync with mobile.
  - [ ] The `Pref` `monthlyConsumptionEnforceLookBackPeriod` is set to `false`.
  - [ ] The lookback period is calculated as expected for requisitions (@andreievg, @joshxg, @mark-prins).
- [ ] Set preference `"Months lead time"` to a positive numerical value.
  - [ ] The `Pref` `monthsLeadTime` is set to the given value.
  - [ ] The lead time is calculated as expected for supplier requisitions (@andreievg, @joshxg, @mark-prins).
