### ISSUE TITLE
Returns via Supplier invoice - make the list bigger

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2525]
## Describe the bug

When returning items using a supplier invoice, the list of items doesn't take up the full height of the screen and scroll behaviour is strange - hard to use, the scrollbar is very small, and I struggled to scroll up again after scrolling down.

![Screen Shot 2020-03-11 at 9 58 28 AM](https://user-images.githubusercontent.com/9192912/76359025-536efb00-637f-11ea-9cd4-a68db9dbccb7.png)

### To reproduce

Steps to reproduce the behaviour:

1. Open a finalised supplier invoice (one with a large number of items on it)
2. Click on **Returns** button
3. Scroll the list of items

### Expected behaviour

Should be using as much space as possible and easy to navigate.

### Proposed Solution

Perhaps filter out all items which have 0 stock on hand : these cannot be returned, so why display in the list?

Make the list as large as possible.

**Comment by wlthomson** [comment]
Have replicated. 

Re. the scrollbar, agree something to fix. Re. the scrolling response, I think there might be a possibility this could be partially an emulator thing, as scrolling is always pretty bad when not using a tablet?

**Comment by mark-prins** [comment]
Yeah - I thought the scrolling is likely to be the emulator. Basically if we make the area bigger and possibly also limit the number of items to those with SoH > 0; then that's all good. will make it much more usable.

**Comment by GaryWilletts** [comment]
@wlthomson @mark-prins If there are no lines to return you'll need to tell the user when they click the "supplier credit" button - you might have already covered that. You might like to leave the 0 quantity lines in and change the "Quantity" column title to "Quantity available for return" or "Quantity available". What we do in desktop and very clear for the user. Just a thought, might not be appropriate.

**Comment by wlthomson** [comment]
@mark-prins @GaryWilletts I think good to limit this issue to the UI bug. I think best to do a new issue for the functionality questions re. `SoH` and column names. 

@mark-prins At this point what are you thinking re. `SoH` and column names? Still worth doing?

**Comment by mark-prins** [comment]
@wlthomson I was thinking that it was worth doing. Displaying a long list of items to the user, many of which you cannot return is a poor user experience. 
Though I'm now thinking that's likely to be mainly my test data though, and reality shouldn't be that bad.

Not sure what to call the column: the number shown is the lower value of `SoH` and `Quantity supplied on this invoice`. `Quantity available for return` covers it but is too long to fit in. I'm beginning to think 'give up and don't do anything'.

**Comment by wlthomson** [comment]
Fixed by #2525.

**Comment by nishaSussol** [comment]
### TESTING
Tested in mobile version 4.0.3

## Setup
- Make a new supplier invoice with a large number of item batches and finalize, OR open an already finalized supplier invoice with a large number of item batches.
- Click "New supplier credit".

## Tests
- [x] The data table fits the screen correctly, i.e. no large white space at the bottom of the page (except for when scrolling right to the bottom, which is consistent with other data table pages). **-PASS-**
