### ISSUE TITLE
Upgrade react-navigation to v5

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2526]
## The suggestion

Upgrade `react-navigation` to v5

**Why?**

- Stay on the BLEEDING EDGE
- It's far better
- Fix a few problems we have with navigating and re-rendering. Specifically with `screenProps`

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2533

**Comment by diegoevangelisti** [comment]
**Testing in progress**

## Testing

*This PR fully changes the navigation logic, so testing will be to ensure navigation has no regressions*

- [ ] Can navigate to Customer Invoices Page
- [ ] Can navigate to Customer Invoice Page
- [ ] Can create a Customer Invoice (and sync to the server with details being correct)
- [ ] Can navigate to Supplier Invoices Page
- [ ] Can navigate to Supplier Invoice Page
- [ ] Can create a Supplier Invoice (and sync to the server with details being correct)
- [ ] Can navigate to Supplier Requisitions Page
- [ ] Can navigate to Supplier Requisition Page
- [ ] Can create a Supplier Requisition (and sync to the server with details being correct)
- [ ] Can navigate to Customer Requisitions Page
- [ ] Can navigate to a Customer Requisition Page
- [ ] After finalising a Customer Requisition, the created Customer Invoice as well as the finalised customer Requisition are synced to the server with the correct details
- [ ] Can navigate to Stocktakes Page
- [ ] Can navigate to a Stocktake Edit Page
- [ ] Can create a Stocktake (and sync to the server with details being correct)
- [ ] Can correctly navigate to the Stocktake manage page, edit the details of a stocktake and navigate back to the stocktake edit page.
- [ ] Can navigate to Stock page
- [ ] Can navigate to Dispensing Page
- [ ] Can create a Prescription and have it sync to the server with correct details
- [ ] Can navigate to the Cash Register page
- [ ] Can create a cash in or cash out transaction, have it sync to the server with correct details
- [ ] Can navigate to the Dashboard Page
