### ISSUE TITLE
Headline of "Patient Detail" when create a new patient need to move to center 

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2532]
## Describe the bug

Headline of "Patient Detail" when create a new patient is not centered, so it needs to be moved to center. 

### To reproduce

Steps to reproduce the behaviour:

1. Go to ''Dispensary"

2. Click on 'New Patient'

### Expected behaviour

Headline should be placed in the center

### Proposed Solution
 Change spacing in modale to center

### Version and device info

- App version: v4.0.0rc
- Tablet model: emulator
- OS version: mac

### Additional context

<img width="835" alt="Screen Shot 2020-03-11 at 10 00 36 PM" src="https://user-images.githubusercontent.com/57238075/76456585-13ba1900-643c-11ea-8910-3ebeda070510.png">

**Comment by joshxg** [comment]
appears to be a problem with all modal titles - so we can just use a single issue: https://github.com/openmsupply/mobile/issues/2476 

And I will close this one
