### ISSUE TITLE
Headline of "Search for the supplier " and "Select master list " in Requisition is not centered

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2534]
## Describe the bug

"Select master list " or "Search for the supplier" and while creating new requisition should be centered.
![Screen Shot 2020-03-12 at 9 21 22 AM](https://user-images.githubusercontent.com/57238075/76461739-546a6000-6445-11ea-998b-75dbb03d9d93.png)
![Screen Shot 2020-03-12 at 9 24 50 AM](https://user-images.githubusercontent.com/57238075/76461746-56ccba00-6445-11ea-9891-782f076ef390.png)

### To reproduce

1. Go to 'supplier requisition'
2. Click on 'new requisition' then you will see "Search for the supplier " is misaligned
3. Click on "Select master list items" then you will see "select master list" is misaligned

### Expected behaviour

Headlines be  centered

### Proposed Solution

Spacing modal to center?

### Version and device info

- App version: v4.0.1
- Tablet model: emulator
- OS version:

**Comment by joshxg** [comment]
@Rebecca367 

This is obviously a problem with all titles - so lets just use the one issue here: https://github.com/openmsupply/mobile/issues/2476 that you made
