### ISSUE TITLE
Replace createAppContainer

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2537]
## Describe the bug

The method `createAppContainer` has been removed from react-navigation v5
Currently if you try to dispense in the app, the `TabNavigator` throws an error

### To reproduce

1. Go to Dispensing
2. Dispense

**Comment by joshxg** [comment]
oops.. 🤣 

I forgot about converting the `TabNavigator`..! whoopsie .. :(

**Comment by joshxg** [comment]
Closed by #2538

**Comment by wlthomson** [comment]
Confirmed fixed in `v5.0.0-rc3`.
