### ISSUE TITLE
Add patient lookup logic to dispensing page

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2542]
## Is your feature request related to a problem? Please describe.

If a patient cannot be found locally, the patient lookup API allows the prescriber to query patient records from the server via a modal.

## Describe the solution you'd like

On dispatching the patient lookup action, the API will be called, and the modal updated to display the results. 

The current patient searchbar allows for searching by name and DOB. For consistency seems like a good idea to stick with this for now and leave other functionality, e.g. lookup by insurance number, for a separate dedicated issue.

## Implementation

- Add action, reducer logic for querying the API.
- Add logic to add a "non-local" patient to the dispensary patient list.
- Possibly update dispensing page logic to provide additional info indicating if a patient is not local?

## Describe alternatives you've considered

See #2541.

## Additional context

See epic #2446.

**Comment by wlthomson** [comment]
Fixed by #2566.

**Comment by nishaSussol** [comment]
## TESTING
Tested on mobile version v5.0.0RC1

- [x] When toggling patient/prescriber datasets, the lookup button updates correctly ("Lookup patient/Lookup prescriber"). **-PASS-**
- [x] When the "Lookup patient" button is pressed, an empty modal is opened with the same title. **-PASS-**
- [x] When the "Lookup prescriber" button is pressed, an empty modal is opened with the same title. 
 **-PASS-**
- [x] When the modal is closed, the user is returned to the dispensary page without any change to the previous state. **-PASS-**
