### ISSUE TITLE
Update prescription tabs to enforce read-only constraints for non-local patients

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2543]
## Is your feature request related to a problem? Please describe.

Patient lookup functionality will enable users to prescribe to non-local patients. To ensure data integrity, users will not be able to edit these patients or associated data (i.e. insurance policies). 

## Describe the solution you'd like

Update the prescription wizard to enforce the following constraints on non-local patients:

- Patient details are read-only.
- Patient insurance policies are read-only.

## Implementation

- Add a getter to `Name`, e.g. `isLocal` which returns if `supplyingStoreId` is current store.
- If prescribing for a patient where `isLocal` is `false`, disable patient, insurance editing.

## Describe alternatives you've considered

N/A. 

## Additional context

See epic #2446.

**Comment by joshxg** [comment]
`Name` has a field `thisStoresPatient` which can be used for this which is set in `incomingSyncUtils`

**Comment by wlthomson** [comment]
@joshxg Ah nice, I wasn't aware of that. Was going to make a getter `isLocal` which just does a match on the current store and the patient's supplying store. Can go with the existing field if already in the schema.

**Comment by wlthomson** [comment]
Fixed by #2660.

**Comment by DhanyaHerath** [comment]
### Testing 

- [x] Patients which are added using the API cannot be edited locally.
- [x] Insurance polices which are added using the API cannot be edited locally.
- [x] Prescribers which are added using the API cannot be edited locally.


Feels very odd to create something (a policy) that immediately becomes uneditable, but it makes sense why :)

**Comment by wlthomson** [comment]
> Feels very odd to create something (a policy) that immediately becomes uneditable, but it makes sense why :)

Yeah, was a bit of a compromise solution to prevent messy edge cases which could cause data integrity problems!
