### ISSUE TITLE
Update outgoing sync to prevent syncing out read-only data

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2544]
## Is your feature request related to a problem? Please describe.

Adding patient API functionality will involve storing non-local patient and insurance records locally. Although the UI will enforce that these records are read-only, catching these records at outgoing sync only requires a few lines of code and provides an extra layer of security and reduces unnecessary syncing.

## Describe the solution you'd like

Add checks to outgoing sync to prevent syncing read-only records.

## Implementation

- Update `Name` sync out logic to not sync out patients where `isLocal` is `false`.
- Update `InsurancePolicy` sync out logic to not sync out policies associated with non-local patients.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #2446.

**Comment by wlthomson** [comment]
Update: 

- Desktop logic exists to update visibility for incoming `[patient]` records, meaning these records must be synced back to desktop in order for `[nameStoreJoin]` records to be created. 
- Similar logic is planned for `[clinician]` records, meaning these records also need to be synced back to desktop.
- Policies can be created on satellites for non-local patients, but only policies created by the current user can be edited. Solution is to only sync out policies where `enteredBy` is the current user?

**Comment by joshxg** [comment]
> Desktop logic exists to update visibility for incoming [patient] records, meaning these records must be synced back to desktop in order for [nameStoreJoin] records to be created.

Are these the patient records created on mobile? The server creates a name store join record for new `name` records, but also the server needs the `name` record? I think I don't understand lol

> Similar logic is planned for [clinician] records, meaning these records also need to be synced back to desktop.

Again I think I don't understand 🤣 

> Policies can be created on satellites for non-local patients, but only policies created by the current user can be edited. Solution is to only sync out policies where enteredBy is the current user?

I don't agree or think using the user table for anything is a good idea. I think adding `storeID` to insurance name join and making it a hybrid patient/store data table (where policies follow the patient around, but are only editable on the `storeID` store)

**Comment by wlthomson** [comment]
> Are these the patient records created on mobile? The server creates a name store join record for new name records, but also the server needs the name record? I think I don't understand lol

Yeah, so the patient records need to be synced back to desktop so that desktop can see that the patient has been used on mobile so it can update the `nameStoreJoins` (as I understand it, the user might add a patient and not actually dispense, so we can't just rely on transactions).

> I don't agree or think using the user table for anything is a good idea. I think adding storeID to insurance name join and making it a hybrid patient/store data table (where policies follow the patient around, but are only editable on the storeID store)

That's the first solution we had. The reason I haven't done it is:

1. it requires a lot more work (migration etc.)
2. we are acknowledging that we are going to have to add join tables for every API record type. 

I'm OK with going that route, it's definitely the safest option.

**Comment by joshxg** [comment]
> Yeah, so the patient records need to be synced back to desktop so that desktop can see that the patient has been used on mobile so it can update the nameStoreJoins (as I understand it, the user might add a patient and not actually dispense, so we can't just rely on transactions).

If this is a patient record created on mobile, then the server needs the name record and also will make a name store join for the mobile store (no others, afaik). I dunno what we are trying to figure out with this one?

> That's the first solution we had. The reason I haven't done it is:
    1. it requires a lot more work (migration etc.)
    2. we are acknowledging that we are going to have to add join tables for every API record type.

I don't understand point 2 can you elaborate for me?

I am very stupid :(

**Comment by mark-prins** [comment]
> it requires a lot more work (migration etc.)

I didn't think the migration would be that bad. We have a home store on the patient and a `nameInsuranceJoin` to link that to policy. If I understand correctly then we are just adding that storeID to the `nameInsuranceJoin` table. 

> we are acknowledging that we are going to have to add join tables for every API record type.

Sorry, I don't understand either. I'll wait for the explainer :)

**Comment by wlthomson** [comment]
Sorry, maybe I'm missing something. As I understand it, to retain visibility, we need a way for mapping stores to patients/prescribers/policies separate from the home store ID. With patients, we have `nameStoreJoin`, with prescribers we have the proposed join table, and if we add a `store_ID` to `nameInsuranceJoin`, we then have join tables for every record type which can be fetched via the API. 

My comment was just to point out why I am reluctant to go that route as it kind of locks us into a pattern which isn't very scalable.

Re. more work, the migration itself shouldn't be that bad, but it means adding a new field and updating existing code to use it. It's also potentially a bit confusing to link a policy to a patient and a user and a store. Does the home store have rights over the policy created by another store? If so, doesn't that bring us back where we started re. data inconsistencies? If not, we need more logic for this (and could also cause problems user side).

I guess my concern is that we are possibly making schema changes to address what should maybe be treated as an "edge-case" rather than core logic?

Maybe I'm overthinking it?

**Comment by joshxg** [comment]
So that we can get on the same page-

What I imagine:

- Add `insuranceNameJoin.store_ID` (`storeID`???)
- Migration (into 4.10, which ONLY has policies from the store they were created on): `insuranceNameJoin.store_ID:=insuranceNameJoin.name.store_ID` for all `insuranceNameJoin` (maybe use `supplying_store_ID`?)
- Visibility: just follows the patients visibility, no join needed, just the relation to the patient to the name store join to the store - relational databases ❤️


This WILL be another backwards incompatible change as we'd be adding `store_ID` to insurance policies. With 4.10 being pushed back a week it looks like, I think we should have time to get this done.

**Comment by joshxg** [comment]
So I suppose the problem with the above is what you have pointed out regarding data inconsistencies of having a policy which belongs to another store. So it could be unactivated (is that a word?) but still used in a different store. 

But that becomes the only problem - which we can solve by either restricting the visibility of insurance policies to a single store (the `store_ID`), or accept that there are data inconsistencies?

**Comment by wlthomson** [comment]
@joshxg I think we're on the same page here (although I was thinking migration using `supplying_store_ID`).

The main issue I have is about how to deal with differing patient home store and policy "creation" stores.

**Comment by wlthomson** [comment]
>But that becomes the only problem - which we can solve by either restricting the visibility of insurance policies to a single store (the store_ID), or accept that there are data inconsistencies?

Correct me if misunderstood, but I don't think we can restrict the visibility, as that will probably cause users to create "duplicate" policies, which I think is the kind of thing we're trying to avoid. 

I think, the basic problem is that if we can edit an insurance policy in two places, we have potential data inconsistencies. So, the issue I have is that I think (again, correct if wrong) that even with the store join, that problem remains unless we prevent the home store from editing policies created by another store (which I think would go against the whole idea of a home store?).  So the question comes back to whether the join provides enough to be worth it?

Maybe an example to clarify:  

1. Patient Josh has his home store at Mark's Pharmacy.
2. Patient Josh goes to Will's Pharmacy and presents Dr. Will with his insurance policy card which Dr. Will enters into the system.
3. The insurance policy gets synced back to Mark's Pharmacy. 
4. Dr. Mark and Dr. Will can now both edit Patient Josh's policy.

We now have an insurance policy that can be edited in two places, which AFAIK is something we want to prevent for policies as a general rule?

An alternative solution:

One thing I've thought about (inspired by the dashboard sync logic) is that it would be quite useful to have a table or field that contains date on when objects have been synced in or out (e.g. `lastSynced`). As the problem only occurs once the policy is synced back from the satellite, if we added a field like that, we could do something like:

```
isEditable() {
  return this.patient.isEditable || !this.lastSynced;
}
```

Thoughts?

**Comment by joshxg** [comment]
> We now have an insurance policy that can be edited in two places, which AFAIK is something we want to prevent for policies as a general rule?

That's what the `storeID` would prevent - policies syncing to any store the patient is visible but editable only on the sites where the `storeID` is an active store.

This still means that you can be using policies which could be outdated. This still means that if there's a mistake in a policy which is made on another site that you can't correct it on every site, so you may get duplicates. I think having a policy merge functionality could help. But I think this is hitting the limit on how much consistency and availability we can get here! 🤣 

- *Patient*: Sync determined by `name_store_join`. Editable on `name.supplying_store_id`. Visible determined by `name_store_join`
- *Prescriber*: Sync determined by `clinician.store_ID` (a clinician store join in the future will determine this). Editable on `clinician.store_ID`. Visible on any store with the record (Subtle difference - you can fetch the reccord through lookup api, but if you were to ever reinitialize the site, you'd only get the clincians with `store_ID`s which are on the site)
- *Policy*: Sync determined by `patient.name_store_join`. Editable on `policy.storeID`. Visiblity determined by `patient.name_store_join` (This should be the same for a `repeat_table`, but lets leave that for now 🤣 )


That's how I see it, what am I missing there?

**Comment by wlthomson** [comment]
I think we're on the same page with all that, except I think the problem remains with the `policy.storeID` fix.

There can only be one store for each policy,  so that effectively means the policy can only be edited by one store. However, as I understand it, the home store should be able to edit all policies for their patient, as preventing them from doing this would conflict with the role of the home store? So, if you then let the home store also edit policies linked to different stores (`[policy]storeID`), you come back to the same problem of having a policy editable in two places.

Does that make sense?

**Comment by joshxg** [comment]
yeah - so we just don't allow the policy to be edited by their home store always (unless it is of course the `store_ID` on the policy). The home store concept was primarily made for the `[name]` record itself - so we're more adjusting the concept more than conflicting? :)

**Comment by wlthomson** [comment]
> yeah - so we just don't allow the policy to be edited by their home store always (unless it is of course the `store_ID` on the policy). The home store concept was primarily made for the `[name]` record itself - so we're more adjusting the concept more than conflicting? :)

I mean, if we're OK with that, then there's no problem 🤷‍♂ . But I think end users might find it a bit problematic that they don't have a central way of managing policies?

**Comment by joshxg** [comment]
if they want to be able to create and edit policies at satellite sites (which is the requirement), then (in our sync system), there is no way of having a central point of editability (is that a word I don't think it's a word), so... too bad unfortunately? Alternatively... messages 🤣 

Slight tangent: should probably be code to set all policies of a provider to `isActive = false` if the provider becomes not active!

**Comment by wlthomson** [comment]
Yeah, so that brings us about full circle to the trade-off: prevent central editing, or prevent satellite editing. There is no problem with creating, it's the editing that is problematic. So I think the suggestion I made earlier about tracking sync could actually be a good balance as:

- allows creating new polices
- allows editing policies if mistakes are made before editing
- enforces that existing policies are read-only if not patient home store

Maybe I'm wrong, but I think this might be preferable to the `store_ID` on the join?

**Comment by joshxg** [comment]
> So I think the suggestion I made earlier about tracking sync could actually be a good balance as it

Isn't that solution essentially "allow editing for an arbitrary amount of time on satellite", though? Because sync is automatic, you could create a policy and the next second it's synced. So it (slippery slope incoming) leads to ok - so for policies, we don't add them into the sync queue until... after a prescription has finished? ok, but only for new policies. Until we get a new requirement to be able to make policies from outside a prescription (likely), then it's going back to more hacking around. I think It's a kludge for (what I think is) a non-existent requirement (allowing editing only on the patients home store).

> We do a similar thing with other records on desktop, where we allow editing only until the record is saved (as that triggers a potential sync)

We don't *really* do this on desktop, though. We allowing editing before a record is saved to the database - pretty sure we do this anyway (or we could if it's not done like that by making the policy in memory, and when you click ok on the policy form it creates the record - just like desktop?)

> as the policy store_ID will probably not be going into v10, could also use this option temporarily until it is implemented?

idea: just allow editing on a patients home store and add a confirmation dialog for safety when closing the insurance modal? Does that provide all the things you want?

**Comment by wlthomson** [comment]
> Isn't that solution essentially "allow editing for an arbitrary amount of time on satellite", though? Because sync is automatic, you could create a policy and the next second it's synced. 

Yeah, that's a fair point.

> We don't really do this on desktop, though. We allowing editing before a record is saved to the database 

I think this just restates what I said though? IMO it's the same thing whether you do it on save or sync: the logic is based on enforcing a boundary on editing a record based on whether that record is "new" or not (i.e. if that record may be linked to other transactions/sites or not).

**Comment by wlthomson** [comment]
Quick summary then I think can close this out!

### Patient 

- sync + visibility determined by `name_store_join.store_ID` .
- can fetch records, `name_store_join` record added when resynced to desktop.
- editable only on home store (`supplying_store_id`).

### Prescriber

- sync + visibility determined by `clinician.store_ID` (TODO: `clinician_store_join`).
- can fetch records, but no visibility updated on desktop (TODO: update `clinician_store_join` when resynced to desktop).
- editable only on home store (`clinician.store_ID`).

### Policy

- sync + visibility determined by `name_store_join.store_ID` (where `name_store_join.name_ID` is `nameInsuranceJoin.nameID`).
- editable only on patient home store (i.e. `nameInsuranceJoin.name.supplying_store_id`).
- new records can be added to existing patient, but once saved, can only be edited on home store.

@joshxg Sound good?

**Comment by joshxg** [comment]
sweet

**Comment by wlthomson** [comment]
Nice, thanks! Closing this out. Will piggy back suggested policy dialog to one of the remaining pending API issues.
