### ISSUE TITLE
Wrong alert message pop-up when click on "request a demo store"

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2546]
## Describe the bug
Wrong alert message pop-up when "request a demo store" button was clicked. 
<img width="823" alt="Screen Shot 2020-03-16 at 1 09 07 PM" src="https://user-images.githubusercontent.com/57238075/76713721-9ff37580-6787-11ea-9b5a-579616c0636f.png">

### To reproduce

1. Go to 'initial page'
2. Click on 'request a demo store'
3. See error

### Expected behaviour
It should lead to getting user details page like e-mail...?

### Proposed Solution

??
### Version and device info

- App version: v 4.0.1
- Tablet model: emulator
- OS version:

**Comment by Rebecca367** [comment]
I couldn't help but wonder where does mobile gonna send me e-mail to?

**Comment by joshxg** [comment]
This is caused from : 

https://github.com/openmsupply/mobile/blob/b76cfb6098e3af7976d9cfe0ed2ee4717747ef1b/src/widgets/modals/DemoUserModal.js#L212-L214

The `isVisible` prop on `ModalContainer` should be the same as on `ConfirmModal.isOpen` prop. This prevents the demo user modal from working so into the next patch might be a good idea @wlthomson?

**Comment by wlthomson** [comment]
@joshxg Agreed, suitable for `4.0.2`!

**Comment by wlthomson** [comment]
Fixed by #2555.

**Comment by Rebecca367** [comment]
oh well...still look the same on my side.
<img width="829" alt="Screen Shot 2020-03-18 at 11 26 13 AM" src="https://user-images.githubusercontent.com/57238075/76913886-3311e400-691d-11ea-8c21-fdcbec5e904b.png">

**Comment by wlthomson** [comment]
@Rebecca367 Did you pull the latest changes? Tested again and working on `v4.0.2` on one of our Lenovo TB-X304L tablets.

**Comment by Rebecca367** [comment]
@wlthomson 
Yes, I think so. I will try it again..
Oh I cannot test it on physical tablet because the tablet is not with me when I am working from home.
