### ISSUE TITLE
Cash register error

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2551]
## Describe the bug

Error when creating a new entry in the cash register:

<img width="1102" alt="Screen Shot 2020-03-16 at 9 31 14 PM" src="https://user-images.githubusercontent.com/9192912/76737786-4bbfb400-67ce-11ea-9a6d-968753cdb744.png">

### To reproduce

Steps to reproduce the behaviour:

1. Go to Cash Register
2. Create a new transaction

### Additional context

Looks like a part of #2481

**Comment by joshxg** [comment]
closed by #2552
