### ISSUE TITLE
Modal string is not centred( create new patient details and create a new prescriber)

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2554]
## Describe the bug

Modal string is not centred when you create a new patient and asking for patient details and the same as to create a new prescriber.
Some related issues been closed but issues still remain.
https://github.com/openmsupply/mobile/issues/2532#issuecomment-597830571

<img width="711" alt="Screen Shot 2020-03-17 at 1 50 45 PM" src="https://user-images.githubusercontent.com/57238075/76811758-976a7000-6857-11ea-96bc-24f951121065.png">
<img width="721" alt="Screen Shot 2020-03-17 at 1 51 18 PM" src="https://user-images.githubusercontent.com/57238075/76811764-9c2f2400-6857-11ea-9aa1-cb800aa49a6f.png">
<img width="784" alt="Screen Shot 2020-03-19 at 10 14 34 AM" src="https://user-images.githubusercontent.com/57238075/77019147-bfd3a500-69e4-11ea-938e-d887a229b50a.png">

### To reproduce

1. Go to 'dispensary'
2. Click on 'new patient' and "new prescriber"
3. See error

### Expected behaviour

modal string to be centered

### Proposed Solution

Make textAlign to be centered.

### Version and device info

- App version: v4.0.1
- Tablet model: emulator
- OS version: 

### Additional context
similar to https://github.com/openmsupply/mobile/issues/2476

**Comment by Rebecca367** [comment]
It's just bizzare. Somehow changed datafile, run emulator, log-in and string is well centered!
phew...machine does wonder stuff.
I will close this issue now.

<img width="784" alt="Screen Shot 2020-03-17 at 3 43 13 PM" src="https://user-images.githubusercontent.com/57238075/76817058-bc1a1400-6866-11ea-9239-6e977da80003.png">
<img width="788" alt="Screen Shot 2020-03-17 at 3 44 03 PM" src="https://user-images.githubusercontent.com/57238075/76817064-bde3d780-6866-11ea-8cb6-5b62a062f0cb.png">

**Comment by Rebecca367** [comment]
After upgrading app. to v4.0.2. 
Strings become uncentered again. FYR

<img width="682" alt="Screen Shot 2020-03-18 at 9 49 12 PM" src="https://user-images.githubusercontent.com/57238075/76942283-5ad76b00-6962-11ea-98eb-f14952255307.png">

<img width="758" alt="Screen Shot 2020-03-18 at 9 41 48 PM" src="https://user-images.githubusercontent.com/57238075/76942211-3a0f1580-6962-11ea-85ec-5ce2862133b7.png">
<img width="751" alt="Screen Shot 2020-03-18 at 9 40 34 PM" src="https://user-images.githubusercontent.com/57238075/76942213-3b404280-6962-11ea-93d3-ac573da34349.png">

**Comment by wlthomson** [comment]
Fixed by #2570.
