### ISSUE TITLE
Took a long time to initialise the App and pull changes from mSupply desktop 

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2558]
## Describe the bug
Took a long time to initialise the App and pull changes from mSupply desktop 
<img width="617" alt="Screen Shot 2020-03-18 at 9 15 32 PM" src="https://user-images.githubusercontent.com/57238075/76940147-907a5500-695e-11ea-9f22-37d470fe67de.png">

### To reproduce

1. Go to 'Initialisation page'
2. Enter primary server URL, sync server name and password
3. Click on initilizing

### Expected behaviour

Pull changes messages should show soon after procedure starts, 
but it stuck in "initialising". It also took a long time to start pulling changes.  

### Proposed Solution

N/A

### Version and device info

- App version: v4.0.2
- Tablet model: emulator
- OS version: macOS

### Additional context

Sometimes it jumps to log-in page without pulling any changes from server

**Comment by joshxg** [comment]
@Rebecca367 

What data file were you using for this? I haven't been experiencing any difference in initialization. With a large data file this can take some time for the server to get all the records ready. That may be what you are experiencing?

**Comment by Rebecca367** [comment]
@joshxg 
I think that I used ivory coast master data file. It seems better now.
