### ISSUE TITLE
Need more translation on dashboard in Portuguese 

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2559]
## Describe the bug
There are some strings are still in English on dashboard.  

### To reproduce

1. Click on 'dashboard'
2. See error

### Expected behaviour
All Portuguese on all strings in the app.

### Proposed Solution

Need more translation supposedly...

### Version and device info

- App version: v4.0.2
- Tablet model: emulator
- OS version: macOS

### Additional context

<img width="814" alt="Screen Shot 2020-03-19 at 9 33 30 PM" src="https://user-images.githubusercontent.com/57238075/77048411-3c897200-6a2b-11ea-82cc-e328588c6abc.png">

**Comment by joshxg** [comment]
These strings are sent directly from desktop to be displayed. If they should be translated they need to be done on desktop

**Comment by Rebecca367** [comment]
@joshxg 
It's hard for users to understand these strings.??
It might be a good idea of you to explain this to clients about "desktop send non-English strings to mobile, so what you see on your device is not in English. It has nothing to do with me who develop this software for you to use."  
It might be a good customer service after all!

**Comment by joshxg** [comment]
@Rebecca367 

Seems a lot of these strings, if not all, are hard coded. So yeah - an issue on desktop would be really great thanks
