### ISSUE TITLE
Payment types are not in English in "cash in" category when a new transaction been created in cash register

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2560]
## Describe the bug

There are payment types not in English  in "cash in" category when you create new transaction in cash register.

<img width="813" alt="Screen Shot 2020-03-19 at 10 14 55 PM" src="https://user-images.githubusercontent.com/57238075/77051690-95a7d480-6a30-11ea-9f73-cf11711f9d08.png">
 <img width="782" alt="Screen Shot 2020-03-19 at 10 14 44 PM" src="https://user-images.githubusercontent.com/57238075/77051538-52e5fc80-6a30-11ea-89cf-fbf337a0760f.png">

### To reproduce

1. Go to 'cash register'
2. Click on 'new transaction'
3. Scroll down to 'payment type'

### Expected behaviour

Payment types are in English 

### Proposed Solution
import those strings in English

### Version and device info

- App version: v4.0.2
- Tablet model: emulator
- OS version: macOS

**Comment by joshxg** [comment]
These are `[Options]` records which are sent directly from desktop. The app is simply displaying the `title` field on the record. If they should be in a different language the record needs to be changed on desktop (preferences -> options)

**Comment by Rebecca367** [comment]
@joshxg 
Great attitude toward user experience. I wouldn't select anything due to I have no idea on payment types and so forth. My desktop is in English, same as mobile, so I have no idea what you are talking about. 
Would you mind showing me on what should I do in [options] records in desktop to make it clear?

**Comment by DhanyaHerath** [comment]
Hi @Rebecca367! It looks like you're using an Ivory Coast datafile. We have the payment types hardcoded in French for them - I agree that's definitely not great, but no one else (as in, no non-French speaking customer) is using payment types so this issue can be closed in mobile for now.

**Comment by Rebecca367** [comment]
@DhanyaHerath 
Thanks for the explanation
