### ISSUE TITLE
confirm button cut-off in the middle when it's on description mode while creating new transaction 

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2561]
## Describe the bug

Confirm button partially cut-off when it's on description mode while creating a new transaction 
<img width="813" alt="Screen Shot 2020-03-19 at 10 38 37 PM" src="https://user-images.githubusercontent.com/57238075/77053008-89bd1200-6a32-11ea-9585-3046d0b76a6e.png">

### To reproduce

1. Go to 'cash register'
2. Click on 'new transaction'
3. Scroll down to type in 'description'

### Proposed Solution
N/A

### Version and device info

- App version: v4.0.2
- Tablet model: emulator
- OS version: macOS

### Additional context
Need more testing on this version due to some new behaviours appears.

**Comment by joshxg** [comment]
The confirm button shouldn't be able to be clicked when the description bottom modal is up, as far as I know - maybe @wlthomson can confirm.

So I think the solution here is possible to either bring the button higher or increase the width of the bottom modal?

**Comment by Rebecca367** [comment]
@joshxg @wlthomson 
I think 1.5 confirm button is confusing, so maybe better not show the middle confirm button?
The confirm button at right hand side is responsive to confirm description and it's working. 
It all depends on everybody's priority, I guess.

**Comment by wlthomson** [comment]
Yeah both solutions work, but the easiest fix is to just hide the main confirm button when any modal is open (gets rid of the possibility of both being displayed at once). 

Agree with @joshxg this isn't super high priority, but def suitable for the next patch release.

**Comment by wlthomson** [comment]
Fixed by #2561.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile version 4.0.3

### Tests
- [x] When making a new cash transaction, the "Confirm" button is displayed at the bottom of the modal. **-PASS-**
- [x] When making a new cash transaction, the "Confirm" button is not displayed at the bottom of the modal if another submodal is open (e.g. click "Enter a description"). **-PASS-**
