### ISSUE TITLE
Confirm button in cash out does not respond well while creating new transaction in cash register

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2562]
## Describe the bug

Confirm button does not respond well after input all details to "cash out".
It greys out itself then no response when you click on it.
<img width="788" alt="Screen Shot 2020-03-19 at 11 05 03 PM" src="https://user-images.githubusercontent.com/57238075/77055660-27661080-6a36-11ea-951f-5c4e76157853.png">
 

### To reproduce

1. Go to 'cash register'
2. Click on 'new transaction'
3. input all criteria then click on "confirm"

### Expected behaviour

confirm new transaction and go back to cash register page

### Proposed Solution

N/A

### Version and device info

- App version: V4.0.2
- Tablet model: emulator
- OS version: macOS

**Comment by joshxg** [comment]
This picture looks like in this picture there is no amount entered, so not all criteria is filled and the button should be disabled?

**Comment by Rebecca367** [comment]
@joshxg 
No, the assumption is not correct because I had tested many times with or without amount.

**Comment by joshxg** [comment]
@Rebecca367 great lets close this one then :)
