### ISSUE TITLE
PageButtonComponent memoisation does not evaluate text prop

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2565]
## Describe the bug

`PageButtonComponent` is exported as a memoised component, but does not currently evaluate the `text` prop. The effect of this is that if a buttons text is updated but the button callback is not, the button will not rerender.

### To reproduce

The bug cannot be reproduced currently, getting ahead of #2540!

### Expected behaviour

`propsAreEqual` should evaluate the `text` prop.

### Proposed Solution

Add the `text` prop to the  `propsAreEqual` evaluation.

### Version and device info

- App version: v4.0.2.
- Tablet model: Android emulator.
- OS version: API 29.

### Additional context

No existing bugs related to this AFAIK (found while working on #2540), so marking as `5.0.0` to easily branch off for #2540.

**Comment by wlthomson** [comment]
Fixed by #2567.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v5.0.0RC1

### Tests
- [x] When toggling patient/prescriber datasets, the lookup button updates correctly (`"Lookup patient/Lookup prescriber"`). **-PASS-**
- [x] When the `"Lookup patient"` button is pressed, an empty modal is opened with the same title. **-PASS-**
- [x] When the `"Lookup prescriber"` button is pressed, an empty modal is opened with the same title. **-PASS-**
- [x] When the modal is closed, the user is returned to the dispensary page without any change to the previous state. **-PASS-**
