### ISSUE TITLE
Cash transaction toggle too close to modal text

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2568]
## Describe the bug

Minor UX issue with cash transaction modal. Toggles are currently a bit too high up on the screen, which looks a bit ugly and harder to read.

1. Go to the cash register and create a new transaction.
2. See bug.

### Expected behaviour

A bit more vertical spacing.

### Proposed Solution

Minor `topMargin` adjustment.

### Version and device info

- App version: v4.0.2
- Tablet model: Android emulator
- OS version: API 28.

### Additional context

Not really a bug per-se, but have milestoned `v4.0.X` as think probably still better suits a patch than a minor/major release?

**Comment by wlthomson** [comment]
Fixed by #2571.

**Comment by nishaSussol** [comment]
### TESTING
Tested in mobile version v4.0.3

## Tests
- [x] When making a new cash transaction, there is a "good" amount of vertical space between the title and the "Cash in/out" toggle **-PASS-**
