### ISSUE TITLE
Add new outgoing tables to sync out queue

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2619]
## Is your feature request related to a problem? Please describe.

To fully enable sync, outgoing sync tables need to be added to the `SyncOut` queue.

## Describe the solution you'd like

Add all new tables to the sync out queue.

## Implementation

In `SyncQueue.js` add the following tables to `recordTypesSynced`

- `Location`
- `Sensor`
- `TemperatureLog`
- `TemperatureBreach`
- `VaccineVialMonitorStatusLog`
- `LocationMovement`

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by Chris-Petty** [comment]
![image](https://user-images.githubusercontent.com/7684221/81122481-0ecd9d80-8f85-11ea-97c6-2bebd67de889.png)
True, so long as the corresponding "Make the server play nice" is labeled BIG PROBLEM

**Comment by joshxg** [comment]
closed by #2839
