### ISSUE TITLE
Add on press logic for selecting records from API search

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2633]
## Is your feature request related to a problem? Please describe.

The basic API workflow requires users to select a patient/prescriber from the list of records which match the given search parameters. 

## Describe the solution you'd like

1. User searches for patient/prescriber.
2. User gets a list of matches.
3. User selects the row in the list which matches the patient/prescriber.
4. The user receives feedback that the patient/prescriber has been added. 

## Implementation

- Add an `onPress` handler to handle user selection.
- Add a popup confirmation on selection.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by wlthomson** [comment]
Fixed by #2652.

**Comment by diegoevangelisti** [comment]
**Testing in progress**

## Testing

- [ ] Selecting a patient record closes the lookup modal and adds that patient to the dispensary patient list.
- [ ] Selecting a prescriber record closes the lookup modal and adds that patient to the dispensary patient list.
