### ISSUE TITLE
TemperatureSync logic: downloading logs

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2640]
## Is your feature request related to a problem? Please describe.

Related issue #2600 

To do all use-cases of the temperature syncing in a single issue is a bit much. This issue will be the code for the actions to scan for sensors

## Describe the solution you'd like

- A `startDownloadingLogs` action
- A `completeDownloadingLogs` action
- A `downloadLogs` action - composition of above two
- A `errorDownloadingLogs` action

## Implementation

- As above

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by mark-prins** [comment]
> This issue will be the code for the actions to scan for sensors

The title and this part of the description do not match up. I'm thinking that it should read *This issue will be the code for the actions to download the logs*

**Comment by joshxg** [comment]
ooooops..

closed by #2646
