### ISSUE TITLE
Temperature sync: full sync

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2641]
## Is your feature request related to a problem? Please describe.

Related issue #2600 

To do all use-cases of the temperature syncing in a single issue is a bit much. This issue will be the code for the actions to scan for sensors

## Describe the solution you'd like

- A `sync` action
- An `updateSyncProgress` action
- A `startResetLogFrequency` action
- A `completeResetLogFrequency` action
- A `errorResettingLogFreqeuncy` action
- A `resetLogFrequency` action - composition of above
- A `startResetAdvertisementFrequency` action
- A `completeResetAdvertisementFrequency` action
- A `errorResetAdvertisementFrequency` action
- A `resetAdvertisementFrequency` action - composition of above
- A `completeSync` action

## Implementation

- As above

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by mark-prins** [comment]
> This issue will be the code for the actions to scan for sensors

I doubt it, based on the title and description.

**Comment by joshxg** [comment]
oops !

closed by #2646
