### ISSUE TITLE
Typo in Payment type constants

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2648]
## Error in mSupply Mobile

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'p.CASH_TRANSACTION_FIELD_KEYS.PAYMENT_TYPE')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e8439a995c24400179228f0?event_id=5e8439a900599c33c20c0000&i=gh&m=ci)

## Stacktrace

    src/widgets/modals/CashTransactionModal.js:263 - CashTransactionModal

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e8439a995c24400179228f0?event_id=5e8439a900599c33c20c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by joshxg** [comment]
@wlthomson any thoughts on this one before I go lookin?

**Comment by wlthomson** [comment]
Hmm, looks like a typo bug in `v4.0.1`. 

Exported as `CASH_TRANSACTION_FIELDS`  (https://github.com/openmsupply/mobile/blob/v4.0.1/src/utilities/modules/dispensary/constants.js).

Imported as `CASH_TRANSACTION_FIELD_KEYS` (https://github.com/openmsupply/mobile/blob/v4.0.1/src/widgets/modals/CashTransactionModal.js).

**Comment by joshxg** [comment]
This seems like it should be a bigger problem then it is, haha

**Comment by joshxg** [comment]
Ah, fixed in this one: https://github.com/openmsupply/mobile/commit/5553c9388ddfe903dbaa6beae368b55c41813ab1#diff-9fbb62761e311f40355db37056fa616477f8e136a7e7fb78e7cdb46be7c98176
