### ISSUE TITLE
Add patient API insurance policy creation logic

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2657]
## Is your feature request related to a problem? Please describe.

When a patient is added to the local database using the lookup API, related insurance policy records also need to be created.

## Describe the solution you'd like

Add lookup API logic for creating insurance policy records.

## Implementation

Add insurance policy record creation logic to existing `lookupApi` helpers.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #2446.

**Comment by wlthomson** [comment]
Fixed by #2660.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile version v5.0.0RC1

- [x] When a prescription is made for a patient retrieved using the API, all associated insurance policies appear in the dropdown list. **-PASS-**
