### ISSUE TITLE
Fix patient API throwing error on default date

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2658]
## Is your feature request related to a problem? Please describe.

An error is thrown if the results of a patient query includes a patient with a default `date_of_birth`  ISO date of `"0000-00-00T00:00:00"`,

## Describe the solution you'd like

Add logic for handling default `date_of_birth` fields.

## Implementation

Add `null` check to `SearchForm` date rendering logic.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #2446.

**Comment by wlthomson** [comment]
Fixed by #2659.

**Comment by DhanyaHerath** [comment]
### Testing 
- [x] Patient search form list renders default date of birth (`00/00/000`) as `N/A`.

![image](https://user-images.githubusercontent.com/29744386/79934484-c0110580-84a6-11ea-972d-1517e4a0468e.png)

It does correctly show up as N/A in the lookup, but once I add the patient to the store, the D/O/B seems to be set to the current date, is that on purpose @wlthomson ?

(Not sure what's going on with the 'e's :) ) 

![image](https://user-images.githubusercontent.com/29744386/79934526-da4ae380-84a6-11ea-837e-7f232be8b9e2.png)

**Comment by wlthomson** [comment]
@DhanyaHerath 

Eep.

That's unexpected behaviour, looks like the record creation logic is using the date default for new patients. Will make an issue for this.

The `"e"` looks like an encoding issue, AFAIK this hasn't come up for data is synced to mobile for other records, so there's something different with how this is being processed at the mobile side or how the data is being processed before sending on the mSupply side. Will also make an issue for this!
