### ISSUE TITLE
Last sync date in navigation bar is showing null

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2666]
## Describe the bug

The last sync date in the navigation bar is dispalying `null`

### To reproduce

1. Have your mobile all set up and initialized.
2. Closed your server
3. Try to sync
4. See error - the text on the navigation bar should read `SYNC ERROR. LAST SYNC null`

### Expected behaviour

null should read the last sync date

### Proposed Solution

This is occurring because the `formatDate` method is expecting a `Date` object rather than the number of ms since unix epoch which it is currently receiving. Wrap `lastSyncTime` in a `Date` constructor before calling `formatDate` as an immediate solution.

### Version and device info

- App version: 4.0 develop
- Tablet model:
- OS version:

### Additional context

I believe this is only occurring in the current 4.0 develop branch

**Comment by wlthomson** [comment]
Looks like this was introduced here: https://github.com/openmsupply/mobile/commit/22d5308314fd11e7a6d5fd7dbd19c2188ee0131a. Looks like it missed the `v4.0.1` cut-off, so shouldn't effect any releases as far as I can tell.

Easy fix, but seems like date might not be granular enough depending on the sync frequency? I guess the idea is that the sync modal displays more time info?

**Comment by wlthomson** [comment]
Fixed by #2832.
