### ISSUE TITLE
Enforce read-only constraints for non-local insurance policies

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2680]
## Is your feature request related to a problem? Please describe.

Insurance policies added via the patient API should not be editable locally.  

## Describe the solution you'd like

- Non-local insurance policies should not be editable.
- If a policy is added to a non-local patient, that policy should be editable.

## Implementation

Add insurance selectors and `PaymentSummary` logic. 

## Describe alternatives you've considered

Alternative is to disallow creating and editing insurance policies for all non-local patients.

## Additional context

See #2675 for background.

**Comment by joshxg** [comment]
@wlthomson Are insurance policies added from the patient API currently editable? That seems like a bit of a problem!

**Comment by joshxg** [comment]
I wasn't able to edit non-local insurance policies. I *think* this issue might be more about making it so non-local are not editable, but local are. I think we just leave it how it is .. I doubt this will ever actually get done until someone wants it 🤣
