### ISSUE TITLE
Supplier Invoice: Remove button unable to trace whether boolean is check or unchecked

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2682]
## Describe the bug

If we checked two items to remove it will show us the remove button and if we unchecked one and keep another as it is then it will not show remove button.

### To reproduce

1. Go to Supplier invoice
2. Create new add few items more than 1
3. Check boolean to remove for two items.
4. Uncheck one and keep another as it is.
5. See Error

### Expected behaviour

Until and unless the boolean is checked for remove. It should show remove button.

### Version and device info

- App version:3.2.2
- Tablet model:emulator

### Additional context

![Screenshot 2020-04-07 at 10 26 59](https://user-images.githubusercontent.com/18479204/78631530-5a285980-78bc-11ea-845b-b651ddba96ad.png)

**Comment by joshxg** [comment]
Consolidating issue into #3213
