### ISSUE TITLE
Supplier Invoice: Unable to enter quantities

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2683]
## Describe the bug
Unable to enter the quantities for some items.

### To reproduce

Steps to reproduce the behaviour:

It's hard to reproduce but i am able to recreate it in emulator twice. While playing with remove at some point it don't allow the users to enter the quantity but not sure. 

### Expected behaviour

Must allow user to enter quantity.

### Version and device info

- App version:3.2.2

### Additional context

https://support.msupply.org.nz/cerb6/profiles/ticket/HW-7643-PL/conversation

**Comment by joshxg** [comment]
This is quite old - sorry it got left behind @anildahalsussol - let me know if this is should still be investigated
