### ISSUE TITLE
Lookup modal request logic may cause unmounted state changes

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2687]
## Describe the bug

The current lookup modal can be closed while querying the API, which can cause updates on unmounted components (or other possible bugs, performance impacts, etc.).

### To reproduce

See https://github.com/openmsupply/mobile/pull/2684#discussion_r405199938.

### Expected behaviour

Modal state should not be updated if unmounted.

### Proposed Solution

Add custom hook for handling fetches and preventing update of unmounted components.

### Version and device info

- App version: `feature/patient-api` branch.
- Tablet model: Android emulator.
- OS version: N/A.

### Additional context

See https://github.com/openmsupply/mobile/pull/2684#discussion_r405199938.

**Comment by wlthomson** [comment]
Fixed by #2687.

**Comment by DhanyaHerath** [comment]
> Fixed by #2687.

I just went on such a loop coming back to this issue thinking I was getting to the PR

**Comment by wlthomson** [comment]
@DhanyaHerath Oops.

![hahaha](https://user-images.githubusercontent.com/43223637/79977651-ba411180-84f2-11ea-82b0-eff6f6a601be.gif)

**Comment by nishaSussol** [comment]
### TESTING
Tested in mobile version v5.0.0RC1

- [x] When looking up a patient or prescriber, no warning is shown about updating state in an unmounted component. **-PASS-**
