### ISSUE TITLE
Can't view customer requisitions

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2704]
## Describe the bug

When viewing customer requisitions, you can't see the table

### To reproduce

1. Go to Customer Requisitions 

### Expected behaviour

Should be able to view customer requisitions

### Proposed Solution

https://github.com/openmsupply/mobile/blob/f4c0604e538e73743d1a4089f959d92ee37109cb/src/pages/dataTableUtilities/getColumns.js#L275-L281

The above column set is an additional one that shouldn't be there, just remove it

### Version and device info

- App version: 4.0.3 develop
- Tablet model: All
- OS version: All

### Additional context

N/A

**Comment by wlthomson** [comment]
Eep!

**Comment by wlthomson** [comment]
Fixed by #2706.

**Comment by DhanyaHerath** [comment]
### Testing - passed
- [x] Customer requisitions page renders correctly.
