### ISSUE TITLE
No 'past' and 'current' toggle for requisitions, supplier invoices, and customer invoices

### ISSUE THREAD

**Issue by edmofro** [openmsupply/mobile#271]
Need to think about whether this is actually a good idea, but it would probably be nice

**Comment by sworup** [comment]
@edmofro @Chris-Petty You mean filter based on date or based on confirmation status?

**Comment by andreievg** [comment]
Removing from dev project for now (until we agree that it's needed)

**Comment by joshxg** [comment]
closed by #XXXX i forgot
