### ISSUE TITLE
Patient history should include date and item directions

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2718]
## Is your feature request related to a problem? Please describe.

Add date and item directions to patient history.

## Describe the solution you'd like

See above.

## Implementation

Add columns, keys to patient history modal.

## Describe alternatives you've considered

N/A.

## Additional context

@craigdrown @Gwalior-84  Feedback from dispensary demo (17/04/20).

**Comment by wlthomson** [comment]
Hmm, adding item directions isn't really feasible without some UX updates (just not enough column space). Initial thought is to use a bottom modal (see stock page). 

I think best way forward is to compromise: will go ahead and add date as a column and will make a new issue for the bottom modal for `v6`.

**Comment by Gwalior-84** [comment]
> 
> 
> Hmm, adding item directions isn't really feasible without some UX updates (just not enough column space). Initial thought is to use a bottom modal (see stock page).
> 
> I think best way forward is to compromise: will go ahead and add date as a column and will make a new issue for the bottom modal for `v6`.

I agree @wlthomson .  Patient directions is a whole new functionality that can't just be squeezed in.

**Comment by wlthomson** [comment]
Fixed by #2834.
