### ISSUE TITLE
Cash on prescriptions should affect the cash register balance

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2720]
## Describe the bug

Receipts for finalised prescriptions should be visible in the cash register.

### To reproduce

1. Create a prescription with a payment.
2. Go to the cash register.
3. Note that no receipt is visible for that transaction.

### Expected behaviour

The receipt should be visible in the register.

### Proposed Solution

From having a quick look, it looks like a possible bug + regression which happened when filtering by payment types was added. The receipt records are being created, but the `paymentType` is not being set (so the record is not displaying in the rego).

### Version and device info

- App version: `v4.0.3`.
- Tablet model: Android (Nexus 10).
- OS version: PC29.

### Additional context

@craigdrown @DhanyaHerath @joshxg Feedback from dispensary demo (17/04/20).

**Comment by craigdrown** [comment]
@wlthomson If I was the customer this would be a "we can't deploy" kind of blocker. Any chance of getting this into the current release (I think this is the only such issue)

**Comment by wlthomson** [comment]
Bumped priority to release blocker and milestoned `v5`.

**Comment by wlthomson** [comment]
Fixed by #2730.

**Comment by ArpitaSussol** [comment]
Tested in 5.0.0-rc1

## Testing

- [ ] Make a new prescription with a payment. The receipt for the payment can be viewed in the cash register (under the correct payment type). - **PASS**
