### ISSUE TITLE
New patient form is locked

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2721]
## Describe the bug

When creating a new patient, the form is locked for editing.

### To reproduce

1. Go to `Dispensary`
2. Press `New patient`
3. See error

### Expected behaviour

The new patient form should be editable.

### Proposed Solution

See above.

### Version and device info

- App version: `feature/patient-api`.
- Tablet model: Emulator (Nexus 10).
- OS version: API29.

### Additional context

Feedback from dispensary demo (17/04/20).

**Comment by wlthomson** [comment]
Fixed by #2731.

**Comment by ArpitaSussol** [comment]
Tested in 5.0.0.rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] When creating a new patient, all fields are editable. - **PASSED**
