### ISSUE TITLE
Update lookup modal table

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2724]
## Is your feature request related to a problem? Please describe.

The lookup modal table should:

- Display column headers.
- Style rows consistently with data table (alternating colours).

## Describe the solution you'd like

Add column headers and row styling.

## Implementation

The lookup modal form uses `FlatList` to render results

- Styles can be added using a conditional in the `renderItem` callback.
- `FlatList` directly supports column headers with `listHeaderComponent`, `stickyHeaderIndices` props (latter isn't documented for `FlatList` but seems to be passed down to the internal virtualised list).

## Describe alternatives you've considered

N/A.

## Additional context

@joshxg @wlthomson Feedback from dispensary demo (17/04/20).

**Comment by joshxg** [comment]
https://github.com/openmsupply/mobile/blob/master/src/widgets/SimpleTable.js this component is really for a simplified table when full DataTable functionality isnt needed

**Comment by joshxg** [comment]
Closed by #3275
