### ISSUE TITLE
Search form field should be focussed on lookup modal being opened

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2725]
## Is your feature request related to a problem? Please describe.

On opening the lookup modal, the top field in the search form should be auto-focussed.

## Describe the solution you'd like

Auto-focus field when component is mounted.

## Implementation

See above.

## Describe alternatives you've considered

N/A.

## Additional context

Feedback from dispensary demo (17/04/20).

**Comment by joshxg** [comment]
Should've used this originally: https://reactnative.dev/docs/textinput#autofocus

Can just have `FormControl` apply to the `index === 0` form component?

**Comment by wlthomson** [comment]
@joshxg Ah yup. I think that's quite an elegant solution and fits with the existing logic nicely.
