### ISSUE TITLE
Reason for stock take can be empty even we have set reasons and there is quantity difference

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2726]
## Describe the bug

While adding a batches for stock take lines in stock take we can close reason modal without entering reason.

### To reproduce

1. Go to Stock take
2. Create stock take and add batches for any item.
3. Put entered quantity which need to different than snapshot quantity.
4. When reason modal pops, then you can simple close it and Fn stock take.

### Expected behaviour

As far as i know if quantity difference and reasons are set then we cannot let it blank.

### Version and device info

- App version:403
- Tablet model:Samsung

Stock take created from tablet.

![Screenshot 2020-04-17 at 17 33 44](https://user-images.githubusercontent.com/18479204/79566924-0d6e2b00-80d3-11ea-8da9-b3a068ba69bc.png)

**Comment by wlthomson** [comment]
@anildahalsussol Did you attach the correct screenshot?

**Comment by bijaySussol** [comment]
@anildahalsussol :

This should be raised against Mobile then desktop?
On either platform - If there is a difference in the snapshot and the quantity - and is there is a reason to put in there Reason must be mandatory.
I think we have done a lot on desktop - and it is OK - I think  - this looks like a Mobile @joshxg - This must be in your range?

**Comment by joshxg** [comment]
It's not quite 100% clear for me sorry. You created a stocktake on mobile, and you were able to enter differences in a stocktake without a reason? How did you do that? Also was this on develop or master?

Regardless, we're looking to change the behavior of reasons to not be mandatory as it makes for a smoother experience for the user, so this bug shouldn't be a problem. Will leave the issue open a little longer so that we can double check, anyway

**Comment by anildahalsussol** [comment]
In mobile while we add a batch, after we enter quantity which is not equal to snapshot quantity we get reason modal.. which we can close without choosing reason.  
Any way if reason is not mandatory then we can ignore this issue. I thought for IC it was mandatory in desktop.. So please feel free to close this ticket if its not mandatory.

**Comment by joshxg** [comment]
@anildahalsussol ah ok. You're right 100% bro - just it happens we spoke about this two days ago about making mobile not have mandatory reasons!!

**Comment by anildahalsussol** [comment]
@joshxg : Ok thanks bro... Closing this issue.
