### ISSUE TITLE
TESTING: Lookup Modal

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2734]
# TESTING 

This is an issue for testing dispensary lookup ("Patient API") functionality added in `v5.0.0`. 

The terminology `"local"` and `"non-local"` is used to differentiate between patient/prescriber records based on whether their supplying store is or is not the current store (i.e. a patient record with a current store matching the mobile store is local, and a patient record with a current store which differs from the mobile store is non-local).

To test, copy and update the following test cases into a comment below.

## Setup

- To access dispensing functionality, `"Uses Dispensary Module` must be enabled in store preferences (done in desktop).
- To access payment and cash register functionality, `"Uses Payment Module"` and `"Uses Cash Register Module"` must be enabled in store preferences  (done in desktop).

### Lookup modal

- [ ] Modal top:
  - [ ] The top of the modal displays a title, separate from the search form and list.
  - [ ] The modal has the title `"Lookup ${recordType}"`, where `recordType` is either `"patient"` or `"prescriber"`.
  - [ ] The modal displays an `X` icon to the right of the title.
  - [ ] The `X` icon closes the modal on press. 
- [ ] Search form:
  - [ ] The left of the modal displays a form. 
  - [ ] The form contains one or more enterable fields.
  - [ ] The form contains a `"Search"` button.
  - [ ] The `"Search"` button performs a record lookup on press.
- [ ] Search list:
  - [ ] The right of the modal displays a list, which contains nothing until a search is performed.
  - [ ] The list is separated from the form by a vertical separator.
  - [ ] The search list displays a spinning loading indicator when a search is performed.
  - [ ] The search list displays one or more records if a search is successful.
  - [ ] Pressing a result row in the search list adds the patient or prescriber and closes the lookup modal.
- [ ] Error modal:
  - [ ] If a search fails, an error modal is displayed in full-screen:
    - [ ] Server is online, but request times out (can replicate by placing a breakpoint in desktop endpoint, e.g. `routes/api/v4/patient`).
    - [ ] Server is online, but request did not match any records.
    - [ ] Server is online, but authentication failed (can replicate this by changing the users password in desktop).
    - [ ] Server is offline.
  - [ ] The error modal displays an error message.
  - [ ] The error modal displays a `"Confirm"` button.
  - [ ] The `"Confirm`" button closes the error modal on press.
  - [ ] When the error modal is closed, the search form is not reset.
  - [ ] When the error modal is closed, the search list is cleared.

### Patient lookup

- [ ] If looking up patients, the search form contains the following fields in the following order:
  - [ ] `"First name"`
  - [ ] `"Last name"`
  - [ ] `"Date of birth"`
  - [ ] `"Personal policy number"`
  - [ ] `"Family policy number"`
- [ ] Looking up a patient by first name matches all patients with first names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches patient records with first names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a patient by last name returns all patients with a last names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches patient records with last names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a patient by date of birth returns all patients with date of birth which matches the given gate.
- [ ] Looking up a patient by personal policy number returns all patients with one or more personal policy number which contains the search string, invariant of letters being lower- or upper-case. E.g. `"person"` matches patients with at least one policy with a personal number such as `"person"`, `"person123`", `"123person"` (including all possible capitalisations).
- [ ] Looking up a patient by family policy number returns all patients with one or more family policy number which contains the search string, invariant of letters being lower- or upper-case. E.g. `"family"` matches patients with at least one policy with a family number such as `"family"`, `"family123`", `"123family"` (including all possible capitalisations).

### Prescriber lookup

- [ ] If looking up prescribers, the search form contains the following fields in the following order:
  - [ ] `"First name"`
  - [ ] `"Last name"`
  - [ ] `"Registration code"`
- [ ] Looking up a prescriber by first name matches all prescribers with first names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches prescriber records with first names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a prescriber by last name returns all prescribers with a last names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches prescriber records with last names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a prescriber by registration code returns all prescribers with registration codes containing the search string, invariant of letters being lower- or upper-case. E.g. `"smith"` which matches the given gate.

**Comment by wlthomson** [comment]
@nmadruga Oops, should have clarified. Testing process is to copy the test cases into a comment (that way it's easier to recycle for later releases!)

## Tests

### Lookup modal

- [x] Modal top:
  - [x] The top of the modal displays a title, separate from the search form and list.
  - [x] The modal has the title `"Lookup ${recordType}"`, where `recordType` is either `"patient"` or `"prescriber"`.
  - [x] The modal displays an `X` icon to the right of the title.
  - [x] The `X` icon closes the modal on press. 
- [ ] Search form:
  - [x] The left of the modal displays a form. 
  - [x] The form contains one or more enterable fields.
  - [ ] The form contains a `"Search"` button.
  - [ ] The `"Search"` button performs a record lookup on press.
- [ ] Search list:
  - [ ] The right of the modal displays a list, which contains nothing until a search is performed.
  - [ ] The list is separated from the form by a vertical separator.
  - [ ] The search list displays a spinning loading indicator when a search is performed.
  - [ ] The search list displays one or more records if a search is successful.
  - [ ] Pressing a result row in the search list adds the patient or prescriber and closes the lookup modal.
- [ ] Error modal:
  - [ ] If a search fails, an error modal is displayed in full-screen:
    - [ ] Server is online, but request times out (can replicate by placing a breakpoint in desktop endpoint, e.g. `routes/api/v4/patient`).
    - [ ] Server is online, but request did not match any records.
    - [ ] Server is online, but authentication failed (can replicate this by changing the users password in desktop).
    - [ ] Server is offline.
  - [ ] The error modal displays an error message.
  - [ ] The error modal displays a `"Confirm"` button.
  - [ ] The `"Confirm`" button closes the error modal on press.
  - [ ] When the error modal is closed, the search form is not reset.
  - [ ] When the error modal is closed, the search list is cleared.

### Patient lookup

- [ ] If looking up patients, the search form contains the following fields in the following order:
  - [ ] `"First name"`
  - [ ] `"Last name"`
  - [ ] `"Date of birth"`
  - [ ] `"Personal policy number"`
  - [ ] `"Family policy number"`
- [ ] Looking up a patient by first name matches all patients with first names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches patient records with first names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a patient by last name returns all patients with a last names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches patient records with last names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a patient by date of birth returns all patients with date of birth which matches the given gate.
- [ ] Looking up a patient by personal policy number returns all patients with one or more personal policy number which contains the search string, invariant of letters being lower- or upper-case. E.g. `"person"` matches patients with at least one policy with a personal number such as `"person"`, `"person123`", `"123person"` (including all possible capitalisations).
- [ ] Looking up a patient by family policy number returns all patients with one or more family policy number which contains the search string, invariant of letters being lower- or upper-case. E.g. `"family"` matches patients with at least one policy with a family number such as `"family"`, `"family123`", `"123family"` (including all possible capitalisations).

### Prescriber lookup

- [ ] If looking up prescribers, the search form contains the following fields in the following order:
  - [ ] `"First name"`
  - [ ] `"Last name"`
  - [ ] `"Registration code"`
- [ ] Looking up a prescriber by first name matches all prescribers with first names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches prescriber records with first names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a prescriber by last name returns all prescribers with a last names containing the search string, invariant of letters being lower- or upper-case. E.g. `"mit"` matches prescriber records with last names `"mitchell"`, `"smith"`, `"kermit"` (including all possible capitalisations).
- [ ] Looking up a prescriber by registration code returns all prescribers with registration codes containing the search string, invariant of letters being lower- or upper-case. E.g. `"smith"` which matches the given gate.

**Comment by nmadruga** [comment]
## Testing - differ from expected
 - The form contains a "Search" button. -FAIL- 
The button text is changed to "Save". #2743
 - The "Search" button performs a record lookup on press. -FAIL UX-
Although using the _return_ key to swap fields from the Registration code will close the window. Better behaviour would be make the search. #2754

**Comment by wlthomson** [comment]
Thanks @nmadruga! Moving to done.

**Comment by wlthomson** [comment]
Priority for `v7` is WHO qualification, so these tests can be bumped to a later minor/major.
