### ISSUE TITLE
Prescription form shows Label as "Invoice undefined" in header title

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#2735]
## Describe the bug

Prescription form shows Label as "Invoice undefined" in header title

### To reproduce

1. Click on Dispensary
2. From patient list, click on dispense option
3. See error

![Screen Shot 2020-04-21 at 11 11 59 AM](https://user-images.githubusercontent.com/58979436/79828941-96ca7980-83c1-11ea-9080-e91735e49f67.png)

### Expected behaviour

Header title should not labelled as "Invoice undefined"

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.0 RC1
- Tablet model: Nexus, API 25
- OS version:

### Additional context

arises while testing #2720

**Comment by wlthomson** [comment]
Thanks for making the issue for this! Also came up in dispensing demo, must have missed it when creating the other issues!

![oops](https://user-images.githubusercontent.com/43223637/79844619-0404fb80-8410-11ea-8807-a231534bfd28.gif)

**Comment by wlthomson** [comment]
Fixed by #2792.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc1

## Testing

- [x] Prescription title is `"Prescription X"`, where `X` is the serial number of the invoice. **--PASS--
