### ISSUE TITLE
Patient lookup search button should be titled 'Search' 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2743]
## Describe the bug

Patient lookup search button is named 'Save' - I think it would make more sense as 'Search'?
![image](https://user-images.githubusercontent.com/29744386/79934221-277a8580-84a6-11ea-804e-96ef6d6d5401.png)

### To reproduce

1. Go to Dispensary
2. Click on Lookup Patient
3.Look at search button 

### Expected behaviour

Should read 'Search'
### Proposed Solution

Change string to 'Search' string?

### Version and device info

- App version: 5.00.RC1
- Tablet model: 
- OS version:

**Comment by wlthomson** [comment]
Fixed by #2819.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Lookup modal button reads `"Search"` (NOT `"Save"`). **-- PASS**
