### ISSUE TITLE
No message showing up when looking up a patient/prescriber that doesn't exist

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2744]
## Describe the bug

This happened in Dispensary module, trying to look up for a patient or prescriber using the existing modal. When searching for a non existing patient (entering a First Name/Last Name), there is no modal with a message explaining ` "No matching records found"`

![searchPatientFailed](https://user-images.githubusercontent.com/32987464/79934060-bc30b380-84a5-11ea-865c-85209f9e114c.gif)

### To reproduce

1. Go to 'Dispensary' module
2. Click on 'Lookup patient'
3. Search for a patient that doesn't exist.
4. There is no feedback messages like ` "No matching records found"`

Repeat the process from step 2 but now Click on  'Lookup prescriber'. The result should be similar.

### Expected behaviour

There should be a message saying  `"No matching records found"`

### Proposed Solution

N/A

### Version and device info

- App version: v5.0.0-rc1
- Tablet model: Testing in AVD
- OS version: Android 9.0 API 28 

### Additional context

While testing #2684

**Comment by wlthomson** [comment]
@diegoevangelisti Closing as fixed!
