### ISSUE TITLE
Items currently being added to a prescription show on patient history

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2746]
## Describe the bug
If I check patient history while creating a prescription for that patient, it shows the items I am currently issuing in the list. 

I find that kind of confusing?
Current prescription: 
![image](https://user-images.githubusercontent.com/29744386/79936010-6e6a7a00-84aa-11ea-83e6-61e73c3a3f8f.png)

Patient history accessed through prescription: 
![image](https://user-images.githubusercontent.com/29744386/79935988-5d216d80-84aa-11ea-8bca-7f6ec09af17a.png)

### To reproduce

1. Create a prescription (most easily seen if the patient has no previous history) 
2. Add some items to the prescription 
3. Click on patient history 
4. Note that the items you're prescribing show up in history 

### Expected behaviour

Not a huge bug and maybe this is expected behaviour, but I find it confusing for the items I am prescribing to show up in history (I haven't prescribed them yet!) particularly since there is no date shown 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.00.RC1
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
nice - looks like an oversight. Should be changed to constrain batches to finalised transactions. Also there's an issue to add a date, somewhere

**Comment by katherine-sussol** [comment]
Closed with #3937
