### ISSUE TITLE
Unintended behaviour when adding a patient without a DOB via lookup API

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2747]
## Is your feature request related to a problem? Please describe.

When adding a patient via the lookup API, if that patient has no DOB, the patient record will be updated with the DOB set with the current date. This could cause problems on sync.

## Describe the solution you'd like

Allow date of birth to be `null` if explicitly set.

## Implementation

Creation logic will need to be updated to allow a `null` DOB (if DOB needs to be enforced elsewhere, this might need to be handled explicitly before `createRecord`).

## Describe alternatives you've considered

Leave as is? 

## Additional context

N/A.

**Comment by wlthomson** [comment]
Fixed by #2794.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc2

### Testing

- [x] When a patient with a `"N/A"` date of birth is added via lookup, the patient details are correct in the dispensary table. --**PASSES**--
