### ISSUE TITLE
Outgoing sync error related to dispensing records

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2750]
## Describe the bug

When syncing while editing a prescription, pushing to the server fails.

From bugsnag:

```
[{"SyncID":"53119d40844311eab983310fd05e0878","RecordType":"transact","RecordID":"dd3d6430b2df11e998aa6d526208ddbc","SyncType":"D","StoreID":"69090277A20DEB43B39DA7F56C8769D2"},{"SyncID":"5311c451844311eab983310fd05e0878","RecordType":"number_reuse","RecordID":"5311c450844311eab983310fd05e0878","SyncType":"I","StoreID":"69090277A20DEB43B39DA7F56C8769D2","Data":{"ID":"5311c450844311eab983310fd05e0878","name":"customer_invoice_number_for_store_69090277A20DEB43B39DA7F56C8769D2","number_to_use":"19"}},{"SyncID":"53121270844311eab983310fd05e0878","RecordType":"transact","RecordID":"f61b9ff0e50a11e9a27e19a6295543af","SyncType":"D","StoreID":"69090277A20DEB43B39DA7F56C8769D2"},{"SyncID":"53123981844311eab983310fd05e0878","RecordType":"number_reuse","RecordID":"53123980844311eab983310fd05e0878","SyncType":"I","StoreID":"69090277A20DEB43B39DA7F56C8769D2","Data":{"ID":"53123980844311eab983310fd05e0878","name":"customer_invoice_number_for_store_69090277A20DEB43B39DA7F56C8769D2","number_to_use":"21"}},{"SyncID":"d37b42c0844211eab983310fd05e0878","RecordType":"transact","RecordID":"d37a5860844211eab983310fd05e0878","SyncType":"D","StoreID":"69090277A20DEB43B39DA7F56C8769D2"},{"SyncID":"59b830a0844311eab983310fd05e0878","RecordType":"clinician","RecordID":"757BCC670CC05C4493F231E73B023F52","SyncType":"U","StoreID":"69090277A20DEB43B39DA7F56C8769D2","Data":null},{"SyncID":"530f7a60844311eab983310fd05e0878","RecordType":"number_reuse","RecordID":"530f5350844311eab983310fd05e0878","SyncType":"D","StoreID":"69090277A20DEB43B39DA7F56C8769D2"},{"SyncID":"a85e77a0844311eab983310fd05e0878","RecordType":"nameInsuranceJoin","RecordID":"a85e2980844311eab983310fd05e0878","SyncType":"U","StoreID":"69090277A20DEB43B39DA7F56C8769D2","Data":{"ID":"a85e2980844311eab983310fd05e0878","insuranceProviderID":"C28688478F6C3F448AF9C020D466FF14","nameID":"44045D030ACC08449E97958A6B44586E","isActive":"true","policyNumberFamily":"F1","policyNumberPerson":"A1","type":"personal","discountRate":"25","expiryDate":"2020-05-22T00:00:00","policyNumberFull":"F1-A1","enteredByID":"4EBF20D4F42F49409F60BF2626AA7B24"}},{"SyncID":"6dac38e0844311eab983310fd05e0878","RecordType":"trans_line","RecordID":"6dabeac0844311eab983310fd05e0878","SyncType":"D","StoreID":"69090277A20DEB43B39DA7F56C8769D2"},{"SyncID":"68064ca0844311eab983310fd05e0878","RecordType":"transact","RecordID":"6805b060844311eab983310fd05e0878","SyncType":"D","StoreID":"69090277A20DEB43B39DA7F56C8769D2"}]
```

Note that the `Data` field is `null` for the clinician record:

```
{"SyncID":"59b830a0844311eab983310fd05e0878","RecordType":"clinician","RecordID":"757BCC670CC05C4493F231E73B023F52","SyncType":"U","StoreID":"69090277A20DEB43B39DA7F56C8769D2","Data":null}
```

Update: investing other snags, other records can be found which also have `null` data (`"transact"` and `"trans_line"`). Common denominator seems to be prescriptions?

Another possibly related snag (body is not included, consists of a long list of record IDs):

```
{"lines":[{"description":"Cannot delete sync record(s) - at least one is locked"}],"error":"Cannot delete sync record(s) - at least one is locked"}
```

New theory is that there may be some record locking occurring while prescribing that is causing sync to fail when triggered while the prescription window is open?

### To reproduce

Unable to reproduce so far, but the error first appeared after the following steps:

1. Lookup a prescriber using the lookup API.
2. Create a prescription for a patient and select the new prescriber.
3. Without cancelling or finalising the prescription, manually trigger sync.
4. See error (maybe).

### Expected behaviour

Push dispensary records without errors.

### Proposed Solution

TO DO.

### Version and device info

- App version: `v5.0.0-rc1`
- Tablet model: Android emulator
- OS version: Unknown

### Additional context

@DhanyaHerath

**Comment by joshxg** [comment]
@wlthomson wondering - are these ones : https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e9fce699791ed001709f7ad?event_id=5e9fce69005a42d3ca740000&i=em&m=nw from taking too long? Might get annoying if that's the case (not a biggy though)

**Comment by wlthomson** [comment]
Yup, maybe worth removing the snagging for timeouts?

**Comment by joshxg** [comment]
I dunno, maybe just leave it in for a version and see how it goes ? 🤣

**Comment by wlthomson** [comment]
Update:

After further investigation, this seems like it may be related to records being locked when attempting to sync while editing a prescription (may still be related to the lookup API, but looks like it might not be limited to it). Have updated description.
