### ISSUE TITLE
Lookup API results list includes non-UTF8 characters

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2751]
## Describe the bug

When looking up patients/prescribers using the lookup API modal, the results list sometimes includes non-ASCII characters (rendered as a `?` symbol):

![#2751-lookup-api-characters](https://user-images.githubusercontent.com/43223637/80159606-98917880-861f-11ea-87bc-9bbdfa09496e.jpg)

### To reproduce

1. Sync to an IC data file.
2. Lookup a patient with a name containing a non-ASCII character, (e.g. `"é"`).
3. See error.

### Expected behaviour

All characters should be correctly displayed.

### Proposed Solution

Maybe a localisation issue? Doesn't seem to occur with normal sync, so maybe @joshxg, @andreievg, @Chris-Petty have some thoughts?

### Version and device info

- App version: `v5.0.0-rc1`
- Tablet model: Android emulator
- OS version: API29

### Additional context

N/A.

**Comment by Chris-Petty** [comment]
Are you able to see give an example, say using the primary key to see what it's supposed to look like on desktop vs how mobile renders it?

**Comment by andreievg** [comment]
This is weird, no idea how they can enter non UTF-8 characters in the UI, this would also affect our sync system if that's the case.

**Comment by wlthomson** [comment]
Update: confirmed that it seems to be an encoding issue with non-ASCII characters (e.g. `"é"`). 

Screenshot added.

**Comment by wlthomson** [comment]
Update: revisiting this as part of `5.1.0` triaging. 

Seems that this is an issue on the desktop side.

Looks like the current structure is sending lookup HTTP data in ISO-8859-1 (confirmed not occurring for normal sync). I'm guessing there's some code in the existing sync logic to do a UTF-8 conversion that isn't being run for the patient/prescriber routes.

Have confirmed that explicitly encoding the patient and prescriber responses in UTF-8 fixes the issue, so going to go ahead and close this and open an issue on desktop repo.
