### ISSUE TITLE
Hardware back button is double handled

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2752]
## Describe the bug

Pressing the hardware backbutton is being double handled.

### To reproduce

1. Go to a page i.e. customer invoices page
2. Click on the hardware back button
4. See error [Popped two routes off the stack. If on customer invoices page, exits the app]

### Expected behaviour

Should only go back once

### Proposed Solution

`backHandler` in `utilities/navigation` needs to return `true`, which means it has handled the event, otherwise if returns a falsey value, `react-navigation` default kicks in (poping the stack again). 

### Version and device info

- App version: 4.0.0-RC2
- Tablet model: All 
- OS version: All

### Additional context

I remember fixing this already, must have lost hte commit somehow!

**Comment by wlthomson** [comment]
@joshxg Thanks! I agree needs to go into `v5.0.0` as impacts user experience pretty badly.

**Comment by wlthomson** [comment]
Fixed by #2775.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile version v5.0.0RC2

### Tests
- [x] Pressing the hardware back button navigates to previous page. **-PASS-**
