### ISSUE TITLE
Dispensary lookup results not resetting on empty search

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2755]
## Describe the bug

Trying to use a filter to search for Prescribers one first time works.
The problem is making a search with a filter after a search without filters is done (which results in a query with all prescribers.

![lookupFilterBug](https://user-images.githubusercontent.com/16461988/80044717-7d5c3580-8559-11ea-918e-d3818bf98058.gif)

The same problem might be happening on the Lookup for patients too. 

### To reproduce

1. Go to Dispensary
2. Click on the Prescribers tab
3. Click on Lookup prescriber
4. Leave all fields blank and "Search"
5. The result should show all Prescribers
6. Enter a name on "First name" and "Search"
7. The result is not filtering only prescribers with the same "First name"

### Expected behaviour

The filters should be included in the result when the "Search" is clicked refreshing the result list (after a search for all prescribers was done without filters). 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.0-RC1
- Tablet model: Emulator of Nexus 10
- OS version: Android 4.4.4

### Additional context

N/A

**Comment by nmadruga** [comment]
Found more info about this problem - ONLY happens if searching for a result that doesn't matches anything.

If you check on the gif I first searched for "Nicole" and no results were presented, then after searching without using filters the result is presented and again searching for "Nicole" keeps the same previous result, which is errouneous.

**Comment by wlthomson** [comment]
Awesome, replicated and fixing now. Thanks @nmadruga!

**Comment by wlthomson** [comment]
Fixed by #2782.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v5.0.0RC2

- [x] Searching for a non-existent patient displays the error modal (`"No records found"`) **-PASS-**
- [x] Searching for a non-existent prescriber displays the error modal (`"No records found"`) **-PASS-**
- [x] After searching for a non-existent patient, no records are displayed from previous queries. **-PASS-**
- [x] After searching for a non-existent prescriber, no records are displayed from previous queries. **-PASS-**
