### ISSUE TITLE
Lookup Modal not showing error message when server is not accessible

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2757]
## Describe the bug

Testing the Lookup modal for Prescribers and mocking 4 different problems o the server:

1. Server is online, but request times out (can replicate by placing a breakpoint in desktop endpoint, e.g. routes/api/v4/patient).
2. Server is online, but request did not match any records.
3. Server is online, but authentication failed (can replicate this by changing the users password in desktop).
4. Server is offline.

Expectations: The error modal displays an error message.
Reality:
For problem 1 and 4
<img width="749" alt="Screen Shot 2020-04-23 at 3 54 46 PM" src="https://user-images.githubusercontent.com/16461988/80057857-c329f580-857b-11ea-9a2d-8ff66b7b37ca.png">
 
For problems 2 and 3
<img width="749" alt="Screen Shot 2020-04-23 at 4 02 05 PM" src="https://user-images.githubusercontent.com/16461988/80057882-cfae4e00-857b-11ea-99f4-f199bf3311b6.png">

### To reproduce

1. Go to Dispensary
2. Click on the Prescribers tab
3. Click on Lookup prescriber
4. To replicate problem 1 - Add breakpoint on Desktop routes_api line 13
5. Leave all fields blank and "Search" => Abort message displays
6.  To replicate problem 2 - enter on fields first and last name impossible strings =>Nothing
7.  To replicate problem 3 - change the user password on Desktop (Admin -> Edit users)
8. Leave all fields blank and "Search" => Nothing is displayed
9. To replicate problem 4 - stop the server on Desktop (Admin -> preferences -> server)
10. Leave all fields blank and "Search" => Abort message displays

### Expected behaviour

The error modal displays an error message.

### Proposed Solution

N/A

### Version and device info

- App version: 5.0.0-RC1
- Tablet model: Emulator of Nexus 10
- OS version: Android 4.4.4

### Additional context

N/A

**Comment by wlthomson** [comment]
@nmadruga Hm, this doesn't seem to be consistent with @diegoevangelisti test results. Will see if I can replicate.

Just as an aside, might be a good idea to upgrade your emulator OS (looks like you're using a pretty old version of Android!).

**Comment by nmadruga** [comment]
> looks like you're using a pretty old version of Android

I believe that's the minor version required for mSupply mobile to run. That's why I'm using this one. It might be why the problem is happening. I can try again on another one that I have with version 5.1. Exactly to test if we need to update the minor version of mSupply mobile or not.

https://docs.msupply.foundation/en:mobile:user_guide:getting_started#recommended_specifications

**Comment by wlthomson** [comment]
Yeah, I recall we've had some other problems with `4.4` before. Might be worth bumping the minimal supported version. For now could you try to replicate with something a bit higher, e.g. `API28`? Just to confirm whether this is partially related to Android stuff or completely unrelated.

**Comment by joshxg** [comment]
There's currently no issues that I know of with `4.4` (they've all been fixed) - it does increase development time to keep supporting that version, but afaik, there are plenty of customers who are still using tablets with that version, so we should keep supporting it until it really becomes a real problem unfortunately 🤣

**Comment by diegoevangelisti** [comment]
@nmadruga @wlthomson 

Maybe this can help! 
Regarding Problem 3, this is the error message that I'm getting (same as expected according to the test case) - I just changed the user's pass (user: `zam` in my case) and then tried to look up a patient/prescriber:

![2020-04-23 16 55 07](https://user-images.githubusercontent.com/32987464/80061623-ef4a7400-8585-11ea-8ad9-e08a74cc866c.jpg)

**Comment by wlthomson** [comment]
> There's currently no issues that I know of with `4.4` (they've all been fixed) - it does increase development time to keep supporting that version, but afaik, there are plenty of customers who are still using tablets with that version, so we should keep supporting it until it really becomes a real problem unfortunately rofl

Thanks for info! I think even though there are no known outstanding issues, just raising the question of whether it's worth continuing to support it or bump up our requirements? I agree with supporting as many devices as possible, but I think a good balance would be something a bit higher (maybe `6.0`).

Maybe missing something, but I think users will be OK with upgrading a couple of versions? Just to give a bit of context on my thinking, `4.1` isn't supported by the play store, and looks like `4.4` only accounts for ~2% of Android devices worldwide (reference: https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide/). Thoughts?

**Comment by wlthomson** [comment]
@diegoevangelisti Thanks for info.

@joshxg @nmadruga Thinking about it, it looks like there are bugs in how the modal handles some response codes regardless of versions, so it doesn't really make much difference anyway!

**Comment by wlthomson** [comment]
@nmadruga Some fixes have been made around the lookup modal. Can you still replicate all of this on latest `develop`?

**Comment by nmadruga** [comment]
@wlthomson I'm back. I planned to test yesterday but that sync just wasn't working and I moved on to other things I needed to work on. So today I tested again, and the result for some points are working well now.

## Setup
Emulator with minimum required version of API 19 Android 4.4.4.

## Testing
1. Server is online, but request times out **-FAIL-** Still showing the Aborted message
2. Server is online, but request did not match any records. **-PASS-** 😆 
 - Although the Aborted message still appeared when I do a search for ALL patients after the "No records found" message. Tried again and no problem. I suspect it can be same reason as problem 1 🔝
<img width="788" alt="Screen Shot 2020-04-29 at 2 06 19 PM" src="https://user-images.githubusercontent.com/16461988/80555177-9e25fe80-8a23-11ea-8602-b5dc98184ef6.png">
3. Server is online, but authentication failed. **-??-** 

 - Changing the password doesn't block the user to query anymore (is this a concern?). mSupply Mobile will only ask for the password again after I was idle for a minute or so.
4. Server is offline. **-PASS-**
![Screen Shot 2020-04-29 at 2 07 59 PM](https://user-images.githubusercontent.com/16461988/80555898-d4647d80-8a25-11ea-966b-bf36b1617557.png)

**Comment by wlthomson** [comment]
@nmadruga Welcome back! That all looks good (I think the authentication delay is probably mSupply caching, and in reality a user wouldn't be changing their password so frequently!) I think the `"Aborted"` message is the remaining problem, so will make a fix for this today!

**Comment by wlthomson** [comment]
@nmadruga could you do a quick test on #2811? Should hopefully fix the request timeout error bug!

**Comment by wlthomson** [comment]
Closing as can't replicate on latest `develop`. @nmadruga feel free to reopen if still occurring for you!
