### ISSUE TITLE
Crash on customer requisition use required/suggested quantity

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2758]
## Describe the bug

The app crashes when working on a `"Customer Requisition"` and pressing `"Use Required Quantity"` and  `"Use Suggested Quantity"` . In two different attempts, these following messages showed up (2 different errors, check below):

Customer requisition before clicking on `"Use Required Quantity"`:
![Screen Shot 2020-04-23 at 4 08 49 PM](https://user-images.githubusercontent.com/32987464/80058209-c96ca180-857c-11ea-86f0-6e3c95ae8c82.png)

  - 1st attempt:
![Screen Shot 2020-04-23 at 4 09 06 PM](https://user-images.githubusercontent.com/32987464/80058241-dd180800-857c-11ea-9e90-05741e3526a9.png)

  - 2nd attempt:
Trying again, I didn't get that error message, but the app freezes and when trying to reload, this is the error:

![Screen Shot 2020-04-23 at 4 14 19 PM](https://user-images.githubusercontent.com/32987464/80058497-8101b380-857d-11ea-97cb-332a9d8769d1.png)

- Pressing the `"Use Suggested Quantity"` button. This is the error message retrieved after trying to reload the page:

![Screen Shot 2020-04-23 at 4 20 00 PM](https://user-images.githubusercontent.com/32987464/80058887-8c091380-857e-11ea-8059-58b36250caa1.png)

### To reproduce

1. Go to 'Customer Requisitions' -> Select a 'Customer Requisition'
2. Click on the button: `"Use Required Quantity"`.

Repeat for `"Use Suggested Quantity"`.

### Expected behaviour

The app shouldn't crash and update the Supplied quantity (if necessary).

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc1
- Tablet model: AVD
- OS version: Android 9.0 API 28

### Additional context

This happened while testing #1244.

**Comment by wlthomson** [comment]
Fixed by #2774.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] App does not crash on setting customer requisition supplied quantity to requested quantity.
- [x] App does not crash on setting customer requisition supplied quantity to suggested quantity.
