### ISSUE TITLE
Current stock page popup doesn't close when focus is changed to the search bar 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2760]
## Describe the bug
From the test cases described in https://github.com/openmsupply/mobile/issues/1245: "Pop up should close  when focusing the search bar when it is open"  - the popup window remains open. 

![image](https://user-images.githubusercontent.com/29744386/80060026-a85a7f80-8581-11ea-9d25-9366454c70c7.png)

### To reproduce

1. Go to Current stock 
2. Click on a row - this should open the popup 
3. Click on the search bar to change focus
4. The popup doesn't close 

### Expected behaviour

According to the test case, should close popup 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0.RC1
- Tablet model: Emulator - Galaxy Tab A 
- OS version: Android 8.0

**Comment by wlthomson** [comment]
@DhanyaHerath Hm, can't seem to replicate this! Just to get a bit more info, are you on an emulator or tablet (and what Android version)?

**Comment by DhanyaHerath** [comment]
Sorry @wlthomson super bad documentation from me, updated issue now

**Comment by wlthomson** [comment]
@DhanyaHerath All good, thanks!

**Comment by joshxg** [comment]
Can't recreate this
