### ISSUE TITLE
Lookup patient with DOB filter result in patients with 'Invalid dates'

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#2761]
## Describe the bug

Trying to search for patients with data of birth in a database full of patients with 'Invalid date' is not showing the result properly. Either the results for the correct day are in the bottom and I can't reach it or not even filtered in the result.

mSupply datafile used: Ivory Coast mSupply Master. Sync store: CSRDuokro

### To reproduce

1. Go to Dispensary
2. Click on the Patients tab
3. Click on Lookup patients
4. Add one existing date of birth and click "Search"
5. The result is showing many patients with Invalid date

### Expected behaviour

The result should include the filtered ones

### Proposed Solution

Maybe not list users with Invalid date, or change the order so the ones matching the filter appear first, in case showing the ones with Invalid date is required.

### Version and device info

App version: 5.0.0-RC1
Tablet model: Emulator of Nexus 10
OS version: Android 5.1 (API 22)

### Additional context

N/A

**Comment by wlthomson** [comment]
Fixed by #2818.
