### ISSUE TITLE
Finalising supplier invoice doesn't update the number of unfinalised transactions on the navigation screen 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2764]
## Describe the bug

Finalising supplier invoice doesn't update the number of unfinalised transactions on the navigation screen when tapping on the back icon (either the mSupply one or the tablet one). For the number to update I need to go back on the tablet screen (tapping on the circle) and cliking on mSupply icon again 

### To reproduce

1. Login to a mobile site that have un-finalising  supplier invoice.
2. Click on supplier invoice and finalise one
3. go back to the navigation screen

### Expected behaviour

I think the number of unfinalised transaction should update to reflect the number of actual un-finalised transaction 

### Screenshot
Screenshots from test CSR NZERE
Initial state
![image](https://user-images.githubusercontent.com/11624516/80144820-31bb8300-857d-11ea-8f55-b42f22f6f846.png)

![image](https://user-images.githubusercontent.com/11624516/80145013-7c3cff80-857d-11ea-94b9-4b4a27e6f814.png)

Finalising invoice 38 and clicking on either back button (mSupply or tablet)

![image](https://user-images.githubusercontent.com/11624516/80145319-ff5e5580-857d-11ea-9cf5-6dd031b25864.png)

End result : Still showing 4 un-finalized transactions when there are only 3 left
![image](https://user-images.githubusercontent.com/11624516/80145760-af33c300-857e-11ea-9c9e-690fd9bb79b2.png)

If I click on the back button when on the Navigation screen to go back to tablet screen and clicking on the mSupply again then it update the number correctly

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.0RC1
- Tablet model: Galaxy tab A (SM-T510)
- OS version: Android

**Comment by joshxg** [comment]
Hmm, this is an unintended consequence of the navigation change, which has reduced the number of full-app-wide re-renders. Thanks alain!

**Comment by wlthomson** [comment]
Have replicated.

Think this is worth getting into `v5.0.0` and good excuse to get familiar with the new navigation changes!

**Comment by wlthomson** [comment]
Have replicated.

Think this is worth getting into `v5.0.0`, so will get onto it now.

**Comment by wlthomson** [comment]
Fixed by #2808.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v5.0.0RC3
- [x] Badges refresh correctly on returning to menu page. **-PASS-**
