### ISSUE TITLE
Supplier credit columns are not translated in french

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2766]
## Describe the bug

The columns of the modal when returning stock from the current stock page are not translated in french. It is fine when returning from a supplier invoice. After I opened the return stock modal from a supplier invoice and went back to opening one from the Current Stock, it was displaying correctly in french. Possibly another symptom of a refresh issue (See #2764 and #2765)

### To reproduce

Log as a french user. Your supplier credit functionality must be activated (see #2336)
1. Go to "Stock Actuel"
2. Click on a icon of column "Retourner"
3. See error. Column of the modal are in english

### Expected behaviour

Column titles must be in french when log as a french user

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0RC1
- Tablet model: 
- OS version:

**Comment by alainsussol** [comment]
As @joshxg said in #2764 and #2765 this may be a casualtie of the navigation change. Happy to close this if related to the same problem.

**Comment by joshxg** [comment]
I think it is related, but these have all been guesses, so lets leave this open to check :) Thanks so much @alainsussol ❤️

**Comment by wlthomson** [comment]
Confirmed fixed in `v5.0.0-rc3` :tada:.
