### ISSUE TITLE
Stocktake manage page confirm modal does not open/close on selection/deselection

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2768]
## Describe the bug

Issues found while testing #1241. Section: COLUMNS -> SELECTED.
When opening the Stocktake Manage Page, the confirmation modal opens up right immediately (not waiting for me to select and item), and then when unselecting an item, it doesn't disappears. (as expected). 
**NOTE**: Same is happening with program stocktakes.
See example below:

![confirmModalStocktake](https://user-images.githubusercontent.com/32987464/80151718-9c68cf00-860e-11ea-8c07-948a308dc296.gif)

### To reproduce

1. Go to 'StocktakeManagePage' and create a new stocktake or open a current one.
4. See confirmation modal opens immediately (error).

### Expected behaviour

The confirmation modal should open when selecting an item and close when unselecting all.

### Proposed Solution

N/A

### Version and device info

- App version: v5.0.0-rc1
- Tablet model: AVD
- OS version: Android 9.0 - API 28

### Additional context

While testing #1241

**Comment by wlthomson** [comment]
Thanks @diegoevangelisti! 

Can replicate and have confirmed, only concern is whether this may be intended behaviour. Looks like the `hasSelection` param was removed intentionally [here](https://github.com/openmsupply/mobile/commit/aca393301078d493822ac08b47b49efadc34d13a#diff-469f92e7b24eca181ed4c281bbaf9801) for [this issue](https://github.com/openmsupply/mobile/issues/1343). Issue refers to `StocktakeEditPage`, but think it is also including `StocktakeManagePage`:

> Bottom confirm modal goes away when nothing is selected, but should always stay

My guess is that the tests need updating? If not, fix is easy, but someone with more knowledge will be able to confirm the intended logic here.

@andreievg @Chris-Petty @sworup Question: can anyone confirm that a mobile stocktake should be able to be confirmed without any items selected?

**Comment by andreievg** [comment]
I think this is a 'nice to have' (low priority).

**Comment by wlthomson** [comment]
@andreievg i agree, but just to confirm, the "nice to have" is the confirm modal only appearing when selected? Looks like modal behaviour previously was as described, but recently has been intentionally made to always be open, so just trying to figure out what the "desired behaviour" is?

**Comment by wlthomson** [comment]
Looks like this isn't something we are too worried about! Bumping to `v6`.

**Comment by wlthomson** [comment]
General concensus seems to be that this isn't too much of a worry at this stage. Bumping to `v6`.

**Comment by joshxg** [comment]
As far as I can tell this is expected behaviour
