### ISSUE TITLE
Save button gets disable when entering policy numbers in Dispensary -> Lookup patient/prescriber

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2769]
## Describe the bug

In Dispensary module -> Lookup patient/prescriber, a search can be performed using the policy number/s. I found that when filling `Personal policy number` and `Family policy number` inputs, the Save` button automatically gets disabled. See it in the example below:

Policy (previously created):
![Screen Shot 2020-04-22 at 4 46 10 PM](https://user-images.githubusercontent.com/32987464/79942060-1176c000-84ba-11ea-89cc-27ce3a4536ce.png)

Error:

![SEARCHPatient2](https://user-images.githubusercontent.com/32987464/79942007-eab88980-84b9-11ea-8b54-3f1f04a89197.gif)

### To reproduce

1. Go to 'Dispensary'
2. Create a new policy to an internal or external patient.
3. Go back to Dispensary and click on `Lookup patient`
4. Enter the policy number/s.
5. See error (`Save` button disabled).

### Expected behaviour

The save button should be enable.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc1
- Tablet model: AVD
- OS version: Android 9.0 API 28

### Additional context

While testing #2678

**Comment by wlthomson** [comment]
Insurance policy fields have been merged, so I think this can be closed.

@diegoevangelisti Can you check on latest `develop` to see if you can still replicate?

**Comment by diegoevangelisti** [comment]
Checking right now @wlthomson, I will keep you updated regarding this one

**Comment by diegoevangelisti** [comment]
It is working well now @wlthomson, I mean, the button doesn't get disable, but it's not finding any records when I'm entering the policy number (a different issue I guess?)

**Comment by wlthomson** [comment]
@diegoevangelisti That's a problem if it's not hitting any records! Could you give me an example (on latest `develop`)?

**Comment by diegoevangelisti** [comment]
Yes, sure. Please take a look at this example below:
I tried first with 1111 (`Personal Policy number` -as you would see in the gif below-), then with 2222 (`Family policy number`) and finally both `11112222` and `1111 2222` but for all of them `No records found` was the answer.

Existing policy:

<img width="869" alt="Screen Shot 2020-04-28 at 4 31 25 PM" src="https://user-images.githubusercontent.com/32987464/80447775-804a9200-896e-11ea-9002-77de8ec6b7f4.png">

Filtering by Policy number:

![policyNumberNoFound](https://user-images.githubusercontent.com/32987464/80447807-948e8f00-896e-11ea-839c-8a07b6ebd114.gif)

**Comment by wlthomson** [comment]
@diegoevangelisti Just to double check, is the insurance policy you are searching for synced to desktop?

**Comment by diegoevangelisti** [comment]
Hi @wlthomson, checking that right now, will keep you updated soon

**Comment by wlthomson** [comment]
@diegoevangelisti I could replicate on the old structure, but can't as of the fix to #6203. I made an issue for reference (and attached the commit).

**Comment by wlthomson** [comment]
Going to go ahead and close this one!
