### ISSUE TITLE
Stocktake page: Sorting is missing from Program column

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#2773]
## Describe the bug

Stocktake page: Sorting is missing from Program column

### To reproduce

1. Go to Stocktake
2. Scroll down to Program column
4. See error. Sorting is missing
![Screen Shot 2020-04-24 at 1 03 34 PM](https://user-images.githubusercontent.com/58979436/80185432-0ba0ec00-862c-11ea-86f4-f778f1b8697b.png)

### Expected behaviour

Sorting should be present

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0 rc1
- Tablet model:
- OS version:

### Additional context

arises while testing #1240

**Comment by wlthomson** [comment]
Just a one-liner change in `getColumns`, I think!

**Comment by wlthomson** [comment]
@ArpitaSussol Thanks! 

Btw, no need to worry about assigning when you make the issue! A mob dev will have a look at all the new issues and milestone, assign for you (if I'm not getting to them fast enough, let me know!)

**Comment by wlthomson** [comment]
Fixed by #2785.

**Comment by ArpitaSussol** [comment]
Tested in V5.0.0 rc2
