### ISSUE TITLE
Batch Icon on finalised stocktake is unresponsive

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2779]
## Describe the bug

On a finalised Stocktake, nothing happens when clicking on the Batch icon. So cannot see the batch infos.

![image](https://user-images.githubusercontent.com/11624516/80227527-beb51980-861b-11ea-88aa-01d11f4c4b3b.png)

### To reproduce

1. Go to Stocktake, 
2. Click on Archives, Click a finalised stocktake  
3. Click on the batch icon
4. See error. Nothing happens.

### Expected behaviour

I assume that Batch info should be displayed even when the Stocktake is finalised

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v500RC1
- Tablet model:  Galaxy tab A (SM-T510)
- OS version: Android

**Comment by wlthomson** [comment]
Oops! This was mostly likely introduced by me with changes to `DataTableRow` icon disabling. 

Replicated and relatively straightfoward fix.

**Comment by wlthomson** [comment]
Fixed by #2784.

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Can view stocktake batch details for finalised stocktakes. **--PASS--**
