### ISSUE TITLE
Incorrect D.O.B in retrieved patient using the `Lookup patient` in Dispensary

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2790]
## Describe the bug

When looking for a Patient in Dispensary module, the result is not showing the correct D.O.B.
Example:

D.O.B: 1 Jan 2001
<img width="1121" alt="Screen Shot 2020-04-28 at 4 55 03 PM" src="https://user-images.githubusercontent.com/32987464/80448636-0962c880-8971-11ea-8c9e-41cf64612d6b.png">

D.O.B: Invalid date
<img width="1121" alt="Screen Shot 2020-04-28 at 4 54 52 PM" src="https://user-images.githubusercontent.com/32987464/80448638-0bc52280-8971-11ea-9ca7-6e2fdfe81093.png">

### To reproduce

1. Go to 'Dispensary' module
2. Click on 'Lookup patient'
3. Search for a patient (i.e. by `Last Name`)

### Expected behaviour

The shown D.O.B. should be correct.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc1
- Tablet model: AVD 
- OS version: Android 9.0 API 28

### Additional context

N/A.

**Comment by wlthomson** [comment]
@diegoevangelisti Could you check if this can still be replicated on `v5.0.0-rc2`?

**Comment by diegoevangelisti** [comment]
@wlthomson just checked in `v5.0.0-rc2` but still getting the same error: `Invalid Date`. I even created a new patient, but nothing changed.

![Screen Shot 2020-04-29 at 4 20 56 PM](https://user-images.githubusercontent.com/32987464/80560574-8bb4c080-8a35-11ea-8b0d-45967b87df21.png)

![Screen Shot 2020-04-29 at 4 20 41 PM](https://user-images.githubusercontent.com/32987464/80560577-8d7e8400-8a35-11ea-938b-76a5a5ab568b.png)

**Comment by wlthomson** [comment]
@diegoevangelisti Hmm, can you step me through the process from the beginning, including where/how you created the patient?

**Comment by diegoevangelisti** [comment]
@wlthomson I've just tested again and it's working fine 🙃

<img width="1136" alt="Screen Shot 2020-05-04 at 8 06 26 AM" src="https://user-images.githubusercontent.com/32987464/80924666-5534c800-8dde-11ea-86b7-4d9fe1fb2de0.png">

**Comment by wlthomson** [comment]
@diegoevangelisti Nice! Closing as fixed.
