### ISSUE TITLE
Application crashes when clicking on the batches icon when doing a stocktake

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2793]
## Describe the bug

Application crashes when clicking on the batches icon when doing a stocktake. Was doing a Stocktake by program with Nzere mobile site from Ivory Coast. The application crashes if I click onthe batches icon of a line whether I have put a quantity for that line or no. The snapshot quantity is 0. It also crashing when I am quickly scrolling down the list of items of the stocktake.   

### To reproduce

1. Go to the Stocktake page
2. Click on New Stocktake, choose a program, choose a name for the stocktake
3. Add a quantity on a line and then click on the Bathes icon

### Expected behaviour

The application should not crash and the modal for the batches should open

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.0.1
- Tablet model: Galaxy tab A
- OS version: Android

**Comment by wlthomson** [comment]
@alainsussol Can you double check you can replicate this on latest `develop`? I think this has been fixed.

**Comment by ArpitaSussol** [comment]
Tested in V5.0.0 rc2

### Test

- [ ] Go to the Stocktake page

- [ ] Click on New Stocktake, choose a program, choose a name for the stocktake

- [ ] Add a quantity on a line and then click on the Bathes icon

**Comment by wlthomson** [comment]
Fixed as of `v5.0.0-RC2`.
