### ISSUE TITLE
Confirm button is misleading in supplier credits for items with 0 stock 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2795]
## Describe the bug
When you open the supplier credit window for an item with 0 stock, you can click 'Confirm' but it (hopefully) won't do anything; it's just a but misleading 

![image](https://user-images.githubusercontent.com/29744386/80555525-99157f00-8a24-11ea-9242-d9037ee4c3aa.png)

### To reproduce

1. Go to Stock window
2. Click on the 'Return' button for an item with no stock 
3. See window - Confirm button seems like it should be clicked but...

### Expected behaviour

Either the `Confirm` button should be disabled, or maybe the arrow to return items should be disabled in the first place?

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0RC1 
- Tablet model: Emulator - Galaxy Tab A 
- OS version: Android 8.0

**Comment by joshxg** [comment]
I think in addition, there should be a clearer indication that there are no batches with stock. I.e. instead of displaying the table, display "NO BATCHES WITH STOCK". Clearer.

**Comment by katherine-sussol** [comment]
Closed with #4060
