### ISSUE TITLE
App crashes when adding items from a Master list to a new Supplier Requisition

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2802]
## Describe the bug

The app crashes when trying to add items from a selected master list in a new Supplier Requisition. See images below:

![Screen Shot 2020-04-30 at 11 41 56 AM](https://user-images.githubusercontent.com/32987464/80657596-2534ae80-8ad8-11ea-8b7a-1c40dbc79a52.png)

![Screen Shot 2020-04-30 at 11 42 04 AM](https://user-images.githubusercontent.com/32987464/80657600-27970880-8ad8-11ea-9e1e-1dd17f80863a.png)

 
### To reproduce

1. Go to `Suppliers Requisitions` page
2. Click on `New Requisition` and follow the steps to create a `General Order` 
3. Click on `Add Master List Items`
4. Select a mater list
5. See error

### Expected behaviour

Items should be added to the requisition.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0-rc2
- Tablet model: AVD
- OS version: Android 9.0 API 28

### Additional context

While testing #1239

**Comment by wlthomson** [comment]
@diegoevangelisti Replicated. Bumping to release blocker.

**Comment by wlthomson** [comment]
Fixed by #2809.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Adding items from master list to supplier requisition does not crash app. **--PASSES--**
