### ISSUE TITLE
Icons for sorting `Requisition Number` column are not visible in `Supplier Requisitions` page

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2804]
## Describe the bug

The column `REQUISITION NUMBER` in `Supplier Requisitions` has its sorting icons hidden (just visibles a little bit, but not enough). See example below:

![80650628-75a41000-8ac8-11ea-85a7-7b0433ebfd71](https://user-images.githubusercontent.com/32987464/80672527-2f1ed780-8b01-11ea-9e58-7011fc6101ca.png)

### To reproduce

1. Go to 'Suppliers Requisitions' page
2. See error (first column, named `REQUISITION NUMBER`)

### Expected behaviour

The icons should be visible as it is for the rest of the columns.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc2
- Tablet model: AVD
- OS version: Android 9.0 API 28

### Additional context

While testing #1238.

**Comment by wlthomson** [comment]
Thanks @diegoevangelisti! Looks like column sizing issue, so should just be a case of adjusting some ratios.

**Comment by wlthomson** [comment]
Fixed by #2806.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] With programs enabled, customer requisitions page columns are not too squashed. **--PASSES--**
- [x] With programs enabled, customer requisitions can be ordered by requisition number. **--PASSES--**
- [x] With programs enabled, supplier requisitions page columns are not too squashed. **--PASSES--**
- [x] With programs enabled, supplier requisitions can be ordered by requisition number. **--PASSES--**
