### ISSUE TITLE
Options to select number of months of stock required on a Supplier Invoice are to small

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2805]
## Describe the bug

When working on a Supplier Requisition and editing the number of months of stock required, a modal pops up showing selectable options: 1, 2, 3,4,5,6 (months). Found that those numbers are too small and difficult to select. See example below:

![80756320-62577a00-8b86-11ea-84ee-26ec0046542c](https://user-images.githubusercontent.com/32987464/80781876-1d543780-8bc8-11ea-8836-b72e252c0713.png)

### To reproduce

Steps to reproduce the behaviour:

1. Open a current 'Supplier Requisition'
2. Click `Months of Stock` (in page info)
4. See small numbers

### Expected behaviour

Selectable numbers should be bigger so users can tap them easily.

### Proposed Solution

N/A.

### Version and device info

- App version: 5.0.0-rc2
- Tablet model: AVD
- OS version: Android 9.0

### Additional context

While testing #1239

**Comment by wlthomson** [comment]
Fixed by #2807.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Toggle bar for supplier requisition months of stock displays correctly. **--PASSES--**
