### ISSUE TITLE
Supplier and reason dropdown icons are not disabled for finalised stocktakes

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2812]
## Describe the bug

See @mark-prins review comment: https://github.com/openmsupply/mobile/pull/2784#pullrequestreview-401406270.

### To reproduce

1. Finalise a stocktake.
2. View stocktake batches.
3. Note that supplier and reason icons are not "greyed out", but do not respond on press.

### Expected behaviour

Supplier and reason icons should be "greyed out" for finalised batches.

### Proposed Solution

Grey out supplier and reason icons if stocktake is finalised.

### Version and device info

- App version: `5.0.0-rc2`
- Tablet model: Nexus 10 (emulated).
- OS version: API 29.

### Additional context

N/A.

**Comment by wlthomson** [comment]
Fixed by #2784.

**Comment by ArpitaSussol** [comment]
Tested in v5.0.0 rc3

## Testing


- [ ] Can view stocktake batch details for finalised stocktakes. - **PASS**
