### ISSUE TITLE
Supplier Invoice: Quantity updated in tablet dont get updated in desktop

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2814]
## Describe the bug

For me the case was Stock transfer. Where desktop created CI to mobile store.
Here when user updates the quantity for item in Supplier invoice, it don't get updated in its collector store in desktop.

### To reproduce

1. Create stock transfer from desktop to mobile store.
2. Open SI in tablet.
3. Edit quantity of one item and finalised directly.
4. Sync the records and check quantity for same items in desktop.
5. Run diagnostic see item ledger issue as well.

### Expected behaviour

Quantity edited in tablet store should update in its collector desktop store as well.

### Version and device info

- App version:3.2.2
- Tablet model:emulator api 28

**Comment by wlthomson** [comment]
@anildahalsussol Is this bug occurring on latest mobile (`v5.0.0-rc2`)?

**Comment by anildahalsussol** [comment]
its on 3.2.2..As many tablets in MAM are in 3.2.2...And they are facing this problem so i tested in 3.2.2

**Comment by anildahalsussol** [comment]
Json of sync records send from tablet to desktop once trans_line is updated in tablet.It seems it updates transact and item_line not trans_line. So its creating ledger issue.
{
      "SyncID":"9b709c908e8311eaad1fd34ab2e38b98",
      "RecordType":"item_line",
      "RecordID":"1DED975C29BE4490B07B92628373265B",
      "SyncType":"U",
      "StoreID":"B091D6D8D1781A49B469C905086F6E87",
      "Data":{
         "ID":"1DED975C29BE4490B07B92628373265B",
         "store_ID":"B091D6D8D1781A49B469C905086F6E87",
         "item_ID":"C8400A9B6B3E7044AA6F90F6C4A6F972",
         "pack_size":"1",
         "expiry_date":"2020-12-31T00:00:00",
         "batch":"ACC39002",
         "available":"0",
         "quantity":"0",
         "stock_on_hand_tot":"0",
         "cost_price":"1",
         "sell_price":"1",
         "total_cost":"0",
         "name_ID":"DC2A3E4642351046B8E33601575FC287",
         "donor_id":null
      }
   },
   {
      "SyncID":"9b7494308e8311eaad1fd34ab2e38b98",
      "RecordType":"item_line",
      "RecordID":"F853F4890FD9417C85AA2E91AE5695A4",
      "SyncType":"U",
      "StoreID":"B091D6D8D1781A49B469C905086F6E87",
      "Data":{
         "ID":"F853F4890FD9417C85AA2E91AE5695A4",
         "store_ID":"B091D6D8D1781A49B469C905086F6E87",
         "item_ID":"298F1E271DF2E44B9A75DE4EEC21B5F0",
         "pack_size":"1",
         "expiry_date":"2021-09-30T00:00:00",
         "batch":"9k02539",
         "available":"140",
         "quantity":"140",
         "stock_on_hand_tot":"140",
         "cost_price":"0.17",
         "sell_price":"0.17",
         "total_cost":"23.8",
         "name_ID":"DC2A3E4642351046B8E33601575FC287",
         "donor_id":null
      }
   },
   {
      "SyncID":"9b74e2508e8311eaad1fd34ab2e38b98",
      "RecordType":"transact",
      "RecordID":"7FBCFF48785249A0B24B6C0E006A34C3",
      "SyncType":"U",
      "StoreID":"B091D6D8D1781A49B469C905086F6E87",
      "Data":{
         "ID":"7FBCFF48785249A0B24B6C0E006A34C3",
         "name_ID":"DC2A3E4642351046B8E33601575FC287",
         "invoice_num":"145",
         "comment":"Stock transfer ",
         "entry_date":"2020-05-05T00:00:00",
         "type":"si",
         "status":"fn",
         "mode":"store",
         "total":"23.8",
         "their_ref":"PO sent date: 4",
         "confirm_date":"2020-05-05T00:00:00",
         "subtotal":"23.8",
         "user_ID":null,
         "category_ID":null,
         "confirm_time":"09:35:48",
         "store_ID":"B091D6D8D1781A49B469C905086F6E87"
      }
   }
]

**Comment by wlthomson** [comment]
I have a feeling this might be a duplicate of https://github.com/openmsupply/mobile/issues/2415.

Suggest upgrading to `v3.2.6` and seeing if that fixes the issue!

**Comment by anildahalsussol** [comment]
Testing now.

**Comment by anildahalsussol** [comment]
Thanks @wlthomson . Fixed on 3.2.6
https://github.com/openmsupply/mobile/issues/2415
