### ISSUE TITLE
Searching for an item in a Supplier Invoice is not working as expected

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2815]
## Describe the bug

The search filter it's not working as expected in a Supplier Invoice. Typing an item's name doesn't filter and then there is no way to get back from that point, the app doesn't respond (it just allowed me to type on the search input). See example below:

![wrongfilter2](https://user-images.githubusercontent.com/32987464/81031981-5f3fef00-8ee2-11ea-8648-15594ba299fc.gif)

### To reproduce

1. Go to 'Supplier Invoices' and open a current/finalised `si`
2. Click on 'Search' and lookup an existing item
3. See error

### Expected behaviour

It should filter as usual.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc2
- Tablet model: AVD
- OS version: Android 9.0

### Additional context

While testing #1236

**Comment by wlthomson** [comment]
Fixed by #2816.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Can filter supplier invoice items by name. **--PASS--**
- [x] Can filter supplier invoice items by code. **--PASS--**
