### ISSUE TITLE
Patient lookup not matching first and last names correctly

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2817]
## Describe the bug

See title. 

### To reproduce

See https://github.com/openmsupply/mobile/issues/2713#issuecomment-624360599.

### Expected behaviour

Patients should be matched by first and last name, and a combination of both.

### Proposed Solution

First step is to determine if this is a mobile or desktop side problem. If desktop, will need to get a fix into the next `v10` patch.

### Version and device info

- App version: `v5.0.0-rc3`
- Tablet model: Android emulator.
- OS version: ~API28.

### Additional context

Raised by @diegoevangelisti.

**Comment by wlthomson** [comment]
Fixed by #2818.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x]  Lookup queries involving multiple fields work correctly (e.g. lookup patient with given first name and last name). **--PASS** 

@wlthomson I tried many combinations and all worked well 🎉
