### ISSUE TITLE
Summary of bugs found during TESTING: Supplier Invoice Page

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2820]
## Describe the bug

List of bugs found during testing of #1236 - Test plan template -.

**NOTE:** All correspond to Supplier Invoice Page

- **Columns > Batch name**

Batches are supposed to be sortable and left aligned but found they are not sortable and center aligned. 

- **Page Info > Entered By**

There is no `Entered By` field.
Then, when generating a Supplier Credit, this field is empty (i.e. `Entered by: null` )

- **Page Info > Comment**

There is no `Comment` in a generated Supplier Credit.

### To reproduce

See above clarifications.

### Expected behaviour

Explained above.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc3
- Tablet model: AVD
- OS version: Android 9.0

### Additional context

Raised while testing #1236
@wlthomson please let me know in case screenshots are needed.

**Comment by wlthomson** [comment]
Gracias @diegoevangelisti!

Just for tidiness have split this into two new issues: #2821 #2822. Closing as a duplicate.
