### ISSUE TITLE
Save button gets disabled when DOB is removed after searching in lookup patient/prescriber

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2823]
## Describe the bug

In Dispensary module, the `Save` button in `Lookup patient` gets disable when removing the entered D.O.B (filter) after searching for a patient/prescriber.

![lookupPatient](https://user-images.githubusercontent.com/32987464/81228704-a04f1500-9042-11ea-8d41-9ab1865960e5.gif)

### To reproduce

1. Go to 'Dispensary'
2. Click on 'Lookup patient' and type a DOB
3. Click on `Save` and then delete the DOB

### Expected behaviour

The button should remain enable.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc3
- Tablet model: AVD
- OS version: Android 9.0 - API 28

### Additional context

Raised while testing #2818

**Comment by wlthomson** [comment]
Fixed by #2827.
