### ISSUE TITLE
Error when doing a full (initial) sync on Mobile

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2840]
## Describe the bug

During a Full (initial) sync, there is an error showing in mobile that is related to an invalid date that cannot be converted to a number. I wold guess that the problem is on the server side because it is happening with mobile version 4 or version 5

![image](https://user-images.githubusercontent.com/11624516/81862395-aa3bb100-9537-11ea-92ca-5e5e012fee25.png)

### To reproduce

1. Empty the cache and application infos of the mobile app

![image](https://user-images.githubusercontent.com/11624516/81862458-c0e20800-9537-11ea-80ea-15aff378637b.png)

2. Have the  mobile app connect to a v411 of the desktop server to start an initial sync
3. See error

### Expected behaviour

No error.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V4 or v5 and server side is v411
- Tablet model:
- OS version:

### Additional context

Possibly related to #6143 desktop issue

**Comment by wlthomson** [comment]
@alainsussol Just before I try to replicate, can you confirm that this is occuring on `v5.0.0` (screenshorts look like testing on `v5.0.0-rc2`, which is not latest)?

**Comment by wlthomson** [comment]
Update: 

Confirmed bug occurring on `v4` (can't replicate on `v5`). 

Likely this will occur on all mobile versions `<5`, so will update `v4` and `v3` for compaitibility.

**Comment by wlthomson** [comment]
Have made separate issues for `v3` and `v4`. I can't replicate on `v5`, but leaving this open in case you still can.

**Comment by alainsussol** [comment]
@wlthomson 
Hi Will,

I cannot replicate it either in v5.0.0 so will close this. Thanks a lot :)

**Comment by wlthomson** [comment]
@alainsussol Thanks! 🎉
