### ISSUE TITLE
Fix timezone offset bug (v3.2)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2841]
## Describe the bug

See https://github.com/openmsupply/mobile/issues/2840.

### Version and device info

- App version: `v3.2.6`
- Tablet model: N/A.
- OS version: N/A.

### Additional context

Bug fix for `v3.2`.

**Comment by wlthomson** [comment]
Fixed by #2844.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v3.2.7
- [x] Initial sync with mSupply desktop v10 is successful without errors. **-PASS-**
- [x] Initial sync with mSupply desktop v11 is successful without errors. **-PASS-**

**Comment by katherine-sussol** [comment]
Updating doc labels as I don't think there are any required from reading through the issue/changes (if I am wrong please let me know 😄 )
