### ISSUE TITLE
Fix timezone offset bug (v4.0)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2842]
## Describe the bug

See https://github.com/openmsupply/mobile/issues/2840.

### Version and device info

- App version: `v4.0.3`
- Tablet model: N/A.
- OS version: N/A.

### Additional context

Bug fix for `v4.0`.

**Comment by wlthomson** [comment]
Fixed by #2843.

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v4.0.4
- [x] Initial sync with mSupply desktop v10 is successful without errors. **-PASS-**
- [x] Initial sync with mSupply desktop v11 is successful without errors. **-PASS-**
