### ISSUE TITLE
Optimisation: Unnecessary calls of renderRow

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#285]
Steps:
- `console.log(rowId)` at the top of renderRow in GenericTablePage
-  start logcat to watch in console
-  go to a stocktake, viewing in stocktake editor.
-  sort by a column and observe console

Expected:
That it'd call renderRow once for every rowData in the table

Actual:
It calls renderRow 2-4 times for each rowData, in correct sequential order
i.e.: `0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3`

If you put console.log('Middle') in refreshData, the above i.e. is: `0,1,2,3,0,1,2,3,Middle0,1,2,3,0,1,2,3`

Not massively impactful as the shadow DOM checks against the real DOM and finds no difference, so render time isn't 2-4 times longer.
- Doesn't appear to happen to pages with many rows, e.g. stocktakes.
- Can be seen in: SupplierInvoicePage, CustomerInvoicePage, StocktakePage AND requisitionsPage, which means that it may not be something cause by the refs logic.

Thought to be the cause of: #257

**Comment by joshxg** [comment]
A lot of data table issues, have made #1043 in hopes of consolidating them all
