### ISSUE TITLE
Fix sync error caused by sync records for non-existent records

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2851]
## Is your feature request related to a problem? Please describe.

See issue #2849. 

Just a quick hotfix to resolve the immediate usability blocker to sync from non-existent records.

## Describe the solution you'd like

Set `canDeleteSyncOut` for missing record error.

## Implementation

See above.

## Describe alternatives you've considered

N/A.

## Additional context

Raised by PNG.

@andreievg

**Comment by ArpitaSussol** [comment]
Tested in 5.1.1

## Testing

### Setup

- Create two names on desktop (customers or suppliers).
- Associate each name with a master list.
- Sync to mobile.
- Merge the two names.
- Sync to mobile (if needed press manual sync twice, ensure no records are waiting).

## Test cases

- [ ] Sync does not cause an error.
