### ISSUE TITLE
Allow creating supplier invoices for internal suppliers

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2880]
## Is your feature request related to a problem? Please describe.

Mobile only supports manual receiving of goods (i.e. supplier invoices) from external suppliers. Supplier invoices for internal stores cannot be manually created, can only be created as part of the goods transfer process via a finalised customer invoice.

## Describe the solution you'd like

Add internal stores to list of suppliers for a new supplier invoice.

## Implementation

Update modal source  from `'ExternalSupplier'` to `'Supplier'` + any changes needed to prevent regressions.

## Describe alternatives you've considered

Leave as it is?

## Additional context

Requested by @Gwalior-84.

Triagers :smile:: @craigdrown @andreievg @joshxg.

**Comment by joshxg** [comment]
Why? Is there someone asking for it? Is there a problem with the current implementation?

**Comment by Gwalior-84** [comment]
Problem with current functionality is that if stock is pushed (no requisition) from an mSupply store that, for whatever reason (and there are too many, including something as simple as "we've had a power cut for two weeks, and the generator broke 6 months back...) did _not_ use a mSupply CI to send the goods.  So how can the receiving facility bring in the stock?

**Comment by wlthomson** [comment]
Since there was an active design decision to restrict the suppliers in mobile, would also be helpful to get some background information on the "why not", i.e. if there are strong reasons we should not do this, or if this was just a case of keeping mobile simple?

**Comment by joshxg** [comment]
I just have prefaced my last comment with: I don't have nearly enough domain knowledge to really have an opinion on why to do it or not 🤣 

>  So how can the receiving facility bring in the stock?
Technically, a stock take

**Comment by joshxg** [comment]
Also, the situation you describe @Gwalior-84 would help hide that

**Comment by joshxg** [comment]
whoops!

**Comment by GaryWilletts** [comment]
There are probably some customers who would object strongly to this functionality - arguably unreasonably because you can just add random stock on a stocktake anyway - but also on the grounds that it adds more potential for the user to select the wrong supplier or do the wrong thing (create a supplier invoice manually instead of processing the one that's arrived automatically). So it might be a good thing to incorporate in the store preferences.

**Comment by Gwalior-84** [comment]
Good point @GaryWilletts 

With this feature, there should be check when trying to create an SI:  If there is already an unfinalised Supplier Requisition from this Name, prompt the user with:

There is an unfinalised Supplier Requisition from XXXX.
Are you sure you want to create a new Supplier Invoice?

Yes / No

**Comment by craigdrown** [comment]
@Gwalior-84  @GaryWilletts @joshxg @wlthomson 
(Is there a "mention eveyone already mentioned" shortcut?)
I am heartened by everyone asking the right questions.
I am concerned that the "real" supplier invoice turns up later, and then you have a right mess. There is already "inventory adjustment" which at least doesn't risk duplicates (although of course if the "real" one arrives later, you have to undo it). 
I am concerned that users will default to entering a supplier invoice rather than making sure it has arrived by sync (or even checking if it has arrived by sync). That isn't a clear answer, but this needs some careful thinking through so we don't create more problems than we solve. Some of that could be alleviated by warning the user when they choose an internal supplier and showing outstanding invoices?

**Comment by wlthomson** [comment]
Brief summary of the general concensus so far (AFAICS):

- No (known) hard barrier to allowing creation of supplier invoices for internal suppliers on mobile
- SIs for internal stores should generally be created automatically, should only be manually created in special circumstances
- If functionality is added, also need to add some mechanism to prevent/reduce risk of misusing 

If above is correct, I think all that needs to be decided is how "strict" the mechanism is, which will help answer the question of how to implement it.

For whatever it's worth, my initial thinking was a combination of @GaryWilletts and @Gwalior-84, e.g.:

1. User presses button for new SI

```
IF external SIs are enabled in store preferences
THEN return internal and external suppliers
ELSE return internal suppliers
```

2. User selects supplier

```
sync with server
IF sync successful
THEN query for unfinalised SR for supplier
  IF no results, create SI
  ELSE alert user that creating SI for existing SR
ELSE alert user that creating SI may cause duplicates
```

**Comment by wlthomson** [comment]
Brief summary of the general concensus so far (AFAICS):

- No (known) hard barrier to allowing creation of supplier invoices for internal suppliers on mobile
- SIs for internal stores should generally be created automatically, should only be manually created in special circumstances
- If functionality is added, also need to add some mechanism to prevent/reduce risk of misusing 

If above is correct, I think all that needs to be decided is how "strict" the mechanism is, which will help answer the question of how to implement it.

For whatever it's worth, my initial thinking was a combination of @GaryWilletts and @Gwalior-84, e.g.:

1. User presses button for new SI

```
IF SIs for internal stores are enabled in store preferences
THEN return internal and external suppliers
ELSE return external suppliers
```

2. User selects supplier

```
IF supplier is external
THEN create SI
ELSE sync with server
  IF sync successful
    THEN query for unfinalised SR for supplier
    IF no results, create SI
    ELSE alert user that creating SI for existing SR
  ELSE alert user that could not sync, creating SI may cause duplicates
```

Depending on how strict we want to be, could also:

- Prevent user from making SI if SR for same store is found
- Prevent users from creating SIs for internal stores if cannot sync

I think the former could make sense, but I think the latter is a bit overkill... given offline-first focus of mobile, blocking functionality until sync is probably something users wouldn't be too keen on!

**Comment by GaryWilletts** [comment]
If we're going to allow it at all then that's basically the right way to do it I think. The sync check needs refining I think; there's probably some records you can check locally e.g. the presence of an unfinalised si for the same supplier, a requisition sent to the supplier but with no response received yet).

The more I think about it, the less I like adding the functionality! One way to give some comfort would be a way of linking/swapping/replacing invoices if the real synced one turns up later. #canOfWorms?

**Comment by joshxg** [comment]
I think #canOfWorms is right :( 

Introducing this functionality will (probably) just emphasize already existing flaws while allowing a user in an edge case situation (I am an user-expert now, ok?) to nicely fix a problem. From a code perspective it is non-trivial if you include the syncing logic or the check-existing things logic, trivial without those. 

Not sure if there's a valid argument for not doing it - but there are certainly far more impactful things to be doing - even just other 'UX' features in mobile!

**Comment by Gwalior-84** [comment]
Yes, I’m certainly OK with telling PNG operators to do an Inv. Adj. for
such fringe cases.  If it raises any auditor eyebrows, that’s good.  An
auditor’s report might be heeded by management, and that generator might
get fixed!

**Comment by wlthomson** [comment]
Following up from above:

Just to circle back (@craigdrown likes this terminology :laughing:), the questions for the sussol triage team:

1. Is this functionality needed to solve a problem
2. Is this functionality not implemented for a reason

- Re. other things to spend time on: I put this under the first question, i.e. whether this functionality solves any problems that cannot be solved via a workaround etc. (IMO most of the listed things are "nice to haves", in as far as that the user can do their basic workflow without them).

- Re. the can of worms: I put this under the second question, i.e. is this can of worms closed for a reason! I think the main thing here is the fact that this functionality is already in desktop... correct if wrong, but I think all these problems seem to also apply to satellite desktop sites? I think we all agree that restricting to internal suppliers is simpler/safer, but is this can of worms already opened?

For the first question, it seems like the motivation for introducing this functionality is to solve an issue which can arise when supplying stores break the agreed workflow (sending stock without a CI). In that context, something like an inventory adjustment (with a comment or something) seems an appropriate fix to me, as the intended workflow has already been broken by the supplying store.
I guess the caveat to this could be if the customer is explicitly asking for this functionality (@Gwalior-84). 

If the answer to the first question is no, I think I would lean towards agreeing with @joshxg and @GaryWilletts that it's probably not worth it! If it's yes, I think the question comes down to whether introducing this functionality in mobile will open a new can of worms, or if the worms have already escaped :laughing:!

**Comment by wlthomson** [comment]
@Gwalior-84 OK with closing this issue?

**Comment by Gwalior-84** [comment]
Yes, I’m OK with closings the issue.  If they really get upset about it, we
can look at it again.  In any case, we should articulate the current
functionality in our docs.  I don’t have access to them here...

**Comment by Gwalior-84** [comment]
I've now had a look at our docs.  They certainly do need updating.  There's _nothing_ about SIs from non-mSupply suppliers.
