### ISSUE TITLE
Insurance policy family number is not a required field

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2918]
## Is your feature request related to a problem? Please describe.

Desktop logic has been updated such that family policy number is not a required field.

## Describe the solution you'd like

Update mobile insurance policy form for consistency with desktop.

## Implementation

Update `FORM_INPUT_KEYS.]POLICY_NUMBER_FAMILY].isRequired = false`.

## Describe alternatives you've considered

N/A.

## Additional context

Raised by @JonnaQuismundo.

**Comment by wlthomson** [comment]
Fixed by #2921.

**Comment by ArpitaSussol** [comment]
Tested in 5.1.1

## Testing

- [ ] Can create an insurance policy with a blank family policy number.
