### ISSUE TITLE
Update insurance form policy number ordering

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2919]
## Is your feature request related to a problem? Please describe.

When viewing/editing an insurance policy on desktop, the family number is ordered before the personal number. This order should be consistent on mobile. 

## Describe the solution you'd like

Reverse ordering of personal and family number fields.

## Implementation

Update `FORM_CONFIGS.insurance` keys.

## Describe alternatives you've considered

N/A.

## Additional context

Raised by @JonnaQuismundo.

**Comment by wlthomson** [comment]
Fixed by #2920.

**Comment by ArpitaSussol** [comment]
Tested in 5.1.1

## Testing

- [ ] Family policy number appears before personal policy number when viewing/editing insurance policies. - **FAILED**

@wlthomson 
Order is not reversed and to maintain consistency with Desktop there should be "-" between Family Policy number and Personal Policy number.
![Screen Shot 2020-07-10 at 12 17 20 PM](https://user-images.githubusercontent.com/58979436/87124068-bb8b0a80-c2a7-11ea-92ed-e5fa26185d11.png)
![Screen Shot 2020-07-10 at 12 16 24 PM](https://user-images.githubusercontent.com/58979436/87124070-bd54ce00-c2a7-11ea-807f-1a86b6a6d17d.png)
![Screen Shot 2020-07-10 at 12 16 06 PM](https://user-images.githubusercontent.com/58979436/87124071-bded6480-c2a7-11ea-8ed8-0cf8d72a8508.png)


Created an issue #3016
