### ISSUE TITLE
Add Burmese ( ြမန်မာ ) language option

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/mobile#2928]
## Is your feature request related to a problem? 
The lack of ြမန်မာ

## Describe the solution you'd like

Add ြမန်မာ

ISO 639-1 | my
-- | --

Icon 
![image](https://user-images.githubusercontent.com/254026/84215020-316d4c00-ab19-11ea-97b2-3443b616e05a.png)

## Implementation

Excel with Aung now- he'll get back to us

**Comment by wlthomson** [comment]
@joshxg I think depending on time frame, this could go into `v5.1` (or later minor) or  `v6` major. Depends on how quick Aung is with the files?

**Comment by AungHtunOo88** [comment]
Hi, This is Aung. I can get this done by tomorrow myanmar time.

**Comment by wlthomson** [comment]
@AungHtunOo88 thanks :smiley:. 

Going to milestone `v5.1`, see how we go from there!

**Comment by joshxg** [comment]
Perfect!

Will most likely need a follow up issue to ensure all the strings fit nicely - unless the implementer does it in this one!

**Comment by AungHtunOo88** [comment]
I have one issue - when I save in .csv, our font turns into ??????, can I send you in Excel Worksheet which you will have actual font?

**Comment by wlthomson** [comment]
@AungHtunOo88 Sure, no problem (can send to anyone in the office, just let us know so we can get it forwarded).

**Comment by AungHtunOo88** [comment]
Hi,
Please find link for translation into Burmese (မြန်မာ).
[https://www.dropbox.com/s/cngnczddn5k95gd/Mobile_translations%20%28translated%29.xlsx?dl=0](url)

**Comment by GaryWilletts** [comment]
Aung's actual file here: [Mobile_translations (translated).xlsx](https://github.com/openmsupply/mobile/files/4763989/Mobile_translations.translated.xlsx)

**Comment by joshxg** [comment]
Thanks @AungHtunOo88 that's great!

Will get this into the code base :)

**Comment by wlthomson** [comment]
Thanks @AungHtunOo88, sticking with `v5.1.0` for this.

**Comment by wlthomson** [comment]
Going to break this out into a few issues, as quite a lot of translations here!

**Comment by wlthomson** [comment]
Burmese language support is supported as of  `v5.1.0`.
