### ISSUE TITLE
Entering batch/quantity value against supplier invoice > Tablet keyboard disappear

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#2939]
## Describe the bug

Entering the batch details / quantity to supply leads to disappear keyboard.

### To reproduce

1. Go to 'Supplier invoice'
2. Click on 'Batch or quantity' to put in > doesn't happen always need to play with it > or need to add a new line.
3. Single/double tap or put the cursor at the end > No disappear of keyboard
4. See Keyboard get disappear when selecting batch column / quantity

### Expected behaviour

consistent

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.1
- Tablet model: Samsung
- OS version: Android

### Additional context

See video:
https://www.dropbox.com/s/3dv1gnj5isb1lqo/supplierinvoice.mp4?dl=0
https://www.dropbox.com/s/m50fa43ujqgluli/video-1591800520.mp4?dl=0

**Comment by sworup** [comment]
@bijaySussol @anildahalsussol 
Just ran this on v5.0.3 on an emulator with these settings. The problem case never happened after a few different tries. Everything ran smoothly.

![Screenshot 2020-06-18 at 11 12 22](https://user-images.githubusercontent.com/683452/84981705-d6f57080-b154-11ea-852f-20c5ae690961.jpg)

**Comment by bijaySussol** [comment]
@sworup : 

I can recreate this every-time from the apk
have you seen above video?

this doesn't always happens needs specific workflow

**Comment by andreievg** [comment]
could it be something to do with the tablet screen size ? (it looks like it's below minimum requirements)

**Comment by bijaySussol** [comment]
> could it be something to do with the tablet screen size ? (it looks like it's below minimum requirements)

Have recreated this on office tablet.
Spec details:

![Screenshot 2020-06-19 at 10 22 44](https://user-images.githubusercontent.com/13144882/85097311-dcb38a80-b216-11ea-844d-a647cf18c4b6.png)
What is the minimum requirement?
Same with this issue: https://github.com/openmsupply/mobile/issues/2941

**Comment by bijaySussol** [comment]
It looks to me: Tablet keyboard taking up too much of the screen when have more lines on original screen and trying to enter batch - the original screen pushes Keyboard screen coz of width can't be fitted in?

**Comment by bijaySussol** [comment]
@sworup :
this issue:https://github.com/openmsupply/mobile/issues/2941
It happened on emulator on stocktake, See GIF:
http://g.recordit.co/ceawL7ZY4G.gif

**Comment by sworup** [comment]
Looking at the bug demo you showed @bijaySussol this is happening because a wrapper component that is not supposed to re-render, is getting its state changed by something, triggering a re-render at the deeper level then the component that opens the keyboard. This will obviously cause a cascade of re-renders resetting the component that opens the keyboard (hence closing it).

**Comment by ujwalSussol** [comment]
@sworup  :  This is issue that our client will raise again and again, so great if we had a fix.

**Comment by joshxg** [comment]
Using #2941 as the single issue for this

**Comment by josh-griffin** [comment]
Hi @bijaySussol

I will get to work on this ASAP!!!!!!!

**Comment by bijaySussol** [comment]
Hey @josh-griffin 
Nice way to say Hello to you.
Thank you but your good work will save one of our user
Cheers
