### ISSUE TITLE
App crashes when trying to create prescription for already-merged-patient on mobile store

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#2944]
## Describe the bug
After merging two patients, the changes are not seen in mobile stores even after successful sync. On further trying to create prescriptions for already-merged patient in mobile, the app crashes every time

### To reproduce
1. Create two patients on mobile store, and sync.
2. On cloud site, merge them.
3. Now on mobile store, sync (manually), and see error: it says Sync Complete and they're still not merged.
4. Now try creating prescription for the already-merged-patient, and see error: the app crashes!

### Expected behaviour
First, after successful sync on mobile, patients should have been merged.
Second, app should not crash whatsoever.

### Version
- App version: v5.0.3

### Additional context
https://github.com/sussol/msupply/pull/6236#issuecomment-643059615

**Comment by anildahalsussol** [comment]
Recreated in master 411 as well.

**Comment by nmadruga** [comment]
@DhanyaHerath and I will have a look on this today.

**Comment by DhanyaHerath** [comment]
partial updates: using `develop` structure for desktop: no sync_out records are created when two patients are merged, so will cause this crash. this should be a desktop issue I think.

That said, with Adrian's PR branch we were seeing sync_out records being created from patient merges, and still seeing a crash, so there is another problem involved I think.

**Comment by DhanyaHerath** [comment]
Closing, since this seems to be a desktop bug: the sync_out records being created on desktop are being filtered out and deleted before they are sent to mobile, because they have a store_id that is different to the mobile store: https://github.com/sussol/msupply/issues/6390
