### ISSUE TITLE
Patient name shows "undefined" for a time being during back and forth from Prescription page

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#2945]
## Describe the bug

Patient name shows "undefined" during back and forth from Dispense page

### To reproduce

1. Go to Dispensary -> Patients tab
2. Click on Dispense action
3. From Prescription page, click on back.
4. See error.
https://recordit.co/ywG2rmPLZI

### Expected behaviour

Patient name should not be shown as "Undefined Undefined" even for a second for better user experience.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.3

### Additional context

arises while testing tablet feature for PR https://github.com/sussol/msupply/pull/6236

**Comment by wlthomson** [comment]
Look's like a navigation issue. 

@joshxg knows more about this than me but from what I can see, it looks like the `cleanup` function in `goBack` (`src/navigation/actions.js`) is `null`ifying the `transaction` before the back animation is completed. Not sure whether this is a re-render that needs to be avoided, or if there's another way around this.

If the prescription is deleted (which I think it has to be), the `transaction` has to be cleared, or an illegal access error will be thrown. 

Tried so far:

- Removing the `batch` around the `navigateBack` and `cleanUp` dispatches.
- Moving the cleanup logic to the `PrescriptionReducer`.

Neither solved the problem, so any ideas appreciated!

**Comment by joshxg** [comment]
@wlthomson I haven't looked in depth (I can if you want me to though) - but is there a selector for the name? Just `name ?? "" maybe? 

def an annoyance through a combo of realm + deleting requirement! I suspect the prescriber name is the same? If not, can just use whatever thats doing? Same thing with the title in the top left I think?

**Comment by wlthomson** [comment]
@joshxg Made a quick fix by tweaking a couple of `prescription` selectors.. Not necessarily the ideal solution, but solves the problem from the user's perspective!

**Comment by wlthomson** [comment]
Fixed by #3012.

**Comment by ArpitaSussol** [comment]
Tested in V6.0.0 rc3

## Testing


- [ ] When navigating back from the first page of a prescription, the patient name does not display as `undefined`. - **PASSED**
