### ISSUE TITLE
Add Myanmar to language selection

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2949]
## Is your feature request related to a problem? Please describe.

Add Myanmar to language selection.

## Describe the solution you'd like

Add Myanmar to language selection, including flag.

## Implementation

Add Myanmar flag, codes etc. Just copy and substitute existing languages.

## Describe alternatives you've considered

N/A.

## Additional context

See #2928 for main issue.

**Comment by wlthomson** [comment]
Fixed by #2952.

**Comment by ArpitaSussol** [comment]
Tested in 5.1.1

## Testing

- [ ] Can select Myanmar from language selection.
- [ ] Myanmar flag is correct and appears correctly.

**Comment by katherine-sussol** [comment]
Updated screenshot here: https://docs.msupply.foundation/en:mobile:user_guide:getting_started?rev=1627968654#selecting_the_language
