### ISSUE TITLE
Can't set patient birthdate to current date 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2957]
## Describe the bug

I started creating a patient, and left the birth date as it was, and then clicked Save. Nothing happened, double-clicked and it showed an error. 

### To reproduce

1.  Go to New Patient 
2. Enter a first and last name
3. Click Enter to move past date field, then click Save (twice, if nothing happens on first go)
![image](https://user-images.githubusercontent.com/29744386/84719040-59075d00-afce-11ea-916a-83efe9c03a25.png)

![image](https://user-images.githubusercontent.com/29744386/84719026-51e04f00-afce-11ea-90c5-e5354e4fb702.png)

### Expected behaviour

Should save the patient with the current date as their birthdate?

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.3
- Tablet model: Emulator- Galaxy Tab A 
- OS version: Android 8.0

### Additional context

Works fine if I change the birthdate to yesterday :)

**Comment by wlthomson** [comment]
Hm, maybe a placeholder issue? What happens if you explicitly set the date to today?

**Comment by wlthomson** [comment]
Update: confirmed doesn't occur if the date is explicitly set.

**Comment by wlthomson** [comment]
Fixed by #2959.

**Comment by ArpitaSussol** [comment]
Tested in 5.1.1

## Testing
- [ ] Patient saves without error.
