### ISSUE TITLE
Add Burmese/Myanmar form strings

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2962]
## Is your feature request related to a problem? Please describe.

Add Burmese/Myanmar translations for form input strings.

## Describe the solution you'd like

See above.

## Implementation

Add Burmese/Myanmar translations to `formInputStrings` localisation.

## Describe alternatives you've considered

N/A.

## Additional context

See #2928 for main issue.

**Comment by wlthomson** [comment]
Fixed by #2963,

**Comment by ArpitaSussol** [comment]
Tested in mSupply 5.1.1
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] New patient form translations are correct.
- [ ] New prescriber form translations are correct.
