### ISSUE TITLE
Patient gender not correctly syncing to desktop

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#2989]
## Describe the bug
When creating Female patient in mobile, it shows up as Male in cloud site. Patient details look different from the one created in mobile store.

### To reproduce
1. In mobile store, create a patient, select Gender : Female, and Sync.
2. In cloud site, check that patient details : it's Male there.

### Expected behaviour
Patient details should be same in cloud site as created in mobile store originally.

### Version and device info
- App version: v412RC04
- Tablet model: v5.0.4

**Comment by wlthomson** [comment]
Can replicate on `v5.0.4` and `v5.1.0`. 

Will target `v5.0.X` for now, with expectation to bump to `v5.1.X` soon.

**Comment by wlthomson** [comment]
Update: looks like easy fix, `female` field was missing from `outgoingSyncUtils`. At this stage, overhead of a patch seems unjustified, so going to add this to `5.1.0` release.

**Comment by ArpitaSussol** [comment]
Tested in apk v5.1.0

### 
Testing

- [ ] Desktop displays correct gender for patients created on mobile. - **PASS**
