### ISSUE TITLE
Merged Prescriber from Desktop store doesn't sync to Mobile Store

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#2991]
## Describe the bug

Merged Prescriber from Desktop store doesn't sync to Mobile Store

### To reproduce

1. In mobile store, create atleast two prescriber .
2. Create Prescription from one of the created Prescriber and sync
3. Merge these prescriber in Desktop Store such that Keep Prescriber with no Prescription and Merge Prescriber with Prescription.
4. Check Mobile Store
5. See Error. Prescribers is not sync 
![Screen Shot 2020-06-26 at 10 16 05 AM](https://user-images.githubusercontent.com/58979436/85820517-1d228380-b796-11ea-9b82-ae55de6bda0e.png)
![Screen Shot 2020-06-26 at 10 15 21 AM](https://user-images.githubusercontent.com/58979436/85820521-1eec4700-b796-11ea-8610-da3b0c24ad5e.png)
![Screen Shot 2020-06-26 at 10 18 00 AM](https://user-images.githubusercontent.com/58979436/85820724-98843500-b796-11ea-8d24-74ca3c8979c9.png)

### Expected behaviour

Sync should work as expected and Merged prescriber should be shown in Mobile as well

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.4
- Tablet model: API 21
- Desktop version: v412RC04

**Comment by nmadruga** [comment]
From my understanding this problem will be also fixed by the solution needed on the Desktop side (https://github.com/sussol/msupply/issues/6390) for a problem described in the issue: #2944

The status of this fix is still **To Do**. But will be included in the v4.12 release.

**Comment by wlthomson** [comment]
Following up from @nmadruga, will milestone this `v6` and move to test column.

**Comment by joshxg** [comment]
there is currently no logic to merge prescribers on mobile, it will just be ignored. The primary server should see this and it should be OK and not break things but would be good to make a new issue to add prescriber merging functionality?

**Comment by wlthomson** [comment]
@joshxg Ah sorry, out of the loop!

In that case, I think best to handle that in this issue.  AFAICS, shouldn't be much work, just be a case of adding prescriber to the table constants?

**Comment by joshxg** [comment]
@wlthomson honestly I dunno with merging and that `mergeRecord` is a disaster 🤣

**Comment by wlthomson** [comment]
Fixed by #3004.

**Comment by nishaSussol** [comment]
Tried in mobile v6.0.0RC2

### Setup
   - [x] Create two prescribers (prescriber_a and prescriber_b) on a non-local store.
   - [x] Make both prescribers visible on mobile store using lookup API.
   - [x] Create a prescription associated with prescriber_b on mobile. **-FAILED-**
   - [ ] Merge prescriber_b into prescriber_a.

Hi @wlthomson ,
The changes are not seen in v6.0.0RC2.
After creating prescription associated with prescriber_b on mobile, there is a sync error, and thus I can't continue with next test steps. Is this an issue for v6?
![Screenshot_2020-07-28-14-31-23-537](https://user-images.githubusercontent.com/59193490/88642603-6ab94580-d0e0-11ea-8d24-f3a9f2cb86e8.jpeg)

**Comment by wlthomson** [comment]
@nishaSussol Definitely an issue for `v6`! 

Could you make a new issue for this (and @wlthomson)? From your description, it sounds unrelated to merge as it look's like desktop is rejecting non-local prescriber/clinician records being synced from mobile.  Small possibility it's a desktop bug, but most likely mobile is sending bad data. Could be a few reasons for this, but can see some bugsnagged errors which might be related.
