### ISSUE TITLE
Insurance discount rate not displaying correctly in payment summary

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2994]
## Describe the bug

Insurance discount rate does not display correctly in the payment window.

### To reproduce

1. Create a new prescription for items with a non-zero sell price.
2. Create/select an insurance policy.
3. Note that the insurance discount amount correctly updates, but the rate remains `"0%"`.

### Expected behaviour

Discount rate should update correctly in payment window.

### Proposed Solution

Fix up existing discount rate selectors and add wrapper for payments for consistency with `discountAmount`.

### Version and device info

- App version: v4.0.4.
- Tablet model: Android emulator (Nexus 10).
- OS version: API 28.

### Additional context

N/A.

**Comment by ArpitaSussol** [comment]
Tested in 5.1.0

## Testing


- [x] When selecting an insurance policy in the payment window,  the insurance discount rate updates correctly.
- [x] After creating a new insurance policy in the payment window,  the insurance discount rate updates correctly.
- [x] Edit an insurance policy in the payment window (ensure the policy has a discount rate which differs from the default of `25`). Cancel without making any changes. Create a new insurance policy. The insurance slider is reset to the default value of `25` (not the value of the previously edited policy).
- [x] Create an insurance policy in the payment window. Cancel without creating the policy. Edit an existing policy (ensure the policy has a discount rate which differs from the default of `25`). The insurance slider is set to the correct value (not the default value of `25`).
