### ISSUE TITLE
Initial/Url Mobile sync shows Dashboard for fraction of second without login

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#2998]
## Describe the bug

Initial/Url Mobile sync shows Dashboard for fraction of second without login

### To reproduce

1. Go to mSupply app
2. Enter Primary Server Url, Username and password
3. Sync starts and after it finishes redirect to dashboard screen (fraction of second) and then displays login screen.
https://recordit.co/NnLfMYOEHM

### Expected behaviour

After sync completes, it clearly redirects to Login screen.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.1.0
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
good one thanks @ArpitaSussol !

**Comment by joshxg** [comment]
I've had a look at this and this is due to the overal design of using modals, which needs a larger refactor. This issue will be taken care of by #1539
