### ISSUE TITLE
Insurance policies from lookup API are inactive (v6)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#3006]
## Describe the bug

All insurance policies from lookup API are inactive.

### To reproduce

1. Add a patient with at least one active policy using lookup API.
2. Dispense to the patient. Navigate to the payment summary page.
3. Note that the active policy is listed as inactive in the policy dropdown.

### Expected behaviour

Active policies should remain active when added to mobile via the lookup API.

### Proposed Solution

Will need to do a fix for `v4` and `v5` majors.

Problem looks like `parseBoolean` is being called on a value which is a boolean (as opposed to a string). Most defensive solution (although a bit hacky), is to make a small fix to `parseBoolean` to ensure booleans are correctly parsed (currently `parseBoolean(true)` returns `false`).

### Version and device info

- App version: v5.1.0.
- Tablet model: Nexus 10 (emulated).
- OS version: API 28.

### Additional context

N/A.

**Comment by wlthomson** [comment]
Closed by #3007.

**Comment by nishaSussol** [comment]
## Testing
Tested in mobile v6.0RC3

Steps to reproduce or otherwise test the changes of this PR:
- [x] Active policies for patients looked up via lookup API are displayed as active. **-PASS-**
- [x] Inactive policies for patients looked up via lookup API are displayed as inactive. **-PASS-**
