### ISSUE TITLE
Insurance: "-" should not be added in absence of Family Policy Number

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3015]
## Describe the bug

"-" should not be added in absence of Family Policy Number

### To reproduce

1. Go to Mobile apk -> create a Prescription
2. Add an insurance such that Family Policy number is blank/empty
3. Finalize and sync
4. GO to Desktop store. Check the following prescription
4. See error. "-" is shown as prefix to Personal Policy Number
![Screen Shot 2020-07-10 at 12 02 12 PM](https://user-images.githubusercontent.com/58979436/87123101-d65c7f80-c2a5-11ea-969b-d9287744bce2.png)

### Expected behaviour

"-" should be removed in absence of Family Policy Number

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.1.1
- Tablet model:
- OS version:

### Additional context

arises while testing #2918

**Comment by wlthomson** [comment]
Fixed by #3030.

**Comment by ArpitaSussol** [comment]
Tested in V6.0.0 rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Policies with personal numbers are correctly formatted after being synced from mobile to desktop  (`familyNumber-personalNumber`). - **PASS**
- [x] Policies without personal numbers are correctly formatted after being synced from mobile to desktop  (`familyNumber`). - **PASS**
