### ISSUE TITLE
insurance form policy number ordering with "-"

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3016]
## Describe the bug

Family Policy number should be placed before Personal Policy number separated with "-"

### To reproduce

1. Go to Patient -> Create prescription.
2. Add insurance both family and personal policy number.
3. See error. Personal policy number is placed before Family policy number

![Screen Shot 2020-07-10 at 12 17 20 PM](https://user-images.githubusercontent.com/58979436/87124267-2dfbea80-c2a8-11ea-9fb9-0a8e2ec25d2c.png)
![Screen Shot 2020-07-10 at 12 16 24 PM](https://user-images.githubusercontent.com/58979436/87124270-2fc5ae00-c2a8-11ea-96d3-ebd3da0f0b0e.png)
![Screen Shot 2020-07-10 at 12 16 06 PM](https://user-images.githubusercontent.com/58979436/87124272-305e4480-c2a8-11ea-83ef-24348408094a.png)

### Expected behaviour

Family policy number should be placed before personal policy number separated with "-"

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.1.1
- Tablet model:
- OS version:

### Additional context

arises while testing #2919

**Comment by wlthomson** [comment]
Fixed by #3029.

**Comment by ArpitaSussol** [comment]
Tested in V6.0.0 rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Policies with personal numbers are displayed as `familyNumber-personalNumber`. - **PASS**
- [x] Policies without personal numbers are displayed as `familyNumber`. - **PASS**
