### ISSUE TITLE
Suppliers are not visible on Mobile when creating a supplier invoice even if a supplier exists and visible on Desktop 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3039]
## Describe the bug

No suppliers are displayed when creating a new supplier invoice. Even when searching for a supplier doesn't find anything even there is a supplier that exists. I was using CSNZERE site in Ivory coast. The district Sanitaire de Yamassoukro is visible for that site and sync is working. So either Suppliers are not syncing to mobile or they do but are not displayed.  

![image](https://user-images.githubusercontent.com/11624516/88109962-625d8980-cb79-11ea-8261-225d38f1b605.png)

![image](https://user-images.githubusercontent.com/11624516/88110639-8b324e80-cb7a-11ea-96f2-f7981d6a7990.png)

### To reproduce

1. Go to Supplier invoice
2. Click on 'New Invoice'
3. No supplier is displayed. Type in for a supplier in the search box
4. See error. Nothing is found

### Expected behaviour

Should be able to choose a supplier when creating a new supplier invoice

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 6.0.0 RC0
- Tablet model:  Samsung Galaxy tab A 10.1
- OS version: Android

**Comment by joshxg** [comment]
Hi @alainsussol 

On mobile, you can only create invoices for external suppliers - no invoices can be manually created for internal suppliers (they should be coming through sync). Would that be the problem here?

**Comment by joshxg** [comment]
Gonna assume that was the issue!
