### ISSUE TITLE
Creating a location seems to create another location with an empty code field

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3040]
## Describe the bug

I am not sure how it happened but I tried to create a new location and found myself also with an extra location record with all fields empty including the location code. Now Mobile is crashing each time I click on the Vaccines button.

![image](https://user-images.githubusercontent.com/11624516/88112026-07c62c80-cb7d-11ea-807b-6c6f48817200.png)

### To reproduce

Have vaccine module store preference on
1. Click on the Vaccines button
2. Click on 'Admin' button
3. Go to location and create anew location.

### Expected behaviour

Should not create an extra record without a code

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v6.0.0RC0
- Tablet model: Galaxy tab A 10.1
- OS version: Android

### Additional context

Testing Vaccine module

**Comment by joshxg** [comment]
Semi-closed by #3044. Still a potential issue with creating multiple locations with empty descriptions and codes which I have been unable to create. The crash is fixed though!!!
