### ISSUE TITLE
Sync error in v6

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3041]
## Describe the bug

Sync issue in v6.0 - `undefined is not an object (evaluating 'n.toString')

### To reproduce

1. As in the screenshot - this was trying to sync with `demo_store31` on `demoivory.msupply.org`

### Expected behaviour

1. No error
2. Bug snagged?

### Additional context

![Screenshot_20200722-102419_mSupply Mobile](https://user-images.githubusercontent.com/9192912/88113768-99c64780-cc06-11ea-8718-324517094bbc.jpg)

**Comment by joshxg** [comment]
Closed by #3043
