### ISSUE TITLE
Unable to put a requested quantity in a supplier requisition of an item that has been set as a vaccine on the cloud server

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3045]
## Describe the bug

The virtual keyboard is displayed for a fraction of a second and then disappear. I can put quantity for other items though.

 

### To reproduce

1. Log on the cloud server
2. Open an item and checked the box Is vaccine? in the general tab, set the restricted area to the location of mobile. Have the sync_out records sync back to the mobile site 
![image](https://user-images.githubusercontent.com/11624516/88227229-4a4e3e80-cc3b-11ea-9db3-e5bd105b7c81.png)

3. On mobile, create a new supplier requisition for the program where the the vaccine item is included and try  requested quantity to that item.

### Expected behaviour

Should be able to put a quantity for items that has been set as a vaccine

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v6.0.0RC1
- Tablet model:Galaxy tab A 10.1
- OS version: Android

### Additional context

Using Ivory coast N'zere and cloud server for testing

**Comment by joshxg** [comment]
Spoke to alain - he mentioned that he tried to recreate this again and was unable to - so an inconsistent bug. I think it's seems similar to the other keyboard disapearing bugs we've been coming across. Super annoying for a user, but solveable through pressing 'next' on the keyboard, usually.

I think it mainly occurs when you're pressing on a cell which would normally be under the keyboard, and the underlying scrollview can't scroll higher to make the cell above it. 

I think we need to investigate more keyboard avoiding options!

**Comment by joshxg** [comment]
Being consolidated into a single issue #2941
