### ISSUE TITLE
Realm Explorer doesn't show any rows in a built APK

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3048]
## Describe the bug

In a release APK, the `RealmExplorer` page doesn't show any fields after searching.

### To reproduce

1. Go to release and download an apk!
2. Sync etc, and go to RealmExplorer
3. Add an object to search for which you know there are records for
Optional 5. Do the same thing in a develop build. See rows!

### Expected behaviour

Should show rows

### Proposed Solution

I'm not sure of an exact solution as I don't know really the cause. However I believe it is to do with:

https://github.com/openmsupply/mobile/blob/f97a07481663f759082e8c70e8fb62e35934c0be/src/pages/RealmExplorer.js#L63-L74

These lines actually cause me issues when starting the app in debug mode (requires node killing, cache clearing etc etc to start it). If you for example replace:

https://github.com/openmsupply/mobile/blob/f97a07481663f759082e8c70e8fb62e35934c0be/src/pages/RealmExplorer.js#L76-L77

These two lines with:

```
const REALM_OBJECTS = ['Sensor'];
const REALM_OBJECTS_FIELDS = {
  Sensor: {
    id: 'string',
    macAddress: 'string',
    name: 'string',
  },
};
```

For example, and rebuild an APK (of course making sure you have a `Sensor`!), then rows for Sensor show.

Also, if I replace:

https://github.com/openmsupply/mobile/blob/f97a07481663f759082e8c70e8fb62e35934c0be/src/pages/RealmExplorer.js#L63-L65

the `.map({schema: ..)}` with just `.map(objectSchema)` then my debugging problem does away..! very strange :)

### Version and device info

- App version: 6.0+ at least
- Tablet model: Lenovo. Causing a crash on a Samsung, apparently (Alain)
- OS version: N/A

### Additional context

This code is nicely dynamic. Would hate to ruin it, but I think just adding basic objects as above for sensor might be the easiest solution.. :(

**Comment by mark-prins** [comment]
🤦  The `REALM_OBJECTS` array has munged values in it `['i','j'...]`
This is why the static version above would work, and why the release build blows up when you ask for a table 'i'
It exists in the `REALM_OBJECTS` array, but isn't a valid table in the database.

**Comment by joshxg** [comment]
Ha wow.. ok.. detective 🕵️

**Comment by ArpitaSussol** [comment]
@joshxg i am not sure the proper way/format of searching object and string in Realm Explorer.

Can you provide sample for searching in Realm explorer please?

**Comment by joshxg** [comment]
```
Name
lastName CONTAINS[c] 'a'
```

or

```
Name
firstName CONTAINS[c] 'b'
```

or

```
Item
code CONTAINS[c] 'a'
```

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Explore. With Realm
