### ISSUE TITLE
Auto-finalise prescriptions received from sync which are not finalised

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3051]
## Describe the bug

Currently mobile deletes confirmed prescriptions that come through sync. Currently mobile doesn't allow confirmed prescriptions, you either finish and finalise it or it gets deleted. Any coming through sync being deleted is a side affect of that.

### To reproduce

1. Have a desktop dispensary.
2. Finalise all prescriptions/customer invoices.
3. Make some prescriptions (say 5), but do not finalise them.
4. Make a new sync site and make the desktop dispensary active on it.
5. Get a fresh copy of mobile and synchronise with the new sync site.
6. It shows a badge on customer invoices of how many confirmed invoices there are (say 5, however many you made earlier).
7. Click on customer invoices and see none.
8. Sync mobile.
9. On central server, the collector copy of the dispensary store no longer has the prescription.
10. This isn't ideal, it's safer to assume confirmed prescriptions made on desktop are valid and part of the patient's history.

### Expected behaviour

Confirmed prescriptions aren't deleted by mobile. It's fine that mobile UI doesn't allow for creating confirmed prescriptions, but any historic ones coming through sync shouldn't be deleted.

### Proposed Solution

If mobile receives prescriptions via sync that are confirmed, mobile should finalise them and sync status update back to the central server. 

### Version and device info

- App version: 5.1.0
- Tablet model: Samsung tabA SM-T580
- OS version: 8.1.0

### Additional context

Alternatively could just not delete them, but do some work to bring up the prescription wizard so that the user can finalise them. But then if they cancel does it keep or delete? Weird conditions, yuck.

**Comment by joshxg** [comment]
there *shouldn't* be any transactions from other patients - we got bigger problems if there are!

**Comment by wlthomson** [comment]
> there _shouldn't_ be any transactions from other patients - we got bigger problems if there are!

Hmm, IIRC we don't currently sync transactions for patients looked up via the API, but I think we will need to view patient history for non-local patients? Maybe being overcautious, but wondering if handling things desktop side might still be the best solution (mainly because unfinalised prescriptions are useless to mobile anyway, so if nothing else its a few bits less over the wire)?

**Comment by Chris-Petty** [comment]
@wlthomson 

> The whole confirmed v. finalised prescription thing is a bit messy in mobile, as technically mobile doesn't support unfinalised prescriptions. This is a deliberate design decision, as the alternative is a bit messy (@joshxg for more background).
> 
> As far as I can tell, the proposed solution is OK, but I think there might be some potential edge cases to think through (e.g. can mobile finalise read-only prescriptions?) A potentially more robust solution might be to ask desktop not to add any unfinalised prescriptions to the sync out queue for stores active on mobile sites?

I'm wary that fixing on server via sync leans towards making separate desktop, mobile and client+1 sync APIs (albeit kinda hacked in for this case, but once you have 10 hacks you've just got messy separate APIs). I don't think that's a road we should go down, or at least if we do, it should be a RESTful way.

Another way to look at it is how it affects the compatibility matrix:
Server fix: Mobile 5.1.**X** should not be used with any mSupply Server version before whichever one we fix this in.
Mobile patch: Specifically mobile 5.1.**0** should not be used with any mSupply Server version before whichever one we fix this in.

Also I think desktop knowing site client type is a bit shaky (though I may be mistaken). The current iteration just makes sync v1 requests "standalone" and otherwise "mobile". Up until the site wizard in 4.12.0, the site.type is not actually set other than that sync version correlation.

> > there _shouldn't_ be any transactions from other patients - we got bigger problems if there are!
> 
> Hmm, IIRC we don't currently sync transactions for patients looked up via the API, but I think we will need to view patient history for non-local patients? Maybe being overcautious, but wondering if handling things desktop side might still be the best solution (mainly because unfinalised prescriptions are useless to mobile anyway, so if nothing else its a few bits less over the wire)?

If they can prescribe to them, I think syncing the histories for non-local patients should be necessary. An essential part of the prescriber's role is to make sure they're not prescribing something that may interact dangerously with prior prescriptions.

**Comment by joshxg** [comment]
> Hmm, IIRC we don't currently sync transactions for patients looked up via the API, but I think we will need to view patient history for non-local patients? 


*If* mobile gets transactions from other sites I don't see the problem with just not touching them at all.


> If they can prescribe to them, I think syncing the histories for non-local patients should be necessary. An essential part of the prescriber's role is to make sure they're not prescribing something that may interact dangerously with prior prescriptions.

Yup - not part of the 'spec' 🤷

**Comment by Chris-Petty** [comment]
> Yup - not part of the 'spec' 🤷

Given Will's phrasing, if a patient _is local_ to the site, does it get history synced?

**Comment by joshxg** [comment]
You get the transactions for patients which are 'local', yeah

**Comment by Chris-Petty** [comment]
> You get the transactions for patients which are 'local', yeah

Right, yea. Duh. I seem to recall some discussion of a compressed history thing but fair enough if that didn't happen!

**Comment by joshxg** [comment]
Closed by #3216
