### ISSUE TITLE
Sync error after creating prescription associated with non-local prescriber

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#3055]
## Describe the bug
Sync error after creating prescription associated with non-local prescriber.

### To reproduce
1. Create a prescriber on a non-local store.
2. Now, on mobile store, make it visible using Lookup API
3. Create a prescription associated with that prescriber on mobile
4. Sync manually. See the error about server rejecting pushed records.

### Expected behaviour
There shouldn't be such sync error.
![Screenshot_2020-07-28-14-31-23-537](https://user-images.githubusercontent.com/59193490/88658195-c4c30680-d0f2-11ea-8794-03d29591a0bb.jpeg)

### Version and device info
- App version: v6.0.0RC2

### Additional context
Found while testing #2991

**Comment by joshxg** [comment]
Sorry this has taken so long. I have retested this on RC10 @nishaSussol and I am unable to recreate.

Prescriber I found from the lookup API:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/35858975/99861981-083f0480-2bfd-11eb-903f-f62516834177.png">


Dispense to a patient:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/35858975/99861990-0f661280-2bfd-11eb-808b-172456988dec.png">
<img width="927" alt="image" src="https://user-images.githubusercontent.com/35858975/99861997-155bf380-2bfd-11eb-8586-266c91c59e5e.png">

Confirm:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/35858975/99862001-1a20a780-2bfd-11eb-8285-8ab9d2d84697.png">

Sync:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/35858975/99862018-23aa0f80-2bfd-11eb-833a-64331b0bc5e8.png">
<img width="927" alt="image" src="https://user-images.githubusercontent.com/35858975/99862024-26a50000-2bfd-11eb-8f7a-e47ae8e30fb0.png">

So I suppose it's been fixed somehow!!

If you think that it still occurrs, please comment again and I will reopen the issue.
