### ISSUE TITLE
Mobile may be blanking out some fields set by desktop?

### ISSUE THREAD

**Issue by adrianwb** [openmsupply/mobile#3056]
## Describe the bug

From investigation of a support issue for MAM (https://support.msupply.org.nz/cerb6/profiles/ticket/QJ-2718-ID), some strange behaviour has been noted for stock transfers to a mobile site (Matupi), which is consistent with mobile blanking out the `[transact]linked_transaction_id` field.

From the journal files on the cloud server:

![image](https://user-images.githubusercontent.com/6196269/88816776-acb3bb80-d1b4-11ea-989a-7ac6b6406235.png)

The left window shows the SI being created, with an initial invoice number of -1 (as expected), and a link back to the original CI (from the Yangon store), and the right window shows it being received back from the tablet about a week later (bad internet!) with the invoice number assigned (as it should be), but with the `linked_transaction_id` reset back to blank.

Doing a query for finalised SI's from stock transfers in the MAM data, with blank links, shows over 300!

![image](https://user-images.githubusercontent.com/6196269/88817544-8b9f9a80-d1b5-11ea-88fe-d29748348b22.png)

There is code in desktop mSupply which _sets_ the link if it is missing (previous version update), but I can find nothing which _unsets_ it... 

### Additional context

Mobile ignores fields that it doesn't "understand" (i.e. which aren't in its schema), and desktop sync will only update fields which are included as part of the sync record. If this is a genuine issue (and not a red herring), then we need to make sure that the same thing isn't happening for any other fields which mobile doesn't support.

**Comment by Chris-Petty** [comment]
Just had a peek at sync processing code on mobile.

1. Incoming records does not save 'linked_transaction_id'
2. Outgoing records does send 'linked_transaction_id'

If I'm not mistaken, if mobile receives a transaction and touches it, it will sync it back to the server and blank the foreign key.

**Comment by wlthomson** [comment]
> Just had a peek at sync processing code on mobile.
> 
> 1. Incoming records does not save 'linked_transaction_id'
> 2. Outgoing records does send 'linked_transaction_id'
> 
> If I'm not mistaken, if mobile receives a transaction and touches it, it will sync it back to the server and blank the foreign key.

Will get a fix for this now and release as part of `5.1.2`.

**Comment by adrianwb** [comment]
Thanks for confirming my suspicions. Can you also check that the same problem doesn't affect any other fields - I'm thinking particularly of the `[requisition]linked_requisition_id` which does the same thing...

**Comment by Chris-Petty** [comment]
`[requisition]linked_requisition_id` is neither sent nor received by mobile. 
`[requisition]linked_requisition_line_ID` is neither sent nor received by mobile.

For these, I see no harm done on __mobile__ as it doesn't use them, given it doesn't have them! But, assuming the link is both ways, if mobile touches the response requisition and updates it, it will wipe out the field on the primary. The request will still have the link, but it's a bit dodgy. Any desktop site with a collector copy may not behave correctly if using that field, or for reporting. So they should be maintained

`[transact]requisition_ID` is maintained on both.
`[trans_line]linked_transact_id` is not received, but is sent!

Can you think of any other important foreign keys I should investigate? Other than... all of them 😰 .

If you're curious, mobile just has a big ol' switch that maps sync record fields to its DB fields for incoming records and vice versa for outgoing. [incomingSyncUtils](https://github.com/openmsupply/mobile/blob/master/src/sync/incomingSyncUtils.js#L258) and [outgoingSyncUtils](https://github.com/openmsupply/mobile/blob/master/src/sync/outgoingSyncUtils.js#L47) respectively.

**Comment by wlthomson** [comment]
Fixed by #3057.
