### ISSUE TITLE
Active insurance policies in desktop site show as inactive in mobile

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#3064]
## Describe the bug
Active insurance policies in desktop site show as inactive in mobile

### To reproduce
1. Create a patient on desktop site with an associated insurance policy.
2. Add that patient on mobile using the lookup modal.
3. Create a prescription for that patient.
4. See the insurance policy. See all the policies show inactive (though they are active in desktop site)

### Expected behaviour
Active insurance policies must not show as inactive.

### Screenshots
![Screenshot_20200803-171242_mSupply Mobile](https://user-images.githubusercontent.com/59193490/89179462-7492eb00-d5af-11ea-9b8d-2aa595a66f27.jpg)
![Screen Shot 2020-08-03 at 17 13 20](https://user-images.githubusercontent.com/59193490/89179472-78bf0880-d5af-11ea-9eb0-75db2c998bad.png)

### Version and device info
- App version: v412
- Tablet model: v5.0.3

### Additional context
Found while testing #2916

**Comment by wlthomson** [comment]
This should be fixed in `v5.1.1` (and `v6.0.0-rc3`). Have you tested on those versions or later?

**Comment by nishaSussol** [comment]
Yes, can't replicate on `v5.1.1` (and `v6.0.0-rc4`). This seem to be already fixed. Can be closed!
