### ISSUE TITLE
Unfinalised prescription still adding to the sync queue

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3075]
## Describe the bug

Create a new prescription. While the wizard is open, open the sync modal.  records have been added to the sync queue.

### To reproduce

1. Go to Dispensary
2. Click on Patient 
3. Click on Prescriber. Manual sync upto this stage.
4. Click Dispense action link
5. Once the prescription modal is open. Check sync modal. Now  it shows Records waiting that means it send prescription  records to sync queue even if the prescription is not finalized
https://recordit.co/uGlDhIOM4o

### Expected behaviour

Until the prescription is not finalized, record should not be send to Sync queue.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V6.0.0 rc2
- Tablet model: Nexus 25
- OS version: Android

### Additional context

Please check the recorded video for more clarfiication. is that the intended behavior?

**Comment by joshxg** [comment]
Have tested and the actual prescription is not sent. Yes, it is a little confusing that it says there are records to be sent, but those are `sync_out` records which don't result in sending the prescription to the server and to actually not create the sync outs is a bit of work that shouldn't be done - so, closing
