### ISSUE TITLE
Edit Insurance: not allowing "Save" button to be enabled

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3078]
## Describe the bug

Editing insurance is not allowed.

### To reproduce

1. Create Prescription
2. Add New insurance
3. Now click on Edit icon of newly created insurance
4. See error. "Personal Policy number", "Policy Provider" and "Policy Type" is disabled. "Discount rate" and "Is Active" is editable but updating fields is not enabling Save button.
https://recordit.co/U536rlkTAW

### Expected behaviour

After updating insurance with given enabled fields, save option should be enabled and updated the insurance

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V6.0.0 rc3
- Tablet model: Nexus 25
- OS version: android

### Additional context

arises while testing #3015

**Comment by joshxg** [comment]
Cannot recreate this error now @ArpitaSussol  - if you still are able to, please reopen!
