### ISSUE TITLE
Sorting stock take lines app crashing

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3081]
## Describe the bug

Creating a new stock take and sorting the stock take lines - mSupply app crashed.

### To reproduce

1. Create a new stock take give a name
2. Add lines
3. Tap `Hide stockouts` and `All items selected`
4. remove `Hide stockouts`
5. Do sorting with Name few times and then do sorting with code
6. See app crashing

https://www.dropbox.com/s/s099isl34qcgo0q/video_2020-08-06_16-37-04.mp4?dl=1

### Expected behaviour

No crashing

### Proposed Solution

See Mobile captain @Chris-Petty 

### Version and device info

- App version: v6.0.0-rc4
- Tablet model: Samsung 
- OS version: Android 9

**Comment by joshxg** [comment]
Closed by #3087
