### ISSUE TITLE
Requisition is received without requisition lines

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#3084]
## Describe the bug

If we create request requisition from one tablet to another. Another Tablet gets requisition without requisition lines.

### To reproduce

1. Create Supplier requisition in a tablet.
2. Then directly Finalised it. (Note need to finalize directly)
3. Sync the finalized Supplier req.
4. Sync in another tablet and check customer requisition.

### Expected behaviour

Response Requisition with requisition lines needs to be synced to the tablet.

### Proposed Solution

As discussed if we can change the order of syncing requisition if it's directly finalized. May be the first requisition_line then requisition. 

### Version and device info

- App version: 5.1.1
- Tablet model: Lenovo

**Comment by anildahalsussol** [comment]
Getting support from Myanmar.

**Comment by joshxg** [comment]
Closed by #3092
