### ISSUE TITLE
Stock transfer is received without trans lines

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#3085]
## Describe the bug

If we create a stock transfer from one tablet to another. Another Tablet gets transaction without trans lines.

### To reproduce

1. Create a Customer invoice on a tablet.
2. Then directly Finalised it. (Note need to finalize directly)
3. Sync finalized Customer invoice.
4. Sync in another tablet and check the Supplier Invoice.

### Expected behaviour

SI with trans-lines needs to be synced to the tablet.

### Proposed Solution

As discussed if we can change the order of syncing transaction if it's directly finalized. Maybe the first trans_line then transact. 

### Version and device info

- App version: 5.1.1
- Tablet model: Lenovo

### Additional context

Problem faced in MAM.

**Comment by bijaySussol** [comment]
@joshxg @wlthomson @anildahalsussol : 

Could this be related with the item not being visible to an another tablet store?
This can happens on desktop, sender can do a stock transfer to another store even if that transferring item is not visible to another store - and the receiver store end up with blank lines against supplier invoice.
Just thought to share - things might be different - as 2 tablet access the 2 different store chances of having item not visible is high on either of the store and desktop does not bother to check the visibility.

**Comment by joshxg** [comment]
Fixed by #3088
