### ISSUE TITLE
After Finalisation of supplier invoice > App crashed.

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3094]
## Describe the bug

Creating supplier invoice and finalising it > mSupply mobile app crashed

### To reproduce

1. Create a new supplier invoice
2. Add Line > Fill in the details
3. Once that details is filled in > Tick that lines > Remove
4. Create new line again - fill in the details
5. Finalise it
6. Tap **Remove** from Alert box which says: Are you sure you want to remove these items?
7. See app crashed

### Expected behaviour

No crashing of app

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.1.1
- Tablet model: Samsung Tablet Galaxy Tab A (SM-T515)
- OS version: Android 9

**Comment by wlthomson** [comment]
Can replicate on `v5.1.2-rc1`. Problem is caused by attempting to delete finalised items. I think best way to fix this is probably to close the delete modal on adding a new line? Might also be worth adding a check to the modal.

**Comment by ArpitaSussol** [comment]
Tested in 5.1.2

### Tests

- [x] Create a new supplier invoice
- [x] Add Line > Fill in the details
- [x] Once that details is filled in > Tick that lines > Remove
- [x] Create new line again - fill in the details
- [x] Finalise it
- [x] Alert box which says: Are you sure you want to remove these items? is not shown.

**Comment by joshxg** [comment]
Closed by #3112
