### ISSUE TITLE
After Finalisation of customer invoice > App crashed

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3096]
## Describe the bug

Creating customer invoice and finalising it > mSupply mobile app crashed

### To reproduce

1. Create a new customer invoice
2. Add Line > Fill in the details
3. Once that details is filled in > Tick that lines > Remove
4. Create new line again - fill in the details
5. Finalise it
6. Tap Remove from Alert box which says: Are you sure you want to remove these items?
7. See app crashed

### Expected behaviour

No crashing of app

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.1.1
- Tablet model: Samsung Tablet Galaxy Tab A (SM-T515)
- OS version: Android 9

**Comment by wlthomson** [comment]
Just to clarify, description says customer invoice, but replication steps say supplier invoice? 

Tried to replicate on both, but can't get a crash. Can you confirm crash is still occurring on `v5.1.2-rc1`?

**Comment by bijaySussol** [comment]
> Just to clarify, description says customer invoice, but replication steps say supplier invoice?

@wlthomson : Good catch - I have corrected now

> Tried to replicate on both, but can't get a crash. Can you confirm crash is still occurring on v5.1.2-rc1?

I will create a video and link it 

thanks

**Comment by ArpitaSussol** [comment]
Tested in v5.1.2

### Tests

- [x] Create a new customer invoice
- [x] Add Line > Fill in the details
- [x] Once that details is filled in > Tick that lines > Remove
- [x] Create new line again - fill in the details
- [x] Finalise it
- [x] Alert box which says: Are you sure you want to remove these items? is not shown.

**Comment by joshxg** [comment]
Closed by #3113
