### ISSUE TITLE
Add sdkmanrc for default java implementation

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#3100]
## Is your feature request related to a problem? Please describe.

When devving on windows, the `sdkman` java has to be set for each terminal. Would be helpful to add a `.sdkmanrc` file to make this easier and to ensure everyone is testing/building using the same version of java.

## Describe the solution you'd like

Add `.sdkmanrc` file with chosen java version.

## Implementation

See https://sdkman.io/usage.

## Describe alternatives you've considered

Leave as is.

## Additional context

Not too worried about the vendor, currently using `11.0.7.hs-adpt`, as that seems to be the most consistent for me, but if others want to suggest another default vendor/version, ok with that, too!

**Comment by joshxg** [comment]
I currently use 8.0.202-zulu  - Should we be using the 'lowest' version supported? Java 8 seems to be fine

**Comment by joshxg** [comment]
Closed by #3214
