### ISSUE TITLE
Deleting stock take from mobile doesn't get deleted from desktop store

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3103]
## Describe the bug

Stock take deletion from the Mobile does not delete it from the desktop store.

### To reproduce

1. Create a new **Stocktake**
2. Choose any 3 lines and create the **stocktake**
3. Add **quantity** against those line the tap on **Manage stocktake**
4. Then **SYNC**
5. Click on **remove** checkbox and tap on the same **stocktake** takes to its details
6. tap on **Manage stocktake** remove 1 selected line from existing
7. Then click on **Confirm**
8. Go back to your **stocktake list**
9. From **Are you sure you want to remove these items?** click **remove**
10. Then **SYNC**
11. Go back to the **desktop store** - You will still see that stock take with no lines

### Expected behaviour

If mobile deletes that stock take that stock take must be deleted for desktop as well.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.1.1
- Tablet model: Samsung Tablet Galaxy Tab A (SM-T515)
- OS version: Android 9

### Additional context

See this video for recreating procedure:
https://www.dropbox.com/s/a8gcm6mnby563aw/stock%20take%20not%20deleted.mov?dl=0

**Comment by wlthomson** [comment]
Could replicate and fix by adjusting what looks like a bug in the `SyncQueue` update logic.

Will make a PR for this now.

**Comment by bijaySussol** [comment]
tested with v5.1.2-rc3 - Working nicely

**Comment by nishaSussol** [comment]
Tested in mobile v5.1.2
- [x] Cannot be replicated anymore
