### ISSUE TITLE
Revert sync ordering logic

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#3107]
## Is your feature request related to a problem? Please describe.

Bug fixed in #3106 is likely to have been the cause of the unordered sync queue. Although sorting logic fixed the immediate symptoms of the bug, it does not correctly sort all records (`recordType` comparisons only define a partial order). For these reasons the changes should be reverted.

## Describe the solution you'd like

Remove the sync queue `isParentOf` ordering logic.

## Implementation

See above.

## Describe alternatives you've considered

Leave as is?

## Additional context

@andreievg.

**Comment by joshxg** [comment]
Closed by #3111
