### ISSUE TITLE
When a restricted location of an item has been changed on desktop, should a message be sent to mobile to relocate that item 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3124]
## Is your feature request related to a problem? Please describe.

I don't think this would happen very often. But let's say you have an item that has a restricted location type and this restriction is changed to another location type (on the desktop). I was wondering if the mobile user should not then receive a warning to relocate the stock of that item to the new type of location ? 

Example: Item A is restricted to location type 1 and the stock that has been received for item A has been located in location type 1. If on the desktop I restrict the Item A to location type 2 instead of 1, then the stock of item A needs to be relocated to a location of location type 2. Does that make sense ?  

## Describe the solution you'd like

A message appear on login OR after syncing AND/OR the lines with the previous location should not have a warning icon that stays there until the item is relocated to the new restricted area

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**
Doing nothing since it might never happen or it might be simply that task of the competent authority to communicate the change to the user of the mobile site

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by joshxg** [comment]
Interesting!

This is a good idea, I think! Do you mean similar to on desktop currently there are 'notes' when you log in?

I think it might be a little out side the scope, currently, but will ask the more senior people what we can do about this one!

**Comment by joshxg** [comment]
We're going to remove this restricted location type feature for vaccine module, so this will be fixed!
