### ISSUE TITLE
Temperature Breach are not triggered/shown even when temperature breach would normally happens 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3125]
## Describe the bug

A clear and concise description of what the bug is. Use screenshots!

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
@alainsussol 

Sorry, a little unclear on what the problem is on this one!!

**Comment by alainsussol** [comment]
Yes sorry, I put it there quickly Friday without any details as I felt my temperatures were in the range of a temperature breach but I was not having any temperature breach warning on the customer invoice or Vaccine graph. However I realized that even though there is no error during syncing I didn't receive anything temperature log since the 9th. So will close this until I can discover what is happening

**Comment by alainsussol** [comment]
@joshxg 
I am reopening this with more info in the description. Why I am certain that you will not be able to duplicate this :)

**Comment by joshxg** [comment]
@alainsussol  

Thanks Alain!! I will look at this today and make SURE I can recreate it
