### ISSUE TITLE
Dispensing: search for items by code

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3130]
## Description
When dispensing, it is possible to search for items by description:

![Screen Shot 2020-09-18 at 1 53 23 PM](https://user-images.githubusercontent.com/9192912/93546262-9658fd80-f9b6-11ea-824d-46d9510f96e9.png)

But you cannot search by code. Would it be possible to expand the search, so that it also searches by code:

![Screen Shot 2020-09-18 at 1 53 45 PM](https://user-images.githubusercontent.com/9192912/93546271-98bb5780-f9b6-11ea-9574-6d8d67d287a2.png)

The `prescription.js` currently uses the search `'name CONTAINS[c] $0', itemSearchTerm`
Include code as well?

**Comment by joshxg** [comment]
Yeah, should just need to change `name CONTAINS[c] $0 || code CONTAINS[c] $0` - this need to be in release soon?

**Comment by mark-prins** [comment]
a client raised it as a concern, so I might pop it in so that we can include in v6. 
Should be fairly low impact
