### ISSUE TITLE
Add header, axis labels to bar chart in mobile dashboard

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#3167]
## Is your feature request related to a problem? Please describe.

Linked with https://github.com/sussol/msupply/issues/6762

## Describe the solution you'd like

- Bar chart needs a header to be shown at top
- Bar chart needs axis labels to show what type of values are being shown in x and y axises

## Implementation

- Code the headed and axis labels in with code
- We also want names to be shown more clearly so we replace names with codes but that bit is done in mSupply side.

## Describe alternatives you've considered

None

## Additional context

None

**Comment by joshxg** [comment]
Closed by #3168 - thanks sworup!
