### ISSUE TITLE
Display size setting for tablet is controlled.

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3174]
## Describe the bug

When enrolled the device onto MDM (MediaPad M5 Lite) for IC - mSupply app against MDM shows an alert message saying: **mSupply Mobile does not support the current display size setting xxxx** 

The display setting against the tablet is controlled.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.3
- Tablet model: MediaPad M5 Lite
- OS version: Android 9

### Additional context

Found this:
https://developer.android.com/work/managed-configurations

**Comment by joshxg** [comment]
Closed by #3177
