### ISSUE TITLE
Customer requisitions: Comment and created date remain editable after finalisation

### ISSUE THREAD

**Issue by chastichno** [openmsupply/mobile#3179]
## Describe the bug

After finalisation customer requisition fields "Comment" and "Created date" are editable.

### To reproduce

1. Create customer requisition and finalise it.
2. Edit comment and created date. Close the requisition.
4. Open requisition again. The comment and date were edited after finalisation.

### Expected behaviour

All the fields should be uneditable after finalisation.

### Version and device info

- App version: 6.0.0-rc7

**Comment by joshxg** [comment]
Closed by #3182
