### ISSUE TITLE
Customer Requisitions: No programs available even if a customer has an available program after selecting the customer which doesn't have an available program

### ISSUE THREAD

**Issue by Mai21** [openmsupply/mobile#3181]
## Describe the bug
1. When a customer which does not have an available program selected after once selecting the customer which has an available program, user can select the program. After user selected the program, app closes.

2. When a customer which has an available program selected after once selecting the customer which does not have an available program, user can not select the program(No programs available). 

### To reproduce

1. Go to Customer Requisitions
2. Click on New Requisition
3. Select a customer which does not have an available program
4. Change a customer which has an available program
5. See a second select box, shows No programs available (bug 2)

6. Close the Requisition Details
7. Click on New Requisition
8. Select a customer which has an available program
9. Change a customer which does not have an available program
10. See a second select box, user can select some program. Select a program
11. App closes (bug 1)

### Proposed Solution
All the time when user changes a customer, need to populate programs based on the customer.

### Version and device info
App version: 6.0.0-rc7

**Comment by chastichno** [comment]
I think issue #3180 has the same problem. Also, I tried to do the same thing for programs (when one customer has multiple programs) and order types was shown only for the program which was selected first. I don't want to create a new issue for that because generally it is just one test case which is not passing:

> - [ ] Can back pedal steps, where the progress is adjusted correctly

**Comment by joshxg** [comment]
Closed by #3184
