### ISSUE TITLE
Customer requisition: 'placeholderName' in Program columns when the internal order created before the first set up.

### ISSUE THREAD

**Issue by Mai21** [openmsupply/mobile#3190]
## Describe the bug

When customer requisition from the internal order without the program created before mSupply mobile set up, table shows 'placeholderName' in Program. After set up, create a customer requisition from the internal order without the program, table  shows 'N/A' in Program. 
![Screenshot_2020-11-05-09-41-53-786](https://user-images.githubusercontent.com/36495540/98184155-91eca200-1f6e-11eb-8f2c-dfae8dedb0da.jpeg)
<img width="1227" alt="Screen Shot 2020-11-05 at 2 00 51 PM" src="https://user-images.githubusercontent.com/36495540/98184485-63bb9200-1f6f-11eb-8e73-dd516d2d083b.png">

### To reproduce

Steps to reproduce the behaviour:
1. [Desktop] Create an internal order to the mobile store without program and an internal order with some program
2. [Mobile] Set up the sync to mSupply mobile
3. [Mobile] Log into the mobile store on desktop -> customer -> requisition
4. [Mobile] See 'placeholderName' in Program
5. [Desktop] Create an internal order to the mobile store without program again
6. [Mobile] Go to desktop -> customer -> requisition
7. [Mobile] Sync
8. [Mobile] See 'N/A' in Program

### Expected behaviour
All customer requisition without program show 'N/A' in Program column.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: Tested in 6.0.0-rc9
- Tablet model: Lenovo TB-X304L
- OS version: Android 8.2.0 

### Additional context

The value in Program by an internal order without program are like this.
- Create an internal order to the mobile store with program and without program then set up -> ‘placeholderName’
- Create an internal order to the mobile store without program then set up, no program column. Create a new requisition -> N/A
- Create an internal order to the mobile store without program then set up, no program column. Create an internal order to the mobile store with program then sync -> N/A
- Create an internal order to the mobile store with program then set up. Create an internal order to the mobile store with program and without program then sync -> N/A

It only happens when there are at least one customer requisition with program and one customer requisition without program each before setting up mSupply mobile. 
If those situation can not happen in the real operation, just please close this issue.

**Comment by joshxg** [comment]
@Mai21 this is fantastic testing, thanks so much. ill look into it more deeply.

**Comment by joshxg** [comment]
Have checked this out properly now, and I can't recreate it! @Mai21 If you're confident this one is a problem maybe you can show me how to recreate? :)

**Comment by Mai21** [comment]
> Have checked this out properly now, and I can't recreate it! @Mai21 If you're confident this one is a problem maybe you can show me how to recreate? :)

I tried to reproduce it but I could not... sorry. 😐

**Comment by joshxg** [comment]
No problemo!
