### ISSUE TITLE
Customer requisition > Sorting by Current stock is much slower then other column

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3194]
## Describe the bug

Sorting using Current stock column from Supply Data - It is much much slower than other column sorting.

### To reproduce

1. Create a response programe requisition
2. Make sure to have some lines - I had < 600 lines < 700
3. Tap on: Supply Data
4. Sort by Current stock column
5. It respond very slowly over other column

### Expected behaviour

see @joshxg verdict.
I do not think why current stock column is way slower than other column - it should be same as a other columns

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: mSupplyMobile-6_0_0-rc9-universal-release.apk
- Tablet model: SM-T515
- OS version: Android 9

**Comment by joshxg** [comment]
Nice find - always the best.

I think this reason is because: The current stock is recalculated for each row when sorting.. but, all the other columns are not. But, basically we need to recalculate because what if the stock is changed..?

So .. maybe just a tablet limitation of being a bit slower.. but, I will check the algorithm, see if we can improve it at all

**Comment by bijaySussol** [comment]
> Nice find - always the best.
> 
> I think this reason is because: The current stock is recalculated for each row when sorting.. but, all the other columns are not. But, basically we need to recalculate because what if the stock is changed..?
> 

For me - I do not think - We need to recalculate the Current stock to pick up the latest current stock if i am not mistaken.

> So .. maybe just a tablet limitation of being a bit slower.. but, I will check the algorithm, see if we can improve it at all

Cheers - You are the GURU!!!

**Comment by joshxg** [comment]
Have had a look and there is not really much we can do here!
