### ISSUE TITLE
Customer requisition does not get set with requisition date

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3196]
## Describe the bug

Customer requisition created from mobile once synced does not get set with requisition date

### To reproduce

1. Create a customer requisition
2. fill in the details required
3. Finalise the requisition
4. Check that requisition from desktop
5. See the requisition date missing

### Expected behaviour

Requisition date should be set

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: mSupplyMobile-6_0_0-rc9-universal-release.apk
- Tablet model: SM-T515
- OS version: Andrioid

**Comment by joshxg** [comment]
Hmmm...

This one is confusing as the date fields are added into the outgoing SYNC:

https://github.com/openmsupply/mobile/blob/cefb892c1091587892e4b52dd1cb15e0240f35c2/src/sync/outgoingSyncUtils.js#L126-L142

So.. I am not sure how this can be - I will need to check further..

**Comment by bijaySussol** [comment]
I think `[requisition]date_stock_take` is missing.

**Comment by joshxg** [comment]
Ah. Hm.

Well, it seems mobile has never sent `date_stock_take`. We have only added `date_order_received` for this new `program customer requisition`.. 

So I suppose not a bug?? @Chris-Petty any thoughts?
