### ISSUE TITLE
mSupply is crashing on startup with v6.0.0RC10

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3201]
## Describe the bug

mSupply is crashing on startup with v6.0.0RC10 after installation. I am not sure why.

### To reproduce

1. Empty application data
2. uninstall previous version of mSupply mobile
3. install v6.0.0 RC10
4. See error. Msupply is crashing

### Expected behaviour

mSupply should open

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 6.0.0 RC10
- Tablet model: Galaxy tab A SM-T510
- OS version: Android 10

**Comment by joshxg** [comment]
ALAIN!!

👍 

I just did some tests. RC10 installs fine by itself, but if it is upgrading anything from about 5.1.2 -> RC5ish, then it will cause a crash, as the schema has changed but there is no bump to the schema version, which we will do just before release.

So if you fresh install the RC it should be fine - let me know if that is not the case, though!

**Comment by alainsussol** [comment]
Hi Josh,

I was testing the vaccine module so the version I had before was 6.0.0RCish but I can't remember which. What I did is erasing the data and the cache of the app, uninstall mSupply and install using the new apk but I will try again and see. It might have to wait until tomorrow though.

Cheers,

Alain

**Comment by joshxg** [comment]
I've tested again today on two tablets and am confident that upgrading from 5.1.2 to 6.0 works correctly, just the upgrading between RC's doesn't.

Of course, I can always be wrong - so will close this for now, but reopen if I am wrong!
