### ISSUE TITLE
SelectModal should show the autocomplete text field higher in the modal

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#323]
Build Number: 19

Description: 
Currently you can only see a few rows between the text field and the keyboard. There is space above to comfortably fit a 2-3 more rows if the field was higher.

Reproducible: Always.

Reproduction Steps: Press new item in customer invoice. Look at the modal. Only observable on tablet.

Comments: Could be debatable. When the keyboard isn't there, it may look odd.

**Comment by joshxg** [comment]
@Chris-Petty

![image](https://user-images.githubusercontent.com/35858975/63236089-84c39480-c290-11e9-9fa2-99bc2c138d85.png)


I see in the user guide it used to be lower - I am assuming it was already moved up as it is not like this anymore

Closing, reopen if I'm incorrect

**Comment by Chris-Petty** [comment]
Thanks, I think I fixed it when rewriting the selector with FlatList #604
