### ISSUE TITLE
Testing manual requisitions

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3233]
## Describe the bug

Customer Requisitions (Program Orders)
When a customer order stocks from you, they create a Supplier Requisition in their system. This will appear as a Customer Requisition in your system. You can also enter a manual customer requisition to record paper or phone orders from program customers.

**Customer Requisitions>New Requisition**

- [x] You can only create a program customer requisition in mSupply Mobile. You cannot create a general customer requisition in mSupply Mobile.  **-PASS-**

- [x] Select the Customer, Program, Order Type and Period. All of the fields in the Requisition Details window are compulsory. **-PASS-**

- [x] The fields must be completed in the order they are displayed. The arrow points to which step you are up to and the tick shows which steps have been completed.  **-PASS-**

- [x] If you change your selection for a field, all of the subsequent fields will be reset. **-PASS-**

- [x] For each of the fields, you can type the first letters of the name to limit the list to options starting with those letters. **-Filtering doesn't seem to be based on the letters being at the beginning of the option, but if they appear anywhere within an option. From @joshxg that's OK. doc will be updated to reflect current behaviour**

**-Customer-**
 - [x] Customer: a drop-down box appears with all of your customers (excluding patients). **-PASS-**

**-Program-**
- [x] Program: a drop-down box appears with all of the programs for the selected customer. **-What would be the behaviour for programs with multiple tags ? From @joshxg  last tag is used-**

**-OrderType-**
- [x] Order Type: a drop-down box appears with the order types for the selected program. Further details for each order type are displayed on the right. **-PASS-**

   **For non-emergency orders:**
  - [x] Maximum orders per period: maximum number of orders that can be placed in a given period. **-PASS-**
  - [x] Maximum MOS: maximum number of months' stock to be kept for each item.**-PASS-**
  **-Threshold MOS is mentioned. Is that OK?-**

   **For emergency orders:**
  - [x] Max Items: maximum number of items allowed to be ordered for an emergency order (an alert will appear if the maximum number of items is exceeded). **-FAIL-**
  - [x] Maximum MOS: maximum number of months' stock to be kept for each item. **-PASS-**
  **-Threshold MOS is mentioned. Is that OK?-**

**-Period-**
- [x] Period: a drop-down box appears with the available periods for the selected order type. When selecting period, further details are displayed on the right. **-PASS-**

- [x] Dates of the period: displayed as DD/MM/YY range. **-PASS-**
- [x] Number or requisitions already created: requisitions already created for the same customer, program, and period. **-PASS. Not the same displays for Emergency orders. Is it Ok ? PASS-**
- [x] For non-emergency order types, if the maximum number of orders have been completed for a period, the period will not be displayed for selection. **-PASS-**

**Tap OK and review the customer requisition**
- [x] The requisition is created and is populated with all program items. **-PASS-**
- [x] The items are displayed alphabetically. **-PASS-**
- [x] You can reorder the items by clicking on the column header for the category that you wish to order the items. Click on the same column again if you wish to reverse the order. **-PASS-**
- [x] Editable cells are indicated by a line across the bottom of the cell. 
   - [x] If you tap on any editable cell within the table, the data entry window will open in the bottom half of the screen and you can enter data using the number pad **-PASS-** 
   - [x] Tapping on the green tick will move you to the next editable cell on the screen. **-Doesn't see a green tick???-**
   - [x] Data is saved automatically as it is filled in the table. **-PASS-**

- [x] You cannot add additional items to a program customer requisition. **-PASS-**

**There are two sets of columns for data entry.** 
- [x] The first is Customer Data which provides columns for entry of the customer requisition information. **-PASS-**
- [x] The second is Supply Data which provides columns for entry of the customer invoice information. **-PASS-**
- [x] You can switch between the two sets of columns using the buttons on the bottom right of the headers. **-PASS-** 
- [x] Row order is identical across both sets of columns. **-PASS-**

Entering customer data
Tap on the cell that you wish to update:

**Entering customer data**
Tap on the cell that you wish to update:

- [x] Opening Balance will be auto-filled with the closing balance from the previous period. **-PASS-**
  - [x] this cell can also be edited if the opening balance is different. **-PASS-**
- [x] Days out of Stock: editable cell for current period data. **-PASS-**
- [x] Quantity Received: this will be auto-filled with the quantity supplied since the last customer requisition. **based on the customer invoices entry date ???**
  - [x] However, this cell can also be edited if the quantity received is different. **-PASS-**
- [x] Quantity Consumed: editable cell for current period data. **-PASS-**
- [x] Additions: editable cell for current period data. **-PASS-**
- [x] Losses: editable cell for current period data. **-PASS-**
   - [x] Note that mSupply will automatically subtract the values in the losses column from stock quantities. You do not need to enter negative values. **-PASS but I assume that this means that it's removed from "Their Stock" Column.-**
- [x] Requested Quantity: editable cell for current period data. **-PASS-**
 - [x] Closing Balance: calculated as
closing balance= opening balance+quantity received-quantity consumed+additions-losses **-PASS. I assume that we are talking about closing balance being the "Their Stock" column -**

**Entering supply data**
Tap on the cell that you wish to update:

- [x] Current Stock: this will be auto-filled with your current quantity of stock for this item. **-PASS-**
- [x] Their Stock: this will be auto-filled with the customer’s closing balance (from the customer data column). **-PASS-**
- [x] Monthly Use: calculated as
average monthly consumption=(outgoing stock*average number of days a month)/(days in period-days out of stock) **-FAIL See [comment](https://github.com/openmsupply/mobile/issues/3233#issuecomment-733184249) -**

- [x]  If you tap on the item code or name, a window will appear at the bottom of the screen that shows the calculation for the item. **-PASS-**

Suggested Quantity: calculated as
- [x] suggested quantity=(daily consumption*days to supply)-stock on hand **-I think that here the doc should say month instead of days-**

- [x] Requested Quantity: this will be auto-filled by the quantity requested by the customer (from the customer data column). **-PASS-**

- [x] Supply this Invoice: editable cell for the current time period. **-PASS-**
- [x] You can also use the auto-fill buttons in the header: **-PASS-**

- [x] Use Requested Quantities: auto-fills the supply this invoice column for all items with the value from the requested quantity column. **-PASS-**
- [x] Use Suggested Quantities: auto-fills the supply this invoice column for all items with the value from the suggested quantity column. **-PASS-**

- [x] Should put the maximum of available stock if supply this invoice number is greater than available stock **-PASS-**

- [x] Selecting either of the auto-fill buttons will overwrite all values in the supply this invoice column. **-PASS-**

**Finalising a Customer Requisition**
When you are completely sure that everything is correct, tap the Finalise button, then Confirm. 
- [x] Finalising the requisition will also generate 
    - [x] a finalised customer invoice **-PASS-**
    - [x] adjust your stock inventory. **-PASS-**

**-Sync-**
- [x] Requisitions are syncing **-PASS-**
- [x] customer invoices are syncing **-PASS-**
- [x] stock adjustments are syncing **-PASS-**
- [x] no ledger problems **-PASS-**

**Comment by alainsussol** [comment]
@joshxg 

Hi Josh,

Can you check if you can replicate this ?

This is what I did.

- Created a new customer and checked some program tags.
![image](https://user-images.githubusercontent.com/11624516/100024525-f86a2080-2db4-11eb-93e5-235eaae9450a.png)


- Made sure that these tags were assigned to at least 1 program
![image](https://user-images.githubusercontent.com/11624516/100023372-dd96ac80-2db2-11eb-8a37-43f9ab61a368.png)

- Synced to mobile (I saw records being synced)

- Created a new customer requisition for that customer but no program is available. 

![image](https://user-images.githubusercontent.com/11624516/100024309-809bf600-2db4-11eb-8922-05c6755bfa23.png)

It seems to work for customers that were already set for that site on initial sync.

![image](https://user-images.githubusercontent.com/11624516/100024435-c5279180-2db4-11eb-9777-2cd460ddd90e.png)

**Comment by joshxg** [comment]
Documenting my journey:


1. Creating a customer

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029262-c6f56180-2e55-11eb-89a7-3fb32749d20b.png">

2. Additional steps:

Made visible in my store:
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029298-de344f00-2e55-11eb-8749-5728bc0f32a0.png">
Made the program visible:
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029321-e8eee400-2e55-11eb-8d8f-621701ff78a3.png">
Used the name tag:
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029338-f1471f00-2e55-11eb-8267-99caf3fcc579.png">

3. Synced:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029370-ff953b00-2e55-11eb-87c6-f3e064e3cc48.png">

4. Tried to make a requisition:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029395-0cb22a00-2e56-11eb-8352-954ab6fd893f.png">

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029408-150a6500-2e56-11eb-8e59-e1c9d4d4cec8.png">



----------

OK So that was fine. Going to try again with a new master list and name tag.

1. New Master list and tag
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029488-4c791180-2e56-11eb-8b4f-446177dd2339.png">

2. New Customer

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029520-5d298780-2e56-11eb-8ea5-a39ae55efd88.png">

3. Setup customer:

tag.
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029552-6f0b2a80-2e56-11eb-85fe-bcd6bebdab57.png">

store visibility.
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029600-7f230a00-2e56-11eb-99bd-a62b409cdb32.png">

master list visibility.
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029656-a083f600-2e56-11eb-918f-cc34c3c01747.png">


4. Sync Mobile and create a new customer requisition:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029737-be515b00-2e56-11eb-8302-4369e7c205e9.png">


#### HUH!!!

5. OH!! I forgot to make the master list visible in my store!

Thats IT!

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100029844-083a4100-2e57-11eb-9973-c38588775094.png">

----------

Tried one last time with a new customer, new master list and new tags:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/35858975/100030059-80a10200-2e57-11eb-9f40-1118586a7edd.png">


Seems to be working OK for me. Maybe you missed the step making the master list visible in the mobile store, also?

**Comment by alainsussol** [comment]
@joshxg 

> Seems to be working OK for me. Maybe you missed the step making the master list visible in the mobile store, also?

Yes I did...thanks :)

**Comment by joshxg** [comment]
>  -What would be the behaviour for programs with multiple tags ?-

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/35858975/100068597-9e448a80-2e9c-11eb-8d68-551baa946f16.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/35858975/100073379-54f73980-2ea2-11eb-9e85-7d23bdf3779e.png">

**Comment by joshxg** [comment]
> -Filtering doesn't seem to be based on the letters being at the beginning of the option, but if they appear anywhere within an option.

Think thats OK - will update


> Number or requisitions already created: requisitions already created for the same customer, program, and period. -PASS. Not the same displays for Emergency orders. Is it Ok ?-

I believe this is good - emergency orders not being restricted.

> -Threshold MOS is mentioned. Is that OK?

PR Here: https://github.com/openmsupply/mobile/pull/3236

> Max Items: maximum number of items allowed to be ordered for an emergency order (an alert will appear if the maximum number of items is exceeded).

PR Here: https://github.com/openmsupply/mobile/pull/3239

> apping on the green tick will move you to the next editable cell on the screen

Uhh.. not sure what this is..?

**Comment by alainsussol** [comment]
@joshxg FYI, an untick test doesn't mean that it fails, it means that it hasn't been done yet. Each test should have either a PASS or a FAIL written at the end once it has been done. I know that not everybody does that but I feel it's clearer that way as you can never know what an untick box means in the head of somebody.

**Comment by joshxg** [comment]
@alainsussol cool!

**Comment by alainsussol** [comment]
@joshxg 

I am not sure that the monthly usage is calculated properly as the day out of stock doesn't seem to be used in the calculation.
In the example below, I feel that the result should be 8.112 and not 5.

![image](https://user-images.githubusercontent.com/11624516/100141484-80593480-2e60-11eb-971a-ebb2264cbf85.png)


average monthly consumption=(outgoing stock*average number of days a month)/(days in period-days out of stock)

(4 * 30.42)/(30-15) = 121.68 / 15 =8.112

The app says that's 4.06 rounded to 5. I don't think it is right. It 's like the app didn't do the (30-15) part but divided by 30 instead.

Is it possible ?

**Comment by alainsussol** [comment]
@joshxg 

Also if I put a value in a row for which all the other columns of supply data are 0. The number is reset to 0. I assume that is ok since the requested quantity is 0 and the Suggested quantity calculation give me also 0. Can you confirm however ?

**Comment by joshxg** [comment]
@alainsussol The DOS issue is a problem - I'll fix that now. 

> Also if I put a value in a row for which all the other columns of supply data are 0. The number is reset to 0. I assume that is ok since the requested quantity is 0 and the Suggested quantity calculation give me also 0. Can you confirm however ?

I'm not quite sure I understand. Do you mean:

1. Enter value in `Supply This Invoice`
2. Switch to `Customer Data`
3. Enter value
4. Switch back to `Supply Data`
5. See `Supply This Invoice` is `0`.

If this is the case: I think that it is resetting to `0` because you have no stock of that item? You can do the same if you do:

1. Enter value in `Supply This Invoice` for an item with `0` stock
2. See value reset to `0` after a second

**Comment by alainsussol** [comment]
@joshxg This is the case. How embarassing !!!

**Comment by joshxg** [comment]
@alainsussol No - I think that is very confusing - we need some sort of indication when you are trying to issue stock which you do not have

**Comment by alainsussol** [comment]
@joshxg I am pretty much done but a couple of things/comments/questions to ask ourselves  before we release.

1) Doc provided seem to says Max items is displayed for emergency orders but it's not.  But maybe I didn't understand the doc correctly.

![image](https://user-images.githubusercontent.com/11624516/100150242-607c3d80-2e6d-11eb-9acc-78162556a2a0.png)

![image](https://user-images.githubusercontent.com/11624516/100150494-b18c3180-2e6d-11eb-90b6-91180f36bfb4.png)

2) Yesterday I was able to create customer requisitions for a store (District Sanitaire de Yamassoukro) and today I can't as the app says there is no program. All of them were available yesterday.

![image](https://user-images.githubusercontent.com/11624516/100151174-cc12da80-2e6e-11eb-815d-6cc15ca73a1f.png)

yesterday
 I have created 3 requisitions for that store
![image](https://user-images.githubusercontent.com/11624516/100151480-30ce3500-2e6f-11eb-8b20-d1c0520df092.png)

One of them
![image](https://user-images.githubusercontent.com/11624516/100151663-7854c100-2e6f-11eb-920c-c3b77e8807f7.png)


The things that changed is that I created a new external client  and upgraded to v6.0.0 RC11. I deleted the app data and did a new initial sync. I didn't check but I am wondering if the message that is supposed to create the name_tags and name_tags_store-join record worked this time. It worked yesterday :).

3)  App didn't do what is described in the doc below 

> Quantity Received: this will be auto-filled with the quantity supplied since the last customer requisition.

Would it be based on the entry date of the customer invoices finalised prior to the date of the requisition and after the date of the last requisition ? (It would explain why it is not working for me as my requisitions for different periods and the related customer invoices have all been done on the same date .) Will test it tomorrow but should not stop you from releasing.

4) In the doc excerpt below "days" should be replaced by "months"

suggested quantity=(daily consumption* **days** to supply)-stock on hand

![image](https://user-images.githubusercontent.com/11624516/100154443-90c6da80-2e73-11eb-9265-efaba3d2b112.png)

5) For customer invoices created automatically when finalising a customer requisition, I think it would be useful to be able to see which batches have been selected by mSupply so they know what to pack and send to the customer. The problem is that if multiple batches are involved, I can't see which one mSupply has chosen. I think it increases the chance of a user sending the wrong batch which would then create a discrepancy between what has actually been sent and what mSupply thinks has been sent to the customer. 

6) Something to mull about. If we consider that different tags might have different MOS values, is it problematic to take the last one ? On the other hand, as seen on Desktop, having the user choosing between multiple tags can become very confusing for him/her.  

mSupply mobile
![image](https://user-images.githubusercontent.com/11624516/100155335-18f9af80-2e75-11eb-90ea-b499e5ed6758.png)

Invoice synced on mSupply Desktop
![image](https://user-images.githubusercontent.com/11624516/100155613-902f4380-2e75-11eb-9cec-97daa0df9bfd.png)


I think that after the calculation of the "Monthly use" has been fixed and that the points mentioned above have been considered (especially 2 and 5) and fixed if needed then I think, we could release but I am ok to release now if it is urgent as I feel we are very close.

**Comment by joshxg** [comment]
1. Issue for that here: https://github.com/openmsupply/mobile/issues/3242 which should fix all the max lines issues
2. I *think* this might be caused by the programs not being visible to your own store? I fixed a bug with this in RC11 which was allowing you to sometimes create a requisition for a program which was visible to the customer but not to your mobile store. I've no idea exactly what store you're using etc, but on the data file that I have, `ENERGIE de YAM..` does not have `PNLS-ANTIRETROVIRAUX ET IO - DISTRICT` master list visible, so I cannot create a requisition to it.
3. It is calculating the customer invoices within the period of the requisition, so yes, most likely if your periods aren't for very recent it will not calculate anything.
4. On it!
5. Yes this is a very good point and something we really need to discuss changing
6. Yup - you're right - although there doesn't seem to be a best solution 😢

**Comment by alainsussol** [comment]
@joshxg 

A. Emergency order max item lines issues fixed (Order type an alert).
B. MOS Threshold Fixed
C. Monthly usage calculation mostly fixed. It's just that the number displayed in the row is not the same than the one displayed in the calculation box. On the row it is rounded down 20.28 to 20 while that in the calculation box, it is rounded up ie 20.28 becomes 21 

![image](https://user-images.githubusercontent.com/11624516/100277420-1f4d6180-2f31-11eb-8784-a6d001389991.png)

D.

>  I think this might be caused by the programs not being visible to your own store? I fixed a bug with this in RC11 which was allowing you to sometimes create a requisition for a program which was visible to the customer but not to your mobile store. I've no idea exactly what store you're using etc, but on the data file that I have, ENERGIE de YAM.. does not have PNLS-ANTIRETROVIRAUX ET IO - DISTRICT master list visible, so I cannot create a requisition to it

Yes it make senses. The District of Yamassoukro would only have the district master lists available to it while the site I am working on would only have the CS master lists (CS)


----------------------

I think we are good to go when C. is fixed

**Comment by joshxg** [comment]
@alainsussol Thanks so much! :)
