### ISSUE TITLE
Login modal needs a space after store label text

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3254]
## Describe the bug

Login page the site label has a space, but the store label does not.
![image](https://user-images.githubusercontent.com/7684221/100304689-2ee9aa80-3004-11eb-9c6e-940ad6e4f425.png)

### Expected behaviour

Both should have spaces.

### Proposed Solution

Add a space.

### Version and device info

- App version:
- Tablet model:
- OS version:

### Additional context

@joshxg @katherine-sussol For tweaks like this we used to allow making PRs with prefix #xxxx, e.g. `#xxxx-add-space-to-login-store-label` kind of says all you need to know without making an issue like this one haha. Do we want to bring that back? Will it be misused (e.g. #xxxx-rewrote-sync)? Can we just handle that if it happens?

**Comment by joshxg** [comment]
> @joshxg @katherine-sussol For tweaks like this we used to allow making PRs with prefix #xxxx, e.g. #xxxx-add-space-to-login-store-label kind of says all you need to know without making an issue like this one haha. Do we want to bring that back? Will it be misused (e.g. #xxxx-rewrote-sync)? Can we just handle that if it happens?

I'd usually just off-road this into my next/another PR haha - I don't mind, sounds good

**Comment by katherine-sussol** [comment]
Whoops - my bad on the space 😿 . Now I know why prettier added `{' '}` after the colon and I shouldn't have deleted it without changing other things.
#xxxx PRs sound good - I think if someone wanted to sneak a big refactor in it via this method it would be at least easier to pick up than snuck inside an unrelated PR 🤷‍♀️ .
