### ISSUE TITLE
Use react-native-ble-plx over sussol ble module

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3261]
## The suggestion

We should use https://github.com/Polidea/react-native-ble-plx instead of our roll-our-own bluetooth module.

**Why?**
It's way better?

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by mark-prins** [comment]
@joshxg Is this done? Can we close the issue?

**Comment by joshxg** [comment]
thanks
