### ISSUE TITLE
Logging Interval for sensors

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3271]
## Is your feature request related to a problem? Please describe.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by mark-prins** [comment]
@Chris-Petty do you have more detail? Can be closed?

**Comment by Chris-Petty** [comment]
This seems to be already be done in new sensor workflow
