### ISSUE TITLE
Temperature Sensor Logging Delay

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3272]
## Is your feature request related to a problem? Please describe.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by mark-prins** [comment]
@Chris-Petty is this covered by #3374 ?
Could this be closed? Do you have more detail?

**Comment by Chris-Petty** [comment]
Yup this one seems done!
