### ISSUE TITLE
Temperature Sensor Replace/Remove buttons

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3273]
## Is your feature request related to a problem? Please describe.

[In the designs for SensorEditPage](https://marvelapp.com/prototype/55aea8f/screen/75648030), there are buttons to "Replace" and "Remove" Sensors. 

## Describe the solution you'd like

TBD. Decide if we need both. Maybe "Replace":

1. Hit cog -> Sensor edit page
2. "Change sensor" button
3. Shows new sensor step 1 select*
4. return to edit page
5. usual input for everything there
6. Save all the details from old sensor (except macAddress and UUID)

*On selecting a sensor in step 3:

1. If its macAddress is the same as a `Sensor` record already on device, reject if `isActive` already (or do we just filter them out? Based on `isActive` or if currently related to a `Location`). If not `isActive`, make it active and associate with the `Location` (idk if we need to update movements records or anything, I'd think the relations of log -> location would already be enough).
2. If a new macAddress just add new `Sensor`, relate things.
3. old `Sensor.isActive` set to false, remove relation to `Location`.
4. If you fail to select one (i.e. back/cancel), keep the current configuration untouched, back to edit page.

I think some flavour of that behaviour ensures there is always one `Sensor` associated to a `Location`. For MVP do we need a way to set a Location/Sensor pair to `isActive` false? (We don't have Location.isActive in mobile yet.)

## Implementation

- Extract out the FlatList in `NewSensorStepOne` to reusable `SensorPicker`
  - Include the useEffect stuff
  - Add prop `onRowPress`, a call back that handles what to do when a sensor is selected from the list (passed through to ScanRow)
  - `onPress` prop for ScanRow...
  - Move redux dispatches to of `ScanRow` to `NewSensorStepOne`
  - `NewSensorStepOne` use `SensorPicker`
  - `NewSensorStepOne` dispatch methods in onRowPress of `SensorPicker`
- `EditSensorPage`, add button to "Replace" sensor as in designs
- Modal (or page? whatever is easier) that uses `SensorPicker`
- Currently the results in the list filter out sensors that are already in the DB according to `macAddress`. Change the filter to allow results that exist, but are currently `isActive == false`
- `OnRowPress` does the thing:
  - Make old sensor not isActive, remove relation to location
  - upsert selected sensor, isActive true, relate to the location. Assumes `name`, `location`, and `logInterval` of old sensor. (Note using upsert because the selected sensor may already have a record, but just not isActive)
  - redux `sensor` state is updated. New sensor is in there, old inactive sensor is not in there. `EditingId` updated with new sensor id
  - Adjust redux init/preload state to include inactive sensors. Don't display them in module page, don't attempt to sync them...
- Assignee definitely tests the following before PR:
  - New sensor works as normal
  - Edit fridge/sensor, replace sensor
    - SensorEditPage updates correctly and saves correctly
    - Navigating back to the list of fridges (Vacc module page) shows the updated sensor (i.e. macAddress should have changed) 

## Describe alternatives you've considered

Do nothing.

## Additional context

![image](https://user-images.githubusercontent.com/7684221/106841552-3960a880-6707-11eb-90c5-56efb8ee5c14.png)

**Comment by mark-prins** [comment]
@Chris-Petty is this still required? If so, do you have more detail to add?

**Comment by Chris-Petty** [comment]
Timely, there is discussion on another issue regarding more or less this issue. I'll update this issue with detail.

**Comment by Chris-Petty** [comment]
One Q:

The description suggestion covers "Replace" quite well. How do we want to handle "Remove"?

@joshxg made a suggestion that for Remove, we'd remove the relation of stock to the Location, then hide the Fridge/sensor via sensor.isActive (note, desktop has a Location field that is similar, but not on mobile yet). 

We could quite reasonably this question as it's own issue regarding the "remove" button, and keep this focused on "Replace"? I think that'd be ideal.

**Comment by joshxg** [comment]
@Chris-Petty 

I was thinking that we just allow for 'remove':

> I am not sure that we need the 'replace' functionality: If we allow people to set a sensor as isActive=false, essentially 'deleting' the sensor, we remove that sensor from the list, and remove the relation of any item to the location of the sensor, but keep the sensor itself related to the location. Then, when they scan again, if they select the same macaddress sensor, we just set that as isActive=true and use the same location..? Or they can rename the location?

**Comment by Chris-Petty** [comment]
That seems simple enough really. Though what if your goal is to keep the items in the current location, you just want to replace the sensor (due to hardware fault)? With just remove would you have to re-associate items with the new location/sensor?

**Comment by joshxg** [comment]
Yeah that's true.

And also why having better location management in mobile would be better 🙄 

I guess replacing is needed- so just a `replace` button, which opens the same step1 component thing for you to select a sensor - when you do, the sensor is replaced and the original sensor is left location-less and set as `isActive=false`, ready to be selected again in the future and assigned a new location.

Works pretty well actually. 

Do you think the scanning/selecting a replacement sensor should be modal? Since it wouldn't be a 3 step process it feels a bit awkward going to a new page for some reason

**Comment by Chris-Petty** [comment]
> Do you think the scanning/selecting a replacement sensor should be modal? Since it wouldn't be a 3 step process it feels a bit awkward going to a new page for some reason

Could be either or, I don't think it'd make too much difference? I'd lean towards navigation though because... idk. I think I just always think of the bluetooth paring on my phone as being a page in settings and I'm projecting that here.

Just had a quick looksie, seems ScanRow is hooked up to go to next tab in the new sensor workflow. So I thiiink there would be a bit of work to decouple baked in `dispatchToProps` from the base component.

So regardless of modal or page, maybe we'd be better abstracting out the `FlatList` in `NewSensorStepOne` to a component/widget `SensorPicker` (I'm avoiding "selector" because of `reselect` jargon overload heh)? If it were me I'd just make a prop `onRowPress` that handles whatever we want it to do when a row is selectted. Probs grab the useEffect and start/stop scan dispatches too as that'll certainly be common in use of the component. I'm a bit fuzzy on reduxing, but gist about right?

**Comment by joshxg** [comment]
I think it's a good idea to extract out `SensorPicker` - I think it's still a good idea to connect `SensorPicker` directly to redux and take the `useEffect` to abstract it all away into a tidy little component you can pretty much just drop in anywhere.. Passing an `onRowPress` seems good

**Comment by Chris-Petty** [comment]
Updated the **Implementation** details above, sound all g?

**Comment by joshxg** [comment]
Looks good. 

This part:

> OnRowPress does the thing:

it not quite complete - I think it's a little more complex.

- `SensorReducer` is holding state of all the 'current' sensors.
	- Since we have a way now of changing `isActive`, this will need to filter out `isActive` sensors (?)
	- Will need to remove the old sensor from this state
	- Will need to add the new sensor to this state

This might get more complex as `SensorEditPage` is working from the old `Sensor` which is passed in as a prop which we're now trying to change from a child.

**Comment by Chris-Petty** [comment]
@joshxg I am indeed fuzzy on the reduxing. Wouldn't the child dispatch an action, reducer handles the stuff (new record, changing isactives, changing `editingId` in `sensor` redux state, then `SensorEditPage` has a new sensor record via `selectEditingSensor`?

Likewise I'd hope that VaccineModulePage the fridge's sensor details update (macAddress at a minimum would change)? Though fuzzy sort of again, cause I did that realmy 🤪

**Comment by joshxg** [comment]
> Wouldn't the child dispatch an action, reducer handles the stuff (new record, changing isactives, changing editingId in sensor redux state, then SensorEditPage has a new sensor record via selectEditingSensor?

Yes this is all right - just the implementation in the issue seemed detailed up until that point where it was missing the `reducer handles the stuff (new record, changing isactives, changing editingId in sensor redux state, then SensorEditPage has a new sensor record via selectEditingSensor?` part, is all!

> Likewise I'd hope that VaccineModulePage the fridge's sensor details update

It wouldn't have updated but this PR should fix that https://github.com/openmsupply/mobile/pull/3462/files and if you update `SensorReducer`, it should (🤞) all be reflected nicely

**Comment by Chris-Petty** [comment]
Sweet, I've updated to note redux stuffs. And some bonus test instructions ha.

As a rule of thumb, should I generally abandon realm for data state and always use selector (which aren't necessarily reselect memoised) these days?

**Comment by joshxg** [comment]
It's generally nicer and easier (once you pass the redux omg what is going on) to reflect updates into the UI when there are updates from multiple sources (sync, navigating from nested pages etc). It's only a pain because of immutably updating realm objects.

I mainly think abandoning realm for selectors is a good idea because we seem very set/keen on shifting away from realm and it decouples more of the app from realm which means less work later 🤷

**Comment by joshxg** [comment]
So... were you working on this @Chris-Petty ?

**Comment by Chris-Petty** [comment]
I'm keen to, but pretty swamped with other stuff coming in hot 😕 .

Would be really mercenary, but do we need this button to get certification (does CCA have an equivalent?)? Could backlog it for patch if not.

If requirement and everyone is pretty booked out, I could chip away at it in the evenings through the week?

**Comment by joshxg** [comment]
It's fine, I don't think it's a requirement was just unsure from the discussion!

**Comment by Chris-Petty** [comment]
> It's fine, I don't think it's a requirement was just unsure from the discussion!

That's fair. Hard to get a good idea of how to go about doing something without looking at the existing implementation a bit, which is half the task/fun of implementing something anyway, so can see why that was unclear! I try to always assign myself to the issue if I'm committing implementing it (just in case you ever courteously ask again in the future and find me unresponsive haha).
