### ISSUE TITLE
Badges do not update until you navigate into the window

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#3279]
## Describe the bug

If a new record is created by sync (eg. a supplier invoice created when a supplier store sends a customer invoice), the badge number does not update after syncing. You have to navigate into the appropriate window (where you can see the newly created record) and then return to the navigator window, after which the badge number will be updated. 

### To reproduce

1. Create a customer invoice for a mobile store. 
2. On the mobile store, sync records
3. See that the navigator hasn't updated the window badges 
4. Click on the customer invoice section - see that the record exists. Click back and see that the badge number has updated. 

### Expected behaviour

The badge numbering should update when the record arrives?

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v6
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
Could use https://github.com/openmsupply/mobile/blob/master/src/hooks/useSyncListener.js in https://github.com/openmsupply/mobile/blob/master/src/pages/MenuPage.js to somehow trigger a re-render when listening to all `Transaction` and `Requisition` data types

**Comment by katherine-sussol** [comment]
Addressed with #4067

**Comment by DhanyaHerath** [comment]
@katherine-sussol yay! 🥳 🚀
