### ISSUE TITLE
Next button in stocktake skipping rows

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#328]
Build Number: 19

Description: In a stocktake, entering a value in a field and pressing next would go the 2nd row below, rather than the 1st row immediately below.

Reproducible: Yes, apparently happened a couple times for Kate.

Reproduction Steps: Unknown. I suspect probably linked to render row.

Comments: Pressing back and then reopening the stocktake stopped the issue. I observed that the counted quantity column was selected for sort, but changing that wasn't solving or reproducing the issue.

**Comment by joshxg** [comment]
I don't believe this is still a problem. Closing
