### ISSUE TITLE
Bump react-native again to 0.63.4

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3287]
## Is your feature request related to a problem? Please describe.

Want this commit https://github.com/facebook/react-native/commit/00d9deaf6ba26c605694d303bb0cb072fceae5a1

## Describe the solution you'd like

Bump react native dependency

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by Chris-Petty** [comment]
@joshxg What does this actually fix (if anything)?

**Comment by joshxg** [comment]
@Chris-Petty 

If you see in the login page, the font-family of the password is a little different 🤣

**Comment by joshxg** [comment]
![image](https://user-images.githubusercontent.com/35858975/101741221-ae13ce00-3b2e-11eb-930b-e21dab198b33.png)
