### ISSUE TITLE
Black background on logout and settings buttons aren't consistent

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3321]
## Describe the bug

![image](https://user-images.githubusercontent.com/7684221/104142343-0ab12400-5420-11eb-9f6e-7ae0dec6afc2.png)
Ew.

### To reproduce

Press either the "Logout" or the "Settings" button at the bottom of the main menu page. The "Language" button on the 

### Expected behaviour

Be some standard grey that we use.

### Proposed Solution

Standard Icon.Button component used from #3303 

### Version and device info

- App version: 6.0.development
- Tablet model: emulator
- OS version: idk

**Comment by joshxg** [comment]
Seems to be fixed
