### ISSUE TITLE
Dispensing dev warning on non-serialisable state

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3322]
## Describe the bug

![image](https://user-images.githubusercontent.com/7684221/104145155-db53e480-542a-11eb-8cba-e1a4eefa96f0.png)

Sounds like regression risk? I don't know enough about current nav to comment further.

If I had to guess without looking; some object is getting put in state that has member functions. Then either navigator, redux, redux-persist or RN is angry about it. I was thinking redux-persist could be the culprit as it may expect serialisable state to save it as a string.

After re-reading; It's certainly react-navigation giving warnings because it's aware that something like redux-persist could break from it. https://reactnavigation.org/docs/troubleshooting/#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state

### To reproduce

Steps to reproduce the behaviour:
**Only in dev**
1. Go to dispensing
2. In "DISPENSE" column press an arrow to dispense to a patient
3. See warning

### Expected behaviour

There is no warning.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 6.0.0 dev
- Tablet model: emulator
- OS version: Android 11

**Comment by joshxg** [comment]
we've always passed for example a `transaction` using navigation params. We should use the id, though.

redux persist has a blacklist (we should really use a white list 🙄 )

**Comment by joshxg** [comment]
Closed by #3508
