### ISSUE TITLE
Crash when selecting prescriber in dispensing

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3323]
## Describe the bug

Had a RSoD crash when selecting prescriber.

![Screen Shot 2021-01-11 at 5 42 28 PM](https://user-images.githubusercontent.com/7684221/104147755-80bf8600-5434-11eb-850f-a6dee2cee03a.png)

![Screen Shot 2021-01-11 at 5 42 45 PM](https://user-images.githubusercontent.com/7684221/104147753-7e5d2c00-5434-11eb-97a6-ecc416c4372a.png)

### To reproduce

1. Dispensing
2. Have 1 preexisting patient, select them.
3. No prescribers. Make a new one.
4. Select that prescriber- **DED APP**

### Expected behaviour

The prescriber is selected and you continue dispensing

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 6.0.0 dev
- Tablet model: emulator
- OS version: 11

**Comment by Chris-Petty** [comment]
~~I wonder if the prescriber isn't persisted cause the thought is that one may cancel the prescription and cancel making the prescriber? Then on navigation it tries to fetch from DB a prescriber not saved yet. I'd suggest just persisting them right away if that's the case.~~ Jokes it's the transaction that's missing! Odd!

**Comment by joshxg** [comment]
Can't repro - can you give more detailed steps please as well as details of your data file

**Comment by Chris-Petty** [comment]
@joshxg I still get this on develop. If it helps, I use the demo data from scratch on hufflepuff site.

![image](https://user-images.githubusercontent.com/7684221/105104846-e936f300-5b17-11eb-84b4-220589356806.png)

**Comment by joshxg** [comment]
@Chris-Petty Interesting. Are you able to investigate it a little more?

**Comment by Chris-Petty** [comment]
The spot was in Prescription actions. Realm.Objects don't like object spreaders, lose all props haha. https://github.com/realm/realm-js/issues/2640
