### ISSUE TITLE
Patient birthdate should be enterable as just a number and not be required

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3324]
## Is your feature request related to a problem? Please describe.

Often people in the developing world will not know their precise birthday. They may know about how many years old they are, though. So they may only know their age approximately. The mobile user may not have a good chance to ask the patient (e.g. they're incapacitated, but need to record what they're giving the patient).

Currently when entering a new patient, the current date is used to pre-populate age. Entering must match DD-MM-YYYY format.

## Describe the solution you'd like

In desktop we make it easy to accomodate this by allowing a user to just enter a number representing years, and calculate the birth date based on the current date minus that approximate age. 

The current UI is:
![image](https://user-images.githubusercontent.com/7684221/104149833-9e90e900-543c-11eb-91ef-6e816485f97e.png)

My quick minimal suggestion is:
- Put a new text input to the right of the calendar button. Label "Approximate Age". Can enter decimal value, works out DOB on that and populates the date entry.
- On save, add something to the name record to indicate age is approximate. E.g.  desktop does`[name]comment:=[name]comment+"Age estimated" if not already there. Maybe this isn't necessary.
- Make it not required? Maybe I'm contradicting someone here heh.

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

None yet

**Comment by katherine-sussol** [comment]
Labelling/bumping as IC has requested this as a feature 😸
