### ISSUE TITLE
Stocktake : mSupply apps crashes when clicking  the ">" button in the Batches column.

### ISSUE THREAD

**Issue by RachanaKunwar** [openmsupply/mobile#3330]
## Describe the bug

Stocktake :  mSupply apps crashes when clicking  the ">" button in the Batches column.

### To reproduce

1. Go to 'Stocktake'
2. Click on 'any unfinalised stocktake'
3. From the item list click the ">" button in the Batches column.
4. See error. App crashes

### Expected behaviour

App should run smoothly. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 6.0.0
- Tablet model: Samsung
- OS version:

### Additional context

https://support.msupply.org.nz/cerb6/profiles/ticket/YD-8341-YI/#message50249

**Comment by joshxg** [comment]
Hi @RachanaKunwar 

I was unable to recreate this bug 

![image](https://user-images.githubusercontent.com/35858975/104543651-d1c8b780-568a-11eb-86b3-1c6cdf0612e2.png)

Are you able to provide me with any details on your data file as I suspect this is due to certain customizations.

Thanks.

**Comment by RachanaKunwar** [comment]
@joshxg : We have tested this with datafile on demo server. [demo.msupply.org]
