### ISSUE TITLE
Handling of Bluetooth permissions/services

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3376]
## Is your feature request related to a problem? Please describe.

Would be good to have a clearer and persistent indication when the device is in a state which disallows bluetooth usage.

For example, if location services are not enabled, the user might receive popups which state that temperatures can't be downloaded, but may not know why - an indication for example in the nav bar which states: "Location services disabled, click to enable" would be a big benefit

## Describe the solution you'd like

TBD

## Implementation

TBD

## Describe alternatives you've considered

TBD

## Additional context

n/a

**Comment by joshxg** [comment]
@katherine-sussol @Chris-Petty @mark-prins 

Anyone have any thoughts on this?

Been thinking this really should be in the navigation bar, so the user is able to have visibility of it from anywhere in the app. However there doesn't seem to be enough room. Especially if we want to add:

![image](https://user-images.githubusercontent.com/35858975/106811835-c68a0a00-66d3-11eb-8d8e-02c641e96e32.png)

Maybe you can .. click on this thing which will open some sort of 'pop up' with a 'current cold chain status'?


Something like 

![image](https://user-images.githubusercontent.com/35858975/106812246-44e6ac00-66d4-11eb-850e-9cd8372fa0c0.png)


Should probably be hitting Manu up, I guess

**Comment by mark-prins** [comment]
What about showing this if bluetooth or location services are disabled:

![Screen Shot 2021-02-04 at 5 06 20 PM](https://user-images.githubusercontent.com/9192912/106843659-6616bf00-670b-11eb-8b5a-11b797ad0d98.png)

Clicking on it would pop a modal showing status:

![Screen Shot 2021-02-04 at 6 06 43 PM](https://user-images.githubusercontent.com/9192912/106847439-c578cd00-6713-11eb-8271-c4c6ae0a56db.png)

and you could click to enable, giving this:

![Screen Shot 2021-02-04 at 5 06 47 PM](https://user-images.githubusercontent.com/9192912/106843662-6911af80-670b-11eb-93f1-99a1cd0f5c28.png)

**Comment by joshxg** [comment]
Oh thats a good idea. The message: SYNC ERROR is from normal sync right? Do we show some sort of message for the bluetooth symbol or just the icon? I like it a lot.

I just had a thought that we might want to keep it extensible for something like `wifi` or `mobile data` or some sort of internet thing? i.e. could actually just have this for 'app permissions/services' and if there is no internet at all, it has a line for internet as you have for location/bluetooth.

Is this mod 

A little bit on permissions/services- right now we don't quite have it right, sorry my bad.

Permissions:
- We need `location` permission to USE bluetooth. This is because bluetooth is short range and so could theoretically give away a GPS location.
- `Storage` permission is for exporting realm and emailing (need to write the csv to a file then attach it to the email)

Services:
- `Bluetooth` needs to be on- you can technically just turn it on from a call in the app willy nilly (I believe) on some devices, some devices don't seem to let you and the user needs to manually turn it on.
- `Location Services` - this is different from the permission. This is usually an icon next to 'bluetooth' or 'wifi' in the pull down status bar of your device, or sometimes in your phones Settings. This is the GPS service that's running in the background - usually it's `Google Location Services`, though there are others. We need this on to scan for devices - without it, nothing gets picked up. I am not really sure why, I guess it's similar to the above with permission and short range communication.

**Comment by joshxg** [comment]
I just realised we can also change/move the normal sync icon 🤣

**Comment by mark-prins** [comment]
I had just the icon in mind - thinking that if we have a message as well, then the bar gets a little cluttered. Sync is king, so it gets all the space it wants. Probably have to move the icon, in the mockup above it comes between sync icon and message and that's bad. I'd squeeze it down the right, in the place where the settings button often is.

I really like the bluetooth icon for this - but I agree, that the permissions/services thing needs to be more generic.
Some other ideas:
- check/tick & cross to show if all permissions are enabled or not
- a triangle+exclamation-mark-warning sign if there is an issue and.. nothing? if its all good. or a check / tick? or a settings icon?
- an icon which is more like settings ( couple of ideas below ) though there aren't existing icons for a disabled option, so it is harder to indicate that there's a problem

![Screen Shot 2021-02-05 at 9 32 43 AM](https://user-images.githubusercontent.com/9192912/106951929-46c47400-6795-11eb-96f5-77e07cd428d9.png)


![Screen Shot 2021-02-05 at 9 36 46 AM](https://user-images.githubusercontent.com/9192912/106952294-cb16f700-6795-11eb-811b-e6b5ee4f40e9.png)

**Comment by Chris-Petty** [comment]
Do you think we could get away with not having the sync text? It isssss a little greedy of sync haha. We could also consider a smaller icon such as (woe for the images in all our docs, though...): 
![image](https://user-images.githubusercontent.com/7684221/106967544-3b307780-67ac-11eb-9a2d-b1c52bb4532a.png)

Just for a slightly different idea, I've always wanted a notifications list in app. Could list out the issues (notifications), ordered by priority, and interaction causes actions and/or navigation to go straight to the problem area (app permissions, sync, in app message from your boss, authorisation been given to invoice, order coming in hot...). Natural icon for me would be a bell: 
![image](https://user-images.githubusercontent.com/7684221/106967773-96626a00-67ac-11eb-8b30-ffebe97f7e14.png)

And I know @joshxg would love to animate this shaking and flashing haha:
![image](https://user-images.githubusercontent.com/7684221/106967894-c0b42780-67ac-11eb-8378-e74829a84e55.png)

Just throwing it out there. This probably getting way into feature creep.

---

Total tangent, just thought it might be fun to implement drag from top list refresh which triggers sync (show toast/warning if no connection).
