### ISSUE TITLE
Vaccines tables sync

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3377]
## Is your feature request related to a problem? Please describe.

The tables for vaccines need to sync. Consider:

- The volume of logs
- Things

## Describe the solution you'd like

**TBD**

## Implementation

**TBD**

## Describe alternatives you've considered

**TBD**

## Additional context

**TBD**

**Comment by joshxg** [comment]
Also gonna put into this a few updates to vaccine generate data!

**Comment by joshxg** [comment]
A
