### ISSUE TITLE
alignment on this is a bit funny

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3414]
alignment on this is a bit funny 

![image](https://user-images.githubusercontent.com/35858975/106212180-e7171780-622e-11eb-917d-5cd7c2e686b8.png)

_Originally posted by @joshxg in https://github.com/openmsupply/mobile/pull/3409#discussion_r566481408_

**Comment by Chris-Petty** [comment]
@joshxg could you share your emulator/device screen details?

**Comment by Chris-Petty** [comment]
I'm too fond of this issue title, I refuse to change anything. Unless it's really that bad I will do the process.

**Comment by joshxg** [comment]
seems to be fixed
