### ISSUE TITLE
Location getter for first sensor

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3420]
## The suggestion

Vaccine Module page (the new one) goes to sensor editor page when pressing the cog button of a fridge (i.e. a location). It just goes to the first sensor associated to the fridge (the implementation is written with listing multiple sensors for a fridge, but we'll get to actually utilising that one day 🙏.

Anyway, `firstSensor()` as a  getter method on Location realm class?

**Why?**

Because potentially neater and tidy.

## Describe alternatives you've considered

Not doing it.

## Additional context

https://github.com/openmsupply/mobile/pull/3409#discussion_r566471603

**Comment by joshxg** [comment]
this is in already
