### ISSUE TITLE
VaccinePage UI should update when events occur.

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3421]
## Is your feature request related to a problem? Please describe.

Currently the `VaccinePage` uses a realm object and each of the UI elements extract their values from the realm models getters. This means certain UI elements won't update when a download occurs

- Current temperature
- Last download time
- Last Breach Time

Also need to update and check the current battery level
- Battery level

Additionally when a sensor is edited and saved, navigating back won't cause an update to the sensor/fridge name.

## Describe the solution you'd like

Likely need to use redux selectors in `mapStateToProps` which will cause an update after a download occurs.

## Implementation

- Would suggest passing a `fridgeID` to `FridgeDisplay` which is then connected to redux, and uses that ID to pick slices of state rather than connecting the `Page` to redux.

## Describe alternatives you've considered

Just literally causing a re-render of the page when certain events occur

## Additional context

N/A

**Comment by joshxg** [comment]
Currently the `VaccinePage` uses a `location` object and reads all of the data from that object. This object is a realm object, so must be re-queried for to get a new reference. Since this is also taken from a realm collection, the whole collection needs to be re-queried. This means the whole page would needs to be re-rendered to update when the last sync time was for a certain sensor, or we need to come up with some other solution (like a duplicate, synced up set of objects which we can use to create new references to re-render a specific row - i.e. like how the `DataTable` works).

Re-rendering the whole page is an option since this page is relatively low impact to re-render. But since we already have most of the code written to allow this to have more fine grained re-rendering, I Think the best way to go about this is:

- Rather than using `fridges` state, use `entities.sensor` (or `entities.location`) state which is updated when adding a sensor through `Add Sensor` flow. This will keep the `VaccinePage` updated with the right number of fridges/sensors. It might need a small tweak to update after sync completes - but this needs to be added regardless.
- Use the `FridgeHeader` component added in #3445 - this will mean the general look will change, as we probably don't want so many conditionals to change but I think it's good/OK to be consistent (in hindsight) and shift the battery level/last sync time to consistently be in the header. This already has logic to constantly update the last sync time and enabling/disabling blink etc.
- The Last breach/current temperature: I think it would be good to keep these two fields in the `entities.sensor` state, where the `SensorReducer` can be updated by actions `SensorDownloadAction.downloadSuccess`, which will update the `currentTemperature` (and `batteryLevel`). For the last sync time, we have #3381 still open which is the issue to create breaches after downloading, so presumably there will be an action to know when a breach was created for a specific sensor which `SensorReducer` can listen for and update `lastBreachTime`.

**Comment by joshxg** [comment]
oops I forgot to @ peeps - @Chris-Petty @mark-prins @katherine-sussol

**Comment by mark-prins** [comment]
I was thinking to use the `FridgeHeader` too - though could it be renamed to something a little generic?

Like the approach you have here, and was thinking along similar lines. Keeping the last breach, current temperature, battery status, last download time ( last download status? ) somewhere separate so that we can the page refreshed is a good idea.

Do we need to re-render after an edit as well though? Otherwise a name change won't get picked up.

**Comment by joshxg** [comment]
Yup- by using the `entities.sensor` state then it should all be kept in sync
