### ISSUE TITLE
Vaccine module page fridge circles; More colours?

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3422]
## Is your feature request related to a problem? Please describe.

Currently each fridge has a green circle rendered next to their name. The green doesn't actually mean anything, maybe we should do something with it?

## Describe the solution you'd like

Give the circle a purpose? Ideas:

- Orange circle if breached recently?
  - Red if currently breached?
- Change to different icons?
  - Over kill? The sensor info row of the fridge gives breach details already

## Implementation

TBD

## Describe alternatives you've considered

Do nothing. Ask a UI designer.

## Additional context

https://github.com/openmsupply/mobile/pull/3409#discussion_r566471691

**Comment by joshxg** [comment]
I think green for good and (flashing?) red for DANGER - low battery/in breach.

**Comment by katherine-sussol** [comment]
The designs have the circle turning orange (sorry...`DANGER_RED`) on some of the other pages if anything (battery/no sync/breach) is in a DANGER state, with the specific danger-causing thing also orange, I kinda like it as it makes it more obvious what's concerning? Although that maybe too much `DANGER_RED`...

**Comment by joshxg** [comment]
I feel like @katherine-sussol is making fun of DANGER_RED and she better be DANGER_CAREFUL

zing
