### ISSUE TITLE
 "Sensor name" in UI should update Sensor.name and Location.description

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3427]
## Is your feature request related to a problem? Please describe.

- Currently the `VaccinePage` shows the name of the sensor and the name of the location:

![image](https://user-images.githubusercontent.com/35858975/106372685-41eb7300-63d7-11eb-8a42-23784e221c95.png)

This is per the designs

- When we create a sensor we need to create a matching location, also - as per: #3426 

So, these will technically, in most cases, be the same text.

## Describe the solution you'd like

TBD

## Implementation

-  "Sensor name" in UI updates Sensor.name and Location.description

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
@Chris-Petty @mark-prins @katherine-sussol 

When we create a `Sensor` we create a `Location`. We currently have no way to edit a `Location`. It was thought that we would use the entered `Sensor name` as both the `Location.description` and the `Sensor Code` as `Location.code` as we need a `Location` to be linked to the `Sensor` to conform to the schema and link temperatures to items etc.

This leaves us with the potential problem above- what should be displayed in the `VaccinePage` list items as the header/sub header

Fields:
- `Sensor.name` [Equal to Location.description?]
- `Sensor.macAddress`

and also

- `Location.description` [Equal to `Sensor.name`?]
- `Location.code`

At the moment it is 

## Location.desription
### Sensor.macAddress

**Comment by Chris-Petty** [comment]
Would the current fields used be fine provided that editing the sensor/fridge (i.e. cog button), `sensor name` field updates both the `sensor.name` and `location.description`?

**Comment by joshxg** [comment]
Yeah (will need to add location description updating)

**Comment by Chris-Petty** [comment]
> Yeah (will need to add location description updating)

Seems fair, wouldn't be far off whatever new sensor logic does?

**Comment by joshxg** [comment]
yup

I guess the other thing is this sensor/location one to one relationship and the ability to remove/replace/switch sensors etc. Not 100% on the exact desired behaviour..

Should we just allow 'disabling' a sensor (set it `isActive = false`) and don't touch the location..? Don't allow switching sensors between locations and don't allow 'reenabling' sensors..?

**Comment by Chris-Petty** [comment]
> yup
> 
> I guess the other thing is this sensor/location one to one relationship and the ability to remove/replace/switch sensors etc. Not 100% on the exact desired behaviour..
> 
> Should we just allow 'disabling' a sensor (set it `isActive = false`) and don't touch the location..? Don't allow switching sensors between locations and don't allow 'reenabling' sensors..?

Just spitballing:

1. Hit cog -> edit page
2. "Change sensor" button
3. Shows new sensor step 1 select*
4. return to edit page
5. usual input for everything there
6. Save all the details from old sensor (except macAddress and UUID)

*On selecting a sensor in step 3:

1. If its macAddress is the same as a `Sensor` record already on device, reject if `isActive` already (or do we just filter them out? Based on `isActive` or if currently related to a `Location`). If not `isActive`, make it active and associate with the `Location` (idk if we need to update movements records or anything, I'd think the relations of log -> location would already be enough).
2. If a new macAddress just add new `Sensor`, relate things.
3. old `Sensor.isActive` set to false, remove relation to `Location`.
4. If you fail to select one (i.e. back/cancel), keep the current configuration untouched, back to edit page.

I think some flavour of that behaviour ensures there is always one `Sensor` associated to a `Location`. For MVP do we need a way to set a Location/Sensor pair to `isActive` false? (We don't have Location.isActive in mobile yet.)

This pretty well into "separate issue to this one" territory?

**Comment by joshxg** [comment]
Ah interesting.

Currently when scanning for sensors we don't show any that are in the db. So I suppose if you don't show any that are in the db and active, then you can potentially choose ones that are inactive. Then at the end of the flow, instead of creating, just make it active. Nifty.

I am not sure if we need any of this for MVP.. but I'm gonna keep going.

I am not sure that we need the 'replace' functionality: If we allow people to set a sensor as isActive=false, essentially 'deleting' the sensor, we remove that sensor from the list, and remove the relation of any item to the location of the sensor, but keep the sensor itself related to the location. Then, when they scan again, if they select the same macaddress sensor, we just set that as isActive=true and use the same location..? Or they can rename the location?

**Comment by Chris-Petty** [comment]
Think it'd be good to move the discussion from here to #3273. Bare with me as I update that one to have appropriate level of detail.

Regarding the original issue here, should we go with agreed solution of editing "Sensor name" in UI updates `Sensor.name` and `Location.description`? (or continue discussing from there)

**Comment by joshxg** [comment]
Happy with that agreed solution, thanks
