### ISSUE TITLE
After reinitialising tablet, crash when viewing fridge details

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3443]
## Describe the bug

![image](https://user-images.githubusercontent.com/7684221/106549190-54031800-6575-11eb-9c62-555afc05a4eb.png)

Go to vaccines module page, click chevron button to view detail (the chart page). Crashes.

### To reproduce

1. Generate vaccine data
2. sync
3. wipe tablet data (`yarn reset`)
4. initialise same site
5. Vaccine module
6. View a fridge
7. ded

### Expected behaviour

Doesn't crash. Shows the fridge's stuff.

### Proposed Solution

Fix sync. ~~Pretty sure `TemperatureBreachConfiguration` is just missing `location` field in `IncomingSyncUtils`.~~ ~~Nah, that doesn't appear to be a relation in desktop~~ what a switcharoo, it is on desktop but I had the wrong branch checked out! So:

- [ ] Fix `incomingSyncUtils`
- [ ] Fix `outgoingSyncUtils`

### Version and device info

- App version: dev branch
- Tablet model: emulator & lenovo
- OS version: 11

**Comment by Chris-Petty** [comment]
@joshxg just reviewing the schema [drawn here ](https://app.diagrams.net/#G1SWb81iwdYyBLTiB6sK5a87ZajaiTb33i), it appears there is a many to one relation from breach configs to locations. Is so in mobile, but no FK `config.location_ID` set in desktop yet (not included in the fields in the schema drawing, might be why it was missed?). Just double checking that's the way we should be going here? Would be:

1. Create issue in desktop for `[temperature_breach_config]location_ID` FK and relation implemented.
2. Update mobile incoming and outgoing sync utils to use/maintain that relationship.

**Comment by joshxg** [comment]
Yes please!

**Comment by Chris-Petty** [comment]
Turns out my mSupply wasn't on develop, but something branched off develop more than 5 days ago when that relation already got fixed heh.

So just fixing incoming/outgoing needed, yey!

**Comment by joshxg** [comment]
Ohhh yeah I did that already when I broke develop - I forgot! Whoops!
