### ISSUE TITLE
StepTwo and EditorRow style updates

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3449]
## Describe the bug

Step Two:

The BreachConfigRows are wrapped in an `AfterInteractions` because the navigation straight after stopping the scanner is a bit slower - and the `AfterInteractions` is rendering a placeholder `null`, and with the paper flexing its janky - hard to see but the paper is only appearing after the configs render:

![steptwojank](https://user-images.githubusercontent.com/35858975/106709655-bf261a80-6659-11eb-8d5c-94a1de4931f8.gif)

EditorRow label is overflowed up:

![image](https://user-images.githubusercontent.com/35858975/106709706-c9e0af80-6659-11eb-9c3d-fa1fa9686564.png)

### To reproduce

1. Go to `NewSensorStepTwo/Three`

### Expected behaviour

- `StepTwo`: Can use a placeholder which is the height of 4 rows? However I've also been thinking the 3 paper in the three steps would look nice if they were the same size..ish?
- `EditorRow`: not sure need to investigate

### Proposed Solution

N/A

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
![image](https://user-images.githubusercontent.com/35858975/106807438-0817b680-66ce-11eb-8f30-90dd009e7f51.png)

**Comment by joshxg** [comment]
![image](https://user-images.githubusercontent.com/35858975/106807519-22ea2b00-66ce-11eb-95f6-ef164e0287c8.png)

**Comment by Chris-Petty** [comment]
Haha damn, I knew changing that width would bite me. Mind if I go at it with something _flexy_?

**Comment by joshxg** [comment]
Sure.

Personally I think it looked OK how it was originally and not sure if it's really worth spending time on!
