### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3480]
## Describe the bug

The addition of `logDelay` and `programmedDate` has lead to a sync error:

![Screenshot_2021-02-10-11-15-43-034](https://user-images.githubusercontent.com/9192912/107442971-c9d23980-6b9c-11eb-8740-91aa95dd177a.jpeg)

### To reproduce

Steps to reproduce the behaviour:

1. Clear app data
2. Sync with an existing site

**Comment by joshxg** [comment]
Ugh! Sorry - Just want to get your app running again, huh? 🤣 

This is because I opted for a default rather than optional on the fields, but forgot that this means they're required, and explicitly setting `null` does not set the default, but it's required .. 😡
