### ISSUE TITLE
Picker is being deprecated out of react-native core

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3542]
## The suggestion

![image](https://user-images.githubusercontent.com/35858975/108289321-1a781100-71f3-11eb-8bfd-6ce5f7e6bcda.png)

Replace picker with a new variant. This warning is actually

**Why?**

before it's too late!!!!!111

## Describe alternatives you've considered

Do nothing, suppress the warning

## Additional context

N/A

**Comment by katherine-sussol** [comment]
8.1 sounds like a good time as any since it seems we have some time 😆

**Comment by katherine-sussol** [comment]
Closed with #4084
