### ISSUE TITLE
BleErrors when updating sensor (when download in progress?)

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#3546]
## Describe the bug
When trying to edit a sensor (even non-Bluetooth settings, e.g. Breach Settings only) it will throw BleErrors if a download is currently happening in the background.
e.g.
- Operation was cancelled
- Device ? is already connected

Attached a screen recording - 
https://user-images.githubusercontent.com/65875762/108297509-3e8e1f00-7200-11eb-954a-870a02a2ebc1.mp4

### To reproduce

1. Go to Vaccines -> Click the cog on a sensor
2. Change some breach threshold temperature(s)
3. Click 'Save'
4. See error(s)

### Expected behaviour

1. Expected sensor to update with no errors (or at least for errors to be fairly rare)

### Proposed Solution

- Maybe one improvement could be to not send BT commands if there haven't been any updates that require them? e.g. if breach config change only
- Above doesn't solve the underlying issue though 🤷  - not sure how to fix that one yet. 

### Version and device info

- App version: 7.0.0 RC3
- Tablet model: Lenovo something (not sure of model name)
- OS version: Android 8.1

### Additional context
- From observations, seems like these errors are coming up/more frequent when downloads are happening/starting in the background. If there are lots of sensors a download sequence could take a while.
- Might need more testing to pin down the specifics, it's being really bizarre 🤔   - will leave issue here to add info as more details come in I guess?

**Comment by joshxg** [comment]
I was able to reproduce this - I got the error when editing a sensor I believe it was when a download was in progress. After a couple of attempts I was able to successfully save (believe the download had finished). 

If this is the case, I wonder if just making the message "cant right now try again soon" is OK?

**Comment by katherine-sussol** [comment]
Oh good, not just me doing something weird 😥 . Yeah, replacing it with a less scary/dev centric message sounds good (might be digging a huge 🕳️🐇   trying to handle this edge case), I think if we can avoid sending BT commands unless the `logInterval` is updated it should help a bit too?

**Comment by joshxg** [comment]
Yeah should be helpful. When you were getting the error, were you also able to *eventually* update the sensor?

**Comment by katherine-sussol** [comment]
Yeah, from testing today (and on Friday) I can update the sensor fine (from a UI perspective and breachConfig perspective) as long as a download isn't happening. 

_Although_ I am also running into #3570 on develop 😆

**Comment by katherine-sussol** [comment]
Added a bit more logging - seems like if a download is already in progress, an attempt to update a sensor (or actually any BT command, e.g. blink) can also cause the background download to fail. It's also possible for the blink command to hang in an infinite spinning state if you press it at the wrong time 🙀 . Will log separate issue for the blink issue.

**Comment by joshxg** [comment]
Ah that all seems to make sense. I believe there is already some redux state which says whether a download is in progress. Wonder if a decent solution would be to just check that state and do a toast rather than the command?

Although the download failing isn't the worst thing in the world, should just download the log on the next run.?
