### ISSUE TITLE
Sensor: In sensor detail page, Line chart shows inconsistency initially 

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3598]
## Describe the bug

 In sensor detail page, Line chart shows inconsistency initially 

### To reproduce

1. Go to Vaccine module
2. Click on Sensor detail icon (Sensor is setup correctly before)
3. Click on Line chart
4. See error. It shows inconsistency initially by displaying two connecting dots.
![Initial Sensor Setup](https://user-images.githubusercontent.com/58979436/108810078-67ccf780-75d2-11eb-989f-856ef2067572.jpg)

Attached CSV
[23-02-2021-1156 (1).xlsx](https://github.com/openmsupply/mobile/files/6027148/23-02-2021-1156.1.xlsx)

### Expected behaviour

It should show straight single line.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V7.0.0-RC6
- Tablet model: Lenovo
- OS version: 8.1

### Additional context

However after sometime, Line Chart looks like this.
![photo_2021-02-23 12 27 34](https://user-images.githubusercontent.com/58979436/108810134-892de380-75d2-11eb-80fa-5121fa2a0d00.jpeg)
CSV attached 
[23-02-2021-1257.xlsx](https://github.com/openmsupply/mobile/files/6027257/23-02-2021-1257.xlsx)

**Comment by joshxg** [comment]
@katherine-sussol 

At a guess, when getting the vaccine data it's splitting into, I think, 30 'periods' and then finding the logs within each period. This is desired because we do want to see when there were no logs at all. However I imagine there are just not 30 logs and so the gaps are from times where there are no logs. Technically not correct, but we could check if there are < 30 logs, just use the logs rather than splitting into periods

**Comment by katherine-sussol** [comment]
Oh, you beat me to it was just typing my findings hehe. Yeah, I think that's what's happening, when there's less than 30 logs there are points along the line with a timestamp and `null` temp even though there's technically no missed logs. Sounds good, will have a go with not doing the splitting if less than 30 logs (and see what happens with 31 logs etc)

**Comment by joshxg** [comment]
@katherine-sussol cool - sorry I should've commented earlier! That fix will do it I'm sure. Something else to think about and for me to muddy the waters:

I think 30 is a random number I came up with. Possibly to do with the default time period being 30 days (kinda like, show 1 month worth of logs when you navigate here). Both of these could be changed if it's better. I.e. look back only 7 days for the initial time period? Also maybe a smaller number of periods would be better? 24? 12? Can leave this alone, but wanted to point out there's no real rhyme or reason for those numbers that I can think of

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0 RC8

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Reproduce #3598 (need less than 24 logs to see bug)
- [x] See nice continuous line
