### ISSUE TITLE
Sensor: In sensor detail page, Bar chart shows inconsistency initially

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3599]
## Describe the bug

A clear and concise description of what the bug is. Use screenshots!

### To reproduce

1. Go to Vaccine module
2. Click on Sensor detail icon (Sensor is setup correctly before)
3. Click on Bar chart
4. See error. It shows inconsistency initially by displaying two Line each for Hot Consecutive/cumulative and Cold Consecutive/Cumulative
![photo_2021-02-23 12 54 23](https://user-images.githubusercontent.com/58979436/108811950-4837ce00-75d6-11eb-87d3-fbdf74a45685.jpeg)

Attached CSV
[23-02-2021-1156 (1).xlsx](https://github.com/openmsupply/mobile/files/6027213/23-02-2021-1156.1.xlsx)

### Expected behaviour

It should show chart or graph of current recorded temperature.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V7.0.0-RC6
- Tablet model: Lenovo
- OS version: 8.1

### Additional context

However After some time, Bar chart looks like this
![photo_2021-02-23 12 55 43](https://user-images.githubusercontent.com/58979436/108812033-74534f00-75d6-11eb-8f30-70a74b7afdad.jpeg)
Attached CSV
[23-02-2021-1257.xlsx](https://github.com/openmsupply/mobile/files/6027254/23-02-2021-1257.xlsx)

**Comment by joshxg** [comment]
Wondering if this might require having a minimum height to the bars?

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0 rc8

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Reproduce #3599 (if there's only 5 or so logs you should be able to see it)
- [x] Graph should not be empty if there is at least one temperature recorded
