### ISSUE TITLE
Add JSONSchema form package

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3611]
## Is your feature request related to a problem? Please describe.

We want to create dynamically created forms from a JSON schema. There are a lot of packages which can do this:

One of the most widely used is https://github.com/rjsf-team/react-jsonschema-form however this is not compatible with react-native.

There are a couple of forks/themese being maintained which support react-native:
- https://www.npmjs.com/package/react-native-web-jsonschema-form - primarily for web and we have to install a bunch of extra dependencies (mainly expo ones) to make it work.
- https://github.com/royaizenberg/react-native-jsonschema-form - pretty abandoned
- https://github.com/zhigang1992/react-native-jsonschema-form - looks pretty promising, but doesn't theme/support the full set of widgets that the original project does, so will still require a decent amount of implementing different components.

## Describe the solution you'd like

Either
- Utilize zhigang1992's version and extend it
	- Pro: Potentially *slgihtly* less code to write
	- Con: We have to rewrite most of the widgets so it really doesn't offer *that* much
	- Con: We are extending an extension of a project, could have nightmares later when/if it's abandoned
- Create our own theme/extension of `react-schema-form`
	- Pro: Saving a decent amount of time by having a package organise which components should be rendered given a schema, out of the box.
	- Con: Potentially losing a decent amount of time by having a package organise which components should be rendered given a schema, out of the box - huh?
	- Pro: full customized widgets is good for us.
	- Con/Pro(??): Might need to do some commits into the mainline branch to ensure the full project is RN compatible.
- Create our own JSON schema form generator
	- if only we had the time 🤣 

Personally I think making our own theme/extension for `react-schema-form` is a good middle ground. The project has 10k+ stars and 60k downloads/week so it is a solid project unlikely to be sunset. They have issues and seem keen on adding RN support if anyone offered a PR which we could do later, so that someone else could decide they don't like our theme and not use it.

## Implementation

Add the package if any to the code base to start utilizing

## Describe alternatives you've considered

Above
## Additional context

N/A

**Comment by joshxg** [comment]
@mark-prins please cast your vote

**Comment by mark-prins** [comment]
Create our own theme/extension of `react-schema-form`

I was able to get Roy Aizenberg's abandoned fork working, and can plug in custom components - so we could get that running easily enough. But.. it is abandoned. and is only a small amount of code, so it isn't giving us much - apart from a bunch of things to work around.

Couldn't get my own components to work as widgets in `zhigang1992` fork, and once again, there isn't actually much code in the repo anyway. We can use bits of both as a base and just make our own theme: I think that'd be the fastest and most long term option.

**Comment by joshxg** [comment]
Awesome, sounds good :)
