### ISSUE TITLE
Add additional fields to the name data type

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3614]
## Is your feature request related to a problem? Please describe.

We need to add additional fields to the `[name]` data type which are not currently there.

## Describe the solution you'd like

Add the following tables to the schema, including to incoming sync
- `[Ethnicity]`
- `[Nationality]`
- `[Occupation]`

Add the following fields to `[name]`
- ethnicity: Relation to the `Ethnicity` table
- occupation: Relation to the `Occupation` table
- religion (nationality???): Relation to the `Religion` table (????????????)
- District - UNSURE HOW TO HANDLE THIS
	- New field? Address?
- Village - UNSURE HOW TO HANDLE THIS
	- New field? Address?

## Implementation

Add the fields to `[name]`, add the fields to `incomingSyncUtils` and `outgoingSyncUtils`

## Describe alternatives you've considered

N/A

## Additional context

Resource spreadsheet: https://docs.google.com/spreadsheets/d/1eYqarZ9KDnK8F6k0Yx0HwuRYt-1SajSd/edit#gid=91174836

**Comment by joshxg** [comment]
@mark-prins 

I have since found out that `religion` !== `nationality` .. 🤷 

- Should we make a `nationality` form in mSupply ❓

in mSupply [name] has:
- ship_address1
- ship_address2
- ship_address3
- ship_address4
- ship_address5
- postal_address1
- postal_address2
- postal_address3
- postal_address4
- postal_address5
- bill_address1
- bill_address2
- bill_address3
- bill_address4
- bill_address5

At the moment, we handle this like: 
- Create an address record when a name comes in using `bill_address1-4` and the `bill_zip_code` https://github.com/openmsupply/mobile/blob/471c1e79f1d2aec239401e9e45c6ee8eea2295c3/src/sync/incomingSyncUtils.js#L544-L552
- https://github.com/openmsupply/mobile/blob/471c1e79f1d2aec239401e9e45c6ee8eea2295c3/src/database/schema.js#L63-L74

Not sure exactly how we should handle village/district, but if we just add a `village/town` and `district/city` fields to the patient form, can we save them as an address' `line3/4` which will correspond to `bill_address3-4` - or could we use one of the other fields ❓

**Comment by mark-prins** [comment]
Some clients use 
- `name_category1` for country 
- `name_category1_level1` for a 'region' 
- `name_category1_level2` for 'district'

Tonga aren't using name categories, so we could use this for a lookup if we get a list of villages & districts.
Otherwise, I'd go with a text input and save to address line 3/4 as you say.

**Comment by joshxg** [comment]
Ah, utilising the categories fields is a good idea!

We could start syncing name categories. This would nicely make it so there is consistency in the data, also, rather than having a free text input field which would cause some dramas?

We just need the two fields for district/village - is it OK to just use cat1/cat2 for those rather than cat1 for country?

Then maybe we start syncing the `name_category1` and `name_category2` tables, add them to `[name]` in mobile and put a drop down field in the `[name]` form..? Maybe this would have to be conditional on actually being some `name_category` records existing.

I also am not sure how the `name_category` levels work..

**Comment by mark-prins** [comment]
I was worried about consistency, if people are typing in text values for village & district.
There was a reason for using cat1 as country and 2 & 3 for the more useful things.. but I can't remember what it might have been! so.. let's not. we may find out why.

`name_category` are hierarchical with the lower levels referring to a `parent_id` in the parent table.. in which case selecting a district could be used to filter the villages to pick from, which is also nice. cuts down the options in select lists.

There are plans to fix ( replace ) that in open msupply as we really need a geography type table.

**Comment by joshxg** [comment]
Hm OK you've lost me, I'm confused whether you are for or against using categories but it seems you are for using them, but with category levels?

**Comment by mark-prins** [comment]
Sorry. 
I'd like to use the categories. ( levels is a distraction, just ignore for now )
