### ISSUE TITLE
Add new vaccine dispensing flow redux shape

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3617]
## Is your feature request related to a problem? Please describe.

We will likely (?) use redux for the new vaccine dispensing flow to be consistent with the rest of the app.

We will need to design and add the shape for this redux state.

## Describe the solution you'd like

TBD

## Implementation

TBD

## Describe alternatives you've considered

Not using redux???

## Additional context

Some things to consider:
- We want to have a step process for creating the prescription. The current dispensing flow creates a realm `Transaction` object, and if navigating away without finishing, deletes it. I think this isn't great and should be avoided, if possible by using an in-memory "transaction" object which is saved at the end of the flow.
	- Pros: We avoid adding more class instances and non-serialisable state into redux.
	- Pros: We don't have to hook into navigation events to delete things.
	- Pros: It's easier to validate things when you don't save them persistently straight away.
	- Pros: Less work when moving to SQLite
	- Cons: Can't utilise any of the realm class-method based logic
- This also goes for a `name`/`name_note` records. Ideally we don't update the name *straight* away, nor create new `name_note` records which we have to then track and delete.
- The general pattern for this is entity based reducers where you have something like:
```
{
byId: {
  [id]: entity,
  [id2]: entity2,
  ...,
 }
ids: [id, id2] // For sorting, if ever needed
editingId: id // this is the one we're editing
}
```
- However, I can imagine there being a LOT of `name_note` records, and there can even be a lot of `name` records (all of Tonga?!). So maybe we need to do a slightly different shape?

```
{
editingEntity: entity
}
```

or

```
// This is for when you're editing many records at once, i.e. name_note records
{
editingEntitiesById: {
    [id]: entity
    [id2]: entity2
	}
editingEntitiesIds: [id, id2]
}
```
- We may also want to think about a shape for `name_note` where we track the notes which are actually touched/edited as we only want to create new `name_note` records which have been changed, rather than for everything.

**Comment by joshxg** [comment]
As a somewhat fuller solution, I propose:

- Add a reducer, `nameReducer` and `name` to `entities` state shape, with the shape:

```
{
	editing: [plain name object],
}
```

- Add a reducer, `vaccinePrescriptionReducer` and `vaccinePrescription` to `entities` state shape, with the shape:

```
{
	creating: [plain vaccinePrescription object]
}
```

- Add a reducer, `nameNoteReducer` and `nameNote` to `entities` state shape, with the shape:

```
// When you go to edit, if the id isn't in creatingById, copy over the object into
// creatingById from editingById?
{
    creatingById: {
        id3: [plain name note object],
    },
    editingById: {
        id1: [plain name note object],
        id2: [plain name note object]
    }

}
```

As much as I would appreciate that all of the reducers in the `entities` space be consistent, I don't think keeping all `names` in memory is very practical? Although, to be fair, that's more or less what we do when we query for `name` and display it in a list.. so.. what do I know? I guess we have GBs of memory and a full realm file is typical a few MB's so what do I know

My concern with this approach is that it is too heavy and that a "vaccineDispensing" reducer would do. It is from my experience thought, that I prefer having entities separated from the `vaccineDispensing` reducer (and likely, a `vaccineDispensing` reducer is unneeded) as if you start to access the entities from elsewhere in the app, it is quite odd to be accessing "name" from a slice that is not "name", or you end up duplicating state and having to keep multiple places in sync.

**Comment by joshxg** [comment]
@mark-prins pinging in the ones that don't have proper solutions if you have any feedback. Sorry for the spam 🤷

**Comment by mark-prins** [comment]
I like the separate `entities` reducers and state for each of the three. Don't think that it is much of an overkill and it matches with the direction of the sensors and all that.

The number of `[name_notes]` would depend on whether we create a `name_note` for every field, or just have an object field - so that decision will sway what we do here. If, and I think we are, loading up all patients then we have 400,000 odd just for Tonga. might be ok as `byId` ?

**Comment by joshxg** [comment]
Ah cool.

Yeah, it might pay to actually test it out. Although currently I don't really see a need for having the `byId` field given we don't need to display lists of any of this (??)
