### ISSUE TITLE
Ordering of ENTERED DATE orders supplier invoices on the same day wrong

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#362]
Build Number: 25

Description: See title. Invoice 6 is the latest, but is shown below invoice 5. Appears to have happened on the prior day too.
![screenshot_2016-09-28-04-23-42](https://cloud.githubusercontent.com/assets/7684221/18898687/b01c2c1e-858f-11e6-9536-022559448195.png)
Reproducible: Yes

Reproduction Steps: make 2 requisitions / supplier invoices consecutively on the same day.

Comments:

**Comment by adrianwb** [comment]
The mSupply master now has the [transact]entry_time field, so you can go ahead and make the changes on mobile

**Comment by joshxg** [comment]
Happened across this and it's been fixed with `4.0.0`
