### ISSUE TITLE
Add patient events and name_notes to the schema

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3620]
## Is your feature request related to a problem? Please describe.

We need to start accepting patient events and name notes through sync as well as sending them back to the server (name_notes)

## Describe the solution you'd like

- Add to the schema:
	- `[name_note]`
	- `[patient_event]`
- Add to `incomingSyncUtils`
	- `[name_note]`
	- `[patient_event]`
- Add to `outgoingSyncUtils`
	- `[name_note]`
- Add to `SyncQueue`
	- `[name_note]`

## Implementation

- I am not sure exactly what each of the fields do on the tables and which exactly will be required.
- I am not sure exactly which patient events we will be creating
- I am not sure exactly how they are used currently

## Describe alternatives you've considered

N/A

## Additional context

![image](https://user-images.githubusercontent.com/35858975/109091644-0d6e9b00-777a-11eb-965c-e2b1eb2baa01.png)

![image](https://user-images.githubusercontent.com/35858975/109091664-15c6d600-777a-11eb-8f29-966290f3ad3a.png)

**Comment by joshxg** [comment]
@mark-prins 

I've actually realised that I am not clear on how we're actually going to use `name_note` and `patient_event`.

Options:

1. Make a `patient_event` which has a code `vaccine_survey`, and then create a `name_note` record for each of the fields in the survey, which is related to the `patient_event` that has the code `vaccine_survey` and the patient? The `event_type` on the `patient_event` could be `object`? In which case we need to probably update the `name_note` interface in mSupply incase people check it and it blows up? Although we wouldn't put anything in the `note` field so it would probably be fine, and just not list anything.
2. Or, make many `patient_event` records all with a code that matches a single field in the vaccine survey

I prefer `(1)`

**Comment by mark-prins** [comment]
I prefer `#1` too. I was originally thinking to add an object field to the `[name_note]` table and drop the whole survey response into that as an object. That does mean some work later in mSupply to support display of that sort of data in the `name_note` tab.

Alternative is to use the existing `[name_note]` fields and create a new note for each item in the survey form. 
I prefer the new object field - either way would work fine though.
