### ISSUE TITLE
Sensor: Temperature Breach Graph axis (X, Y) UI enhancement

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3625]
## Describe the bug

Some enhancement is needed in Sensor's Graph. For instance, in Detail dialog window of Temperature breach Y axis only shows Date irrespective of time that seems unclear.

### To reproduce

1. Go to Vaccine -> Sensor Detail page
2. One should have atleast one temperature Breach in a day.
3. Click on temperature breach icon from the graph
4. See error. Y axis is only showing Date irrespective of time
![photo_2021-02-25 11 36 17](https://user-images.githubusercontent.com/58979436/109109614-b8bd2700-775d-11eb-9e1d-cf192dbc2926.jpeg)

### Expected behaviour

It would be better if Temperature breach graph shows time as well

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0-rc7
- Tablet model: Lenovo
- OS version: 8.1

**Comment by joshxg** [comment]
Thanks @ArpitaSussol - I do agree, it needs to look better!

**Comment by wlthomson** [comment]
@ArpitaSussol As far as I can tell, the x-axis ticks are formatted only to include time if the day is the current date. AFAICS, including time doesn't really take up much space (if the time is formatted succinctly, which it is), so suggested solution is to update tick formatting to always include date + time.

**Comment by wlthomson** [comment]
Fixed by #3667.

**Comment by ArpitaSussol** [comment]
Tested in 7.0.0.rc10

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Temperature line chart tick labels display both time and date.
- [ ] Temperature line chart x-axis has no more than 15 ticks. -FAILED
showing more than 15 ticks
![photo_2021-03-10 18 12 17](https://user-images.githubusercontent.com/58979436/110629471-4b34e000-81cc-11eb-9250-dcd100205210.jpeg)

- [x] Temperature bar chart tick labels display both time and date.
- [ ] Temperature bar chart x-axis has no more than 15 ticks. -FAILED
showing more than 15 ticks
![photo_2021-03-10 18 12 24](https://user-images.githubusercontent.com/58979436/110629525-57b93880-81cc-11eb-9593-73b4446f472f.jpeg)
