### ISSUE TITLE
Sensor Thresholds: HOT Cumulative showing lower value than COLD Cumulative

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3626]
## Describe the bug

In Sensor Thresholds setting, HOT Cumulative showing lower value than COLD Cumulative

### To reproduce

Steps to reproduce the behaviour:

1. Go to Vaccine-> Add Sensor -> Go to Step 2 of Sensor Threshold
2. Click on "-" icon for Hot cumulative in such a way that its value be lower than Cold Cumulative.
3. See error. It allows in case of Cumulative where as in case of Consecutive Hot/Cold it doesn't allow
![photo_2021-02-25 12 31 49](https://user-images.githubusercontent.com/58979436/109114245-7566b680-7765-11eb-97b0-e3f04872fe50.jpeg)

### Expected behaviour

Temperatures are bound by the hot/cold in each group. HOT Cumulative cannot be lower than COLD Cumulative and vice versa. Also "-"  sign against values shown as dot "." when number's length increases. It would be good to enlarge space for Value field.
![photo_2021-02-25 12 31 12](https://user-images.githubusercontent.com/58979436/109114178-62ec7d00-7765-11eb-81c1-b9b2a6279050.jpeg)

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0-rc7
- Tablet model: Lenovo
- OS version: 8.1

**Comment by ArpitaSussol** [comment]
@katherine-sussol i am not sure is this because of +-0.1 margin, values are showing in this way. 
But it seems incorrect to me  as Hot cumulative can be 1.9 or above and Cold Cumulative can be 2.0 and below.
What its going to treat when Cumulative Temperature is 2.0?? 
![photo_2021-03-04 10 26 53](https://user-images.githubusercontent.com/58979436/109912563-730bdb80-7cd4-11eb-8068-8ccae9cff400.jpeg)
![Screen Shot 2021-03-04 at 10 28 37 AM](https://user-images.githubusercontent.com/58979436/109912581-7acb8000-7cd4-11eb-8696-3b3af344bbb5.png)

**Comment by katherine-sussol** [comment]
@ArpitaSussol Whoooops. Yes. I think there is a + and a - around the wrong way, the hot is supposed to always be at least 0.1 above the cold. I think consecutive ones are fine but the cumulative settings are the wrong way around.

**Comment by katherine-sussol** [comment]
Needs testing in RC9

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0.rc9

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Try to add new sensor
  - [x] Try to set hot cumulative <= cold cumulative (shouldn't let you)
  - [x] Try to set cold cumulative >= hot cumulative (shouldn't let you)
- [x] Try to edit existing sensor
  - [x] Try to set hot cumulative <= cold cumulative (shouldn't let you)
  - [x] Try to set cold cumulative >= hot cumulative (shouldn't let you)
