### ISSUE TITLE
Vaccine->Sensor: Sensor code is showing previous value even if its left blank/empty

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3627]
## Describe the bug

Sensor code is showing previous value even if its left blank/empty. 

### To reproduce

1. Go to Vaccine -> Sensor -> Add Sensor
2. Enter details Sensor name and Sensor code . Click save
3. Remove the sensor. Try adding same sensor with different sensor name and Sensor code (can be left blank as well)
4. See error. Sensor Code shows exisiting old value.

https://user-images.githubusercontent.com/58979436/109124783-6e46a500-7773-11eb-930b-7cc8604d64da.mp4

https://user-images.githubusercontent.com/58979436/109124899-8caca080-7773-11eb-8aa0-1d4364bb0542.mp4

### Expected behaviour

Sensor code should be updated and reflect the updated value

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0 RC7
- Tablet model: Lenovo
- OS version: 8.1

**Comment by wlthomson** [comment]
Confirmed replicated on latest build.

**Comment by wlthomson** [comment]
Fixed by #3654.

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0.rc9

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Edit an existing sensor code. After saving and navigating back to the sensor edit page, the code has been updated.
- [x] Delete an existing sensor. After reconnecting the sensor with a new code and navigating back to the sensor edit page, the code has been updated.
