### ISSUE TITLE
(L)App becomes quite unresponsive when tables are heavily populated.

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#363]
Build Number:25/26

Description: When there is a lot of rows in a table, the whole app becomes quite slow. Entering values in a field will take a frustrating amount of time to selected the next row when pressing next. Finalise button will take a few moments before rendering the press and bringing up the modal. Affects Customer Invoices and editing stocktakes. Have not tested but likely to affect all pages with a table and too many rows rendered e.g. supplier invoice, requisition, manage stocktake, current stock (not that you can do much there anyway).

Reproducible: Yes

Reproduction Steps:
1. Use a large data set i.e. Copy of East timor data, sync with Balibar PS
2. Create/open a customer invoice
3. Press `Add Master List Items`. Make sure that the master list is 100s of items.
4. Test the interface - note the delay on the next button and finalise.
5. Repeat the issue in editing a stocktake that was created with all items selected.

Comments:

**Comment by sworup** [comment]
One of the steps to do this could replace ListView with `new list components, such as FlatList or SectionList for bounded memory use, fewer bugs, better performance, an easier to use API, and more features.` Excerpt directly taken from React Native doc 😄.

**Comment by joshxg** [comment]
A lot of data table issues, have made #1043 in hopes of consolidating them all
