### ISSUE TITLE
Mobile Vaccines: Permissions and Services Window

### ISSUE THREAD

**Issue by RowenaN** [openmsupply/mobile#3633]
## Describe the bug

![image](https://user-images.githubusercontent.com/71358001/109435181-11eaca80-7a7e-11eb-9c95-3786b8363bbe.png)

- "and" needs to be inserted between the permissions and services.  But could perhaps be simplified to: "The following permissions and services are required for cold chain functionality."
- Also - do you press on the icon or the line (sorry don't have access now to test)?  If icon (as per docs), please change the second sentence to: "Press on any disabled icon to enable the permission or service." If line, please let me know and I can update docs :-)
- We generally give windows a title - makes it easier for reference?

### To reproduce

See above

### Expected behaviour

Correction to wording

### Proposed Solution

As above

### Version and device info

Sorry, don't have access currently but from google docs: https://docs.google.com/document/d/1MD17DWP5BJYVh7KuHsdexHUhSMBB0JWg8TeBAR4_gBY/edit#heading=h.ktu9skw3ggj0 

(Let me know if you need further explanation - RN)

### Additional context

N/A

**Comment by katherine-sussol** [comment]
> * "and" needs to be inserted between the permissions and services.  But could perhaps be simplified to: "The following permissions and services are required for cold chain functionality."

👍 Nice and succinct!

> * Also - do you press on the icon or the line (sorry don't have access now to test)?  If icon (as per docs), please change the second sentence to: "Press on any disabled icon to enable the permission or service." If line, please let me know and I can update docs :-)

I just gave this a test on a tablet, looks like it is the whole line is selectable

> * We generally give windows a title - makes it easier for reference?

Humm maybe something like "Permissions and Services"? I wonder if it's too duplicate-ey (what's the real word for this) of the subheadings? 🤔

**Comment by mark-prins** [comment]
It's the whole line, not just the icon.

**Comment by mark-prins** [comment]
Adding a title caused issues with the layout.. and it was difficult to decide on what to call it.
It is something akin to 'System Configuration' as these are android / tablet settings which need to be configured / enabled and are distinct from the app settings or preferences.

**Comment by RowenaN** [comment]
Thanks - will change the docs to indicate whole line rather than icon.  

I will update screenshots later with wording changes (I am saving screenshots until the end - in the same way I used to save referencing for uni assignments until the end - and like then I will probably say, I will never do that again).

The heading was just a suggestion.  Not sure if the above wording changes makes the layout easier? From an idiot perspective, could you give it one title "Permissions and Services" with a list of four items (get rid of the "Permissions" and "Services" subtitles)?

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0rc10

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Permissions modal reads: `"The following permissions and services are required for cold chain functionality."`
