### ISSUE TITLE
Mobile Vaccines: Cumulative Breach Period

### ISSUE THREAD

**Issue by RowenaN** [openmsupply/mobile#3635]
## Describe the bug

It is not specified how long the cumulative breach period is.  In ColdChain the default setting is 72 hours.  However the user can adjust this through adjusting the graph period.  From the ColdChain user manual:

![image](https://user-images.githubusercontent.com/71358001/109440594-b0375a00-7a97-11eb-937c-8d4fa8863e9d.png)

### To reproduce

As above - not sure if this is just not configurable (?), or just not specified in docs.  Raising here so can understand whether this is a feature or just a bug in the docs....

### Expected behaviour

Either period is configurable - further explanation is required in docs.  

If not configurable, default period should be specified in docs.  

### Proposed Solution
As above - up to dev / specs / users....

### Version and device info

Sorry, don't have version - working off docs here:
https://docs.google.com/document/d/1MD17DWP5BJYVh7KuHsdexHUhSMBB0JWg8TeBAR4_gBY/edit# 

### Additional context

This might just need clarification for docs - please let me know if this is the case (RN)

**Comment by wlthomson** [comment]
A cumulative breach is basically a summation of log durations within a given time window. For the log to be included, it has to have been above/below the breach threshold. The log durations and thresholds are set on the sensor, whereas the time window can be adjusted when visualising the data (the "graph period"). 

So, yes, the graph period can be adjusted. Does that make sense?

Do you want me to update the docs?

**Comment by RowenaN** [comment]
Thanks Will. This is for the CC app:
![image](https://user-images.githubusercontent.com/71358001/109701154-91e87000-7bf7-11eb-822a-d7d1a4859105.png)

So I now understand, for Mobile Vaccines: 

- Duration and temperature are set under Sensor thresholds - set for the sensor as properties

- Period is set using the graph period (z window) - thus can be adjusted at visualisation and is not a property of the sensor.

This is completely fine - just trying to ensure that the public docs describe correctly. The only thing that needs to be noted is that we cannot say that Mobile Vaccine has the same functionality as CC.  I have had a quick look at the WHO PQS requirements and I don't think this is required for the 30-day logger.  But could someone who is involved in WHO qualification of Mobile Vaccines please note as something to check?

I can change the public docs as I need to make other changes as well (thanks for the offer Will).

**Comment by joshxg** [comment]
Cold chain works the same way. The Z-window of the graph (on the detail view) on cold chain determines the z-window. The z-window by default on the list-view is 72 hours (3 days).

The list view on mobile does not show cumulative breach (nor graphs) on the list view, so we can just omit that there is a 72 hour default situation thing

Cold chain docs:

Page 6
![image](https://user-images.githubusercontent.com/35858975/109709664-a16cb680-7c01-11eb-885e-d9b3e0dc7f51.png)


Page 7
![image](https://user-images.githubusercontent.com/35858975/109709573-8d28b980-7c01-11eb-9211-13c404d734ad.png)

**Comment by RowenaN** [comment]
So when does the period setting work in CC?  I thought if you set "period" it would overwrite the default.  Or is it just there to give the impression that we let users decide - cunning!

Ok, for mobile the default z period = 72 hours - so graph will show last 72 hours by default.  If you change the date range above the graph, does it save or if close and reopen will it always revert to 72 hours?

(sorry, I might be sidetracking things on github)

**Comment by joshxg** [comment]
> So when does the period setting work in CC? I thought if you set "period" it would overwrite the default. Or is it just there to give the impression that we let users decide - cunning!

- The list view is 72 hours, the default when you navigate to the detail view is 72 hours which can be changed.

> Ok, for mobile the default z period = 72 hours
Mobile default z-window on the detail view is 30 days.. why? I dunno.

> does it save or if close and reopen will it always revert to 72 hours?
z-window changes are not saved

**Comment by wlthomson** [comment]
Closing as looks like this discussion is resolved now 👍 .
