### ISSUE TITLE
Supplier Invoice: Item list column inconsistency for vaccine and non-vaccine item

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3648]
## Describe the bug

In Supplier Invoice, Item list column shows inconsistency while adding and sorting for vaccine and non-vaccine item.

 **Similar inconsistency can be seen on Customer Invoice Item columns as well.**

### To reproduce

1. Uncheck Payment section from Store -> Preference in Desktop
2. Sync. Go to Supplier Invoice -> Create new Supplier invoice
3. Add non-vaccine Item & then add vaccine item.
4. See error. Columns become clumsy and there is no new column(Location, VVM status) shown for vaccine item

https://user-images.githubusercontent.com/58979436/109618143-4f735480-7b5f-11eb-858f-c5865bafd98d.mp4

https://user-images.githubusercontent.com/58979436/109618191-5bf7ad00-7b5f-11eb-82c9-11129d96c0ee.mp4

### Expected behaviour

Column should be shown in case of vaccine item and should be assigned N/a or hidden when non vaccine item

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V7.0.0 rc7
- Tablet model: Lenovo
- OS version: 8.1

### Additional context
 
this problem might not occur when every line item is of type vaccine. Not sure about wether vaccine and non vaccine item should be allowed/entered in one.

**Comment by katherine-sussol** [comment]
Thanks @ArpitaSussol - am able to reproduce this one for Supplier and Customer Invoices. On my tablet the columns don't even re-adjust like they do in the video 😆.

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0 rc8

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Add non-vaccine item to SI/CI
- [x] Add vaccine item to SI/CI
- [x] New vaccine columns should appear with N/A for non-vaccine items, there should be one header per column
- [x] Remove vaccine item from SI/CI
- [x] Vaccine columns should disappear, and there should be one header per column

For SI, Location option icon get enabled for non-vaccine item. 
Created an issue #3664
