### ISSUE TITLE
SI: VVM status shows inconsistency in case of inactive and default values

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3666]
## Describe the bug

VVM status by default shows first option as value. If that value becomes inactive still values keep showing.

### To reproduce

1. Go to Desktop. Go to Item ->Vaccine -> Show vaccine vial monitor status
2. Create 3-4 options as active. Sync
![Screen Shot 2021-03-04 at 1 54 44 PM](https://user-images.githubusercontent.com/58979436/109931655-369aa880-7cf1-11eb-8f00-35c03f3bc577.png)

3. Go to Mobile app -> Supplier Invoice -> Create an SI -> add vaccinated item
4. VVM status and Location is shown 
5. Location is assigned N/A where as VVM column is filled with First VVM option.
6. Now go to Desktop. Go to Vaccine -> Show Vaccine vial monitor status -> Inactive the first option
![Screen Shot 2021-03-04 at 1 35 46 PM](https://user-images.githubusercontent.com/58979436/109930830-3057fc80-7cf0-11eb-9000-37cb12608b1c.png)

7. Sync. Go to mobile app -> check the unfinalized SI created above
8. See Error. VVM column is still filled with inactive value
9. Create another new SI in mobile. Add vaccine item. 
10. See Error. in this Item list as well inactive VVM value shown

https://user-images.githubusercontent.com/58979436/109931207-a8bebd80-7cf0-11eb-99f6-47275255821d.mp4

### Expected behaviour

for new SI, default value should be the vvm status which has the lowest VaccineVialStatus.level is applied

I am not sure what should be the intended behavior if VVM's value is already assigned and then turn into inactive for unfinalised SI. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0 RC8
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #2913

**Comment by katherine-sussol** [comment]
Thanks @ArpitaSussol I can reproduce this one. I can also reproduce the same behaviour when doing a Stocktake. 

I don't know how often VVM statuses would be made inactive, but I think ideally if a VVM was already assigned and then inactivated, it should probably default to the lowest active available?

**Comment by joshxg** [comment]
I reckon the behaviour should be if you set a vvm status to inactive, it does not update any historic values, but just does not allow you to select this vvm status in the future. 

If we follow this, then if there is an unfinalised line with an inactive vvm status already assigned, I think it is OK to leave it assigned?

🤷 

I think as long as we can't assign new lines an inactive status, it will be OK and this is an edge case that we can fix at some 'later point'?

**Comment by katherine-sussol** [comment]
That's pretty much how it works now for unfinalised invoices/stocktakes, it will keep all historic values (incl inactive states), but if you try to edit any you're forced to pick an active one (or close the modal). 

The weirdest behaviour is probably when adding a new vaccine line (if the lowest vvm status was made inactive),  it still defaults to the inactive one. So it will still technically be possible to create new invoices with an inactive status. It's still kind of edge case-ey but a little more annoying. Maybe we fix the 'default' behaviour and leave the editing of unfinalised stocktakes/invoices to later?

**Comment by joshxg** [comment]
Ya sounds like the query for assigning a vvm status is not filtering by active, so if we just add that it should be good enough?

**Comment by katherine-sussol** [comment]
Needs testing in RC9

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0 rc9

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Ensure there are some vaccine items available to the store for testing
- [x] In Desktop, set the lowest VVM status to inactive (Item -> Vaccines -> Show Vaccine Vial Monitor Status)
- [x] Try to do a stocktake or create a new supplier invoice and add a vaccine item line
- [x] The VVM Status should default to the one with the lowest level that is active
