### ISSUE TITLE
Manage state and rendering of JSONForm

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3670]
## Is your feature request related to a problem? Please describe.

The JSONForm implementation is re-rendering and forgetting entered values.
Look at making it a little more stable & implement pre-populating with previously saved responses for the current patient.
[Reference](https://github.com/openmsupply/mobile/pull/3661#discussion_r587249405)

**Comment by joshxg** [comment]
This is tied in with #3663

**Comment by joshxg** [comment]
Hmm.. actually maybe need to revisit this to have more control over number of renders
