### ISSUE TITLE
Mobile Vaccines: chevron icon overlaps with time string

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#3673]
## Describe the bug

Migrated from #3665,

Log record time label overflow and overlap with Sensor detail icon.

### To reproduce

1. Go to Sensor list page. Check the alarm icon label. When alarm label shows two digit value and "minutes" , label overlap with Detail icon.
![2021-03-04 13 08 08](https://user-images.githubusercontent.com/58979436/109926116-b3765400-7cea-11eb-8bfc-d2edbdf45da6.jpg)

### Expected behaviour

Margin should be there between Alarm icon label and Detail icon.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0 rc8
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #2913

**Comment by wlthomson** [comment]
Fixed by #3678.

**Comment by ArpitaSussol** [comment]
tested ni v7.0.0 rc10

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Setup a sensor with a log interval > 10 minutes (e.g. 15 minutes). View the sensor > 10 minutes after the last temperature log. The date string does not overlap the chevron icon.
