### ISSUE TITLE
Vaccine dispensing: Add option for refused vaccination

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3683]
## Is your feature request related to a problem? Please describe.

`are we able to include a box somewhere for refusers?`

## Describe the solution you'd like

- Add a 'Refused' option to the survey form
- Add the ability to save and quit to step two

## Implementation

The buttons on the second step are currently `Cancel` and `Next`
~~Add a `Save & Exit` button in the middle of the current buttons - rationale is that the usual workflow is to continue to step three, so that button should be rightmost.~~

~~This interrupts the user flow, and stops the 'ok & next' being an option for users. it would be a rare event though, so probably ok~~

On the third step: 
- Add a refused checkbox
- If selected
  - Don't create a prescription
  - Record a patient event for 'Refused vaccination'
  - Save the patient edits and survey details

## Describe alternatives you've considered

- Add a `Save` button - this would then require the user to click `Cancel` to leave the process; which I think is confusing - does cancel then undo the save? I would also expect users to click `Save` during normal workflow which adds an unnecessary button click
- Add a `Refused` button which stores the refused option and saves and quits : this is tightly bound to the contents of the survey form and is therefore less configurable
- Allow some form of zero quantity selection or 'refused' vaccine on step three, so that users can follow the usual process - this creates a prescription which is clearly marked as refused vaccination and meets the reporting requirements and saves the form and allows for the user to click 'ok & next' at the end of the process

**Comment by joshxg** [comment]
> Allow some form of zero quantity selection or 'refused' vaccine on step three, so that users can follow the usual process - this creates a prescription which is clearly marked as refused vaccination and meets the reporting requirements and saves the form and allows for the user to click 'ok & next' at the end of the process

I like this option- I was thinking we could possibly create a new `name_note` "refused vaccine".

This would need:
- A new patient event "vaccine refusal"
- Button can be conditional on there being a vaccine refusal button

I don't like:
- Patient events are user defined, and creating conditionals on user defined data is flimsy and not ideal.
