### ISSUE TITLE
Sensor: updating logging interval and sensor code field frequently shows alert warning and doesn't allowed to update the Sensor's value

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3705]
## Describe the bug

 updating logging interval and sensor code field frequently shows alert warning and doesn't allowed to update the Sensor's value. Its not showing consistent behavior. Sometimes error alert is shown sometimes its not. Not sure whats causing this behavior. I tried removing the Sensor followed by restarting the app and adding sensor again but after few updates it start showing same error alert message.

### To reproduce

1. Go to added sensor list
2. Click on cog icon
3. Change the Sensor code and then change the logging interval. Click on Save
4. It might saved/updated. If updating successful try repeating step 3 again
4. See error. It shows error " A download is in progress, please try again soon"

https://user-images.githubusercontent.com/58979436/110440044-53afec80-80e0-11eb-83c0-fb980557b4c8.mp4

### Expected behaviour

Its should update the values without any alert error warning

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V7.0.0 rc9
- Tablet model: Lenovo
- OS version: 8.1

### Additional context

Low priority for now as its not blocker.

**Comment by joshxg** [comment]
@katherine-sussol 

I spoke to arpita a little last night and she was saying that she was waiting a good few minutes and at some point she would *only* get the alert. I thought it sounded like the state might be getting stuck and never allowing downloads for a bit? Maybe worth investigating a little? 

Even after an app restart the alert would still be persistent, so maybe the potentially incorrect state is being persisted also?

I dunno, thought it warranted a look around as if it was true (state being put in an incorrect... state ( 🙄 )  and being persisted preventing updating the log interval forever) it seemed like a bit of a nightmare

**Comment by katherine-sussol** [comment]
Can confirm something funky going on with download state - hopefully, with the linked PR it's a bit better.

To re-test in RC10(? - or whichever build comes after RC9)

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0 RC10

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Re-test #3705 and verify that the sensor log interval can be updated more consistently (it will still fail if there is a download happening in the background but should happen less after this change)
- [x] Verify downloads are still happening every ~1min in the background (check wifi icon in UI for user testing or console logging for dev testing)
