### ISSUE TITLE
Vaccine dispensing UI polish

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3708]
## The suggestion

- A little bit of UI polish for the vaccine dispensing
- I don't have anything explicit in mind it just feels like it needs some polish

**Why?**

- Cause it makes me feel better

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
@mark-prins I am thinking to try and use the `Paper` components a little more cause I think they look nice. Any niggles you have that should be touched up?

**Comment by mark-prins** [comment]
> Any niggles you have that should be touched up?

The centred drop-down pop-up thing bothers me, but I think leave that alone, it's a bigger discussion!
The `vaccinator` selection could be better.. though I'm not sure what to do with it sorry..
