### ISSUE TITLE
When using a patient from the patient API also send a request to create a name store join

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3710]
## Is your feature request related to a problem? Please describe.

- When we look up a patient, there is no visibility created. This means you will not receive any updates to the record, receive new but related data or receive the patient when initialising (arguably good)

## Describe the solution you'd like

- Create a `name_store_join` for a patient when looked up from the patient api

## Implementation

- Create a `name_store_join` for a patient when looked up from the patient api

## Describe alternatives you've considered

Not doing this.

## Additional context

I think this is a good idea. I think if we want to limit init cost, we could potentially delete the nsj's on the server which aren't related to a patient whos home store is the mobile store?

**Comment by joshxg** [comment]
@mark-prins I know they're pre-registering patients, but there's surely gonna be some that aren't registered? 🤷 

@Chris-Petty If we go ahead with this (creating a nsj when looking up a patient), do you have any thoughts on side effects

**Comment by Chris-Petty** [comment]
@joshxg Just to clarify, the current thinking for creating a name_store_join to be done server side or on mobile? I'd assume server side, but this reads that you want to do it on mobile?

That said, surely making patients on both mobile/desktop makes an nsj on the satellite. So I presume it'd be fine for mobile to make the nsj for one they've looked up, except an edge case (which wouldn't occur for a _new patient_):

1. SiteA lookup patient.
2. makes nsj, starts prescription. No sync yet.
3. EDGE: siteB that prescribed to the same patient last week finally syncs after being offline for ages.
4. Server doesn't know to send history created in above step to siteA, as it has no nsj between the patient and siteA.
5. SiteA syncs - it forever has this gap in patient history.

That could feasibly happen IMO. First thought in mind to solving that:

1. Server responsible for nsj from search
2. client app searches for patient
3. client app must confirm selection (upon request, an nsj created via new endpoint, I guess? (do we go full REST and open up `REST/vX/name_store_join` that can be PUT to?)) 
4. Good to go however we handle from here currently?

Q: Mobile currently makes the prescription based on the results from the search API, saving a record of the `name` aye? 

>I think this is a good idea. I think if we want to limit init cost, we could potentially delete the nsj's on the server which aren't related to a patient whos home store is the mobile store?

I always assumed that the server already made nsj's for the search API haha. For limiting initialisation, I think that's a fair idea to add (as a new issue following this?). An alternative: if you prescribe to a patient and don't make any nsj as we currently do, just make it that you always have to use the search API to prescribe to that patient again (i.e. get fresh history). Would be simpler, though not so "offline first". Not sure where this lands, we always have to balance the right compromise with sync.

(Side note: there is a boolean controlling vis on the nsj, we've avoided deleting them for better or worse)

**Comment by joshxg** [comment]
> creating a name_store_join to be done server side or on mobile? I'd assume server side, but this reads that you want to do it on mobile?

The patient lookup API actually returns a list of all patients leftover after the filters are applied so the server doesn't know which patient the client wants. Would require a new endpoint to create the nsj so my suggestion is to create the nsj on the client.

> That said, surely making patients on both mobile/desktop makes an nsj on the satellite.

Mobile doesn't make the nsj in this case- the satellite makes it when new patients are sent

🤔 

> except an edge case (which wouldn't occur for a new patient)

Your edge case is valid- i'm going to state another edge case now which will direct your attention away: there are quite a few edge cases with the patient lookup API being a secondary source of incoming data. For example:

- Sync on mobile
- Insurance provider created
- Patient created with an insurance policy for the insurance provider
- Mobile looks up patient (comes with insurance policy)
- Mobile doesn't have the provider for the policy, yet

-----------

Anyway: If we use the bomb pref for Tonga, which will allow patients to sync everywhere, we don't need this and I think creating a new endpoint is an option. If we don't, then we need a solution and the quickest is to create a nsj on mobile

**Comment by mark-prins** [comment]
I'm now favouring creating a confirmation endpoint ( which creates the nsj ) to minimise the possibility of missing out on updates to the `name` and related records - though the likelihood is pretty low.

**Comment by joshxg** [comment]
Yeah it's certainly the safest route so I agree that an endpoint is the way to go! (concern at the moment is timing with mSupply releases)

**Comment by joshxg** [comment]
Have made an mSupply issue here: https://github.com/sussol/msupply/issues/8270

**Comment by adrianwb** [comment]
> 
> 
> @joshxg Just to clarify, the current thinking for creating a name_store_join to be done server side or on mobile? I'd assume server side, but this reads that you want to do it on mobile?
> 
> That said, surely making patients on both mobile/desktop makes an nsj on the satellite. So I presume it'd be fine for mobile to make the nsj for one they've looked up, except an edge case (which wouldn't occur for a _new patient_):
> 
>     1. SiteA lookup patient.
> 
>     2. makes nsj, starts prescription. No sync yet.
> 
>     3. EDGE: siteB that prescribed to the same patient last week finally syncs after being offline for ages.
> 
>     4. Server doesn't know to send history created in above step to siteA, as it has no nsj between the patient and siteA.
> 
>     5. SiteA syncs - it forever has this gap in patient history.
> 
> 
> That could feasibly happen IMO. First thought in mind to solving that:
> 
>     1. Server responsible for nsj from search
> 
>     2. client app searches for patient
> 
>     3. client app must confirm selection (upon request, an nsj created via new endpoint, I guess? (do we go full REST and open up `REST/vX/name_store_join` that can be PUT to?))
> 
>     4. Good to go however we handle from here currently?
> 
> 
> Q: Mobile currently makes the prescription based on the results from the search API, saving a record of the `name` aye?
> 
> > I think this is a good idea. I think if we want to limit init cost, we could potentially delete the nsj's on the server which aren't related to a patient whos home store is the mobile store?
> 
> I always assumed that the server already made nsj's for the search API haha. For limiting initialisation, I think that's a fair idea to add (as a new issue following this?). An alternative: if you prescribe to a patient and don't make any nsj as we currently do, just make it that you always have to use the search API to prescribe to that patient again (i.e. get fresh history). Would be simpler, though not so "offline first". Not sure where this lands, we always have to balance the right compromise with sync.
> 
> (Side note: there is a boolean controlling vis on the nsj, we've avoided deleting them for better or worse)

See https://github.com/sussol/msupply/issues/8270#issuecomment-800172798

Patient history (if by that you mean prescriptions?) doesn't follow patients around by default (unless you turn on a pref to share prescriptions across stores, and you turn on the store syncing of prescriptions prefs) - other stuff (like insurance, PMR) is linked to the patient itself and is retrieved by the API, so I'm not sure that the edge case here is valid? However, as pointed out elsewhere, the data pulled could be rendered out of date by someone on another site changing it, but I'm not sure that there's much you can do about that?

Obviously, just looking up a list of patients matching some search criteria shouldn't make them all visible - that should only happen whenever a single patient is selected (or, like desktop, whenever a prescription is created for them).

**Comment by adrianwb** [comment]
> Your edge case is valid- i'm going to state another edge case now which will direct your attention away: there are quite a few edge cases with the patient lookup API being a secondary source of incoming data. For example:
> 
>     * Sync on mobile
> 
>     * Insurance provider created
> 
>     * Patient created with an insurance policy for the insurance provider
> 
>     * Mobile looks up patient (comes with insurance policy)
> 
>     * Mobile doesn't have the provider for the policy, yet

I don't think there's any way around this, other than to try again later. I'd be more worried if you create an prescription linked to a policy which has already been deleted but not synced!

**Comment by Chris-Petty** [comment]
> See [sussol/msupply#8270 (comment)](https://github.com/sussol/msupply/issues/8270#issuecomment-800172798)
> 
> Patient history (if by that you mean prescriptions?) doesn't follow patients around by default (unless you turn on a pref to share prescriptions across stores, and you turn on the store syncing of prescriptions prefs) - other stuff (like insurance, PMR) is linked to the patient itself and is retrieved by the API, so I'm not sure that the edge case here is valid? However, as pointed out elsewhere, the data pulled could be rendered out of date by someone on another site changing it, but I'm not sure that there's much you can do about that?
> 

I had a chat with Josh the other day. Back when it was first done there was talk of some kind of condensed history, so that drug interactions could be spotted by those dispensing - didn't happen though cause time and stuff! I still think something like that would be great. Mobile could even try doing it asynchronously:

Select your patient, immediately start a request for last 3(?) months of dispensed medicines in the background - user starts filling out script in the mean time. If 

> Obviously, just looking up a list of patients matching some search criteria shouldn't make them all visible - that should only happen whenever a single patient is selected (or, like desktop, whenever a prescription is created for them).

Yup absolutely, sorry if it wasn't clear. That was the idea with the confirm endpoint. Basically tell the server "Hey I'm making a prescription for this patient now, set the nsj up and give me a 200 response so I know I can proceed!".

**Comment by joshxg** [comment]
> I don't think there's any way around this, other than to try again later. I'd be more worried if you create an prescription linked to a policy which has already been deleted but not synced!

yeah there's a few issues I tried to point out which I don't think ever got solved, however it's been awhile since I've been in this space so I might be wrong:
- https://github.com/sussol/msupply/issues/5492
- https://github.com/sussol/msupply/issues/5491
- https://github.com/sussol/msupply/issues/5490

--------

This issue is now changing to implement a request sent to the endpoint being made here: https://github.com/sussol/msupply/issues/8270

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 rc3

## Testing

- Chose Remote Patient 
![photo_2021-03-22 15 28 50](https://user-images.githubusercontent.com/58979436/111970830-d47cd880-8b23-11eb-87b6-2eb67d536093.jpeg)
- selected a remote patient to normal dispense
- selected same remote patient to vaccine dispense
![Screen Shot 2021-03-22 at 3 35 39 PM](https://user-images.githubusercontent.com/58979436/111971319-4fde8a00-8b24-11eb-9075-dcfc33c2fd0a.png)
- Query the store ID
![Screen Shot 2021-03-22 at 3 26 55 PM](https://user-images.githubusercontent.com/58979436/111971480-7e5c6500-8b24-11eb-944f-7521e677d4b0.png)

- Query the name ID
![Screen Shot 2021-03-22 at 3 21 02 PM](https://user-images.githubusercontent.com/58979436/111971527-8ae0bd80-8b24-11eb-9229-ee1f42dfcb15.png)

- Only 1 name_store_join is created 
![Screen Shot 2021-03-22 at 3 27 19 PM](https://user-images.githubusercontent.com/58979436/111971607-a0ee7e00-8b24-11eb-8349-1b346d4416d0.png)


@joshxg @mark-prins is this intended behavior? For same patient with vaccine dispense and normal dispense only one name_store_join should be created or two ?

**Comment by joshxg** [comment]
@ArpitaSussol 

Sorry- should be more clear. Only one should ever be created :)

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC3

## Testing

- [x] When selecting a remote patient to vaccine dispense to, a name store join is created on the server (if you have the internet)
- [x] When selecting a remote patient to normal dispense to, a name store join is created on the server (if you have the internet)
