### ISSUE TITLE
Vaccine: The sensor log interval is not saved/set in the database

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3732]
## Describe the bug

A clear and concise description of what the bug is. Use screenshots!

### To reproduce

1. Go to Mobile ->Vaccine-> Add Sensor
2. Check/Set the Logging interval to any values
3. Sync. Go to Desktop -> Admin ->Record Browser -> Check sensor table
4. See error. Log interval value is showing 0
![Screen Shot 2021-03-11 at 11 04 32 AM](https://user-images.githubusercontent.com/58979436/110740986-00fb3f80-825c-11eb-8d20-5cdb574e6665.png)
![photo_2021-03-11 11 26 29](https://user-images.githubusercontent.com/58979436/110741378-a8787200-825c-11eb-9fae-7b01707d3aa9.jpeg)

### Expected behaviour

Log interval value should be set to defined value in Mobile after sync.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 7.0.0 rc10
- Tablet model: Lenovo
- OS version: 8.1

**Comment by joshxg** [comment]
Nice work- definitely needs to be fixed. Quick look at outgoing sync utils and there is no log interval being sent out.. at all!

**Comment by ArpitaSussol** [comment]
Tested in v7.0.0.RC11

## Testing

Steps to reproduce or otherwise test the changes of this PR:

1. - [x] Add a sensor in mobile - note log interval
2. - [x] Sync
3. - [x] Check Desktop for Sensor record and verify log interval matches what was set up in mobile (I can see the schema but not sure how to verify the record)
4. - [x] Uninstall mobile (or if there is another way to clear all saved data 🤷 )
5. - [x] Reinstall mobile 
6. - [x] Sync
7. - [x] Check the sensor exists in mobile with the log interval that was originally set up in step 1
