### ISSUE TITLE
Monthly usage is too high for newly added items

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3736]
## Describe the bug

The number of usage days to divide usage is very small when just synced and just creating requisitions

### To reproduce

1. Sync a site
2. Create a CI with some quants
3. Create a SR, check monthly usage

### Expected behaviour

monthly usage should be calculated correctly

### Proposed Solution

https://github.com/openmsupply/mobile/blob/c21dedf5f31bd667ab284dff76608adfc8241b2f/src/utilities/dailyUsage.js#L51

Think this line should take the ceil? Or `math.max(.., 1)`

### Version and device info

- App version: 7.0 dev?
- Tablet model:
- OS version:

### Additional context

Not sure when this was introduced, think 6.0

**Comment by katherine-sussol** [comment]
Replicated in develop 😆  - `Math.max(.., 1)` seems to do the trick and in line with `customerRequisitionProgramDailyUsage`. Not sure what the milestone should be - it looks like 8.0.0 is already released, will leave for now.

**Comment by katherine-sussol** [comment]
Closed with #3907
