### ISSUE TITLE
Buttons not disabled in a finalised customer requisition

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3737]
## Describe the bug

The button `use suggested quantity` and `use required quantities` are not disabled in a finalised customer requisition

### To reproduce

1. Go to Create a program CR
2. Click on finalise
3. click use suggested quants

### Expected behaviour

Should be disabled

### Proposed Solution

Disable em when finalised

### Version and device info

- App version: 6.0+ I guess
- Tablet model:
- OS version:

### Additional context

N/a

**Comment by wlthomson** [comment]
Hm, I can't replicate this on `v7.0.0-rc10`:

![#3737-finalised-cr-disable-buttons](https://user-images.githubusercontent.com/43223637/110879298-9d4b4200-8341-11eb-9aaf-932d3544ca96.png)

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 

## Testing

- [x] Get a CR from desktop (Create an Internal order to your mobile store) -> sync then finalise it -> buttons set suggested/requested are disabled.
