### ISSUE TITLE
Remove Generate Vaccine Data button

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3739]
## Is your feature request related to a problem? Please describe.

There is a button to generate vaccine data which is not hidden behind `__DEV__` or anything

## Describe the solution you'd like

Either remove the button or hide it behind `if (__DEV__)`

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by wlthomson** [comment]
Fixed by #3749.

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0.RC11

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] In release build check that in the settings menu there is no button to generate vaccine data and the page is not
