### ISSUE TITLE
Customer Credit: Item list is not syncing/shown to mobile app

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3740]
## Describe the bug

In mobile, customer credit's Item list created in Desktop doesn't sync or shown in the list.

### To reproduce

1. Go to Desktop -> create a customer invoice
2. Sync to mobile site
3. Go to Customer Invoice -> Past tab -> Click on above created Customer Credit
4. See error. Item list is not shown
![photo_2021-03-11 16 41 01](https://user-images.githubusercontent.com/58979436/110778314-4b93b080-828a-11eb-9f96-43fede844887.jpeg)
![Screen Shot 2021-03-11 at 4 39 43 PM](https://user-images.githubusercontent.com/58979436/110778340-53ebeb80-828a-11eb-80fa-f5ed095776e0.png)

### Expected behaviour

Either Item list should be shown for related Customer Credit or Customer Credit should be removed from the list completely.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0.rc10
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #1234

**Comment by joshxg** [comment]
Nice!

Was able to replicate this- seen this behaviour before, usually when there is a misalignment in the `widths` array v `columns` array for the route (A very mSupply-esque implementation of matching two arrays up 🤣 )

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC2

## Testing

- [x] On desktop, create a SUPPLIER CREDIT to your mobile store. Sync and view the customer credit in Customer invoices -> past tab- it has the lines
