### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3750]
## Is your feature request related to a problem? Please describe.

Some feedback

1. more gap between field label and the field above (e.g. on patient edit window)
2. Cancel and save buttons should be full width down the bottom of same window
3. date picker icon a bit low res?

**Comment by joshxg** [comment]
I suspect given the cancel/save buttons being full width will look silly when there are varied number of buttons on each page 🤔

**Comment by Chris-Petty** [comment]
Silliest nit that I noticed yesterday but didn't mention:

![image](https://user-images.githubusercontent.com/7684221/110887511-55331c00-834f-11eb-967a-e2be36796bef.png)

On the new vaccine dispensing page, the gap between left and right paper/sections is a little misaligned with the progress thingy. Might look better/more symmetrical if aligned. Might be not worth the effort!
