### ISSUE TITLE
Sensor log interval is not reset after downloading

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3758]
## Describe the bug

After downloading logs from a sensor, the log interval should be reset.

This causes all logs to be reset.

if the logs are not reset, then the sensor will likely reach the max amount of logs (`~20k`) and then ever time we download, we'll download and parse 20k logs each download which is not ideal.

### To reproduce

1. Download some logs
2. Check the number of logs via blue maestro for example

### Expected behaviour

Should send a log interval set command after downloading logs.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by wlthomson** [comment]
Fixed by #3766.
