### ISSUE TITLE
TemperatureLogs are not being saved by counting backward

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3759]
## Describe the bug

`TemperatureLog` records are being saved counted from the most recent log

If, for example, the battery runs out of battery for a while, then when the sensor comes on, we would start saving logs from when the battery ran out of battery.

We should be saving logs by counting *back* from the time now, so when the first download occurs after a sensors battery is replaced, we have a 'gap' in the logs from when the sensor was off.

This will be the same for when a sensor is paused.

### To reproduce

1. Go to a sensor and pause it
2. wait for awhile
3. start downloading logs again.
4. View the logs (email yourself a csv, it's easier)
5. See error

### Expected behaviour

Logs when downloaded should be counted backward.

This test case isn't good: https://github.com/openmsupply/mobile/blob/e5897abcb85870e70cf43645a097011ae48169bd/src/bluetooth/TemperatureLogManager.test.js#L161-L185

This is only true because `timeNow = 600`, `logInterval=300` and `mostRecentLog=0`. The log saved should be `300`, because that is `300` less than `timeNow`. But it is correct and `300` because it is also `300` more than the most recent log.

### Proposed Solution

Change `createLogs` to count back from the `timeNow` like it is already doing when there is no `mostRecentLogTime`, except that the log should be aligned with the most recent log. I think something like:

The test case `Creates the correct number of logs` should be:

```
...
const maxNumberToSave = 1;
    const mostRecentLogTime = 1;
    const timeNow = 1200;

    const logs = [{ temperature: 10 }, { temperature: 11 }, { temperature: 12 }];
    const shouldBe = [
      {
        id: '1',
        temperature: 12,
        location: undefined,
        timestamp: new Date(901 * MILLISECONDS.ONE_SECOND),
        sensor,
        logInterval: 300,
      },
    ];
```

I think change to something like:

```
let initial;
    if (mostRecentLogTime == null) {
      initial = moment.unix(timeNow).subtract((logsToSave.length - 1) * logInterval, 'seconds');
    } else {
      const numberOfLogIntervalsUntilNow =
        Math.floor((timeNow - mostRecentLogTime) / logInterval) + 1;

      initial = moment.unix(
        mostRecentLogTime +
          (numberOfLogIntervalsUntilNow * logInterval - maxNumberToSave * logInterval)
      );
    }
```

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by wlthomson** [comment]
Not sure if it's an issue, but I think even the above solution will not avoid some degree of error given the above scenario (up to the log interval). E.g.

Let `log_interval` be `3600` (1 hr). Assume the device starts logging on the hour but loses battery for some period and regains battery on the half hour. By working backwards, would not all the logs be off by that half hour? I.e. is this solution based on the assumption that the device will regain power exactly on the log interval offset, or are we OK with accepting a certain degree of error?

**Comment by joshxg** [comment]
You're right-

With our log interval being 10 minutes, and the log interval being reset after each download, then the log downloaded directly after replacing the battery would probably be pretty misaligned but it should align pretty quick- I think that reduces the error state to a pretty satisfactory level?

**Comment by katherine-sussol** [comment]
I think that sounds reasonable - if the logging is reset after the download, with the 'backward counting' that should mean the second log should have a more or less correct timestamp - think the only side effect is that the logging time will potentially move around a bit (not really a big deal but might look odd).
e.g. With logging interval of 10min
- Log 1 (10:00am)
- Log 2 (10:10am)
- Log 3 (10:20am)
- [Battery cutout]
- Log 4 at 11:09pm - App will timestamp with 11:00pm
- Log 5 at 11:19pm - App timestamps with 11:19pm - rest of logs will now not be on the 10min mark but more or less accurate

Possibly not that helpful to anyone but was thinking it through and want to check I'm not misunderstanding anything!

**Comment by joshxg** [comment]
I think this is why my suggestion code is so weird- it tries to account for this (if I remember correctly)

So:

- If there is no most recent log, we're just starting off, count back from now and just use that one, all good.
- Else, if there is one we could either be in the happy path where we just need to count from the most recent log or we could be in the battery just started logging again/unpaused path, so to try cover both, count how many logs were possible since the last log- if it's the happy path, it should be equal to max number to save and we just end up with the most recent log time. Otherwise, the max number to save is less, in which case we end up with an initial timestamp slightly greater than the most recently logged timestamp

Hope that makes sense- maybe the math could be clearer.

With comments? 🤣 

```
let initial;
// If we have not logged previously, just count back from now.
if (mostRecentLogTime == null) {
  initial = moment.unix(timeNow).subtract((logsToSave.length - 1) * logInterval, 'seconds');
} else {
  // How many logs could possibly have been logged since the last one
  const numberOfLogIntervalsUntilNow = Math.floor((timeNow - mostRecentLogTime) / logInterval) + 1;

  // Account for the possibility of the number of logs which could have been stored
  // until now being greater than the number we're actually saving due to pausing and/or batteries
  // turning off.
  const timestampOffset =
    numberOfLogIntervalsUntilNow * logInterval - maxNumberToSave * logInterval;

  initial = moment.unix(mostRecentLogTime + timestampOffset);
}
```
