### ISSUE TITLE
mSupplyMobileAppContainer re-renders whenever sync occurs

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3767]
## Describe the bug

- mSupplyMobileAppContainer re-renders whenever sync occurs

### To reproduce

Internal bug

### Proposed Solution

Check and see why it's re-rendering

### Version and device info

- App version: 1.0+
- Tablet model:
- OS version:

### Additional context

N/A

**Comment by wlthomson** [comment]
Might be a red herring, but I think could be `isSyncing` (`mSupplyMobileApp` prop used in class method `synchronise` which is passed as a prop to `SyncModal`).
