### ISSUE TITLE
Prescriber: Adding/Updating Prescriber's Gender field is not reflecting/saving

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3770]
## Describe the bug

Adding/Updating Prescriber's Gender field is not reflecting/saving. It always shows "Male" as updated/added value.

### To reproduce

1. Go to Dispensary -> Add Prescriber
2. Fill the necessary details and select Gender as "Female"
3. Open the Prescriber through Edit icon
4. See error. Gender's value shown is "Male"

### Expected behaviour

Gender should reflect the value that is chosen or updated.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 7.0.0 rc11
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #2108

**Comment by katherine-sussol** [comment]
Hmm I could reproduce this but from a use case perspective, I'm not sure whether displaying the gender toggle makes much sense on this screen? Does it matter if the prescriber is male or female? Took a look https://github.com/openmsupply/mobile/issues/2106 and https://docs.msupply.foundation/en:mobile:user_guide:dispensing and doesn't seem like it's explicitly called out as necessary.

**Comment by joshxg** [comment]
@katherine-sussol best reference is really to check mSupply desktop. If it's a field there then having it as a field in mobile is generally the way to go

**Comment by katherine-sussol** [comment]
@joshxg Ooh of course, thanks - found it in Desktop (which does have the field).

**Comment by katherine-sussol** [comment]
Closed with #3909

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 rc1

## Testing

- [x] Go to Dispensary -> Add Prescriber
- [x] Fill the necessary details and select Gender as "Female"
- [x] Open the Prescriber through Edit icon
- [x] Gender's value shown is "Female"
