### ISSUE TITLE
Item's quantity updated from stocktake is not sortable in Dispensary's Item list

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3771]
## Describe the bug

Item's quantity updated from stocktake is not sortable in Dispensary's Item list

### To reproduce

1. Go to Stocktake. Create Stocktake
2. Update the quantity of any Item whose quantity is 0 from initial. Save & Finalized
3. Go to Dispensary. Select Patient, Prescriber and Scroll down to look for item whose quantity is updated[greater than 0]
4. See error. That item list is still shown in the quantity line 0
![20210315_122017](https://user-images.githubusercontent.com/58979436/111113567-176e0780-858a-11eb-9230-38fd86981da8.jpg)

### Expected behaviour

Once quantity is udpated from Item list and is greater than 0. It should be shown/sorted in Item's Quantity List. Otherwise it confused that wether an item's quantity is updated and thus failed this testcase " **tems are sorted alphabetically and by quantity: e.g. all items with a non-zero quantity appear first and are sorted alphabetically, followed by all items with no quantity.**"

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V7.0.0 rc11
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #2108

**Comment by joshxg** [comment]
Oops I don't know when or why I closed this..!

The prescription items list is basically being populated in state when the app loads and doesn't seem to ever refresh. You can sync new items in and they'll not show until you reset the app, not ideal!

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0 apk

@clemens-msupply i am not sure about the changes/fixes here as i could still see the unsorted quantity column like previously.
![Screenshot_20210823-110045_mSupply-Mobile](https://user-images.githubusercontent.com/58979436/130394716-40bee101-4c38-49cb-90cf-2a16561c27ed.jpg)

**Comment by clemens-msupply** [comment]
@joshxg this is a different view isn't it? My changes were for prescribing only...

**Comment by joshxg** [comment]
@clemens-msupply Ah, yes. Seems there is the same problem elsewhere..

`VaccinePrescriptionReducer` is very similar but a different feature for dispensing vaccines, only.

**Comment by ArpitaSussol** [comment]
@clemens-msupply @joshxg this issue can be closed then?
