### ISSUE TITLE
Sync time should be configurable

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3776]
## Is your feature request related to a problem? Please describe.

The sync interval should be configurable

## Describe the solution you'd like

- UI in settings page to set the sync interval
- Not sure where to store this. Maybe a setting

## Implementation

TBD

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
This, I think, is no longer needed for our current requirements

**Comment by joshxg** [comment]
Actually this does need to be done!

Even though we plan on having the lookup be the main source of finding patients rather than them being synced everywhere, we still need to send them from tablets TO the server!

**Comment by ArpitaSussol** [comment]
@joshxg @mark-prins 
what is the use of Sync password here? 
I am able to change Sync interval and Idle logout interval by providing user's password.

**Comment by joshxg** [comment]
- `sync password` is the password for the sync site
- When prompting after `save changes`, you need to put in user name

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC4

## Testing

- [x] Sync interval can be configurable from the settings page
