### ISSUE TITLE
Sensor: Removing sensor with logs for few days is keep showing detail page

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3787]
## Describe the bug

Trying to remove Sensor which has temperature logs for few days resulting in same detail page showing until and unless back button is pressed.

### To reproduce

1. Go to Vaccine -> Click on one of the Sensor which has logs for more than a day
2. Click on remove icon.
3. See error. Sensor Detail page keep showing.

https://user-images.githubusercontent.com/58979436/111308015-45cf0e00-8682-11eb-9522-7be453a6ee10.mp4

### Expected behaviour

Once Sensor is removed, detail page should also fades/remove away right

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #3758

**Comment by katherine-sussol** [comment]
Could repro this on `develop`. Seems like when 'remove' is clicked the app is navigating back to the last screen (which in this case is `fridgeDetail`). I guess for this bug it might be better to just always go to `vaccines` (a.k.a 'Cold Chain') on removal 🤔  (with all the cleanup stuff normally done on back navigation preserved).

**Comment by katherine-sussol** [comment]
Closed with #3916

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 rc1

## Testing

- [x] Go to Vaccine -> Click on one of the Sensor which has logs for more than a day
- [x] Click on remove icon.
- [x] Sensor Detail page should not show. And redirect to Add Sensor page
