### ISSUE TITLE
Adverse drug reactons

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3795]
## Is your feature request related to a problem? Please describe.

We need a new feature- adverse drug reactions

## Describe the solution you'd like

- Using the new table described here: https://github.com/sussol/msupply/issues/8244
- Where `data` is a form created with a JSON Schema from `FormSchema`

## Implementation

- [x] Add to schema + sync
	- [ ] ISSUE: https://github.com/openmsupply/mobile/issues/3799
	- [ ] PR: #3800
- [x] Add a column+placeholder modal to `DispensingPage` with a column for a patient to create a new ADR
	- [ ] ISSUE: https://github.com/openmsupply/mobile/issues/3802
	- [ ] PR:
- [x] Fill the placeholder modal out with form details
	- [ ] ISSUE: https://github.com/openmsupply/mobile/issues/3803
	- [ ] PR:

## Describe alternatives you've considered

TBD

## Additional context

N/A

**Comment by joshxg** [comment]
@mark-prins 

Some things I can think of to determine before being able to move forward- got any others?

- What form will Tonga be using, or what can we use as a template? 
	- Would be good to have something somewhat real to work from. 
	- Would also be good to know if we are going to need to make any new widgets for the JSONForm
- Where in the UI do we want this to go?
	- Dispensary -> find the patient -> edit -> somewhere in the patient edit modal?
	- Another button on the menu page? Do we need to edit the patient at the same time as an ADR?

With these I think this should be reasssooonably quick to implement


[I have only just recently realised that navigating to dispensary and seeing a list of patients is pretty useless..! What are the chances you actually scroll through the list!]

**Comment by mark-prins** [comment]
That's what I had on my list to decide too.
I'll put together an ADR form that uses existing components only and send it around as a starting point.
As discussed, we'll start with another column in the patient table in dispensing and show the ADR form in a modal.

**Comment by katherine-sussol** [comment]
Updating doc labels - public docs available here: https://docs.msupply.foundation/en:mobile:user_guide:adverse_drug_reactions

Internal doc on configuring various JSONForm might be useful though
