### ISSUE TITLE
TESTING: Vaccine dispensary

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3801]
# Vaccine Dispensary tests

- This is a three step process. 
- There will be test cases for each step as well as test cases to ensure the final result is correct and also side effects throughout the app.

## Setup
- Your mobile store MUST have at least one vaccine item which is visible ✅ 
- Your mobile store MUST be a dispensary ✅ 
- For step TWO there is an optional EXTRA form to fill out. Step two should be tested WITHOUT this form first, then with the form afterward.
- For step THREE there is an optional EXTRA vaccine refusal:
	- You MUST have a PATIENT_EVENT with code `RV`

### Step One - patient select

_General idea: Searching for a patient using some search criteria._
- Normal search: Searches through all patients which have been created on the mobile store or have been looked up online previously.
- Online search: searches through all patients on the server
- New patient: creates a new patient

*General*
- [ ] Can type in first name
- [ ] Can type in last name
- [ ] Can type in date of birth- get an error message when an invalid date is entered. Can push the calendar icon to open a date selector. Can only select dates that are today, or before today.
- [ ] The keyboard automatically opens and the last name field is focused, ready to type in.
- [ ] There are three columns, first name, last name and date of birth (D.O.B)
- [ ] The title is Step: 1 Select a patient
- [ ] When no search details have been entered, there is text `"Enter the patient's details to start searching for them"`
- [ ] When search details were entered, but no patient is found, there is text `"No patients found that match your search criteria"`
- [ ] Pressing a row takes you to step 2
- [ ] Pressing cancel returns to the menu page
- [ ] Pressing the BACK button (top left arrow) returns you to the menu page.
- [ ] Pressing the HARDWARE BACK button (on the device, if it has one) returns you to the menu page.

*Normal search*
- [ ] Can search for patients in the local database using:[Create a few patients in Menu Page -> Dispensary -> New Patient - you should be able to find these patients]
	- [ ] first name
	- [ ] last name
	- [ ] DOB
	- [ ] Combinations of all three

*Online search*
- [ ] Pressing the search online button searches for patients on the primary server. All patients which match the search criteria are shown using:
	- [ ] first name
	- [ ] last name
	- [ ] DOB
	- [ ] Combinations of all three

*New patient*
- [ ] Pressing New Patient takes you to step two

### Step two - edit patient details

_General idea: editing a patients details if they need updating. Also filling out a survey/form if it has been set up._
- Patient details: The regular patient details on the `[name]` record. When we edit this, we should be able to see these details on the server on the patients record.
- Survey/form: Additional information about a patient- you won't be able to see this form anywhere except for if you issue another vaccine to the patient

*General*
- [ ] You cannot go to step 3 without filling out all of required details 
- [ ] Pressing cancel returns to the menu page
- [ ] Pressing the BACK button (top left arrow) returns you to the menu page.
- [ ] Pressing the HARDWARE BACK button (on the device, if it has one) returns you to the menu page.
- [ ] You can press the FIRST STEP CIRCLE to go back to search for a new patient

*Patient details*
- [ ] The inputs for the patient details are pre-filled with their existing details if this is for an existing patient
- [ ] The inputs are empty for a non-existing patient.
- [ ] First name
    - [ ] Required
    - [ ] must be at least one character with no maximum limit
    - [ ] Label: `"First name"`
    - [ ] Invalid message: `"Must not be empty"`
- [ ] Last name
    - [ ] Required
    - [ ] Must be at least one character with no maximum limit
    - [ ] Label: `"Last name"`
    - [ ] Invalid message: "Must not be empty"
- [ ] Date of Birth
    - [ ] Required
    - [ ] must be a valid date in the format `DD/MM/YYYY`
    - [ ] Label is `"Date of birth"`
    - [ ] Invalid message is: "`Must be a valid date in the format DD/MM/YYYY"`
    - [ ] Pressing the calendar button opens a date picker
    - [ ] Choosing a date in the date picker correctly sets the date
    - [ ] Dates chosen in the date picker are correctly formatted (`DDMM/YYYY`)
- [ ] Email
    - [ ] Not-required
    - [ ] Label: `"Email"`
- [ ] Phone
    - [ ] Not-required
    - [ ] Label: `"Email"`
- [ ] Address1
    - [ ] Not-required
    - [ ] Must be less than 50 characters
    - [ ] Invalid message: "Must be less than 50 characters"
- [ ] Address2
    - [ ] Not-required
    - [ ] Must be less than 50 characters
    - [ ] Invalid message: "Must be less than 50 characters"
- [ ] Country
    - [ ] Not-required
    - [ ] Must be less than 20 characters
    - [ ] Invalid message: "Must be less than 20 characters"

*Additional information*
[This form is dynamic and changeable so difficult to write tests for, sorry!]
- [ ] The form is only visible when you have one created on the server
- [ ] The form has all of the details which were created on the server
- [ ] I gave this form a good test to try and break it
- [ ] The form is PREPOPULATED with the ANSWERS from the LAST survey

### Step three - vaccine select

_General idea: Select a vaccine and a batch. The patient will be issued 1 dose._

- [ ] The list of vaccines shows all vaccines and no other items
- [ ] The list of vaccines shows the correct quantity
- [ ] The list of vaccines automatically selects the LAST DISPENSED vaccine, if there has been one
- [ ] The list of vaccine BATCHES shows the correct batches for the item selected
- [ ] The list of vaccine BATCHES shows the correct quantities
- [ ] The list of vaccine BATCHES automatically selects the batch which has been opened (there is a non-integer quantity) and with the most recent expiry date
- [ ] Pressing REFUSED vaccine de-selects any vaccines selected
- [ ] You CANNOT create a prescription without either refusing or selecting a batch
- [ ] You can select ANY vaccinator (which are created on the server)
- [ ] The patient name is the patient you selected.
- [ ] Clicking CONFIRM will finish and return you back to the menu page
- [ ] Clicking CANCEL will cancel and return you back to the menu page
- [ ] Clicking OK & Next will finish and start a new vaccination process

### Result

- [ ] After completing a vaccination, a PRESCRIPTION is created - if NOT refused
- [ ] The PRESCRIPTION has ONE LINE, which has ONE DOSE (the quantity, for example, if the vaccine has 10 doses, will be `.1`) 
- [ ] The PRESCRIPTION is for the patient selected
- [ ] The PRESCRIPTION has the correct `[medicine_administrator]` (vaccinator)
- [ ] If the vaccine was REFUSED, a `[name_note]` is created for the patient.
- [ ] If you CREATED A NEW PATIENT - the PATIENT is created with the correct details
- [ ] If you SELECTED A PATIENT ONLINE - the PATIENT is created in the MOBILE store with the correct details.

### SIDE EFFECTS
- [ ] When an item has a FRACTION quantity left (i.e. 10.1)- the quantity shows correctly in a CUSTOMER INVOICE
- [ ] When an item has a FRACTION quantity left (i.e. 10.1)- the quantity shows correctly in a STOCK TAKE
- [ ] When an item has a FRACTION quantity left (i.e. 10.1)- the quantity shows correctly in a CURRENT STOCK PAGE

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0.RC2


*General*
- [x] Can type in first name
- [x] Can type in last name
- [x] Can type in date of birth- get an error message when an invalid date is entered. Can push the calendar icon to open a date selector. Can only select dates that are today, or before today.
- [x] The keyboard automatically opens and the last name field is focused, ready to type in.
- [x] There are three columns, first name, last name and date of birth (D.O.B)
- [x] The title is Step: 1 Select a patient
- [x] When no search details have been entered, there is text `"Enter the patient's details to start searching for them"`
- [x] When search details were entered, but no patient is found, there is text `"No patients found that match your search criteria"`
- [x] Pressing a row takes you to step 2
- [x] Pressing cancel returns to the menu page
- [x] Pressing the BACK button (top left arrow) returns you to the menu page.
- [x] Pressing the HARDWARE BACK button (on the device, if it has one) returns you to the menu page.

*Normal search*
- [x] Can search for patients in the local database using:[Create a few patients in Menu Page -> Dispensary -> New Patient - you should be able to find these patients]
	- [x] first name
	- [x] last name
	- [x] DOB
	- [x] Combinations of all three

*Online search*
- [x] Pressing the search online button searches for patients on the primary server. All patients which match the search criteria are shown using:
	- [x] first name
	- [x] last name
	- [x] DOB
	- [x] Combinations of all three

*New patient*
- [x] Pressing New Patient takes you to step two

### Step two - edit patient details

_General idea: editing a patients details if they need updating. Also filling out a survey/form if it has been set up._
- Patient details: The regular patient details on the `[name]` record. When we edit this, we should be able to see these details on the server on the patients record.
- Survey/form: Additional information about a patient- you won't be able to see this form anywhere except for if you issue another vaccine to the patient

*General*
- [x] You cannot go to step 3 without filling out all of required details 
- [x] Pressing cancel returns to the menu page
- [x] Pressing the BACK button (top left arrow) returns you to the menu page.
- [x] Pressing the HARDWARE BACK button (on the device, if it has one) returns you to the menu page.
- [x] You can press the FIRST STEP CIRCLE to go back to search for a new patient

*Patient details*
- [x] The inputs for the patient details are pre-filled with their existing details if this is for an existing patient
- [x] The inputs are empty for a non-existing patient.
- [x] First name
    - [x] Required
    - [x] must be at least one character with no maximum limit
    - [ ] Label: `"First name"`
    - [ ] Invalid message: `"Must not be empty"`
- [ ] Last name
    - [ ] Required
    - [ ] Must be at least one character with no maximum limit
    - [ ] Label: `"Last name"`
    - [ ] Invalid message: "Must not be empty"
- [ ] Date of Birth
    - [ ] Required
    - [ ] must be a valid date in the format `DD/MM/YYYY`
    - [ ] Label is `"Date of birth"`
    - [ ] Invalid message is: "`Must be a valid date in the format DD/MM/YYYY"`
    - [ ] Pressing the calendar button opens a date picker
    - [ ] Choosing a date in the date picker correctly sets the date
    - [ ] Dates chosen in the date picker are correctly formatted (`DDMM/YYYY`)
- [ ] Email
    - [ ] Not-required
    - [ ] Label: `"Email"`
- [ ] Phone
    - [ ] Not-required
    - [ ] Label: `"Email"`
- [ ] Address1
    - [ ] Not-required
    - [ ] Must be less than 50 characters
    - [ ] Invalid message: "Must be less than 50 characters"
- [ ] Address2
    - [ ] Not-required
    - [ ] Must be less than 50 characters
    - [ ] Invalid message: "Must be less than 50 characters"
- [ ] Country
    - [ ] Not-required
    - [ ] Must be less than 20 characters
    - [ ] Invalid message: "Must be less than 20 characters"

*Additional information*
[This form is dynamic and changeable so difficult to write tests for, sorry!]
- [ ] The form is only visible when you have one created on the server
- [ ] The form has all of the details which were created on the server
- [ ] I gave this form a good test to try and break it
- [ ] The form is PREPOPULATED with the ANSWERS from the LAST survey #3809

### Step three - vaccine select

_General idea: Select a vaccine and a batch. The patient will be issued 1 dose._

- [ ] The list of vaccines shows all vaccines and no other items
- [ ] The list of vaccines shows the correct quantity
- [ ] The list of vaccines automatically selects the LAST DISPENSED vaccine, if there has been one
- [ ] The list of vaccine BATCHES shows the correct batches for the item selected
- [ ] The list of vaccine BATCHES shows the correct quantities
- [ ] The list of vaccine BATCHES automatically selects the batch which has been opened (there is a non-integer quantity) and with the most recent expiry date
- [ ] Pressing REFUSED vaccine de-selects any vaccines selected
- [ ] You CANNOT create a prescription without either refusing or selecting a batch #3807 
- [ ] You can select ANY vaccinator (which are created on the server) 
@joshxg @mark-prins 
**HOW TO CREATE/ADD VACCINATOR? can only see table details from record browser**
- [ ] The patient name is the patient you selected.
- [ ] Clicking CONFIRM will finish and return you back to the menu page
- [ ] Clicking CANCEL will cancel and return you back to the menu page
- [ ] Clicking OK & Next will finish and start a new vaccination process

### Result

- [ ] After completing a vaccination, a PRESCRIPTION is created - if NOT refused
- [ ] The PRESCRIPTION has ONE LINE, which has ONE DOSE (the quantity, for example, if the vaccine has 10 doses, will be `.1`) 
- [ ] The PRESCRIPTION is for the patient selected
- [ ] The PRESCRIPTION has the correct `[medicine_administrator]` (vaccinator)
- [ ] If the vaccine was REFUSED, a `[name_note]` is created for the patient.
- [ ] If you CREATED A NEW PATIENT - the PATIENT is created with the correct details
- [ ] If you SELECTED A PATIENT ONLINE - the PATIENT is created in the MOBILE store with the correct details.

### SIDE EFFECTS
- [ ] When an item has a FRACTION quantity left (i.e. 10.1)- the quantity shows correctly in a CUSTOMER INVOICE
- [ ] When an item has a FRACTION quantity left (i.e. 10.1)- the quantity shows correctly in a STOCK TAKE
- [ ] When an item has a FRACTION quantity left (i.e. 10.1)- the quantity shows correctly in a CURRENT STOCK PAGE

**Comment by mark-prins** [comment]
> HOW TO CREATE/ADD VACCINATOR?

@ArpitaSussol : good point! there isn't a way to to this in mSupply yet. 
I was using this in foot runner:
```
C_COLLECTION($cMedicineAdministrators)
C_OBJECT($obNewAdmin; $obAdmin)

$cMedicineAdministrators:=New collection()
$cMedicineAdministrators.push(New object("code"; "V001"; "first_name"; "Test-vaccinator"; "last_name"; "One"))
$cMedicineAdministrators.push(New object("code"; "V002"; "first_name"; "Vaccinator-test"; "last_name"; "Two"))

For each ($obAdmin; $cMedicineAdministrators)
	$obNewAdmin:=ds.medicine_administrator.new()
	$obNewAdmin.ID:=UUID_generate
	$obNewAdmin.first_name:=$obAdmin.first_name
	$obNewAdmin.last_name:=$obAdmin.last_name
	$obNewAdmin.code:=$obAdmin.code
	$obNewAdmin.save()
End for each 
```

**Comment by ArpitaSussol** [comment]
> > HOW TO CREATE/ADD VACCINATOR?
> 
> @ArpitaSussol : good point! there isn't a way to to this in mSupply yet.
> I was using this in foot runner:
> 
> ```
> C_COLLECTION($cMedicineAdministrators)
> C_OBJECT($obNewAdmin; $obAdmin)
> 
> $cMedicineAdministrators:=New collection()
> $cMedicineAdministrators.push(New object("code"; "V001"; "first_name"; "Test-vaccinator"; "last_name"; "One"))
> $cMedicineAdministrators.push(New object("code"; "V002"; "first_name"; "Vaccinator-test"; "last_name"; "Two"))
> 
> For each ($obAdmin; $cMedicineAdministrators)
> 	$obNewAdmin:=ds.medicine_administrator.new()
> 	$obNewAdmin.ID:=UUID_generate
> 	$obNewAdmin.first_name:=$obAdmin.first_name
> 	$obNewAdmin.last_name:=$obAdmin.last_name
> 	$obNewAdmin.code:=$obAdmin.code
> 	$obNewAdmin.save()
> End for each 
> ```

thank you @mark-prins :). 

I am curious whether Vaccinator's add/edit for Tonga for Current release is going to be added Manually then?

**Comment by mark-prins** [comment]
Yes - we won't have administration for vaccinators ready in time for Tonga
