### ISSUE TITLE
Remove doses field

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3819]
## The suggestion

We have changed the way we calculate open vial wastage to only use inventory adjustments which have an `openVialWastage` reason.

This was the primary reason for having a `doses` field. 

**Why?**

Now, we only allow `doses` to equal `quantity*number of doses per vial`, so we don't need to store the number of doses.

## Describe alternatives you've considered

Leave it

## Additional context

- By removing this field, it is much better to calculate things. For example, if you change an item to be a vaccine and to have doses, then we need to figure out what to do with historic stuff. For example, do item batches now have a number of doses? So should we go and update all the item batches? Transaction batches? etc

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0RC4

## Testing

- [x] Issuing stock by doses in customer invoices correct decreases the item batch quantity
- [x] stock changes in stocktake correctly decreases/increases the item batch quantity
- [x] Issuing stock in vaccine dispensing correctly decreases the item batch quantity
