### ISSUE TITLE
Save name notes from remote patients

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3824]
## Is your feature request related to a problem? Please describe.

name notes from remote patients aren't saved. They need to be

## Describe the solution you'd like

Not sure exactly, but there is an array of name notes sent from the server and we need to use them

## Implementation

TBD

## Describe alternatives you've considered

TBD

## Additional context

- I imagine this is not going to be great

**Comment by ArpitaSussol** [comment]
@joshxg running below footrunner code creates the name_note for that store in record browser but how its related and linked with Search for a patient in vaccination/Normal Dispensing?

## Testing

- [ ] Search for a patient in vaccination dispensing which is NOT from the mobile store, but does have a previous clinical data - the clinical data is prepopulated on step 2
- [ ] Search for a patient in NORMAL dispensing lookup which is NOT from the mobile store, but does have a previous clinical data - the clinical data is prepopulated on step 2 of vaccination

### Related areas to think about

This is Hard to test because you need to have a patient which has clinical data form that is not from the mobile store.

You can use the following code to create one with footrunner:

```
$nn:=ds.name_note.new()
$nn.ID:=UUID_generate
$nn.data:=data
$nn.name_ID:="SOME PATIENT ID YOU CAN FIND IN RECORD BROWSER"
$nn.patient_event_ID:="295C2B7E53264C1B98ADD57B720F3AF6"
$nn.save()
```

**Comment by joshxg** [comment]
That was not very helpful for you... oops!

If you use this code, then you can replace "HERE" with the code of the patient to link the name note 

```
$patientCode:="HERE"

$data:=JSON Parse("{\n  \"respondentContactData\": {\n    \"firstName\": \"Josh\",\n    \"lastName\": \"Griffin\"\n  },\n  \"patientClinicalData\": {\n    \"previousSeriousAllergicReactions\": false,\n    \"previousAdverseEventsFollowingImmunisation\": false,\n    \"currentlyPregnant\": false,\n "+"   \"currentlyLactating\": false\n  },\n  \"Covid 19 Status\": {\n    \"everTestedPositiveForCOVID19\": false\n  },\n  \"Covid 19 Vaccination Data\": {\n    \"Covid-19 Vaccine Type\": \"Astra-zeneca\",\n    \"Any AEFI experienced\": false\n  },\n  \"firstName\": \"Chuck\",\n  \"l"+"astName\": \"Norris\",\n  \"age\": 75,\n  \"bio\": \"Roundhouse kicking asses since 1940\",\n  \"password\": \"noneed\"\n}")



$patient:=ds.name.query("code == :1"; "@"+$patientCode+"@")[0]

$pe:=ds.patient_event.new()
$pe.ID:=UUID_generate
$pe.code:="PCD"
$pe.save()

$nn:=ds.name_note.new()
$nn.ID:=UUID_generate
$nn.data:=$data
$nn.name_ID:=$patient.ID
$nn.patient_event_ID:=$pe.ID
$nn.save()

```

**Comment by ArpitaSussol** [comment]
> $patientCode:="HERE"
> 
> $data:=JSON Parse("{\n  \"respondentContactData\": {\n    \"firstName\": \"Josh\",\n    \"lastName\": \"Griffin\"\n  },\n  \"patientClinicalData\": {\n    \"previousSeriousAllergicReactions\": false,\n    \"previousAdverseEventsFollowingImmunisation\": false,\n    \"currentlyPregnant\": false,\n "+"   \"currentlyLactating\": false\n  },\n  \"Covid 19 Status\": {\n    \"everTestedPositiveForCOVID19\": false\n  },\n  \"Covid 19 Vaccination Data\": {\n    \"Covid-19 Vaccine Type\": \"Astra-zeneca\",\n    \"Any AEFI experienced\": false\n  },\n  \"firstName\": \"Chuck\",\n  \"l"+"astName\": \"Norris\",\n  \"age\": 75,\n  \"bio\": \"Roundhouse kicking asses since 1940\",\n  \"password\": \"noneed\"\n}")
> 
> 
> 
> $patient:=ds.name.query("code == :1"; "@"+$patientCode+"@")[0]
> 
> $pe:=ds.patient_event.new()
> $pe.ID:=UUID_generate
> $pe.code:="PCD"
> $pe.save()
> 
> $nn:=ds.name_note.new()
> $nn.ID:=UUID_generate
> $nn.data:=$data
> $nn.name_ID:=$patient.ID
> $nn.patient_event_ID:=$pe.ID
> $nn.save()

@joshxg i got this runtime error while running above footrunner code. Can you please check what is missing?
![Screen Shot 2021-03-25 at 10 24 07 AM](https://user-images.githubusercontent.com/58979436/112420158-d7124480-8d54-11eb-9071-3a80adc81f61.png)

**Comment by joshxg** [comment]
@ArpitaSussol 

You have to replace this line: 

```
$patientCode:="HERE"
```

With the patient code of a patient you want to link that to.. so for example if the code is ABC1 ..

```
$patientCode:="ABC1"
```

Hopefully that works..

**Comment by ArpitaSussol** [comment]
> @ArpitaSussol
> 
> You have to replace this line:
> 
> ```
> $patientCode:="HERE"
> ```
> 
> With the patient code of a patient you want to link that to.. so for example if the code is ABC1 ..
> 
> ```
> $patientCode:="ABC1"
> ```
> 
> Hopefully that works..

oops sorry i confused with Patient ID :( my bad

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC5

## Testing

- [x] Search for a patient in vaccination dispensing which is NOT from the mobile store, but does have a previous clinical data - the clinical data is pre populated on step 2
- [x]  created name_note for it
- [x] Search for a patient in NORMAL dispensing lookup which is NOT from the mobile store, but does have a previous clinical data - the clinical data is pre populated on step 2 of vaccination
- [x] created name_note for it
- [x] Search for a patient in vaccination dispensing which is from the mobile store, but does have a previous clinical data - the clinical data is pre populated on step 2
- [x]  created name_note for it
- [x] Search for a patient in NORMAL dispensing lookup which is from the mobile store, but does have a previous clinical data - the clinical data is pre populated on step 2 of vaccination
- [x] created name_note for it
