### ISSUE TITLE
Vaccination: Vaccinator is not listed/showing in Prescription

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3828]
## Describe the bug

After adding valid Vaccinator from list and saving it, not showing in Dispensing -> Prescription list both in mobile and in Desktop

### To reproduce

1. Go to Vaccination -> Select A Patient -> Select a vaccinator -> Add Vaccine -> Confirm/Ok & Next
2. Go to Dispensing
3. Search above mentioned Patient -> Click on History icon
4. See error. No Vaccinator is  shown in Prescriber column

https://user-images.githubusercontent.com/58979436/111941293-d7ae9f00-8af8-11eb-98a7-edf1fdcadaf2.mp4

### Expected behaviour

Either Vaccinator should be shown in Prescriber column or there should be separate column for it.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.0.0 RC2
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #3801 for Testcase
- **The PRESCRIPTION has the correct [medicine_administrator]**

**Comment by joshxg** [comment]
@ArpitaSussol 

You're right that the vaccinator/medicine administrator is different from the prescriber. I don't think we have the need to show the vaccinator at this point in time. But it did have me check the medicine_admin and it was not being saved correctly, so I will do a PR for that!!

**Comment by ArpitaSussol** [comment]
@joshxg in which record to check medicine admin has been saved after creating vaccine prescription?

- [ ] With only 1 vaccinator created, create a vaccine prescription and sync, check in record browser that the medicine admin has been saved

**Comment by joshxg** [comment]
Sorry @ArpitaSussol ! On the `[trans_line]`

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC4

- [x] With only 1 vaccinator created, create a vaccine prescription and sync, check in record browser that the medicine admin has been saved
