### ISSUE TITLE
Logout timer should be configurable

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3837]
## Is your feature request related to a problem? Please describe.

There was an inactivity timer added for ivory coast which logs the user out if the app comes back into the foreground after having been in the background for 3 minutes.

## Describe the solution you'd like

- Make this timer configurable.
- Make this timer toggleable??

## Implementation

TBD

## Describe alternatives you've considered

TBD

## Additional context

TBD

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC4

## Testing

- [x] Can configure an idle logout period in the settings page and it works!
