### ISSUE TITLE
DOB's when looking up are incorrect

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3838]
## Describe the bug

Report coming from a user: "D.O.B. is incorrect : A patient was created on one tablet, and looked up on another - the D.O.B. was roughly a day out"

### To reproduce

Not sure havent been able to repro

### Expected behaviour

DOB's should be correct

### Proposed Solution

TBd

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by mark-prins** [comment]
Resolved by setting the regional settings for all users on the server.
