### ISSUE TITLE
Rename PACKS -> VIALS in vaccine dispensing

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3841]
## Is your feature request related to a problem? Please describe.

Rename PACKS -> VIALS in vaccine dispensing

## Describe the solution you'd like

Rename PACKS -> VIALS in vaccine dispensing

## Implementation

change the string

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
this one makes sense

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC4

## Testing

- [x] The name of the column for the number of vials is "VIALS" in vaccine dispensing, last step
