### ISSUE TITLE
Cannot create new patients from Dispensary module

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#3847]
## Describe the bug
Cannot create new patients from Dispensary module

### To reproduce
1. Go to 'Dispensary'
2. Click on `Create New patient`
3. Add in the details and click `Save`
4. See error.
5. Creating patient from Vaccination (New patient, then Issue/Refuse vaccine and Confirm) works fine though.

### Screenshots
![Screenshot_2021-03-24-14-20-14-965](https://user-images.githubusercontent.com/59193490/112280556-3ae13280-8cad-11eb-8d57-cf8e453c4faf.jpeg)

### Expected behaviour
Should allow to create new patient nicely in Dispensary module as well

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: v8.0.0.RC4
- Tablet model: Lenovo
- OS version: 8

### Additional context
Found while testing #3831

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC5

## Testing

- [x] Can create new patients
- [x] When looking up a patient from the lookup API, a name store join is created on the server
