### ISSUE TITLE
Address of patient is still not consistent

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#3855]
## Describe the bug
Address of patient created in the mobile site is not consistent/same when viewing it from cloud server or any other mobile store through Lookup

### To reproduce

1. From `Dispensary`, Create a new patient, add some addresses and Save
![Screenshot_2021-03-25-12-58-51-202](https://user-images.githubusercontent.com/59193490/112433789-d84e6c00-8d6a-11eb-99e8-7e36b69aacd8.jpeg)

2. Sync
3. On desktop cloud, login to that mobile store and search for that patient
4. See error : the address there is different from the one actually entered
![Screen Shot 2021-03-25 at 12 51 44 PM](https://user-images.githubusercontent.com/59193490/112433540-83125a80-8d6a-11eb-8536-6ef0481f9267.png)
5. Also, from anothe mobile site, search for that same patient through Lookup and see the same error

### Expected behaviour
should be same everywhere

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: v8.0.0.RC5
- Tablet model: Lenovo
- OS version: 8

### Additional context
Found while testing #3831

**Comment by joshxg** [comment]
@nishaSussol I've been trying to repro this but I can't 😢 

Maybe you can send me your data file on telegram or something just so I can make sure my environment is similar to yours so I can rule that out?

**Comment by katherine-sussol** [comment]
I thought I'd also try to repro (just in case I got lucky!) but also couldn't 😿 , also tried editing and address seems to be updating in Desktop for me

**Comment by joshxg** [comment]
Think we can close it for now unless Nisha Really feels strongly :)
