### ISSUE TITLE
Patient Extra Information: Patient ID on toggle is become non- required fields

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3857]
## Describe the bug
Patient ID is required field to be filled up while saving Patient. Entering Patient ID for first time and all the required fields enables the Save button. Removing the Patient ID still shows Save button to be enabled and also saved the Patient record.

Secondly, the yes/no question regarding "Ever Tested positive for COVID-19, for either option date of diagnosis is enterable and also saved in database. 
### To reproduce

1. Go to Vaccination -> New Patient -> Add required fields
2. Save button is enabled now
3. Remove the Patient ID text field value
4. See error. Save option still keep showing and also saved the Patient details
5. Select "No" for "Ever tested positive for COVID-19"
6. See Error. Date of Diagnosis can be filled and value is saved in Database.

https://user-images.githubusercontent.com/58979436/112447675-b14b6680-8d79-11eb-9e17-8f1f60f27d3f.mp4

![Screen Shot 2021-03-25 at 2 42 34 PM](https://user-images.githubusercontent.com/58979436/112447836-db9d2400-8d79-11eb-8886-ebd4bb2720bb.png)

### Expected behaviour

Save button should be disabled until and unless all the required fields are filled up.
Even though, Date of Diagnosis can be filled for NO answer but it should not be saved in Database. otherwise it might create confusion

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.0.0 RC5
- Tablet model: Samsung
- OS version: 8.1

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC6

## Testing

- [x] Patient ID is always required

@joshxg @mark-prins If i enter space only in Patient ID then also its allowed me to save. Not an issue but just curious :) 
I think its fine for now. but can i make an issue for backlog ?

**Comment by joshxg** [comment]
Oh of course. Interesting! Good testing 😀
