### ISSUE TITLE
Trouble setting doses in a stocktake batch 

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3865]
## Describe the bug

When setting a value of `1` dose in a batch of a vaccine item which has a value for `doses` of `6` the entered value changes incorrectly. When entering `1` the value changes to `1.02`.. entering `20` changes to `19.98`

https://user-images.githubusercontent.com/9192912/112771881-794e6700-908a-11eb-9768-21077a1034a3.mov

Another issue is that when entering a value for `dose` in a batch, this value isn't shown in the stocktake; though it is saved correctly. The following sequence is for an item with a `doses` value of `10`:

![stocktake](https://user-images.githubusercontent.com/9192912/112771972-cf230f00-908a-11eb-9dc0-b72aa680c71a.png)

![stocktake2](https://user-images.githubusercontent.com/9192912/112771976-d1856900-908a-11eb-8866-6949a44ff9c6.png)

![stocktake3](https://user-images.githubusercontent.com/9192912/112771979-d3e7c300-908a-11eb-8f0b-ecfc5a755088.png)

### To reproduce

1. Create a stocktake and add a vaccine item
2. Add a batch and set the doses value
3. Urgh.

### Expected behaviour

The value entered for `doses` should be the value shown

### Proposed Solution

🤷‍♂️

**Comment by joshxg** [comment]
hmm

When setting doses, we are using:

```
const newCountedTotalQuantity = Number(newValue / this.dosesPerVial).toFixed(2);
```

then, doses is:

```
return this.countedTotalQuantity * this.dosesPerVial;
```

So, total quantity is 0.33 and doses is 1.98

Should I.. round up? remove rounding from the total quantity? Not sure if removing total quantity rounding would fully work...?

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0 RC7

## Testing

- [x] Customer invoices doses column when entered, also adjusts the total quantity column to be doses*doses per vial
- [x] stocktakes doses column when entered, also adjusts the total quantity column to be doses*doses per vial
- [x] cannot see more than two decimal places for a quantity anywhere in the ui...
