### ISSUE TITLE
ADR Form: time field shows inconsistent validation warning

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3869]
## Describe the bug

In ADR Form, time field shows wrong validation warning

### To reproduce

1. Go to Dispense -> Patients
2. Click on ADR action of any Patients
3. Scroll down to Date and time field. select date and time
4. See error. Whatever value you select from time dropdown field, it keeps showing validation warning message and stopped the form to be saved
![Screenshot_2021-03-29-14-33-27-302](https://user-images.githubusercontent.com/58979436/112812202-8c6a3280-909c-11eb-95e5-19c19fcd6941.jpeg)
![Screenshot_2021-03-29-14-33-35-835](https://user-images.githubusercontent.com/58979436/112812213-8ffdb980-909c-11eb-8c58-ff35cfa684bf.jpeg)

### Expected behaviour

Should not show inconsistent warning message

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.0.0 RC6
- Tablet model: Lenovo
- OS version: 8.1

### Additional context

arises while testing #3803

**Comment by joshxg** [comment]
This is fixed on mSupply end
