### ISSUE TITLE
Vaccination: Patient online[server] search for existing patient is showing inconsistency in Patient Detail form

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3884]
## Describe the bug

While searching Patient from online/server, and selecting any one of them results in blank First name, last name and DOB is set to current date.

### To reproduce

1. Go to Vaccination
2. Enter any name in lastname or firstname and click on Search Online button
3. From list select any patient whose dob is not equal to current date
4. See error. First name and Last Name is blank and also DOB is set to current date.
NOTE: above mentioned problem does not persist if creating new patient in one of the mobile store and syncing to other mobile site. **Above problem is shown for existing patient only**

https://user-images.githubusercontent.com/58979436/112954673-57beaf80-915e-11eb-9ec2-88cd397613f8.mp4

### Expected behaviour

Firstname, Lastname and DOB should be filled correctly in Patient Detail form

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.0.0 RC7
- Tablet model: Lenovo/Samsung
- OS version: 8.1

**Comment by joshxg** [comment]
Have given this a good try and can't seem to recreate it at this point. @mark-prins are you able to give it a spin?

**Comment by mark-prins** [comment]
I've tried with a number of configurations.. and can't recreate. Am using the develop branch and a local mSupply server. Will try with RC7 against Tonga server once I've upgraded it.

**Comment by joshxg** [comment]
Arpita- we will have a new server build and new mobile version for you soon. Maybe we can try on fresh data files to recreate this one after that? If you can recreate it, we will reopen

**Comment by ArpitaSussol** [comment]
Closing it for now.
