### ISSUE TITLE
Couple of polishes for vaccine prescriptons

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3894]
## Is your feature request related to a problem? Please describe.

Just a few bits of polish for vaccine prescriptions
- Disable 'search online' while searching
- Navigating to `PatientSelect` seems to take a bit too long
- Make the ok and ok and next buttons with one press

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0

## Testing

- [x] navigating to patient select feels a bit faster

- [x] Search online gets disabled

- [x] ok and next/ok buttons are one press now- could cause funny behaviour if spammed

- [x] Search online gets disabled while it is searching online
