### ISSUE TITLE
menu page doesn't refresh after initializing

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3896]
## Describe the bug

The module reducer doesn't recalc after initializing, so if you init with modules installed, they don't show straight away

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in V8.0.0

## Testing

- [x] Init a store with cold chain, vaccines, dispensing or dashboard enabled. See the modules are enabled when you first init.
