### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by edmofro** [openmsupply/mobile#39]
Expected:
Any significant action should be added to a log which is synced to the central store

Actual:
No logging

**Comment by andreievg** [comment]
removing from dev project for now

**Comment by katherine-sussol** [comment]
Some logging now as per https://github.com/openmsupply/mobile/issues/4189 (but no syncing of these). Keeping this issue open in case there are further enhancement requests/suggestions (regardless of the unlikeliness of them being done 😼 ).

**Comment by bijaySussol** [comment]
We have a enough logging on Central server, so probably this issue could really be outdated.
Closing this for now.
