### ISSUE TITLE
Nationality/Ethnicity should be saved from patient lookups

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3911]
## Is your feature request related to a problem? Please describe.

The patient lookup isn't mapping nationality and ethnicities

## Describe the solution you'd like

Add the fields

## Implementation

TBD

## Describe alternatives you've considered

TBD

## Additional context

TBD

**Comment by ArpitaSussol** [comment]
Tested in V8.0.1

## Testing

- [x] Lookup a patient with an ethnicity and/or nationality - it should show on step 2 of vaccine dispensing
