### ISSUE TITLE
tonga vaccines rollout - item "VAX" should not be visible on dispensing tablets

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/mobile#3913]
## Describe the bug

to avoid confusion, there should be ideally only one item for covid 19 vaccines. However, we can currently see 2 when running stocktake for instance. Item "VAX" should not be visible. 

### To reproduce

Store Team1_Dispensing, Team2_Dispensing, Team3_Dispensing, Team4_Dispensing, Team5_Dispensing

### Expected behaviour

user can only select only 1 item (code C19VAZ)

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.
![photo_2021-04-12 11 44 43](https://user-images.githubusercontent.com/74992958/114325491-7d977b80-9b84-11eb-9800-4f6eefaf6fa6.jpeg)

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
the items were still set as visible on the server
