### ISSUE TITLE
extra information form for vaccines 

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/mobile#3914]
## Describe the bug

you cannot select the answer for the yes/no questions. 
![photo_2021-04-12 11 48 38](https://user-images.githubusercontent.com/74992958/114325596-08787600-9b85-11eb-8d10-354aebab1f34.jpeg)

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
believe this is fixed now
