### ISSUE TITLE
Handle [location]hold

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3919]
## Describe the bug

Mobile doesn't handle locations which are on hold which is the same (afaik) as an `isActive` field

### To reproduce

1. have a `location` on `hold` (can only do this on desktop)
2. Click on a supplier invoice and try to assign an item

### Expected behaviour

- The locations on hold should not show

### Proposed Solution

N/A
### Version and device info

- App version: 8.0.0
- Tablet model:
- OS version:

### Additional context

N/A

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 

**#Testing**

- [x] have a location on hold (can only do this on desktop)
- [x] Click on a supplier invoice and try to assign an item
- [x]  on hold location is not showing in list
