### ISSUE TITLE
8.1 dependency upgrades

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3922]
## The suggestion

Been awhile since we did a round of dependency upgrades. We have some time now, with no clear deadline for 8.1 to get these done.

**Why?**
So we don't get to far behind.

## Describe alternatives you've considered

Doing nothing

## Additional context

N/A

**Comment by katherine-sussol** [comment]
@joshxg Can pick this one up and give it a go (and hopefully don't break everything) - is there any general rule of thumb on what to upgrade?
Did a yarn audit and got `Severity: 132 Low | 1 Moderate | 25 High` - good idea to update anything showing up here?
Also looks like there's a newer react-native version released. Worth making separate issues for each dependency that needs changes?

**Comment by joshxg** [comment]
@katherine-sussol A lot of the deps that come through with `audit` are peer deps from the packages we use.

This is a bit annoying. I think this was the last PR (maybe) https://github.com/openmsupply/mobile/pull/3264. I personally go through the `package.json` and upgrade each one individually checking release notes for potential breakages then commit each upgrade separately.. breaking it up into multiple PRs if there are a lot of upgrades needed (I think there will be).

Not sure if one PR per dep is needed, but could group them up say.. "linter/formatting" packages in a single PR kind of thing..

Anything that is to do with native code can be quite annoying so need to be cautious with those. Latest RN doesn't have too many new stuff so shouldn't break anything with a quick glance, and has also been out for a while and had a few patches so I think it is stable to upgrade to.

react-navigation I *think* is the main one where we are behind and also can cause a lot of issues to upgrade.

Hope that helps. I think it's important we get this done for 8.1. TLDR advice is: start with the 'easy' upgrades (where the code is pure javascript and only minor/patch version bumps) and move into the bigger ones where the package has some native code and/or has a major version bump (Where we need to evaluate if there are breaking changes that require us to change some code)

**Comment by katherine-sussol** [comment]
Just realised last PR (#3970) broke regular dispensing ooops, don't know which dep broke it specifically yet, will try investigate:
 ![image](https://user-images.githubusercontent.com/65875762/115499673-edfc7600-a2c3-11eb-81ea-ec529eecd4dd.png)

**Comment by joshxg** [comment]
@katherine-sussol looks like realm to me

**Comment by katherine-sussol** [comment]
Done for now (seems there are a few 🐛  that crawled out from this Issue  - but being tracked as separate issues).
