### ISSUE TITLE
requisition created date is non-nullable on mobile but not desktop

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3925]
## Describe the bug

- `[requisition]date_order_received` can be null on desktop.
- It cannot be on mobile
- this causes sync to halt during initialization

### To reproduce

1. Go to desktop and make a mobile stores requisition have `date_order_received = 00/00/00`
3. try init

### Expected behaviour

Should be able to init

### Proposed Solution

I think maybe the `parseDate` func should return `undefined` instead of `null` when receiving a date `00/00/00`

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by katherine-sussol** [comment]
@joshxg I haven't been able to find a way to set `date_order_received` via the Desktop UI (it seems to set to current date if I enter 00/00/00 in most places I've tried...it thinks it knows better than me 😠 ) - does this need manual record editing or is there a use case that I'm missing that _would_ set to 00/00/00 easily?

**Comment by joshxg** [comment]
Hmm..

I think it happens with a requisition which is a `sg` status, which we can't actually create on mobile, heh.

So, I think you have to go through the tedious process of having a store which is NOT a mobile store, and create an `sg` status requisition THEN convert the store to a mobile site and sync it.

Basically I would just manually edit a requisition on desktop to test with..

**Comment by katherine-sussol** [comment]
Closed with #4056
