### ISSUE TITLE
show patient history in vaccine dispensing

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3938]
## Is your feature request related to a problem? Please describe.

- Want to show the patients history in vaccine dispensing

## Describe the solution you'd like

Not sure, will figure it out!

## Implementation

TBD

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by ArpitaSussol** [comment]
Tested in V8.0.2

## Testing

- [x] Can open a modal with the patients vaccine history from the history button on step 3 of vaccine dispensing
