### ISSUE TITLE
patients with more than 2 doses 

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/mobile#3948]
## Describe the bug

for multiple patients, a second doses with a quantity close to 0 is recorded in their history (see below screenshot). 

![Screen Shot 2021-04-16 at 12 36 44 PM](https://user-images.githubusercontent.com/74992958/114961287-d9cc0980-9ebc-11eb-9ba3-b79a3086b632.png)

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in V8.0.2

## Testing

- [x] Have 1 vaccine with 12 doses/vial. Give yourself some quantity. Then, dispense all. On the very LAST dose when dispensing through vaccine dispensing, the patient is only given 1 LINE in the transaction, and the ITEM BATCH now has ZERO quantity.
