### ISSUE TITLE
Can create a vaccine prescription with no lines

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3955]
## Describe the bug

Can create a vaccine prescription with no lines

### To reproduce

1. Go to a vaccine prescription, go through to step 3
2. go back to step1, then go back to step 3
3. click OK

### Expected behaviour

No prescription unless a batch is selected

### Proposed Solution

N/A

### Version and device info

- App version: v8.0.0+
- Tablet model:
- OS version:

### Additional context

N/A

**Comment by ArpitaSussol** [comment]
Tested in V8.0.2

## Testing

- [x] Cannot create a prescription with no lines
