### ISSUE TITLE
Breach temperature thresholds should realign on .5

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3966]
## Describe the bug

When changing the breach temperature tresholds, if one of the thresholds gets close to the other, it is reduced by .1. Then, the threshold can never again align on .5

### To reproduce

1. Go to set up a new sensor
2. Click on the hot threshold and make it 8 degrees
3. Go to the cold threshold and bring it up close to 8 degrees - it will land on 7.9.
4. Then, reduce the cold threshold. It was go to 7.4, 6.9 6.4 etc, never realigning on .5

### Expected behaviour

Should realign on .5

### Proposed Solution

TBD
### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] When a temperature approaches a threshold (i.e. cold temperature threshold = hot temperature threshold), make the offset 0.5 degrees celsius, rather than 0.1.
