### ISSUE TITLE
Option to re-initialise mobile

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3968]
## Is your feature request related to a problem? Please describe.

**Possibly not required** feel free to argue this one.

I've had to reset tablets a lot recently, switching between environments to test production and dev servers.
We've also had an issue with tablets in Tonga, where the MDM is preventing admin users from accessing settings and clearing app data.

So.. there was a suggestion to allow clearing app data from within the app.

## Describe the solution you'd like

A protected (password? pin?) button in settings which resets the database and reloads the app.

**Comment by katherine-sussol** [comment]
Added some notes on this feature to public docs here: https://docs.msupply.foundation/en:mobile:user_guide:mobile_settings#perform_a_factory_reset_of_msupply_mobile
