### ISSUE TITLE
Add units to 'Average Temperature' 

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#3981]
## Is your feature request related to a problem? Please describe.

Not immediately obvious what temperature unit is being recorded by Cold Chain Mobile when glancing at the summary screen.

## Describe the solution you'd like

Add a '°C' after the number (or possibly an '°F') :)

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

Mobile v8.0.2
mSupply Server v5.01

![photo_2021-04-23 10 10 45](https://user-images.githubusercontent.com/19318937/115791257-3dee5080-a41c-11eb-914d-9fe931829d52.jpeg)

**Comment by katherine-sussol** [comment]
Been playing around with the card... I don't really know what looks good haha.

@adamdewey What do you think of these?

Stuck a symbol underneath the temperature:
![image](https://user-images.githubusercontent.com/65875762/128099872-4c5335e1-bf6d-4e67-ab74-01d857821afa.png)
Put it to the side and shrank the card text a bit so the average temperature card isn't stretched so much horizontally to fit the symbol in:
![image](https://user-images.githubusercontent.com/65875762/128099938-a4a3646b-7a53-48ee-b04a-5f9f0be873fd.png)

**Comment by adamdewey** [comment]
Ooh, nice Kat. Tricky with the space isn't it. 

I think the first looks better, but also looks a bit like it's text wrapping. 

I wonder, could you make the °C a different colour  - maybe a gray? 

That might make it look less like it's text wrapping?

**Comment by katherine-sussol** [comment]
Yeah, such limited real estate (just like in Auckland)! 

Gray looks like this - 
![image](https://user-images.githubusercontent.com/65875762/128100678-820b5805-642d-4ad6-9034-830eaf3cce3a.png)

**Comment by adamdewey** [comment]
Haha exactly, 

I think that looks good!

**Comment by ArpitaSussol** [comment]
Tested in v8.3.0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Have cold chain enabled and a sensor connected with temperatures. Tap on that sensor on the cold chain page and check the 'Average Temperature' card
