### ISSUE TITLE
Display Hot/Cold breach limits on Mobile Cold Chain line graph

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#3984]
## Is your feature request related to a problem? Please describe.

I got really confused by the red and blue maximum and minimum temperature lines on the Cold Chain line graph as I assumed they were my Hot/Cold breach limits, but turns out I assumed wrong. 

![PXL_20210422_234638063~2](https://user-images.githubusercontent.com/19318937/115798455-667d4700-a42a-11eb-8361-2dda21a7cdb6.jpg)

This confusion was somewhat compounded when I switched to the bar chart view as the red line _IS_ the Hot breach limit there :P

![PXL_20210422_234630499~2](https://user-images.githubusercontent.com/19318937/115798483-7432cc80-a42a-11eb-927c-fac530de0633.jpg)

## Describe the solution you'd like

Could we remove the max/min temperature lines and put in the Hot/Cold breach limits instead? 

Guess we'd need to add 4 lines, for both consecutive and cumulative Hot and Cold, maybe we could label them with tiny text or a touchable pop-up info box? 

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

**Comment by katherine-sussol** [comment]
The bar chart currently shows the `HOT_CONSECUTIVE` and `COLD_CONSECUTIVE` breach limits - could easily align the line chart with this, although I'm not sure about 4 lines, I think it could get quite cluttered especially if the limits are close to one another 🤔 .

**Comment by adamdewey** [comment]
Yeah I agree - I think maybe 4 lines is too much. Vote we just go with the HOT/COLD_CONSECUTIVE and keep them consistent on both charts :)

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Have a sensor connected with logs, and navigate to the Vaccine Line Chart (Under Cold Chain menu option), confirm that the hot and cold consecutive breach lines are showing instead of the min/max temperature averages.
