### ISSUE TITLE
Supplier invoice confirm date shows sync date until finalised

### ISSUE THREAD

**Issue by edmofro** [openmsupply/mobile#399]
Build Number: Dev build from master at 27/1/17

Description: The confirm date is the same as the entry date, when the supplier invoice is not yet confirmed. Should be blank.

![supplier-invoice](https://cloud.githubusercontent.com/assets/1274422/22350847/34ea5382-e47a-11e6-9caa-c7011e6b1f9a.png)

**Comment by Chris-Petty** [comment]
This appears to be fixed
