### ISSUE TITLE
Promise rejection when dispensing to a patient with a created date

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3992]
## Describe the bug

When a patient is created through regular dispensing page, then dispensed to through vaccine dispensing, there is a promise rejection which causes the loading spinner to not be closed.

### To reproduce

1. Go to `dispensing`
2. Click on `new patient`
3. Create a new patient
4. Go to `vaccinations`
5. select the patient and create a prescription for that patient

### Expected behaviour

Should correctly create a prescription

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 
- Tablet model:
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in V8.0.5

## Testing

- [x] Create a patient in `dispensing`, then create a vaccine prescription, the prescription is created
