### ISSUE TITLE
Name note not synchronising

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4009]
## Describe the bug

Edit a patient using 'normal' dispensing, including values on the patient survey form.
Save and sync.

The changes do not show as name notes on the server.

### To reproduce

1. Follow the steps above

### Expected behaviour

Using the vaccination process, the changes show on the server as a new name note

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
I've done some testing lately and name notes are syncing correctly 🤔
