### ISSUE TITLE
Manage stocktake is not updating stock quantities unless item is vaccine

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4010]
## Describe the bug

https://user-images.githubusercontent.com/65875762/116958351-66186200-acee-11eb-9264-3d7f71fe3b8e.mp4

### To reproduce

Steps to reproduce the behaviour:

1. Go to Stocktake -> New Stocktake
2. Try to add some quantity for a few items
3. Finalise
4. From Main Menu -> Current Stock
5. Observe non-updated quantities for non-vaccines (but vaccine stock is updated fine)

### Expected behaviour
- Stock quantities should reflect what was entered in the stocktake

### Proposed Solution

Find the offending code first

### Version and device info

- App version: 8.0.5
- Tablet model: Emulator
- OS version: Android 10

### Additional context
- Items coming from supplier invoices still add to stock total quantities fine, think it is just stocktakes not updating.
- Found while testing after upgrading react-navigation and thought I'd broken it 😓

**Comment by ArpitaSussol** [comment]
Tested in V8.0.6

### Testing


- [x] Go to Stocktake -> New Stocktake

- [x] Try to add some quantity for a few items

- [x] Finalise

- [x] From Main Menu -> Current Stock

- [x] Observe non-updated quantities for non-vaccines (but vaccine stock is updated fine)

- [x] Stock quantities should reflect what was entered in the stocktake
