### ISSUE TITLE
Weird behavior while adding lines in Customer Invoice

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#4038]
## Describe the bug
`Available stock` value is changing according to the `Quantity` field entered and thus required quantity cannot be entered in Customer Invoice

### To reproduce
In mobile,
1. Go to Customer Invoices and Create New
2. Add a new line and some quantity
3. Add next new line and try to type some quantity. Notice the strange behavior there: Available stock value changes as per the first value typed in Quantity field

Check the recording:
https://user-images.githubusercontent.com/59193490/117757357-b38d5580-b23f-11eb-9507-0af1e881f340.mp4

### Expected behaviour
`Available stock` values should not change as per the quantity entered.
 
### Proposed Solution
`Available stock` values should be the value of stock available, which should not change easily as per the `Quanity` field is entered

### Version and device info
- App version: v8.0.3
- mSupply version: v5-02

### Additional context
Found while v502 Sync testing

**Comment by joshxg** [comment]
Hey @katherine-sussol  this one looks pretty bad. Do you think you could have a look? We might need to get a patch for master out pretty quickly

**Comment by katherine-sussol** [comment]
@joshxg sure I'll take a look. I just realised v5.02 meant the mSupply version not the app version, oops.

**Comment by katherine-sussol** [comment]
I couldn't replicate this on `master`, but I could when I went back to `8.0.5`, I think this might be the same underlying issue as https://github.com/openmsupply/mobile/issues/4010 which makes sense given there was some manipulation being done behind the scenes on the total quantities.

**Comment by katherine-sussol** [comment]
@nishaSussol would you be able to retest on`8.0.6` and let us know if it's still happening on there? I think it should be fixed in this build.

**Comment by ArpitaSussol** [comment]
> @nishaSussol would you be able to retest on`8.0.6` and let us know if it's still happening on there? I think it should be fixed in this build.

Tested with mSupply 5.0.2 and apk 8.0.6, in PNG and IC datafile :

- no issues in Customer Invoice for both PNG and IC datafile
- Cash Register Module for PNG is not shown where as for IC Cash Register is shown in Mobile. (NOTE: Store Preference "mobile: uses Cash Register module" is checked)

**Comment by katherine-sussol** [comment]
Thanks @ArpitaSussol (sorry I think I missed the original notification). Is the cash register module not showing up on the PNG data file a problem that needs investigation? (Excuse my ignorance I have no idea if it's supposed to do that or not 😆 )
