### ISSUE TITLE
App crashes when selecting vaccinator text in vaccine dispensing drop down

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4040]
## Describe the bug

https://user-images.githubusercontent.com/65875762/117763753-71840400-b27f-11eb-9f69-97aa17f6301c.mp4

### To reproduce

1. Go to Vaccine Dispensing
2. Select a patient and continue until taken to the actual dispensing page
3. Click on the vaccination drop down (note, the arrow works, but clicking on the text will crash the app)

### Expected behaviour

Selecting the text should do the same thing as selecting the arrow

### Proposed Solution

🤷‍♀️  depends where the problem is, although I think it started after the RN upgrade 😹 

### Version and device info

- App version: Current develop
- Tablet model: Emulator/Lenovo (not sure it matters)
- OS version: 8.1 but not convinced it matters

### Additional context
I think it's this one on Bugsnag: https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/6083a4ee1d21390007185b45?filters[event.since][0]=30d&filters[error.status][0]=open

**Comment by katherine-sussol** [comment]
Crashing also been reported in the `react-native-picker` repo (have tried bumping the picker to the newer community version to see if that did anything). Had a read through the discussions, haven't found any super useful workarounds (tried the suggestion to set gesturesEnabled to false in `screenOptions`)  
- https://github.com/react-native-picker/picker/issues/237 
- https://github.com/react-native-picker/picker/issues/220

Still not sure how to fix without just downgrading to 0.63 yet, and the Picker itself works fine on the ADR form.
If `SimpleTable` is removed from the VaccineSelect page (just leaving an empty component inside `AfterInteractions`) the picker no longer causes a crash, so maybe there is some weird interaction going on between them behind the scenes? 🤷‍♀️

**Comment by joshxg** [comment]
Interesting!

So, this is only on develop right? I don't *think* 8.1 is super urgent for anyone *right now* so I don't think it's too much to wait.

I *think* this [commit ](https://github.com/facebook/react-native/commit/b0e8c1e)will fix the issue.. they're just being very slow to cherry pick and cut a patch

**Comment by joshxg** [comment]
BTW if you're a huge nerd like me, watching this repo: https://github.com/react-native-community/releases is helpful (sorry I haven't been keeping up with mobile bugsnags recently 😢 )

The patch discussion issues are useful as there are generally cherry pick requests for the major bugs pretty quick.

**Comment by katherine-sussol** [comment]
> Interesting!
> 
> So, this is only on develop right? I don't _think_ 8.1 is super urgent for anyone _right now_ so I don't think it's too much to wait.
> 
> I _think_ this [commit ](https://github.com/facebook/react-native/commit/b0e8c1e)will fix the issue.. they're just being very slow to cherry pick and cut a patch

Yeah it's just happening on develop. I think there may have been some patient history commits in develop that @mark-prins suggested might be needed soon-ish? Would it be better to put those into master and release from there instead of this dodgy branch that I've destroyed? 😼

**Comment by joshxg** [comment]
Oh right. Yeah I imagine picking the commits into master is probably a good idea

**Comment by joshxg** [comment]
https://github.com/facebook/react-native/releases/tag/v0.64.2 its ouuuuut

**Comment by mark-prins** [comment]
🎉  !! was just about to check - glad you did :)

**Comment by katherine-sussol** [comment]
Closed by #4079 (yayy)
