### ISSUE TITLE
Temperature log timestamps can be incorrect when some hunchy funchy happens

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4045]
## Describe the bug

OK

- Hook up a sensor to a tablet
- Take the sensor away and use it elsewhere.
- Bring it back 4 days later with less then 4 days worth of logs
- App will try and start integrating from 4 days ago rather than counting back 4 logs (all the sensor has) from *now*

### To reproduce

```
it('Correctly calculates the timestamp of a sensor when there is a gap of logs', () => {
    // We are mocking the case where the sensor has been taken away and used elsewhere, for some reason.
    // This sensor is returning a few days later with only a few logs (they were deleted elsewhere).
    // In this case, we should be calculating timestamps backwards from now, rather than counting
    // forward from the saved timestamps.

    // Mocks
    const dbService = {};
    const utils = { uuid: () => '1' };
    const downloadManager = new TemperatureLogManager(dbService, utils);
    const sensor = { id: 'a', logInterval: 300 };

    // Important numbers!

    // We can save heaps of logs
    const maxNumberToSave = 100;
    // The most recent log we have saved is here.
    const mostRecentLogTime = 1000;
    // The time now though, is 100 log intervals into the future.
    const timeNow = mostRecentLogTime + 100 * 300;
    // Then, when we downloaded the logs, we only got two of them.
    const logs = [{ temperature: 10 }, { temperature: 11 }];

    // So when we save these two logs we downloaded, we should save them at
    // timeNow and timeNow - logInterval
    const shouldBe = [
      {
        id: '1',
        temperature: 10,
        timestamp: new Date((timeNow - sensor.logInterval) * 1000),
        sensor,
        logInterval: sensor.logInterval,
      },
      {
        id: '1',
        temperature: 11,
        timestamp: new Date(timeNow * 1000),
        sensor,
        logInterval: sensor.logInterval,
      },
    ];

    expect(
      downloadManager.createLogs(logs, sensor, maxNumberToSave, mostRecentLogTime, timeNow)
    ).toEqual(shouldBe);
  });
```

### Proposed Solution

I think if we just pass `Math.min(maxNumberToSave, shouldBe.length)` (but like, the right variables) then we will count back the number of logs a sensor actually has rather than what we 'think' it *should* have..
### Version and device info

- App version: 7.0+
- Tablet model:
- OS version:

### Additional context

Another option would be to make the download and integrate code less confusing 🙃

**Comment by joshxg** [comment]
@katherine-sussol Had a report from some people who seem to have done this situation... does it make sense?

**Comment by katherine-sussol** [comment]
This is super convoluted 😆  but I think that the problem and proposed solution makes sense. I guess the existing code had an assumption we'd be the only ones deleting logs ... 
I think if I'm understanding correctly `shouldBe` in the example above would just be the actual number of logs we got from the sensor?

**Comment by joshxg** [comment]
yeah..... 😕
