### ISSUE TITLE
Unable to dispense quantity > 1

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4046]
## Describe the bug

Tried to dispense using the standard dispensing module. Unable to increase quantity more than 1

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by katherine-sussol** [comment]
This issue will be fixed with a merge from `master`

**Comment by katherine-sussol** [comment]
Fixed with #4051
