### ISSUE TITLE
Module section shows on navigator when no modules enabled

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4047]
## Describe the bug

Set up a new store, don't enable any modules ( experienced with the Tonga server, so check that if you can't repro )
The module section is shown on the navigator, but there are no modules in it - no menu buttons.

Screenshot:
![screen](https://user-images.githubusercontent.com/65875762/130707861-6d818938-c2f0-48c5-929d-d3501f290c3c.png)

### To reproduce

1. Add a store with no items visible
2. Select the preference to use vaccines
4. Have fun!

### Expected behaviour

The module section should not be shown

**Comment by katherine-sussol** [comment]
Fixed in version after 8.3.0-rc0

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Have no modules enabled and no visibility of any vaccine items in a mobile store, but have the dispensary enabled. Module section should not show.
