### ISSUE TITLE
Battery percentage should correlate to when it needs replacing, not voltage

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#4048]
## Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/7684221/118056475-1ddbfc80-b3de-11eb-8c87-6dae7f5454bf.png)

I believe that the battery percentages shown in app are what are described above. For the user, it'd be more useful if 70% showed as something like 10%, to indicate that the sensor's battery (voltage) is low and they need to replace it.

## Describe the solution you'd like

As above.

## Implementation

Basic math that I am TOTALLY capable of doing...

## Describe alternatives you've considered

🦐 

## Additional context

If this is sent to mSupply/dashboard, should we send the voltage % or our adjusted % 🤔 ?

**Comment by Chris-Petty** [comment]
Whoops I thought I was in mSupply cold chain repo 😆

**Comment by joshxg** [comment]
think our `sensor` table should just keep battery level as a percentage 0-100 and we can map the range 70-100 to 0-100 when we save

**Comment by katherine-sussol** [comment]
This is resolved via msupply-ble-service: 
https://github.com/openmsupply/msupply-ble-service/blob/9dc0419837b47f57616e34902ded24688934b872/src/Bluetooth/BleService.ts#L418
