### ISSUE TITLE
Cold chain line graph doesn't have lines?

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4053]
## Describe the bug

😿 
![image](https://user-images.githubusercontent.com/65875762/118582046-d04cfe80-b7e6-11eb-98d0-0ea1498ef711.png)

### To reproduce

Steps to reproduce the behaviour:

1. Enable cold chain, set up a sensor and let it log for a while
2. View sensor details for the sensor and select line graph icon

### Expected behaviour

Lines? Something more like this (from `master`):
![image](https://user-images.githubusercontent.com/65875762/118583582-68e47e00-b7e9-11eb-9bf1-c8d9680fa79e.png)

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: Develop 
- Tablet model: N/A
- OS version: Android 8.1

### Additional context
??

**Comment by katherine-sussol** [comment]
The line seems to appear after a graph redraw when new data comes in if staying on the page, but when the line chart is first loaded, only has the 'circles' (and no lines).

Tried downgrading victory-native from `35.3.3` to `35.3.1` (pre 8.1 version) just in case that was what caused it, but no luck.

**Comment by joshxg** [comment]
Interesting.. so no matter how many data points, on a first render, theres no line?

**Comment by joshxg** [comment]
Was `react-native-svg` changed?

**Comment by katherine-sussol** [comment]
> Interesting.. so no matter how many data points, on a first render, theres no line?

Yeah, very odd. 



> Was `react-native-svg` changed?

Was bumped from `11.0.1` to `12.1.1`, interestingly downgrading that seemed to make the lines re-appear on first render 🤔

**Comment by joshxg** [comment]
Took a guess as it's the primary svg package for `react-native` guessing its a peer dep

**Comment by ArpitaSussol** [comment]
Tested in v8.1.1 rc3

- [x] Enable cold chain, set up a sensor and let it log for a while
- [x] View sensor details for the sensor and select line graph icon
