### ISSUE TITLE
Add barcode field to realm schema 

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4068]
## Is your feature request related to a problem? Please describe.

Child of #4066

## Describe the solution you'd like

The ability for mobile to store a patient's barcode

## Implementation

- Add barcode field to realm `Name` object
- Update sync utils to include barcode 

## Describe alternatives you've considered

None really.

## Additional context
N/A

**Comment by katherine-sussol** [comment]
Closed by #4077

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Sync and check realm explorer to see if it's there?
