### ISSUE TITLE
Remote patient searching via QR Code

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4072]
Child of #4066
Prerequisite: https://github.com/sussol/msupply/issues/8840

## Is your feature request related to a problem? Please describe.

As a user, I would like to be able to use a scanned QR code to search against online patient records (when a local search has returned no results), so that I don't need to manually enter search criteria into the app when dispensing a vaccine.

## Describe the solution you'd like
Given:
- The app has successfully retrieved a QR code, and 
- A local search has been performed with the QR code and no results were found
  - A search should be performed against the mSupply server patient API using the QR code
  - If there is a match, the user should be taken to Step 2 of the vaccine dispensing flow, with the relevant patient details prepopulated
  - If there is no match, the user should be told the patient couldn't be found, and be taken back to the vaccine dispensing page to either try again or enter details manually
 
## Implementation

TBD

## Describe alternatives you've considered

N/A

**Comment by katherine-sussol** [comment]
Found a sample ID:
![Untitled copy](https://user-images.githubusercontent.com/65875762/121832084-52b0db80-cd1d-11eb-9230-426089c43cfd.png)
Encoded is the following: `VGID\00177678/8N2HYJL`

**Comment by ArpitaSussol** [comment]
Tested in mSupply V8.2.0 - rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Have a patient that is not available locally but is available remotely, scan a QR code corresponding to that patient -> should be taken to step 2 of the patient vaccination page with remote patient details pre-populated
