### ISSUE TITLE
Show number of doses left for a vaccine vial

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/mobile#4080]
## Is your feature request related to a problem? Please describe.

Georgia (BES) has advised that vaccinators in Tonga are sometimes accidentally dispensing second doses to patients in Mobile because they have to go into the vaccine module to check how many doses are left in a vial.

## Describe the solution you'd like

For vaccines show the number of doses left in a vial in the current stock section of Mobile.

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Have at least one vaccine in stock, navigate to the 'Current Stock' page in mobile and select the vaccine (it is not super obvious it is clickable but that's a separate issue: #3532)
