### ISSUE TITLE
Data import 

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#4082]
## Is your feature request related to a problem? Please describe.

When trying to reproduce user's issues, sometimes it's hard to know exactly what's wrong and how their data might be causing it.

It'd be useful to be able to take realm data exported from the app, and import it into the app on a different device (i.e. one in our offices).

@ujwalSussol says this would be really helpful for support trying to debug issues (one current support ticket trying to diagnose a sync issue), and for testers trying to reproduce things. I tend to agree!

A little more on said support issue, this would allow support to potentially recover un-synced data. There is a current support ticket where a client cannot sync, and has 100 invoices on the tablet. If the problem is due to a bad app state, clearing the tablet and resyncing would lose all those invoices. If support could get the data from the tablet, diagnose it, correct it, wipe the tablet and import, then mission accomplished! (And hopefully figure out what caused the bad state along the way.)

Support ticket : https://support.msupply.org.nz/cerb6/profiles/ticket/YQ-9957-RF

## Describe the solution you'd like

An import button somewhere on initialisation page (subtle cog in the corner?)

## Implementation

?

@andreievg once did something with loading a realm datafile into the app. Might have been at build time though.

Realm may have a way of doing this neatly with a realm datafile.

One thing to consider is that realm data from an older version of mobile would either A: need to go through migration or B: not work, they need to upgrade to a version that includes the import functionality (and therefore ran migrations needed).

## Describe alternatives you've considered

🙅 

## Additional context

Related to #3277 ?

**Comment by ujwalSussol** [comment]
@Chris-Petty   

We have had two or three zoom meetings regarding this.  @raviSussol  has come up with a way and he and @ArpitaSussol  have tested his work. He added a feature into mSupply.

I will allow @raviSussol  to explain.

**Comment by raviSussol** [comment]
@Chris-Petty I've had a quick look yesterday at the mobile for a realm db restore/import and I tried to import realm file in the app and it worked - data are restored. I planned to show how it works to our Nepal dev + testers but we ran out of time setting tablet and mac to share screen in the Zoom. So maybe tomorrow I'll show to the Nepal dev team and will update here what I did so far.

**Comment by ArpitaSussol** [comment]
above mentioned issue is fixed by @raviSussol. Here is the attached video regarding how Data Import will work in below link
https://drive.google.com/drive/folders/1J-Es-eI4LY3XC0U3dXVdNiQgfvxnGzhK

**Comment by katherine-sussol** [comment]
Docs updated with some brief notes on the import functionality: https://docs.msupply.foundation/en:mobile:user_guide:mobile_settings
