### ISSUE TITLE
Need check connection button

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#4085]
## Is your feature request related to a problem? Please describe.

mSupply mobile allows to change the Sync URL and the Sync password from its setting page.
With this, Thinking to expand this to have a Sync username and check connection button - So that if there is a mystery happened as seen here: https://support.msupply.org.nz/cerb6/profiles/ticket/12482/ - the first thing is to check the connection same as mSupply desktop - to make sure connection is good. So with this issue we are aiming to see if connection is OK

Something like this:

![photo_2021-06-09_13-06-27](https://user-images.githubusercontent.com/13144882/121317744-506c0d00-c92a-11eb-8cf2-5e8fd215dd2a.jpg)

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

ATM setting page is control by mSupply preference > We probably also need a way to enable setting page within from the app itself.

@joshxg said this: 
Josh g, [09.06.21 13:11]
Also we need to.. return the settings button when holding mSupply man

**Comment by joshxg** [comment]
@bijaySussol 

Probably best if we do three issues:
- Check Connection button
- Change Sync Username field
- Enable the settings button from within the app

If this is for check connection button:
- Add a button on this Page: https://github.com/openmsupply/mobile/blob/master/src/pages/SettingsPage.js
- This button could try to authenticate against the server, similar to how sync usually does it like here: https://github.com/openmsupply/mobile/blob/c734e03bfdfd7595cf1a24eafbc1675b8fcc36da/src/authentication/SyncAuthenticator.js#L57-L59

**Comment by bijaySussol** [comment]
@joshxg : 

Splitted into 3 issues including this.

**Comment by ArpitaSussol** [comment]
tested in v8.1.1 rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Click on check connection
   - [x] Show show the connection status same as check connection button in 4D but with limited alert

**Comment by katherine-sussol** [comment]
Docs updated: https://docs.msupply.foundation/en:mobile:user_guide:mobile_settings#check_connection
