### ISSUE TITLE
Change Sync Username field

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#4087]
## Is your feature request related to a problem? Please describe.

mSupply mobile allows to change the Sync URL and the Sync password from its setting page.
We allow to modify the sync Username

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by bijaySussol** [comment]
I probably don't think we need this to get this IN.
Any thought @joshxg @mark-prins ?

**Comment by joshxg** [comment]
@bijaySussol I am not sure. I believe it is more of a support feature. If it would help support our customers and save the time of our support team, then I am happy to see it get in. Otherwise, if you don't think it will help too much, we can definitely leave it out.
