### ISSUE TITLE
Realm Explorer crashes in a release build

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4092]
## Describe the bug

In a realease build (8.1.0-rc0) typign anything into the search bar of the realm explorer crashes the app

### To reproduce

1. Go to Settings
2. Click on the search bar and try to search for something

### Expected behaviour

No crash

### Proposed Solution

N/A

### Version and device info

- App version: 8.1.0-rc0
- Tablet model:
- OS version:

### Additional context

N/A

**Comment by joshxg** [comment]
@mark-prins @katherine-sussol not sure if this is a release blocker, what do you think? If we get them stuck on this version for awhile might run into trouble if we needed to use it, I suppose! No idea what the issue is

**Comment by joshxg** [comment]
oh https://github.com/openmsupply/mobile/issues/4091

**Comment by mark-prins** [comment]
would like to fix. will see if I can do it :)

**Comment by joshxg** [comment]
@mark-prins 

Oh.. more info

- I typed `'Josh'` and it was OK
- I typed `'i'` and it was not OK.. 🙄 

I have uploaded a source map now, so hopefully bugsnags will be better

**Comment by katherine-sussol** [comment]
Hmm interesting, I grabbed the universal release build and am managing to search for the most part 🤔, except when I tried specific letters 'O', 'I', or 'T' and left in the search box I saw the crashing, very odd...

**Comment by mark-prins** [comment]
that sounds very validating :)
`Josh` = `OK`
strange.. to have 'reserved' letters

**Comment by joshxg** [comment]
Bit better: https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/60af1883a478290008207e8c?event_id=60c16d2f007d07c1efd20000&i=em&m=fq

!

**Comment by joshxg** [comment]
Ugh. I just remembered about this one: https://github.com/openmsupply/mobile/issues/3048 which might or might not be related.........

**Comment by mark-prins** [comment]
Slightly different.. but I have wandered down that path. I wasn't getting any rows, so started looking into it

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Explore. With Realm
