### ISSUE TITLE
Patient name cut off when dispensing

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4093]
## Describe the bug

Minor UI issue:
![image](https://user-images.githubusercontent.com/65875762/121454724-70b5cd80-c9f7-11eb-8dfd-bb1001b9a56f.png)

### To reproduce

1. Log into a dispensary
2. Select a patient and try to dispense something
3. On the prescriber selection screen, the patient's name is cut off at the bottom slightly

### Expected behaviour

No cut off

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.1.0-rc0
- Tablet model: Lenovo
- OS version: 8.1

### Additional context
The prescriber name is also cut off on the item selection screen further along the prescription process

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 rc1

## Testing

- [x] Log into a dispensary
- [x] Select a patient and try to dispense something
- [x]  On the prescriber selection screen, the patient's name is cut off at the bottom slightly
