### ISSUE TITLE
Selecting a vaccine on the supplier requisition page crashes app

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4095]
## Describe the bug
Linked Bugsnag logged issue: https://github.com/openmsupply/mobile/issues/4094

https://user-images.githubusercontent.com/65875762/121458191-0bfd7180-c9fd-11eb-9efc-c2cfb657d995.mp4

### To reproduce

Steps to reproduce the behaviour:

1. Go to supplier requisition and pick a vaccine

### Expected behaviour

No crash

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.1.0-rc0
- Tablet model: Lenovo
- OS version: 8.1

### Additional context

Vaccine module wasn't enabled, not sure if relevant

**Comment by mark-prins** [comment]
The one in `DataTablePageModal` is essentially the same: selecting VVM status on the supplier invoice will crash the app

**Comment by mark-prins** [comment]
Ok. I see now - it requires a finalised supplier requisition, which sets the page `lastRequisitionDate`
The error I get is `Error: Property 'doses' does not exist on object 'TransactionBatch'` which is due to the `doses` being a getter on the `TransactionBatch` and not an underlying db field.

**Comment by katherine-sussol** [comment]
Closed by #4099 (for testing in 8.1.0-rc1)

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0.rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Go to supplier requisition and pick a vaccine
- [x]  app should not crash
