### ISSUE TITLE
Stocktake batch modal crashes when modifying vaccine VVM status

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4097]
## Describe the bug

Bugsnag logged issue: https://github.com/openmsupply/mobile/issues/4096
Recording:
https://user-images.githubusercontent.com/65875762/121468447-e9745400-ca0e-11eb-95aa-9aa2c0c05b68.mp4

### To reproduce

Steps to reproduce the behaviour:

1. Try to set up a VVM status for vaccine stock in mobile 
2. Observe app crash

### Expected behaviour
No app crash

### Proposed Solution

For some reason 
`data={UIDatabase.objects('VaccineVialMonitorStatus').filtered('isActive == True')}` doesn't work
but 
`data={UIDatabase.objects('VaccineVialMonitorStatus').filtered('isActive == true')}` does

### Version and device info

- App version: 8.1.0-rc0
- Tablet model: Lenovo
- OS version: 8.1

### Additional context
N/A

**Comment by mark-prins** [comment]
The one in `DataTablePageModal` is essentially the same: selecting VVM status on the supplier invoice will crash the app

**Comment by katherine-sussol** [comment]
Closed by #4098 (for testing in 8.1.0-rc1)

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 rc1

## Testing

- [x] Try to set up a VVM status for vaccine stock in mobile 
- [x] Observe app do not crash.
