### ISSUE TITLE
Requisition: Item's Monthly Use calculation seems wrong 

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#4101]
## Describe the bug

In Customer Requisition, Item's Monthly use calculation is wrong.
### To reproduce

1. Go to Customer Requisition
2. Click on exisiting Customer Requisition or Create a new Requisition
3. Click on any Item. Dialog window will show at bottom of screen showing calculation for Suggested Quantity
4. See error. "Monthly use" calculation seems wrong. 
![Screenshot_20210610-161016_mSupply-Mobile](https://user-images.githubusercontent.com/58979436/121510299-3522ff80-ca07-11eb-8836-9512df213954.jpg)

### Expected behaviour

Suggested Quantity calculation should reflect right calculation

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.1.0-rc0
- Tablet model: Samsung
- OS version: 8.1

**Comment by joshxg** [comment]
@ArpitaSussol I can't recreate this at the moment..

There is definitely something wrong with the calculation 0 * 30 / 31 is not 32! But it's a little hard to see without the other columns (Customer Data) to be able to recreate this 🤔

**Comment by ArpitaSussol** [comment]
> @ArpitaSussol I can't recreate this at the moment..
> 
> There is definitely something wrong with the calculation 0 * 30 / 31 is not 32! But it's a little hard to see without the other columns (Customer Data) to be able to recreate this 🤔

hmm i just clicked on Item row of existing Requisition and that dialog window shown. So most probable not an issue ?
