### ISSUE TITLE
Submitting a username does not focus the password field

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4105]
## Describe the bug

When pressing submit on the username in the login modal, the password form isn't focused

### To reproduce

1. Go to login
2. Click on username and enter a username and press enter/submit

### Expected behaviour

The password field should be focused. This is pretty annoying cause the password field is also usually hidden

### Proposed Solution

Unsure

### Version and device info

- App version: 8.1.0-rc0
- Tablet model:
- OS version:

### Additional context

N/A

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 rc1

## Testing

- [x] Go to login
- [x] Click on username and enter a username and press enter/submit
- [x] Password field should be on focus
