### ISSUE TITLE
Warning on Cash Register screen

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4126]
## Describe the bug

Viewing the cash register screen in develop mode shows a warning:

![telegram-cloud-photo-size-5-6213084731478748495-y](https://user-images.githubusercontent.com/9192912/121988885-41d09a80-cdef-11eb-82f2-d6462831e630.jpg)

### To reproduce

1. Ensure that you have records in the `[paymentType]` table
2. Enable the cash register preference for your mobile store
3. Open the cash register on the tablet

**Comment by ArpitaSussol** [comment]
Tested in V8.1.0 rc1

## Testing

- [x] Ensure that you have records in the `[paymentType]` table
- [x] Enable the cash register preference for your mobile store
- [x] Open the cash register on the tablet. No warning should be shown
