### ISSUE TITLE
Notification badge is not displayed immediately after sync

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4130]
## Describe the bug

A notification badge is displayed on the app homepage when there is an outstanding item that requires the user's attention. For example, a new Supplier Invoice. 

However the badge does not appear after a simple sync action. 

To trigger the badge to appear the user must exit the homepage and re-enter the homepage. Then the badge will be shown. 

### To reproduce

1. Log into a primary site
2. Create a 'Customer Invoice' for a mobile site
2. Finalise the Customer Invoice. 
3. Log into the mobile site
4. Perform a manual sync
5. Observer that no notification badge is displayed
6. Navigate to any other page than the homepage in the mobile app
7. Navigate back to the homepage
8. Observe notification badge now appears.

![2021-06-16_11-01-10](https://user-images.githubusercontent.com/19318937/122135213-308d9980-ce94-11eb-87d9-05bb567852f6.png)

https://user-images.githubusercontent.com/19318937/122135287-4f8c2b80-ce94-11eb-8de9-1a8e0c386842.mp4

### Expected behaviour

As a user I would expect to be alerted of any changes that require my attention after a sync operation without having to refresh the homepage. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v8.0.8
- Tablet model: Lenovo TB X505-N
- OS version: Android 10

**Comment by katherine-sussol** [comment]
This was sort of improved in 8.1 with https://github.com/openmsupply/mobile/issues/3279, although it's not an instant update (it updates the badges within ~10s of sync?). Good for if someone is sitting on the page while sync is happening in the background, but maybe not as good for sync button spammers like me 😹

**Comment by adamdewey** [comment]
Oh! Sorry, missed that Kat - I was looking in open tickets... 

Oh cool, well that's definitely better - I guess 10 seconds isn't ideal but at least they'll see the badge if they're away from the tablet and come back while an auto-sync has happened in the meantime!

Will close this as a dupe..
