### ISSUE TITLE
Improve date picker in Mobile ColdChain module

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4139]
## Describe the bug

I've often thought the date picker just takes a long time to show, but actually I've recently discovered that it only shows if you tap on the little calendar icon, and not on the date. In the past I must just have tapped randomly several times and accidentally hit the calendar icon by chance - would be great if tapping on the date triggered the same thing :)

### To reproduce

1. Go to ColdChain module
2. View a sensor's graph
3. Tap on the actual date characters 
4. Observe nothing happens
5. Tap on the calendar icon
6. Observe date picker appears

https://user-images.githubusercontent.com/19318937/122330920-18974200-cf88-11eb-9ca4-7d3eb7468528.mp4

### Expected behaviour

I would expect tapping on either the calendar icon or the date itself would bring up the date picker.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.0.8
- Tablet model: Lenovo TB-X505N
- OS version: Android 10

**Comment by katherine-sussol** [comment]
Thanks for pointing this one out @adamdewey!
Closed with #4149

**Comment by ArpitaSussol** [comment]
Tested in v8.1.1 rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] View the fridge detail page for a fridge with some sensor logs and tap the text that displays the date - this should open the DatePicker
