### ISSUE TITLE
Text cut off on 'Done' button on 'Add Master List Items' modal (for Supplier Requisitions)

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4150]
## Describe the bug

![image](https://user-images.githubusercontent.com/65875762/122715221-ad69aa80-d2bc-11eb-9274-b6f095e2552d.png)

### To reproduce

1. Go to 'Supplier Requisitions'
2. Create a new Supplier Requisition
3. Click on 'Add Master List Items'
4. Observe done button

### Expected behaviour

No cut off

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.1.0-rc1
- Tablet model: Emulator
- OS version: 

### Additional context
Not sure where else text is being cut off, seems to have been popping up a few times

**Comment by katherine-sussol** [comment]
Closed with #4175

**Comment by ArpitaSussol** [comment]
Tested in 8.1.1 rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Follow steps in #4150 and verify the text on the button isn't cut off
