### ISSUE TITLE
TemperatureLog.sensor is not synced

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4151]
## Describe the bug

in `incomingSyncUtils`, incoming `TemperatureLog` records are not related to their `Sensor`.

This means you don't get the 'current' temperature of a `Sensor` till later

### To reproduce

1. Go to sync a mobile store with an existing sensor+logs
2. Click on vaccines page

### Expected behaviour

N/A

### Proposed Solution

Add to `incomingSyncUtils`

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
Closed by #4152

**Comment by ArpitaSussol** [comment]
Tested in V8.4.0

## Testing

- [x] Setup a mobile with a sensor and some temperature logs. Reinitialize. Check the records/current temperature of the sensor
