### ISSUE TITLE
Import data button is enabled

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#4154]
## Describe the bug

This is against the develop branch of Mobile and against the first window where user keep the sync details to connect to mSupply to collect data from the server

![photo_2021-06-22_11-16-54-import](https://user-images.githubusercontent.com/13144882/122879740-f53e0f80-d358-11eb-9a6d-8d42f37f3044.jpg)

### To reproduce

1. Take the develop master
2. Setup locally
3. Start the mSupply app
4. on a window where user authentic using the sync details
5. Import data is enabled

### Expected behaviour

Import data button should be disabled

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v8.1.0-r1
- Tablet model: Emulator
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in 8.1.1 rc3

## Testing

Setup the mobile connection from the scratch to the desktop mSupply

- [x] `Import Data` button would be disabled while initialisation is on process
