### ISSUE TITLE
Enable QR code patient lookup

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4157]
## Is your feature request related to a problem? Please describe.

Looking to release a version of mobile, and thought that it might be time to enable the button for all users?

## Describe the solution you'd like

Enable the vaccination > QR code patient lookup button. i.e. remove the `__DEV__` check.

**Comment by mark-prins** [comment]
@katherine-sussol @joshxg : any concerns?

**Comment by joshxg** [comment]
Nope, release the kraken

**Comment by katherine-sussol** [comment]
Sounds good to me! I don't think anyone will be able to do anything (good or bad) with that button if it's not set up properly in the backend anyway? 🤣
