### ISSUE TITLE
Respect medicine administrator soft delete

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4158]
## Is your feature request related to a problem? Please describe.

- Can soft delete vaccinators on the server

## Describe the solution you'd like

- Accept incoming `is_active` field and add it to the schema.
- Filter the list of vaccinators by the `is_active` field.

## Implementation

TBD

## Describe alternatives you've considered

N/A

## Additional context

- Don't need to SEND medicine admins to the server, so will not cause versioning issues.

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc0

## Testing

- [x] Cannot see softly deleted vaccinators.
