### ISSUE TITLE
"Check connection" causes sync to halt and further shows inconsistent behavior

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#4170]
## Describe the bug

on clicking Settings -> Check connection, causes sync to fails. 
### To reproduce

1. Go to Settings
2. Click on Check Connection. It shows message "Connection successful" if working properly
3. Do some requisition and manually sync the mobile site
4. See error. Sync fails with the message "Sync record rejected....."
5.  Now logout from the system.
6. login again
7. See Error. "Site name not found" error shown and one couldn't login into the site

https://user-images.githubusercontent.com/58979436/123241244-b054dd00-d500-11eb-8508-85d47d265919.mp4

### Expected behaviour

Sync should be consistent in any operation

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.1.0
- Tablet model: Samsung
- OS version: 8.1

**Comment by bijaySussol** [comment]
@ArpitaSussol : 

I have found this similar issue here: https://github.com/openmsupply/mobile/issues/4153

But it was not anything to do with check connection button 
Could this be related with something else, can check

**Comment by bijaySussol** [comment]
@ArpitaSussol : 

Doing TV - found that - when check connection is clicked URL get changed
![Screenshot 2021-06-24 at 15 56 08](https://user-images.githubusercontent.com/13144882/123246110-2a876080-d505-11eb-99b0-d69c88e91dab.png)

Could be a issue with this as well:#4153

**Comment by ArpitaSussol** [comment]
Tested in v8.1.1 rc3

### Testing

- [x] Go to Settings
- [x] Click on Check Connection. It shows message "Connection successful" if working properly
- [x] Do some requisition and manually sync the mobile site
- [x] No error. 
- [x] Now logout from the system.
- [x] login again
- [x] No Error.
