### ISSUE TITLE
Vaccine dispensing: insert step for site of vaccination

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4176]
## Is your feature request related to a problem? Please describe.

Tonga would like to record the following additional data as part of the vaccination process:

- Island ( drop down field )
- Village ( drop down field, dependent on the selected Island )
- Free text field for ‘Administering Location’

## Describe the solution you'd like

- Insert a step in the wizard process which asks for
- Island, Village and administering location
- Save this data against the transaction

## Implementation

- Populate mSupply region table using the new import feature
- Create region properties to save population and geolocation data
- After this we can remove the district and population tables used by the dashboard
- Create a new JSON schema and save in mSupply ( generate island and village from the region table )
- #4197
- #4210
- #4198

**Comment by mark-prins** [comment]
@npendergrast & @craigdrown  : does this cover what is required? And what do we do about 'save to region tables'? I'm not sure what the requirement is sorry!

**Comment by npendergrast** [comment]
Hi @mark-prins, this all sounds good to me (after your explanation earlier of the properties connected to the region table).

I'm not sure about the final requirements for Kiribati and what location data they will want to have recorded.

**Comment by katherine-sussol** [comment]
Have updated public docs with extra step: https://docs.msupply.foundation/en:mobile:user_guide:vaccine_dispensing#vaccine_dispensing_for_covid-19_other_vaccines
