### ISSUE TITLE
Red and blue breach lines have disappeared from ColdChain histogram view

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4178]
## Describe the bug

The red and blue hot and cold breach lines are not showing in the histogram view.

### To reproduce

Steps to reproduce the behaviour:

1. Log into Mobile > ColdChain
2. Select a sensor and open the histogram view

![image](https://user-images.githubusercontent.com/19318937/123562842-4b053280-d805-11eb-87d4-2f0619f1604d.png)

### Expected behaviour

A red and blue line is shown for the hot and cold breach configuration limits. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.1
- Tablet model: Lenovo TB-X5050N
- OS version: Android 10

**Comment by katherine-sussol** [comment]
Closed with #4185
