### ISSUE TITLE
Crash when pressing hardware back button on initialisation screen

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#418]
Build Number: 1.1.0-beta.1

Description: Opening mobile when no initialisation has been done. Press the hardware back button. App closes and says "Unfortunately, mSupply Mobile has stopped"

Reproducible: Yes

Reproduction Steps:
1. Clear app data
2. Open app
3. Press hardware back button

Repeat 2 and 3 as much as you like.

Comments:
Not major as users will rarely see this screen beyond initial set up, and the crash is inconsequential.
But it may be related to #365 .

**Comment by andreievg** [comment]
Also mentioned in: https://github.com/sussol/mobile/issues/365

Logged as: `undefined is not a function (evaluating 'this.intervalIds[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]()')`

Origin: sussol-utilities/lib/Scheduler.js

Explanation: When sussol-utilities package is compiled using with babel es2015 preset, `for of` loop in clearAll function compiles to use `Symbol`, seems to be no polyfill for Symbol. There are numerous issues re: this problem, even a feature request: https://react-native.canny.io/feature-requests/p/polyfill-es6-symbol and good explanation here: https://github.com/redux-saga/redux-saga/issues/54

Solutions:
* compile sussol-utilites using es2015-loose preset or react preset.
* replace `for of` with `forEach`
* in `index.android.js`, before main import `import 'babel-polyfill'` (increase app size but help with future compatibility) 

What do you think Chris ?

**Comment by edmofro** [comment]
Re. above comment, for of was replaced with canonical for loop at sussol-utilities 0.4.4, which is now in use by mSupply Mobile

**Comment by joshxg** [comment]
This is no longer occurring, closing
