### ISSUE TITLE
Improved observability through logging

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4189]
## Is your feature request related to a problem? Please describe.

We have been having a lot of issues with bluetooth specifically. It is hard to debug bluetooth issues.

## Describe the solution you'd like

Improved debugging of use in production through internal logging.

## Implementation

Unsure

## Describe alternatives you've considered

N/A

## Additional context

No idea how to implement this right now!

**Comment by joshxg** [comment]
@katherine-sussol @mark-prins 

I'm thinking there are some high level goals for this would be:
- A generic enough solution which can be used in more areas than just bluetooth
- Would be excellent to reuse the same thing for omSupply
- Logs providing enough information to actually be valueable

What I have so far as a rough plan:

An interface like this for some logging objects:

```
Interface Logger { 
     prefix: string // Prefixes or adds this string to each log this logger logs. i.e. would log something like `bleService:someLogMessageHere`
    start: ([]:any) => void // logs a log like, `${prefix}:start:${optional params stringified}
    end: ([]:any) => void // logs a log like, `${prefix}:end:${optional params stringified}
    info: ([]: any) => void // logs a log like, `${prefix}:info:${optional params stringified}
    error: ([]: any) => void // logs a log like, `${prefix}:error:${optional params stringified}
     new: (string) => Logger // Returns a new logger with extra prefix - i.e. new Logger(“BleService”).new(“downloadLogs”) prefixes all logs with `BleService::downloadLogs::`
}
```
- Each method will control the actual logging, and check whether it should be logging (can turn it off globally or something)

Where the general usage would be:

- Each file/class creates a logger instance:
`const FileLogger = new Logger(“BleService”);`

- Within the file/class, you can spawn another logger for more fine grained detail:
const logger = FileLogger.new(“downloadLogs”)

- Then you start the logging, with optional parameters?
`logger.start(x: []any)`

- And you can end
`logger.end(x: []any)`

- And you can add arbitrary info throughout the method call
`logger.info(x: []any)`

- As well as errors
`logger.error(x: []any)`

Some things to still work out:
- It would have been nice to make this a little more automatic but what I have tried so far seem a little frail, use experimental tech or add decent performance penalties..
- I want to be able to switch the actual implementation of logging to be `console.log` for development and something else for not development
- I want to set the global logging level. Usually this is something like `verbose`, `warn`, `error`, `info` or something, so maybe I should just go with that as the methods. But, I am a special snowflake and I like having a clearer guideline from the API in where you should use each method. For example, if someone just starts using `info` for method start calls and someone else uses `warn`.
- I think this is easy and fine to incrementally start adding to places in the code base.
- I am not sure if we should just use a file or DB. We could even just create a new realm instance (I think) and have that solely for logging .. ? A text file for now would be easier but grepping through the logs is horrible. Could also use bugsnag..?

**Comment by wlthomson** [comment]
I have had some good experiences with https://github.com/trentm/node-bunyan. Covers a lot of these use-cases and also allows `serializer` logging functions which might help with logging problematic realm objects?

**Comment by mark-prins** [comment]
one additional requirement you touched on but didn't list explicitly was performance impact. Particularly if we are running in production, which I think we need to from what I understand.

I was leaning toward file system logging:
- it's fairly simple
- doesn't rely on an external system or process
- reasonably quick?

though, I wonder about
- how to grep logs, as you say
- how to access logs remotely
- size limitations & performance impact if too large

thinking to rollover logs to keep the size down.

bunyan looks good - thanks @wlthomson!!

**Comment by joshxg** [comment]
For an initial implementation, logging to the same place as the realm files seems good enough. I suspect that firing a promise off to the native side to write some data with no other actions on the js thread shouldn't be to bad performance wise.

Some lessons learned from the mSupply logging: 
- Valid JSON makes it easier.. can we easily append valid json 🤔 
- Continually writing log files gets big fast! Rolling over is good - maybe sticking with just the one for now, could extend it later.
