### ISSUE TITLE
Ability to search middle of a text string

### ISSUE THREAD

**Issue by andrew-d-uk** [openmsupply/mobile#419]
Currently the search function appears to only search the beginning of item strings, possibly for speed reasons?

Ideally users would like to search anywhere in the string - e.g. if a user is looking for an item called "Acetcylic acid (Aspirin)" it should appear in search results for 'aspirin'

Users can quickly learn to get around this.

**Comment by Chris-Petty** [comment]
It is currently done like this by preference as it is consistent with mSupply Desktop. If you want to add all items starting with 'a' to a stock take, all you need to do is search for 'a'. If it returned everything containing 'a' it wouldn't be particularly useful, unless say you wanted every item containing 'Aspirin' somewhere in the name.

Some places in the app, such as adding an item to an invoice, does filter by checking the whole string as you suggest. It should be possible to option to sort like this in the table searches.

**Comment by joshxg** [comment]
Looks like this is intended functionality and won't be acted on, closing.
