### ISSUE TITLE
Show vaccinator in patient history for online patient lookups

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/mobile#4203]
## Is your feature request related to a problem? Please describe.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

For Tonga we added a feature to allow patient history lookup for all patients in the vaccine module (limited to vaccination history only): https://github.com/openmsupply/mobile/issues/4022

Tonga/BES have now asked that they would also like to be able to see that vaccinator/prescriber in the patient history for patients that have been looked up online.

This may require a change to the 4D api as vaccinator is probably not currently provided by the api.

**A clear and concise description of what you want to happen.**

Currently when you look up a patient who was vaccinated on another tablet in the dispensing module you can see the item, quantity and date of the vaccine in the patient history. But currently prescriber (vaccinator) shows N/A. Tonga would like to see who the vaccinator was.

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by katherine-sussol** [comment]
I had a look at the patient history API. I _think_ the vaccinator is returned as "medicineAdministrator", so should be able to use that... (although is 'Prescriber' accurate for someone who does a vaccination? 🤷‍♀️ )

e.g:
```
[
  {
      "confirm_date": "2021-06-29",
      "transLines": [
          {
              "quantity": 1,
              "item_name": "Acetylsalicylic Acid 100mg tabs",
              "ID": "afe9a920d86311ebb73d2fafdfc2f1e3",
              "itemLine": {
                  "item": {
                      "code": "030063",
                      "doses": 0,
                      "is_vaccine": false
                  }
              }
          }
      ]
  },
  {
      "confirm_date": "2021-06-29",
      "transLines": [
          {
              "quantity": 0.125,
              "item_name": "COVID19 Vaccine AstraZeneca",
              "ID": "dc39ceb0d86311ebb73d2fafdfc2f1e3",
              "itemLine": {
                  "item": {
                      "code": "COV1",
                      "doses": 8,
                      "is_vaccine": true
                  }
              },
              "medicineAdministrator": {
                  "first_name": "Limisesi",
                  "last_name": "Kaiveleta"
              }
          }
      ]
  }
]
```

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- Prerequisites:
  - Run `z_toggleDangerousPatientMode` (⚠️!)  on mSupply Desktop
  - Create a vaccination on a store (ensure it has a vaccinator selected)
  - Login to a different store on mobile and navigate to Dispensing -> History

- [x] Confirm that the vaccine history record shows up, and the vaccinator is displayed
