### ISSUE TITLE
Online patient history lookup throwing a server communication error for certain patients

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/mobile#4216]
## Describe the bug
When using opening the history of certain patients that have been searched for via online lookup the user receives the following error

![image](https://user-images.githubusercontent.com/55637835/124697662-4d6d3800-df3b-11eb-9c24-e8c4647d63f9.png)

### To reproduce

Ask Nick for patient name (won't list here on public repo)

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by katherine-sussol** [comment]
Appears that one particular user that happens to be having the issue has an old transaction with no `itemLine`, which causes the whole patientHistory response to not process.

e.g.
    {
        "confirm_date": "2021-04-28",
        "transLines": [
            {
                "quantity": 0.083333333333333,
                "item_name": "ChAdOx1-S (Recombinant)  AstraZenna Vaccine",
                "ID": "4ed46090a96e11eb8d8071ff5200b23b",
                "medicineAdministrator": {
                    "first_name": "[FIRST_NAME]",
                    "last_name": "[LAST_NAME]"
                }
            }
        ]
    },

**Comment by katherine-sussol** [comment]
Few thoughts - 
- Could hide transactions from the history that don't have itemLines
- Show transactions that don't have itemLines but leave blank fields where data is unavailable, (looks like it's just itemCode that wouldn't show) 
- ? Are the above ignoring a bigger problem going on behind the scenes? (are itemLines supposed to be there?)

@npendergrast @mark-prins Votes? 😆

**Comment by joshxg** [comment]
Think refused vaccines might not have `itemLines` or transactions with no trans lines

Would be good to know why the transactions have no item lines - maybe they refused so we could display that. Or the transaction has no trans lines, so they can be filtered out.

**Comment by katherine-sussol** [comment]
Hm interesting, I tried creating a few refused vaccines - I don't think any CIs/Transactions were generated, looks like it only creates a refusal NameNote?

Filtering out those with no `transLines` might be a good extra safety step (although the one on the Tonga server somehow got a `transLine` but no `itemLine`).

**Comment by joshxg** [comment]
Whoops my mistake!

Hmm.. what is the `type` on the `[trans_line]`? Believe `cash_in` and `cash_out` types won't have an `item_line`

**Comment by joshxg** [comment]
Just had a look at the data file- uh oh!

There are 22 `trans_line` records with an `item_line_ID` (that is NOT blank), but the actual `item_line` record does not exist.

Each of the 22 `trans_line` each have a unique `item_line_ID` - so each of the `item_line` "records" have one `trans_line`. Some of these are for the `DO NOT USE` items.

The 4d for a json dump : `ALERT(JSON Stringify(ds.trans_line.all().query("itemLine = null && item_line_ID # ''").toCollection("*, transact.*, item.*")))` (double click to select all in the alert and right click to copy).

The only thing I can think of is that the `item_line` records have been deleted through footrunner

**Comment by katherine-sussol** [comment]
That's worrying 🙀 , should we just skip those lines and pretend those transactions never happened? 🤣  At least then they'll be able to see the rest of their history (although it does feel a bit dodgy to be covering up a data error that way). 
Oh, we could also use the fancy new logger and just log the error when skipping?

**Comment by mark-prins** [comment]
> Could show transactions that don't have itemLines but leave blank fields where data is unavailable, (looks like it's just itemCode that wouldn't show) - (doesn't look as nice - but more accurate?)

I would head toward this sort of option: surface the problem rather than swallow the error. Just handle missing properties in the history display code. It does of course raise the visibility of the issue and therefore create more work for us, so there is a downside. The positive side is that is might lead us to fixing the source of the issue

**Comment by katherine-sussol** [comment]
Closed by #4281 (lines will still show but have 'N/A' in the item code where not available)

**Comment by ArpitaSussol** [comment]
@npendergrast hi Can you provide me Patient list please.

In general for other datafiles, Online patient history lookup is working fine.

**Comment by alainsussol** [comment]
@npendergrast 

Hi Nick,

Hope you are well. Would you be able to direct @ArpitaSussol to the right datafile to test this please. And possibly the name or code of a patient that experienced the issue.

Thanks a lot !!!

**Comment by npendergrast** [comment]
Hi @ArpitaSussol and @alainsussol,  really sorry about the delay I must have missed this one.

I've had a look over my past correspondence with the dev team, and it seems the patient which we were having the problem with is no longer in the current database for Tonga-vax (as Tonga has occasionally requested a cleanup of their database and deletion of patients that had not actually been vaccinated).
Not sure I can find a useful example now, but I will have a look to see if we have any copies of the datafile from that time lying around.

**Comment by alainsussol** [comment]
@npendergrast 

Thanks Nick !!!

**Comment by ArpitaSussol** [comment]
Closing this issue.
