### ISSUE TITLE
Lists appear to be continually sorted

### ISSUE THREAD

**Issue by andrew-d-uk** [openmsupply/mobile#422]
Build Number: 30

Description: If you are entering a stocktake, and you sort by the 'Actual Quantity' field, the list seems to refresh the sort on that field continually. So if you enter a new number into an actual quantity field, it sorts the list again causing the item you just entered to disappear off your screen to another place in the list. 

Reproducible:

Reproduction Steps:

Comments: This is potentially confusing for users, mainly because they want to check that the value they just entered was correct so have to search through the list for it. But I might guess it is also resource intensive as each time the field is updated mSupply sorts a list of perhaps 300 items?

**Comment by Chris-Petty** [comment]
Thanks Andrew,

This is a fair point, and a result of how we coded the sorting. I would suspect other tables do this also such as customer invoices or requisitions when changing the quantities.

It should take little time to sort on each update as the list should largely already be sorted, but still unnecessary over head as you point out!

**Comment by Chris-Petty** [comment]
Hi @arjunSussol As you concluded, the key solution is to not refresh the table when editing a cell. I think this is actually the standard for column sorting in other applications (likely for exactly the problems raised in this issue), but something not understood at the time of implementing react-native-generic-table-page

```javascript
              onEndEditing={(target, value) => {
                if (!this.props.onEndEditing) return;
                this.props.onEndEditing(column.key, target, value);
                this.refreshData();
              }}
```
https://github.com/sussol/react-native-generic-table-page/blob/master/index.js#L384-L388

Solution needs to revolve around "this.refreshData()" call here. Easy blunt fix is to remove that line. But that leaves a slight loose end, the sorting arrow on the column header will remain the same, even though the sort is no longer true. So something like the following may be a solution to that:

```javascript
              onEndEditing={(target, value) => {
                if (!this.props.onEndEditing) return;
                this.props.onEndEditing(column.key, target, value);
                if (column.key === this.state.sortBy) {
                  this.setState({ sortBy: '' });
                }
              }}
```

Dunno if that's enough, but I think that's the right direction.

**Comment by arjunSussol** [comment]
Andrei and Chris, I am also approaching same process, also recommended by Chris. After looking at this, I can conclude that only preventing sorting and refreshing on editable column is not  working because we are always refreshing Generic table via refreshData method: 
`<GenericPage
        data={data}
        refreshData={this.refreshData}`

So, we also need to stop sorting on this refreshData method during editing values on the editable columns.

**Comment by joshxg** [comment]
> ```js
>               onEndEditing={(target, value) => {
>                 if (!this.props.onEndEditing) return;
>                 this.props.onEndEditing(column.key, target, value);
>                 if (column.key === this.state.sortBy) {
>                   this.setState({ sortBy: '' });
>                 }
>               }}
> ```
> 
> Dunno if that's enough, but I think that's the right direction.

Hi @arjunSussol  !

[Only just had my first quick proper look at this component so take with a grain of salt]

I think this approach looks good. However `DataTable` re-renders look tightly coupled with a `DataSource` update. I think this would prevent the `DataTable` triggering a re-render from simply changing the `sortBy` variable (and subsequently the `HeaderCell`).

Could be a bit to hacky, but on top of Chris' suggestion, a clean way would be to pass `sortBy` as a prop to `DataTable` from `react-native-generic-table-page`:

```
  renderDataTable() {
    return (
      <DataTable
        sortBy={this.state.sortBy}
        refCallback={(reference) => (this.dataTableRef = reference)}
```
(https://github.com/sussol/react-native-generic-table-page/blob/d968c53d369f1f892f87931217f6ade601751793/index.js#L458-L469)
 
and change `shouldComponentUpdate` in `DataTable`:

```
  shouldComponentUpdate(props) {
    return this.props.dataSource !== props.dataSource || this.props !== props.sortBy;
  }
```
(https://github.com/sussol/react-native-data-table/blob/6b8e17e0465ee1e3b0d87c5b9b204aa34c1d081c/src/DataTable.js#L25-L27)

I can't see any negative side effects from this, and I can't think of a simpler way to trigger a re-render in `DataTable` to update the `HeaderCell` sorting icon.

@Chris-Petty Just as a note I think this highlights potentially bigger problems with this component than just using `ListView` over `FlatList`.

**Comment by Chris-Petty** [comment]
@joshxg You're probably right that the problem goes beyond FlatList - resorting the table can potentially cause a ton of re-renders anyway as highlighted here, not to mention sorting time itself. To get to the real roots some performance analysis would be nice - generally should be the starting point of any optimisation 😉 .

**Comment by Chris-Petty** [comment]
Current analysis is "it's slow as hell" hahaha.

**Comment by andreievg** [comment]
A few things to consider:
* Not all onEndEditing call call this.refreshData() directly, i.e. in CustomerInvoicePage this.refreshData is called via `DATA_TYPES_SYNCHRONISED` mechanism
* Some time we have to call this.refreshData (i.e. stocktake edit page, when counted quantity is changed, also the adjustment quantity changes (and needs to be re-rendered).

My suggestion:

When sorting by editable column, make sure to set `this.dataFilters.sortBy = ''` after this.setState in refreshData

**Comment by Chris-Petty** [comment]
That'd remove the sort direction after every refresh data, including if you just tried to sort it by a column.

**Comment by andreievg** [comment]
just for columns that are editable, i think it would work

**Comment by andreievg** [comment]
The only break there is if you search, after sorting by editable column, then search will be reset

**Comment by andreievg** [comment]
Sorry It's a bit more involved, there is always a search filter on table, default one is defined in pages constructor. If we do this.dataFilters.sortBy = '', it would break the app in sortDataBy.

**Comment by andreievg** [comment]
We can set `this.dataFilters.sortBy = null`, and in sortDataBy, if sortBy is null, just return data.

In my opinion we need to refactor search functionality, too many repeats. i.e. 
```

    // We use != null, which checks for both null or undefined (undefined coerces to null)
    if (newSearchTerm != null) this.dataFilters.searchTerm = newSearchTerm;
    if (newSortBy != null) this.dataFilters.sortBy = newSortBy;
    if (newIsAscending != null) this.dataFilters.isAscending = newIsAscending;
  }
....

    this.setState({
      data: sortDataBy(data, sortBy, sortDataType, isAscending),
    });
```
this is repeated in every page.

@arjunSussol if you can come up with generic way of doing this i.e. maybe in GenericPage.js, I think this issues scope can be broadened to accomodate such a refactor (don't have to though)

**Comment by joshxg** [comment]
This is being completed with the new Data table rewrite #1043, going to close this
