### ISSUE TITLE
Additional COVID-19 vaccination dispensing fields for Kiribati

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4228]
## Is your feature request related to a problem? Please describe.

Kiribati / WHO have requested additional fields to be captured during the COVID-19 vaccination dispensing process. 

I know @katherine-sussol has been working on adding an additional intermediary page to the workflow. 

These are the fields that Kiribati / WHO require to be added to that page: 

| Field label | Field Type| Prepopulate value |
| --- | --- | --- |
| Country of Vaccination | Dropdown (Kiribati) | Kiribati|
| Island of Vaccination | Dropdown (TBD) | -
| District of Vaccination | Dropdown (Central, Linnix, Northern, South Eastern, South Western, Tarawa & Banaba) | -
| Administering Health Facility Name | Alphanumeric | -
| Anatomical Site | Dropdown (Left arm, Right arm) | -
| Dose Number | Dropdown (First, Second) | -
| Informed Consent Received | Toggle (Yes, No) | No
| Reason for Non-consent | Alphanumeric | -
| Exempted from Vaccination? | Toggle (Yes, No) | No
| Reason for Exemption | Alphanumeric | -
| Additional notes | Alphanumeric | -

## Describe the solution you'd like

The fields above added to the new page :)

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by katherine-sussol** [comment]
🥳   Aside from Additional notes, should we mark the rest as mandatory fields?
I think maybe if Informed Consent = No or Exempted = Yes, then Reason for Exemption / Non-consent should be mandatory?

**Comment by adamdewey** [comment]
Hey Kat! 

Sorry, I wasn't clear here in the requirements. I've actually just separated those and added a reason field for each to make it easier to implement. 

I think we should make the exemption reason mandatory but the non-consent one not mandatory as the patient might just not give an answer?

**Comment by katherine-sussol** [comment]
https://user-images.githubusercontent.com/65875762/125391574-d6cbb100-e3f8-11eb-9542-396085072bdc.mp4

Sample JSON Schema to create the above (renamed to .txt so it could be attached 🤣 ):
[testKiribatiJsonSchema.txt](https://github.com/openmsupply/mobile/files/6805941/testKiribatiJsonSchema.txt)

Sample UI Schema:
[testKiribatiUiSchema.txt](https://github.com/openmsupply/mobile/files/6805942/testKiribatiUiSchema.txt)

**Comment by joshxg** [comment]
Can this be closed? 🤔

**Comment by adamdewey** [comment]
From my pov yes :)
