### ISSUE TITLE
Show the patients age next to the DOB on the patient edit/create form

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4232]
## Is your feature request related to a problem? Please describe.

Similar to desktop with an age and dob field next to each other:

![image](https://user-images.githubusercontent.com/35858975/125540049-751e6b2c-4510-4853-8423-a3c849cf404f.png)

## Describe the solution you'd like

Two fields next to each other. If you edit one, it updates the other.

## Implementation

- This is probably more annoying than it might seem and may be easier to implement by just showing the age rather than having the age be editable

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by katherine-sussol** [comment]
This one has been brought up before https://github.com/openmsupply/mobile/issues/3324 (and then IC also requested it although apparently, we're not doing customisations for them anymore? 🤷 ). 

That aside 😕 , it sounds like the driving factor is people not knowing their age so maybe it's important to be able to edit the field? (though it does sound super annoying :/)

**Comment by joshxg** [comment]
Ah thanks! 

Yeah I agree. Will have to see when implementing how painful it is to actually do might turn out to be super easy... (tui?)

**Comment by joshxg** [comment]
Just having a quick look - On top of the dependency of data between the two inputs, there is the added complication of layouts. The `Control` component just renders the `Input` components in a column.

Think i'll just make a new form control for DOB's - should make it easier

**Comment by ArpitaSussol** [comment]
Tested in mSupply v8.2.0- rc2

## Testing

- [x] When editing a patient, can edit the age or dob
