### ISSUE TITLE
Vaccine dispensing: Refusal comment area

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4234]
## Is your feature request related to a problem? Please describe.

When refusing a vaccine, offer the user the ability to add a comment/reason for the refusal.

## Describe the solution you'd like

- When the `refuse` checkbox is checked, turn the item select area to a text input.
- Allow the user to enter a reason/comment

## Implementation
- Save the comment/reason against the refusal name note

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by ArpitaSussol** [comment]
@mark-prins where the refusal note will be saved ? in Name_note table or anywhere else ??

**Comment by mark-prins** [comment]
yes, saves as text in the `[name_note]` table - so you can actually see the reason in desktop ( unlike the JSON objects.. )

**Comment by katherine-sussol** [comment]
Updated public docs to cover the 'reason for refusal' text field: https://docs.msupply.foundation/en:mobile:user_guide:vaccine_dispensing#refused_vaccinations

**Comment by ArpitaSussol** [comment]
@mark-prins 
name_note for refused vaccines is no seen anywhere in Server.

I created patient event as "RV" in server.

https://user-images.githubusercontent.com/58979436/130742782-4e9c60d1-2a1e-4921-a33b-cd0970dada39.mp4

https://recordit.co/EoJIEoDwn5

**Comment by joshxg** [comment]
Sorry @ArpitaSussol this has changed now and so there is no RV name note made.. now, if you have a patient_event for `vaccination`, then everytime, refused or not, there should be one, and if the person refused, it should have `refused: true`

**Comment by ArpitaSussol** [comment]
> Sorry @ArpitaSussol this has changed now and so there is no RV name note made.. now, if you have a patient_event for `vaccination`, then everytime, refused or not, there should be one, and if the person refused, it should have `refused: true`

okay so where can i check `refused: true`? [table name] and 
should have to create patient event for vaccination or not?

**Comment by joshxg** [comment]
Yes please.
- create a `[patient_event]` for `vaccination`, not `RV`.
- Can check `refused:true` in the `[name_note]data` .. which will have to be in record browser

**Comment by ArpitaSussol** [comment]
> Yes please.
> 
> * create a `[patient_event]` for `vaccination`, not `RV`.
> * Can check `refused:true` in the `[name_note]data` .. which will have to be in record browser

Code and Description is same here ? 
![Screenshot 2021-08-25 at 1 39 11 pm](https://user-images.githubusercontent.com/58979436/130750273-78907784-8ecd-4d6b-bf51-a88800bbc6db.jpg)

**Comment by joshxg** [comment]
@ArpitaSussol Yup!

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] create a `[patient_event]` for `vaccination`
- [x] Can check `refused:true` in the `[name_note]data` in record browser
