### ISSUE TITLE
Seeded supplementary data is invalid as initial state

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4237]
## Describe the bug

When prescribing to a patient the second+ time such that their supplementary data is pre-filled, the form is invalid when it should be valid.

### To reproduce

1. Go to fill out supplementary data for a patient and finalise the prescription
2. Click on the patient again
3. Scroll down to the third step and try to proceed without touching the form (which is pre-filled and technically valid)

### Expected behaviour

Should be able to just 'next' if the form is pre-filled

### Proposed Solution

Getting pretty messy! I remember having to spend a bit of time on this for the patient survey. At a basic level, we need to run validation on the pre-filled form after we have found it and set the `isValid` state to the result

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by katherine-sussol** [comment]
Oh fail 😿 . I think the initial `isValid` state is being set correctly to the result but something is resetting it to false somewhere down the line...will take a look 👀

**Comment by katherine-sussol** [comment]
Superseded by #4269 (... for now)
