### ISSUE TITLE
Support for arrays in JSONForm

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4248]
## Is your feature request related to a problem? Please describe.

Currently we don't support array types in the JSONForm. Would be good to.

## Describe the solution you'd like

Implement `ArrayFieldTemplate` for `JSONForm`

## Implementation

Should just be able to return the array of components passed to `ArrayFieldTemplate`

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by ArpitaSussol** [comment]
@katherine-sussol can you help with test cases for this? is this testable from final end or not?
