### ISSUE TITLE
Search name is not working properly

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4251]
## Describe the bug

While searching for full name shows nothing in the list.

### To reproduce

Steps to reproduce the behaviour:

1. Go to Customer requisition/Supplier requisition.
2. Type any name from the list.
3. See an error

### Expected behaviour

Should work like item search.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:808
- Tablet model: tried in the emulator(8.1)

### Additional context

![photo_2021-07-16 11 54 27](https://user-images.githubusercontent.com/18479204/125901225-2299e3ed-7c63-4bf5-9b94-6d30e711f1dc.jpeg)
![photo_2021-07-16 11 54 23](https://user-images.githubusercontent.com/18479204/125901230-16b6080d-0f47-47ed-9a0c-8eecbfbc7290.jpeg)

**Comment by ArpitaSussol** [comment]
Tested in V8.2.1

## Testing

- [x] Can search for a customer/supplier by name in the `ByProgramModal`
