### ISSUE TITLE
On install/update shows incorrect version number

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#426]
Version Number: v1.1.1

Description: Version number not set correctly. Will show `v1.1.0` when updating to v1.1.1, or `v` on fresh install.

Reproducible: yes

Reproduction Steps: Uninstall app, install app, will show `v` for version on initialisation page

Comments: After first attempt to sync connect to server, the app version will update to correct value.

**Comment by Chris-Petty** [comment]
Related to #1455

**Comment by katherine-sussol** [comment]
Hmm, this one looks like the function `migrateDataToVersion` (which sets the current version number to AsyncStorage when the app starts up) hasn't finished running before the `FirstUsePage` or the `LoginModal` tries to read it from AsyncStorage.

Not sure what a proper fix is here... could we set something saying that data is still being migrated, and then update the footer version thingy once it's complete? Would that look a little weird 🤔 ?

**Comment by Chris-Petty** [comment]
Not sure why this never occurred to me before, but could it just read the package.json version number?

**Comment by katherine-sussol** [comment]
Ohh ... yeah that's a lot simpler and basically where the migration code is getting it from anyway 🤣

**Comment by katherine-sussol** [comment]
Closed by #4049
