### ISSUE TITLE
Remote non vaccinations showing up in patient vaccine history

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4263]
## Describe the bug

Regular dispensing transactions are showing up in the vaccine patient history modal

### To reproduce

Steps to reproduce the behaviour:

1. Log in to a store with vaccine dispensing enabled and view dispensing history from all stores pref enabled
2. Dispense a non-vaccine to a patient 
3. Login to a different store, find the patient remotely, navigate to Vaccine Dispensing and complete the flow until the final (vaccine select) page, tap the patient history button
4. Observe the remote non-vaccine transaction showing up in the history

### Expected behaviour

Expected to only see vaccinations

### Proposed Solution
Fix the noob rename done as part of https://github.com/openmsupply/mobile/issues/4203

### Version and device info

- App version: 8.2.0-rc1
- Tablet model: Any
- OS version: Any

### Additional context
None

**Comment by ArpitaSussol** [comment]
Tested in V8.2.1

## Testing

- [x] Log in to a store with vaccine dispensing enabled and view dispensing history from all stores pref enabled
- [x] Dispense a non-vaccine to a patient
- [x] Login to a different store, find the patient remotely, navigate to Vaccine Dispensing and complete the flow until the final (vaccine select) page, tap the patient history button
- [x] Observe the remote non-vaccine transaction is not showing up in the history
