### ISSUE TITLE
Patient address is not retained

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4266]
## Describe the bug

When editing the address fields of a patient the values are not retained

### To reproduce

Steps to reproduce the behaviour:

1. Go to Dispensing and edit a patient
2. Enter values for address one and address two
3. Save and edit the patient again

### Expected behaviour

The values should save..
Also, when looking up a remote patient, the values should come through correctly.
Should work for prescribers too.

**Comment by ArpitaSussol** [comment]
Tested in V8.2.1

@mark-prins if i edit a patient whose Address fields are empty, then this flow works fine.

https://user-images.githubusercontent.com/58979436/127636793-b4302dc7-73d0-4a85-a3f3-7761926b2338.mp4

But if i edit a patient where address fields are already present, update it and search using Lookup then it doesn't update the address field.

https://user-images.githubusercontent.com/58979436/127636928-0a11d172-2474-48aa-a216-a81dd0f2867a.mp4

**Comment by mark-prins** [comment]
Hi @ArpitaSussol - that's just because the changes haven't synchronised to the server yet. When you do a lookup of the patient it is going to fetch the address which is stored on the server, and update the local patient to match that.

If you do a manual sync after updating the patient, then the address changes show correctly after lookup.

**Comment by ArpitaSussol** [comment]
> Hi @ArpitaSussol - that's just because the changes haven't synchronised to the server yet. When you do a lookup of the patient it is going to fetch the address which is stored on the server, and update the local patient to match that.
> 
> If you do a manual sync after updating the patient, then the address changes show correctly after lookup.

okay will check it :). Thanks

**Comment by ArpitaSussol** [comment]
Tested in V8.2.1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Edit a patient address and save and check again
- [x] Lookup a patient (which has an address 1&2 entered) and check the address arrives
- [x] Edit and save the looked up patient and check the server
- [x] Edit a patient record through the vaccination process
- [x] Prescribers too?
