### ISSUE TITLE
New column for vaccination history

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4297]
## Is your feature request related to a problem? Please describe.

Display the name notes created here: https://github.com/openmsupply/mobile/issues/4296 in the vaccination step 1 page.

## Describe the solution you'd like

Just display the name notes of patient event `🤷 ` in the table?

## Implementation

Unsure- I think there might be an issue with receiving all the name notes from the patient api

## Describe alternatives you've considered

- Showing this detail in the current `patient history` modal. Users want to see this in step1, and also might be too cluttered?

## Additional context
- https://github.com/sussol/msupply/issues/9253
- Might be an issue for historic users - what about tonga? Will they just have the column and not show any details? 🤔

**Comment by mark-prins** [comment]
perhaps a column which has a button which opens a modal to show history - with the button only showing if there are notes ( and the column only showing if.. this isn't Tonga? ) the button text could be the number of notes available?
