### ISSUE TITLE
Can't enter patient details in 'Add manual entry' screen of webform ADR 

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4299]
## Describe the bug

The webform ADR has a screen to allow the user to enter a patient's basic details manually so the ADR can later be matched up to a patient record. 

Currently the user is unable to enter these details - the screen does not allow typing. 

### To reproduce

Steps to reproduce the behaviour:

1. Go to https://kiribati-vax-training.msupply.org:2048/patient_hub/index.html#/adverse-drug-reactions
2. Attempt to type text in any of the fields. 

![image](https://user-images.githubusercontent.com/19318937/127074107-0bbe92c6-ee3e-4c4a-9fa0-075eae16507e.png)

![image](https://user-images.githubusercontent.com/19318937/127074119-5fe463b5-ab72-4bf3-ada9-56c321fab3a9.png)

### Expected behaviour

Boxes accept text. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version: mSupply V5-03-01

**Comment by joshxg** [comment]
Moved here: https://github.com/openmsupply/patient-hub/issues/116

**Comment by adamdewey** [comment]
Oops, sorry my bad!
