### ISSUE TITLE
24 hour vaccination confirm modal gets stuck open

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4302]
## Describe the bug

This modal

![image](https://user-images.githubusercontent.com/35858975/127242448-4833081e-09b4-4bca-b03f-fe28eb15fac0.png)

Should close when you click confirm, before, the spinner starts to spin, otherwise it stays open, blocking the spinner and is very confusing.

Additionally, it gives more opportunity to spam click confirm, then the app tries to create multiple prescriptions

### To reproduce

1. Go to finalise a second prescription for a user within 24 hours
2. Click on confirm

1. Go to finalise a second prescription for a user within 24 hours
2. Click on confirm twice

### Expected behaviour

Close the modal before the spinner starts. Debounce the confirm

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in v8.2.1

## Testing

- [x] Issue a vaccine to a patient the second time. When confirming on the modal, the modal doesn't block the spinner
