### ISSUE TITLE
Patient Age is being rounded up, should be rounded down

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4327]
## Describe the bug

It seems that we are rounding a patient's age up, whereas in real life it's more common to round the age down (at least, in my experience!)

If we leave it rounding up then patients are going to ask nurses to change their age every time they try to confirm the patient's details during vaccination rollouts. 

### To reproduce

Steps to reproduce the behaviour:

1. Import patient from spreadsheet (inlcuding date of birth)
2. Check patient age in Desktop
3. Compare patient age in Mobile

![image](https://user-images.githubusercontent.com/19318937/127923154-eccdbd52-c236-4a00-92af-03ccb7c1d058.png)

![2021-08-03_08-48-32](https://user-images.githubusercontent.com/19318937/127922902-acb252ea-a4d4-441e-9a5d-5c31ea768b86.png)

![image](https://user-images.githubusercontent.com/19318937/127923339-e2b455de-d793-45d3-aacb-6073a3ce5582.png)

### Expected behaviour

Mobile to round the age down. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.2.1
- Tablet model:
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in V8.2.2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Set the date of birth to `25/08/1997` for a patient and check the age. Should be `23`
