### ISSUE TITLE
Female patients are being displayed as males

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4328]
## Describe the bug

Female patients that were imported into mSupply are showing as male in Mobile for some reason. 

### To reproduce

Steps to reproduce the behaviour:

1. Import patients from spreadsheet
2. Look at patient gender in Desktop / Record browser
3. Compare patient gender in Mobile.

![image](https://user-images.githubusercontent.com/19318937/127923956-98fef2dd-2f56-43ba-8491-583e247303f9.png)

![image](https://user-images.githubusercontent.com/19318937/127923985-cf33b5cd-5cd3-4a9d-91b6-cfd0c09f4b28.png)

![image](https://user-images.githubusercontent.com/19318937/127923999-faeb0be0-139f-4581-ac18-767d834d17bc.png)

### Expected behaviour

Females to be displayed as female. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.2.1
- Tablet model:
- OS version:

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Turn off the pref `new_patients_visible_in_this_store_only` for your mobile store. create a female patient in another store and sync on the tablet. Check the gender of the patient on the tablet
