### ISSUE TITLE
Patient Date of birth is still being saved as a day earlier than what is being entered in Mobile

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/mobile#4334]
## Describe the bug

Tonga/BES has reported that DOB is still saving as one day incorrect. Saves birthday as a day earlier than the actual day.

We thought this had been fixed previously by changing the Timezone settings on the server: https://github.com/openmsupply/mobile/issues/3838

### To reproduce

Steps to reproduce the behaviour:

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.1.1-rc
- Tablet model: Lenovo TB-X304L
- OS version: 8.1

**Comment by katherine-sussol** [comment]
I just reproduced this locally when creating a new patient -> syncing -> uninstall -> reinitialise tablet

Think it is because when it gets synced to the server it is being converted to a NZT/locally timezoned date rather than ISO formatted date.

**Comment by katherine-sussol** [comment]
Hopefully (🤞 ?) closed with #4404, available in a release after 8.3.0-rc0

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Edit a patient's DOB (or create a new patient), sync to the server and check the patient's DOB on the server. The date should be the same as what was entered in the mobile UI
