### ISSUE TITLE
Inconsistent use of date formatting

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4348]
## Describe the bug

The date fields based on JSON schemas are rendering in the format ```yyyy-mm-dd``` in the Mobile UI

However elsewhere (non-JSON fields in Mobile, webform fields in Patient Hub) we are rendering date fields in the format ```dd/mm/yyyy```

This is causing issues with validation, especially as the Mobile ADR and the Patient Hub ADR are using the same JSON schema:

1. Patient Hub ADR
<img width="1407" alt="2021-08-10_12-28-11" src="https://user-images.githubusercontent.com/19318937/128791849-46715b14-2c86-4073-a288-c2de4ebd52a3.png">

2. Mobile ADR (note validation error)
<img width="1280" alt="2021-08-10_12-26-55" src="https://user-images.githubusercontent.com/19318937/128791852-b86c78b4-17df-4a11-a53c-4576b028bd23.png">

3. Inconsistent date format within Mobile: 
<img width="1280" alt="2021-08-10_12-34-30" src="https://user-images.githubusercontent.com/19318937/128791911-453376bc-c165-4af7-858c-b6a160af7da7.png">

### To reproduce

Steps to reproduce the behaviour:

1. Enable Vaccination module and populate an ADR JSON schema containing a date field into form_schema
2. Enter a date into Mobile ADR form
3. Enter a date in Patient Hub ADR form
4. Compare the difference
5. Also compare date format between Mobile Date of Birth field and Mobile JSON-based field

### Expected behaviour

Date formating to be consistent throughout our seamless ecosystem. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.2.2
- Tablet model: Lenovo TB X505F
- OS version:

### Additional context

JSON schema used: 

```"
date": {
					"title": "Reporting date",
					"type": "string",
					"pattern": "^(0?[1-9]|[12][0-9]|3[01])([-]|[/])(0?[1-9]|1[012])([-]|[/])\\d{4}$",
					"errorMessage": "Please enter a date in the format dd/mm/yyyy, for example 13/12/1989"
				},
```

JSON schema-UI used: 

```
"reporter": {
		"date": {
			"ui:widget": "DateWidget"
		},
```

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Repro #4348, date formats should be consistent across all areas of mobile.
