### ISSUE TITLE
Tonga: require a solution for vaccinating in the outer islands where they will not have regular internet access

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/mobile#4369]
## Is your feature request related to a problem? Please describe.

Tonga has advised that in **October** they will be starting the second dose of vaccinations in the outer islands. These outer islands do not have very stable internet access and so a lot of the time the tablets will need to work in offline mode.

## Describe the solution you'd like

They would like to be able to download all patients and their previous transactions to specific tablets so that they can search for previous patient vaccinations when dispensing second vaccinations.

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by Chris-Petty** [comment]
@mark-prins ta! Yea this is sounding a little like the Kiribati vax requirements... the changes that allow this aren't quite in master (https://github.com/sussol/msupply/pull/9459), but should be before October! Got a few issues raised by testers to address.

Given the above, yup that pref being turned **off** (and making sure the store mode is dispensary, which they must be already I think?) would cause all patients and all their notes to sync to all sites, indeed by making name_store_joins. Then you need footrunners (run before or after changing the pref, wouldn't matter I think) as you said and you'd be set...

But, how many patients are there? Can be a bit of a sync explosion which isn't good if their internet is bad to begin with! Catch 22 huh?

**Comment by mark-prins** [comment]
spot on, thanks @Chris-Petty!
I was thinking that we'd limit the sync explosion by only enabling this on a couple of stores, but on re-reading the issue it sounds like the whole team would be heading out. Currently 46,197 patients and 52 dispensary stores === 💥??
2.3 million name records alone, and then 3+ name notes per person too.
Other thought was to drip feed the creation of the name note vaccination records - not create them all at once

**Comment by npendergrast** [comment]
Hi @Chris-Petty and @mark-prins, the request from Tonga was actually for specific tablets to receive all patients/records, rather than every tablet, as only a few tablets will be going to the smaller outer islands at a time (sorry I should have put that detail in the issue). They weren't keen on all tablets having all patients.

But if pushing all patients to specific tablets for Tonga will be too complicated they may just need to settle for looking up all the patients they expect to visit on the outer islands for dose 2 while each of those tablets still has internet.

**Comment by mark-prins** [comment]
Sounds like the 'sync everywhere' option will work ok then, if there are limited numbers of tablets. That's what I had assumed, so you must have mentioned that at some point :)
