### ISSUE TITLE
Keyboard not vanishing when tapping on all parts of screen

### ISSUE THREAD

**Issue by sinclairsystems** [openmsupply/mobile#437]
Build Number:1.1.3

Description: When performing a stock take and manually entering count values. If you tap on a existing input field the keyboard will vanish but if you click elsewhere e.g above the main table it will not

Reproducible: yes
![msupplymobileissuephoto]
(https://user-images.githubusercontent.com/13606681/28298687-d36b7b32-6bc8-11e7-9984-27abbea4831f.jpg)

Reproduction Steps:
after entering a stock count number try closing the keyboard by tapping in the space above the table but outside another input field

Comments:
Low priority as this also occurs in previous versions

**Comment by joshxg** [comment]
Being fixed with #1043

**Comment by joshxg** [comment]
oops i lie no it isnt

**Comment by joshxg** [comment]
yes it is, kind of
