### ISSUE TITLE
Cannot get through the URL validation locally

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#4383]
## Describe the bug

Setup a local server on a Laptop with some client datafile, Even when the local IP can be access from Tablet, Passing the same URL on mobile, always says - Cannot connect.

![Screenshot 2021-08-27 at 13 18 38](https://user-images.githubusercontent.com/13144882/131093960-ebf6bd36-2ea1-46c2-9808-f84a2952a5d2.png)

![photo_2021-08-27_13-23-22](https://user-images.githubusercontent.com/13144882/131093998-0e44c031-2048-4872-a321-c971ad611e80.jpg)

### To reproduce

Steps to reproduce the behaviour:

1. Start local server on Laptop and start the local webserver
2. Start the Mobile app
3. From the first screen Put your local IP and with sites details
4. Tap Login
5. It will always says: Cannot connect to server

### Expected behaviour

IDK considering 5.1.1 or 5.1.2 - Doing the same work flow , it connect just fine.
I do not know what is happening or is a new change on 8_2_3 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8_2_3 
- Tablet model: SM-T515
- OS version: Android 9

**Comment by mark-prins** [comment]
I follow the same steps with my laptop and don't have the same issue, so it's hard to say based on what you have here.
Would you mind trying the [RC release of 8.3.0](https://github.com/openmsupply/mobile/releases/tag/v8.3.0-rc0) - I put a change into the `develop` branch which gives more information than just 'Cannot connect' 

If that doesn't show something helpful, then using the `develop` branch will allow you to intercept the server response more easily, so have a go with that version. I can show you where to hook in to the error response.. though I expect you'll find it easily enough.

**Comment by bijaySussol** [comment]
This was a Android restriction shared to team and i think this is fixed already
Can be closed !
