### ISSUE TITLE
Items not showing when dispensing to patients

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4394]
## Describe the bug

Items not showing! When dispensing. 

Works ok for me in 8.2.3 but in 8.3.0 the items just don't show. 

![photo_2021-09-01 21 49 44](https://user-images.githubusercontent.com/19318937/131650756-12275d19-1a40-4f8c-a2a7-b68d15a2c893.jpeg)

### To reproduce

Steps to reproduce the behaviour:

1. Go to Dispensing module
2. Select a patient to dispense to. 

### Expected behaviour

Items should show. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:  8.3.0-rc0
- Tablet model: Lenovo TB-X505N
- OS version: Android 10

**Comment by mark-prins** [comment]
Issue showed initially after first logging in to the store, then reloaded the app after adding logging to test and all items showed.

**Comment by katherine-sussol** [comment]
I saw this again today 🙀 (and also got asked about it again today coincidentally 😆). The items magically reappeared and failed to re-disappear after reloading the app. Seems to happen consistently after the first-time initialisation of the app...

**Comment by katherine-sussol** [comment]
Closed by #4750
