### ISSUE TITLE
Built in reports/dashboard from synced reports and feedback to the user

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#441]
Description:  
Mobile users would appreciate feedback on how the app is serving them. This should likely be in the form of a dashboard with some basic reports/charts.

Suggestions:
- Item consumption charts/tables (potentially useful for auditors)
- Item stock level charts
- Number of patients/invoices
- Items with low stock/near expiring stock
- Time since last stock take (and button to navigate to that stocktake)
- Current stock inbound from suppliers
- Current stock requested in requisitions

Perhaps a new DB table storing these calculated reports so that temporal information is readily available. This may be similar to what is already implemented in mSupply, so may be worth investigating that to see what can align and be synced.

Comments:
Talk to clients and consultants about what features in this area would benefit them the most. All of this should have a solid design (Open in the public forum) before implementation.

**Comment by andreievg** [comment]
To summarise our discussion yesterday:

We decided to add a new table to mSupply that will sync to mobile site. 

| Field          |Type                        
|----------------|--------------------------------------------|
|ID              | Text UUID                                  |
|storeID         | Text UUID                                  |
|data            | json                                       |
|reportID        | Text UUID (FK to dashboard_report.ID       |
|type            | Text                                       | 
|title           | Text                                       |
|tabName         | Text (optional)                            |

This should be enough to display synced dashboards report in mobile. json data field will be in the same format as current web dashboard.

TODO add link to mSupply Desktop issue
