### ISSUE TITLE
Customer Requisition: on entering value in input field of requisition shows ambiguous behavior

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#4416]
## Describe the bug

In Customer Requisition, on entering value in input field of requisition shows ambiguous behavior. Keep showing value 0 in the input field and once the focus is out , the given field shows last entered value.

### To reproduce

Steps to reproduce the behaviour:

1. Go to Customer Requisition
2. Click on New Requisition or Click on any existing current requisition
3. Enter value in any of the field.
4. See error. Field keep reverting to 0 unless focus is out from it.

https://user-images.githubusercontent.com/58979436/132630151-f02679d8-6e7f-4b0c-85af-4c4d11344b36.mp4

### Expected behaviour

Value should be shown at the time of input.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.3.0-rc0
- Tablet model: Samsung
- OS version: 8.1

### Additional context

While going through general flow of Customer Requisition with @ujwalSussol Sir, found this behavior of input field. 
This scenario is not replicable in Customer Invoice or Supplier Invoice or Supplier Requisition.

**Comment by katherine-sussol** [comment]
Have replicated in 8.3.0-rc0 and 8.2.3, seems to happen with all columns on this page 😄  will take a look.

**Comment by katherine-sussol** [comment]
Closed by #4420 for 8.3.0

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Follow the steps in the original issue reported (#4416) - row values should update immediately on edit and not require the user to unfocus the row
