### ISSUE TITLE
Trim trailing '/' characters when entering sync url into mobile

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4424]
## Is your feature request related to a problem? Please describe.

When there are trailing '/' characters at the end of an otherwise valid URL, sync will fail because mobile con🐱enates this URL with `/sync/version/endpoint/`, doubling up the '/' characters.

See https://github.com/sussol/msupply/issues/9614 for related issue raised in Desktop.

## Describe the solution you'd like

Trim the trailing '/' characters before saving the sync url (which can currently be entered on the initialisation screen or settings screen)

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

- Throwing invalid url error message (though this specific case is for when URLs are valid but just have an extra '/' at the end)
- Leaving the mess for desktop to deal with (think there is already a workaround being put in Desktop, but still better practice to clean up client behaviour too)

## Additional context
We already have #276 for general URL validation, this is a more specific use-case within that.

**Comment by ArpitaSussol** [comment]
Tested in v8.3.0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Set up (on the initialise or settings page) a URL ending with '/', e.g. `http://192.168.1.158:5000/` when saved, sync/login should still work
