### ISSUE TITLE
Fix linting errors in develop 

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4456]
## Is your feature request related to a problem? Please describe.
Run:
`yarn eslint src`

See output:
![image](https://user-images.githubusercontent.com/65875762/138371979-30459d73-f7ee-413a-b7ed-f5ee86416f78.png)

## Describe the solution you'd like

Ideally should have no linting errors when cloning the repo, so it's easier to identify problems caused by local changes.

## Implementation

TBD

## Describe alternatives you've considered

Not fixing

## Additional context

N/A

**Comment by joshxg** [comment]
I wonder if we should revert adding typescript. I already regret it

**Comment by katherine-sussol** [comment]
Hrm yeah, the amount of cascading changes required when converting a file is annoying... although I think maybe we just need some kind of rule like don't convert a file unless incorporating all the necessary linked changes (or no `--no-verify` when committing? 🤣)  But then I guess that discourages people from trying and then having TS will not be very useful anyway and then we may as well not have done it...🤔
