### ISSUE TITLE
Update French 🇫🇷  translations in mobile

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4479]
## Is your feature request related to a problem? Please describe.

Demo for UNFPA in French is happening and it's been noted that some translated strings need updating for various reasons.

## Describe the solution you'd like

Updated json files with translations (courtesy of Richard).

## Implementation

Import from updated spreadsheet @ https://docs.google.com/spreadsheets/d/1yNEwvHbq__1GWCw7Bul-dnqnnPINVa2CbNcCYg-zOFE/edit#gid=1174361042

## Describe alternatives you've considered

Leaving as is and outing ourselves with bad French? 🤔 

## Additional context

N/A

**Comment by nisha-dangol** [comment]
## Testing
tested in mobile v8.5.0-rc1

- [ ] Select French as the language for the app, browse around app and confirm the text makes sense (probably easier if one understands French) and check text isn't cut off on any buttons or labels.

I actually found some places that are missing French translations: 
![Screenshot_2022-05-23-13-43-30-550](https://user-images.githubusercontent.com/59193490/169773922-f0926150-abd9-4bc0-9893-3f877ae627f3.jpeg)
![Screenshot_2022-05-23-13-43-58-220](https://user-images.githubusercontent.com/59193490/169773940-5b49ee76-c3a7-471c-83b9-66e94ddd1a8b.jpeg)
![Screenshot_2022-05-23-13-42-12-737](https://user-images.githubusercontent.com/59193490/169773950-3426ff7b-8a29-4911-89b2-2884a5b4f9f9.jpeg)
![Screenshot_2022-05-23-13-45-57-654](https://user-images.githubusercontent.com/59193490/169773955-f408de24-01b5-446c-8d90-891d87475535.jpeg)
Created issue [here](https://github.com/openmsupply/mobile/issues/4725)
