### ISSUE TITLE
Password placeholder string doesn't update when the language is changed

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4485]
## Describe the bug

https://user-images.githubusercontent.com/65875762/139754665-09ec76d3-d60a-4692-baba-b8579c02bbb8.mp4

### To reproduce

Steps to reproduce the behaviour:

1. Login to the app
2. Change the language
3. Observe the password placeholder text

### Expected behaviour

Expected the placeholder text to update

### Version and device info

- App version: 8.3.0
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

**Comment by katherine-sussol** [comment]
Closed by #4507

**Comment by ArpitaSussol** [comment]
Tested in v8.4.0-rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Navigate to login page and swap languages, the password placeholder should update to the language selected
