### ISSUE TITLE
Kiribati: Updating patient first/last name in Vaccination Module does not update full name

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4516]
## Describe the bug

This was reported by Teani in Kiribati. 

If a user edits a patient's first / last name in the Vaccination Module the full name is not updated in mSupply Desktop. 

i.e. an edit to `name.last` is not reflected in `name.name`

### To reproduce

Steps to reproduce the behaviour:

1. Go to the Vaccination Module
2. Search for a patient and enter their record
3. Edit their last name and go through the vaccination process to administer a vaccine. 
4. Search for the patient under the new last name
5. Open their vaccination history
6. Note the name at the top of the page is displaying the old last name

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.2.2
- Tablet model: Lenonvo Tab
- OS version: Android 10

**Comment by katherine-sussol** [comment]
Where is the cry emoji reaction on issues 🤣  ... I'll squeeze it into an 8.4.0 RC.

**Comment by katherine-sussol** [comment]
Closed by #4517 (candidate for 8.4.0-rc2)

**Comment by ArpitaSussol** [comment]
Tested in v8.4.0-rc2

### Testing

- [x] Go to the Vaccination Module
- [x] Search for a patient and enter their record
- [x] Edit their last name and go through the vaccination process to administer a vaccine.
- [x] Search for the patient under the new last name
- [x] Open their vaccination history
- [x] Note the name at the top of the page is displaying the latest updated last name
