### ISSUE TITLE
Missing consecutive breaches when there is a current cumulative breach in progress

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4549]
## Describe the bug

Consecutive breaches aren't being recorded if there is a pre-existing cumulative breach that hasn't yet been 'closed' e.g:
![image](https://user-images.githubusercontent.com/65875762/148327149-fe05b0a7-3645-4382-8579-7dcbcd2f050c.png)
NB: Red box in screenshot is wrong -> hot breaches are to the right of 'average temperature' (accidentally highlighted the cold consecutive breach card)

The app is incorrectly recording a HOT_CUMULATIVE breach in the DB. The DB is supposed to only hold consecutive breaches.
![image](https://user-images.githubusercontent.com/65875762/148327562-a3353cf3-3c68-4423-a2f7-d3160e638ab1.png)

### To reproduce

Steps to reproduce the behaviour:

1. Set up a HOT_CUMULATIVE breach config that that will trigger soon-is (e.g. max 8 degrees, 2min duration, when it's 26 degrees where the sensor is)
2. Set up a breach config such that a HOT_CONSECUTIVE breach will be created, but AFTER the cumulative breach (e.g. max 8 degrees, 20min duration)
3. Wait for 20min
4. See error (we would expect a hot consecutive breach after 20min above the threshold....but there isn't 😭 )

### Expected behaviour
Cumulative and Consecutive breach calculations should be separate

### Proposed Solution
Think this line: https://github.com/openmsupply/mobile/blob/5c6e6b9cf98fb6ce1b44eaf79ab61d41e1e75c0c/src/actions/BreachActions.js#L35 should be modified to only look at consecutive breach configs

### Version and device info

- App version: 7.X.X
- Tablet model: N/A
- OS version: N/A

### Additional context
N/A

**Comment by katherine-sussol** [comment]
Initially reported by @anildahalsussol, (thanks for the testing!)

**Comment by katherine-sussol** [comment]
Closed with #4553 (released in 8.4.1)

**Comment by ArpitaSussol** [comment]
Tested in apk V8.4.1

### Testing

- [x] Set up a HOT_CUMULATIVE breach config that that will trigger soon-is (e.g. max 8 degrees, 2min duration, when it's 26 degrees where the sensor is)
- [x] Set up a breach config such that a HOT_CONSECUTIVE breach will be created, but AFTER the cumulative breach (e.g. max 8 degrees, 20min duration)
- [x] Wait for 20min
- [x] we could see a hot consecutive breach after 20min above the threshold
