### ISSUE TITLE
v6 and server v5.04 incompatibility

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4556]
## Describe the bug

There is a field `doses` on a few tables - `StocktakeBatch`, `TransactionBatch` and `ItemLine` that were removed in v7 and removed in v5.04 on mSupply - making v6 incompatible with v5.04, as sync breaks when mobile sends records with fields the server doesn't understand.

### To reproduce

Steps to reproduce the behaviour:

1. Go to v6
2. with a v5.04 server
3. Try sync

### Expected behaviour

Sync should work

### Proposed Solution

- A patch for v6 to remove the fields (debatable whether this is needed) https://github.com/openmsupply/mobile/commit/084642bd13f3323dddde3cbf3f2a90564f4e8e25
- Remove doses from outgoing sync https://github.com/openmsupply/mobile/commit/20f0c69016602d164d401209972b0bb208753fe8#diff-61af01964877469339aecbb5e1ab54e0e09d51e6f2499cd5674891a8f5bf41cb

### Version and device info

- App version: v6.x

### Additional context

The client with this problem has strict policies around upgrading tablets or the server, so upgrading mobile to a non-ancient version is an option but seems that is a lot easier to just implement this patch instead.

**Comment by katherine-sussol** [comment]
Hmm it _looks_ like the doses field was only removed in v5.05 of mSupply (have tested on a few different versions of 5.04.X to try to see if it was missing and it wasn't!) so a little confused if the client is on v5.04 of mSupply why it's missing. Buuuut, based on the error message,  removing the doses field still sounds like the correct solution 🤷 .

**Comment by joshxg** [comment]
Ugh, sorry. 

Seems like a bit of miscommunication that might have lead you down an annoying rabbit hole - either me commenting what version the field was removed or the version the client is on.

I also thought (through the PR, not actually checking) that the field was only removed in 5.05 and not 5.04, but was told the client was on 5.04, so assumed I was wrong.

I agree and have seen this error quite a few times and know that mSupply simply iterates over the incoming requests payload, which has "tableName" and "data", and tries to find the 'field number' (pointer) for the specified table. If it can't find it, barfs - which then if mobile receives an error, stops sending records.

So, yes, I think going ahead is the right move, thanks a lot!

**Comment by katherine-sussol** [comment]
Closed by #4557
