### ISSUE TITLE
Corrections to French translations 🇫🇷 

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4563]
## Is your feature request related to a problem? Please describe.

While doing a demo in French, Pauline noticed some typos in the French translations for mSupply mobile.
These have been updated in the spreadsheet here:
https://docs.google.com/spreadsheets/d/1yNEwvHbq__1GWCw7Bul-dnqnnPINVa2CbNcCYg-zOFE/edit#gid=1174361042

## Describe the solution you'd like

We should import these for the next mobile release!

## Implementation

Use the import tool to update the french translations in mobile, then test to make sure it's all looking ok 👀  (sometimes the prompts get a bit long and things get cut off)

## Describe alternatives you've considered

Leaving the typos and looking unprofessional? 🧐 

## Additional context
N/A

**Comment by katherine-sussol** [comment]
Closed by #4648

**Comment by nisha-dangol** [comment]
## Testing
Tested in mobile v8.5.0-rc1

### Tests
- [x] Check the buttons for 'use requested quantities' and 'use suggested quantities' (Customer Requisitions)
- [x] Check the title for 'suggested_equals' pageInfo (Customer Requisitions)
![image](https://user-images.githubusercontent.com/65875762/161195434-30d32d78-f57b-460d-9290-e1ba5f266a97.png)
- [x] Check the 'current_stock' label (Menu Page and column heading for supplier requisitions)
![image](https://user-images.githubusercontent.com/65875762/161195485-3e015622-5d85-4fef-a50e-ed923c54741b.png)
![image](https://user-images.githubusercontent.com/65875762/161195549-deab46a7-1603-404f-9f02-8aa60f3ec0f2.png)

The placement for 'their stock' label column in customer requisition doesn't look good. Created issue for that [here](https://github.com/openmsupply/mobile/issues/4720)
![Screenshot_2022-05-20-10-55-18-506](https://user-images.githubusercontent.com/59193490/169457532-f5033377-1a0b-4394-873c-52739f6ce664.jpeg)
