### ISSUE TITLE
'Customer Requisitions' Main Menu button has 'Requisitions' text cut off on some devices

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4565]
## Describe the bug

Some screenshots (note it happens for both 4 panel layout and 3):
![image](https://user-images.githubusercontent.com/65875762/150895347-2d44cfc6-8414-472b-970d-4b93ef36a0d6.png)
![image](https://user-images.githubusercontent.com/65875762/150895385-bea74c7c-9504-44a4-b336-92d504919eb3.png)

### To reproduce

Steps to reproduce the behaviour:

1. Navigate to the main menu on mobile
2. See error (Button that should say 'Customer Requisitions' just says 'Customer')

### Expected behaviour

Full button text please

### Proposed Solution

Unsure yet - thinking of some kind of button resize

### Version and device info

- App version: 8.4.1
- Tablet model: Known to occur on Samsung SM-T500 and Samsung SM-T505
- OS version: Android 11 

### Additional context
Found by a client during training

**Comment by katherine-sussol** [comment]
Pasting info from the support ticket here:

I think Samsung might be setting the default font size a little bit larger than other manufacturers - there is a workaround for these devices to adjust the font size (but perhaps we could also look at finding a better button/font size combo that works across the range of supported devices).

The default settings have the size configured as such:
![image](https://user-images.githubusercontent.com/65875762/151892977-2d75ea2c-ced6-414f-a904-f6c4c60c1099.png)

With this setting the UI looks like this (which is what PNG are seeing):
![image](https://user-images.githubusercontent.com/65875762/151892985-106a9bcb-91fb-4ca0-a466-0804a21a6873.png)

When the font size is decreased to this setting:
![image](https://user-images.githubusercontent.com/65875762/151892995-9e16fb13-7c53-47de-a0e5-bdbeaa293043.png)

The menu displays like this:
![image](https://user-images.githubusercontent.com/65875762/151893005-78367d82-1007-4328-b5fa-c5b2553696ac.png)

**Comment by Gwalior-84** [comment]
I think it is a bit difficult to change the font size from the default.  Given that these Samsung tablets are a common device for mSupply Mobile, I think it might be worth trying to change mSupply to work with the default for these devices.  Can we make all the buttons text boxes a bit wider?

**Comment by katherine-sussol** [comment]
We can certainly look at resizing the default menu text/button sizing, or a combo of both - we just have to be careful to ensure the update doesn't break the view on the smaller devices we support.

**Comment by katherine-sussol** [comment]
Adjusted in 8.4.2-rc2. Possibly not the most ideal solution for smaller devices, but that would require significantly more investment.
