### ISSUE TITLE
Unable to connect local webserver running in non SSL

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#4567]
## Describe the bug

From Android Pie version, Android have forced to used the https over the http, which failed to connect the local test web server for testing which runs in http.
See here for supporting docs:
https://android-developers.googleblog.com/2018/12/android-pie-la-mode-security-privacy.html
https://medium.com/mindorks/my-network-requests-are-not-working-in-android-pie-7c7a31e33330
https://developer.android.com/training/articles/security-config

### To reproduce

Steps to reproduce the behaviour:

1. Setup a local webserver
2. Install v8 mobile app
3. Connect via credential
4. See error > It cannot be connected

### Expected behaviour

Most of the user may not face the problem as they runs in SSL, but for local testing, It will be hard for us if we need to test locally

### Proposed Solution

we could create a networkConfig.xml with this:
![photo_2022-01-25_21-11-50](https://user-images.githubusercontent.com/13144882/151006274-7ae8e2bb-22b9-46ee-9f81-e075d61192c2.jpg)

and in Android manifest we can link it up to use it

But there probably a better way to do this, leaving to Mobile developer

### Version and device info

- App version: V6 and higher
- Tablet model: SM-T515
- OS version: Android 11

**Comment by joshxg** [comment]
Yeah - `http` doesn't work for *production* builds. Develop builds work with servers over http.

I very much doubt any client is communicating with a server over `http`, and if they are we should certainly look at changing that to `https`.

As for testing: My initial thought is that for the end-to-end testing you seem to be describing, it might be best to use https so we have an environment which is as close to production as possible? Though, that's a bit of a cop out answer.. the alternative I can think of is to create 2 builds: Testing and Production for every release (and it seems easier to add an ssl cert to the 'testing' server which would also help with testing mSupply)?

**Comment by Gwalior-84** [comment]
@joshxg @anildahalsussol @katherine-sussol @mark-prins @ujwalSussol 

I believe we have three use cases:

- Production
- Testing - primarily for internal use by our testers
- Training - for demonstrating and training users in mSupply.  At times, (like now, with the PNG MOVEX project) this will need to happen in environments where there is frequently **NO** internet.  It is this last use case that is prompting this need.  We set up the mSupply server on a local laptop and the mobile devices connect to that laptop through the LAN.

**Comment by bijaySussol** [comment]
> Yeah - `http` doesn't work for _production_ builds. Develop builds work with servers over http.
> I very much doubt any client is communicating with a server over `http`, and if they are we should certainly look at changing that to `https`.

For local testing it is hard to test for someone like me, when i got to test, I got to boot server locally and connect

> As for testing: My initial thought is that for the end-to-end testing you seem to be describing, it might be best to use https so we have an environment which is as close to production as possible? Though, that's a bit of a cop out answer.. the alternative I can think of is to create 2 builds: Testing and Production for every release (and it seems easier to add an ssl cert to the 'testing' server which would also help with testing mSupply)?

Seeing that V5.1.2 version works with http with local server, maybe it would be good to have it?
I am quite not sure of having 2 build as i know nothing on this side.
But what i can confirm is: the build V5.1.2 or V5 X version works quite well above that version, It does not

**Comment by bijaySussol** [comment]
> * Training - for demonstrating and training users in mSupply.  At times, (like now, with the PNG MOVEX project) this will need to happen in environments where there is frequently **NO** internet.  It is this last use case that is prompting this need.  We set up the mSupply server on a local laptop and the mobile devices connect to that laptop through the LAN.

If V5 x version works for training then Vx works nicely over http @Gwalior-84

**Comment by ujwalSussol** [comment]
> Yeah - `http` doesn't work for _production_ builds. Develop builds work with servers over http.
> 
> I very much doubt any client is communicating with a server over `http`, and if they are we should certainly look at changing that to `https`.
> 
> As for testing: My initial thought is that for the end-to-end testing you seem to be describing, it might be best to use https so we have an environment which is as close to production as possible? Though, that's a bit of a cop out answer.. the alternative I can think of is to create 2 builds: Testing and Production for every release (and it seems easier to add an ssl cert to the 'testing' server which would also help with testing mSupply)?

@joshxg  : We just need http for training purposes and for us to test locally. The folks at PNG are crying out for this as Training needs to be carried at remote sites where facilities are so bad that Nepal looks to be very advanced. :-) 

Yes for all our cloud servers :  http is never enabled so this is safe as we are in control.

**Comment by joshxg** [comment]
There's an APK here which is master with the security config altered which works against an mSupply server over http on a lan:

https://drive.google.com/file/d/1Z4ZrRuZk8bYcSrcXQlYLmZCZ0iDDNm_2/view?usp=sharing

This should hopefully solve any immediate issue.

Note that this is master with a change to the security config. So, not a patch. Therefore you would need to reinstall, an upgrade wouldn't work.

Hope this helps

**Comment by katherine-sussol** [comment]
Fixed with #4567 (and included in 8.4.2)

**Comment by nisha-dangol** [comment]
## Testing
Tested in mobile v8.5.0-rc2

### Tests
- [x] Run mSupply server on a computer locally with local ip exposed.
- [x] Open mSupply mobile in a mobile device. Try connecting to the local ip address which obviously would not have secure https ssl connection.
- [x] The connection should work.
