### ISSUE TITLE
Sensor downloads freezing intermittently 

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4568]
## Describe the bug

Support ticket: https://support.msupply.org.nz/cerb6/profiles/ticket/13814
This might not be a new issue as it's been observed previously - but has been reported again by another client that mSupply mobile is sometimes not downloading logs from sensors (once it gets into this state, the download never resumes until connecting to the sensor via the Blue Maestro app).

Blink commands do work - so unlikely to be purely a Bluetooth issue.
Might be related to similar cold chain issue here: https://github.com/openmsupply/msupply-cold-chain/issues/212

Not great as it's not consistently reproducible - needs investigation.

### To reproduce

Steps to reproduce the behaviour:

1. Set up cold chain in mobile with sensors 
2. Leave it to download
3. Observe that (sometimes!?!) it doesn't and only restarts when the blue maestro app connects to the sensors.

### Expected behaviour

Downloads to happen

### Proposed Solution

TBD

### Version and device info

- App version: 8.4.1
- Tablet model: SM T505 (but not believed to be device specific)
- OS version: Android 11

### Additional context

N/A

**Comment by joshxg** [comment]
😱 

Maybe we need to look again at what bluemaestro is doing.

I remember their app being on bitbucket or gitlab but I've been unable to find it for awhile. I wonder if andrei still has a copy of their repo

**Comment by katherine-sussol** [comment]
Is it this one maybe? Hasn't been updated in a while so maybe it's an old repo 🤔  https://bitbucket.org/RichieJH/android-tempo-utility-sdk-current/src/master/ 

I'm borrowing a device from @npendergrast that has Android 11 on it to see if I can at least replicate it 😓

**Comment by katherine-sussol** [comment]
Kat's Testing fails: 
- Started the tablet and paired 2 sensors, saw issue with infinite N/A and no downloads happening
- W/Craig, enabled the developer settings to debug bluetooth https://source.android.com/devices/bluetooth/verifying_debugging#debugging-with-logs (including toggling BT/restarting the app), magically downloads started working ...

@adamdewey's testing:
- Paired 3 sensors and they all reported correctly in 8.3.0
- Upgraded to 8.4.1 - removed/re-added sensor with weird mac address format and it also downloaded fine
