### ISSUE TITLE
Response requisition in suggested state creates a rouge CI in mobile

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4592]
## Describe the bug

- In normal flow of mSupply , when a Response requisition is created, it is created in suggested state and it does not create any linked CI yet.
- In mobile, when a mobile site creates a Response requisition,  it is created in suggested state and creates (forcefully) a linked customer invoice. 
- This CI does not show on the interface as mobile would hide ci with linked requisition but it is there. 
- These requisition and ci sync back to server and in main server we have a suggested response requisition with a linked ci. Which should never happen. 
- When we delete the suggested response requisition, this CI does not get deleted (as it was created against the flow of mSupply), and since the response requisition is deleted, the CI will finally show up in mobile. 
- This is a rouge CI issue.

### To reproduce

Steps to reproduce the behaviour:

1. Open mobile app, and create a Customer requisition, you would have to give customer with program so do that to create a customer requisition. It would be in progress state, i.e. suggested state.
2. Look for a new confirmed Customer invoice in the Customer invoice tab of mobile, there won't be any.
3. In the mSupply server, when the Customer requisition has synced in notice that customer requisition is in suggested state. Go to Customer invoice tab, you will see a new CI has synced in which is the linked CI to the customer requisition that we had just created. 
    - The Ci might not have any trans_lines, which could be related to a different issue raised here https://github.com/openmsupply/mobile/issues/4562
4. Now delete the customer requisition (still in SG state) in desktop or mobile. 
5. Let the sync happen.
6. Now check for the customer requistion, which should have been deleted as expected.
7. Go to Customer invoice tab of mobile the linked customer invoice is not deleted, and now since its linked requistion is gone, it show shows up in the mobile Ci tab.

### Expected behaviour

- Since the Customer requisition is in SG state, it should not create a CI. 
- If it must create the CI, the customer requisition must be in confirmed state.
- The Customer requisition, if it has linked CI, should not be deletable until the CI is deleted.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by sworup** [comment]
@Chris-Petty @joshxg any idea on this?

**Comment by joshxg** [comment]
CI's created for sg response requisitions on mobile I believe is normal and always has been like this. The bug I see here is when deleting a manual requisition the CI should be deleted also.

should just need to add code here to delete linked ci for this case https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/database/DataTypes/Requisition.js#L53-L55

**Comment by joshxg** [comment]
CI with no lines, my guess is: https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/database/DataTypes/Requisition.js#L392-L399

**Comment by sworup** [comment]
> CI with no lines, my guess is:
> 
> https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/database/DataTypes/Requisition.js#L392-L399

@joshxg `pruneRedundantItems` is called during finalisation or on `createAutomaticOrder` button click. These are either happening during finalisation or through Supplier invoice button. The missing trans lines issue shows up on mSupply desktop during suggested phase (CI is confirmed). So I do not think tinkering here is the fix.

**Comment by sworup** [comment]
> CI with no lines, my guess is:
> 
> https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/database/DataTypes/Requisition.js#L392-L399

@joshxg it seems the requisition creates a blank Ci when we finalise the requistion without giving any quantity. So no items were actually transferred so a blank CI. If we give quantity to the requistion it shows the lines.

Now 2 things that are problems here:

1. The CI even though does not show in mobile UI shows up in database and would have blank lines. I guess that is just aesthetically un-pleasing as you cannot do anything to that CI.
2. In mobile if we finalise the ci without giving any item(s)... then it will create a blank finalised CI.
  - Possible solution would be to not allow finalising requistion that has a blank CI, I mean items with no quantity, what do you think?

**Comment by joshxg** [comment]
If I remember correctly, you cannot remove lines from a customer requisition, and you can't delete a customer requisition.

So, if we have no stock for an item.. we can't remove and we can't finalise.. it's also not ideal. 

Another idea: When finalising a customer requisition that has no quantity supplied.. delete the CI?

**Comment by Chris-Petty** [comment]
@joshxg just checking how I remember it, you can't finalise if there's no issue amount for _all_ lines, not just for one right? If so still a bit annoying if a customer requests one line of which you can't supply though 😕 .

> Another idea: When finalising a customer requisition that has no quantity supplied.. delete the CI?

I'm struggling to see why not? Would be relatively clean? Can't think of any logic that depends on that CI existing (at least if it's blank anyway).

**Comment by Chris-Petty** [comment]
> CI's created for sg response requisitions on mobile I believe is normal and always has been like this. The bug I see here is when deleting a manual requisition the CI should be deleted also.
> 
> should just need to add code here to delete linked ci for this case
> 
> https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/database/DataTypes/Requisition.js#L53-L55

And dis for the original issue described here seems legit

**Comment by sworup** [comment]
@joshxg @Chris-Petty In mobile we can finalise requisition with all blank lines.
https://user-images.githubusercontent.com/683452/155939565-1a9272c0-a8df-4dd0-a591-7beb459367d5.mp4

**Comment by sworup** [comment]
@joshxg @Chris-Petty 
I think the deletion fix, fixes the rouge Ci issue. 
The blank CI issue I am going to fix with this issue: https://github.com/openmsupply/mobile/issues/4562
So setting this issue's PR to completed and ready for review and merge.

**Comment by katherine-sussol** [comment]
Closed by #4599

**Comment by nisha-dangol** [comment]
## Testing
Tested in mobile v8.5.0-rc1

### Tests
- [x] Create a Customer Requisition on mobile
- [ ] After it syncs delete it **-CAN'T DELETE IT-**
- [ ]  Go to Customer invoice tab
- [ ]  See a customer invoice corresponding (created by) the deleted Customer Requisition appear. This CI should have been deleted with Customer Requisition.
- [ ]  Check to see if the deleted requisition in mobile is also deleted on server.

### Regression tests
- [ ] Create, update and delete customer and supplier requisitions. They should all work as expected.

@sworup @katherine-sussol 
AFAIK, the finalised customer requisitions cannot be deleted neither on mobile nor on the cloud datafile on desktop. So, maybe edit/update the test cases above?
As for the sg customer requisitions, it does not create any corresponding CI, which I believe is correct!

**Comment by katherine-sussol** [comment]
Thanks @nisha-dangol, yes I think the first step is referring to creating a sg customer requisition rather than a finalised one - will update the steps in the linked PR!

You'll be able to see a cn CI on Desktop after the sg customer requisition is synced (but not mobile) - and then when the sg customer requition is deleted on mobile (and then also synced), I believe the expected behaviour is for that CI to also be deleted (@sworup can correct me if I'm wrong here!)

**Comment by nisha-dangol** [comment]
> Thanks @nisha-dangol, yes I think the first step is referring to creating a sg customer requisition rather than a finalised one - will update the steps in the linked PR!
> 
> You'll be able to see a cn CI on Desktop after the sg customer requisition is synced (but not mobile) - and then when the sg customer requition is deleted on mobile (and then also synced), I believe the expected behaviour is for that CI to also be deleted (@sworup can correct me if I'm wrong here!)

thanks!

**Comment by nisha-dangol** [comment]
## Testing
Tested in mobile v8.5.0-rc1

### Tests
- [x] Create a sg Customer Requisition on mobile
- [x] Let the sg Customer Requisition sync
- [x] Check the Customer invoice tab on Desktop and Mobile
    - [x] On desktop: See a customer invoice corresponding (created by) the Customer Requisition appear.
    - [x] On mobile: There should be no customer invoice corresponding to the Customer Requisition visible at this point (though there will be one that was created behind the scenes)
- [x] Delete the sg Customer Requisition
- [x] The linked CI should have been deleted with Customer Requisition.
- [x] Check to see if the deleted requisition in mobile is also deleted on server.

**Comment by sworup** [comment]
> Thanks @nisha-dangol, yes I think the first step is referring to creating a sg customer requisition rather than a finalised one - will update the steps in the linked PR!
> 
> You'll be able to see a cn CI on Desktop after the sg customer requisition is synced (but not mobile) - and then when the sg customer requition is deleted on mobile (and then also synced), I believe the expected behaviour is for that CI to also be deleted (@sworup can correct me if I'm wrong here!)

@katherine-sussol sorry for the late reply. 
Yes you are correct.
