### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by GaryWilletts** [openmsupply/mobile#4613]
## Is your feature request related to a problem? Please describe.
Sao Tome are going to start using mSupply mobile within about 2 months. We need the Portuguese version for them.

## Describe the solution you'd like

Make it speak Portuguese.

## Implementation

Hand it to Nicole who will work her tappity, tappity, tap magic.

## Describe alternatives you've considered

Doing it myself. Cough. Not really.

## Additional context
None

**Comment by GaryWilletts** [comment]
@joshxg Not sure who to tag to make sure this is noticed so I tagged you 😄

**Comment by joshxg** [comment]
:)

Do you know about this @nmadruga  ?

**Comment by nmadruga** [comment]
I guess most of the work was already done in the past #2115, but I can have a look on any remaining (new since 2020) strings to translate also. And perhaps align with latest translations done on mSupply Desktop [1](https://github.com/sussol/msupply/issues/9803) [2](https://github.com/sussol/msupply/issues/10013) and [3](https://github.com/sussol/msupply/issues/10026)

**Comment by nmadruga** [comment]
Updating "home store" to be "local de origem" in Portuguese. Just a reminder that this also needs to be updated in mSupply Desktop strings... **17009;634**

**Comment by nmadruga** [comment]
Just checked 2 other strings to be translated in mSupply Desktop - not in XLIFF files yet: 
"Invalid username or password" which gets returned to mobile and displayed to the user.

These strings are currently defined in `coldchain_LoginV1` and `REST_authenticate`.

TO_BE_DONE by me as part of the same PR to do the replace of the string mentiioned above : )

**Comment by nmadruga** [comment]
> TO_BE_DONE by me as part of the same PR to do the replace of the string mentioned above : )

New XLIFF string added: **17009;658**
