### ISSUE TITLE
Changing language doesn't take effect

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#4625]
## Describe the bug

When you select another language and log in it doesn't  refresh the App to be using the new one - you would still see everything on the previous language selected. If I close and reopen the app and log in now then it shows the correct language selected. The only page that actually changes on the go is the login screen.

### To reproduce

Steps to reproduce the behaviour:

1. Go to the Login page - click on language. Select one different to English by clicking twice
2. You will see the login page in the new language selected
3. Now login - The language on the main page will still be English
4. Close the app and open again - It will be showing in the new language
5. Log in - Now you can see the strings on the main menu as well

### Expected behaviour

Should change the strings on the main menu everytime you change the language on the login page. Shouldn't need to refresh the App.

### Proposed Solution

Not sure.

### Version and device info

- App version: v8.4.3
- Tablet model: Emulator 5 SDK .1
- OS version:

### Additional context

N/A

**Comment by nmadruga** [comment]
What I have found so far is that this seems to be a problem with re-mounting the MenuApp page. So the Login page is correctly translated (which also seems to confirm #4485 is fixed), but then the main menu still is showing on the previous language. The sync modal is in the new language though. If I go to another module i.e. stocktake - is in the new language. And then back to the main menu now it's also in the new language. So only needs fixing the menuApp right after changing the language.... but how.... @joshxg last minute help?

**Comment by joshxg** [comment]
Quick recap of some options from a talk in office:

- Add a `rerender` function to `MobileAppSettings` and set it in `mSupplyMobileAppContainer` [ probably the best and easiest option ]
- Add `currentLanguage` to `mSupplyMobileAppContainer` and pass a callback to `LoginModal` for langauge changes. This should re-render at the root.
- Use an observer pattern in `MobileAppSettings` - adding a `register` function and components can listen to changes in `MobileAppSettings`
- Bonus/too much: Realm observables: https://docs.mongodb.com/realm/sdk/react-native/examples/use-change-listeners-in-components/

**Comment by ArpitaSussol** [comment]
Tested in v8.5.0-rc0

@nmadruga Flag icon or the language is not reflected in Menu page instead its showing the language and flag of previous one. Please go through the below recording 

https://user-images.githubusercontent.com/58979436/161198001-cd06d02a-887b-4923-b85a-cf584d45c98f.mp4

**Comment by nisha-dangol** [comment]
Tested as #4680
