### ISSUE TITLE
Update lookup patients to work with HL7/Tamanu integration

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#4631]
## Is your feature request related to a problem? Please describe.

Lookup for patients not working when there are patients coming from the HL7 integration

## Describe the solution you'd like

In msupply Desktop the lookup patients also return patients that aren't included in msupply yet, with the option to import when clicked by the user. The owrk is on a PR for version 5.07 in mSupply Desktop, but it doesn't work without some tweaking on mobile. Basically needs to fix the App breaking when receiving the HL7 patients - due to less columns present (mostly only persent in name or relation tables from mSupply) and fix the second request to actually import the patient and send to mobile (already done in Desktop).

another nice think would be to show the tick for patients from Tamanu that were already imported (and which ones haven't) to the mSupply primary server. To help on the decision making - so the user knows which one are actually external to mSupply.

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by Chris-Petty** [comment]
Not needed https://github.com/openmsupply/mobile/pull/4634#issuecomment-1522666220
