### ISSUE TITLE
Link PCD name_note with VaccinationEvent name_note

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4635]
## Is your feature request related to a problem? Please describe.

Child of #4624 

## Describe the solution you'd like

When creating a vaccine prescription, the PCD `name_note` used at the time (on the patient edit step of vaccine dispensing) should be linked to the vaccination event `name_note`

## Implementation

Agreed solution: Save the PCD `name_note` ID into the VaccinationEvent name note when a vaccination is confirmed. This way we will have a record of which PCD was used at the time of vaccination without needing to create a new PCD note if the PCD is not updated.

## Describe alternatives you've considered

Save the transact id into the PCD `name_note`.
But there is the possibility that the PCD was not updated at the time of vaccination (meaning we don't need to create a new one). Therefore we'd need to create a new PCD `name_note` for every vaccination, which is not ideal.

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by anildahalsussol** [comment]
@katherine-sussol: I think we need migration code? or we do fr code in msupply?

**Comment by katherine-sussol** [comment]
> @katherine-sussol: I think we need migration code? or do we do fr code in msupply? To add transactID for exiting name note.

Yeah, we will need migration code (and it will be slightly dodgy because we will have to guess via heuristic which PCD belongs to which vaccination event). I'd created an issue here for it: https://github.com/openmsupply/mobile/issues/4638

**Comment by katherine-sussol** [comment]
Closed by #4651
