### ISSUE TITLE
Flag isn't corresponding to selected language

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#4644]
## Describe the bug

Issue introduced on v8.5.0-RC0 to be fixed, so the flag uses the same language as selected by the user on the login screen

### To reproduce

Steps to reproduce the behaviour:

1. Go to login
2. Click on Language select some other than english (i.e.Spanish)
3. After loged in noticed the English flag is still showing
![Screen Shot 2022-03-30 at 4 25 18 PM](https://user-images.githubusercontent.com/16461988/160747176-f21b049a-fad3-4814-bc68-2630357d295d.png)

4. If you go back to the login and change again, it will show the previous flag...

### Expected behaviour

Show the same flag as the language selected

### Proposed Solution

N/A

### Version and device info

- App version: v.8.5.0-RC0
- Tablet model:
- OS version:

**Comment by katherine-sussol** [comment]
Closed by #4654
