### ISSUE TITLE
Hide items with zero stock, or add toggle to hide them on the 'Current Stock' page

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4647]
## Is your feature request related to a problem? Please describe.
Currently mobile displays all items that the store has visibility of on the 'Current Stock' page, including potentially many lines with 0 stock. 

This can make it a bit hard for some users to identify what is actually in stock - so either hiding these or having an option to toggle them on/off them would be ideal (maybe better to have a toggle in case someone wants to see items that are potentially missing/uncounted?)

## Describe the solution you'd like
TBD

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

Ignoring

## Additional context
Confusion/app behaviour questioned in support ticket: https://support.msupply.org.nz/cerb6/profiles/ticket/IG-3278-HL

**Comment by arjunSussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile: #4647 Hide items with zero stock, or add toggle to hide them on the 'Current Stock' page](https://trello.com/c/YBCG7y8M/436-mobile-4647-hide-items-with-zero-stock-or-add-toggle-to-hide-them-on-the-current-stock-page)

**Comment by sworup** [comment]
Resolved with https://github.com/openmsupply/mobile/pull/4864
