### ISSUE TITLE
Kiribati (1.3.a) Record patient as deceased

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4672]
## Is your feature request related to a problem? Please describe.
An option will be added to mSupply Mobile to allow the user to indicate on a patient’s medical record that the patient is deceased.

`isDeceased` field added to name records on mSupply with `V5-08-00-RC20` 
Desktop issue: https://github.com/sussol/msupply/issues/10564

## Describe the solution you'd like
A checkbox or toggle on the patient record page to show if the patient is deceased or not. Updating/saving should edit the record and be synced back to Desktop.

## Implementation
- Update realm schema with new field
- Update incoming/outgoing sync utils to include new flag on patient record
- Update the patient edit page (both in dispensary and vaccination module)
- Changes to ensure value is saved when the user confirms the patient's details.

## Describe alternatives you've considered
N/A

## Additional context
[Trello
](https://trello.com/c/pQYEJCBR/68-13a-record-patient-as-deceased)

**Comment by katherine-sussol** [comment]
Closed by #4719

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest apk

### Tests
- [x] Open an existing patient and change the 'Is deceased' value, press save (if in dispensing) or complete the vaccine dispensing flow (if in vaccinations area)
- [x] Re-open the patient to check the value was saved and loaded correctly
- [x] Sync to Desktop (min version V5-08-00-RC20) and check that the flag has come through on the [name] record (check in record browser - no UI available for viewing at this stage)
