### ISSUE TITLE
Alter language flag icon

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4680]
## Is your feature request related to a problem? Please describe.

There has been some debate about the language flag icon and the general consensus is that something needs to be changed as it's a bit distracting / unsure of appropriateness of using country flags outside of the country the flag represents. 

Current implementation of flag icon: 

![image](https://user-images.githubusercontent.com/19318937/165628009-c33dbf9f-260e-4ef5-87e2-2a1b88b02844.png)

## Describe the solution you'd like

One of the 2 options mentioned here (the choice is yours!): 

<img src="https://user-images.githubusercontent.com/19318937/165627586-1c4c3a45-0913-4d6e-98ed-089ff3ea4ef9.png" width="400">

Example of language selector (see Mobile log-in page for current use of language selector): 

![image](https://user-images.githubusercontent.com/19318937/165628556-e73de51c-8b42-4f39-be8e-a6b9f69f5aac.png)

Example of small flag icon: 

![2022-04-27_09-56-52 (1)](https://user-images.githubusercontent.com/19318937/165627821-2873aa49-12e0-40fc-8f15-b63397da71d1.png)

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

Note that the 2 options offered are not really equivalent as one just moves the displayed icon, and the other is asking for additional functionality (the ability to switch languages once past the log-in screen). 

So.... over to you 😁

**Comment by DhanyaHerath** [comment]
Unasked for opinion: I really think we should just remove it entirely. The debate itself has already taken time ;) and
(1). I don't see the point of leaving it as an indicator. I would think looking at the language used would in itself be an indicator, surely?
(2). I don't see the advantage of the added functionality. Logging out and changing languages is already a functionality, and doesn't take that long for a one-off change. Plus no one's asked for it that I know of, and therefore we have no 💸 budget 💸  for it.

**Comment by mark-prins** [comment]
As a supporter of 'FLEXIT' I'm happy to just remove. However.. I wanted to know why it was added first. My interpretation of the PR which introduced the change is that it was a developer convenience when testing a related issue. Given that.. I'll remove it.

**Comment by DhanyaHerath** [comment]
[flexit](https://auckland.ac.nz/flexit)? 🎓  [flexIT](https://flexit.fit/)? 💪🏽  [flexit](https://www.flexit.no/en/)? ☁️ 
Flemish people leaving the EU?

**Comment by mark-prins** [comment]
The Flemish have suffered under the yoke of imperialist suppression for too long!!!

**Comment by adamdewey** [comment]
> Unasked for opinion: I really think we should just remove it entirely. The debate itself has already taken time ;) and (1). I don't see the point of leaving it as an indicator. I would think looking at the language used would in itself be an indicator, surely? (2). I don't see the advantage of the added functionality. Logging out and changing languages is already a functionality, and doesn't take that long for a one-off change. Plus no one's asked for it that I know of, and therefore we have no 💸 budget 💸 for it.

+1

**Comment by katherine-sussol** [comment]
Closed by #4681

**Comment by nisha-dangol** [comment]
## Testing
Tested in mobile vv8.5.0-rc1

### Tests
- [x] No flag on menu page
- [x] When changing language, this should be reflected on the menu page without the need to restart the app
