### ISSUE TITLE
Need to handle undefined UserJson

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4684]
## Describe the bug

Now even if UserJson is undefined it shows an "Unexpected error from the server" which seems to be unclear while testing locally I found that it never hit the server but later found server API was wrong as my IP address changed. 

### To reproduce

Steps to reproduce the behaviour:

1. Go to user login.
2. Be able to log in.
3. And change your IP address.
4. See an error

### Expected behaviour

At least if it can show me a clear error so that we can fix the problem. Like User is Undefined. And I saw that it can be due to the wrong URL where UserJson is undefined.

### Proposed Solution

For now, I am thinking of at least showing the error "User Json is undefined and also the server URL". So that we can see if that's the reason behind getting "Unexpected error from the server".

### Version and device info

- App version: 8.4
- Tablet model: Nexus emulator
- OS version:

**Comment by anildahalsussol** [comment]
@katherine-sussol: Do you think it's valid to work on? It's just a two-line code as in Kiribati we saw this error and we were unable to find the cause. We checked in the server if it was hitting the server but nothing was there in the Json log which tracks every incoming and outgoing traffics. I found that URL can be the possible reason for getting undefined.

**Comment by katherine-sussol** [comment]
@anildahalsussol I think it could be potentially useful to distinguish between 
`!userJson` and `!userJson.UserID` for logging/display. 

Although the error message `userJson is undefined` might not mean much to anyone that doesn't have access to the mobile repo 😅 . Maybe something a little more generic? (some ideas: 'missing response from the server' or 'response from the server was undefined'... 🤔 )

**Comment by katherine-sussol** [comment]
Closed by #4686
