### ISSUE TITLE
Add the ability to edit vaccination transact data via the Vaccination Event modal

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4715]
## Is your feature request related to a problem? Please describe.

Trello: https://trello.com/c/J4kCLZGC/74-17b-17c-edit-vaccine-type

Editing this portion of the 'vaccination event record':
![image](https://user-images.githubusercontent.com/65875762/168733543-c52b97f5-3096-4e16-a81e-3ff17eef5328.png)

## Describe the solution you'd like

It's possible to just edit the name note itself - but we wouldn't be able to update the actual transaction unless the vaccination was done on the same tablet...

Probably just need to agree on a 'source of truth' for this data. 

## Bugs found & Fixes

- [ ] #4785 
- [ ] #4791

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by adamdewey** [comment]
Discussed with @katherinesetiadarma , edit functionality looking really good. Some decisions to get it across the line:

- Won't make 'Refusal', 'Bonus dose' or 'Date of Entry' editable at this stage
- Add a pop-up to tell user they will affect inventory levels when they change item type
- Add a pop-up to tell user they need to use a different tablet (tell them which one) if editing a non-local patient

**Comment by katherine-sussol** [comment]
> * Add a pop-up to tell user they need to use a different tablet (tell them which one) if editing a non-local patient

This isn't looking like it's going to be possible, we can tell that there is no corresponding `[transact]` record on the tablet, but can't identify _which_ store it exists on 🤔 ...

Would the 'place of vaccination' on the form be enough of a hint for Kiribati to work out which tablet was likely used?

**Comment by adamdewey** [comment]
Ooh, ok maybe we'll have to run a dashboard report to tell them which tablet to use to edit which patient. 

But to future-proof it, could we put the store id and name into the name_notes from now on? (Only if it's a very simple change!)

**Comment by sworup** [comment]
# Bugs found & Fixes

- [ ] Vaccination event Edit model: Date-picker and date is not updating correctly

**Comment by chastichno** [comment]
Closed as completed
