### ISSUE TITLE
Vaccination regression testing following Kiribati View vaccination events feature 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#4732]
## Describe the bug

This feature will be implemented in mobile v8.5.0. So the tests will be run using Tonga VAX datafile and mobile v8.5.0rc1. The mSupply server will be of version v6.0.0  

### Version and device info

- App version: v8.5.0rc1
- Tablet model: Galaxy A8
- OS version: 

### Additional context

The issues specific to the release can all be found here: [v8.5.0 Release Discussion](https://github.com/openmsupply/mobile/issues/4541), although the highest priority issue (for us) is  [view vaccination events in mobile](https://github.com/openmsupply/mobile/issues/4623), in particular, validating that it doesn’t break for any other clients (especially Tonga, as they also use the vaccine dispensing module), as this was a Kiribati specific feature request.

**Comment by alainsussol** [comment]
#### Navigation
- [ ]  Vaccination button is displayed if setup done properly

#### Choosing a Patient  
- [ ]  Click on the Vaccinations Button
- [ ] Put the last name or part of a last name that you know is in the database on the tablet. A list should appear that display the names that includes the string of character you have put **-PASS-**
- [ ] Check that no names that appears in the list has nothing to do with what you have enter **-PASS-**
- [ ] Try to affine you search with a more precise last name. The list is relevant to what you have written **-PASS-**
- [ ] Try to affine you search with a first name. The list is relevant to what you have written **-PASS-**
- [ ] Try to affine you search with a date of birth. The list is relevant to what you have written **-PASS-**
- [ ] Try something which you think will return no results. The list is empty  **-PASS-**
- [ ] Create a new patient on the server but don't sync it to mobile.
- [ ] Search for that patient. No results is found **-PASS-**
- [ ] Click on on the "Search Online" button. The patient should be found **-PASS-** 
- [ ] The details should be exact. **-FAIL see #4736-**
- [ ]

**Comment by adamdewey** [comment]
I've never used the QR code functionality before - @npendergrast , @mark-prins - any idea here?

**Comment by npendergrast** [comment]
Hi @alainsussol and @adamdewey, I believe the QR code patient lookup was added for a specific client which is not is use so far. I believe the qr lookup would be on the barcode field of the patient table. I think @katherine-sussol worked on this feature?

**Comment by adamdewey** [comment]
Thanks Nick, if so sounds like another non-blocker :)

**Comment by adamdewey** [comment]
Thanks @alainsussol for testing - this is so useful!

**Comment by katherine-sussol** [comment]
> Hi @alainsussol and @adamdewey, I believe the QR code patient lookup was added for a specific client which is not is use so far. I believe the qr lookup would be on the barcode field of the patient table. I think @katherine-sussol worked on this feature?

Yep - that's right (on all counts). If mobile doesn't find anything by the QR code the app should default to a manual patient search... although Kiribati won't have any patients set up with barcodes (`name.barcode` field would need to be populated for patients).

**Comment by adamdewey** [comment]
@alainsussol - there will be a new rc (or release even?) coming out soon - would you have time to test this too?

In particular we want to make sure the vaccination history screen appears correctly for Tonga: 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19318937/170592724-50507134-a83e-49be-bcda-a1b2ed31f1bd.png">

(Note this is the Kiribati vaccination history screen, the Tonga one should be unchanged and operate as in previous version of Mobile). 

Thanks so much in advance! 🙏

**Comment by alainsussol** [comment]
@adamdewey @katherine-sussol 

This is 3 new possible issues I found in v805-00rc1
https://github.com/openmsupply/mobile/issues/4744
https://github.com/openmsupply/mobile/issues/4743
https://github.com/openmsupply/mobile/issues/4742

@nisha found this on v805-00rc2
https://github.com/openmsupply/mobile/issues/4741

**Comment by adamdewey** [comment]
Great work @alainsussol and @nisha-dangol 

My observations in light of the Kiribati release tomorrow: 

#4744 - Odd, haven't seen this before, so hopefully a rare occurrence...
#4743 - I see this too, but Kiribati don't use the Dispensing module so more of an issue for Tonga
#4742 - I see this too, but Kiribati don't use the Prescription module on Desktop so more of an issue for Tonga
#4741 - Kiribati doesn't crash so guessing it's related to the extra JSON schema for Tonga

So, I definitely think we need to look into these before Tonga is upgraded to a new mobile version, but we could potentially get away with giving the rc2 to Kiribati in the meantime

**Comment by sworup** [comment]
v8.6.1 has been released. Closing this.
