### ISSUE TITLE
Default the ability to edit historical vaccinations to 'off' and add setting to enable

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4733]
## Is your feature request related to a problem? Please describe.
Editing historical vaccination records in mobile is already kind of dodgy for Kiribati (who have requested this functionality).
Vaccine dispensing is also used by Tonga, who have not requested it.
Therefore it might be a good idea to 'disable' the functionality by default and only allow if it has been explicitly enabled in the settings menu - to stop people accidentally fiddling with records.

## Describe the solution you'd like

TBD

## Implementation

TBD

## Describe alternatives you've considered

Enabled by default

## Additional context

N/A

**Comment by chastichno** [comment]
There are a couple of things being added to mobile that are quite different from normal behaviour and can affect the database a lot. Those are:
- Editing vaccination event
- Deleting vaccination event
- Deleting a patient medical record

I agree that this behaviour should be turned "OFF" by default. Should we add store preferences on the desktop to control that? @mark-prins

**Comment by mark-prins** [comment]
Good idea - a store preference would be useful. the structure to support all of that is already in place, should be simple enough to do

**Comment by adamdewey** [comment]
After speaking to @arjunSussol, trying to assess the priority of this. 

There are only 2 clients using this - one of them wants it, the other one isn't affected yet as they're not on this version (afaik)

So I'm wondering whether we can close this as 'not required' as we're looking to sunset Mobile as soon as possible and start pushing Open mSupply in its place. 

Unsure if the other client are looking to upgrade to the newer version any time soon. 

Will check with @jagoje and see

**Comment by adamdewey** [comment]
@arjunSussol - I spoke to @jagoje and the other client actually wants the edit vaccination functionality too, so we don't need to do this issue as we are unlikely to get any other vaccine clients before Open mSupply is ready.

**Comment by arjunSussol** [comment]
Thanks @adamdewey for the update. Issue closed now.
