### ISSUE TITLE
App constantly crashes while I try to do anything with patients

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4741]
## Describe the bug
While trying to view patients vaccine history, or simply trying to dispense the patients gets the mobile app to crash every single time.

### To reproduce
Steps to reproduce the behaviour:
1. Get sync setup in Tonga vax datafile
2. Create some patients or use any exisitng
3. In mobile site, try to look at patient vaccination records
5. Simply try to dispense any patient and see the app crashing as well

### Screenshots
https://user-images.githubusercontent.com/59193490/170649566-33fec73d-b47c-4c98-88ba-31d82cc3a2b8.mp4

https://user-images.githubusercontent.com/59193490/170649494-c76de600-0a6b-429a-8f35-4e8ee8c5576f.mp4

### Expected behaviour
No any crash!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: 508
- Tablet model: 8.5.0-rc2

### Additional context
Found while testing #4640

**Comment by alainsussol** [comment]
@adamdewey @katherine-sussol @nisha-dangol 

It is happening for me too !!!

**Comment by adamdewey** [comment]
Ah, probably related to the JSON schema I guess @katherine-sussol ?

**Comment by katherine-sussol** [comment]
Yeah, the vaccine history is definitely related to the JSON schema (can be avoided by uploading one before updating any apps). Unsure about dispensing crashing though - I've just removed the schema on my test datafile and have not yet been able to replicate the crashing 🤔 - going to try grab a tonga datafile and retest.

**Comment by katherine-sussol** [comment]
Have replicated with the test user on the tonga vax server - the error being thrown is the same:
`undefined is not an object (evaluating '(0,N.selectVaccinationEventSchemas)()[0].jsonSchema')` - so as long as before upgrading to 8.5.0 (on a datafile with a PatientEvent type = 'vaccination') there is a form schema uploaded I think this crash should not occur.

**Comment by katherine-sussol** [comment]
Hi @nisha-dangol I'm going to close this for now - I have not been able to replicate once adding the schema (though please do reopen if you are able to!)

These are the files needed: https://github.com/sussol/client-JSON-schemas/tree/main/Kiribati/COVID-19-vaccination-rollout.

Can run some FC in mSupply to create the placeholder schema and then use the record browser to insert the above:
```
$obFormSchema:=ds.form_schema.new()
$obFormSchema.ID:=UUID_generate
$obFormSchema.type:="VaccinationEvent"
$obFormSchema.version:=1

$obFormSchema.json_schema:=New object()
$obFormSchema.ui_schema:=New object()

$obFormSchema.save()
```
