### ISSUE TITLE
Mobile displays twice as many patient history records as there is in reality

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#4743]
## Describe the bug

It seems that mobile display records for 2 stores in it's Patient history on for the current store and one for the remote store. 

Mobile - Patient history
![image](https://user-images.githubusercontent.com/11624516/170878691-40edf31f-937d-444c-b11d-b420bc0c1cd9.png)

Mobile invoices
![image](https://user-images.githubusercontent.com/11624516/170879362-72b8d0d0-66c1-4a5d-bd5a-aaf6324055ac.png)

![image](https://user-images.githubusercontent.com/11624516/170879386-458ddb30-c21b-4e4a-9aec-277c25e1f245.png)

![image](https://user-images.githubusercontent.com/11624516/170879402-51fadd9c-dfc7-4baf-bc2e-c8dda878ef3e.png)

Server
![image](https://user-images.githubusercontent.com/11624516/170879201-0a2a3cb0-5f16-44fe-9c08-16f031830aff.png)

### To reproduce

Steps to reproduce the behaviour:
Used Tonga datafile
1. On mobile, create a couple of vaccinations transaction for the same client
2. Sync. Get to that user Patient history (available on the Client Name's input form
3. Compare to the patient history available on mobile accessible through the Dispensing button and finding the name

### Expected behaviour

I think the real patient history should be created

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v8-5-0Rc1
- Tablet model: Samsung Galaxy Tab A8 
- OS version: Android v8

**Comment by katherine-sussol** [comment]
Looks likely to be a date comparison issue :( - will take a closer look.
The UI is displaying local results and combining with remote server results and filtering out duplicates by itemCode/Date for vaccinations (as many vaccination name notes did not have transaction ids....).

**Comment by katherine-sussol** [comment]
Closed by #4748
