### ISSUE TITLE
NumberSequence sync

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#4766]
## Is your feature request related to a problem? Please describe.

`NumberSequence` and `NumberToReuse` equivalents [on mSupply desktop](https://github.com/sussol/msupply/pull/10889) have had a field for `store_id` added. This was to make sync logic for them work, as we're syncing them now! When mobile syncs with mSupply desktop, it should make sure that at least in translation this value is populated, or go further and store it as a field on the table (would still likely need to translate it though!).

## Describe the solution you'd like

1. Initialise mobile
2. Make some invoices and not invoice number
3. Sync
4. reinitialise
5. Make some invoices, invoice number should continue from where you left off

## Implementation

?

## Additional context

- I can't remember what mobile was already doing here. Perhaps it works out the next "MAX" invoice number from the data when it initialises? Otherwise did it just start from 1 again? Idk!
- Need to do it regardless, otherwise if you convert a mobile site to a desktop site it _will_ start from 1 again.
- https://github.com/sussol/msupply/pull/10889

**Comment by Chris-Petty** [comment]
https://github.com/openmsupply/mobile/blob/80824641c7e16273c75d5750d70f2e13d5e02de9/src/sync/outgoingSyncUtils.js#L112-L127

Well looks like mobile was already syncing them. Cool! I guess it was already getting them on initialisation. Could just make sure that the additional field is included in each case of the above code... basically just add `store_ID: thisStoreId` would be enough?

@JonnaQuismundo, for backwards compatibility do you think v3 API should be making sure this field is populated? Could you check if a mobile site syncing will wipe out the value of `store_ID` on the server for its store? I'm not 100% sure if it would!

**Comment by JonnaQuismundo** [comment]
> https://github.com/openmsupply/mobile/blob/80824641c7e16273c75d5750d70f2e13d5e02de9/src/sync/outgoingSyncUtils.js#L112-L127
> 
> Well looks like mobile was already syncing them. Cool! I guess it was already getting them on initialisation. Could just make sure that the additional field is included in each case of the above code... basically just add `store_ID: thisStoreId` would be enough?
> 
> @JonnaQuismundo, for backwards compatibility do you think v3 API should be making sure this field is populated? Could you check if a mobile site syncing will wipe out the value of `store_ID` on the server for its store? I'm not 100% sure if it would!

@Chris-Petty mobile sync is working fine. Creating records also gets the max number.

**Comment by katherine-sussol** [comment]
As per above, both of these tables are currently already synced with mobile - the app uses the storeID extracted from the 'name' field of the number/number_reuse table to determine whether or not the record corresponds to the current store - i.e. 
![image](https://user-images.githubusercontent.com/65875762/174710937-4da03aed-4004-4e12-b847-1fedd1a38c93.png)

Records are also sent back to desktop in the above format via the v3 api.

I assume (based on @JonnaQuismundo testing above and my testing) the sync V3 API is also using this store ID to determine which store the record belongs to (without needing an extra field populated)? 🤔. Maybe there is a translation step required to ensure it's transferred to (`[number]store_ID`) - but I think in its current form - we're sending over sufficient info for that to be worked out already?

**Comment by JonnaQuismundo** [comment]
@katherine-sussol hi, yes the `store_ID` field depends (string manipulation) on that `[number]name`/`[number_reuse]name` - I believed everything is in place.

**Comment by katherine-sussol** [comment]
Awesome! I have found this related mobile issue: https://github.com/openmsupply/mobile/issues/1401 (reusing numbers for requisitions is not currently working), but believe everything is otherwise working as expected, so will close this issue 🎉

**Comment by JonnaQuismundo** [comment]
@katherine-sussol @Chris-Petty oh, regarding reusing numbers. Seems like mobile doesn't reuse numbers for invoices.
There is a preference setting to reuse numbers for invoices and PO, I'm not sure if mobile is checking that.

![Screen Shot 2022-06-21 at 5 42 45 PM](https://user-images.githubusercontent.com/61759124/174724879-71ddb19c-83b6-4912-88ee-6713feefa21d.png)

![Screen Shot 2022-06-21 at 5 44 49 PM](https://user-images.githubusercontent.com/61759124/174724984-94672f85-4561-42b5-b58a-78cdd32f4f00.png)

As per Requisition - the desktop doesn't reuse the numbers too 😱 Do you know if that is intended? @Chris-Petty
