### ISSUE TITLE
Vaccination event Edit model: Date-picker and date is not updating correctly

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4785]
## Describe the bug

- The date that come in to the form is in the wrong format, and the Date-picker, cannot handle it. It does not bug out but the interface shown would always default to the latest date. 
- Also saving the date has no effect on listing page.

### To reproduce

Steps to reproduce the behaviour:

https://user-images.githubusercontent.com/683452/177276639-d5fa6c1f-af52-4b69-a5e9-997fefdf5a6d.mp4

### Expected behaviour

- Datepicker should show the selected date not today's date.
- The format in form and format after save should be same.
- The saved date should show up in listing page.

### Proposed Solution

- Update Datepicker component of JSONForm, now this is generic component and would affect many forms so must be careful during coding and testing. But I believe the component itself needs to fixed otherwise this issue will show up in many places. 

### Version and device info

- App version:
- Tablet model:
- OS version:

### Additional context

Related to (bug fix for) https://github.com/openmsupply/mobile/issues/4715

**Comment by chastichno** [comment]
Closed as completed in #4786

**Comment by nisha-dangol** [comment]
## Testing
Tested in latest apk

### Tests
- [x] Go to Vaccinations page
- [x] Select vaccination history of one of the patient from online search
- [x] see the date of vaccination
- [x] Select to edit details
- [x] In pages additional details see that the date is in dd/mm/yyyy format.
- [x] click the datepicker button, the date should show properly in datepicker.
- [x] now in the date input box, press backspace to delete the date, it should not error out or say invalid date
- [x] click the datepicker button again, and the picker now should show today's date and let you select other dates
