### ISSUE TITLE
Kiribati: vaccination editing bugs

### ISSUE THREAD

**Issue by chastichno** [openmsupply/mobile#4791]
part of #4715

## Describe the bug

A couple of bugs/improvements in the editing of the vaccination events:

#### 1. Clicking 'Save changes' in editing vaccinator/vaccine has no obvious indication of changes being done. 
To reproduce:
- [ ] Go to 'Vaccinations'
- [ ] Search for a patient who got the vaccination on this tablet. Click on the 'History' button.
- [ ] Select the vaccination. In the last column click the 'Edit' button. Make some changes to the Vaccinator and/or Vaccine.
- [ ] Click 'Save changes' - SEE ERROR, no obvious indication of the transaction being edited. Another issue here is that you can click 'Edit' and 'Save Changes' as many times as you wish and every time it will create a new vaccination (😱)

**Suggested fix**: add an pop-up window at the end saying that the stock levels for the changed item were adjusted and the vaccine was updated

#### 2. Editing 'Additional Details' AFTER editing Vaccinator and Vaccine on the same page will adjust the details for the old vaccination event, not the new one => There should be an order in editing a Vaccination Event ('Extra information' and 'Additional details' first, THEN Vaccinator and Vaccine)
To reproduce:
- [ ] Go to 'Vaccinations'
- [ ] Search for a patient who got the vaccination on this tablet. Click on the 'History' button.
- [ ] Select the vaccination. In the last column click 'Edit' button. Make some changes to the Vaccinator and/or Vaccine.
- [ ] Click 'Save changes', and 'Cancel editing' (don't worry, it is saved, it's just not obvious).
- [ ] Adjust 'Additional Details', for example, the date, click 'Save changes'.
- [ ] Go back to the home page. 
- [ ] Go to 'Vaccinations'
- [ ] Search for a patient who got the vaccination on this tablet. Click on the 'History' button.
- [ ] SEE ERROR - there's one transaction with the corrected vaccine and vaccinator and another transaction with the corrected date.

**Suggested fix**: Alert users to first update the 'Extra information' and 'Additional details' before they click "Edit"

#### 3. Buttons 'Save changes' are a little bit cut off, I guess it has something to do with a line height:
![Screen Shot 2022-07-11 at 3 10 12 PM](https://user-images.githubusercontent.com/41636693/178181661-441e89ce-ed5b-4e1a-a19d-27a8e42b4af4.png)

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model: emulator
- OS version: android

**Comment by chastichno** [comment]
@sworup With the latest changes made in #4798, I guess this issue is not really needed anymore

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest apk

### Tests
1. Clicking 'Save changes' in editing vaccinator/vaccine has no obvious indication of changes being done.
- [x] Go to 'Vaccinations'
- [x] Search for a patient who got the vaccination on this tablet. Click on the 'History' button.
- [x] Select the vaccination. In the last column click the 'Edit' button. Make some changes to the Vaccinator and/or Vaccine.
- [x] Click 'Save changes' - indication of the transaction being edited. 
- [x] Clicking 'Edit' and 'Save Changes' many times will NOT create a new vaccination - pop-up window at the end saying that the stock levels for the changed item were adjusted and the vaccine was updated

2. Editing 'Additional Details' AFTER editing Vaccinator and Vaccine on the same page will adjust the details for the old vaccination event, not the new one => There should be an order in editing a Vaccination Event ('Extra information' and 'Additional details' first, THEN Vaccinator and Vaccine)
- [x] Go to 'Vaccinations'
- [x] Search for a patient who got the vaccination on this tablet. Click on the 'History' button.
- [x] Select the vaccination. Adjust 'Additional Details', for example, the date, click 'Save changes'.
- [x] In the last column click 'Edit' button. Make some changes to the Vaccinator and/or Vaccine.
- [x] Click 'Save changes'
- [x] Go back to the home page.
- [x] Go to 'Vaccinations'
- [x] Search for a patient who got the vaccination on this tablet. Click on the 'History' button.
- [x] There's only one transaction with the all the changes.

3. Buttons 'Save changes' are a little bit cut off, I guess it has something to do with a line height:
- [x] No more cut-off texts in buttons
