### ISSUE TITLE
Kiribati: Prevent giving vaccine to deceased patient

### ISSUE THREAD

**Issue by chastichno** [openmsupply/mobile#4792]
## Is your feature request related to a problem? Please describe.

Do not proceed if a patient is deceased, alert.

![image](https://user-images.githubusercontent.com/19318937/178619194-d0eee019-46c2-48d2-b613-9ec15cb41113.png)

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

[trello issue](https://trello.com/c/Tkz880xw/69-13b-prevent-giving-vaccine-to-deceased-patient)

**Comment by chastichno** [comment]
Closed as completed

**Comment by nisha-dangol** [comment]
## Testing
Tested in latest mobile v8.5.0 apk

### Tests
1. 
- [x] Go "Vaccination" -> Search for patients
- [ ] Select a patient who you know is deceased -> see an alert.
- [ ] Clicking "OK" closes an alert, you stay on the same page.

Hi @chastichno 
I don't see any `is deceased` or such options in the patient details. Also, the ADR details I add to the patient (for example, I definitely saved an ADR form with 'Died' outcome for the patient), synced it but those details don't seem to update, and thus the vaccination event can be added for a dead patient! Created the issue [here](https://github.com/openmsupply/mobile/issues/4815)

**Comment by chastichno** [comment]
Here is the video that shows where you can find a "deceased" property of a patient:

https://user-images.githubusercontent.com/41636693/180337547-99763650-8139-4822-ab0b-141524034c02.mov

The ADR form, I believe, does not affect the actual details of the patient. I'll take a look at that issue though.

**Comment by nisha-dangol** [comment]
> Here is the video that shows where you can find a "deceased" property of a patient:
> 
>  Screen.Recording.2022-07-22.at.12.36.37.PM.mov 
>
I definitely don't see that (is deceased) option in the latest apk. Weird!
See [this recording](https://user-images.githubusercontent.com/59193490/180364653-4e335f43-3441-4f88-8ce5-4c420aeb0b1c.mp4)!

**Comment by chastichno** [comment]
@nisha-dangol I wasn't able to replicate this. Could you please send me your data file? Also, what version of mSupply desktop are you using?

**Comment by nisha-dangol** [comment]
> @nisha-dangol I wasn't able to replicate this. Could you please send me your data file? Also, what version of mSupply desktop are you using?

The server is on v6-02-00-rc8 and [here's](https://www.dropbox.com/s/nhi6z5lcpa42afn/kiribati_vax.7z?dl=0) the datafile.

**Comment by nisha-dangol** [comment]
## Testing
Tested in latest apk

### Tests
1.
- [x] Go "Vaccination" -> Search for patients
- [x] Select a patient who you know is deceased -> see an alert.
- [x] Clicking "OK" closes an alert, you stay on the same page.

2.
- [x] Go "Vaccination" -> Search for patients
- [x] Select a patient who you know is editable on the current site. Edit patient window opens.
- [x] Change "Is deceased" to "Yes", click "Next" -> see an alert.
- [x] Clicking "OK" closes an alert, you stay on the same page.

3.
- [x] Go "Vaccination" -> Search for patients
- [x] Click "New patient". Edit patient window opens.
- [x] Change "Is deceased" to "Yes", click "Next" -> see an alert.
- [x] Clicking "OK" closes an alert, you stay on the same page.

4.
- [x] Go to "Vaccination" or "Dispensing". Select any patient to edit.
- [x] Toggles for "Gender" and "Is Deceased" must be displayed correctly in both of the cases:
     - [x] If patient is editable on the current site
     - [x] If patient is not editable on the current site

Hi @chastichno, I'm not quite sure if the last test (No. 4) can be tested correctly with my datafile.
Could you send me the link to your datafile, the one you're using for the test? It seems that the in the anonymised datafile we're using (created by @anildahalsussol ), @sworup and I have noticed that all the patients (be it in their current home site or belonging to other mobile site) are all editable in the logged-in mobile store. All patients show the editable icon (pen icon) regardless of their original home store.

**Comment by sworup** [comment]
Yes, it seem, it is following the store pref of can edit patients from any store which is set to true for the store and no way in mobile and desktop to set it to false.

**Comment by nisha-dangol** [comment]
Moving to Done, since this is fixed now, after running the FC code!
