### ISSUE TITLE
Kiribati: soft delete of vaccinations

### ISSUE THREAD

**Issue by chastichno** [openmsupply/mobile#4796]
## Is your feature request related to a problem? Please describe.

After editing a vaccination current vaccination should become "deleted" and should not be visible in the UI.
So two things need to be done:
1. Make deleted vaccinations (vaccinations with `NameNote.isDeleted=true`) to be not visible to the users @adamdewey please confirm
2. Add a "Delete" button to the "Edit vaccination event" page

--------

### More context: 

**User Stories:** 
 
![image](https://user-images.githubusercontent.com/19318937/178615544-f5ab29f0-b073-41a8-8594-91e02f49aff4.png)

**Proposed solution**

- The system will be updated to allow deletion of vaccination events
- The system will be updated to make automatic stock inventory adjustments when deleting a vaccination event (e.g. the issuing store will be refunded the vaccine stock that was erroneously recorded as being administered to the patient).
- Deleted vaccination events will be kept in the back-end for auditing purposes.
- Users won't be able to delete vaccinations that were given on a different tablet - so we need to have a pop-up message telling them which tablet to use instead do delete the vaccination

**This is what is meant by a 'vaccination event':** 

![image](https://user-images.githubusercontent.com/19318937/178616373-184535b0-f798-46af-ba10-1dde72250e91.png)

![image](https://user-images.githubusercontent.com/19318937/178616154-e509ca06-c614-419b-841a-b6f9903585d3.png)

## Describe the solutions you'd like

For the "Delete" button I think we should implement it through user going to the "Edit vaccination event" page, then clicking "Edit" and then after "Vaccinator" and "Vaccine" DDLs there should be button "Delete".
Deletion must prevent users from editing this name note anymore.

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by adamdewey** [comment]
@chastichno

1. Yes, exactly - soft deleted vaccinations should not be visible to the users in the Mobile UI
2. That sounds good - we should make it so it's quite difficult to delete so the user only does it if they are really sure. E.g. give them a warning, and maybe make the button not very obvious (hide in a kebab menu?)

**Comment by adamdewey** [comment]
Just to be clear, so there's no confusion about what it means to delete a 'vaccination event', I will update the issue description with some relevant information from the Trello card

**Comment by adamdewey** [comment]
@chastichno - have added some more info to the issue description, could you have a read through and let me know if it needs clarifying? Cheers!

**Comment by chastichno** [comment]
Closed as completed

**Comment by nisha-dangol** [comment]
## Testing
Tested in local apk 8.4.2 built by @sworup for testing

### Tests
- [x] Go to "Vaccination" -> search for a patient.
- [x] Select "History" for a patient with the vaccination events entered on the current site.
- [x] Select one of the vaccination events. Click "Edit" in the last column, click "Delete ...".
- [x] See confirmation window. Click "Cancel" -> confirmation window closes.
- [x] click "Delete ...". again, but this time click "Confirm" -> You see all three forms again, all the buttons are disabled, you cannot do any changes anymore.
- [x] Close it. Sync. Go to "Vaccination" -> Select "History" for this patient again -> see that the deleted vaccination event is not there anymore.
- [x] Select another vaccination event. Click "Edit". Do some changes, click "Save" -> buttons will become disabled, you cannot change it anymore.
- [ ] Close it. Sync. Go to "Vaccination" -> Select "History" for this patient again -> see the edited vaccination event 
Noticed some bugs here. @sworup says it is an existing bug. Created an issue [here](https://github.com/openmsupply/mobile/issues/4805)

**Comment by sworup** [comment]
@nisha-dangol 
The test case failing above is an issue and it had to have an issue created but it is not related to the code in this PR. I think @chastichno added it here for regression testing of the features flow.

The tests actually related to the code in this PR seems be passing and I think this PR can be considered done in that regard. We can mark it as passing tests.

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest apk

### Tests
- [x] Go to "Vaccination" -> search for a patient.
- [x] Select "History" for a patient with the vaccination events entered on the current site.
- [x] Select one of the vaccination events. Click "Edit" in the last column, click "Delete ...".
- [x] See confirmation window. Click "Cancel" -> confirmation window closes.
- [x]  click "Delete ...". again, but this time click "Confirm" -> You see all three forms again, all the buttons are disabled, you cannot do any changes anymore.
- [x] Close it. Sync. Go to "Vaccination" -> Select "History" for this patient again -> see that the deleted vaccination event is not there anymore.
- [x] Select another vaccination event. Click "Edit". Do some changes, click "Save" -> buttons will become disabled, you cannot change it anymore.
- [x] Close it. Sync. Go to "Vaccination" -> Select "History" for this patient again -> see the edited vaccination event (in fact it is a completely new one, the old one is hidden but 🤫)

**Comment by sworup** [comment]
@nisha-dangol The issue coming from this issue has been moved to testing done this can go there as well.
