### ISSUE TITLE
Kiribati: a pop-up message to contain the name of the store where vaccination was made

### ISSUE THREAD

**Issue by chastichno** [openmsupply/mobile#4801]
## Is your feature request related to a problem? Please describe.

Currently, a pop-up message comes out when you try to edit a vaccination record that was entered on a different tablet. This message, however, does not include the name of the store (we simply didn't capture that information before). 

## Describe the solution you'd like

With the vaccines that would be entered after the next release, Store name is going to be saved on a vaccination event so we can tell users what tablet was used.

## Implementation

Check if vaccination event contains details about the dispensing tablet (Store name and store ID) and if so show the name of the store to the user who attempts to edit the vaccination event.

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest apk

### Tests
- [x] Use a data file with the vaccination module set up and some vaccinations already dispensed. You will need two tablets with two different stores set up on them (let's say "Tablet 1" (with "Store 1") and "Tablet 2" (with "Store 2").
- [x] On "Tablet 1" some vaccination events should be entered for "Patient 1" (before this version upgrade).
- [x] Log in "Tablet 2" and go to "Vaccination" -> Open "Patient 1" history. Click on any vaccination event.
- [x] In the last column click "Edit" -> see an alert that says you have to find a tablet where vaccination was made.
- [x] Using "Tablet 1" add another vaccination event for "Patient 1".
- [x] On "Tablet 2" go to "Vaccination" -> Open "Patient 1" history. Click on the latest vaccination event.
- [x] In the last column click "Edit" -> see an alert that specifies that you have to use "Store 1" tablet to edit this vaccination event.
