### ISSUE TITLE
Kiribati: Delete patient medical record

### ISSUE THREAD

**Issue by chastichno** [openmsupply/mobile#4802]
## Is your feature request related to a problem? Please describe.

Add soft deletion of the patients to the "Patient Details" page.

--------

### More context: 

**User Stories:** 
![2022-02-28_10-13-21](https://user-images.githubusercontent.com/41636693/178885802-84875730-cde4-4db4-9ae8-a8388ebd7f2f.png)

### Proposed solution

- The system will be updated to allow deletion of patient medical records via mSupply Desktop.
- Vaccination events associated with the deleted patient medical record will also be deleted. 
- The system will be updated to make automatic stock inventory adjustments when deleting a vaccination event (e.g. the issuing store will be refunded the vaccine stock that was erroneously recorded as being administered to the patient). 
- Deleted patient medical records and vaccination events will be kept in the back-end for auditing purposes. 

Some other proposed solution details:
- **If there are vaccines dispensed to the patient on a different tablet - it will not be deleted!**
- If there are any dispensary transactions made with this patient on the current tablet, the patient will not be deleted.
- All the vaccination events associated with this patient will be deleted, and stock will be returned.

## Implementation

Not sure yet

## Additional context

Trello card: [(1.7.g + 1.7.h + 1.7.i) Delete patient medical record](https://trello.com/c/DpudXeHa/76-17g-17h-17i-delete-patient-medical-record)

- I'm not sure if there's a way of checking if this patient had transactions on another tablet. As we soft delete it shouldn't cause any problems even if there are any transactions on the other tablet. However, Adam reassured me that they do not use dispensing module at all.

**Comment by sworup** [comment]
@chastichno @adamdewey for this issue:

Added a delete button the Patient delail interface
![Screen Shot 2022-07-19 at 4 37 47 PM](https://user-images.githubusercontent.com/683452/179733731-7b01e7a4-6951-4724-ab74-8575469686f1.jpg)

Here's what I am going to do.

1. This delete button will only be active if vaccine events of this patient do not have any entries. Vaccine event entries would have to be at least soft deleted. @chastichno has already done the soft deletion of vaccine entries part.
2. If there are no active (not isDeleted) vaccine entries linked to the patient we will allow deletion, at which point we would soft delete the patient.

Is there anything else needing to be done?

**Comment by adamdewey** [comment]
@sworup that sounds perfect!

Can we make sure there is a confirmation dialogue for the user in case they accidentally press the button?

Cheers

Adam

**Comment by sworup** [comment]
Merged with https://github.com/openmsupply/mobile/pull/4812

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest apk [here](http://t.ly/vwPC)

### Tests
- [x] Go to patients list
- [x] Open the patient detail of one of the patients, who has vaccine history
- [x] See the delete button 
- [x] Now go back to patients list
- [x] Select and open patient details of one of the patients whom you know- does not have active vaccine history
     - [x] Vaccine history that is deleted are not counted - **IDK what that means, but I created a patient, added vaccination event for them, deleted that vaccination event and deleted the patient and then in Online Lookup, on searching for that (deleted) patient, it shows up!**
- [x] See the delete button and see it enabled. 
- [x] Click the delete button, a popup will show asking you if you are sure
- [x] Select no; you go back to the patients details
- [x] Select yes and the patient will be soft deleted
- [ ] Check patient list, patient list search, vaccine patient selection windows, the soft deleted patient should not show up in the list. - **The patient shows up in the Lookup window in Vaccinations (type patient first & last names, and hit `Search Online` button. The deleted patient will show up)**
- [ ] This affects at least in UI in New patient creation button and form too so please check it works too.

**Comment by nisha-dangol** [comment]
Moving to Done since related issue already created https://github.com/openmsupply/mobile/issues/4842

**Comment by sworup** [comment]
The issue stemming from this issue is fixed but that fix stemmed another issue.
@nisha-dangol we can set this one to testing done as future bigs will be handled by future sisues.
