### ISSUE TITLE
Editing vaccination event detail is very inconsistent

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4805]
## Describe the bug
Upon editing the vaccination event details (any of vaccine details, doses, dates, or any) and syncing, the edited changes do not show up correctly. This is very inconsistent that some (edited) records are updated while others are not.

In below example, I've clearly changed the vaccine name, date, dose type, arm(left/right), vaccinator and such, but after editing and syncing, not all changes are not reflected; notice that vaccine name and vaccinator are updated/edited, but not the dose type, date and arm values.

### To reproduce
Steps to reproduce the behaviour:
1. Create a vaccination event and confirm.
2. Now go to the same patient history and edit the details.
3. Make sure to make many changes, from dose types, dates, arms to vaccines and vaccinators (more changes, better)
4. Sync, make sure it syncs well (I manually synced twice everytime)
5. Now open that same event record and notice the inconsistency: some field values are edited, some are not!
See the [recording!](https://user-images.githubusercontent.com/59193490/179503951-7d2730c0-db90-4928-b051-1cdec486585f.mp4)

### Expected behaviour
Edited values must be consistent.

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version:

### Additional context
Found while testing #4796

**Comment by sworup** [comment]
I will pick this up soon. But anyone else wants to pick it before me... be my guest. 😄

**Comment by sworup** [comment]
Closed by https://github.com/openmsupply/mobile/pull/4807
