### ISSUE TITLE
ADR details for a patient is not saved in mobile

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4815]
## Describe the bug
When adding ADR form for a patient, the records are created and synced as well. But upon checking the ADR details, while fetching data from server, it displays nothing!

### To reproduce
Steps to reproduce the behaviour:
1. In sync setup with a mobile, create or use any patient.
2. Go to Dispensing>>ADR
3. Add ADR details. (for example, I definitely saved an ADR form with 'Died' outcome for the patient) and Save
4. Sync. Notice that created records are syncing as well
5. Click the ADR again.
6. Notice the loading message as `fetching patient history from server`
7. But afterwards, the previously saved records aren't there anymore. Weird?

### Expected behaviour
The previously saved ADR records should display on mobile as well?

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest 8-5-0 apk built by @sworup 

### Additional context
Observed while testing #4792

**Comment by chastichno** [comment]
@nisha-dangol From what I can see in the [documentation](https://wiki.msupply.foundation/en:mobile:user_guide:adverse_drug_reactions#adverse_drug_reaction_reporting), there's no option to see past ADR in mobile, however, they can be displayed in the dashboard. I'm not sure though how we can see the actual ADRs for the patient.

**Comment by chastichno** [comment]
@mark-prins Thank you for the explanation. I have one more question. How are those ADR notes are being used then? Who receives it after it is submitted?

**Comment by mark-prins** [comment]
no one really - it was a request when we started with the vaccination process in Tonga, but the rest of the process - how to handle and review, wasn't really considered fully. We also have the online ADR form, but that is not used as far as I know

**Comment by chastichno** [comment]
@nisha-dangol I'm closing this issue as it is not valid
