### ISSUE TITLE
Installing new apk over the existing old version leads to crashing

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4816]
## Describe the bug
With an initial version mSupply installed already, when you install the new apk, the app doesn't work anymore; it keeps crashin and won't even open

### To reproduce
Steps to reproduce the behaviour:
1. Make sure you have mSupply (old version) installed already.
2. Install the new apk
3. Open it.
4. See error : it keeps crashing!
5. But, if you fresh install (uninstall old version and re-install), it does work!

### Expected behaviour
No crash at all!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest 8-5-0 built by @sworup

**Comment by nisha-dangol** [comment]
Moving to Done since this is already fixed!

**Comment by sworup** [comment]
This was app key problem and has been fixed
