### ISSUE TITLE
Editing or deleting vaccination events are not reflected in the patient history

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4822]
## Describe the bug
After editing or deleting the vaccination event for a patient, the changes are reflected properly in the vaccination history, but not in the patient history, i.e, the deleted or edited records are being displayed in patient history, when they actually should be hidden!

### To reproduce
Steps to reproduce the behaviour:
1. Select a patient and create a vaccination event (let's suppose First Dose)
2. Now open that vaccination event and edit some details (maybe make it Second Dose or change the vaccine details)
3. Now Go to Dispensing>>that Patient>>History
4. See error: You'll see two records (both initial one and the latest/edited one as well.
5. Try deleting that vaccination event and check again. The record has not been deleted from the Patient History.

### Expected behaviour
Show only the latest data in Patient Record, no any older or deleted records should show anymore.

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest apk built by @sworup 

### Additional context
Found while testing #4796

**Comment by chastichno** [comment]
@nisha-dangol 
Hi Nisha, thank you for the testing.
I'm not sure which build you used but I can't really replicate it:

https://user-images.githubusercontent.com/41636693/181387210-5ad943cb-fe7c-4eb6-8a68-d8c29f9cd7b7.mov

The only place where I can see the previous vaccinations is customer invoices history - but after each customer invoice, there's a customer credit, which is expected.

**Comment by sworup** [comment]
@nisha-dangol @chastichno yes, this is patient history and it tracks patient's dispensing transactions as well as vaxine record. Upon further testing I did realise that vaccine history was tracking correctly in this window.
Closing the issue.

**Comment by sworup** [comment]
@nisha-dangol @chastichno yes, this is patient history and it tracks patient's dispensing transactions as well as vaxine record. Upon further testing I did realise that vaccine history was tracking correctly in this window.
Closing the issue.

**Comment by nisha-dangol** [comment]
Moving to Done as can't be replicated anymore in latest apk
