### ISSUE TITLE
mSupply crashes when changing the vaccine to the one that is not in stock currently

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4823]
## Describe the bug
When changing the vaccine details to a new one(the one that is not available in stock), the whole app crashes, instead of some alert message.

### To reproduce
Steps to reproduce the behaviour:
1. Make sure you have multiple vaccines, some with stock some with none
2. Make a vaccination event with some vaccine that is in stock initially.
3. Now edit it to the out-of-stock vaccine this time
4. See error: the app crashes!

### Expected behaviour
App should not crash at all!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Additional context
Recording [here](https://user-images.githubusercontent.com/59193490/180945217-7bd6559f-274d-46a1-8ad4-1726c6181d8c.mp4)

**Comment by chastichno** [comment]
@adamdewey

**Comment by chastichno** [comment]
@sworup I can pick up this one if you haven't started yet

**Comment by sworup** [comment]
> @sworup I can pick up this one if you haven't started yet

Ok carry on @chastichno

**Comment by sworup** [comment]
Merged and closed with #4848

**Comment by nisha-dangol** [comment]
## Testing
Tested in [latest](http://t.ly/K3Xv) apk

### Tests
- [x] Use a file with some vaccines out of stock
- [x] Go to vaccination -> see history for any patient -> select any vaccination event -> edit it. See in vaccine dropdown list that there are no vaccines out of stock
