### ISSUE TITLE
Dispensing/Prescriptions does not work properly like before

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4825]
## Describe the bug
If I remember correctly, previously we used to be able to dispense patients and create prescriptions on mobile. Now, after vaccination module, I can't seem to dispense or create the prescriptions anymore from the Dispensing module. Is it intended (because of vaccination module) or just another bug?

### To reproduce
Steps to reproduce the behaviour:
1. Go to Dispensing
2. Choose a patient and then a prescriber
3. See error: notice that no any items appear in the list despite the available stocks. And since you can't add items, you won't be able to continue and thus can't create any prescription.

### Expected behaviour
Shouldn't dispensing work normally like before? Or is there any changes now?

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version:
- Tablet model:
- OS version:

**Comment by chastichno** [comment]
@nisha-dangol 
Sorry, Nisha, I cannot really replicate it:
![Screen Shot 2022-07-28 at 11 12 45 AM](https://user-images.githubusercontent.com/41636693/181388211-7084bd99-bf87-4014-aca0-5a3613f5f19d.png)

**Comment by nisha-dangol** [comment]
> @nisha-dangol Sorry, Nisha, I cannot really replicate it
>
Wow, that's really weird. I caught this issue on [this apk](http://t.ly/vwPC).
For me, after adding patient & prescriber, it doesn't show any list of items (even though there are stocks of items/vaccines available) and thus cannot proceed with the prescription.
![Screenshot_20220728-103221_mSupply-Mobile](https://user-images.githubusercontent.com/59193490/181423083-25e90416-fd10-44af-af9e-8498a5ec03fd.jpg)

**Comment by nisha-dangol** [comment]
Ok, so it turns out that items which are vaccine do not display in the item list for prescription as said by @sworup. Only non-vaccine items can be dispensed. 
Tested and confirmed. So, closing this!

**Comment by sworup** [comment]
Evidence:
https://github.com/openmsupply/mobile/blob/80824641c7e16273c75d5750d70f2e13d5e02de9/src/reducers/PrescriptionReducer.ts#L10
