### ISSUE TITLE
Kiribati Vax: Lookup patient is overwriting the changes done in patient detail

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4841]
## Describe the bug

A clear and concise description of what the bug is. Use screenshots!

### To reproduce

1. Go to dispensing and select patient name
2. Click on edit and then edit ID (identification info like citizen) and save
3. Now go back and select the name from the look-up patient.
4. Open the same name and see the ID.

### Proposed Solution

- Since lookup is overriding the local data and the we need a viable simple solution we can do this.
  - Lookup will query all data on server like it does right now.
  - When the user clicks on the item, we check internally to see if that record exist in our database already.
  - If the record exists we do not pull that data from the server (no db update) we show the data from database even if it is old.
    - We are expecting sync will take its normal course and adjust that data especially since now we are restricting patient edit to one store.
  - If the record does not exist on our database then we pull the data.

### Version and device info

- App version: 8.4.2.20220727
- Tablet model:Samsung
- OS version:

**Comment by arjunSussol** [comment]
@anildahalsussol @sworup @adamdewey @ujwalSussol and more I have added a proposed solution.
Could you all review it and help to make a concrete agreed solution.
After that I will try to fix it.
For now, I am looking at its work flow and codes.

**Comment by arjunSussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile: #4841: Kiribati Vax: Lookup patient is overwriting the changes done in vaccination event](https://trello.com/c/zwMioLjG/536-mobile-4841-kiribati-vax-lookup-patient-is-overwriting-the-changes-done-in-vaccination-event)

**Comment by sworup** [comment]
@arjunSussol @anildahalsussol @adamdewey @chastichno I have updated the proposed solution for this issue. This solution can be the simplest and most viable solution for now.

Another solution is to compare last edited dates, but if we want the data to show the latest iteration we might have to merge data which would need some planning. 

If we plan to compare dates and only pull if the dates are same then it's pretty much as the solution I mention above.

**Comment by sworup** [comment]
Resloved with https://github.com/openmsupply/mobile/pull/4882
