### ISSUE TITLE
Kiribati vax: Deleted patients again shows up

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4842]
## Describe the bug

Deleted patients again show up on tablets.

Related to https://github.com/sussol/msupply/issues/11303

### To reproduce

Steps to reproduce the behaviour:

1. Create a name and sync.
2. Once it's synced ask another tablet say B to sync.
3. Now that name must be visible to another tablet as well.
4. Start creating vaccination event from tablet B and delete the name from tablet A.
5. After event is done and sync from tablet B to server.
6. Now sync tablet A and check patient and search online.
7. See error.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:8.4.2.20220727
- Tablet model:Samsung
- OS version:

**Comment by sworup** [comment]
Our vax system is not designed to allow patient records to be editable by all stores that. It should (for now until we build proper sync logic) only allow the store owning the patient to edit that patient. 
**But in mSupply store pref there is a setting to allow patients to be editable from all store.**
I think we can start with disabling this pref by default for kiribati vax customisation. 
Now this would probably mean all data should be resynced. 

@anildahalsussol @chastichno @adamdewey @ujwalSussol opinions please.

**Comment by adamdewey** [comment]
@sworup - hmm, 2 things: 

1. We need to be able to somehow tell them which tablet they need to use to edit the patient, they can't try all 40 tablets until they find the right one. (Possibly a dashboard report would be sufficient)
2. We need to be careful about re-syncing data, it would be a big effort for that much data in Kiribati, especially for 40 tablets. Would need extra coordination with the Kiribati team during the upgrade process

**Comment by sworup** [comment]
> 1. We need to be able to tell them which tablet they need to use to edit the patient, they can't try all 40 tablets until they find the right one. (Possibly a dashboard report would be sufficient)

- Will create an issue for this.

> 2. We need to be careful about re-syncing data, it would be a big effort for that much data in Kiribati, especially for 40 tablets. Would need extra coordination with the Kiribati team during the upgrade process.

- @adamdewey It is just 1 pref boolean that gets updated not all data so if we set this boolean during initial tablet update we should be fine.
- We run this footrunner code https://github.com/openmsupply/mobile/issues/4876#issuecomment-1212762457 in mSupply and have all the tablet sync the all stores can edit patient boolean pref.

**Comment by sworup** [comment]
@nisha-dangol our `all stores can edit patient = false` boolean should have fixed this. 
I am going to close this and put this in ready for testing. Please reopen if the problem exists.

**Comment by sworup** [comment]
@nisha-dangol just showed me that this still exists, reopening and working on it.

**Comment by sworup** [comment]
https://trello.com/c/S6USfNti/95-deleted-patients-again-shows-up

**Comment by sworup** [comment]
Resolved with https://github.com/openmsupply/mobile/pull/4881

**Comment by nisha-dangol** [comment]
Issue found [here](https://github.com/openmsupply/mobile/issues/4885), so will be re-tested with #4885

**Comment by sworup** [comment]
The issue stemming from this issue is fixed but that fix stemmed another issue.
@nisha-dangol we can set this one to testing done as future bigs will be handled by future sisues.
