### ISSUE TITLE
kiribati Vax:  Editing vaccination event, clicking save buttons multiple times quickly  is crashing apps and which is corrupting the record

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4844]
## Describe the bug

While editing vaccination events and saving application crashes and while reopening the apps and seeing the history for the same patients it shows blank.

### To reproduce

Steps to reproduce the behaviour:

1. Goto vaccination.
2. Select any patient and click on history.
3. Select the event that you are allowed to edit otherwise it will show the alert which is nice 👍
4. Now after editing try to click save multiple times which will crash the application.
5. Now reopen the application and select same patient and check same history.
6. See error

### Agreed Solution

- This happens when you click save multiple times. So we need to disable save button after 1st click and not enable it until we get a response back from the server or database.

### Version and device info

- App version: 8.4.2.2022727
- Tablet model:Samsung
- OS version:

**Comment by sworup** [comment]
Fixed with #4851

**Comment by sworup** [comment]
Fixed with #4851

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest [apk](http://t.ly/6cOv)

### Tests
- [x] Go to any vaccination event that you can edit from the current tablet
- [x] Click "Save changes" with no changes - alert is shown, the button is back to be enabled
- [x] Change vaccination or vaccine, try to click "Save" multiple times - shouldn't be allowed.
