### ISSUE TITLE
Chopped Done: Label Done is chopped while creating CI from masterlist

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4847]
## Describe the bug

Label Done is chopped while creating CI from masterlist

### To reproduce

Steps to reproduce the behaviour:

1. Goto create customer invoice.
2. Add an items from masterlist.

### Expected behaviour

Label done should not be chopped

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 84.20220727
- Tablet model:Samsung
- OS version:

**Comment by arjunSussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile: #4847 Chopped Done: Label Done is chopped while creating CI from masterlist](https://trello.com/c/JDzoeLPl/525-mobile-4847-chopped-done-label-done-is-chopped-while-creating-ci-from-masterlist)

**Comment by sworup** [comment]
Merged with #4865
