### ISSUE TITLE
Save and delete button are still showing active for remote patients in patient edit

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4849]
## Describe the bug

- CAN_EDIT_PATIENTS_FROM_ANY_STORE is supposed to be false for Kiribati Vax code as if we allow any store can have edit rights for all other store's patients, there are all sorts of data override over sync errors.
- CAN_EDIT_PATIENTS_FROM_ANY_STORE is set from mSupply store pref where the boolean is set to true by default
- This issue does not set CAN_EDIT_PATIENTS_FROM_ANY_STORE to false but presumes if it is.

- In such case save and delete button was still showing for remote patients

### To reproduce

Steps to reproduce the behaviour:

1. Set CAN_EDIT_PATIENTS_FROM_ANY_STORE pref to false
2. Go to Dispensing page.
3. In edit column you would see the book icon (not the pen icon). This means the record is read only.
4. Click edit to go inside.
5. See that save and delete button are both active when this record should be read only. Even the left side patient detail form is disabled.

### Expected behaviour

- Treat patient records created in other stores as read only data, the can be viewable but should not be editable or delatable.

### Proposed Solution

Update the logic to treat patient records created in other stores as read only data, the can be viewable but should not be editable or delatable.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by sworup** [comment]
Merged with #4850

**Comment by nisha-dangol** [comment]
## Testing
Tested in the latest http://t.ly/6cOv

### Tests
- [x] Set CAN_EDIT_PATIENTS_FROM_ANY_STORE pref to false. mSupply desktop has default pref that sets CAN_EDIT_PATIENTS_FROM_ANY_STORE to true. Have to disabled. - Ran the FC code for this!
- [x] Go to Dispensing page
- [x] In edit column you would see the book icon (not the pen icon). This means the record is read only. These patient records are created in other store and should not be editable in this store.
- [x] Click icon (book) to go inside.
- [x] See that save and delete button these should be inactive.
