### ISSUE TITLE
App hangs/keeps on loading forever when OK button is clicked multiple times while entering a vaccination event

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4871]
## Describe the bug

While creating a vaccination event, enter all details and finally tap on the Confirm button a multiple times and see that it keeps on loading forever.
  
### To reproduce

Steps to reproduce the behaviour:
1. Go to Vaccination
2. Select patient and enter details
3. Choose vaccine and prescriber
4. Click `Confirm` button multiple times 
5. See error: the loading won't stop!
6. Good thing at least the entered vaccination event is saved; you can restart and see that data saved.

### Expected behaviour
App should not hang like that!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest apk [here](http://t.ly/6cOv)

**Comment by sworup** [comment]
Resolved with https://github.com/openmsupply/mobile/pull/4880

**Comment by nisha-dangol** [comment]
## Testing
- [x] Go to Vaccination
- [x] Select patient and enter details
- [x] Choose vaccine and prescriber
- [x] Click Confirm button multiple times
- [x] See no error
- [x] Check that vaccination event was saved.

Hi @chastichno This seems to work for the `Confirm` button in the Vaccination confirmation page. But this can still be recreated for the `Ok&Next` button. Issue [here](https://github.com/openmsupply/mobile/issues/4886)

**Comment by nisha-dangol** [comment]
Tested in the [latest](http://t.ly/0uZv) apk.
