### ISSUE TITLE
Kiribati Vax: Patient is editable from multiple tables causing sync problems

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4876]
## Description

- the patient is editable from all stores as of the default pref and that pref is hardcoded and set by a footrunner in mSupply. 
- Mobile was created so that one store would do the editing. We do have check or data comparison and merge capabilities (at least in mobile) side to handle cases where multiple online and offline tables are making changes to the same data and it all merges and resolved conflict to get a final latest data snapshot.
- So when we lookup data that already exist in our database and click the data it updates the data we have right now. Now imagine a case where multiple mobile stores are trying to edit the same data. The sync would have a race condition where latest data wins, overriding all previous data.

### To reproduce

Steps to reproduce the behaviour:

1. Create a name and create an event and sync to the server from tablet A.
2. Sync tablet B and that name must be visible.
3. That patient is editable in tablet B which is weird actually I think only Homestore must be allowed to edit.
4. And now sync and now search online for that name.
5. And see the Is deceased Boolean.
6. See error.

### Expected behaviour

- Other stores where patient was not created in should not be abled to edit the patient.

### Proposed Solution

Run footrunner code in mSupply to disable allow all stores to edit patient boolean.

**Comment by sworup** [comment]
This footrunner code should lock editing of patient to the table from which the Patient originated. This is a temporary fix to make things to work for Kiribati Vax for now as allowing all stores to edit patients is causing a lot of sync trouble we have to discuss and try and fix properly.

```
C_COLLECTION($cStoreIDs; $cPreferences)
C_OBJECT($1; $obPref; $obPrefsToUpdate; $obDefaultOptions; $obClone; $obStore;  $obStorePreferenceToToggle)
C_TEXT($tStorePreferences)


$tStorePreferences:= "store_preferences"

pref_setAllowPatientUpdates(True)

$cPreferences:= New collection(New object("pref"; "can_edit_patients_from_any_store"; "enabled"; False); \
New object("pref"; "can_view_all_patients_history"; "enabled"; True))

$obDefaultOptions:= New object("storeIDs"; ds.store.all().ID; "preferences"; $cPreferences)

$cStoreIDs:= $obDefaultOptions.storeIDs

$obPrefsToUpdate:= ds.pref.query("store_ID in :1 and item = :2"; $cStoreIDs; $tStorePreferences)

For each($obPref; $obPrefsToUpdate)
$obClone:= $obPref.toObject()

	For each($obStorePreferenceToToggle; $obDefaultOptions.preferences)
$obClone.data[$obStorePreferenceToToggle.pref]:=$obStorePreferenceToToggle.enabled
$obPref.data:=$obClone.data

$obStore:= ds.store.get($obPref.store_ID)
log_create("Footrunner"; "Setting preference '" + $obStorePreferenceToToggle.pref + "' to " + String($obStorePreferenceToToggle.enabled) + " for:" + $obStore.name)
	End for each

	$obPref.save()

	If(sync_on_primary)
		sync_create_syncout_record_UUID(Table(-> [pref]); "U"; $obPref.ID; 3; $obPref.store_ID)
	End if

End for each
```

[z_toggleDangerousPatientMode.txt](https://github.com/openmsupply/mobile/files/9314059/z_toggleDangerousPatientMode.txt)

**Comment by sworup** [comment]
The footrunner fixes this issue.

**Comment by nisha-dangol** [comment]
Moving to Done since this was already tested as part of #4849
