### ISSUE TITLE
Kiribati Vax: In patients detail window, show which store the patient was created on

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4877]
# Description

https://github.com/openmsupply/mobile/issues/4842#issuecomment-1203925482

> Adam: We need to be able to tell them which tablet they need to use to edit the patient, they can't try all 40 tablets until they find the right one. (Possibly a dashboard report would be sufficient)

### Expected behaviour

- Currently patient is only editable by its home store. But in other tablets (with other stores), we need to at least show which store they can go to, to edit this patient. Of course they would need physically use that tablet but having the store name available at least makes things easier for the client.

### Proposed Solution

- We can show it in patient detail window somewhere, maybe at the top, as a pill where it says Patient Details, we can append a pill ui interface with the store name.

### Version and device info

- App version:8.4.2.20220727
- Tablet model:Samsung
- OS version:

**Comment by sworup** [comment]
@adamdewey, Me and @chastichno talked earlier today about a possible fix to this issue:

Currently we have a SupplyingStoreID field in our mobile database that is used to figure out if the current store is same as the supplying store which is the original store of the name. Now we do not store… store data in mobile so it means this StoreId cannot really translate to a name. To get the name of the store we would need to use this SupplyingStoreID and get the name id for the stores tabled and then use that name id to get the name record.

- Suggestion 1: We sync and extra field, StoreNameID to mobile, and use the Name table in mobile (synced and local) to query the store name.
  - Problem: Mobile syncs Name table partially, it only syncs Names it has visibility to so this store's name record might not be synced to mobile.
- Suggestion 2: We sync and extra field, StoreName to mobile, and show that in the patient record.
  - Problem: 
    1. This would require a new field to be added to resync all tablets using this version of apk. Resync all names means a large sync queue. 
    2. During sync of name records, a query per name has to be made to storeNameJoin table, which is potentially 2 more qerry per record sync at server side. But come to think about it, we might be doing this already.
- Suggestion 3: A patch suggestion: create an endpoint in mSupply that returns store info. Have a small button in mobile store details page somewhere. Clicking it fetches the store name on the fly from mSupply server and shows it in the notification snackbar or something.
    - Problem: 
      - This is not sync and this would not store data anywhere in database, this is a internet api call and show on demand on a button click, quick and dirty.
      - This will not fetch data automatically, that is why we need to hide it behind user action, such as a button. This will not show latest data if we do not tie it to an action or sync. As mentioned earlier sync is expensive for development time and production overheads.
   
I wanted to sync stores table to mobile, years ago, I even made a pr to do it. But it got rejected 😭 in account of the fact that if we sync store we have to sync store_name_joins and prefs of these foreign store too, which add a ton of sync out records to the list. Since mobile is one store only system this never made sense to do.

Even though our patient edit features pushes it a little bit, I think for now **Suggestion 3** seems like a most viable and quick solution. Waiting for you reply.

**Comment by sworup** [comment]
@chastichno
I totally didn't see Adam says:
> ... (Possibly a dashboard report would be sufficient) https://github.com/openmsupply/mobile/issues/4842#issuecomment-1203925482

@anildahalsussol do we have a dashboard report that shows patient's home stores?

**Comment by chastichno** [comment]
I vote for the dashboard as changing it in mSupply seems like a lot of work for such a small thing. Not sure though if it's easier in the dashboard

**Comment by sworup** [comment]
We are going to do this with dashboard so closing this now.

**Comment by nisha-dangol** [comment]
Moving to Done/Pass !
