### ISSUE TITLE
App crashes while changing the vaccine for newly created patient

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4878]
## Describe the bug
App crashes while changing the vaccine for newly created patient

### To reproduce
Steps to reproduce the behaviour:
1. Go to Vaccinations and create a new patient
2. Add details an enter a vaccine and confirm, and sync
3. Go to that patient vaccination history.
4. Edit some additional detail like dose number or arm and save.
5. Now change the vaccine and vaccinator and save
6. See error: app crashes!
App crash recording: https://user-images.githubusercontent.com/59193490/184337976-7f194944-d22f-4ed4-b49e-fda458852acf.mp4

Now, open that patient vaccination history and also notice that additional details like date, arm, dose, etc are all missing!
Additional details missing recording: https://user-images.githubusercontent.com/59193490/184338034-848a65f3-5e2c-48e4-bb58-80c621a04cce.mp4

### Expected behaviour
No crash

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: the latest apk

**Comment by chastichno** [comment]
I cannot replicate this bug

**Comment by sworup** [comment]
Might be related to this https://github.com/openmsupply/mobile/issues/4888

**Comment by sworup** [comment]
After the changes in https://github.com/openmsupply/mobile/pull/4899 this error suddenly stopped happening. The side-effect I found is, if you edit Additional Details and then edit vaccination event and save vaccination event, you can no longer save edit anything else in the form, so additional detail's changes that you had made are never saved and would be discarded.

**Comment by sworup** [comment]
@nisha-dangol Just tested for this thoroughly and this error does not exist anymore. The change in https://github.com/openmsupply/mobile/pull/4899 and other merged PRs might have fixed it. This could be the vaccinator and vaccination dropdown issue we talked about and might have been fixed by dropdown related changes in #4899.
Closing this but please do test it.
