### ISSUE TITLE
Kiribati Vax: Vaccine can be processed for deleted patient in vaccination lookup window

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4885]
## Describe the bug
After the patient has been deleted from the original store, from another stores, that deleted patients still show up in the online lookup and can be processed for further vaccination events.
### To reproduce

Steps to reproduce the behaviour:
1. Create a patient in Store1 and sync
2. Delete it and sync
3. In Store2, go to Vaccination and search online; that deleted patient shows up
4. Select it and see error: it lets you add vaccination event for deleted patient.

### Expected behaviour
Once deleted, should not be able to further create any record.

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest

**Comment by sworup** [comment]
@nisha-dangol This is also the error for edit events.
Also I had fixed this with https://github.com/openmsupply/mobile/issues/4841 and https://github.com/openmsupply/mobile/issues/4842 for patient details. THis is mostly the same logic, but I thought this window uses the same list as in dispensing lookup list which is does not.
I have to replicate code from the earlier prs here also and maybe add some dispach logic updates.

**Comment by chastichno** [comment]
Closed as completed in #4893

**Comment by nisha-dangol** [comment]
Re-tested in the latest apk.

Deleted patients are not allowed to proceed with further vaccination event as long as it is in sync. But when we don't manual sync after the patient has been deleted in homestore, still a record can be created for the deleted patient! Issue [here](https://github.com/openmsupply/mobile/issues/4910)

**Comment by sworup** [comment]
The issue stemming from this issue is fixed but that fix stemmed another issue.
@nisha-dangol we can set this one to testing done as future bigs will be handled by future issue.
