### ISSUE TITLE
App hangs/keeps on loading forever when OK&Next button is clicked multiple times while entering a vaccination event

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4886]
## Describe the bug
Pretty much same as #4871 but this time with `OK&Next` button instead of `Confirm` button in vaccination last page (Step4: Select the vaccine page, to be exact! )

### To reproduce
Steps to reproduce the behaviour:
same as #4871 .. Instead of `Confirm`, try clicking `OK&Next` button multiple times and see the error!

### Expected behaviour
App should not hang/keep loading forever like that!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest apk

### Additional context
#4871

**Comment by sworup** [comment]
Fixed with https://github.com/openmsupply/mobile/pull/4896

**Comment by nisha-dangol** [comment]
## Testing
Tested in the [latest](http://t.ly/0uZv) apk

- [x] Go to Vaccination
- [x] Select patient and enter details
- [x] Choose vaccine and prescriber
- [x] Click OK & Next button multiple times
- [x] See no error
- [x] Check that the vaccination event was saved.
