### ISSUE TITLE
Clicking New Patient button multiple times lets us enter vaccination details with empty fields and hangs the app

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4887]
## Describe the bug
In Vaccination window, clicking `New Patient` button multiple times lets us enter vaccination details with empty fields and on confirming, the app eventually loads forever!

### To reproduce
Steps to reproduce the behaviour:
1. Go to Vaccination
2. Tap New Patient` button multiple times and see error: you've skipped Step 2,3 and landed on last Step 4 page with vaccine details
3. Click Confirm and see it loading forever!

### Expected behaviour
Do NOT let multiple taps ANYWHERE lead to such errors!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest apk

**Comment by chastichno** [comment]
closed as completed in #4895

**Comment by nisha-dangol** [comment]
## Testing

### Tests
- [x] Go to Vaccination.
- [x] Tap New Patient` button multiple times. It should only go to Tab 2 and should not let you go further without validation.
