### ISSUE TITLE
App crashes on tapping Save changes button multiple times

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4888]
## Describe the bug
App crashes when we edit some extra info and tap `Save changes` button multiple times and click another button afterwards (`Edit` button now)

### To reproduce

Steps to reproduce the behaviour:
1. IN Vaccinations, create new patient and add complete vaccination event
2. GO back to that patient vaccination history
3. Edit some extra information (like add/edit ID number)
4. Tap `Save Changes` button of Page 2 multiple times. Do same for Extra info page's `Save Changes` button as well.
5. Now click on `Edit` button (of Page 3)
6. See error: app crashes!
7. Re-open and try to click that patient history: app crashes every single time.

### Expected behaviour
No app crashes!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest

**Comment by sworup** [comment]
Error message:



```
TypeError: null is not an object (evaluating 'formData[dependencyKey]')

This error is located at:
    in Form
    in Unknown (at JSONForm.js:227)
    in Unknown
    in RCTView (at View.js:34)
    in View (at Paper.js:37)
    in RCTView (at View.js:34)
    in View (at Paper.js:35)
    in Paper (at VaccinationEvent.js:225)
    in RCTView (at View.js:34)
    in View (at VaccinationEvent.js:224)
    in RCTView (at View.js:34)
    in View (at FlexRow.js:29)
    in FlexRow (at VaccinationEvent.js:223)
    in RCTView (at View.js:34)
    in View (at FlexRow.js:29)
    in FlexRow (at VaccinationEvent.js:168)
    in RCTView (at View.js:34)
    in View (at FlexView.js:27)
    in FlexView (at VaccinationEvent.js:167)
    in VaccinationEventComponent (created by Connect(VaccinationEventComponent))
    in Connect(VaccinationEventComponent) (at PatientSelect.js:354)
    in RCTView (at View.js:34)
    in View (at ModalContainer.js:89)
    in RCTView (at View.js:34)
    in View (at ModalContainer.js:87)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at Modal.js:228)
    in RCTView (at View.js:34)
    in View (at Modal.js:249)
    in VirtualizedListContextResetter (at Modal.js:247)
    in RCTModalHostView (at Modal.js:234)
    in Modal (at ModalContainer.js:80)
    in RCTView (at View.js:34)
    in View (at ModalContainer.js:79)
    in ModalContainer (at PatientSelect.js:349)
    in RCTView (at View.js:34)
    in View (at FlexView.js:27)
    in FlexView (at PatientSelect.js:281)
    in PatientSelectComponent (created by Connect(PatientSelectComponent))
    in Connect(PatientSelectComponent) (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at BottomTabView.tsx:55)
    in SceneContent (at BottomTabView.tsx:172)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.tsx:127)
    in Screen (at ResourceSavingScene.tsx:30)
    in ResourceSavingScene (at BottomTabView.tsx:166)
    in RNSScreenContainer (at src/index.native.tsx:165)
    in ScreenContainer (at BottomTabView.tsx:146)
    in SafeAreaProviderCompat (at BottomTabView.tsx:145)
    in BottomTabView (at createBottomTabNavigator.tsx:45)
    in BottomTabNavigator (at TabNavigator.js:27)
    in TabNavigator (at Wizard.js:44)
    in RCTView (at View.js:34)
    in View (at DataTablePageView.js:36)
    in RCTView (at View.js:34)
    in View (at DataTablePageView.js:35)
    in _c
    in RCTView (at View.js:34)
    in View (at Wizard.js:32)
    in WizardComponent (created by Connect(WizardComponent))
    in Connect(WizardComponent) (at VaccineDispensingPage.js:36)
    in VaccineDispensingPageComponent (created by Connect(VaccineDispensingPageComponent))
    in Connect(VaccineDispensingPageComponent) (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.tsx:127)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:165)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
    in GestureHandlerRootView (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at mSupplyMobileApp.js:253)
    in RCTView (at View.js:34)
    in View (at mSupplyMobileApp.js:252)
    in MSupplyMobileAppContainer (created by Connect(MSupplyMobileAppContainer))
    in Connect(MSupplyMobileAppContainer) (at main.js:31)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at main.js:30)
    in Provider (at main.js:29)
    in ErrorHandler (at main.js:28)
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
```

**Comment by sworup** [comment]
I think when the form loads, it will take data from vaccinationData from from NameNote.data and try to populate the form. In at least 1 case I am testing, the system tries to get the data from the database which has "null" as field value. Now there is check here:

https://github.com/openmsupply/mobile/blob/484ff67bdbeb86dff82743283abe3ca675d7476d/src/selectors/Entities/name.js#L113-L116

The string has customData set as "null", so it is a string. So this passes the 1st condition, and goes to JSON.parse. Here the system expects customData to be an object. It has just been converted from "null" so it converts to null which is not an object. Hence the crash.

**Comment by sworup** [comment]
ok this is the datepicker bug in Page 2 of Vaccination Event details. The datepicker is not setting the currently selected data when it gets the default date which mean even if the date shows in 1Date of Vaccination`, save changes button click without interacting with the datepicker will set null as the value and would crash the vaccination event window thereafter.

![Screen Shot 2022-08-16 at 5 43 27 PM](https://user-images.githubusercontent.com/683452/184874133-b6c60f15-afb7-4b0d-9b83-e9d85b218fe3.jpg)

**Comment by sworup** [comment]
@chastichno @adamdewey ok this is not actually related to datepicker. When you try to edit a already given vaccine, and save the Additional details in vaccine events without updating the Additional details form. It actually never captures and prescription customData object which contains this additional details. You save the form with customData set to null which overrides the current json data record to null.

When you close the form and try to open it again. Since now the customData is null, which it was never supposed to be, it cannot populate the variables needed for the form and the app crashes.

The fix would be to get the customData field in the updatedForm state and then save it with the updated version instead of setting null. It took a while to figure this out, and I am currently trying to work out a good solution so that I would not break the app. Need 1 more day.

**Comment by sworup** [comment]
New discovery. 

Extra information form get the focus at the start so its onChange gets triggered by default. Hence its values are updated into the state and it updates as expected. No null value.

I think the coder (Cat probably) expected that Additional details' onChange would trigger on initial load as well but it does not. Which means the state remain null and that null gets updated in form. 

I have fixed it setting the state to the additional data in record when the page loads.

**Comment by nisha-dangol** [comment]
Tested in latest [apk](http://t.ly/95N6)
- [x] No more run time error
New bug: Now, we can't edit the vaccine nor vaccinator details at all!

**Comment by sworup** [comment]
Another bug found

- Dropdown code filtered out vaccines with no stock
- In dropdown, we were selecting the selected vaccine based on index from the vaccines list but not considering that dropdown has no stock vaccines filted.
- This causes an issue where when there is a vaccine in the list without stock, the dropdown selection would select a completely different vaccine.
- Changed the code to query for id so that current vaccine is selected.

**Comment by sworup** [comment]
> Tested in latest [apk](http://t.ly/95N6)
> 
> * [x]  No more run time error
>   New bug: Now, we can't edit the vaccine nor vaccinator details at all!

Fixed with ca05931b

**Comment by sworup** [comment]
https://github.com/openmsupply/mobile/pull/4899

**Comment by nisha-dangol** [comment]
## Testing
Tested in the [latest](http://t.ly/0uZv) apk
 
### tests
- [x] Go to Vaccinations > Select a Patient's History
- [x] Select a vaccine event from the list to edit
- [x] After the vaccination event details window opens. Tap on save changes button however you like, tap multiple times in any order you want.
- [x] Originally the bug originated from Page 2 Additional Details, just saving it without updating any data would have crashed the app. So check that with priority.
- [x] The data would be saved, or not saved at all after our current fix. Go back to the Patient list page and navigate back to the same vaccine event. Originally trying to do this would have crashed the app. Now it should work properly.
- [x] Regression testing: Maybe try a vaccine event from create just to make sure create is working properly.

### Out of stock vaccine causes dropdown error
- [x] Run a vaccine out of stock, preferably with name that would have shown up in the dropdown list in between, this is an index bug afterall. If there are 3 vaccines [a, b, c] and b is out of stock. It would show in the vaccine dropdown as [a, c]. So here c is index 1. But when the selected vaccine is set it set as index 1 of earlier vaccines list which is b.
- [x] Go to Vaccinations > Select a Patient's History > Select a vaccine event from the list to edit
- [x] Edit Vaccination events.
- [x] Select a vaccine, preferably one coming after out of stock vaccine in the original list.
- [x] Make sure correct vaccine is selected in the dropdown and after save it is saved correctly too.

### Cannot save edit of Page 3: Vaccination event
- [x] Go to Vaccinations > Select a Patient's History > Select a vaccine event from the list to edit
- [x] Edit Vaccination event.
- [x] Change vaccinator, change vaccine
- [x] click Save changes
- [x] Data should update properly.
