### ISSUE TITLE
Editing patient vaccination details of different forms cause app crash

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4891]
## Describe the bug
In patient vaccination details, there are 3 forms: Extra Info, Page2:Additional Details and Page3:Vaccination Event. Editing one form and clicking `Save Changes` of another form is updating the records, which is leading to app crash! 

### To reproduce
Steps to reproduce the behaviour:
1. Create a patient and a vaccination event.
2. Go to that history and edit
3. Change any detail from first form(Extra Info) and click `Save changes` of next form(Page2:Additional Details)
4. See error: records updated toast is displayed.
5. Sync that
6. See the same patient history from another mobile store.
7. See app crash!

### Expected behaviour
Button of one form must not save changes for another form? 
And, definitely No app crash!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest apk
-

**Comment by sworup** [comment]
Might be related to https://github.com/openmsupply/mobile/issues/4888

**Comment by sworup** [comment]
Definitely related to #4888

**Comment by sworup** [comment]
Closed with https://github.com/openmsupply/mobile/pull/4899
