### ISSUE TITLE
toggle failure: current stock and stocktake

### ISSUE THREAD

**Issue by arjunSussol** [openmsupply/mobile#4894]
## Describe the bug

toggle doesn't work in current stock and stock take page

### To reproduce

Steps to reproduce the behaviour:

1. Go to `current stock`
2. Click on `Hide zero stock` toggle
3. It hides zero stock but never show all stocks if you click again
4. Similarly, go to `Stocktake`
5. View/Create new stock take and click `Hide stockouts` toggle
6. It fails again to show respective data

### Proposed Solution
Toggle must work accordingly with every click.

### Version and device info

- App version:
- Tablet model:
- OS version:

### Additional context

Noticed when testing https://github.com/openmsupply/mobile/pull/4864

**Comment by arjunSussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile: #4894: toggle failure: current stock and stocktake](https://trello.com/c/COSI6UA6/569-mobile-4894-toggle-failure-current-stock-and-stocktake)

**Comment by sworup** [comment]
Resolved with https://github.com/openmsupply/mobile/pull/4897
