### ISSUE TITLE
Kiribat Vax: Vaccination event details extra information pages edit gets overridden if multiple tablets are involved

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4905]
# Description

- Vaccination events detail page has 3 sub-pages 1. Extra Information, 2. Addition details and 3. Vaccination event
- Sub-page 3 is only editable in the store where the vaccination event originated at. The other 2 sub-pages can be edited anywhere.
- If we edit the sub-page 1 and 2 concurrently in 2 or more tablets and save the changes, the change that is synced last will override all other changes. 
- This might be very annoying for the user.

## Agreed solution

- We cannot merge changes and do latest change check for vaccination event details edit right now given the tight deadline right now so we do a quick and dirty solution for now.
- Just like sub-page 3, sub-page 1-2 would also only be editable in the store tablet the vaccination event originated in. That would avoid the sync race condition issue for now.

**Comment by sworup** [comment]
Merged with [6ae34e3](https://github.com/openmsupply/mobile/commit/6ae34e3d9bab617509732bf88b0093efcb581210)

**Comment by nisha-dangol** [comment]
## Testing
### Set 1
- [x] Go to Vaccinations > Search for a Patient that you know has vaccination events originating from some other store.
- [x] Select the Patient > Select the vaccination detail
- [x] Try to change textarea,dropdown, datepicker etc. All these should be disabled.
- [x] Click on save changes. You would get a modal box saying you can only edit details in home store.

### Set 2
- [x] Now Go to Vaccinations > Search for a Patient that you know has vaccination events originating from current store.
- [x] Select the Patient > Select the vaccination detail.
- [x] Try to change textarea,dropdown, datepicker etc. All these should be enabled.
- [x] Click on save changes. You should be able to save changes.
