### ISSUE TITLE
Improve Alert: While editing vaccination event need to show atleast store id or need to query for store name from name note

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4908]
## Describe the bug

Now the alert while editing the vaccination event is quite vague if the store name doesn't exist in the name note. That may lead users to search for all the tablets to find the Homestore of name note event.

### To reproduce

Steps to reproduce the behaviour:

1. Go to Vaccination.
2. Search online the patients.
3. Choose any patients with vaccination events.
4. Check the history and select any vaccination event of that patient.
5. Now try to edit the see alert.

### Expected behaviour

It will be difficult for users to search the home store of vaccination events to edt. So good to show at least store id. Later we can make one dashboard report for this.

### Version and device info

- App version: 8.5.0 develop
- Tablet model:
- OS version:

### Additional context

<img width="489" alt="Screenshot 2022-08-31 at 14 12 23" src="https://user-images.githubusercontent.com/18479204/187640313-d5d42970-9c81-4aa4-898a-c8e3a4ff149a.png">

**Comment by arjunSussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile: #4908  Improve Alert: While editing vaccination event need to show atleast store id or need to query for store name from name note](https://trello.com/c/ebAzJkDw/637-mobile-4908-improve-alert-while-editing-vaccination-event-need-to-show-atleast-store-id-or-need-to-query-for-store-name-from-nam)

**Comment by ujwalSussol** [comment]
Talking with @sworup and @arjunSussol : it seems best to close this issue... This PR requires the re-sync of legacy data and the client may not be keen to do this.

So closing this issue for now.
