### ISSUE TITLE
Kiribati Vax: When new vaccine event is created all other vaccine events of the Patient are updated, causing potential sync race conditions

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4911]
## Describe the bug

When new vaccine event is created all other vaccine events of the Patient are updated along with it causing sync issues.

### To reproduce

Steps to reproduce the behaviour:

1. Go to "Vaccinations"
2. Search of a Patient with current store as home. One with previous vax events.
3. Click on the Patient to create new Vaccine event.
4. You may edit patient details but that is irrelevant.
5. Complete the steps to create a vaccination event.
6. Visually you may not see it, but all of the vaccination events of that Patient has been updated, probably with the same data. This creates update sync out records for these vax events (Name Notes). 
7. You may use the Realm explorer to see this happen. Before syncing, go to it and look for SyncOut object string. It will show pending sync out records, and there would be multiple NameNotes updates, there should only be 2 in case of Creating new vaccine event.

### Expected behaviour

- New Vaccine event creation should not update existing vaccine events of the Patient.

### Proposed Solution

- In CreateRecords.ts in createPatient which is also used for Update patient which new vaccine event tries to do during new vaccine event creation, there is a line of code that loops through all nameNotes and updates them. 
- This code is there because during sync in of new patient these name notes had to be created. Remember create and update are same method createPatient.  We do not want to create/update all name notes for this particular case, and there is a code in NameNote create code block that creates 1 single Vax event name note. 
- So we need to add a check that ignores this code during vaccine event creation and edit too.

https://github.com/openmsupply/mobile/blob/80824641c7e16273c75d5750d70f2e13d5e02de9/src/database/utilities/createRecord.js#L337
- We do want it for sync in and other things so a boolean check would be required, we cannot remove the code block that is.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by sworup** [comment]
Resolved with #4912

**Comment by nisha-dangol** [comment]
## Testing
Tested in latest apk

### Tests
### Create new Patient / Vaccination event from Vaccination route
- [x] Go to Vaccination > New patient (Even though this says New patient it actually allows you create a vaccination event too)
- [x] Create the vaccination event, and check if the new Patient and its vaccination event is created properly.

### Create Vaccination event for existing patient
- [x] Use 2 tablets
- [x] In tablet 1. Go to Vaccination > Search for a patient (It'd be better to use a patient that already has vaccination event).
- [x] Create an new vaccination event for this patient. (Previously, when a new vaccination event is created here, a buggy code would update all the other vaccination events for that patient, with existing data, this would cause a sync out queue).
- [x] Go to some other table (tablet 2) and select the same patient, and edit one of his existing vaccination event. And sync.
- [x] Now go back to tablet 1 and sync. It is important that tablet 1 would sync later as new sync would always override old ones.
- [ ] This previously would have created a case where tablet 1's unnecessary updates (during new vax event creation) would have overridden tablet 2's new changes. Make sure the changes in tablet 2 was not overridden. **FAILED**
    - [ ] So if you delete vax events in tablet 2 it'd be un-deleted as it was not deleted in tablet 1.
    - [ ] If tablet 2 has edits to data it would be overridden set back to changes in tablet 1.
    - [ ] This include isDeceased changes too. Or any changes in the form.

### Edit Vaccination event for existing patient
- [x] Same case as above, use two tables to edit different vax events of the same patient.
- [x] Of course you would not be allowed to edit vax events that your store is not home store for, so make to test vax events in their home stores.
- [x] Sync them both and the individual changes must persist, they should not be overridden (while previously it was overriding).

**Comment by nisha-dangol** [comment]
Re-tested as part of #4920
