### ISSUE TITLE
Kiribati Vax: Event details subform's save buttons are not behaving consistently

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4925]
## Description

> @adamdewey says:
> The first I notice - it would be nicer for the user if it's more obvious they can't edit stuff, so making things grey instead of orange. 

> ![2022-09-13 11 13 09 AM](https://user-images.githubusercontent.com/683452/189816445-89d76f25-8183-4a48-b583-d261d8efb6db.jpg)

> 
![2022-09-13 11 13 29 AM](https://user-images.githubusercontent.com/683452/189816524-a5e650fb-8a4e-4f10-b34f-07ad021cc07e.jpg)

> Adam Dewey, [10 Sep 2022 at 3:41:36 AM]:
> ... there seems to be a problem with editing the 2nd page info.
> This is a vaccine that I just created on this tablet:

https://user-images.githubusercontent.com/683452/189817198-8b2bf95a-01ca-420e-98d0-e24961267d29.mp4

**Comment by sworup** [comment]
> Adam Dewey, [10 Sep 2022 at 3:41:36 AM]:
> ... there seems to be a problem with editing the 2nd page info.
> This is a vaccine that I just created on this tablet:

@adamdewey the button is graying out because Island of vaccination field does not have a value after you changed country of vaccination

**Comment by adamdewey** [comment]
> @adamdewey the button is graying out because Island of vaccination field does not have a value after you changed country of vaccination

Ah yes, you're right! 

Ok that's great, thanks Sworup

**Comment by sworup** [comment]
Merged with #4926

**Comment by nisha-dangol** [comment]
## Testing
- [x] Go to vaccination
- [x] Select a Patient who has vaccination event you know does not originate for the current store
- [x] Select the patient and then the vaccination event
- [x] See the fields are grayed out, including checkbox and dropdowns
- [x] See the buttons are grayed out too
- [x] Select a Patient who has vaccination event you know originate for the current store
- [x] Select the patient and then the vaccination event
- [x] See the fields are not grayed out and are editable
- [x] See the buttons are not grayed out and function as they supposed to

The same behaviour (unable to select any field option values in the form when the Save buttons are greyed out) would look good even after the vaccine event is saved. Issue for next release: #4930
