### ISSUE TITLE
Ability to change Sync URL  and site password from the mobile login window

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/mobile#4949]
## Is your feature request related to a problem? Please describe.

While supporting Mobile, it was evident that `Site setting` needs to be modifiable from the mSupply Mobile Login window. 

The problem : 

* A client has a Mobile issue.
* With great difficulty we get the Mobile data file. 
* We import to the local mobile tablet.
* **Problem :** It attempts to sync to the live server. We have no easy way to re-point to another clone system. 

## Describe the solution you'd like

- We have the mSupply login window as shown. 
- Lets have a setting icon. When clicked we will display a `Authorisation` window with Hardcoded password that we know.
-Once password is correctly entered, we need the following window to show the following details : 
- Site name :  [data not changeable]
- Site ID : [data not changeable]
- Site password : [Password to be update-able]
- Site URL : [URL to  update-able]
- We need a [save] and [back]
- If we have the above feature then testing and debugging mobile issue will be easier. 

![Mobile_site_and_url_chnage](https://user-images.githubusercontent.com/6764266/192709030-1d0b6c2b-7e84-4a82-aae1-1ea08b01b493.png)

## Implementation

n/a

## Describe alternatives you've considered

n/a

## Additional context

I think there is a setting page that you can get to once you login. So perhaps a review and we just expose this page at the beginning.

**Comment by ujwalSussol** [comment]
@arjunSussol  assigned to you. thanks.

**Comment by sworup** [comment]
Resolved with  #4973
