### ISSUE TITLE
Change messages in admin setting page

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#4996]
## Describe the bug

The more I look into this the more it does not look right.
When user is logged out and is clicking the setting page, he/she need to give a master password. The same master password is needed to save authorised changes. However the messages says user password.

I know the same interface/components are shared between the setting page here and once you get after you have logged in, but it just does not feel right as it required master password but asks for user password.

### While login in with master password

![SCR-20221114-fpd](https://user-images.githubusercontent.com/683452/201583647-fb3a7e1e-a17c-4bf2-abbf-da4979966407.png)

### While doing factory reset

![SCR-20221114-fnv](https://user-images.githubusercontent.com/683452/201583299-435b2fca-b76a-42d6-a3fa-eec8686da14f.png)

### While saving updates to the fields, by clicking the save button

![SCR-20221114-fpd](https://user-images.githubusercontent.com/683452/201583647-fb3a7e1e-a17c-4bf2-abbf-da4979966407.png)

Make it "Please confirm with your master password to save the changes"

### While updating sync URL and sync password

![SCR-20221114-fv6](https://user-images.githubusercontent.com/683452/201583940-4a44234a-e4e8-4b4b-871b-0277d388d883.png)

Add this one line above the two lines shown here just below the Warning label, "Please confirm with your master password to save the changes"

### To reproduce

Steps to reproduce the behaviour:

1. Sync a data file
2. Click the setting button and type the master password
3. From this moment on all instances ask for your user password, but you actually are supposed to give your master password.
4. Also at least 1 message can be more clear about what you are supposed to do

### Expected behaviour

- The UI should ask for master password. And in some instances should be more clear with instruction

### Proposed Solution

- Create/update message component variables.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by arjunSussol** [comment]
@sworup one query related to last snapshot (Sync url and password edit), this is edit form and we can update label for better understanding but what if we change sync interval and logout interval?

User and developer/tester should be aware that there is `Save Changes` button to update the changes.
So, is it good to make aware on each edit field?

Better to either keep one label on top or bottom of form with suitable label that aware us that we need to click Save button or keep it as it is.

Anyway, waiting for your opinion again.

**Comment by sworup** [comment]
Resolved with #5002
