### ISSUE TITLE
JSON Malformed upon vaccination POST request Payload

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#5017]
## Describe the bug

JSON Malformed upon vaccination POST request Payload.

### To reproduce

Steps to reproduce the behaviour:

1. Add a vaccination transaction
2. Get the POST request Payload from Mobile
4. Validate the JSON
5. See error

### Expected behaviour

JSON should be validated correctly.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.6.1
- Tablet model: Emulator
- OS version: Android 9

**Comment by bijaySussol** [comment]
@sworup : 

As discussed, Could you please make the changes as per discussion and create a Custom app through the PR so that we can test before merging?

Details can be found here: https://github.com/sussol/msupply/issues/11375#issuecomment-1336337004

Thanks

**Comment by sworup** [comment]
Resolved with #5018
