### ISSUE TITLE
App crash: While opening customer requisition

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#5034]
## Describe the bug

While opening customer requisition in a tablet apps is crashed.

### To reproduce

1. Create program internal requisition.
2. Add a reason in line.
3. Finalised the requisition and sync.
4. Sync is supplying the store.
5. Open customer requisition.
6. See error

### Expected behaviour

Should not crash the system.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5 send to v8.6
- Tablet model: lenovo
- OS version:

**Comment by sworup** [comment]
@anildahalsussol Tried to create supplying and customer mobile stores and created requisitions to see if I could re-create this issue.
The customer requistion opened without any problem.
I think the fix here fixed this issue too https://github.com/openmsupply/mobile/issues/5037 so closing this.
