### ISSUE TITLE
Reason would not show on Requisition on Remote desktop

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#5037]
## Describe the bug

Raised here first: https://github.com/sussol/msupply/issues/11962

- Reason field not shown while sending Internal order from tablet store(V502) to Remote V7 desktop.
- We can create the internal order with reason but they would not show up on remote desktop.
- @anildahalsussol has tested this in the latest mobile version, and the issue exists there too.

### To reproduce

Steps to reproduce the behaviour:

1. Create internal order from tablet with mSupply v-502
2. Check customer requisition on desktop remote system V7-beta40
3. See the Reason column

### Expected behaviour

If there is reason provided then it should appear on requisition

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.2 and later
- Tablet model: Any
- OS version: Android

**Comment by sworup** [comment]
According to @bijaySussol Reason also should be mandatory for Requisition if available. We are doing this for Stocktake and should do it for requisitions too.

https://github.com/openmsupply/mobile/issues/4974

**Comment by sworup** [comment]
Resolved with #5046

**Comment by AnushaUp** [comment]
## Testing
Tested in `8.6.2-rc04`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Create internal order (Supplier Requisition) from a tablet, add reasons to the internal order
- [ ] Check customer requisition on desktop remote system 
- [ ] See the Reason column, the reasons should show properly

**Comment by AnushaUp** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Create internal order (Supplier Requisition) from a tablet, add reasons to the internal order
- [ ] Check customer requisition on desktop remote system 
- [ ] See the Reason column, the reasons should show properly
