### ISSUE TITLE
App crashes with store pref alert patient when dispense same vaccine is OFF

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#5069]
## Describe the bug
Details [here](https://github.com/openmsupply/mobile/pull/5040#issuecomment-1379918121)

### To reproduce
Steps to reproduce the behaviour:
1. Get Tonga vax sync setup with mobile
2. For the mobile store, get the store Pref`mobile: Alert if a patient is dispensed the same vaccine multiple times in a week` OFF
3. Sync
4. In mobile store, dispense any vaccine.
5. See error: App Crash! 
See the recording: https://user-images.githubusercontent.com/59193490/212004741-dcce741c-914d-471a-adbe-113606818214.mp4

### Expected behaviour
No any crash whatsoever

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: v8.2.3 rc1 Tonga
- Desktop Server: v7-00-2

### Additional context
Weird thing that this happens sometimes, so the exact steps are not traceable.

**Comment by sworup** [comment]
@nisha-dangol has not been able to recreate this issue.
So until this re-surfaces, we are closing this issue.
