### ISSUE TITLE
App Crashes When Entering The Details of Insurance Policy in Mobile App

### ISSUE THREAD

**Issue by santoshkhanal12** [openmsupply/mobile#5080]
## Describe the bug

App Crashes When Entering The Details of Insurance Policy in Mobile App

### To reproduce

Steps to reproduce the behaviour:

1. Any Data File with mobile stores
2. Sync Setup on mobile
3. Open `Dispensing` tab
4. Dispense a patient
5. Select the Prescriber
6. Select the items and quantity to the items that has been dispense
7. Click on `Next`
8. Go to payment section and click on the `+` (Plus Button)
9. Insurance policy Window will appear following things happen:
     A. Enter any text/number on Family policy Number. App gets crashed.(Bug)
     B. Enter any text/number on Personal Policy number. App gets crashed.(Bug)
     C. Try to change Policy Provider, the selection will not gets changed. (Bug)
     D. Try to change Is Active Yes or No boolean, No changes will be observed. (Bug)
      E. Try to change Policy type boolean, No changes will be observed. (Bug)

Video Reference: https://recordit.co/7NQ3UCXXQi

          

### Expected behaviour

No Bugs should be seen as mentioned.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.6.2-rc04
- Tablet model:Samsung
- OS version: Android

### Additional context

Found While testing the issue: https://github.com/openmsupply/mobile/issues/5043

**Comment by sworup** [comment]
Merged with https://github.com/openmsupply/mobile/pull/5084

**Comment by AnushaUp** [comment]
Tested in `v8.6.2-rc05`
- [ ]  Any Data File with mobile stores
- [ ]  Sync Setup on mobile
- [ ]  Open `Dispensing` tab
- [ ]  Dispense a patient
- [ ]  Select the Prescriber
- [ ]  Select the items and quantity to the items that has been dispense
- [ ]  Click on `Next`
- [ ]  Go to payment section and click on the `+` (Plus Button)
- [ ]  Insurance policy Window will appear following things happen:     
      

    - [ ]  Enter any text/number on Family policy Number. App gets crashed.(Bug)
    - [ ]  Enter any text/number on Personal Policy number. App gets crashed.(Bug)
    - [ ] Try to change Policy Provider, the selection will not gets changed. (Bug)
    - [ ] Try to change Is Active Yes or No boolean, No changes will be observed. (Bug)
    - [ ]  Try to change Policy type boolean, No changes will be observed. (Bug)
