### ISSUE TITLE
Stocktake batch sell price - if you put number in wrong format the app crashes

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#5099]
## Describe the bug

https://user-images.githubusercontent.com/683452/216960585-e4116476-6e1f-4e68-bab5-51b78bf40246.mp4

### To reproduce

Steps to reproduce the behaviour:

1. Go to Stocktake
2. Click on New Stoktake
3. Click on Batches
4. In sell price column try adding 2.00., notice the dot at the end
5. Witness the crash

### Expected behaviour

If the user submits wrong format number the system should be wise enough to stop taking input when the format is wrong

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by sworup** [comment]
Resloved by https://github.com/openmsupply/mobile/pull/5103

**Comment by AnushaUp** [comment]
## Testing
Tested in `v8.6.2-rc5`
Steps to reproduce or otherwise test the changes of this PR:

- [x] Go to Stocktake, Click on New Stoktake. Click on Batches.
- [x] In sell price column try adding 2.00., notice the dot at the end. It could be any wrong format. **-FAILED-**
   @sworup here its not letting us to put exact value and while addling new item on stocktake its taking previous input value automatically.
- [ ] The system should not crash and the price should readjust to a number.

**Comment by sworup** [comment]
> * @sworup here its not letting us to put exact value and while addling new item on stocktake its taking previous input value automatically.

Sell price taking the existing stock's sell price is a existing feature in system. 
Also the dot value being difficult to put exactly even if the format is correct is a bug but needs extensive work to tackle (probably would need to rehash the mechanism to take number input). I do not think it is related to this issue. This issue is about crash if you put text or dot or wrong format in the input box.

**Comment by sworup** [comment]
> * @sworup here its not letting us to put exact value and while addling new item on stocktake its taking previous input value automatically.

@AnushaUp 
Sell price taking the existing stock's sell price is a existing feature in system. 
Also the decimal value being difficult to put exactly even if the format is correct is a bug but needs extensive work to tackle (probably would need to rehash the mechanism to take number input). I do not think it is related to this issue. This issue is about crash if you put text or dot or wrong format in the input box.

We can pass this PR and create new issue for the problems.

**Comment by AnushaUp** [comment]
@sworup okay
