### ISSUE TITLE
Require Chinese translation

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#5100]
## Is your feature request related to a problem? Please describe.

No, It is a fully new functionality

## Describe the solution you'd like

- Take translation
- Import it
- Make a changes to cope with new translation
- Handle showing Flag

![chinese](https://user-images.githubusercontent.com/13144882/216970150-93a049c8-5202-409c-93df-b2d1d4df1bf8.png)

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Moneyworks job code : ZENITH04**

**Comment by bijaySussol** [comment]
Have already done for testing purpose so i have a nice idea how to do this.
But for now, Holding it off for further admin checks clearance.
thanks

**Comment by adamdewey** [comment]
Ok, we have admin clearance for this now @bijaySussol - all good to work on 🙏

**Comment by bijaySussol** [comment]
> Ok, we have admin clearance for this now @bijaySussol - all good to work on 🙏

Thanks @adamdewey 
Changes are done and got the latest translated docs from client

Thanks

**Comment by adamdewey** [comment]
Fantastic, nice one @bijaySussol

**Comment by bijaySussol** [comment]
@arjunSussol : 

We probably can close this issue?
Thanks
