### ISSUE TITLE
Mobile crashes while opening customer requisition

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#5121]
## Describe the bug
With mSupply server on 507-18-IC-test exe and mobile site on latest v8.6.3, opening the customer requisition on mobile is crashing the application
There is no crash with the latest v702 develop setup though!

### To reproduce
Steps to reproduce the behaviour:
1. Get sync setup with mSupply server on 507-18-IC-test exe from [here](https://jenkins.msupply.org:8443/job/mSupplyMaster-Installers/2098/) and mobile site on latest apk v8.6.3
2. Create some internal order to mobile store.
3. In mobile store, open the customer requisition
4. See error: app crashes! 

### Expected behaviour
App should not crash! 

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: v8.6.3
mSupply Server: v5-07-18-IC-test 

### Additional context
Found while testing #5090

**Comment by arjunSussol** [comment]
@nisha-dangol @JonnaQuismundo as you have already discussion that we need upgrade mSupply desktop version to latest to Ivory Cost to compatible with latest mobile, we can close this issue.
