### ISSUE TITLE
Add notification when macro eyes API runs

### ISSUE THREAD

**Issue by jmbrunskill** [openmsupply/mobile#5188]
## Is your feature request related to a problem? Please describe.
Curently it's hard to see if the Macro Eyes API is being called or not in the Application when the user clicks the 'Use Suggested' button on a Program Requistion.

## Describe the solution you'd like

Ideally the system should show some kind of notification to confirm if a macro eyes api call has been made.

Perhaps something like at toast message saying

"X usage predictions updated from STRIATA API"

(STRIATA is the forecasting system from MacroEyes)

`ToastAndroid.show();` might be useful?

If the API returns an error, and error toast with error information should be displayed.

## Implementation

I would expect this message to be triggered around here:
https://github.com/openmsupply/mobile/blob/3b21d2587b82a1a4ee92ebb4470fc860a8f0eb56/src/pages/SupplierRequisitionPage.js#L288

## Describe alternatives you've considered

Do nothing

## Additional context

There's a pilot underway with this code, and we need better visibility of usage.
Branch: `feature/macro-eyes`

**Comment by bijaySussol** [comment]
Fixed by this: https://github.com/openmsupply/mobile/pull/5189
