### ISSUE TITLE
Macro eyes: App crashed using 'use suggested Quantities' 

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#5212]
## Describe the bug

Macro eyes: App crashed using 'use suggested Quantities' 

### To reproduce

Steps to reproduce the behaviour:

1. Have a order no line
2. Click on 'use suggested Quantities'

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v8.6.4-rc06-macro-eyes
- Tablet model: Emulator
- OS version: Android 10

### Additional context

Related to this: https://github.com/openmsupply/mobile/pull/5202

**Comment by bijaySussol** [comment]
Error:
![Screen Shot 2023-05-30 at 1 35 55 PM](https://github.com/openmsupply/mobile/assets/13144882/2afb4af9-4f0e-473e-8680-f3854016c813)

**Comment by wmucheru** [comment]
@bijaySussol Noted on the above issue, looking into it.

**Comment by wmucheru** [comment]
@bijaySussol Just to confirm, are there instances where `data` might be undefined? If so, which variable holds the requisition object which contains `orderType` and `period`?
