### ISSUE TITLE
App crashing on start-up for version 8.6.5

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#5214]
## Describe the bug

Version 8.6.5 crashes on starting. 

![telegram-cloud-photo-size-1-5167881174159305479-y](https://github.com/openmsupply/mobile/assets/19318937/2c4e5758-daa6-40f2-9873-28783ed7f828)

### To reproduce

Steps to reproduce the behaviour:

1. Update app to version 8.6.5
2. Start app

### Expected behaviour

App opens.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.6.5
- Tablet model: Lenovo and Samsung Tab A7
- OS version: Android 10 and Android 12

**Comment by arjunSussol** [comment]
This crash should be fixed by https://github.com/openmsupply/mobile/commit/3801f41bf76ac770b8b98dd942b50789a1268836

As it is already merged, no need to create another PR>

To test it, testers should update the apk from older version (below 8.6.4) to latest v8.6.5.
