### ISSUE TITLE
App crash: While opening existing prescription with edit patient

### ISSUE THREAD

**Issue by AnushaUp** [openmsupply/mobile#5220]
## Describe the bug

mSupply application crash when trying to open edit patient section while editing the existing CI(prescription)

### To reproduce

Steps to reproduce the behaviour:

1. Go to mSupply
2. Click on `Customer Invoice`
3. Click on existing Prescription or create one
4. Click on prescriber
5. Open it and goto edit patient section and save it with or without any changes
6. Click `Next`
7. See error

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

### Additional context

https://github.com/openmsupply/mobile/assets/115983430/78d4ff09-1283-4713-bf45-c62c91dc3666

**Comment by anildahalsussol** [comment]
This issue seems due to current policies.

**Comment by arjunSussol** [comment]
> This issue seems due to current policies.

@anildahalsussol this issue was not due to current policy.
It was legacy bug and I wonder how we missed it till date.

It was due to resetting state to null after clicking Save button on patient edit modal.
However, it fixed now and PR #5230  created.

**Comment by AnushaUp** [comment]
## Testing
Tested in `v8.6.6-rc02`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Better to test with IC data or enable payment module and insurance policy
- [ ] Go to dispensing, click existing home store patient to dispense
- [ ] On tab 2 and 3 click editable button of patient, with/without updating click `Save` button of patient window.
- [ ] Click Next on dispensing page tab 2 or 2, it should not be crashed.
- [ ] In last payment confirmation tab, try to create new policy with different discount rate.
- [ ] Select any policy and click `Save and Close` button
- [ ] Revisit the same prescription from customer invoice page, follow the above same process.
- [ ] It should be processed without any crash.
