### ISSUE TITLE
Set some more fields as mandatory

### ISSUE THREAD

**Issue by arjunSussol** [openmsupply/mobile#5239]
## Describe the solution you'd like

To create a patient, we have already set some fields as mandatory. 
Without entering data to mandatory fields, user can't create new patient.

Now, we are going to expand this and setting more fields as mandatory as described in the [excel](https://docs.google.com/spreadsheets/d/1TxGC30J7qJOqOQz_L2L62BTt8URho4-1JS4NS_g_RFM/edit?pli=1#gid=1122312565)

For patient details except formSchema side, we needs a store preference to set more mandatory fields.
mSupply desktop issue: https://github.com/openmsupply/msupply/issues/13386
 
## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by arjunSussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(4.1.4.b) Prevent user from omitting mandatory information](https://trello.com/c/KhoHdBO9/109-414b-prevent-user-from-omitting-mandatory-information)

**Comment by AnushaUp** [comment]
Tested [HERE](https://github.com/openmsupply/mobile/pull/5266#issuecomment-1639487332)
