### ISSUE TITLE
Phrase is not being translated: "Start typing to search"

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#525]
Build Number: 2.0.0

Description: When adding items on Supplier Invoice, Customer Invoice or Requisitions, the sentence "Start typing to search" is not being translated. We have those translations on file generalStrings. But for some reason it keeps showing english version while in other languages.
![image](https://user-images.githubusercontent.com/16461988/30526427-53d3bd04-9c6e-11e7-880b-1792884bb61a.png)

Reproducible: Yes

Reproduction Steps: On login screen change the language to other than English (button 'Language' on the bottom left of the login screen). After logged in other language select the similar to: Supplier Invoice > New Supplier Invoice > New Line.

**Comment by Chris-Petty** [comment]
This appears to be fixed
