### ISSUE TITLE
Phrase is not being translated: "Invalid username or password"

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#526]
Build Number: 2.0.0

Description: If the user set a wrong username or password, while using other language, the app is not translating the phrase "Invalid username or password". There is no translation for that phrase.
![image](https://user-images.githubusercontent.com/16461988/30526499-76f15b38-9c6f-11e7-8244-744dabccc47d.png)

Reproducible: Yes

Reproduction Steps: On login screen change the language to other than English (button 'Language' on the bottom left of the login screen). Than type an username with wrong password.

**Comment by Chris-Petty** [comment]
This error message actually comes from the server auth API. We should still localise it!

**Comment by nmadruga** [comment]
Going to fix this in a bit, as mentioned [here](https://github.com/openmsupply/mobile/issues/4613#issuecomment-1064632534)

**Comment by DhanyaHerath** [comment]
Closed in desktop/V5-08-00-RC13, PR https://github.com/sussol/msupply/pull/10468

**Comment by nisha-dangol** [comment]
Tested in mobile v8.5.0-rc1 with desktop server on 5-08-00-rc43

Hi @nmadruga @katherine-sussol 
I think this issue still persists. The message is clearly in English for non-English user.
![Screenshot_2022-05-20-11-37-20-837](https://user-images.githubusercontent.com/59193490/169460270-7f28aba4-e63f-4c74-a7d3-b93110b96ec1.jpeg)
![Screenshot_2022-05-20-11-22-45-547](https://user-images.githubusercontent.com/59193490/169458754-88ffe87a-8982-4594-a2c9-4ec8ee91fb9c.jpeg)

**Comment by Chris-Petty** [comment]
I don't think Desktop has a Kiribati translation? If so that'll be why. 

(Hot-take: it'd be better for mobile to translate the string based on an error code from the server).

**Comment by nisha-dangol** [comment]
'The Account is blocked... ' message seems to appear for every language (french, Tetum, Spanish.. )
![Screenshot_2022-05-23-14-07-29-962](https://user-images.githubusercontent.com/59193490/169776996-86669033-6857-413b-99ab-211eb5dce989.jpeg)
![Screenshot_2022-05-23-14-07-00-589](https://user-images.githubusercontent.com/59193490/169777003-86a2a2b7-276d-4ba0-a802-fe66426bc6fd.jpeg)
![Screenshot_2022-05-23-14-07-15-728](https://user-images.githubusercontent.com/59193490/169777009-f8fc8d54-3ca2-4c2c-957c-13c489541d79.jpeg)

**Comment by Chris-Petty** [comment]
It's a bit funky, but have you changed the language on the server's user?

If I recall correctly, it's relying on the user on the server to have the right language selected.

**Comment by nisha-dangol** [comment]
> It's a bit funky, but have you changed the language on the server's user? The reproduction steps are located here for this particular message: [sussol/msupply#10468](https://github.com/sussol/msupply/pull/10468)
> 
> If I recall correctly, it's relying on the user on the server to have the right language selected. To clarify, I don't mean the mobile user's user account on the server, but the user account of mSupply. @nmadruga might have a footrunner or something to get it going right?

Yes, I changed the mobile user's default language to French on server cloud and tried logging in with wrong password till 'account is blocked...' message appears, which is in English for French user. 
![Screenshot_2022-05-24-11-12-58-762](https://user-images.githubusercontent.com/59193490/169958212-f82dfad8-4b03-45e9-896b-2bdeea297231.jpeg)

**Comment by Chris-Petty** [comment]
> > It's a bit funky, but have you changed the language on the server's user? The reproduction steps are located here for this particular message: [sussol/msupply#10468](https://github.com/sussol/msupply/pull/10468)
> > If I recall correctly, it's relying on the user on the server to have the right language selected. To clarify, I don't mean the mobile user's user account on the server, but the user account of mSupply. @nmadruga might have a footrunner or something to get it going right?
> 
> Yes, I changed the mobile user's default language to French on server cloud and tried logging in with wrong password till 'account is blocked...' message appears, which is in English for French user. ![Screenshot_2022-05-24-11-12-58-762](https://user-images.githubusercontent.com/59193490/169958212-f82dfad8-4b03-45e9-896b-2bdeea297231.jpeg)

Sorry it's less intuitive than that unfortunately, completely understand why you tried this way.

You need to be able to change the _server's_ language. Under the hood there is a 4D user named "msupply" and the language needs to be set on that (with footrunner I guess). Either that or this just isn't working! @nmadruga do you remember how?

**Comment by Chris-Petty** [comment]
Oh lol, sorry 😅 ! I was working on auth and just saw _that_ string is not actually translated at all on the back end sorry. So it just won't be right. But, the "Invalid username or password" one should be working?

**Comment by nisha-dangol** [comment]
> Oh lol, sorry 😅 ! I was working on auth and just saw _that_ string is not actually translated at all on the back end sorry. So it just won't be right. But, the "Invalid username or password" one should be working?

Yup, I noticed that "Invalid username or password" was correctly translated to French (when user language was set to French in cloud server); only "account blocked..." message is in English regardless of the user language selected in cloud or mobile.

**Comment by Chris-Petty** [comment]
Can you open an issue in the msupply repo to translate that string too please?

**Comment by nisha-dangol** [comment]
> Can you open an issue in the msupply repo to translate that string too please?

[Here's](https://github.com/openmsupply/mobile/issues/4729) the issue
