### ISSUE TITLE
No icons/images on main menu page

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#527]
Build Number: 2.0.0

Description: There are no icons/images on on main menu.
![screenshot_20170918-133144](https://user-images.githubusercontent.com/7684221/30526853-ded09b78-9c75-11e7-84ed-0fb45916d13f.png)

Reproducible: Not sure.

Reproduction Steps:
1. Tab A 2016
2. Install 2.0.0
3. Sync a site with 200k+ records
4. Login
5. No icons?

Comments: App functionality seems fine, maybe a bit slower than usual. Though, it is working on a rather large realm database.

**Comment by joshxg** [comment]
@Chris-Petty closing as I've never seen or heard of this, reopen if you think it still exists? :)
