### ISSUE TITLE
Bold/highlight the currently edited row

### ISSUE THREAD

**Issue by edmofro** [openmsupply/mobile#529]
## Describe the bug

Currently when editing a cell in a row, there is not enough visual feedback of what row the the user has focused.

### To reproduce

1. Go to a unfinalised customer invoice
2. Add a few items if there aren't any
3. Focus textinput of quantity field of an item
4. WANT: the row that focused cell is in to be highlighted.

### Expected behaviour

The row currently with focus in it should be highlighted in some manner. Either highlight the row by changing the background colour. BONUS: Get fancy and highlight the row and bold the text in the cell with focus if you like.

### Solution
This will require some in-depth knowledge of the page and data table state management.

1. Add action constant `"focusCell"`
2. Create an action creator function in `cellActions.js`. Action payload should have `rowKey` and `columnKey`
3. Add a reducer function in `cellReducers.js` that immuntably sets: `dataState.row[action.rowKey].focusedColumn = action.columnKey` (likely catch, if the focus has moved from one row to another, need to clear the focusedColumn from the previous rowState object)
4. Add a function `onFocusCell` to getPageDispatchers that dispatches the above action.
5. `TextInputCell.js` needs prop for `onFocus` that passes into the `TextInput` props. The component should make a method that calls it with rowKey and columnKey.
6. `DataTableRow.js` needs to check rowState to see if it's "focusedColumn" has a value and highlight the row if so.

### Version and device info

- App version: all
- Tablet model: all
- OS version: all

### Additional context

Original description: 
>When editing a stocktake in particular, but also requisitions etc., it can be easy for a user to enter the quantity on the row above or below the one they mean to. The contrasting lines help with that, but apparently not enough. Would be great to highlight or bold the currently edited item to make it clearer!

**Comment by Rebecca367** [comment]
@Chris-Petty @joshxg @diegoevangelisti 
I have done some digging and turn out it is not working, but it is a good experience getting to know how the codebase works. Howe to debug in VSC? just set debug=true?
I have done some modifications on Row.js as below but it not working. Any suggestions are welcomed:
const Row = React.memo (
  ({
    rowData,
    rowState,
    rowKey,
    renderCells,
    style,
    onPress,
    debug = true,
    rowIndex,
  }) => {
    if (debug) {
      console.log ('=================================');
      console.log (`Row: ${rowKey}`);
    }

    const {adjustToTop} = useContext (RefContext);
    const onPressRow = useCallback (() => onPress (rowData), [onPress]);
    const onFocus = () => adjustToTop (rowIndex);
    const onFocusBold = () => {
      onPressRow ((rowIndex.fontWeight = 'bold')); // extra cold
      console.log ('Hello!! in onFocusBold');
    };
    const Container = onPress ? TouchableOpacity : TouchableNoFeedback;
    return (
      //<Container onPress={onPressRow} style={style} onFocus={onFocus}>
      //{renderCells(rowData, rowState, rowKey, rowIndex)}
      //</Container>
      (
        <Container onPress={onPressRow} style={style} onFocus={onFocus}>
          {renderCells (rowData, rowState, rowKey, rowIndex, onFocusBold)}
        </Container>
      )
    );

**Comment by Chris-Petty** [comment]
@Rebecca367 @diegoevangelisti I updated the description to explain better.
@joshxg I'd appreciate if can have a glance at solution incase I'm a bit off please

**Comment by joshxg** [comment]
looks good

**Comment by Rebecca367** [comment]
Thanks

**Comment by Rebecca367** [comment]
@Chris-Petty @joshxg Thanks for the insights. Currently Working on it.

**Comment by Rebecca367** [comment]
This issue needs pre-requisite knowledge on some technologies and code-page understanding. So, it will take longer than what was expected.Let's say give it another week to work on.

**Comment by Chris-Petty** [comment]
@Rebecca367 That's fair, it'd be better to work on this with me or Josh, but this week has a couple pressing deadlines. If you want to take on other issues I can aim to help later next week.

**Comment by Rebecca367** [comment]
@Chris-Petty That will be lovely! Thank you

**Comment by Rebecca367** [comment]
@Chris-Petty @joshxg @diegoevangelisti 
There are some changes that I have made in code page by page but needs further implementation. It is still not working properly, so maybe it needs experienced developers to take a look at it?

1. In cellActions.js

export const refreshRowWithBold = (rowKey, columnKey, bold) => ({//extra
  type: ACTIONS.REFRESH_ROW, //extra
  payload: { rowKey, columnKey, bold }, //extra
});//extra

2. In cellReducers.js
export const refreshRowWithBold = (state,action)=>{ // extra
  const {payload}=action;
  const {rowKey} = payload; //extra
  const newDataState = new Map(dataState.row[action.rowKey].focusedColumn= action.columnKey);//extra
  newDataState.set(rowKey, { ...nextRowState });//extra

  return { ...state, dataState: newDataState };//extra

3. In getPageDispatchers.js
onFocusCell: focusCell=>dispatch(BasePageActions.selectRow(rowKey, route)),// extra

4. In TextInputCell.js
const onFocus=newValue => onFocus(newValue,rowKey,columnKey);//extra

5. In DataTableRow.js
case COLUMN_TYPES.CHECKABLE:
              return (
                <CheckableCell
                  key={columnKey}
                  rowKey={rowKey}
                  columnKey={columnKey}
                  **focusedColumn={refreshRowWithBold}//extra**
                  isChecked={rowState && rowState.isSelected}
                  isDisabled={isDisabled}
                  CheckedComponent={CheckedComponent}
                  UncheckedComponent={UncheckedComponent}
                  DisabledCheckedComponent={DisabledCheckedComponent}
                  DisabledUncheckedComponent={DisabledUncheckedComponent}
                  onCheck={getCallback(columnKey, 'onCheck')}
                  onUncheck={getCallback(columnKey, 'onUncheck')}
                  containerStyle={touchableCellContainer}
                  width={width}
                  isLastCell={isLastCell}
                />
              );

**Comment by joshxg** [comment]
@Rebecca367 can you link to your branch rather than pasting code as you've done above? It's really hard to read.

**Comment by Rebecca367** [comment]
@joshxg feel free to switch branch to #529 bold-edit-row to modify as I have committed and pushed modified code to this branch.

**Comment by joshxg** [comment]
@Rebecca367 there is no diff when comparing develop and `#529-Bold-edit-row` - there are no commits ahead of develop?

**Comment by Rebecca367** [comment]
@joshxg already did. Free free to take a look at it. Thanks
