### ISSUE TITLE
Empty requisitions sent to Desktop

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#576]
Build Number: 2.0.0-rc11

Description:
Mobile can send requisitions to Desktop that have no lines.
![image](https://user-images.githubusercontent.com/7684221/33587516-589e0612-d9d3-11e7-9ace-69837502831f.png)
This is the response requisition, but through inspecting database the request requisition also has no requisition lines.

Reproducible: Have not tried, not sure yet

Reproduction Steps:

Comments: Observable in Timor Leste DHS data. Affects a small amount of requisitions.

**Comment by sworup** [comment]
@Chris-Petty This is the behavior I am observing... did you mean this?

![7u8bkrc4go](https://user-images.githubusercontent.com/683452/52324615-19a82400-2a0a-11e9-872c-68ec55433bea.gif)

Supplier requisition in mobile does create an empty requisition. I suppose this was a work in progress kind of entry.
If yes, how do you propose we handle this? Some possibilities could be-
- Do we prevent mobile from creating an empty supplier requisition?
- We create the empty supplier requisition but never sync it.

**Comment by andreievg** [comment]
@sworup I think the issue was, you could finalise supplier requisition with no-lines (or all lines set to 0 order quantity). i.e Chris was talking about response requisition (customer requisition). Can you please check if it's still the case ?

**Comment by sworup** [comment]
@andreievg Customer Requisition has limited edit functionalities in mobile. You cannot add lines or edit anything but quantity. You cannot delete lines either. All you can do is finalise.

**Comment by andreievg** [comment]
@sworup, I think the issue was, you could finalise supplier requisition with no-lines. What you show in the gif is creating requisition, then checking it syncs (you are logged in the same store and checking it's request requisition). To replicate what @Chris-Petty says, make a requisition to suppling store, finalise it (with all lines set to 0 quantity) and check the response requisition on desktop

**Comment by joshxg** [comment]
Not able to replicate:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/35858975/99869334-fd04cc80-2c2e-11eb-8fe9-ae171300a0e4.png">
