### ISSUE TITLE
Highlighting essential items - Row highlighting

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#578]
Request comes from East Timor for highlighting rows in forms for essential drug list items on mobile.
Currently we don't actually store this field on mobile, so if this is implemented we'll need to resync items to mobile upgraded sites. Defaulting the value to False in migration is probably the most graceful solution.

Need to discuss with other clients whether this is a good thing to add.
Need to design around this - how to make it extensible, are there better ways to present this?

**Comment by joshxg** [comment]
@Chris-Petty is this still something we want to do?

**Comment by Chris-Petty** [comment]
If we're tidying up open issues, not much harm in closing this feature request. Could be worth noting that row highlighting might be a good data table requirement, though.
