### ISSUE TITLE
Stocktake batch TextInputs clipped

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#603]
Build Number: <=2.1.0

Description: 
BATCH NAME runs out of cell to the right side.
For some reason expiry underline is darker than other fields.
![image](https://user-images.githubusercontent.com/7684221/35890839-367a0daa-0c06-11e8-95d9-1784b45f301f.png)

Reproducible:

Reproduction Steps:

Comments:

**Comment by Chris-Petty** [comment]
While you're in here mr fixer:

![screenshot_20180207-120658](https://user-images.githubusercontent.com/7684221/35946606-51a3e90c-0cc9-11e8-9b83-54aba11c776c.png)

Fix the inner table page for batches running out of the containing row by a pixel...
Happens on tab A 2016 10.1" on master

**Comment by Chris-Petty** [comment]
With new react native it looks a little different, but persists: 
![image](https://user-images.githubusercontent.com/7684221/48229049-d0950380-e40b-11e8-913b-24cf7b0e06a9.png)
(the input goes out of cell on top of the neighbouring cell for batch name now)

**Comment by joshxg** [comment]
Being fixed with #1043
