### ISSUE TITLE
Problem related to spinner when finalising stocktake

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#620]
Build Number: 2.1.0-rc8

Description: We had a reported problem from Solomon Islands happening with more than one tablets when finalising stocktakes with only 5 items. It was taking very long (about half hour) showing the spinner. And when it was showing the stocktake finalised and the screen with the spinner in front of it, not enabling the user to close it. Also the spinner was moving slightly to both sides. @nmadruga has a video of that happening.

Reproducible: Only in some tablets model SM-P555 on android version 6.0.1. The problem reported was happening in Solomon Islands on March 2018.

Comments: We have released a test version v2.1.0-rc9 without the spinner that shows a screen with 'Please wait' and asked them to test it on one of the tablets. It worked. Now we just want to be sure it has solved the problem for other tablets there before merging the branch without the spinner: https://github.com/sussol/mobile/tree/V2.1.0-rc9-no-spinner

We need to find what was the problem and fix it (we couldn't reproduce it one of our tablets), in order to get the spinner back to a newer version. Otherwise we will keep the screen 'Please wait'.

**Comment by joshxg** [comment]
@nmadruga Do you know if this has been fixed?

**Comment by joshxg** [comment]
Just checking issues - this seems really confusing - is the problem fixed? I can only imagine so! At least, in newer versions.. I will close this and let you reopen it if I'm wrong!?
