### ISSUE TITLE
Stock take table search should include "CONTAINS" results in filter.

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#623]
Build Number: 2.1.0-rc8

In select item boxes, we searches from the beginning and through out each item name. In stocktake search bar it only searches from beginning. This can be annoying for new users that aren't familiar with what exactly an item may have been named.

Example:
"Para" should filter items in stocktake first to those starting with "para", followed by items with "para" anywhere in its name.

**Comment by joshxg** [comment]
@Chris-Petty - should we be using contains rather than starts with for all page searches? Personally I think starts with is better?

**Comment by Chris-Petty** [comment]
For combined medicines it better, e.g. search "para", you want to see "codeine/paracetamol 100mg/500mg". Especially when it's not up to us to name things, consistent search order is not guaranteed.

**Comment by joshxg** [comment]
Fixed by #1043
