### ISSUE TITLE
Stocktake batch editing confusing

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#625]
Build Number: 2.1.0-rc8

Description: 
I understand it perfectly well, but when training people for the first time with little experience with apps or tablets it can be pretty confusing.

Often when searching the table for an item, users would tap on the item name. If they then go for editing a batch quantity rather than the item's total quantity the screen may scroll the table, concealing the row that is expanded. User can be pretty lost at this stage without assistance.

![screenshot_20180312-172116](https://user-images.githubusercontent.com/7684221/37265680-da4f0a70-2619-11e8-9175-96a4ee093ecd.png)

Might be worth getting Manu to review design?

**Comment by arjunSussol** [comment]
@Chris-Petty @andreievg this issue also can be fixed by https://github.com/sussol/react-native-generic-table-page/pull/15

After your review we can close this issue too.

**Comment by Chris-Petty** [comment]
Seems like a different issue to me, I can only envision having more screen realestate (out of our control) or a redesign of the interface resolving this.

**Comment by joshxg** [comment]
No expansions anymore - closing
