### ISSUE TITLE
Can accidentally make multiple stocktakes

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#628]
Build Number: 2.1.0-rc8

Description:
If you double press "Create", it'll make 2 stocktakes with the same items. If it's on a particularly slow tablet, you can get even more presses!

Reproducible: Yes

Reproduction Steps:
Description covers it enough

Comments:

**Comment by andreievg** [comment]
This was fixed in https://github.com/sussol/mobile/pull/605 I believe

**Comment by andreievg** [comment]
This was fixed in https://github.com/sussol/mobile/pull/605 I believe

**Comment by andreievg** [comment]
Oops can you remove my comments please

**Comment by Chris-Petty** [comment]
I deleted one - It's a fair thing to bring up though. The simple solution is the same as #605

**Comment by Chris-Petty** [comment]
Github is drunk 
![image](https://user-images.githubusercontent.com/7684221/37382587-7ba00714-27a8-11e8-9c60-a2f3807407ab.png)
