### ISSUE TITLE
Stocktake item total quantity adjustments wrong if no expiry date on batches

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#639]
Build Number: 2.1.0-rc8

Description: 
Same as snapshot works correctly:
![image](https://user-images.githubusercontent.com/7684221/37933858-024d9fec-31a9-11e8-971a-c358f6b7942d.png)

Reduced works correctly:
![image](https://user-images.githubusercontent.com/7684221/37933983-5f43e012-31a9-11e8-9739-ddf33c95c5c3.png)

Increased works correctly:
![image](https://user-images.githubusercontent.com/7684221/37934036-7c3590f8-31a9-11e8-8596-e52edb3bc914.png)

But if you recount or correct a mistake, reducing the increased value
![image](https://user-images.githubusercontent.com/7684221/37934122-b9771bee-31a9-11e8-9b82-a591edf323e4.png)
Stock has been reduced by 50 but applied incorrectly across batches.

I think this anomaly is caused by the fact none of the 3 batches have an expiry date. Giving them dates it works correctly.
![image](https://user-images.githubusercontent.com/7684221/37934316-4cb76634-31aa-11e8-8c2f-762b6f604734.png)

Reproducible: yes

Reproduction Steps:
In a stocktake with an item that has stock across 3 batches with no expiry.
1. Increase stock above the snapshot quantity for the item
2. Change focus to make sure it's saved.
3. Decrease stock to below the snapshot quantity for the item

Comments: Not the end of the world but pretty bad.

**Comment by joshxg** [comment]
@Chris-Petty Is this #1471? Basically funny FEFO with dates and stuff?

**Comment by joshxg** [comment]
Going to close this, reopen if its not the case but I'm on a mission
