### ISSUE TITLE
Back navigation doesn't affect modals

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#646]
Build Number: 2.1.0-rc8

Description:
Originally this issue was for (in app and hardware) back button still navigating pages rather than closing modals. After #805 (I guess) the navigation problem is fixed, but the back button should still close modals.

- Add item
- New invoice/ any other selector modal.
- Batch Editing in stocktakes
- Editing comments/references on invoices (in pageInfo)
- Months of stock on requisition

Reproducible: yes

Reproduction Steps:
1. Open/create in progress requisition
2. Tap "Months stock" number to edit
3. Press hardware back button
The modal is closed, but app also navigates back to the requisition list.

Comments:

**Comment by andreievg** [comment]
Related: https://github.com/sussol/mobile/issues/793

**Comment by joshxg** [comment]
This just requires adding the prop `onRequestClose={onClose}` to `ModalContainer`
