### ISSUE TITLE
Closing app while finalising leaves dirty records

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#658]
Build Number: 2.1.0-rc8

Description: Not 100% sure of the exact details. But if you say finalise a big stocktake or transaction, you can close the app while that is processing. There isn't much in the way of handling that. If the Realm write is interrupted does it throw out what it was doing up till then cleanly? What if the app errors during a write?

Reproducible:  Not sure

Reproduction Steps:

Comments: Issues like #654 and #657 may be explained by this.

**Comment by joshxg** [comment]
I tried getting any sort of negative side effect from exiting while in the middle of finalising a stocktake (and other records) with 1500 items and had no side effects - going for a risky close but reopen if I'm wrong @Chris-Petty !
