### ISSUE TITLE
Expiry fields still underlined (i.e. TextInput) in finalised supplier invoices/stocktakes

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#662]
Build Number: 2.1.0-rc10

Description: Expiry fields still underlined (i.e. TextInput) in finalised supplier invoices/stocktakes

Reproducible: yes

Reproduction Steps: Look at a finalised supplier invoice, also a finalised stocktake

Comments:

**Comment by joshxg** [comment]
No idea where this was fixed, but it is
