### ISSUE TITLE
Push records needs better errors and bugsnag

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#680]
Build Number: 2.1.0

Description: Currently error messages are lacklustre on record push with sync. Below are the only messages:
```javascript
try {
  responseJson = await response.json();
} catch (error) {
  throw new Error('Unexpected response from sync server');
}
if (responseJson.error.length > 0) {
  throw new Error('Server rejected pushed records');
}
```

Reproducible: yes

Reproduction Steps:
I don't have something specific at hand. Get the server to send back an error.

Comments:
Refactor: make bugsnag/utilities.js, pull the outgoingSyncUtils.js use of bugsnag out and put it there. Then use appropriately and improve the errors in description snippet.

**Comment by nmadruga** [comment]
This problem happened again on 3rd July 2018 on Taro tablet. And it ended up being just a very week or maybe unavailable mobile data signal to sync. One idea is to improve this message, if it is covering more than one type of problem. A better message for the case on Taro is: "No connection with the server" to make it clear that the problem is with the connectivity and not mSupply server.

**Comment by Chris-Petty** [comment]
It's actually getting an error response from the server, but the connection is just too flaky. I think it'd be better to actually display the error, or handle the http status codes (presumably coming through) with appropriate messages.

**Comment by Chris-Petty** [comment]
Cook Islands now suffering a similar pain regarding this vague error.

**Comment by raviSussol** [comment]
@Chris-Petty @nmadruga Since Im working on this #775 issue (where both have similar codes) to edit - so I'll branch off from that issue and update the error message to more verbose (or handle http response code) to clarify the current unknown error.

**Comment by joshxg** [comment]
Going to close this and use #1025 - the solution there has problems and might not be suitable as a final solution, but we can reopen and/or make new issues with different solutions afterwards
