### ISSUE TITLE
Feature request :  Can we allow the mobile user to export data.

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/mobile#743]
Currently we can get to the admin window and export Realm database. 

We have found that SureMDM does not have the right to control all brands of tablet. So we need the user to be able to click the button to export a the data.... Then sussol folks can transfer the data via SureMDM.

Also SureMDM is slow due to the internet speed at the other end....  So getting the end user to export data would be great.

We need a Maintenance page.

**Comment by joshxg** [comment]
I believe this feature has been implemented, but obviously has it's faults, which have their own issues, so closing.
