### ISSUE TITLE
Update to realm@2.20.0

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#753]
Build Number: 2.1.1
Description:  Currently using realm@1.13.0, multiple errors when running `yarn install` in newly cloned repo.
Reproducible: Yes.
Reproduction Steps: Clone the repo and run `yarn install` .
Comments: Test after updating, latest stable realm version is backwards-incompatible with current version.

**Comment by Chris-Petty** [comment]
Did you get around this? You've since made PRs so I'd assume so.

**Comment by wlthomson** [comment]
Planned for next week, there are some backwards incompatibilities so upgrading to latest will need to be tested.

**Comment by wlthomson** [comment]
Issue has been traced to node version, tested working v8.11. Probably still a good idea to update Realm, in any case.

**Comment by sworup** [comment]
@Chris-Petty @wlthomson As of now Realm 2.21.1 only support Node v10.

**Comment by Chris-Petty** [comment]
@sworup I've assigned you onto this (and some others 😉 ). When you get to it look ahead a bit to see if moving forward what node we're using is good for other dependencies (key ones like react/RN/webpack etc.). If it works then get cracking, people can upgrade their node version.

**Comment by Chris-Petty** [comment]
Fixed in #787
