### ISSUE TITLE
Failing listViewStyle prop for in-built Realm Explorer 

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#754]
Build number: 2.1.1.
Description: Navigating to the RealmExplorer.js page causes the following error to be logged:
```Warning: Failed prop type: Invalid prop `listViewStyle` of type `object` supplied to `DataTable`, expected `number.```
Reproducible: Yes.
Reproduction Steps: Run the app with `react-native run-android && react-native log-android`. Click and hold the mSupply logo until the button for Realm Explorer appears. Click on the Realm Explorer button. Check the terminal log for the error.

**Comment by sworup** [comment]
This warning comes in at every step. I did fix it once locally by changing DataTable PropType values in our DataTable plugin but I do not think I pushed the changes.

**Comment by sworup** [comment]
@Chris-Petty @wlthomson Actually I did pushed the changes
https://github.com/sussol/react-native-data-table/pull/44

**Comment by joshxg** [comment]
Fixed by #1043
