### ISSUE TITLE
(S)2 tablets 1 store STOP it happening

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#762]
**Problem:** Can currently make 2 tablets sync to the same store. This causes sync issues, breaking the whole system as it's not design for it.

**Expected:** Cannot sync two tablets to same store, hardware (or something) is tracked in some manner and blocks it happening. As this will likely need server side work, could be applied to desktop sync too.

**Comments:**

**Comment by ujwalSussol** [comment]
We have a mantis issue that @anildahalsussol  wants to work on : https://bugs.msupply.org.nz/view.php?id=8898

**Comment by andreievg** [comment]
- [ ] - checking test

**Comment by joshxg** [comment]
Realised the desktop PR for this https://github.com/sussol/msupply/pull/2280 has not been merged, so obviously is not working.

**Comment by joshxg** [comment]
# TESTING

- [x] Try to sync the same store to two tablets

There's an issue with the hardware ID though. Issue here: #1290
