### ISSUE TITLE
Prettier config

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#768]
We need one. Needs to play ball with eslint rules too.

**Comment by wlthomson** [comment]
There is currently a .prettierrc file in the root directory of the repo, but it has not been applied consistently. I can either open a new issue for this, or fix it up and make a PR referencing this issue.

**Comment by andreievg** [comment]
@will @joshxg -> Can one of you apply prettier changes across the whole project + add information in reademe.md about using prettier.

We want to use current .eslintrc file (not sure if it's up to date), but i am pretty sure you can configure prettier to use eslint setting.

**Comment by will** [comment]
@andreievg I haven't kept up with anything in javascript really for the last 7 years or so, I'd have no idea where to start to do a prettier thing. I know some people use like standard something? is that a thing? Sorry

**Comment by andreievg** [comment]
@will, sorry wrong will lol. Thanks for reply though.

**Comment by andreievg** [comment]
@wlthomson

**Comment by Chris-Petty** [comment]
> We want to use current .eslintrc file (not sure if it's up to date), but i am pretty sure you can configure prettier to use eslint setting.

Even better, commit the config, dev-dependency prettier package, make running it a pre-commit or pre-PR hook.

**Comment by wlthomson** [comment]
@andreievg @Chris-Petty If all up to date, will have a look at suitability of current config. If out of date or otherwise unsuitable, will migrate to the one we are currently using for rnr.

**Comment by Chris-Petty** [comment]
The current config looks good to me (consistent with how we've treated mobile in the past). Though, if you come up with a good reason to tweak it let it be heard 😃

**Comment by sworup** [comment]
@wlthomson @Chris-Petty @andreievg @joshxg 
This article could be a good read...
https://blog.aurity.co/creating-react-native-app-boilerplate-with-flow-jest-enzyme-prettier-and-eslint-cefdbce3b3d

**Comment by wlthomson** [comment]
Fixed by #797. Closing.
