### ISSUE TITLE
Customer invoice should warn if allocating more than stock available

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#77]
Expected:
- Shows warning dialog explaining no more than what is available can be allocated
- Changes value to equal that of available stock

Actual:
- Just changes value to equal that of available stock

**Comment by bijaySussol** [comment]
@Chris-Petty : We doing this...

**Comment by Chris-Petty** [comment]
> @Chris-Petty : We doing this...

Lol this is soooooo old. If it's been this low priority for this long... unless it's actually secretly done it can be closed.

**Comment by bijaySussol** [comment]
Thanks @Chris-Petty 
I am going through some of the issues from Mobile repo, to see if we can bring down the issues for Mobile as we doing for Destop

And this will be one off.

Cheers
