### ISSUE TITLE
Problem with initial sync with mSupply server v3.85

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/mobile#772]
Build Number: 2.1.1

Description: When trying to use a new configured sync site and mobile store using Laos datafile after it went through hundreds of records the sync the wifi was turned of (by mistake) and when it was back the error message was showing: "value not convertible to a number" and that wouldn't allow the initial sync to be completed.

Reproducible:

Reproduction Steps:

Comments:

**Comment by Chris-Petty** [comment]
I think the solution here should be a server side check: mobile sends app version, server checks the range it can handle (I think mSupply >= 4.00 is good for mobile >= 2.0.0). Servers with the end point can respond that you need a newer/older version of mobile if necessary. If there is no endpoint then mobile can just assume the server is too old.

**Comment by joshxg** [comment]
I think this should be closed
