### ISSUE TITLE
Customer requisition docs have finalised example rather than unfinalised

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#776]
http://docs.msupply.org.nz/mobile:user_guide2#customer_requisitions

The third image explains editing values, but uses an finalised requisition so cells don't appear editable and also the buttons are greyed out.

![image](https://user-images.githubusercontent.com/7684221/50501749-6ae5ff00-0abf-11e9-9dfb-7934fd964718.png)

**Comment by katherine-sussol** [comment]
Moved to https://docs.msupply.foundation/en:mobile:user_guide:customer_requisitions and now features clickable buttons!
![image](https://user-images.githubusercontent.com/65875762/118432790-9cfa6900-b72d-11eb-91be-5b1ace336a02.png)
