### ISSUE TITLE
Customer invoice > "Add master list items" adds items tablet store can't see

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#783]
Build Number: 2.2.0-rc0 ( probably exists earlier )

Description: 
![untitled](https://user-images.githubusercontent.com/7684221/50806260-bff50100-135a-11e9-97df-fb3aa7fc095b.png)

Here are a bunch of items in the customer invoice visible to the customer store, but not this store. So naturally there is no available stock

Reproducible: Yes

Reproduction Steps:
1. Create a customer invoice for a store with different item visibility than the store being worked on
2. See all the items that this store can't see and therefore has no available stock for

Comments:
Should only add the intersection of items between supplying store and customer name to the customer invoice I reckon.

**Comment by sworup** [comment]
@Chris-Petty This is the same case for demo stores items. In this case the store items are visible but would still show 0 stock.

![gna5r4eglo](https://user-images.githubusercontent.com/683452/50956140-12f9c000-14e3-11e9-9ec7-8754452286c0.gif)

**Comment by sworup** [comment]
@Chris-Petty what is the behavior we are looking for to solve this problem?

**Comment by ujwalSussol** [comment]
@Chris-Petty   I have explained the issue as i have understood .....

Store A
Master list A


Store B
Master list B


Customer C
master list C

If store A issue to issue stock to    Store B or Customer C,  we only need to show items that has an interaction of   "Master list A <>  Master list B"  or   "Master list A <>  Master list C"

**Comment by sworup** [comment]
@Chris-Petty if we are looking to take items that are common to both master-lists it should be `intersection` right?

![screen shot 2019-01-10 at 2 47 21 pm](https://user-images.githubusercontent.com/683452/50957645-dc25a900-14e6-11e9-8584-2683874c8084.png)

**Comment by Chris-Petty** [comment]
@ujwalSussol That's right, If `store A` makes a customer invoice for `store B`, "add master list items" should add only the items that are in **both** `master list A` and `master list B`.
