### ISSUE TITLE
Incoming sync sets cost price based on sell price on itemBatch

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#786]
**Build Number:**  Been like this for 2 years. Just everything. Today it's 2.2.0-rc0 though.

# Description

https://github.com/openmsupply/mobile/blob/6058be29f51630154f74dc37f2c796e72c850673/src/sync/incomingSyncUtils.js#L105
This line above shows sell price being used for cost price. If this is somehow intentional it needs a comment explaining it, but sure just looks like a small mistake.

Reproducible: Doesn't really affect anything I can think of.

Reproduction Steps:

Comments:

**Comment by joshxg** [comment]
# Testing
- [x] Incoming sync sets cost price based on cost price not sell price
