### ISSUE TITLE
Upgrade react-navigation from version 1.0.0-beta.11 to version 3.X.X (latest)

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#804]
# Description

React navigation in our application has been struck at version 1.0.0-beta.11 for a long time. After the said version, the developers changed the code bootstrapping and most of the code to a large extent and our application became no longer compatible for a version upgrade.

We need to change our code so that the latest version of react-navigation, v3.1.5 at the time of this writing, would work with our code.

**Comment by sworup** [comment]
Just found a bug, back button goes all the way back even if the navigation is 2-3 steps down. Will look into it.

**Comment by andreievg** [comment]
@sworup can you also check what happens when back button is pressed when a modal is open (i.e. selecting items in customer invoice)

**Comment by sworup** [comment]
@andreievg I noticed it after I checked in the code, back button does not work properly in all cases. Its because the goback method previously working was not working anymore so I used a global static method, that only took the page back to the main page. I will work on fixing this.

**Comment by andreievg** [comment]
@sworup cool, I've mentioned about the modal because it isn't working in master version also

**Comment by sworup** [comment]
I have pushed a more stable version of React-navigation 3 integration code to the PR. Please check. @andreievg @Chris-Petty 

> @sworup can you also check what happens when back button is pressed when a modal is open (i.e. selecting items in customer invoice)

The modal loads over the invoice with its top just coming below the navigation menu with the back button. The back button in this case, is the back button of the invoice (not the modal, modal does not have back button), pressing it would act like the back button of the single invoice and brings you back to the invoices' list.

**Comment by Chris-Petty** [comment]
@sworup I think it's better to discuss the PR on the PR.

**Comment by Chris-Petty** [comment]
Fixed in #805
