### ISSUE TITLE
Finalise button is not opening Finalise modal

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#806]
# Description

Finalise button for all the single items (invoices, stocktake etc.) does nothing when clicked. 

Previously it was validating if the invoice had no items or finalising and locking the invoice.

Reproducible: Yes

# Reproduction Steps

![n7nguhpkfg](https://user-images.githubusercontent.com/683452/52691906-664faa00-2f8a-11e9-8f4b-f5e77e7902b7.gif)

**Comment by sworup** [comment]
Probably introduced by ESLint autofix changes.

**Comment by joshxg** [comment]
# Testing
- [x] Everything can be finalized
