### ISSUE TITLE
Error message "undefined is not an object (evaluating item.batches)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#808]
Build Number: 2.2.0-rc0

Description: Syncing with primary server fails with message "undefined is not an object (evaluating 'item.batches')".

Reproducible: Yes.

Reproduction Steps: Sync mobile with a primary server with records of type `Stock_take_lines`.

Comments: Seems to be related to eslint updates related to arrow syntax.

**Comment by wlthomson** [comment]
@andreievg As the eslint updates we discussed also fix this issue, I'll include them in this PR. Sound good?

**Comment by wlthomson** [comment]
Fixed by #810. Closing.

**Comment by joshxg** [comment]
# Testing
- [x] Can sync mobile where incoming sync has a stock take line
