### ISSUE TITLE
[Ivory Coast] Create requisitions by program

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#815]
Epic:  sussol/org-issues#18

### Description:
Require functionality to create a requisition linked to a program

### Requirements:
- Creating a requisition should have the option to create a "program" requisition
- When these are linked, a user should not be able to add or remove items.
- Should require a period to be created (?)
- All the items in the program will have a requisition line related to the requisition

### Comments:
This has been implemented on desktop already issue [here](https://github.com/sussol/msupply/issues/2524).

#### TLDR of Desktops implementation:
- When a new requisition is to be created, *if there exists a `masterList` with `isProgram` [being added in this [issue](link here)*, prompt the user to create a `general` or `program` requisition. 
- The requisition is then populated with `requisitionLines` for each item in the `masterList`
- The user then selects the supplier and period after the requisition is created.

**I might be missing things here**

#### Thoughts on mobile implementation (from what I think andrei has described)

- When a user clicks create requisition and there exists a `masterList` with `isProgram = true`, a modal opens prompting if it is a `general` order or `program` order.
- If `general` order, nothing different.
- if `program` order - display a new modal prompting for:
    - supplier
    - program
    - period
    - order type
- Pre-populate the requisition with this data

#### things to note
- Period limitations on creating a requisition [ Ensuring multiple requisitions aren't created for a certain store/program in the same period.

Need more discussion on design and implementation. This is potentially a reasonable sized issue also, so could be broken down further once discussed and assigned a little further

**Comment by joshxg** [comment]
Thinking something like

![image](https://user-images.githubusercontent.com/35858975/54504333-181e3400-4998-11e9-82f3-e90d5a8ba765.png)

For stock takes by program and requisitions, using the existing components, the large radio buttons used in the stock takes page for normal or program based, and drop downs for Supplier, Program, Order type and period. Supplier always usable and the other three disabled/hidden if not a program order

**Comment by joshxg** [comment]
Or, something like this using the popup from creating a new stock take

![image](https://user-images.githubusercontent.com/35858975/54505012-038f6b00-499b-11e9-9ebd-90ec385a23d0.png)

Where the radio buttons are general/program and drop downs are for Supplier, program, order type and period.

**Comment by Chris-Petty** [comment]
I like the going with a new modal approach, making it consistent for both new requisitions and stock takes. 

**Requisition**
Seems good.
- Hasn't been mentioned, but suppliers would be reduced down to those using same program? Dunno if we can do this without `store` table if that's where tags will be!
- New modal 👍 agree with online ordering work flow direction
- If for program, lockdown add/remove items and other buttons?

**Stock take**
- I think reusing the modal from requisition approach is good (actually the same modal? May be more sensible to just have a very similar layout but different modal implemented).
- For general, would it direct to the old stock take editor page?
- As desktop isn't that locked down for programs either, should it go to editor page too for add remove items?

**Comment by joshxg** [comment]
>     * Hasn't been mentioned, but suppliers would be reduced down to those using same program? Dunno if we can do this without `store` table if that's where tags will be!

Currently we are just using any supplier to be chosen, similar to how entering a supplier works currently. I think this probably does need a second thought though on if this set of suppliers needs to be restricted in some way depending on the program. 

>     * If for program, lockdown add/remove items and other buttons?

Definitely

> **Stock take**

Have an issue here #816 for more specific stock take things

>     * For general, would it direct to the old stock take editor page?
 
My thoughts were that it would be less of a dialog, more of a page which slides/transitions to the next 'state' when a 'next' button is pressed (hard to explain exactly.. but like a slide show!) rather than the modal disappearing. Then it is just an intermediary state between clicking 'New requisition' or 'New stock take' which would appear if there are programs which exist in the DB (I have thoughts on implementation, I don't think it is very difficult, essentially a wrapping component which animates mounting/unmounting). 

This then makes it easier to transition into the online ordering work flow. Add a 'finalise' state/page, or any others in the future (regimen data for example). Then adding additional features such as a steps/progress bar.

>     * As desktop isn't that locked down for programs either, should it go to editor page too for add remove items?

I am working on adding a more 'locked down' version of requisition by program for desktop here https://github.com/sussol/msupply/pull/2782 - similar to the first example above.

**Comment by andreievg** [comment]
@joshxg, just to clarify some logic:

Display new modal on new requisitions, only if, at least one masterList associated with current store:
* isProgram
* has at least one matching storeTag

Will comment re stocktake in stocktake issue

Periods should be enforced as per desktop (we may need to add new columns to requisition list, showing program and period, if at least one requisition has period/program link)

**Comment by joshxg** [comment]
Summary so far:

Using a design similar to : https://github.com/openmsupply/mobile/issues/815#issuecomment-473754235

On clicking "New requisition" - the above page loads if there exists a masterList with `masterList.isProgram=True && masterList.programSettings.storeTags["My store tag"] = true`

Details are filled: Program - Supplier - Order type - period

Then the new requisition appears as is now, with adding/removing item buttons, supplier name etc etc not visible. Probably should also display the details entered in the previous page somewhere on the page

**Comment by DhanyaHerath** [comment]
### TESTING
- [x] No trace of this feature if making customer requisitions or if no programs defined.
- [x] When creating a requisition a modal appears with options for a general or program requisition
- [x] When creating a requisition, a process of steps from supplier, program, order type period must be followed to create a program requisition
- [x] The requisition is populated with items from that program
- [x] Creating a general order creates a normal requisition

Two small notes - I don't think these are bugs necessarily: 
1. If I re-click on a ddl after I've made a choice, that choice is lost when I open the ddl. So if I cancel out of the options modal without re-selecting an option, it gets re-set to the red arrow even though the option was selected originally. 
![image](https://user-images.githubusercontent.com/29744386/60404224-da69b200-9bfa-11e9-9db5-1956a363c051.png)

2. If I fill in all the details for a program requisition and then click the general requisition tab, all the information is lost when I go back to program requisition (possibly this was on purpose?) 

2.5. Sneaky third one just to say the lack of capitalization on the tabs makes me sad :-( 

These are tangents though, so I think this issue itself has passed build testing.

**Comment by joshxg** [comment]
Thanks! `1` and `2.5` have issues #1039 and #1040 - `2` is intentional. Could be improved with a refactor of the functionality which I hopefully get to do soon!
