### ISSUE TITLE
[Ivory Coast] Stock take reasons

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#817]
Epic:  sussol/org-issues#18

### Description:
*Reason: Term we have been using to apply a description of the reason why a value differs in the system. For example, a stock take line reported quantity differs from the snapshot quantity. If the snapshot quantity is 10 and a user enters 5, they have to enter a 'reason' - stolen, wastage etc.

Functionality to assign a reason to a stock take line.

### Requirements
- A stock take line **must** have a reason (From the reason table being synced in [issue](issue here) when the snapshot quantity != counted quantity.

#### TLDR Desktop implementation - sussol/msupply#2461 sussol/msupply#2544
- There is a table `Reason(ID, title, type, isActive)
    - only soft deleted, so isActive acts as a deletion.
    - type is `stocktakeLineAdjustmentReason` for stock take line reasons
    - title is the user defined name for the reason eg `Stolen`
- When a user enters a different value in the listbox for the counted quantity, a dialog appears (same as when you double click) requiring a user to enter a reason from a dropdown before it can be closed.
- If the user alters the value in the dialog which opens on double click, they cant move on until a reason is entered from a dropdown.
- The drop down holding the reasons has no values until snapshot != counted quantity

#### Suggestions for mobile
- Entering a counted quantity differing from the snapshot quantity (after losing focus) will open a modal to enter a reason.
- Clicking on the reason cell will re-open the modal

Seems very intrusive, but not sure of a better implementation due to relatively small real estate.

**Comment by joshxg** [comment]
Should be relatively simple. I think the "batch" details within the listbox is/will be to cluttered and also will probably lead to some messy code trying to enforce. Pretty simple to just use the stock take name popup

![image](https://user-images.githubusercontent.com/35858975/54505626-84e7fd00-499d-11e9-963c-6595599e25ee.png)

If you can imagine "Enter a reason" once snapshot quantity != actual quantity. There's also definitely room to shrink the last 3 columns also, to have a reasons column?

**Comment by Chris-Petty** [comment]
A higher effort suggestion:

Implement a stocktakeItemPage.js where you can edit batch level info. Navigation to it from `stocktakeEditPage` via a button in the expansion or an edit icon/button column on the right. In the new page there would be good space to have a table of batches and columns for reasons/comments.

If we go there an OK & NEXT equivalent button to go to the next item in the stocktake would be good. 

That said, possibly makes the enforcing reasons harder in this way as if you're working in the current stocktakeEditPage.

**Comment by joshxg** [comment]
@wlthomson @Chris-Petty @andreievg 

Summarizing:

After editing a stock take line (if (snapshot quantity != actual quantity & storeUsesReasons)), show a modal similar to that of choosing a supplier with:
- no search bar
- A default period selected/highlighted/top of list (what constitutes a default period is not finalized, arbitrary at the moment)
- Closes on selecting a period

This also will introduce removal of the stock take line expansion:
- turn this into a modal
- have a reason for each batch in this table, when clicking on that column, same modal/drop down as above would appear

Whoever is assigned should probably break this into a few chunks

**Comment by DhanyaHerath** [comment]
# TESTING
- [ ] When entering a value for a stock take **line** whose value differs from the snapshot quantity, a reason must be applied.
- [ ] Entering a value for a stock take **line** distributes the reason throughout the reasons where it is applicable
- [ ] When entering a value for a stock take **batch** whose value differs from the snapshot quantity, a reason must be applied.
- [ ] Returning the quantity of a **batch** to the snapshot quantity removes the reason for that batch
- [ ] Returning the quantity of a **line** to the snapshot quantity removes the reason for all batches
