### ISSUE TITLE
[Ivory Coast] Add MOS (months of stock) to requisitions

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#818]
Epic:  sussol/org-issues#18

### Description:

MOS for a particular item represents that item's quantity divided by average monthly consumption: `currentMOS = stockOnHand / AMC`. The max MOS is taken into account when making a requisition,  anything above this should not be allowed to order: `requestedMOS + currentMOS <= maxMOS`. 

Threshold MOS is used to identify which items to show on a requisition (mainly for emergency requisitions). Anything above this will be hidden, i.e. only show items which are below the required threshold: `currentMOS <= thresholdMOS`.

### Requirements:

Requisitions for stock should satisfy `requestedMOS <= maxMOS - currentMOS`. 

Items displayed for a requisition should satisfy `currentMOS <= thresholdMOS`.

**Comment by joshxg** [comment]
Essentially/quickly: If it is a program based requisition - use `MaxMOS` and `thresholdMOS` in `orderType` - use these to set the current MOS UI field and make this not editable. Have a threshold MOS field next to it somewhere which shows only on program based requisitions. Also a checkbox(?) for applying threshold MOS visibility

**Comment by DhanyaHerath** [comment]
# TESTING:

- [x] Clicking `Hide Over Stock` button on a program requisition will hide all of the items whose current stock on hand exceeds the threshold MOS set in the order type used to create the requisition
- [x] Clicking automatic order will set the quantities to order using the maxMOS for the order type used to create the requisition
Nb. 'Automatic Order' is only in general orders, program requisitions have 'use suggested amount' only - both work. 
It does confuse me a bit to have the toggle set to 'Hide overstock' when the requisition is finalised. If you only order overstocked items, it looks like an empty requisition. But that might be on purpose and I'm just easily confused?

**Comment by joshxg** [comment]
Thanks! Issue for here for the confusion: #1042
