### ISSUE TITLE
Item defaultPrice is synced incorrectly

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#820]
Build Number: 2.2.0

# Description

https://github.com/openmsupply/mobile/blob/9dbaf8a9f9115edc2583c3b23c715b81f34b4f8b/src/sync/incomingSyncUtils.js#L70

This uses buy_price. Buy_price field in mSupply is actually only for "service" items. The default sell price of an item is actually per store and stored on item_store_join. Ha.

## Expected behaviour
When syncing item_store_joins it should set the default price on the related item record based on 		`[item_store_join]default_price`.

## Reproducible
It's just wrong. Symptoms would be that no default price anywhere is actually correct. Main run on affect from that is stocktakes creating new item batches will set them up with erroneous sell/cost price. Could happen with supplier invoices, too.

## Comment:
Develop this on master, patch and release with v2.2.1

**Comment by Chris-Petty** [comment]
Fixed in #821

**Comment by joshxg** [comment]
# Testing
- [x] Item store join records set the default price of an item when synced
