### ISSUE TITLE
[IC][Requisitions][Stocktake] byProgramModal

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#823]
Epic: https://github.com/sussol/org-issues/issues/18
Related issues: #815 #816 

Description:
Require a modal for gathering details for a requisition and stock take by programs. Should be generic enough to cater to both use cases.

Full design details #815

**Comment by DhanyaHerath** [comment]
# TESTING
#### Requisition
- [x] The sequential steps work correctly
    - [ ] The step numbers are correct .. (1,2,3,4..) - _there are no sequence numbers_ 
    - [x] Each step is ticked as you step through the process
    - [x] When going back a step, the process is reset to the correct state
    - [x] When a step is unavailable, i.e. no periods, the interface clearly shows this
    - [x] All modals that appear resulting in a button press display the correct information

#### Stocktakes
- [x] Process steps display the correct state
- [x] Can type in a name and have it shown correctly

Not a bug as such, but seems inconsistent that if you have no programs you can create a stocktake without a name (and it will assign a name to it) but it's not possible to do so once you have programs associated.

#### All
- [x] Navigating between general and program types correctly display the right information
- [x] Navigating between general and program types correctly reset the state
