### ISSUE TITLE
[Laos] handle donor on incoming supplier transactions, itemBatches and customer invoices

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/mobile#832]
Build Number: 2.2.0

Description: Title says it all- Stock transfers coming in might have a donor- want to preserve this information so it can be reported on for transactions synced back to desktop.

Reproducible: Yes.

Reproduction Steps: As the fields don't exist in schema, I will go out on a limb and suggest doing a stock transfer to a mobile store then receiving it will create this problem.

Comments: Thanks ;-)

**Comment by joshxg** [comment]
# Testing
- [x] Retain donor details when syncing to and from mobile
