### ISSUE TITLE
Store pref "Show extra fields on requisitions" freezes mSupply 

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/mobile#833]
Build Number: 4.03 RC47 ish

Description: Reported by Ujwal. We want to show these extra fields for Côte d'Ivoire, but maybe don't want to use the "ordering cycle" and "allowable period" etc from this pref. 

Reproducible:expect so

Reproduction Steps: Set pref for store then create a new internal order with Ivory_coast customisation enabled

Comments: My gut feeling is to not have to have this pref turned on for Côte d'Ivoire - instead either make a separate pref that controls showing the extra info or show it irrespective of the pref if ivory_coast customisation is set?

**Comment by DhanyaHerath** [comment]
The current implementation uses the period start and dates for Côte d'Ivoire rather than using the fields defined through this pref (ie.  "ordering cycle" and "allowable period"). 

There was a bug in period schedules that meant the dates were stored oddly and was leading to massive queries - is it possible that they were using periods made before the changes? I can take a look anyway.

**Comment by andreievg** [comment]
@DhanyaHerath @craigdrown 
It looks like the issue happens for 'general' orders, where Ordering cycle is set to 0.

I suggest removing logic done for Cambodia (including First order, ordering cycle, allowable period prefs) and just using periods (if one is linked to requisition)

**Comment by DhanyaHerath** [comment]
@andreievg Do you mean remove the work done for Cambodia entirely, including the preference, and just default to using periods for everyone? Or just for Ivory Coast?

**Comment by andreievg** [comment]
@DhanyaHerath, yeah, just keep 'show extra information on requisition' pref.

I know that might seem like going backwards, but feel those other prefs/code will not be used anymore

**Comment by Chris-Petty** [comment]
@DhanyaHerath @andreievg server side merge done
