### ISSUE TITLE
[Vaccine Module][Schema Changes] - Introduce DB changes

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#838]
As per epic: https://github.com/sussol/org-issues/issues/23
Schema discussion: https://github.com/sussol/org-issues/issues/22
Sync changes blocked by: https://github.com/sussol/msupply/issues/2953

#### Description

Vaccine Module Development will require schema changes and sync changes

#### Schema Changes

`Item.doses` <- number

`TransactionBatch`

| Field Name         | Type     | mSupply Desktop Link (for sync) |
|--------------------|----------|---------------------------------|
| isVVMPassed        | boolean  | same                            |
| doses              | integer  | same                            |
| location           | Location | (FK) location_ID -> Location    |

`ItemBatch`

| Field Name        | Type              | mSupply Desktop Link (for sync)               |
|-------------------|-------------------|-----------------------------------------------|
| location          | Location          | (FK) location_ID -> Location                  |
| sensorLogs | SensorLog[] | SensorLogs (many) to ItemBatch (many) are linked through SensorLogItemBatchJoin |

`Location` <- Desktop name `Location`

| Field Name        | Type              | mSupply Desktop Link (for sync)                                                                      |
|-------------------|-------------------|------------------------------------------------------------------------------------------------------|
| id                | uuid(primary)     | ID                                                                                                   |
| description       | text              | description                                                                                          |
| code              | text              | code                                                                                                 |
| locationType      | LocationType      | (FK) type_ID -> Location_type                                                                        |
| temperatureBreach | TemperatureBreach | (FK) temperatureBreachID -> temperatureBreach                                                        |
|                   |                   | store_ID -> assign current store ID from Settings, and only integrate records with matching store_ID |

`LocationType` <- Desktop name `Location_type`

| Field Name         | Type          | mSupply Desktop Link (for sync) |
|--------------------|---------------|---------------------------------|
| id                 | uuid(primary) | ID                              |
| description        | text          | Description                     |
| minimumTemperature | float         | Temperature_min                 |
| maximumTemperature | float         | Temperature_max                 |
| customData         | text          | custom_data                     |

`SensorLog` <- Desktop name `sensorLog`

| Field Name  | Type        | mSupply Desktop Link (for sync)                                                                      |
|-------------|-------------|------------------------------------------------------------------------------------------------------|
| id          | UUID        | ID                                                                                                   |
| sensorID    | Sensor      | (FK) sensorID -> sensor                                                                              |
| locationID  | Location    | (FK) locationID -> location                                                                          |
| pointer     | integer     | same                                                                                                 |
| dateTime    | date        | date (date), time (time), needs to be converted to two fields, vice versa                            |
| value       | float       | same                                                                                                 |
| logInterval | integer     | same                                                                                                 |
| ItemBatches | ItemBatch[] | SensorLogs (many) to ItemBatch (many) are linked through SensorLogItemBatchJoin                      |
| isInBreach  | boolean     | same                                                                                                 |
|             |             | store_ID -> assign current store ID from Settings, and only integrate records with matching store_ID |

`Sensor` <- Desktop name `sensor`

| Field Name     | Type     | mSupply Desktop Link (for sync)                                                                      |
|----------------|----------|------------------------------------------------------------------------------------------------------|
| id             | UUID     | ID                                                                                                   |
| locationID     | Location | (FK) locationID -> location                                                                          |
| name           | text     | same                                                                                                 |
| macAddress     | text     | same                                                                                                 |
| batteryLevel   | float    | same                                                                                                 |
| temperature    | integer  | same                                                                                                 |
| lastConnection | date     | lastConnectionDate (date), lastConnectionTime (time) needs to be converted to two fields, vice versa |
|                |          | store_ID -> assign current store ID from Settings, and only integrate records with matching store_ID |

`TemperatureBreach`  <- Desktop name `temperatureBreach`
##### Table not needed, will use SensorLogItemBatchJoin

| Field Name | Type           | mSupply Desktop Link (for sync)                                                            |
|------------|----------------|--------------------------------------------------------------------------------------------|
| id         | uuid (primary) | ID                                                                                         |
| batches    | ItemBatch[]    | ItemBatch (many) to TemperatureLog (many) are linked via TemperatureBreachItemBatchJoin    |
| sensorLogs | SensorLogs[]   | SensorLogs (many) to TemperatureLog (one) are linked through SensorLogs.temperatureBreach  |

`TemperatureBreachItemBatchJoin` <- Desktop name `temperatureBreachItemLineLink`
##### Table not needed, will use SensorLogItemBatchJoin

| Field Name        | Type              | mSupply Desktop Link (for sync)               |
|-------------------|-------------------|-----------------------------------------------|
| id                | uuid (primary)    | ID                                            |
| itemBatch         | ItemBatch         | (FK) itemLineID -> itemLine                   |
| temperatureBreach | TemperatureBreach | (FK) temperatureBreachID -> temperatureBreach |

`SensorLogItemBatchJoin` <- Desktop name `temperatureBreachItemLineLink`

This table should store link between sensorLog and itemLine (for temperature breaches only)

| Field Name | Type              | mSupply Desktop Link (for sync) |
|------------|-------------------|---------------------------------|
| id         | uuid (primary)    | ID                              |
| itemBatch  | ItemBatch         | (FK) itemLineID -> item_line    |
| sensorLog  | TemperatureBreach | (FK) sensorLogID -> sensorLog   |

... to be finalised (check if anything is missing)

**Comment by joshxg** [comment]
Quite a lot of changes, needed this so I guess I'll leave it here :
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/35858975/55386908-f377ae00-558c-11e9-94d7-fa59b05b093d.png">

(I think/hope I've got everything in there)

Just to throw some more potential confusion, could just use a `hasBreached` boolean instead of `TemperatureBreach` on `SensorLog`?

Mainly playing devil's advocate/pushing the other side. I like an easy to work with DB, just seeing it without cycles and derived data can be helpful to double check and ensure that everything is needed.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/35858975/55387910-ca581d00-558e-11e9-9e11-39e0a07d03dc.png">

**Comment by andreievg** [comment]
Thumbs up on that last structure, apart from:
* sensor will need to have foreign key to location and tidy ups i.e. storeid on location is not needed

**Comment by andreievg** [comment]
@joshxg i've updated the issue description above.

Not happy about the naming of field 'customData' on location_type (but still sticking with json field rather then extra two tables)

**Comment by joshxg** [comment]
Cheers - I'll do the 4D issue first most likely

**Comment by andreievg** [comment]
@joshxg, umm, i know of a way to export/import newly created tables to 4D, I can do the schema changes  (Tomorrow).
