### ISSUE TITLE
[Vaccine Module][Custom Invoice][Doses] - Add doses to customer invoice

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#839]
As per epic: https://github.com/sussol/org-issues/issues/23

#### Description

Need to add new column ('doses used' or 'doses given') in Customer Invoice. This column should only be rendered when there is an item that is a vaccine in the invoice. 

If at this stage item does not already have a getter `isVaccine`, create one, it should `safely` check for item.categroy.name = 'Vaccine'.

Maximum doses that can be entered is quantity * item.doses.
Minimum doses should be quantity.
If item.doses = 1, then the cell should not be editable and doses should automatically be set to quantity.

What if quantity is reduces and doses were entered ?
What if quantity is increased and doses were entered ?
I think for now, we just reset the doses to Minimum doses as per above ?

Design:

![VM - Customer Invoices (1)-1](https://user-images.githubusercontent.com/26194949/55357256-12445900-5529-11e9-8020-4285325e8336.png)

**Comment by joshxg** [comment]
Are we rendering the column if the *invoice* contains a vaccine, or if there exists an item that is a vaccine? Adding items and adding a column seems like it would be a little odd, no?

**Comment by andreievg** [comment]
@joshxg the idea was to add column if invoice contains vaccine.

> Adding items and adding a column seems like it would be a little odd, no?
In my view it's fine, by the way most times supplier invoice with vaccines will come from EPI store with mainly vaccine items on it. And I would assume similar for customer invoice i.e. vaccine items would be on a seperate customer invoice to other.

**Comment by joshxg** [comment]
ok - will most likely use a `hasVaccines` transaction helper method - seems like a few use cases for it?
