### ISSUE TITLE
[Vaccine Module][VVM Component] - Add VVM component

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#840]
As per epic: https://github.com/sussol/org-issues/issues/23

#### Description

The VVM component has three states: null, false and true.

Once toggled from null, can't return to that state. 

It will be used in Supplier Invoices and Managed Vaccine Item pages.

One thing to be mindful of is if it's toggled to 'FAIL' there should be a modal asking what quantity failed VVM (and the batch would be split accordingly)

During our presentation and designs stage I did 'hack' and implementation of it, it's very rough but can be used as base (yeah I did name it VV`N` at the start, oops):

https://github.com/openmsupply/mobile/blob/vaccine-module-experimental/src/widgets/VVNToggle.js

And used here:
https://github.com/openmsupply/mobile/blob/7eb0052c7eaff6e4ff386322780069fdd5aa0017/src/pages/SupplierInvoicePage.js#L258-L270

![Screen Shot 2019-04-02 at 9 33 28 AM](https://user-images.githubusercontent.com/26194949/55357871-90552f80-552a-11e9-82f1-bf9a6e104cdd.png)
![Screen Shot 2019-04-02 at 9 32 11 AM](https://user-images.githubusercontent.com/26194949/55357811-71569d80-552a-11e9-9510-74b8eb43e8c2.png)
![Screen Shot 2019-04-02 at 9 32 16 AM](https://user-images.githubusercontent.com/26194949/55357815-73206100-552a-11e9-915e-9d95b4ce06fe.png)

**Comment by joshxg** [comment]
Just to make sure, date logic and `previousText` are leftovers?

Just a pure, controlled component with an `onToggle` so it has nothing to do with the modal. Generic with props which can control colors?

**Comment by andreievg** [comment]
Yeah modal will be separate I think and colors can be static for now, don't need to pass them as props
