### ISSUE TITLE
[Vaccine Module][Supplier Invoice] - Add VVM and Fridge assignment column

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#841]
As per epic: https://github.com/sussol/org-issues/issues/23

#### Description

Two columns to be added to Supplier Invoice, they should only be rendered if at least one item in invoice 'isVaccine'

If at this stage item does not already have a getter isVaccine, create one, it should safely check for item.categroy.name = 'Vaccine'.

If at this stage location does not have isFridge getter, create one, it should safely check for location.locationType.description = 'fridge' (ignore case, so turn to lower/upper case)

##### Fridge Selection

Default (first for now) fridge should be assigned to transactionBatches for all vaccines items. (Should this be done when page loads and when new vaccine item is added).

Modal pops up with all fridges when fridge cell is touched

##### VVM Status

use this component: https://github.com/openmsupply/mobile/issues/840 

When this component is toggled to false a modal should pop up asking what quantity to apply this to. The transactionBatch should be split accordingly.

###### DB Logic

Make sure itemBatch inherits transactionBatch.location 

Inventory adjustment to remove VVM fails from stock and record VVM passes should be created in seperate issue (https://github.com/openmsupply/mobile/issues/842)

#### Design

Had comments on the design, saying 'underscore look like a link, should have chevron'
fridge name + chevron instead of just underscore.

![VM - Supplier Invoice No Toggle (1)-1](https://user-images.githubusercontent.com/26194949/55358424-df4f9480-552b-11e9-8b57-2cd80f8b8754.png)

**Comment by joshxg** [comment]
- Are we happy with just using a modal similar to the one for reasons for fridge selection?
- What is the rubbish icon for?

**Comment by joshxg** [comment]
>Fridge Selection
>Default (first for now) fridge should be assigned to transactionBatches for all vaccines items. (Should >this be done when page loads and when new vaccine item is added).
>

If we assume all items being added to a supplier invoice are assigned the default fridge: Is there a use-case where an item (which is a vaccine) is on the supplier invoice which has not already been assigned some fridge?

**Comment by andreievg** [comment]
@joshxg 
> Are we happy with just using a modal similar to the one for reasons for fridge selection?

Yep
> What is the rubbish icon for? Is that just an indication, or is it a button to perform an event?

I was thinking it's indicative, so that user know this items will be discarded (through inventory adjustment) once supplier invoice is finalised.

> If we assume all items being added to a supplier invoice are assigned the default fridge: Is there a use-case where an item (which is a vaccine) is on the supplier invoice which has not already been assigned some fridge?

Currently when Supplier Invoice comes from supplier 'TransactionBatch' will not have a location associated. I am not 100% sure when to do the default fridge assignment, there is a possibility that 'TransactionBatch' item may not be synced yet, or category may not be synced when 'TransactionBatch' arrives, so was thinking to do the fridge associated when:
* Supplier Invoice is opened
* New item is added

**Comment by joshxg** [comment]
Ah, right. Makes sense and seems those two options are the best (only) solutions.

- Supplier invoice is opened: `Transaction` model helper `setVaccinesDefaultLocation`, run on `componentDidMount`
- New item is added: Could set a fridge in `createRecord` to a default fridge? (I like to keep as much logic out of the actual components as possible)

**Comment by andreievg** [comment]
Some helpful info as per VVM toggle use case: https://github.com/openmsupply/mobile/issues/842
