### ISSUE TITLE
[Vaccine Module][VVM Inventory Adjustment] - Create generic Inventory Adjustment helper for VVM statuses

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#842]
As per epic: https://github.com/sussol/org-issues/issues/23

#### Description

Both Supplier Invoices and Manage Vaccine Item will have VVM toggles. VVM Status needs to be recorded in inventory adjustment  `transactionBatch.isVVMPassed`.

We need generic way of creating these adjustments.

Input will be an array of transactionBatches (some with isVVMPassed = null)

**Comment by joshxg** [comment]
Thinking about supplier invoices first:

- When a lines VVM toggle is set to `Fail` - we  set `TransactionBatch.setTotalQuantity(ItemBatch.numberOfPacks)`
- Make the quantity column not-editable
- When toggle is set to `Pass`, enable editing - set value to (?)

The inventory adjustments will be made in the finalising code - collect each `TransactionBatch` with `vvmStatus = false`, and call the method with the list - adjusting each `ItemBatch.numberOfPacks = 0`

Does this seem correct so far?

**Comment by andreievg** [comment]
@joshxg 

When toggled to `Fail` there should be a modal that asks how many batches have failed. The batch is then split into `Fail` and `Pass`.

In term of being able to edit quantity, I think for now let's leave it editable for both cases.

When adding a new item to supplier invoice (which is not normal procedure, as most vaccine items would come from supplying store with supplier invoice), when new item is added the quantity will be 0, can disable (hide) VVM and fridge toggle (as if it was a normal item), until

 quantity is changed ?

> The inventory adjustments will be made in the finalising code - collect each TransactionBatch with vvmStatus = false, and call the method with the list - adjusting each ItemBatch.numberOfPacks = 0.

Yeah, there may even be some code to create inventory adjustments in stocktake code (not likely to be reusable, from memory it's deeply linked with stocktake,  but can give some insights re inventory adjustments in mobile)

**Comment by joshxg** [comment]
Each line in `SupplierInvoicePage` is a batch(If this is wrong stop reading here). 

If we have `3` lines for `ATROPINE 0.5% coll. fi/10ml` - we set one to `Fail`, a modal comes up and then we select `2` - we auto adjust the VVM toggle for two lines in the `SupplierInvoicePage`? 

Seems a little faster, less intrusive and easier to code to just let the user toggle for each batch? (Unless I'm mistaken about each line being a batch?)

**Comment by andreievg** [comment]
@joshxg 

Yeah this is deeper then issue, I think https://github.com/openmsupply/mobile/issues/841, talks about actual VVM component use, this inventory adjustment will just reduce batches that have VVM as `Fail` (should be reusable inventory adjustment to be used in Vaccine Item Page).

As per discussion on VVM toggle use, let's do by example:

Hepatitis Vial (batchName: '123456', quantity: 20, isVVMPassed: null) -> that means 20 vials of the same batch.

When VVM is toggled to 'Fail', a modal comes up asking what quantity (how many vials) have failed VVM ? The user puts in 5, and the line is split now:

Hepatitis Vial (batchName: '123456', quantity: 15, isVVMPassed: true) 
Hepatitis Vial (batchName: '123456', quantity: 5, isVVMPassed: false) 

Does that make sense ?

**Comment by joshxg** [comment]
Ah right, thanks

**Comment by joshxg** [comment]
@andreievg 

Have a branch for this [here](https://github.com/openmsupply/mobile/compare/vaccine-development...%23842-generic-inventory-adjustment-helper) - untested, I want the branch from #849 and don't want to merge it before review, but would be interested if it looks rightish?
