### ISSUE TITLE
[Vaccine Module][TemperatureBreach] - Populating TemperatureBreach table

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#844]
As per epic: https://github.com/sussol/org-issues/issues/23
This can be helpful to read: https://github.com/openmsupply/mobile/issues/838

#### Description

We need to record temperature breaches in a table (`TemperatureBreach`), it's not straight forward process but it reduces complexity and query time when displaying/calculating temperature breaches in other parts of the code/interface.

##### Tables

`TemperatureBreach` 

| Field Name | Type           | mSupply Desktop Link (for sync)                                                            |
|------------|----------------|--------------------------------------------------------------------------------------------|
| id         | uuid (primary) | ID                                                                                         |
| batches    | ItemBatch[]    | ItemBatch (many) to TemperatureLog (many) are linked via TemperatureBreachItemBatchJoin    |
| sensorLogs | SensorLogs[]   | SensorLogs (many) to TemperatureLog (one) are linked through SensorLogs.temperatureBreach  |

`TemperatureBreachItemBatchJoin` 

| Field Name        | Type              | mSupply Desktop Link (for sync)               |
|-------------------|-------------------|-----------------------------------------------|
| id                | uuid (primary)    | ID                                            |
| itemBatch         | ItemBatch         | (FK) itemLineID -> itemLine                   |
| temperatureBreach | TemperatureBreach | (FK) temperatureBreachID -> temperatureBreach |

`SensorLog.temperatureBreach`

`ItemBatch.temperatureBreaches[]`

####  Adding Sensor Log

... to be continued

**Comment by joshxg** [comment]
@andreievg closing this?
