### ISSUE TITLE
[Vaccine Module] Manage Vaccine Stock Page

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#858]
As per epic issue https://github.com/sussol/org-issues/issues/23

#### Description:

This page is opened: 
- When 'Manage Stock' button is pressed from the 'Vaccine Module' page. Should populate a list of vaccine items.
- When 'Show Stock' button is pressed from a Fridge view in 'Vaccine Module' page. Should populate a list of vaccine items, pre-filtered by that fridge

Requirements:
- Sortable by fridge (and item name/code(?))
- Has a 'manage'/'adjustment' column, which will navigate to the 'Vaccine item page' here #851 
- Displays the columns below

![image](https://user-images.githubusercontent.com/35858975/56085813-5414be00-5e9e-11e9-9aac-e8108a196ed3.png)

**Comment by joshxg** [comment]
@andreievg 

Filtering by item code/name as well as fridge:

Options as I see it:
1. Some sort of 'Filter by'. Could be large like other toggles on GenericTablePages, or smaller, underneath/to the side of the `SearchBar` component.

(rough example)
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/35858975/56085861-4f9cd500-5e9f-11e9-92dc-27401faf7279.png">
2. (Your suggestion) Two search bars. If we want to use placeholders this requires an update to the npm package (currently you can add a placeholder, but it does not have reduced opacity or anything and doesn't really look like a placeholder).

(rough example - imagine a placeholder or label next to the search bars!)
<img width="484" alt="image" src="https://user-images.githubusercontent.com/35858975/56085886-95f23400-5e9f-11e9-98ad-ef7ae777f833.png">

3. Button 'Filter by fridge' - opens `GenericChooseModal` to select a fridge which will filter the data.

**Comment by joshxg** [comment]
Temperature exposure:

Just pointing out this seems a little odd to be here rather than on the per batch page?

**Comment by joshxg** [comment]
#### Columns:
- Do we want an item code column?

#### Helpers:

- `get ItemBatch.hasBreach()` - Returns if this batch has been in a breach (hasBreach? Sounds weird)
- `get Item.hasBreach()` returns a bool if this item has a batch with `hasBreach` (Is this over the top?)
- `get Item.quantityInBreach()` - returns the sum of all `ItemBatch.totalQuantity` where `ItemBatch.hasBreach() === true`
- `get ItemBatch.exposureRange()` - returns an object `{min, max, average}` for the temperatures this `ItemBatch` has been in
- `get Item.exposureRange()` - returns an object `{min, max, average}` for all the `ItemBatches` for this `Item`

input on these?

**Comment by andreievg** [comment]
@joshxg
> Filtering by item code/name as well as fridge:

imo, filter by fridge drop down would be ideal (that can go in page info) + our usual filter to filter by item/code.

> Temperature exposure:
> Just pointing out this seems a little odd to be here rather than on the per batch page?

There is not much info we are displaying in this page, i think temperature exposure makes sense + fills in the space.

> Do we want an item code column?
Yes please

> Do we want sorting? 

I think we can leave this for now, By the way, there are not that many vaccine items (around 10 at the most).

>  get ItemBatch.exposureRange() - returns an object {min, max, average} for the temperatures this ItemBatch has been in 

I think {min, max} should be sufficient

> hasBatchInFridges(fridges) - passed an Array/Realm.Results of Location objects. this.batches.some() and searches if that batch is in one of the passed fridges (This is for manually typing a fridge name).
> hasBatchInFridge(fridge) same as above, but only searches for if there is a batch in a specific fridge

What do you think about Location.getItems(database) ?

Just thinking about work flow, when fridge is selected, number of batches, quantity, quantity in breach, exposure and breach need to change for all items. Will add another comment to talk about it

**Comment by andreievg** [comment]
the `flow` I was talking about:

* drop down (GenericChooseModal) in page info for fridge (with all fridges option) set's state.location (realm object?)
* refreshData, if !!state.location -> location.getItems(database)
* renderCell:
```
renderCell = (key, item) => {
    const { location } = this.location;

    // keys would be: getNumberOfBathces, getNumberOfBatchesInBreach, getExposureTemperature, hasBreach <- not a getter

    switch (key) {
      default:
        return item[key](location);
      case 'hasBreach': {
        const hasBreach = item.hasBreach(location)
        return // icon cell
      }
    }
  };
```

**Comment by andreievg** [comment]
in refreshData -> of course add item filter isVaccine

**Comment by andreievg** [comment]
and don't have to have keys with 'get' btw, can do
```
const mapping = { numberOfBatches: getNumberOfBatches }
...
 return item[mapping[key]](location);
```
