### ISSUE TITLE
[Vaccine Module] hazard point generation

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#886]
## Description

Helper method for vaccine modals and charts to generate hazard points for a breach.

## Requirements

Utility method to map each breach to an object containing breach and associated date and temperature data:

`extractBreachPoints(breaches)`

- `sensorLogs`: `sensorLog[]` (output from `aggregateLogs`, i.e. `[...minLines, ...maxLines]`)
- `breaches`: `sensorLog[[]]` (output from `extractBreaches`)

Returns an array with the following structure: 

```
[
  {
    date,
    temperature,
    sensorLogs: sensorLog[]
  }
]
```

**Comment by andreievg** [comment]
I think this method needs to take the following params: (result of `extractBreaches`, result of aggregateLogs)

And result is correct, with breaches being one of the breaches from extractBreaches, and date/temperature a data point from aggregateLogs

**Comment by andreievg** [comment]
actually the return, instead of `breaches`: should just be `sensorLogs`

**Comment by andreievg** [comment]
@wlthomson i've added this method, was in a rush
