### ISSUE TITLE
[Ivory Coast] add lead time to desktop

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#887]
## Description

Desktop currently uses a suggested quantity formula based on "lead time".

See https://github.com/sussol/msupply/issues/2971.
See https://github.com/sussol/msupply/issues/2930

## Requirements

Add "lead time" customisation to mobile pricing for IC.

**Comment by joshxg** [comment]
# Testing
- [x] Lead time is used in suggested quantity for program requisitions
