### ISSUE TITLE
localisation for program based stocktakes/requisitions model (ByProgramModel)

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#889]
Build Number: 2.2.0-RC

Description: IC customisations. ByProgramModal.js needs to use localisation

Reproducible: Yes

**Comment by DhanyaHerath** [comment]
### Testing
Might have done something wrong here because nothing seems translated: 
![Screenshot_2019-07-01-12-36-36-594](https://user-images.githubusercontent.com/29744386/60406445-03de0a00-9c0a-11e9-9067-856a56c29ed3.jpeg)

**Comment by joshxg** [comment]
Thanks! New issue for this here https://github.com/openmsupply/mobile/issues/1041
