### ISSUE TITLE
[Ivory Coast] Requisition made after cancelling supplier modal

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#924]
Description:

Cancelling the supplier modal for a requisition creates the requisition anyway

Reproducible:
yes?

Reproduction Steps:
1. Go to supplier requisitions
2. Click new requisition
3. cancel the modal
4. see your requisition

Comments:
`onNewRequisition` method is called on both selecting a supplier and cancelling the modal. Should cancel if no parameters are passed, however it is currently passed the event object, which makes the conditional return true, not closing the modal

**Comment by DhanyaHerath** [comment]
### Testing - passed
- [x] Clicked new requisition, clicked around lots, cancelled out of the modal - no requisition was created.
