### ISSUE TITLE
IC Creating a general supplier order : The App crashes.

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/mobile#928]
Build Number: mSupplyMobile-26-4-19-3.apk

Description:
For Ivory Coast, Creating a program order works fine, But normal supplier order fails. 

Reproducible:
Tested on the client1.msupply.org data.

Login :  Do New Requisition > Supplier >  Choose a supplier   
Click OK and the mSupply app on the Lenova crashes. 

Reproduction Steps:

Comments:

**Comment by joshxg** [comment]
@ujwalSussol 

I cannot reproduce this on any emulator. Can I please have the exact specs of the tablets this is crashing on? 

- Android version
- Tablet modal (and any processor details, if you have any)

Also if you could direct me toward details for using the demo servers, that would be great. Thanks

**Comment by joshxg** [comment]
# Testing
- [X] Creating a general requisition doesn't crash the app
