### ISSUE TITLE
Adding program list to mobile store causes unhandled promise rejection warning

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#945]
Build Number: 2.3.0-rc0 develop

Description:
If you change the master lists on the mobile store to include a program-list, it rejects some promise. 

![image](https://user-images.githubusercontent.com/7684221/56943466-b5fa4680-6b73-11e9-83a0-4017c94dee4d.png)

Reproducible: yes

Reproduction Steps:
1. Have a mobile device with no program list
2. Add a program list to its store
3. sync
4. In dev you'll get an unhandled promise rejection

**Comment by Chris-Petty** [comment]
As from #972 bugsnag report:
![image](https://user-images.githubusercontent.com/7684221/57598202-5d30a200-75a6-11e9-8167-cd882441fd2f.png)

**Comment by joshxg** [comment]
Closed by #1069

**Comment by wlthomson** [comment]
## TESTS

- [x] Can't replicate this issue on latest build.
