### ISSUE TITLE
[Ivory Coast] Fields disabled/enabled in incorrect state 

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#946]
Description:

- Couple of fields are editable during finalized transactions
    - i.e reason in a finalized stocktake
- Couple of fields are disabled incorrectly - e.g. a reason for a stocktake line when it has a reason already (can't change a reason)

**Comment by Chris-Petty** [comment]
Fixed in #944

**Comment by DhanyaHerath** [comment]
# TESTING

- [x] Clickable things are not clickable when finalized [i.e. adding items, changing cell values, comments etc]
- [x] Things that should still be clickable (while unfinalised, eg. changing a reason) are clickable
