### ISSUE TITLE
Can make program requisition to own store

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#949]
Build Number: 2.3.0-rc0

Description: Can select your own store when making a program requisition, requesting stock from yourself.

Reproducible: Yes

Reproduction Steps: Should be obvious

Comments: Similar to #699 , maybe inspire solution from that.

**Comment by joshxg** [comment]
@Chris-Petty I just want to double check - the query for suppliers is correct for requisitions? Other than this bug obviously, there are no other restrictions we should have in place for this?

**Comment by Chris-Petty** [comment]
Yea seems fine other than this.

**Comment by Chris-Petty** [comment]
Fixed in #967

**Comment by DhanyaHerath** [comment]
### Testing 
Own store didn't show up in supplier drop down list
