### ISSUE TITLE
Customer requisition finalisation crash

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#950]
Build Number: 2.3.0-rc0 dev+apk

Description: 
![image](https://user-images.githubusercontent.com/7684221/57004428-0e3c5180-6c23-11e9-8867-3cd2b58bb4f2.png)

Reproducible: yes

Reproduction Steps:
1. receive a customer requisition
2. enter a value
3. finalise it
4. some loading spinner and a RSoD (in dev, crash in apk)

Comments: There were items in the customer requisition that my store didn't actually have visible, but were visible in the requisition regardless.

**Comment by Chris-Petty** [comment]
Fixed in #951

**Comment by joshxg** [comment]
# Testing
- [x] Doesn't crash when finalizing a customer requisition

There was some strange spacing issue with the string in the modal. Not 100% sure why but it's annoying. New issue here #1036
