### ISSUE TITLE
Opening requisitions requisitions crashes app ('undefined' custom data)

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#956]
Build Number: 2.3.0-rc0

Description: When you open older requisitions or any that have synced from server (initialisation) the app will crash with an error:
![image](https://user-images.githubusercontent.com/7684221/57054895-925a0c00-6ceb-11e9-897a-45ffac87aff1.png)

mSupply server will send the string `'undefined'`, this would get stored as such rather than as `null` in what is an optional field in mobile. When null checking the string 'undefined' is true. Then we try parse that string throughout the app.

Reproducible: Yes

Reproduction Steps: 
1. Create a general requisition (no program)
2. sync
3. clear app data
4. initialise
5. Try open the requisition, have a bad time

Comments: Possibly related to promise rejection here #945

**Comment by Chris-Petty** [comment]
Fixed in #957

**Comment by joshxg** [comment]
# Testing
- [x] Opening requisitions which have synced from the server do not crash the app
