### ISSUE TITLE
Initialisation loses all details of a stocktake

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#958]
Build Number: 2.3.0-rc0 dev, single user interpreted 4.03.00-RC79

Description:
When you initialise an existing store, you lose all the the details of stocktakes. Either server isn't syncing them out or they're all breaking on incomingSyncUtils.
![image](https://user-images.githubusercontent.com/7684221/57113648-980e2b00-6d99-11e9-96d5-4837e280fa53.png)

Server actually has the stocktakes:
![image](https://user-images.githubusercontent.com/7684221/57113543-27670e80-6d99-11e9-9bf1-a56fd00f0135.png)

Reproducible: Yes

Reproduction Steps: 
1. Create a stocktake, give it a name, comment, some items and counts
2. Finalise
3. Sync to server
4. Clear app data
5. initialise store on tablet
6. See stocktakes have placeholder details

Comments:

**Comment by Chris-Petty** [comment]
Should have done this before merging develop into master for 2.3.0. Whoops. (#959)

**Comment by Chris-Petty** [comment]
Fortunately I'm pretty sure this is a serverside bug.

**Comment by DhanyaHerath** [comment]
### Testing 
* Stocktakes are there and good
