### ISSUE TITLE
General stocktake default name "undefined"

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#960]
Build Number: 2.3.0 master

Description:
General stocktake can get a name in format "undefined -  - <currentDate+Time>"

Reproducible: yes

Reproduction Steps:
1. Go to general tab when making a new stocktake
2. Tap field then hit keyboard done to dismiss
3. Can proceed without name
![image](https://user-images.githubusercontent.com/7684221/57210291-39aeaa00-7030-11e9-9d95-fd80ee44ba7b.png)
4. Stocktake name gets messed up 
![image](https://user-images.githubusercontent.com/7684221/57210312-4d5a1080-7030-11e9-8fff-4a7210da9e7c.png)

Comments:

**Comment by joshxg** [comment]
# Testing
- [x] Default name for a stocktake is not undefined (And has a correct name Stocktake - date)
