### ISSUE TITLE
Stocktake program dialog should not show if no programs

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#962]
Build Number: 2.3.1

Description: Stocktake program dialog shows when there are no programs to choose from. This disrupts old workflows for sites without programs.

Reproducible: Yes

Reproduction Steps: Create stocktake on site with no programs.

Comments:

**Comment by Chris-Petty** [comment]
Possibly related #945

**Comment by joshxg** [comment]
Fixed in #963

**Comment by joshxg** [comment]
# Testing
- [x] Program dialog only shows when there are programs defined for a store
