### ISSUE TITLE
On stocktake, after entering expiry date, the reason window is displayed

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#969]
Build Number: The one Ivory Coast is working on

Description: When taking a stocktake, some deployment team have mentioned that after putting the expiry date and getting out of the field, the reason window pop up. Some also complained that when entering the batch number, the numeric keyboard hides the field(It might be just the tablets)

Reproducible: I dont think that it happens to all the team. 

Reproduction Steps: go and do a stocktake, enter the reason, batch number and expiry date and try to get out of the field an the window to add a reason appears again

Comments: Did no try it myself

**Comment by Chris-Petty** [comment]
Fixed in #970

**Comment by joshxg** [comment]
Will be tested with #817
