### ISSUE TITLE
Error in MainActivity

### ISSUE THREAD

**Issue by sussol-invoices** [openmsupply/mobile#973]
## Error in mSupply Mobile

**Error** in **MainActivity**
ENOENT: no such file or directory, open '/storage/emulated/0/Download/mSupplyMobile_data/msupply-mobile-data.realm'

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cdaa7b3d346e00019df0d10?event_id=5cdaa7b3003a003bc70a0000&i=gh&m=ci)

## Stacktrace

    index.android.bundle:21 - h

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cdaa7b3d346e00019df0d10?event_id=5cdaa7b3003a003bc70a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by joshxg** [comment]
Closed due to development issue
