### ISSUE TITLE
TypeError in MainActivity

### ISSUE THREAD

**Issue by sussol-invoices** [openmsupply/mobile#974]
## Error in mSupply Mobile

**TypeError** in **MainActivity**
TypeError: null is not an object (evaluating 'this.item.batchesWithStock')

This error is located at:
    in p
    in s
    in Connect(s)
    in Unknown
    in v
    in RCTView
    in f
    in RCTView
    in f
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in f
    in b
    in y
    in L
    in RCTView
    in h
    in C
    in k
    in v
    in P
    in Unknown
    in Connect(Component)
    in RCTView
    in n
    in Connect(n)
    in s
    in c
    in E
    in RCTView
    in RCTView
    in c

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cdaf41ac3698e0019da9844?event_id=5cdaf41a0039ef67320c0000&i=gh&m=ci)

## Stacktrace

    index.android.bundle:848 - get

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cdaf41ac3698e0019da9844?event_id=5cdaf41a0039ef67320c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by joshxg** [comment]
Either a `StocktakeItem` or `TransactionItem` without a related `Item`? Seems odd - `Item` is not an optional field for those classes.

@Chris-Petty any ideas?

**Comment by sussol-invoices** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **MainActivity**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cdaf41ac3698e0019da9844?event_id=5cdaf8e10039f99e66ec0000&i=gh&m=fx)

**Comment by Chris-Petty** [comment]
My tendency is to close bugsnag issues that are in dev releases, ideally they shouldn't be in the wild and I can't keep track of if we've fixed them already. It'll reopen this issue if the event occurs in a newer release.

![image](https://user-images.githubusercontent.com/7684221/57736038-b6a9e580-76fa-11e9-814e-150bc271bb2d.png)
