### ISSUE TITLE
Cambodia Mobile: Threshold and MAX mos of the program in tablet is showing different than in dekstop

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#988]
Build Number:2.3.3

Description:While trying to make supplier requisition and choosing program the max and threshold mos for the order type  is showing different than its in desktop

Reproducible: Yes

Reproduction Steps: Create new supplier requisition. Choose a order type there we can see the max mos and threshold mos.

Comments:  Prorgam: Malaria, For Tag: OD
![SeenInTabletINCambodaiDatafile](https://user-images.githubusercontent.com/18479204/57926136-3508b200-78ca-11e9-8c8b-abd9817c72a4.jpg)
![InTestServerOfCambodia](https://user-images.githubusercontent.com/18479204/57926215-713c1280-78ca-11e9-919b-42e82ed7b271.png)

**Comment by joshxg** [comment]
@anildahalsussol is the picture incorrect here?

**Comment by anildahalsussol** [comment]
@joshxg : yah sorry the first one is wrong. Now i have uploaded right one.
![SeenInTabletINCambodaiDatafile](https://user-images.githubusercontent.com/18479204/57992476-0f4ef900-7ad4-11e9-92be-f0214caa5650.jpg)

**Comment by joshxg** [comment]
@anildahalsussol - Do you mean Ivory Coast?

**Comment by wlthomson** [comment]
@anildahalsussol Cambodia doesn't currently use mobile. Ivory Coast should be the only place program functionality is being used. Is this an incorrect label?

**Comment by anildahalsussol** [comment]
@wlthomson :  I was confused that i thought cambodia will also use Tablet. So I tested with cambodia datafile. Thus I labelled it cambodia. So we can labelled it as  Ivory Coast. Sorry

**Comment by Chris-Petty** [comment]
@anildahalsussol As at the moment this functionality is just going to be limited to Ivory Coast then it only really makes sense to relate it to them. That said, nothing on mobile is behind a customisation code, so if you can reproduce something it's good to do it with demo data if possible.

**Comment by Chris-Petty** [comment]
@wlthomson @anildahalsussol just to be sure, don't share a copy of the Cambodia datafile on a public repo! Reproduction steps should include configuration steps required. The images in this case seem to have enough detail in my eyes.

**Comment by wlthomson** [comment]
> @wlthomson @anildahalsussol just to be sure, don't share a copy of the Cambodia datafile on a public repo! Reproduction steps should include configuration steps required. The images in this case seem to have enough detail in my eyes.

The reason I've asked for a data file is that I couldn't replicate this with a data file based on these images/steps. I wasn't expected an active data file from a site, just a demo data file that demonstrated the problem. I'm happy to replicate without a data file; the reason I ask is that I think this could be related to an older data file.

**Comment by wlthomson** [comment]
> @wlthomson @anildahalsussol just to be sure, don't share a copy of the Cambodia datafile on a public repo! Reproduction steps should include configuration steps required. The images in this case seem to have enough detail in my eyes.

Good point! That wasn't what I was asking for but I can see why you were concerned.

To clarify, the reason I'm asking for a data file is that I can't replicate this with a new data file based on these steps. I'm not asking for an active data file from a site, just a demo data file that demonstrates the problem. I'm happy to replicate without a data file; but as I can't replicate this directly, I'm thinking there's a possibility that this could be a compatibility issue related to an old data file.

**Comment by joshxg** [comment]
@anildahalsussol @wlthomson 

I haven't been able to recreate this bug, I'm not sure if it's been fixed since this occurred or there was another problem. Going to close, please let me know if this is still reproducible!
