### ISSUE TITLE
Crash on sorting by column "SUPPLIER" on Supplier Invoices Page

### ISSUE THREAD

**Issue by sussol-invoices** [openmsupply/mobile#989]
This I suspect is because Realm (or at least the version we run) doesn't like sorting by getter fields, only schema fields.

Need to add otherPartyName to sort by sortDataType 'string' here:
https://github.com/openmsupply/mobile/blob/master/src/pages/SupplierInvoicesPage.js#L118-L125

## Error in mSupply Mobile

**Error** in **MainActivity**
Error: Cannot sort on key path 'otherPartyName': property 'Transaction.otherPartyName' does not exist.

This error is located at:
    in p
    in f
    in p
    in s
    in Connect(s)
    in Unknown
    in v
    in RCTView
    in f
    in RCTView
    in f
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in f
    in b
    in y
    in L
    in RCTView
    in h
    in C
    in k
    in v
    in P
    in Unknown
    in Connect(Component)
    in RCTView
    in n
    in Connect(n)
    in s
    in c
    in v
    in RCTView
    in RCTView
    in c

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cdea145fdfa510019f0e237?event_id=5cdea1450039f41b68690000&i=gh&m=ci)

## Stacktrace

    src/utilities/sortDataBy.js:36 - sortDataBy
    src/pages/SupplierInvoicesPage.js:127 - refreshData

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5cdea145fdfa510019f0e237?event_id=5cdea1450039f41b68690000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Reproduced by sorting on supplier name in supplierInvoices page

**Comment by Chris-Petty** [comment]
Interestingly, this bug would have existed ever since the column was added almost 2 years ago lol.
