### ISSUE TITLE
Add a column for packsize for stocktake msupply mobile

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#991]
Build Number: 2.3.3

Description: Adding a column for packsize for stocktakes

Reproducible: yes

Reproduction Steps: 

Comments: They want to have a packsize to help the user remember to count the stocktakes in terms of unit of 1.

**Comment by alainsussol** [comment]
Closing. False alarm !!!

**Comment by alainsussol** [comment]
It was not a false alarm. They told me that it has been fixed but they were mistakenly looking at the requisition window. So they still would like an extra column in the stocktake window because the user still makes the mistakes of counting their stocktake in packsize greater than one rather than in unit o dispensation which is one

**Comment by wlthomson** [comment]
@alainsussol Mobile always uses pack sizes of 1. Could you clarify why you would want this?

**Comment by wlthomson** [comment]
@alainsussol @craigdrown @andreievg

I can see why it could be confusing for users who may assume that pack sizes will be consistent in desktop and mobile, but given that the column of `packSize` will always be a column of 1s, it seems like it this might be a bit of an unnecessary use of table space?

**Comment by Chris-Petty** [comment]
@alainsussol @wlthomson This seems to be more of a training issue in my opinion, with some item configuration woes potentially. 

Mobile always for all items has a pack size of 1. Certain items come in bulk containers, such as say 2500 tablets of paracetamol 500mg or 2.5L of toluene. The central warehouse may think of these as as 1 item, but they need to be considered as a larger pack if they aren't given out at the bulk volume.

1 container of 2500 tablets should be 1 pack of 2500 units (tabs in this case).
1 bottle of 2.5L should be 1 pack of 2500mL.

If the central warehouse does this, then mobile can dispense based on units. This may require some setup of default pack size centrally and training around what that actually means for warehouse staff dealing with incoming stock. Mobile users should be trained that they should always deal with the smallest unit by default.

The alternative is to treat containers as the base unit (bad practice as I understand it!). Working like this, mobile users would treat opening a container (no matter how much it contains) as consuming 1 of the item. This will fuzzy up their consumption data, though. In the instance of 2500 tablets in a container you would lose detail between each container. AMC may become ineffective depending on the actual level of consumption if they use less than a container in a given period.

**This should extend to blister packs.** If they dispense a blister pack of 10 tablets at a time, they should be recording an amount based total tablets, i.e. n*10 tablets. Same if it's a box filled with blister packs of tablets. Still a training issue. Adding a column to mobile isn't the way to get around this in my opinion when our screen realestate is already very limited.

**Comment by alainsussol** [comment]
@Chris-Petty @wlthomson 
I understand your point about training and I agree with it. The trainers tried to reinforce the idea of using the dispensation unit (which is 1) for stocktake during the training. However, there is still some confusion amidst the staff that uses mobile due to the item description which often says something like box of 100 gloves so if they have 10 boxes, Many have the reflex to put a quantity of 10 rather than a quantity of  1000 (10*100) . This was suggested as a way to remind staff to use dispensation unit whatever the item description is saying. I think they found this an important tool to help their staff do the right thing to avoid stock mismanagement. If we don't want to add an extra column maybe we can propose an alternative like changing the title of the quantity column to something like "quantity in dispensing unit" or a warning before starting the stocktake that tells you to enter all quantities in dispensing unit. What do you think ?

**Comment by Chris-Petty** [comment]
@alainsussol Ah gloves is a classic one. That was one that Cook Islands had trouble with as well and I think they went with the box being the smallest denominator. High enough consumption to be OK I'd hypothesise, and a pain to enter into mobile every time a pair is used! But this only works if they only use one pack size of that particular glove (explained more below).

I think for most items, particularly medicines, pack size shouldn't be in the name. The pack size of the batch is where that should be handled. If you have paracetamol 10pack and 200pack, you don't really want to handle that as separate stock items with separate reporting. You can only get away with it if you only ever have the one pack size. Gloves is a tricky edge case, as often there is only ever the one pack size (100), so using that as the base unit isn't unheard of.

The most important thing is for their staff to agree on the how they're doing it. If everywhere does it by the box but one place starts doing it by the glove, that one place is going to receive a lot of boxes!
