### ISSUE TITLE
Bugsnag:  crash "Text strings must be rendered within a component"

### ISSUE THREAD

**Issue by sussol-invoices** [openmsupply/mobile#996]
## Error in mSupply Mobile

**Error** in **MainActivity**
Invariant Violation: Text strings must be rendered within a <Text> component.

This error is located at:
    in RCTView
    in RCTView
    in RCTView
    in RCTView
    in RCTView
    in RCTView
    in p
    in f
    in p
    in s
    in Connect(s)
    in Unknown
    in v
    in RCTView
    in f
    in RCTView
    in f
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in f
    in b
    in y
    in L
    in RCTView
    in h
    in C
    in k
    in v
    in P
    in Unknown
    in Connect(Component)
    in RCTView
    in n
    in Connect(n)
    in s
    in c
    in v
    in RCTView
    in RCTView
    in c

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5ce5820e95cd1e00198a0ef6?event_id=5ce5820e0039f36e98ae0000&i=gh&m=ci)

## Stacktrace

    node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:35 - invariant

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5ce5820e95cd1e00198a0ef6?event_id=5ce5820e0039f36e98ae0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
There is an error `No property 'id' on object of type 'Setting'` just before, but that may just be a warning from #945. Otherwise appears to happen on resume, though in development I think I have seen the RSoD with this error when opening the requisitions page from the main screen.

**Comment by joshxg** [comment]
Hm, what does `happen on resume` mean?

**Comment by Chris-Petty** [comment]
@joshxg As in they put the app in background, then opened it again. Just going off the bugsnag trace. Could be totally unrelated.
