### ISSUE TITLE
Bugsnag: Crash on create new program requisition

### ISSUE THREAD

**Issue by sussol-invoices** [openmsupply/mobile#999]
## Error in mSupply Mobile

**Error** in **MainActivity**
Value 'NaN' not convertible to a number.

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5ce69144f72a31001ca41fd7?event_id=5ce691440039ef3f28be0000&i=gh&m=ci)

## Stacktrace

    src/database/UIDatabase.js:149 - value
    src/database/utilities/createRecord.js:150 - createRequisition
    src/database/utilities/createRecord.js:393 - createRecord
    src/pages/SupplierRequisitionsPage.js:92 - 
    src/database/UIDatabase.js:157 - readFileGeneric
    src/pages/SupplierRequisitionsPage.js:83 - onNewRequisition
    src/widgets/modals/ByProgramModal.js:124 - onConfirm

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5ce69144f72a31001ca41fd7?event_id=5ce691440039ef3f28be0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Seems possible to get the value NaN trying to be written to database.

**Comment by joshxg** [comment]
Did you look into this already? What field was trying to be set to NaN?

**Comment by joshxg** [comment]
# Testing
- [x] No NaN error occurs when creating a program requisition

#### Note: This will get caught again if it occurs on 2.3.4, so marking as a success
